"""AI providers package.

Exposes the abstract provider interface and the provider registry. Concrete
backends (DeepSeek, OpenAI, Claude, Gemini, local) live in sibling modules and
inherit from ``BaseProvider``.
"""

from pr1me.providers.audio import (
    AudioError,
    AudioMixer,
    AudioMixError,
    AudioMixRequest,
    AudioProvider,
    AudioRender,
    AudioTimeoutError,
    FFmpegAudioMixer,
    build_audio_backend,
    build_mix_command,
    build_mix_filter,
)
from pr1me.providers.base_provider import (
    BaseProvider,
    Completion,
    CompletionRequest,
    Message,
    NoopProvider,
    StructuredCompletion,
    Usage,
)
from pr1me.providers.comfyui import (
    ComfyUIExecution,
    ComfyUIOutputImage,
    ComfyUIProvider,
    ComfyUIQueueResponse,
    ComfyUIRender,
    ComfyUITimeoutError,
    inject_variables,
)
from pr1me.providers.deepseek import DeepSeekProvider
from pr1me.providers.registry import ProviderRegistry
from pr1me.providers.video_renderer import (
    FFmpegVideoRenderer,
    RenderSegment,
    VideoRender,
    VideoRenderer,
    VideoRendererProvider,
    VideoRenderError,
    VideoRenderFailure,
    VideoRenderRequest,
    VideoRenderTimeoutError,
    build_render_backend,
    build_render_command,
    mp4_duration,
)
from pr1me.providers.voice import (
    HTTPVoiceBackend,
    VoiceBackend,
    VoiceError,
    VoiceProvider,
    VoiceRender,
    VoiceSynthesisError,
    VoiceSynthesisRequest,
    VoiceTimeoutError,
    wav_duration,
)
from pr1me.providers.youtube import (
    HTTPYouTubeBackend,
    YouTubeAuthError,
    YouTubeBackend,
    YouTubeProvider,
    YouTubeProviderError,
    YouTubePublishResult,
    YouTubeTimeoutError,
    YouTubeUploadError,
    YouTubeUploadRequest,
    build_youtube_backend,
    youtube_category_id,
)

__all__ = [
    "AudioError",
    "AudioMixError",
    "AudioMixRequest",
    "AudioMixer",
    "AudioProvider",
    "AudioRender",
    "AudioTimeoutError",
    "BaseProvider",
    "ComfyUIExecution",
    "ComfyUIOutputImage",
    "ComfyUIProvider",
    "ComfyUIQueueResponse",
    "ComfyUIRender",
    "ComfyUITimeoutError",
    "Completion",
    "CompletionRequest",
    "DeepSeekProvider",
    "FFmpegAudioMixer",
    "HTTPVoiceBackend",
    "Message",
    "NoopProvider",
    "ProviderRegistry",
    "StructuredCompletion",
    "Usage",
    "VoiceBackend",
    "VoiceError",
    "VoiceProvider",
    "VoiceRender",
    "VoiceSynthesisError",
    "VoiceSynthesisRequest",
    "VoiceTimeoutError",
    "FFmpegVideoRenderer",
    "RenderSegment",
    "VideoRender",
    "VideoRenderError",
    "VideoRenderFailure",
    "VideoRenderRequest",
    "VideoRenderTimeoutError",
    "VideoRenderer",
    "VideoRendererProvider",
    "build_audio_backend",
    "build_mix_command",
    "build_mix_filter",
    "build_render_backend",
    "build_render_command",
    "build_youtube_backend",
    "inject_variables",
    "mp4_duration",
    "wav_duration",
    "youtube_category_id",
    "HTTPYouTubeBackend",
    "YouTubeAuthError",
    "YouTubeBackend",
    "YouTubeProvider",
    "YouTubeProviderError",
    "YouTubePublishResult",
    "YouTubeTimeoutError",
    "YouTubeUploadError",
    "YouTubeUploadRequest",
]
