"""PR1M3 Labs knowledge base taxonomy.

400 engineering topics curated for the PR1M3 Labs channel niche:
3D printing, additive manufacturing, and practical engineering.

Entry shape: (topic, difficulty, subcategory, keywords, search_intent)
- difficulty: "B" (beginner), "I" (intermediate), "A" (advanced)
- keywords: ";" separated search terms
- search_intent: the question a viewer is trying to answer
"""

CATEGORIES = {
    'slicer': 'Slicer & Print Settings',
    'materials': 'Materials & Filament',
    'hardware': 'Printer Hardware',
    'troubleshooting': 'Calibration & Troubleshooting',
    'design': 'Design for 3D Printing',
    'finishing': 'Post-Processing & Finishing',
    'industrial_am': 'Advanced & Industrial AM',
    'mechanical': 'Mechanical Engineering',
    'physics': 'Physics of Engineering',
    'manufacturing': 'Manufacturing Processes',
    'electronics': 'Electronics & Motors',
    'tools': 'Tools, Measurement & Practice',
}

TAXONOMY: dict[str, list[tuple[str, str, str, str, str]]] = {
    # ------------------------------------------------------------------ slicer
    'slicer': [
        ('Layer Height', 'B', 'Print Quality', 'layer height;3d print quality;layer resolution;layer lines', 'does layer height matter for quality'),
        ('Infill', 'B', 'Print Quality', 'infill;3d print infill;infill density;infill percentage', 'what infill percentage should I use'),
        ('Supports', 'B', 'Supports', 'supports;3d printing supports;support settings;overhang support', 'when do I need supports'),
        ('Wall Line Count', 'B', 'Print Quality', 'wall lines;perimeters;shell thickness;wall count', 'how many wall lines should I use'),
        ('Top & Bottom Layers', 'B', 'Print Quality', 'top layers;bottom layers;solid layers;slicer top thickness', 'how many top layers for a solid top'),
        ('Print Speed vs Quality', 'B', 'Print Quality', 'print speed;print quality;speed vs quality;fast printing', 'does print speed affect quality'),
        ('Retraction Settings', 'I', 'Extrusion', 'retraction;stringing fix;retraction distance;retraction speed', 'how to fix stringing with retraction'),
        ('Z-Seam Alignment', 'I', 'Print Quality', 'z seam;seam alignment;seam position;layer seam', 'how to hide the z seam'),
        ('Cooling Fan Speed', 'I', 'Cooling', 'cooling fan;part cooling;fan speed;overhang cooling', 'what fan speed for PLA'),
        ('Print Temperature Windows', 'I', 'Extrusion', 'print temperature;nozzle temperature;temp range;hotend temp', 'what temperature should I print at'),
        ('Bed Temperature Basics', 'B', 'Adhesion', 'bed temperature;bed temp;heated bed;first layer adhesion', 'what bed temperature should I use'),
        ('First Layer Speed', 'B', 'Adhesion', 'first layer speed;initial layer;first layer settings;bed adhesion', 'how slow should the first layer be'),
        ('Ironing: What It Does', 'I', 'Print Quality', 'ironing;ironing settings;smooth top layer;top surface finish', 'what does ironing do in a slicer'),
        ('Adaptive Layer Height', 'A', 'Print Quality', 'adaptive layer height;variable layer height;layer height variation', 'how to use adaptive layer height'),
        ('Vase Mode Explained', 'I', 'Print Quality', 'vase mode;spiralize;spiral vase;single wall print', 'what is vase mode'),
        ('Spiral vs Normal Contours', 'I', 'Extrusion', 'spiral contours;contour mode;spiral printing;vase mode contours', 'spiral contour printing explained'),
        ('Slicer Skeleton: G-Code Paths', 'I', 'G-Code', 'g-code paths;slicer skeleton;print moves;toolpath', 'how a slicer plans print paths'),
        ('Coasting & Wipe', 'I', 'Extrusion', 'coasting;wipe settings;nozzle ooze;pressure relief', 'what are coasting and wipe'),
        ('Combing Mode', 'I', 'Extrusion', 'combing;travel moves;nozzle retraction;combing mode', 'what does combing do'),
        ('Travel Moves & Stringing', 'I', 'Extrusion', 'travel moves;stringing;wipe on travel;retraction travel', 'why do travel moves cause stringing'),
        ('Brim vs Raft vs Skirt', 'B', 'Adhesion', 'brim;raft;skirt;bed adhesion helpers', 'brim raft or skirt which to use'),
        ('Overlap & Extrusion Width', 'A', 'Extrusion', 'extrusion width;overlap;line width;wall overlap', 'what is extrusion width overlap'),
        ('Flow Rate Calibration', 'I', 'Extrusion', 'flow rate;extrusion multiplier;flow calibration;over extrusion', 'how to calibrate flow rate'),
        ('Linear Advance', 'A', 'Extrusion', 'linear advance;k-factor;pressure control;corner blobs', 'what is linear advance'),
        ('Pressure Advance', 'A', 'Extrusion', 'pressure advance;klipper pa;pa tuning;filament pressure', 'how to tune pressure advance'),
        ('Acceleration & Jerk Settings', 'I', 'Motion', 'acceleration;jerk;print speed settings;motion quality', 'how do acceleration and jerk affect prints'),
        ('Input Shaping', 'A', 'Motion', 'input shaping;resonance compensation;ringing fix;klipper input shaper', 'what is input shaping'),
        ('Bridge Settings', 'I', 'Print Quality', 'bridging;bridge speed;bridge fan;bridge flow', 'how to tune bridging'),
        ('Thin Wall Settings', 'I', 'Print Quality', 'thin walls;single wall;thin feature printing;minimum wall', 'how to print thin walls'),
        ('Infill Pattern Comparisons', 'I', 'Infill', 'infill patterns;gyroid;cubic;grid infill;honeycomb', 'which infill pattern is strongest'),
        ('Infill Density vs Strength', 'I', 'Infill', 'infill density;part strength;lightweight parts;infill percentage', 'does infill density affect strength'),
        ('Lightning Infill', 'A', 'Infill', 'lightning infill;adaptive infill;tree-like infill;infill speed', 'what is lightning infill'),
        ('Grid vs Gyroid vs Cubic', 'I', 'Infill', 'gyroid;grid infill;cubic infill;infill comparison', 'gyroid vs grid vs cubic infill'),
        ('Per-Object Settings', 'I', 'Slicer Workflow', 'per object settings;object settings;multiple objects;per model settings', 'how to use per-object slicer settings'),
        ('Print Order & Adhesion', 'I', 'Slicer Workflow', 'print order;sequence printing;adhesion between parts;multi part print', 'which part prints first in a batch'),
        ('Fan Cooling & Warping', 'I', 'Cooling', 'fan cooling;warping;cooling and warping;ABS fan', 'does fan cooling cause warping'),
        ('Minimum Layer Time', 'I', 'Cooling', 'minimum layer time;small parts;layer cooling;slow down small layers', 'why do small parts overheat'),
        ('Small Feature Speeds', 'I', 'Print Quality', 'small features;small part quality;feature speed;tiny details', 'how to print small details cleanly'),
        ('Fuzzy Skin Setting', 'I', 'Print Quality', 'fuzzy skin;textured surface;fuzzy print;grip surface', 'what does fuzzy skin do'),
        ('Custom Supports', 'I', 'Supports', 'custom supports;manual supports;support painting;support blockers', 'how to add custom supports'),
        ('Tree Supports', 'I', 'Supports', 'tree supports;organic supports;support structure;tree support settings', 'are tree supports better'),
        ('Support Interface Density', 'I', 'Supports', 'support interface;support density;interface layers;support surface', 'what is support interface density'),
        ('Z-Hop Explained', 'I', 'Extrusion', 'z hop;z lift;retraction hop;nozzle dragging', 'what is z hop and when to use it'),
        ('First Layer Flow', 'I', 'Adhesion', 'first layer flow;initial layer flow;extrusion first layer;bottom layer flow', 'how much first layer flow do I need'),
        ('Elephant Foot Compensation', 'I', 'Adhesion', 'elephant foot;first layer bulge;compensation;bottom flare', 'how to fix elephant foot'),
        ('Slicer Preview Reading', 'B', 'Slicer Workflow', 'slicer preview;g-code preview;layer view;print preview', 'how to read the slicer preview'),
        ('G-Code Explained', 'B', 'G-Code', 'g-code;m code;g code commands;3d printer code', 'what is g-code'),
        ('Slicing Speed vs Print Speed', 'B', 'Slicer Workflow', 'slicing speed;print speed;difference;fast slicing', 'does slicer speed matter'),
        ('Negative Expansion Offsets', 'A', 'Print Quality', 'xy compensation;hole compensation;negative expansion;size accuracy', 'how to fix holes printing too small'),
        ('Slicer Profiles: What Matters', 'B', 'Slicer Workflow', 'slicer profile;profile settings;print profile;machine profile', 'which slicer profile should I use'),
    ],
    # ------------------------------------------------------------------ materials
    'materials': [
        ('PLA', 'B', 'Core Materials', 'pla;pla filament;pla settings;pla temperature', 'what is PLA filament'),
        ('PETG', 'B', 'Core Materials', 'petg;petg filament;petg settings;petg vs pla', 'what is PETG filament'),
        ('ABS', 'B', 'Core Materials', 'abs;abs filament;abs settings;abs fumes', 'what is ABS filament'),
        ('TPU', 'I', 'Flexible Materials', 'tpu;flexible filament;tpu settings;flexible prints', 'how to print TPU'),
        ('Nylon: PA', 'A', 'Engineering Materials', 'nylon;pa filament;nylon printing;pa12', 'how to print nylon'),
        ('Polycarbonate: PC', 'A', 'Engineering Materials', 'polycarbonate;pc filament;pc printing;high temp filament', 'how to print polycarbonate'),
        ('ASA', 'I', 'Core Materials', 'asa;asa filament;asa vs abs;outdoor prints', 'what is ASA filament'),
        ('PVA Support Material', 'I', 'Support Materials', 'pva;water soluble supports;pva filament;dissolvable supports', 'how does PVA support work'),
        ('PLA+ vs PLA', 'I', 'Core Materials', 'pla plus;pla+;pla+ vs pla;tough pla', 'is PLA+ worth it'),
        ('Wood-Filled Filament', 'I', 'Composite Materials', 'wood filament;wood pla;wood filled;wood texture print', 'how to print wood filament'),
        ('Carbon Fiber Composites', 'A', 'Composite Materials', 'carbon fiber filament;cf pla;carbon reinforced;cf nylon', 'what is carbon fiber filament'),
        ('Metal-Filled Filament', 'I', 'Composite Materials', 'metal filament;metal pla;metal filled;bronze filament', 'how to print metal filament'),
        ('Glow-in-the-Dark Filament', 'B', 'Novelty Materials', 'glow filament;glow in the dark;glow pla;glowing prints', 'how to print glow filament'),
        ('Silk & Dual-Color Filament', 'B', 'Novelty Materials', 'silk filament;silk pla;dual color;dual color filament', 'what is silk filament'),
        ('PETG vs ABS', 'I', 'Material Comparisons', 'petg vs abs;abs or petg;material choice;strong filament', 'PETG or ABS which is better'),
        ('PLA vs PETG', 'B', 'Material Comparisons', 'pla vs petg;which filament;beginner filament;petg or pla', 'should I use PLA or PETG'),
        ('Filament Drying', 'I', 'Material Care', 'filament drying;dry filament;drying box;filament dryer', 'why dry your filament'),
        ('Moisture & Nylon', 'A', 'Material Care', 'nylon moisture;wet nylon;hygroscopic;drying nylon', 'why does nylon absorb water'),
        ('Annealing PLA', 'A', 'Material Care', 'annealing pla;pla heat treatment;strength pla;annealed pla', 'can you anneal PLA'),
        ('Filament Storage', 'B', 'Material Care', 'filament storage;storing filament;dry box;filament humidity', 'how to store filament'),
        ('Spool Weight & Flow', 'I', 'Material Handling', 'spool weight;filament flow;spool accuracy;material weight', 'is spool weight exact'),
        ('Filament Tolerance', 'I', 'Material Selection', 'filament tolerance;diameter tolerance;filament quality;1.75mm tolerance', 'does filament diameter tolerance matter'),
        ('Recycled Filament', 'I', 'Sustainability', 'recycled filament;petg recycled;eco filament;sustainable printing', 'is recycled filament good'),
        ('Pellets vs Filament', 'A', 'Industrial Materials', 'filament pellets;pellet extrusion;material cost;pellet printing', 'why use pellets over filament'),
        ('Material Density & Part Weight', 'I', 'Material Properties', 'material density;part weight;lightweight parts;density pla', 'how much will my print weigh'),
        ('Glass Transition Temperature', 'I', 'Material Properties', 'glass transition;tg temperature;pla tg;heat resistance', 'what is glass transition temperature'),
        ('Heat Deflection Temperature', 'A', 'Material Properties', 'heat deflection;hdt;heat resistance testing;high temp use', 'what is HDT in materials'),
        ('UV Degradation of Plastics', 'I', 'Material Properties', 'uv degradation;sunlight plastic;pla uv;outdoor filament', 'do prints degrade in the sun'),
        ('Chemical Resistance', 'I', 'Material Properties', 'chemical resistance;petg chemicals;pla solvent;material compatibility', 'which filament resists chemicals'),
        ('Hygroscopic Filaments', 'I', 'Material Properties', 'hygroscopic;water absorbing filament;dry materials;moisture filament', 'which filaments absorb water'),
        ('Multicolor & AMS Systems', 'I', 'Advanced Workflow', 'multicolor printing;ams;filament switcher;multi filament', 'how do multicolor printers work'),
        ('Filament Joining & Splicing', 'I', 'Material Handling', 'filament splice;join filament;filament welder;spool merge', 'how to join filament'),
        ('Dual Extrusion & Ooze', 'A', 'Advanced Workflow', 'dual extrusion;ooze;prime tower;dual nozzle', 'why does dual extrusion ooze'),
        ('Material Creep & Deformation', 'A', 'Material Properties', 'creep;cold flow;deformation;load over time', 'what is material creep in prints'),
        ('Stress Relaxation in Parts', 'A', 'Material Properties', 'stress relaxation;bolt preload loss;printed fastener;plastic creep', 'why do printed parts loosen over time'),
        ('PA-CF in Practice', 'A', 'Engineering Materials', 'pa cf;nylon carbon;cf nylon print;engineering filament', 'what is PA-CF filament'),
        ('HIPS Support Material', 'A', 'Support Materials', 'hips;hips filament;limonene supports;dissolvable abs', 'what is HIPS filament'),
        ('Flexible vs Rigid Materials', 'B', 'Material Selection', 'flexible filament;rigid vs flexible;shore hardness;tpu hardness', 'flexible or rigid filament'),
        ('PLA Colorants & Dyes', 'I', 'Material Customization', 'pla colors;pigments;dyeing pla;custom color filament', 'can you dye PLA'),
        ('Additive Masterbatches', 'A', 'Industrial Materials', 'masterbatch;color concentrate;filament production;additives plastic', 'what are masterbatches in filament'),
        ('Material Data Sheets', 'I', 'Material Selection', 'material datasheet;tensile strength data;filament specs;mechanical data', 'how to read a filament datasheet'),
        ('Izod vs Charpy Impact', 'A', 'Material Properties', 'izod;charpy;impact strength;notch test', 'izod vs charpy impact test'),
        ("Young's Modulus for Printers", 'A', 'Material Properties', 'youngs modulus;stiffness filament;material stiffness;modulus comparison', "what does young's modulus mean for prints"),
        ('Filament Reel Issues', 'B', 'Material Handling', 'filament tangles;reel issues;filament knot;spool tangling', 'why does filament tangle'),
        ('Choosing Your First Filament', 'B', 'Material Selection', 'first filament;which filament to buy;beginner material;filament guide', 'what filament should I start with'),
    ],
    # ------------------------------------------------------------------ hardware
    'hardware': [
        ('Bowden vs Direct Drive', 'I', 'Extrusion System', 'bowden;direct drive;extruder type;bowden vs direct', 'bowden or direct drive'),
        ('Hotend Types', 'I', 'Extrusion System', 'hotend;hotend types;hotend upgrade;heat block', 'which hotend should I use'),
        ('All-Metal Hotends', 'I', 'Extrusion System', 'all metal hotend;ptfe hotend;high temp hotend;hotend upgrade', 'why go all-metal hotend'),
        ('Nozzle Materials', 'I', 'Extrusion System', 'nozzle material;hardened nozzle;brass nozzle;nozzle wear', 'which nozzle material do I need'),
        ('Nozzle Diameter Effects', 'I', 'Extrusion System', 'nozzle diameter;0.4mm nozzle;0.6mm nozzle;nozzle size', 'does nozzle size matter'),
        ('Thermistor Readings', 'I', 'Thermal System', 'thermistor;temp sensor;thermistor 3950;temperature reading', 'how does a thermistor work'),
        ('Heat Break Explained', 'A', 'Thermal System', 'heat break;heatbreak;thermal gradient;hotend cooling', 'what does a heat break do'),
        ('Heater Cartridges', 'I', 'Thermal System', 'heater cartridge;heater power;hotend heating;24v heater', 'how do heater cartridges work'),
        ('PTFE Liner & Temperature', 'I', 'Thermal System', 'ptfe tube;ptfe degradation;capricorn tube;hotend liner', 'what temperature can PTFE handle'),
        ('Extruder Gears & Grip', 'I', 'Extrusion System', 'extruder gear;bondtech;dual drive gear;filament grip', 'why does my extruder skip'),
        ('Stepper Motors', 'I', 'Motion System', 'stepper motor;nema 17;step motor;motor torque', 'how do stepper motors work'),
        ('Stepper Drivers', 'A', 'Motion System', 'stepper driver;tmc2209;driver current;microstepping', 'what do stepper drivers do'),
        ('Lead Screws vs Belts', 'A', 'Motion System', 'lead screw;belt drive;z axis;motion system', 'lead screw or belt z-axis'),
        ('Linear Rails', 'A', 'Motion System', 'linear rail;linear bearing;rails vs rods;mgn12', 'are linear rails worth it'),
        ('Bed Leveling Sensors', 'I', 'Motion System', 'bed leveling;auto level;level sensor;bltouch', 'how does auto bed leveling work'),
        ('Probing: BLTouch & CRTouch', 'I', 'Motion System', 'bltouch;crtouch;probe accuracy;z probe', 'bltouch or crtouch'),
        ('Belt Tension', 'I', 'Motion System', 'belt tension;gt2 belt;belt tension gauge;loose belt', 'how tight should printer belts be'),
        ('Frame Stiffness', 'A', 'Machine Structure', 'frame stiffness;printer rigidity;frame braces;machine flex', 'why does frame stiffness matter'),
        ('CoreXY vs Cartesian', 'A', 'Machine Structure', 'corexy;cartesian printer;corexy vs cartesian;printer kinematics', 'corexy or cartesian'),
        ('Delta vs Cartesian', 'A', 'Machine Structure', 'delta printer;cartesian vs delta;delta kinematics;printer types', 'delta or cartesian printer'),
        ('XY Gantry Deflection', 'A', 'Machine Structure', 'gantry deflection;xy flex;toolhead sag;stiffness', 'what is gantry deflection'),
        ('Z-Wobble Sources', 'I', 'Machine Structure', 'z wobble;z axis wobble;leadscrew wobble;vertical artifacts', 'what causes z wobble'),
        ('Flexible Couplings', 'I', 'Machine Structure', 'flexible coupling;coupling z;motor coupling;z coupler', 'what do flexible couplings do'),
        ('Print Bed Types', 'I', 'Bed System', 'build plate;glass bed;pei bed;print surface', 'which print bed surface is best'),
        ('Magnetic Beds', 'I', 'Bed System', 'magnetic bed;flexible plate;magnetic print surface;spring steel', 'are magnetic beds good'),
        ('PSU & Wiring Safety', 'I', 'Electrical System', 'psu;power supply;wiring safety;electrical printer', 'what power supply do I need'),
        ('Mainboards & Firmware', 'I', 'Electrical System', 'mainboard;motherboard printer;firmware;control board', 'which mainboard should I choose'),
        ('Klipper vs Marlin', 'I', 'Firmware', 'klipper;marlin;firmware comparison;klipper benefits', 'klipper or marlin'),
        ('Closed-Loop Control', 'A', 'Motion System', 'closed loop;encoder feedback;open loop;servo steppers', 'what is closed-loop control'),
        ('Resonance & VFAs', 'A', 'Motion System', 'vfa;resonance;ringing;vertical fine artifacts', 'what causes vertical fine artifacts'),
        ('Enclosures & Drafts', 'I', 'Environment', 'printer enclosure;drafts;temperature stability;enclosure benefits', 'do I need an enclosure'),
        ('Heated Chambers', 'A', 'Environment', 'heated chamber;chamber temperature;high temp printing;enclosure heating', 'why do pro printers heat the chamber'),
        ('Dual Z-Axis', 'I', 'Motion System', 'dual z;dual z axis;z alignment;gantry sag', 'do I need dual z'),
        ('Toolhead Mass', 'A', 'Machine Structure', 'toolhead weight;mass printing;lightweight toolhead;acceleration mass', 'does toolhead weight matter'),
        ('Probe Accuracy & Repeatability', 'A', 'Motion System', 'probe accuracy;repeatability;z probe variance;leveling quality', 'how accurate is my probe'),
    ],
    # ------------------------------------------------------------------ troubleshooting
    'troubleshooting': [
        ('First-Layer Squish: Dial It In', 'B', 'Adhesion', 'first layer;z offset;nozzle height;squish', 'how much squish on first layer'),
        ('Warping Causes & Fixes', 'B', 'Adhesion', 'warping;warp fix;curling corners;adhesion loss', 'why does my print warp'),
        ('Stringing', 'B', 'Extrusion', 'stringing;strings;stringing fix;ooze', 'how to fix stringing'),
        ('Z-Banding', 'I', 'Layer Artifacts', 'z banding;layer banding;ribbing;layer lines uneven', 'what causes z banding'),
        ('Layer Shifting', 'I', 'Layer Artifacts', 'layer shift;shifted layers;missed steps;print shift', 'why is my print shifting layers'),
        ('Under-Extrusion', 'I', 'Extrusion', 'under extrusion;gaps;thin walls;extrusion problems', 'why is my print under-extruding'),
        ('Over-Extrusion', 'I', 'Extrusion', 'over extrusion;blobs;excess material;extrusion too high', 'why is my print over-extruding'),
        ('Blobs & Zits', 'I', 'Extrusion', 'blobs;zits;blobs on print;nozzle blobs', 'how to remove blobs from prints'),
        ('Gaps Between Walls', 'I', 'Layer Artifacts', 'gaps walls;wall gaps;infill gaps;perimeter gaps', 'why gaps between walls'),
        ('Poor Bed Adhesion', 'B', 'Adhesion', 'bed adhesion;print not sticking;adhesion fix;first layer fails', "why won't my print stick"),
        ('Overhangs & Sagging', 'I', 'Print Quality', 'overhang;sagging;overhang quality;drooping layers', 'why do overhangs sag'),
        ('Ringing & Ghosting', 'I', 'Motion Artifacts', 'ringing;ghosting;echo lines;vibration print', 'what causes ringing'),
        ('Pillowing', 'I', 'Layer Artifacts', 'pillowing;top layer gaps;top surface holes;top blobs', 'why is my top layer pillowing'),
        ('Clogged Nozzle', 'I', 'Extrusion', 'clogged nozzle;nozzle clog;clog fix;partial clog', 'how to fix a clogged nozzle'),
        ('Heat Creep', 'A', 'Extrusion', 'heat creep;heatcreep;filament jam;cold side', 'what is heat creep'),
        ('Filament Grinding', 'I', 'Extrusion', 'filament grinding;skipping extruder;filament shavings;extruder skip', 'why is my extruder grinding'),
        ('Stuck Filament', 'I', 'Extrusion', 'stuck filament;filament stuck;load filament;nozzle jam', 'how to remove stuck filament'),
        ('Bed Leveling Routine', 'B', 'Adhesion', 'bed leveling;level the bed;paper method;manual leveling', 'how to level the print bed'),
        ('E-Step Calibration', 'I', 'Extrusion', 'e steps;esteps calibration;extruder steps;steps per mm', 'how to calibrate e steps'),
        ('Flow Calibration', 'I', 'Extrusion', 'flow calibration;extrusion multiplier;flow test;calibrate flow', 'how to calibrate extrusion flow'),
        ('Temperature Towers', 'I', 'Calibration Prints', 'temperature tower;temp tower;temperature test;print temp test', 'how to read a temperature tower'),
        ('Retraction Calibration', 'I', 'Calibration Prints', 'retraction test;retraction tower;stringing test;retract calibrate', 'how to calibrate retraction'),
        ('First-Layer Test Prints', 'B', 'Calibration Prints', 'first layer test;test print;calibration print;level test', 'what is a first layer test'),
        ('Benchy as Diagnostic', 'B', 'Calibration Prints', 'benchy;3d benchy;test print;benchmark print', 'what can benchy tell me'),
        ('Print-in-Place Failures', 'I', 'Print Quality', 'print in place;stuck joints;fused parts;mechanisms', 'why does print-in-place stick'),
        ('Layer Gaps from Retraction', 'A', 'Layer Artifacts', 'layer gaps;retraction gaps;extrusion resume;seam gaps', 'why layer gaps after retraction'),
        ('Overheating Small Parts', 'I', 'Print Quality', 'overheating;small parts;minimum layer time;blobby details', 'why do small prints overheat'),
        ('Corner Lifting', 'I', 'Adhesion', 'corner lift;lifting corners;curling;warp edges', 'why do corners lift'),
        ('Delamination & Splitting', 'I', 'Layer Artifacts', 'delamination;layer split;layer separation;split print', 'why is my print splitting layers'),
        ('Spaghetti Detection', 'I', 'Print Quality', 'spaghetti;failed print;print failure;spaghetti detection', 'what causes spaghetti prints'),
        ('Failed Print Recovery', 'I', 'Print Quality', 'failed print;resume print;power loss;print recovery', 'how to recover a failed print'),
        ('Z-Offset vs Z-Probe', 'I', 'Adhesion', 'z offset;z probe;probe offset;nozzle probe gap', 'z offset or z probe offset'),
        ('Manual Mesh Bed Leveling', 'I', 'Adhesion', 'mesh leveling;manual mesh;bed mesh;leveling grid', 'what is manual mesh leveling'),
        ('Belt Tension Diagnosis', 'I', 'Motion Artifacts', 'belt tension;loose belt;belt tune;belt artifacts', 'how to tell if belts are loose'),
        ('Frame Alignment Check', 'I', 'Machine Structure', 'frame alignment;square frame;frame check;printer squaring', 'how to check frame alignment'),
        ('Nozzle Wear Signs', 'I', 'Extrusion', 'nozzle wear;worn nozzle;nozzle replacement;abrasive filament', 'when to replace a nozzle'),
        ('Wet Filament Symptoms', 'I', 'Extrusion', 'wet filament;moisture symptoms;popping;steam print', 'signs of wet filament'),
        ('Ringing Test Prints', 'A', 'Calibration Prints', 'ringing test;resonance test;ghosting test;tune ringing', 'how to test for ringing'),
        ('VFA Test Prints', 'A', 'Calibration Prints', 'vfa test;vertical artifacts test;surface test;print test', 'how to test for vfas'),
        ('Flow Test Method', 'I', 'Calibration Prints', 'flow test;single wall test;wall thickness test;flow cube', 'how to run a flow test'),
        ('Pressure Advance Tuning', 'A', 'Calibration Prints', 'pressure advance tune;pa test;tune pressure advance;pa tower', 'how to tune pressure advance'),
        ('Input Shaper Tuning', 'A', 'Calibration Prints', 'input shaper tune;resonance test;shaper calibration;vibration test', 'how to tune input shaping'),
        ('Tuning Order', 'B', 'Workflow', 'print tuning order;calibration order;first calibration;tuning sequence', 'what order should I calibrate'),
        ('Print Logs & History', 'I', 'Workflow', 'print logs;history;track prints;print journal', 'should I track print history'),
        ('Baseline Profile Setup', 'I', 'Workflow', 'baseline profile;default profile;known good settings;profile backup', 'how to make a baseline profile'),
    ],
    # ------------------------------------------------------------------ design
    'design': [
        ('Overhang Angles', 'B', 'Geometry', 'overhang angle;45 degree rule;overhang limit;print angles', 'what overhang angle is safe'),
        ('Bridging Design', 'I', 'Geometry', 'bridging;bridge design;bridge span;gap bridging', 'how far can a print bridge'),
        ('Fillets vs Chamfers', 'I', 'Geometry', 'fillets;chamfers;edge rounding;corner stress', 'fillet or chamfer'),
        ('Wall Thickness Minimums', 'I', 'Geometry', 'minimum wall;wall thickness;thin walls;minimum feature', 'how thin can a wall be'),
        ('Print Orientation Strength', 'I', 'Structural Design', 'print orientation;layer direction;part strength orientation;z strength', 'does orientation affect strength'),
        ('Layer Adhesion & Part Strength', 'I', 'Structural Design', 'layer adhesion;bond strength;z strength;layer bonding', 'how strong is a printed part'),
        ('Tolerances & Clearances', 'I', 'Fits', 'print tolerance;clearance;fit tolerance;moving parts', 'what clearance for moving parts'),
        ('Press-Fit Design', 'I', 'Fits', 'press fit;interference fit;press fit tolerance;bearing press fit', 'how to design a press fit'),
        ('Living Hinges', 'A', 'Mechanisms', 'living hinge;flexible hinge;printed hinge;petg hinge', 'how to design a living hinge'),
        ('Snap Fits', 'I', 'Mechanisms', 'snap fit;snap joint;snap design;cantilever snap', 'how to design a snap fit'),
        ('Threads: Cut vs Tapped vs Heat-Set', 'I', 'Fasteners', 'printed threads;tapped threads;heat set inserts;threads in prints', 'best way to add threads'),
        ('Heat-Set Inserts', 'I', 'Fasteners', 'heat set insert;brass insert;insert boss;melt insert', 'how to use heat-set inserts'),
        ('Generous Radii & Stress', 'A', 'Structural Design', 'stress concentration;radii;notch stress;corner stress', 'why do sharp corners crack'),
        ('Avoid Sharp Corners', 'I', 'Geometry', 'sharp corners;corner strength;stress risers;rounded corners', 'why avoid sharp corners in prints'),
        ('Hole Sizing & Shrinkage', 'I', 'Geometry', 'hole size;hole shrink;small holes;hole compensation', 'why are holes too small'),
        ('Embossed Text Orientation', 'I', 'Geometry', 'embossed text;engraved text;text on prints;deboss', 'embossed or engraved text'),
        ('Supports-Free Design', 'I', 'Geometry', 'design without supports;support free;self supporting;no supports', 'how to design without supports'),
        ('Design for FDM vs Resin', 'I', 'Process Design', 'fdm vs resin design;print orientation resin;resin design rules', 'how does design change for resin'),
        ('Draft Angles & Tapers', 'I', 'Geometry', 'draft angle;taper;release angle;wall taper', 'what is a draft angle'),
        ('Internal Channels', 'A', 'Geometry', 'internal channels;cooling channels;flow channels;hidden passages', 'how to print internal channels'),
        ('Self-Supporting Lattices', 'A', 'Lattices', 'lattice;self supporting lattice;lattice design;triply periodic', 'what lattices print without supports'),
        ('Gyroid Lattice Parts', 'A', 'Lattices', 'gyroid;gyroid infill;gyroid lattice;lightweight lattice', 'what is a gyroid lattice'),
        ('Lightweighting', 'A', 'Structural Design', 'lightweighting;weight reduction;shell design;ribbing', 'how to lighten a part'),
        ('Print-in-Place Mechanisms', 'A', 'Mechanisms', 'print in place;living mechanism;foldable print;single print assembly', 'how do print-in-place parts work'),
        ('Compliant Mechanisms', 'A', 'Mechanisms', 'compliant mechanism;flexure;flexure joint;printed flexure', 'what is a compliant mechanism'),
        ('Keyways & D-Shafts', 'I', 'Fits', 'keyway;d shaft;shaft fit;press on shaft', 'how to fit a gear to a shaft'),
        ('Bolt Bosses & Ribs', 'I', 'Fasteners', 'bolt boss;boss design;ribs;fastener boss', 'how to design a bolt boss'),
        ('Stepper Motor Mounts', 'I', 'Fits', 'stepper mount;nema 17 mount;motor bracket;mount holes', 'how to mount a stepper'),
        ('Bearing Mounts', 'I', 'Fits', 'bearing mount;bearing fit;ball bearing housing;press bearing', 'how to design a bearing mount'),
        ('Scaling Parts & Shrinkage', 'I', 'Geometry', 'scale parts;shrinkage;print scale;oversize part', 'why scale up printed parts'),
        ('Splitting Large Parts', 'I', 'Assembly', 'split large print;cut model;print in parts;large part assembly', 'how to split a big print'),
        ('Dovetail Joins', 'I', 'Assembly', 'dovetail;dovetail joint;interlocking parts;wood joinery print', 'how to design a dovetail joint'),
        ('Slot & Tab Assembly', 'I', 'Assembly', 'slot and tab;tab assembly;finger joint;knockdown joints', 'what is slot and tab joinery'),
        ('Friction-Fit vs Epoxy', 'I', 'Assembly', 'friction fit;glue prints;epoxy join;joining parts', 'glue or friction fit parts'),
        ('Design for Post-Processing', 'I', 'Post-Process Design', 'design for finishing;sanding design;finishing allowance;surface design', 'how does finishing change design'),
        ('Text & Fonts on Parts', 'B', 'Geometry', 'text on 3d prints;fonts;small text;emboss text', 'how small can text be'),
        ('QR Codes & Logos', 'I', 'Geometry', 'qr code print;logo on print;embedded logo;relief logo', 'how to print a QR code'),
        ('Multi-Part Assemblies', 'I', 'Assembly', 'multi part;assembly design;modular print;part compatibility', 'how to design multi-part builds'),
        ('GD&T for 3D Prints', 'A', 'Quality', 'gd&t;geometric tolerancing;datum;position tolerance', 'what GD&T applies to printing'),
        ('Datum Features', 'A', 'Quality', 'datum;datum feature;reference surface;measuring prints', 'what is a datum feature'),
    ],
    # ------------------------------------------------------------------ finishing
    'finishing': [
        ('Sanding PLA & ABS', 'B', 'Sanding', 'sanding prints;sand pla;sand abs;wet sanding', 'how to sand 3d prints smooth'),
        ('Acetone Smoothing ABS', 'I', 'Chemical Finishing', 'acetone smoothing;vapor smoothing abs;acetone bath;abs smoothing', 'how to smooth ABS with acetone'),
        ('Chemical Smoothing Resin', 'A', 'Chemical Finishing', 'resin smoothing;chemical polish;solvent dip;ipa polish', 'how to smooth resin prints'),
        ('Painting 3D Prints', 'I', 'Painting', 'paint prints;spray paint print;painting pla;primer paint', 'how to paint 3d prints'),
        ('Primers & Fillers', 'I', 'Painting', 'primer;filler primer;spot putty;surface filler', 'what primer for prints'),
        ('Epoxy Coating', 'I', 'Coating', 'epoxy coat;resin coat;epoxy finish;seal print', 'how to epoxy coat prints'),
        ('Polishing Clear Prints', 'I', 'Sanding', 'polish prints;clear print;transparent print;buffing', 'how to make prints glossy'),
        ('Vapor Smoothing Systems', 'A', 'Chemical Finishing', 'vapor smoothing;polysmooth;fume smoothing;vapor polish', 'what is vapor smoothing'),
        ('Heat Gun Deburring', 'I', 'Deburring', 'heat gun;deburr print;string removal;heat smoothing', 'can I use a heat gun on prints'),
        ('Support Removal Tools', 'B', 'Deburring', 'support removal;remove supports;snips;support tool', 'how to remove supports cleanly'),
        ('Drill & Tap Printed Parts', 'I', 'Machining', 'drill prints;tap printed;thread tap pla;drill printed hole', 'can you tap printed parts'),
        ('Thread Tapping PLA', 'I', 'Machining', 'tap pla;thread tap plastic;self tap;threaded hole', 'how to tap threads in PLA'),
        ('Silicone Molding from Prints', 'A', 'Molding', 'silicone mold;mold from print;two part mold;casting mold', 'how to make a silicone mold from a print'),
        ('Casting & Mold Making', 'A', 'Molding', 'resin casting;cast parts;mold making;metal casting print', 'how to cast parts from prints'),
        ('Dyeing Nylon Parts', 'A', 'Chemical Finishing', 'dye nylon;nylon dye;rit dye;color nylon', 'how to dye nylon parts'),
        ('Powder Coating', 'A', 'Coating', 'powder coat;powder coating;coated prints;durable coating', 'can prints be powder coated'),
        ('Electroplating Prints', 'A', 'Coating', 'electroplating;metal plating;copper plate;chrome print', 'can you electroplate prints'),
        ('CNC Finishing of Prints', 'A', 'Machining', 'cnc prints;machining printed parts;finish mill;cnc final pass', 'how to CNC finish a print'),
        ('Welding Plastics', 'I', 'Joining', 'plastic weld;solder plastic;weld pla;friction weld', 'how to weld plastic parts'),
        ('Weatherproofing Prints', 'I', 'Coating', 'waterproof print;weatherproof;seal print;uv coat', 'how to waterproof prints'),
    ],
    # ------------------------------------------------------------------ industrial_am
    'industrial_am': [
        ('SLA vs FDM', 'I', 'Process Comparison', 'sla vs fdm;resin vs filament;resin printer;fdm vs sla', 'sla or fdm printer'),
        ('Resin Types', 'I', 'Resin Printing', 'resin types;tough resin;standard resin;resin properties', 'which resin should I use'),
        ('Resin Washing & Curing', 'I', 'Resin Printing', 'resin washing;curing;ipa wash;cure station', 'how to wash and cure resin'),
        ('MSLA & LCD Resolution', 'A', 'Resin Printing', 'msla;lcd printer;resolution resin;pixel size', 'what is msla printing'),
        ('DLP vs LCD vs Laser', 'A', 'Resin Printing', 'dlp;lcd;laser sla;projector printing', 'dlp or lcd resin'),
        ('Metal 3D Printing', 'A', 'Industrial AM', 'metal 3d printing;dmls;metal additive;printed metal parts', 'how does metal 3d printing work'),
        ('SLS & Nylon Powder', 'A', 'Industrial AM', 'sls;powder bed;sls nylon;selective laser sintering', 'how does SLS work'),
        ('MJF Technology', 'A', 'Industrial AM', 'mjf;multi jet fusion;hp mjf;powder printing', 'what is multi jet fusion'),
        ('DMLS & LPBF', 'A', 'Industrial AM', 'dmls;lpbf;laser powder bed;metal am', 'dmls vs lpbf explained'),
        ('FDM vs SLS', 'I', 'Process Comparison', 'fdm vs sls;sls vs fdm;powder vs filament;nylon sls', 'fdm or sls for parts'),
        ('Continuous Carbon Fiber', 'A', 'Industrial AM', 'carbon fiber continuous;markforged;cf printing;continuous fiber', 'how does continuous carbon fiber printing work'),
        ('Multi-Material AM', 'A', 'Industrial AM', 'multi material printing;multi jet;voxel printing;dissolvable', 'what is multi material printing'),
        ('Industrial Print Farm', 'I', 'Industrial AM', 'print farm;production printing;batch printing;printer fleet', 'how do print farms work'),
        ('AM vs Injection Molding', 'I', 'Process Comparison', 'am vs injection molding;3d printing vs molding;production parts;molding cost', 'when is printing cheaper than molding'),
        ('Binder Jetting', 'A', 'Industrial AM', 'binder jetting;binder jet;sand printing;full color printing', 'what is binder jetting'),
    ],
    # ------------------------------------------------------------------ mechanical
    'mechanical': [
        ('Gears: How Teeth Engage', 'B', 'Gears', 'gears;gear teeth;gear mesh;how gears work', 'how do gears work'),
        ('Gear Ratios', 'B', 'Gears', 'gear ratio;reduction ratio;torque gears;speed gears', 'what is a gear ratio'),
        ('Planetary Gears', 'A', 'Gears', 'planetary gear;epicyclic;sun gear;gear box', 'how do planetary gears work'),
        ('Bevel Gears', 'I', 'Gears', 'bevel gear;right angle drive;mitre gear;bevel angle', 'what are bevel gears for'),
        ('Worm Gears', 'I', 'Gears', 'worm gear;worm drive;self locking;worm wheel', 'how does a worm gear work'),
        ('Spur vs Helical Gears', 'I', 'Gears', 'spur gear;helical gear;gear noise;gear comparison', 'spur or helical gears'),
        ('Bearings: How They Work', 'B', 'Bearings', 'bearings;ball bearing;how bearings work;bearing types', 'how do bearings work'),
        ('Ball vs Roller Bearings', 'I', 'Bearings', 'ball bearing;roller bearing;bearing load;bearing type', 'ball or roller bearings'),
        ('Preload & Bearing Life', 'A', 'Bearings', 'bearing preload;bearing life;l10 life;bearing stiffness', 'what is bearing preload'),
        ('Lubrication Basics', 'I', 'Lubrication', 'lubrication;grease types;oil vs grease;bearing lube', 'what lubricant should I use'),
        ('Threads & Fasteners', 'B', 'Fasteners', 'threads;fasteners;bolt;metric thread', 'how do threads work'),
        ('Screw Types', 'I', 'Fasteners', 'screw types;machine screw;self tapping;bolt vs screw', 'which screw should I use'),
        ('Torque & Tension', 'I', 'Fasteners', 'torque tension;bolt torque;clamp load;tightening torque', 'why does bolt torque matter'),
        ('Loctite & Locking', 'I', 'Fasteners', 'loctite;threadlocker;lock nuts;vibration loosening', 'why do bolts come loose'),
        ('Shaft Keys', 'I', 'Shafts', 'shaft key;keyway;woodruff key;torque transfer', 'what is a shaft key'),
        ('Couplings', 'I', 'Shafts', 'coupling;shaft coupling;flex coupling;motor coupling', 'what type of coupling do I need'),
        ('Springs: Coil & Leaf', 'I', 'Springs', 'springs;coil spring;leaf spring;spring rate', 'how do springs work'),
        ('Belts & Pulleys', 'I', 'Power Transmission', 'belt pulley;timing belt;pulley ratio;belt drive', 'how do belts and pulleys work'),
        ('Chains & Sprockets', 'I', 'Power Transmission', 'chain sprocket;chain drive;bike chain;roller chain', 'how do chains and sprockets work'),
        ('Cams & Followers', 'A', 'Mechanisms', 'cam follower;cam mechanism;cam profile;cam shaft', 'how do cams work'),
        ('Linkages & Four-Bar', 'A', 'Mechanisms', 'linkage;four bar;mechanism design;crank rocker', 'what is a four-bar linkage'),
        ('Ratchets & Pawls', 'I', 'Mechanisms', 'ratchet;pawl;ratchet mechanism;one way', 'how does a ratchet work'),
        ('Clutches', 'A', 'Power Transmission', 'clutch;clutch types;friction clutch;overrunning', 'how do clutches work'),
        ('Brakes: Friction & Disc', 'I', 'Power Transmission', 'brakes;disc brake;friction brake;braking force', 'how do disc brakes work'),
        ('Levers & Mechanical Advantage', 'B', 'Statics', 'lever;mechanical advantage;fulcrum;lever classes', 'what is mechanical advantage'),
        ('Pulleys & Lifting', 'B', 'Statics', 'pulley;block and tackle;lifting;rope pulley', 'how do pulleys multiply force'),
        ('Hydraulics & Pascal', 'B', 'Fluids', 'hydraulics;pascal law;hydraulic press;fluid power', 'how do hydraulics work'),
        ('Pneumatics', 'I', 'Fluids', 'pneumatics;air cylinder;compressed air;actuators', 'how do pneumatic systems work'),
        ('Pressure Vessels', 'A', 'Fluids', 'pressure vessel;hoop stress;pressure tank;burst pressure', 'how are pressure vessels designed'),
        ('Shafts & Torsion', 'A', 'Shafts', 'torsion;shaft stress;twist angle;torque shaft', 'how much can a shaft twist'),
        ('Press Fits', 'I', 'Fits', 'press fit;interference;interference fit;press tolerance', 'how do press fits hold'),
        ('Heat Fits & Shrink Fits', 'A', 'Fits', 'shrink fit;heat fit;thermal fit;interference heat', 'what is a shrink fit'),
        ('Clevis & Pin Joints', 'I', 'Fits', 'clevis;pin joint;shoulder bolt;clevis pin', 'how to design a clevis joint'),
        ('Weld Types', 'I', 'Joining', 'weld types;fillet weld;butt weld;weld joints', 'what are the weld types'),
        ('Rivets vs Bolts', 'I', 'Fasteners', 'rivets;bolts vs rivets;rivet joint;blind rivet', 'rivets or bolts'),
        ('Structural Beam Basics', 'B', 'Statics', 'beam;bending;i beam;beam strength', 'how do beams carry load'),
        ('Cantilever Loads', 'I', 'Statics', 'cantilever;overhang load;bending moment;cantilever beam', 'how much can a cantilever hold'),
        ('Stress vs Strain', 'B', 'Materials', 'stress strain;stress strain curve;elastic;material strength', 'what is the difference between stress and strain'),
        ('Yield vs Ultimate Strength', 'I', 'Materials', 'yield strength;ultimate strength;tensile test;material limits', 'yield or ultimate strength'),
        ('Fatigue & Crack Growth', 'A', 'Materials', 'fatigue;metal fatigue;crack growth;cycle loading', 'why do parts fail from fatigue'),
        ('Factor of Safety', 'I', 'Statics', 'factor of safety;design margin;safety factor;engineering design', 'what is factor of safety'),
        ('Tolerance Stacks', 'A', 'Quality', 'tolerance stack;stack up;tolerance analysis;fit accumulation', 'what is a tolerance stack'),
        ('Surface Finish Ra', 'I', 'Quality', 'surface finish;ra value;roughness;surface texture', 'what does surface roughness Ra mean'),
        ('Hardness Scales', 'I', 'Materials', 'hardness;rockwell;shore durometer;vickers', 'how is material hardness measured'),
        ('Anodizing', 'I', 'Surface Treatment', 'anodizing;anodized aluminum;hard anodize;aluminum finish', 'what does anodizing do'),
        ('Galvanic Corrosion', 'I', 'Materials', 'galvanic corrosion;corrosion;aluminum steel;dissimilar metals', 'why do metals corrode together'),
        ('Steel vs Aluminum', 'B', 'Materials', 'steel vs aluminum;aluminum or steel;material choice;metal strength', 'steel or aluminum'),
        ('Titanium in Practice', 'A', 'Materials', 'titanium;ti parts;titanium strength;lightweight metal', 'when should you use titanium'),
        ('Bushings vs Bearings', 'I', 'Bearings', 'bushing;bronze bushing;plain bearing;bearing vs bushing', 'bushing or bearing'),
        ('Shim & Spacer Fit', 'I', 'Fits', 'shim;spacer;shimming;alignment shim', 'how are shims used'),
    ],
    # ------------------------------------------------------------------ physics
    'physics': [
        ('Friction: Static vs Kinetic', 'B', 'Mechanics', 'friction;static friction;kinetic friction;stiction', 'static vs kinetic friction'),
        ('Coefficient of Friction', 'I', 'Mechanics', 'coefficient of friction;friction coefficient;mu;grip', 'what is coefficient of friction'),
        ('Torque vs Power', 'I', 'Mechanics', 'torque vs power;horsepower;torque curve;engine torque', 'torque or power which matters'),
        ('RPM & Speed', 'B', 'Mechanics', 'rpm;revolutions per minute;speed ratio;motor speed', 'what does rpm mean'),
        ('Centrifugal vs Centripetal', 'I', 'Mechanics', 'centrifugal force;centripetal;circular motion;fake force', 'centrifugal or centripetal'),
        ('Flywheels & Energy Storage', 'A', 'Mechanics', 'flywheel;energy storage;angular inertia;momentum wheel', 'how do flywheels store energy'),
        ('Heat Transfer: Conduction', 'I', 'Thermodynamics', 'conduction;heat transfer;thermal conductivity;conductive cooling', 'how does heat move through metal'),
        ('Convection Cooling', 'I', 'Thermodynamics', 'convection;air cooling;heat sink airflow;natural convection', 'how does convection cool parts'),
        ('Radiation & Infrared', 'I', 'Thermodynamics', 'radiation;infrared;emissivity;thermal radiation', 'how does heat radiate'),
        ('Thermal Expansion', 'I', 'Thermodynamics', 'thermal expansion;expansion coefficient;thermal growth;heat fit', 'why do metals expand when hot'),
        ('Heat Sink Design', 'A', 'Thermodynamics', 'heat sink;fin design;thermal resistance;cooling fins', 'how to design a heat sink'),
        ('Thermal Interface Materials', 'A', 'Thermodynamics', 'thermal paste;thermal pad;tim;interface material', 'thermal paste or pad'),
        ('Archimedes & Buoyancy', 'B', 'Fluids', 'buoyancy;archimedes;float;displacement', 'why do things float'),
        ('Pressure & Force', 'B', 'Fluids', 'pressure;force area;pascal;psi', 'what is pressure'),
        ('Vacuum & Suction', 'I', 'Fluids', 'vacuum;suction;negative pressure;vacuum cup', 'how does suction work'),
        ('Bernoulli & Flow', 'I', 'Fluids', 'bernoulli;fluid flow;pressure velocity;venturi', "what is bernoulli's principle"),
        ('Viscosity', 'I', 'Fluids', 'viscosity;fluid thickness;oil viscosity;flow resistance', 'what is viscosity'),
        ('Reynolds Number', 'A', 'Fluids', 'reynolds number;laminar flow;turbulent flow;flow regime', 'what is the reynolds number'),
        ('Drag & Streamlining', 'I', 'Fluids', 'drag;aerodynamic drag;streamline;air resistance', 'what causes drag'),
        ('Momentum & Impulse', 'I', 'Mechanics', 'momentum;impulse;collision;impact force', 'what is impulse'),
        ('Angular Momentum', 'I', 'Mechanics', 'angular momentum;rotation;spinning;conservation momentum', 'what is angular momentum'),
        ('Gyroscopes & Precession', 'A', 'Mechanics', 'gyroscope;precession;gyroscopic;spinning wheel', "why don't gyroscopes fall"),
        ('Resonance & Natural Frequency', 'I', 'Vibration', 'resonance;natural frequency;vibration;tuned frequency', 'what is resonance'),
        ('Damping', 'I', 'Vibration', 'damping;vibration damping;shock;energy absorption', 'what is damping'),
        ('Structural Vibration', 'A', 'Vibration', 'structural vibration;machine vibration;modal;vibration modes', 'why do machines vibrate'),
        ("Elasticity & Hooke's Law", 'B', 'Mechanics', 'hookes law;elasticity;spring constant;elastic deformation', "what is hooke's law"),
        ("Poisson's Ratio", 'A', 'Materials', 'poissons ratio;lateral strain;material squeeze;expansion ratio', "what is poisson's ratio"),
        ('Center of Mass', 'I', 'Mechanics', 'center of mass;balance point;center of gravity;stability', 'what is center of mass'),
        ('Statics: Balanced Forces', 'B', 'Mechanics', 'statics;balanced forces;equilibrium;force balance', 'what does equilibrium mean'),
        ('Dynamics: F=ma in Machines', 'I', 'Mechanics', 'newtons second law;f=ma;acceleration force;machine dynamics', 'how does f=ma apply to machines'),
    ],
    # ------------------------------------------------------------------ manufacturing
    'manufacturing': [
        ('Injection Molding', 'B', 'Molding', 'injection molding;mold;plastic molding;molded parts', 'how does injection molding work'),
        ('CNC Milling', 'B', 'Machining', 'cnc milling;milling machine;end mill;cnc machining', 'how does cnc milling work'),
        ('CNC Turning & Lathe', 'I', 'Machining', 'cnc turning;lathe;turning;spindle machining', 'how does cnc turning work'),
        ('Laser Cutting', 'I', 'Cutting', 'laser cutting;laser cutter;co2 laser;cut sheet metal', 'how does laser cutting work'),
        ('Waterjet Cutting', 'A', 'Cutting', 'waterjet;water jet cutting;abrasive jet;cold cutting', 'how does waterjet cutting work'),
        ('Sheet Metal Bending', 'I', 'Forming', 'sheet metal;press brake;bend allowance;k factor', 'how is sheet metal bent'),
        ('Aluminum Extrusion', 'I', 'Forming', 'aluminum extrusion;extrusion profiles;t slot;die extrusion', 'how is aluminum extruded'),
        ('Die Casting', 'I', 'Molding', 'die casting;cast metal;zinc casting;aluminum casting', 'how does die casting work'),
        ('Forging', 'I', 'Forming', 'forging;hammer forging;wrought metal;forged steel', 'how does forging work'),
        ('Welding Basics', 'B', 'Joining', 'welding;mig;tig;stick welding', 'how does welding work'),
        ('Brazing & Soldering', 'I', 'Joining', 'brazing;soldering;silver solder;capillary joint', 'brazing vs soldering'),
        ('Heat Treatment', 'A', 'Materials', 'heat treatment;quenching;tempering;hardening steel', 'what is heat treatment'),
        ('Annealing & Tempering', 'I', 'Materials', 'annealing;tempering;soft steel;stress relief', 'annealing vs tempering'),
        ('EDM Machining', 'A', 'Machining', 'edm;electric discharge;wire edm;sinker edm', 'how does edm machining work'),
        ('Grinding & Abrasives', 'I', 'Machining', 'grinding;abrasive;surface grinder;wheel grit', 'how does grinding work'),
        ('Powder Metallurgy', 'A', 'Materials', 'powder metallurgy;sintering;metal powder;pm parts', 'how is powder metal made'),
        ('Plating & Coating', 'I', 'Surface Treatment', 'plating;electroplating;coating;chrome plating', 'how does electroplating work'),
        ('Sand Casting', 'I', 'Molding', 'sand casting;foundry;cast iron;green sand', 'how does sand casting work'),
        ('Vacuum Forming', 'I', 'Forming', 'vacuum forming;thermoforming;plastic forming;blister mold', 'how does vacuum forming work'),
        ('Rapid Prototyping vs Production', 'I', 'Process Selection', 'rapid prototyping;prototype vs production;production parts;prototyping methods', 'prototyping or production'),
        ('Tolerancing in Machining', 'A', 'Quality', 'machining tolerance;cnc tolerance;hold tolerance;tight tolerance', 'what tolerance can cnc hold'),
        ('Thread Cutting Methods', 'I', 'Machining', 'thread cutting;threading;tap vs die;thread mill', 'how are threads made'),
        ('Mold Design Basics', 'A', 'Molding', 'mold design;draft in mold;ejector pins;mold tooling', 'what makes a good mold'),
        ('Batch vs Mass Production', 'B', 'Process Selection', 'batch production;mass production;production scale;manufacturing scale', 'batch or mass production'),
        ('DFM Principles', 'I', 'Process Selection', 'dfm;design for manufacturing;manufacturable design;dfa', 'what is design for manufacturing'),
    ],
    # ------------------------------------------------------------------ electronics
    'electronics': [
        ('Stepper Motors Deep Dive', 'I', 'Motors', 'stepper motor;how stepper works;nema;motor steps', 'how does a stepper motor work'),
        ('Servo Motors', 'I', 'Motors', 'servo;servo motor;position control;servo vs stepper', 'how do servo motors work'),
        ('BLDC Motors', 'A', 'Motors', 'bldc;brushless;ec motor;motor commutation', 'how do brushless motors work'),
        ('DC Motors Basics', 'B', 'Motors', 'dc motor;brushed motor;motor basics;motor speed control', 'how does a dc motor work'),
        ('Motor Drivers & H-Bridges', 'I', 'Power Electronics', 'h bridge;motor driver;l298n;mosfet driver', 'how does an h bridge work'),
        ('Encoders', 'I', 'Sensors', 'encoder;rotary encoder;quadrature;position feedback', 'how do encoders work'),
        ("Ohm's Law", 'B', 'Fundamentals', 'ohms law;voltage current resistance;v=ir;circuits', "what is ohm's law"),
        ('Power: Watts & Efficiency', 'B', 'Fundamentals', 'watts;power;efficiency;electrical power', 'what is electrical power'),
        ('Voltage Dividers', 'I', 'Fundamentals', 'voltage divider;resistor divider;signal scaling;sensor read', 'how does a voltage divider work'),
        ('PWM Explained', 'I', 'Fundamentals', 'pwm;pulse width modulation;duty cycle;fan control', 'what is pwm'),
        ('Thermistors & Sensors', 'I', 'Sensors', 'thermistor;ntc;temperature sensor;resistance temperature', 'how do temperature sensors work'),
        ('Relays vs MOSFETs', 'I', 'Switching', 'relay;mosfet;solid state switch;switching loads', 'relay or mosfet'),
        ('Batteries: Cells & Series', 'I', 'Power', 'battery cells;series parallel;18650;voltage pack', 'how do batteries connect'),
        ('Charging & Protection', 'I', 'Power', 'charging;bms;overcharge;cell protection', 'how does battery protection work'),
        ('Cable & Wire Gauge', 'I', 'Wiring', 'wire gauge;awg;cable sizing;current wire', 'what wire gauge do I need'),
        ('Soldering Basics', 'B', 'Wiring', 'soldering;through hole;joint quality;solder', 'how to solder'),
        ('PCBs & Traces', 'I', 'Electronics Design', 'pcb;printed circuit board;trace width;pcb design', 'what is a pcb'),
        ('Microcontrollers', 'B', 'Embedded', 'microcontroller;arduino;mcu;embedded control', 'what is a microcontroller'),
        ('3D Printer Control Boards', 'I', 'Embedded', 'control board;printer mcu;octopus board;mainboard', 'what does the control board do'),
        ('Wiring & Connectors', 'I', 'Wiring', 'connectors;jst;dupon;xt60;wiring harness', 'which connector should I use'),
        ('Fuses & Protection', 'I', 'Safety', 'fuses;overcurrent;protection;circuit breaker', 'why do fuses matter'),
        ('Grounding & Noise', 'A', 'EMC', 'grounding;ground loop;signal noise;common ground', 'why does grounding matter'),
        ('EMI & Interference', 'A', 'EMC', 'emi;interference;shield;noise suppression', 'why does my signal have noise'),
        ('Power Supplies & Ratings', 'I', 'Power', 'power supply;psu rating;current rating;power needs', 'how to choose a power supply'),
        ('Multimeter Skills', 'B', 'Measurement', 'multimeter;measuring voltage;continuity;meter basics', 'how to use a multimeter'),
    ],
    # ------------------------------------------------------------------ tools
    'tools': [
        ('Calipers', 'B', 'Measuring', 'calipers;vernier;digital caliper;measuring parts', 'how to use calipers'),
        ('Micrometers', 'I', 'Measuring', 'micrometer;mic;measuring precision;ratchet stop', 'how to use a micrometer'),
        ('Dial Indicators', 'I', 'Measuring', 'dial indicator;dti;runout;measure runout', 'how to use a dial indicator'),
        ('Torque Wrenches', 'I', 'Measuring', 'torque wrench;torque spec;click torque;tighten bolts', 'how to use a torque wrench'),
        ('Feeler Gauges', 'I', 'Measuring', 'feeler gauge;gap measurement;thickness gauge;set gap', 'how to use feeler gauges'),
        ('Square & Flatness Checks', 'I', 'Measuring', 'square;flatness;surface plate;check square', 'how to check for square'),
        ('Measuring Threads', 'I', 'Measuring', 'measure threads;pitch gauge;thread pitch;thread size', 'how to measure a thread'),
        ('Precision Basics', 'B', 'Measuring', 'precision;accuracy;measurement error;repeatability', 'precision vs accuracy'),
        ('Dial vs Digital Readouts', 'I', 'Measuring', 'dial readout;digital readout;dro;lathe readout', 'dial or digital readout'),
        ('Shop Safety Basics', 'B', 'Workshop', 'shop safety;safety gear;eye protection;workshop rules', 'what safety gear do I need'),
        ('Workshop Lighting', 'I', 'Workshop', 'workshop lighting;workbench light;task lighting;color temp', 'what lighting for a workshop'),
        ('Workholding', 'I', 'Workshop', 'workholding;vise;clamps;hold parts', 'how to hold parts for machining'),
        ('Vises & Clamps', 'B', 'Workshop', 'vise;clamps;f-clamp;quick clamp', 'which clamp do I need'),
        ('Cutting Tools & Bits', 'I', 'Workshop', 'cutting tools;end mill bits;drill bits;tool selection', 'which cutting tool for what'),
        ('Deburring Tools', 'B', 'Workshop', 'deburr;deburring tool;edge cleanup;chamfer tool', 'how to deburr edges'),
        ('Precision Squares', 'I', 'Measuring', 'precision square;engineers square;check square;90 degrees', 'how to check 90 degrees'),
        ('Gauge Blocks', 'A', 'Measuring', 'gauge blocks;jo blocks;reference standard;calibration', 'what are gauge blocks'),
        ('Laser Levels', 'B', 'Workshop', 'laser level;leveling;alignment laser;layout tool', 'how to use a laser level'),
        ('Micrometer vs Caliper', 'I', 'Measuring', 'micrometer vs caliper;which measuring tool;precision tool', 'micrometer or caliper'),
        ('Tolerance Measurement', 'I', 'Measuring', 'measure tolerance;check dimensions;quality control;gauge part', 'how to verify a dimension'),
    ],
}
