"""Batch 13: first layer discipline, nylon, probes, surface bumps, flexures, gear noise, conduction, and bending."""

CURATED = [
    # ======================================================================
    {
        "topic": "First Layer Speed",
        "core_question": "Why is the first layer printed so slowly, and how slow should it be?",
        "learning_objective": "The viewer can explain why first layer speed is reduced and set it correctly for adhesion.",
        "engineering_summary": "The first layer is the foundation of every print: everything above stacks on this one, so the slicer prints it far slower than the rest. A slow first layer gives molten plastic time to squish, flow outward, and mechanically grip the bed surface before it cools - typically 25-30 mm/s versus 60-100 mm/s for normal layers. Fast first layers skim and skid, leaving gaps and weak adhesion that no later setting can repair. The slower speed also lets the part-cooling fan and bed temperature bond the material properly, which matters most on textured beds and sticky materials like PETG. The habit: never raise first layer speed to chase print time; the foundation layer is where prints live or die.",
        "real_world_application": "Every slicer profile separates initial layer speed from normal speed; print farms never touch it because first-layer failures cost whole batches.",
        "common_misconceptions": [
            "First layer speed barely matters (it is the single most important adhesion setting)",
            "Fast first layers save meaningful time (it is one layer - the savings are negligible)",
            "Speed is separate from squish (speed and z-offset work together for the first layer)",
        ],
        "teaching_strategy": "Show a slow first layer flowing out, then a fast one skidding, then the settings screen and the failure comparison.",
        "script": "The first layer is the foundation: everything above stacks on this one. A slow first layer buys time for molten plastic to squish, flow, and grip the bed, so slicers default first layer speed to a fraction of normal - typically 25 to 30 millimeters per second. Fast first layers skim and skid, leaving gaps that never close. Slow layers also give the cooling fan time to bond plastic to the surface. It matters most on textured beds and sticky PETG. Print slow, get the squish right, and the first layer stops being the failure point.",
        "text_overlay": [
            "LAYER ONE = THE FOUNDATION",
            "25-30MM/S VS 60-100",
            "FAST LAYERS SKID",
            "SQUISH + SLOW = STUCK",
        ],
        "scenes": [
            {
                "goal": "Hook: the skidding layer",
                "teaching_point": "Fast plastic never gets a grip",
                "shot": "macro shot of a fast first layer skidding across the bed",
                "motion": "molten plastic skids and streaks",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["first layer", "skidding", "bed"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a fast first layer skidding across a print bed, bright task light, print lab",
            },
            {
                "goal": "The squish",
                "teaching_point": "Time to flow and grip",
                "shot": "macro shot of a slow first layer flattening onto the bed",
                "motion": "bead flattens and grips the surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["slow first layer", "squished bead", "bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a slow first layer bead squishing flat onto the print bed, bright task light, print lab",
            },
            {
                "goal": "The settings",
                "teaching_point": "Slicers separate initial layer speed",
                "shot": "slicer screen shot with the initial layer speed setting highlighted",
                "motion": "setting values highlight on the screen",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slicer screen", "initial layer speed", "highlight"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer settings screen with initial layer speed highlighted on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The result",
                "teaching_point": "Gaps in the first layer never close",
                "shot": "tabletop shot of a print with first-layer gaps beside a clean one",
                "motion": "tilt between the two prints",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["gapped print", "clean print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a print with first layer gaps beside a clean first layer print, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Slow layer, strong foundation",
                "shot": "wide hero shot of a print with a perfect first layer on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["perfect first layer", "print", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a print with a perfect first layer on the printer bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A speed gauge showing slow first layer versus fast layers",
            "subject": "speed gauge with first layer marker",
            "background": "dark print lab blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "gauge center, first layer overlay",
            "text": "SLOW FIRST LAYER",
            "elements": ["speed gauge", "first layer", "print bed"],
            "style": "diagnostic studio photography",
            "mood": "foundational, deliberate, steady",
            "prompt": "photograph of a speed gauge with a first layer overlay on a print bed, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "First Layer Speed: Print Slow, Stick Fast",
            "title_variations": [
                "First Layer Speed Guide",
                "How Slow Should the First Layer Be",
                "Initial Layer Speed Settings",
                "First Layer Adhesion Fix",
                "Why First Layers Are Slow",
            ],
            "description": "The first layer is the foundation of every print: everything above stacks on this one, so slicers print it far slower - typically 25-30 mm/s versus 60-100 mm/s for normal layers. A slow first layer gives molten plastic time to squish, flow outward, and mechanically grip the bed before cooling. Fast first layers skim and skid, leaving gaps and weak adhesion that no later setting can repair. The slower speed also lets the fan and bed temperature bond the material properly, which matters most on textured beds and sticky materials like PETG. Never raise first layer speed to chase print time - the foundation layer is where prints live or die.",
            "hashtags": ["#FirstLayer", "#3Dprinting", "#Adhesion", "#Slicer"],
            "seo_keywords": [
                "first layer speed",
                "initial layer speed settings",
                "first layer adhesion fix",
                "how slow first layer",
                "first layer squish",
                "bed adhesion first layer",
                "print foundation layer",
            ],
        },
        "fact_check": [
            "First layer speed is typically reduced to 25-30 mm/s versus normal speeds.",
            "Slow first layers give plastic time to squish and grip the bed.",
            "Fast first layers skid and leave unfillable gaps.",
            "The first layer speed setting is separate from normal print speed in slicers.",
            "First layer speed matters most on textured beds and sticky materials like PETG.",
        ],
    },
    # ======================================================================
    {
        "topic": "Nylon: PA",
        "core_question": "What does it take to print nylon (PA) successfully?",
        "learning_objective": "The viewer can explain nylon's properties and the drying, temperature, and adhesion discipline it demands.",
        "engineering_summary": "Nylon (polyamide, PA) is the workhorse engineering filament: tough, wear-resistant, and flexible, with real strength, fatigue resistance, and chemical resistance. Printing it is a discipline. Nylon is aggressively hygroscopic - it absorbs moisture from the air and must be dried for hours before printing, because wet nylon prints with steam bubbles, stringing, and weak parts. It needs a hot hotend (250-280 C), a hot bed, and an enclosure, because nylon warps like ABS. It also sticks aggressively to build surfaces: glue stick, dedicated nylon plates, or textured PEI are required, and glass-filled blends wear brass nozzles quickly. The payoff is parts that take abuse - functional gears, hinges, and tools that PLA could never survive.",
        "real_world_application": "Functional gears, flexible cable clamps, bushings, and wear parts use nylon; print farms keep it in sealed dry boxes.",
        "common_misconceptions": [
            "Nylon prints like PLA (it demands drying, high temperatures, and an enclosure)",
            "Nylon is waterproof (it is hygroscopic - it absorbs water, weakening it)",
            "Any plate works (nylon sticks so well it can destroy normal surfaces without a release layer)",
        ],
        "teaching_strategy": "Show the wet vs dry nylon symptom, the high-temperature setup, then the adhesion ritual and the tough part payoff.",
        "script": "Nylon, polyamide, is the workhorse engineering filament: tough, wear-resistant, and flexible, with real strength and chemical resistance. But printing it is a discipline. Nylon is aggressively hygroscopic - it soaks up moisture and must be dried for hours before printing. It needs a hot hotend, 250 to 280 degrees, a hot bed, and an enclosure, because nylon loves to warp. It also sticks to everything: build plates need glue stick, and glass-filled blends wear nozzles fast. The payoff: parts that take abuse - gears, hinges, and functional tools PLA could never survive.",
        "text_overlay": [
            "PA = TOUGH + WEAR-RESISTANT",
            "HYGROSCOPIC: DRY IT HOURS",
            "250-280, HOT BED, ENCLOSURE",
            "GLUE STICK OR IT NEVER LEAVES",
        ],
        "scenes": [
            {
                "goal": "Hook: the tough part",
                "teaching_point": "Gears and tools that take abuse",
                "shot": "wide shot of a nylon gear and hinge parts on a bench",
                "motion": "slow push-in on the gear teeth",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["nylon gear", "nylon hinge", "functional parts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of nylon gears and hinge parts on a dark bench, bright task light",
            },
            {
                "goal": "The drying",
                "teaching_point": "Hygroscopic means dry or fail",
                "shot": "macro shot of wet nylon printing with steam and stringing",
                "motion": "steam puffs and strings form",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["wet nylon", "steam", "stringing"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of wet nylon printing with steam and stringing, bright task light, print lab",
            },
            {
                "goal": "The temperatures",
                "teaching_point": "250-280, hot bed, enclosure",
                "shot": "wide shot of an enclosed printer running nylon",
                "motion": "print head moves in the enclosure",
                "lighting": "warm interior light",
                "background": "print lab",
                "objects": ["enclosed printer", "nylon spool", "hot bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an enclosed printer running nylon filament, warm interior light, print lab",
            },
            {
                "goal": "The adhesion",
                "teaching_point": "Nylon sticks to everything",
                "shot": "close-up of glue stick being applied to a build plate",
                "motion": "glue spreads across the plate",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["glue stick", "build plate", "release layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of glue stick being applied to a build plate for nylon, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Discipline buys tough parts",
                "shot": "wide hero shot of a finished nylon gear set in a clean lab",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["nylon gear set", "functional print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished nylon gear set in a clean lab, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nylon gear half-submerged in a moisture drop motif",
            "subject": "nylon gear with moisture warning",
            "background": "dark workshop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "gear center, moisture drop behind",
            "text": "NYLON: DRY IT FIRST",
            "elements": ["nylon gear", "moisture drop", "dry box"],
            "style": "material studio photography",
            "mood": "tough, disciplined, functional",
            "prompt": "photograph of a nylon gear with a moisture drop motif and dry box behind it, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Nylon: The Tough Filament",
            "title_variations": [
                "How to Print Nylon",
                "Nylon Filament Guide",
                "PA Filament Settings",
                "Nylon Printing Problems",
                "Strongest Flexible Filament",
            ],
            "description": "Nylon, polyamide, is the workhorse engineering filament: tough, wear-resistant, and flexible, with real strength, fatigue resistance, and chemical resistance. Printing it is a discipline. Nylon is aggressively hygroscopic - it absorbs moisture and must be dried for hours before printing, because wet nylon prints with steam bubbles, stringing, and weak parts. It needs a hot hotend (250-280 C), a hot bed, and an enclosure, because nylon warps like ABS. It also sticks aggressively: build plates need glue stick or dedicated surfaces, and glass-filled blends wear brass nozzles fast. The payoff is parts that take abuse - functional gears, hinges, and tools PLA could never survive.",
            "hashtags": ["#Nylon", "#PA", "#Filament", "#Engineering"],
            "seo_keywords": [
                "how to print nylon",
                "nylon filament settings",
                "PA filament guide",
                "nylon printing temperature",
                "nylon bed adhesion",
                "drying nylon filament",
                "nylon vs abs strength",
            ],
        },
        "fact_check": [
            "Nylon is tough, wear-resistant, and chemically resistant.",
            "Nylon is aggressively hygroscopic and must be dried before printing.",
            "Nylon requires 250-280 C hotend temperatures and a hot bed.",
            "Nylon warps like ABS and typically requires an enclosure.",
            "Nylon adheres aggressively and needs release layers like glue stick.",
        ],
    },
    # ======================================================================
    {
        "topic": "Bed Leveling Sensors",
        "core_question": "How do automatic bed leveling sensors actually work?",
        "learning_objective": "The viewer can explain mesh probing, the BLTouch vs inductive difference, and the limits of sensors.",
        "engineering_summary": "Bed leveling sensors replace the paper-feel ritual with measurement: a probe touches or senses points across the bed, records the height at each one, and builds a mesh of the surface. The firmware then compensates the nozzle height as it travels, so a warped or tilted bed still produces a consistent first layer. The classic choices: BLTouch, a pin that physically touches the bed with a magnet and servo, works on any surface; inductive sensors sense metal without touching, so they only work on metal beds. The mesh is only as good as the probe's repeatability: a loose mount, over-rotated arm, or wildly warped bed defeats the sensor, and a tilted frame is not a mesh problem. Level the frame, then trust the mesh.",
        "real_world_application": "Nearly every modern printer ships with a probe or touch sensor; mesh compensation is what makes textured PEI sheets and slightly warped beds work reliably.",
        "common_misconceptions": [
            "A sensor makes manual leveling obsolete (the frame must still be square and the offset set)",
            "Inductive sensors work on any bed (they only sense metal surfaces)",
            "The mesh is perfect (probe repeatability and mount rigidity limit accuracy)",
        ],
        "teaching_strategy": "Show the probing pattern building a mesh, the BLTouch vs inductive comparison, then the sensor failure modes.",
        "script": "Bed leveling sensors replace the paper-feel ritual with measurement: a probe touches points across the bed, measures each height, and builds a mesh of the surface. Firmware then compensates as the nozzle travels, so a warped bed still gives a consistent first layer. The classic choices: BLTouch, a pin that physically touches the bed, and inductive sensors that sense metal without touching - which only work on metal beds. Sensors handle meshes, not madness: a wildly warped bed, loose probe, or over-rotated arm fools them. Level the frame, then trust the mesh.",
        "text_overlay": [
            "PROBE + MESH = COMPENSATION",
            "BLTOUCH: TOUCHES, ANY SURFACE",
            "INDUCTIVE: METAL ONLY",
            "LEVEL THE FRAME FIRST",
        ],
        "scenes": [
            {
                "goal": "Hook: the probing pattern",
                "teaching_point": "Points become a mesh",
                "shot": "graphic-style shot of a probe touching bed points forming a mesh grid",
                "motion": "dots light up in a grid pattern",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["probe diagram", "bed points", "mesh grid"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a probing pattern diagram building a bed mesh grid on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The BLTouch",
                "teaching_point": "A pin that physically touches",
                "shot": "close-up of a BLTouch pin deploying to touch the bed",
                "motion": "pin lowers, touches, retracts",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["BLTouch", "deployed pin", "bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a BLTouch pin deploying to touch the print bed, bright task lighting, print lab",
            },
            {
                "goal": "The inductive sensor",
                "teaching_point": "Senses metal, no touching",
                "shot": "medium shot of an inductive sensor hovering above a metal bed",
                "motion": "sensor stops at the metal surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["inductive sensor", "metal bed", "gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an inductive sensor hovering above a metal print bed, bright task lighting, print lab",
            },
            {
                "goal": "The limits",
                "teaching_point": "Sensors can be fooled",
                "shot": "tabletop shot of a sensor on a loose mount with a tilted frame",
                "motion": "mount wobbles as the probe deploys",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["loose probe mount", "tilted frame"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a loose probe mount and tilted printer frame, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Frame first, mesh second",
                "shot": "wide hero shot of a printer probing its bed and printing a perfect first layer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer probing", "perfect first layer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer probing the bed then printing a perfect first layer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A probe touching a grid of bed points with a mesh overlay",
            "subject": "probe with bed mesh grid",
            "background": "dark print lab blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "probe center, mesh overlay",
            "text": "BED LEVELING SENSORS",
            "elements": ["probe", "mesh grid", "print bed"],
            "style": "diagnostic studio photography",
            "mood": "measured, compensated, precise",
            "prompt": "photograph of a bed leveling probe over a mesh grid overlay on a print bed, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bed Leveling Sensors: Mesh Magic",
            "title_variations": [
                "How Auto Bed Leveling Works",
                "BLTouch vs Inductive Sensor",
                "Probe and Mesh Explained",
                "Bed Mesh Compensation",
                "Why Probes Fail",
            ],
            "description": "Bed leveling sensors replace the paper-feel ritual with measurement: a probe touches or senses points across the bed, records each height, and builds a mesh of the surface. The firmware then compensates the nozzle height as it travels, so a warped or tilted bed still gives a consistent first layer. The classic choices: BLTouch, a pin that physically touches the bed and works on any surface, and inductive sensors that sense metal without touching, which only work on metal beds. The mesh is only as good as the probe's repeatability: loose mounts, over-rotated arms, or wildly warped beds defeat it. Level the frame, then trust the mesh.",
            "hashtags": ["#BLTouch", "#3Dprinting", "#BedLeveling", "#Hardware"],
            "seo_keywords": [
                "how auto bed leveling works",
                "bltouch vs inductive sensor",
                "bed mesh compensation",
                "probe repeatability",
                "bed leveling sensor explained",
                "printer probe setup",
                "first layer mesh leveling",
            ],
        },
        "fact_check": [
            "Probes sample points across the bed and firmware builds a compensation mesh.",
            "BLTouch uses a physically deployed pin and works on any bed surface.",
            "Inductive sensors only sense metal beds.",
            "Mesh accuracy is limited by probe repeatability and mount rigidity.",
            "A tilted or un-square frame must be fixed before relying on the mesh.",
        ],
    },
    # ======================================================================
    {
        "topic": "Blobs & Zits",
        "core_question": "Why do I get little bumps on my print surface, and how do I fix them?",
        "learning_objective": "The viewer can diagnose bump patterns and fix the pressure, material, or motion causes.",
        "engineering_summary": "Blobs and zits are small bumps of excess plastic on a print's surface, often repeating at the same spot on every layer. The classic cause is nozzle pressure: filament keeps oozing while the nozzle changes direction, retracts, or hops, and the built-up pressure dumps a bump when extrusion resumes. The fix sequence starts with retraction distance and speed, then temperature, then the slicer's pressure-relief tools: coasting, which stops extruding just before the move ends, and wipe, which drags the nozzle to bleed pressure off. Wet filament and over-extrusion add random bumps. The detective clue is consistency: same spot every layer means pressure and motion; random bumps mean material. Match the cause to the pattern.",
        "real_world_application": "Vases, enclosures, and any smooth-surface print show blobs immediately; the pressure-relief settings fix them without post-processing.",
        "common_misconceptions": [
            "Blobs are always retraction (pressure, temperature, and material causes also matter)",
            "More retraction always fixes them (excess retraction causes gaps and new blobs)",
            "Blobs are cosmetic only (they catch on print heads, snag, and ruin functional parts)",
        ],
        "teaching_strategy": "Show the repeating bump pattern, the pressure buildup animation, then the fix sequence and the random-vs-repeat diagnosis.",
        "script": "Blobs and zits are the pimples on your print's surface: little bumps of excess plastic, usually at the same spots on every layer. The classic cause is pressure buildup in the nozzle: filament oozes while the nozzle changes direction, and the extra pressure dumps a bump when extrusion resumes. The fix sequence: calibrate retraction and temperature first, then coasting and wipe, which bleed pressure off before the nozzle lifts. Wet filament and over-extrusion also add bumps. The clue is consistency - same spot every layer means pressure; random bumps mean material. Match the cause, kill them.",
        "text_overlay": [
            "PRESSURE DUMPS = BUMPS",
            "RETRACTION + TEMP FIRST",
            "COASTING + WIPE BLEED PRESSURE",
            "SAME SPOT = MOTION, RANDOM = MATERIAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the pimples",
                "teaching_point": "Bumps in a repeating rhythm",
                "shot": "macro shot of a print surface with a column of blobs",
                "motion": "slow pan up the blob column",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["blob column", "print surface"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a print surface with a repeating column of blobs, raking side light, dark bench",
            },
            {
                "goal": "The pressure",
                "teaching_point": "Ooze builds pressure, resume dumps it",
                "shot": "graphic-style shot of a nozzle cross-section with pressure building",
                "motion": "pressure gauge rises, bump releases",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle diagram", "pressure gauge", "bump"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle pressure diagram with a rising gauge on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The fixes",
                "teaching_point": "Retraction, temperature, coasting, wipe",
                "shot": "slicer screen shot with retraction and wipe settings highlighted",
                "motion": "settings highlight in sequence",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slicer screen", "retraction", "coasting settings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer screen with retraction and coasting settings highlighted, clean viewport lighting",
            },
            {
                "goal": "The diagnosis",
                "teaching_point": "Repeat means motion, random means material",
                "shot": "tabletop shot of two prints: one with repeat blobs, one with random bumps",
                "motion": "tilt between the two patterns",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["repeat blob print", "random bump print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two prints showing repeat blobs versus random bumps, neutral lab lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the cause, kill the bumps",
                "shot": "wide hero shot of a smooth blob-free print on the printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth blob-free print on the printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A print surface with blobs on one side and smooth on the other",
            "subject": "print with blobs and clean half",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "blobbed half left, clean half right",
            "text": "BLOBS & ZITS",
            "elements": ["blob column", "clean surface", "pressure icon"],
            "style": "diagnostic macro photography",
            "mood": "bumpy, diagnostic, fixable",
            "prompt": "macro photograph of a print with a blobbed half and a clean half, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Blobs & Zits: Kill the Bumps",
            "title_variations": [
                "Why Prints Have Blobs",
                "Blobs on Print Surface Fix",
                "Nozzle Pressure Blobs",
                "Coasting and Wipe Explained",
                "Zits on 3D Prints",
            ],
            "description": "Blobs and zits are small bumps of excess plastic on a print's surface, often repeating at the same spot on every layer. The classic cause is nozzle pressure: filament keeps oozing while the nozzle changes direction, and the built-up pressure dumps a bump when extrusion resumes. The fix sequence starts with retraction distance and speed, then temperature, then the slicer's pressure-relief tools: coasting, which stops extruding before the move ends, and wipe, which drags the nozzle to bleed pressure off. Wet filament and over-extrusion add random bumps. The clue is consistency: same spot every layer means pressure and motion; random bumps mean material.",
            "hashtags": ["#Blobs", "#3Dprinting", "#Troubleshooting", "#Quality"],
            "seo_keywords": [
                "blobs on 3d print",
                "zits on print surface",
                "nozzle pressure blobs",
                "coasting and wipe settings",
                "blob fix retraction",
                "bumps on print layers",
                "over extrusion bumps",
            ],
        },
        "fact_check": [
            "Blobs often repeat at the same position on every layer.",
            "Nozzle pressure buildup dumps excess plastic when extrusion resumes.",
            "Retraction, temperature, coasting, and wipe are the primary fixes.",
            "Wet filament and over-extrusion produce random surface bumps.",
            "Repeating bumps indicate motion and pressure; random bumps indicate material.",
        ],
    },
    # ======================================================================
    {
        "topic": "Living Hinges",
        "core_question": "How do I design a living hinge that survives thousands of folds?",
        "learning_objective": "The viewer can design thin flexure hinges with correct orientation, geometry, and material.",
        "engineering_summary": "A living hinge is a thin section of material that flexes instead of using a pin: one continuous piece of plastic that folds thousands of times. The design secret is geometry. The hinge needs a thin, flexible web - usually one or two layer lines thick, printed flat so the layers run along the fold - and generous fillets where sharp corners would tear. Material matters: PETG and polypropylene flex far more cycles than brittle PLA. Width, length, and fold angle all tune the bending stress: wider and shorter hinges bend less per fold, and a shallower fold angle reduces peak strain. Keep the web thin and the radius generous, and a printed hinge will out-flex any replacement. Geometry, orientation, material - the three rules of living hinges.",
        "real_world_application": "Battery compartments, box lids, dust covers, and foldable fixtures use living hinges; 3D-printed polypropylene hinges survive tens of thousands of cycles.",
        "common_misconceptions": [
            "Living hinges are a special material (they are geometry - a thin web in a flex-friendly material)",
            "Orientation does not matter (layers must run along the fold, or the hinge snaps quickly)",
            "Thicker means stronger (thicker webs bend with more stress and fail sooner)",
        ],
        "teaching_strategy": "Show the thin web geometry, the layer orientation rule, the fillet detail, then a folding demonstration.",
        "script": "A living hinge is a thin section of material that flexes instead of using a pin: one piece of plastic that folds thousands of times. The secret is geometry: a thin web, one or two layer lines thick, printed flat so the layers run along the fold, with generous fillets where sharp corners would tear. Material matters: PETG and polypropylene flex far more than brittle PLA. Width, length, and fold angle tune the bending stress. Keep the web thin and the radius generous, and a printed hinge will out-flex any replacement. Geometry, orientation, material - the three rules.",
        "text_overlay": [
            "THIN WEB = THE HINGE",
            "LAYERS RUN ALONG THE FOLD",
            "FILLETS STOP TEARS",
            "PETG + PP > PLA",
        ],
        "scenes": [
            {
                "goal": "Hook: the folding box",
                "teaching_point": "One piece, thousands of folds",
                "shot": "macro shot of a box lid hinging open on a thin plastic web",
                "motion": "lid folds open and closed repeatedly",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["box lid", "living hinge", "folding"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a box lid folding open on a living hinge, bright task light, dark bench",
            },
            {
                "goal": "The geometry",
                "teaching_point": "Thin web, generous fillets",
                "shot": "graphic-style shot of a hinge cross-section with web and fillets",
                "motion": "section highlights the web thickness",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hinge cross-section", "web", "fillet"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a living hinge cross-section diagram with web and fillet callouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The orientation",
                "teaching_point": "Layers run along the fold",
                "shot": "tabletop shot of two hinges, one with layers along the fold and one across",
                "motion": "correct hinge flexes, wrong one snaps",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["correct hinge", "wrong hinge", "layer lines"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two printed living hinges with different layer orientations on a test bench, neutral lab lighting",
            },
            {
                "goal": "The material",
                "teaching_point": "PETG and PP outlast PLA",
                "shot": "tabletop shot of PETG and PP hinge samples being flexed",
                "motion": "samples fold without snapping",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["PETG hinge", "PP hinge", "flexing"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of PETG and polypropylene hinge samples being flexed, neutral lab lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Geometry, orientation, material",
                "shot": "wide hero shot of a fully open foldable print working smoothly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["foldable print", "living hinge"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a foldable print with a living hinge working smoothly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A thin flexure web bending with layer lines visible",
            "subject": "living hinge bending open",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "hinge center, layer lines lit",
            "text": "LIVING HINGES",
            "elements": ["thin web", "layer lines", "fold radius"],
            "style": "design macro photography",
            "mood": "flexible, thin, resilient",
            "prompt": "macro photograph of a living hinge bending open with visible layer lines, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Living Hinges: Fold It Forever",
            "title_variations": [
                "How to Design a Living Hinge",
                "Living Hinge 3D Printing",
                "Flexible Hinge Design",
                "PETG Living Hinge",
                "Printed Hinge Orientation",
            ],
            "description": "A living hinge is a thin section of material that flexes instead of using a pin: one continuous piece of plastic that folds thousands of times. The design secret is geometry: a thin web, usually one or two layer lines thick, printed flat so the layers run along the fold, with generous fillets where sharp corners would tear. Material matters: PETG and polypropylene flex far more cycles than brittle PLA. Width, length, and fold angle all tune the bending stress: wider and shorter hinges bend less per fold, and a shallower fold angle reduces peak strain. Keep the web thin and the radius generous, and a printed hinge will out-flex any replacement. Geometry, orientation, material.",
            "hashtags": ["#LivingHinge", "#Design", "#3Dprinting", "#Flexures"],
            "seo_keywords": [
                "living hinge design",
                "living hinge 3d printing",
                "printed hinge orientation",
                "PETG living hinge",
                "flexible hinge web",
                "living hinge layer direction",
                "designing flexures",
            ],
        },
        "fact_check": [
            "Living hinges use a thin flexure web instead of a pin joint.",
            "Layer lines must run along the fold direction for hinge survival.",
            "Fillets at the web ends prevent stress tears.",
            "PETG and polypropylene endure far more flex cycles than PLA.",
            "Bending stress in a hinge is tuned by web width, length, and fold angle.",
        ],
    },
    # ======================================================================
    {
        "topic": "Spur vs Helical Gears",
        "core_question": "Why are some gears noisy, and what do helical gears change?",
        "learning_objective": "The viewer can compare spur and helical engagement and choose between noise, smoothness, and cost.",
        "engineering_summary": "Spur gears have straight teeth parallel to the shaft, simple to cut and cheap to make. But straight teeth engage along their whole length at once, so the shock of each tooth contact is delivered simultaneously - making spur gears noisy and rough at speed. Helical gears cut their teeth at an angle, so engagement starts at one end and rolls across the tooth face: contact is always happening somewhere, which makes them smoother, quieter, and stronger under high loads. The price: angled teeth produce an axial thrust force that pushes the gears along their shafts, requiring thrust bearings, and helical gears cost more to manufacture. For printed gears, spur teeth dominate because they print cleanly and need no angled-tooth complications. Smooth and fast means helical; simple and printed means spur.",
        "real_world_application": "Car gearboxes and high-speed industrial drives use helical gears for quiet smooth operation; printed mechanisms and cheap gearboxes use spur gears.",
        "common_misconceptions": [
            "Noise means bad gears (spur gears are inherently noisier than helical)",
            "Helical gears are just quieter (they also carry more load through gradual engagement)",
            "Axial thrust is free (angled teeth push sideways and need thrust bearings)",
        ],
        "teaching_strategy": "Show both tooth shapes, the whole-length vs rolling engagement, then the axial thrust trade and the printed gear verdict.",
        "script": "Spur gears are the straight-toothed classics: teeth parallel to the shaft, simple to cut and cheap. But straight teeth engage along their whole length at once, so they run noisy and shocky. Helical gears cut teeth at an angle, so engagement starts at one end and rolls across the face - contact never stops, making them smoother, quieter, and stronger at high loads. The price: angled teeth push sideways along the shaft, needing thrust bearings and costing more. Printed gears are usually spurs, printing without angled-teeth complications. Smooth and fast means helical; simple and printed means spur.",
        "text_overlay": [
            "SPUR: WHOLE TOOTH AT ONCE",
            "HELICAL: ROLLS ACROSS",
            "ANGLE = THRUST FORCE",
            "PRINTED = SPUR, DRIVEN = HELICAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the noisy gearbox",
                "teaching_point": "Straight teeth clash at speed",
                "shot": "macro shot of spur gears meshing with visible shock",
                "motion": "teeth engage along their full length",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["spur gears", "tooth engagement", "shock"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of spur gears meshing with visible tooth shock, bright task light, dark bench",
            },
            {
                "goal": "The engagement",
                "teaching_point": "Whole length vs rolling contact",
                "shot": "graphic-style shot comparing straight and angled tooth engagement",
                "motion": "contact line sweeps across the helical tooth",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["engagement diagram", "spur teeth", "helical teeth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of spur and helical gear engagement diagrams on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The thrust",
                "teaching_point": "Angled teeth push sideways",
                "shot": "graphic-style shot of helical gears with axial thrust arrows",
                "motion": "thrust arrows push along the shaft",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["helical gear diagram", "thrust arrows", "shaft"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of helical gear diagrams with axial thrust arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The printed choice",
                "teaching_point": "Spurs print without complications",
                "shot": "tabletop shot of printed spur gears on a printed gearbox",
                "motion": "gears turn smoothly in the print",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["printed spur gears", "printed gearbox"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of 3D printed spur gears turning in a printed gearbox, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the gear to the job",
                "shot": "wide hero shot of a quiet helical gearbox beside a simple spur gear train",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["helical gearbox", "spur gear train"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a helical gearbox beside a spur gear train, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Spur and helical gears side by side with a noise meter",
            "subject": "spur and helical gears with noise meter",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "two gears split, meter between",
            "text": "SPUR VS HELICAL",
            "elements": ["spur gear", "helical gear", "noise meter"],
            "style": "mechanical studio photography",
            "mood": "meshing, comparative, mechanical",
            "prompt": "macro photograph of spur and helical gears with a noise meter between them, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Spur vs Helical Gears",
            "title_variations": [
                "Why Helical Gears Are Quieter",
                "Spur Gear Noise Explained",
                "Helical Gear Engagement",
                "Which Gear Should I Use",
                "Gear Types Explained",
            ],
            "description": "Spur gears have straight teeth parallel to the shaft, simple to cut and cheap to make. But straight teeth engage along their whole length at once, delivering the shock of each tooth contact simultaneously - making spur gears noisy and rough at speed. Helical gears cut teeth at an angle, so engagement starts at one end and rolls across the tooth face, with contact always happening somewhere: smoother, quieter, and stronger under high loads. The price is axial thrust: angled teeth push the gears along their shafts, requiring thrust bearings, and helical gears cost more to manufacture. Printed gears dominate as spurs because they print cleanly. Smooth and fast means helical; simple and printed means spur.",
            "hashtags": ["#Gears", "#SpurGear", "#HelicalGear", "#Mechanics"],
            "seo_keywords": [
                "spur vs helical gears",
                "why helical gears are quieter",
                "helical gear engagement",
                "spur gear noise",
                "axial thrust gears",
                "gear types explained",
                "printed gears helical",
            ],
        },
        "fact_check": [
            "Spur gear teeth are parallel to the shaft and engage along their full length at once.",
            "Helical teeth engage progressively, providing smoother and quieter operation.",
            "Helical gears generate axial thrust that requires thrust bearings.",
            "Helical gears carry higher loads but cost more to manufacture.",
            "Printed gears are usually spur gears for printability.",
        ],
    },
    # ======================================================================
    {
        "topic": "Heat Transfer: Conduction",
        "core_question": "How does heat move through metal, and why do metals conduct so well?",
        "learning_objective": "The viewer can explain conduction, the free-electron mechanism, and the factors that set conduction rate.",
        "engineering_summary": "Conduction is heat moving through a material without the material itself moving: hot atoms jiggle, pass the motion to their neighbors, and the heat walks through. Metals conduct exceptionally well because free electrons carry energy fast through the lattice - that is why a brass nozzle heats in seconds and why heatsinks are aluminum. Plastics conduct terribly; they trap heat, which is why printed parts cool unevenly and why hotend heat breaks rely on a plastic-free thermal gradient. The conduction rate depends on three factors: the material's thermal conductivity, the cross-sectional area, and the temperature difference across it. Doubling the temperature gap doubles the heat flow. Copper beats aluminum, aluminum beats steel, and plastic beats nothing.",
        "real_world_application": "Heatsinks, hotend heat blocks, and heat breaks are designed around conductivity: copper blocks, aluminum sinks, and thermal pastes bridge tiny gaps.",
        "common_misconceptions": [
            "Heat travels by the material moving (conduction passes vibration, not mass)",
            "Thicker material always conducts faster (area helps; length resists)",
            "All metals conduct the same (copper, aluminum, and steel differ by many times)",
        ],
        "teaching_strategy": "Show the atom jiggle chain, the free-electron difference, then the conductivity comparison and the hotend example.",
        "script": "Conduction is heat moving through a material without the material moving: hot atoms jiggle, pass the motion to their neighbors, and the heat walks through. Metals conduct because free electrons carry energy fast - that's why a brass nozzle heats in seconds and heatsinks are aluminum. Plastics conduct terribly, trapping heat, which is why prints cool unevenly. The conduction rate depends on three things: the material's thermal conductivity, the area, and the temperature difference. Doubling the temperature gap doubles the heat flow. Copper beats aluminum, aluminum beats steel, and plastic beats nothing.",
        "text_overlay": [
            "ATOMS JIGGLE, HEAT WALKS",
            "FREE ELECTRONS = METALS WIN",
            "RATE = MATERIAL × AREA × ΔT",
            "DOUBLE ΔT = DOUBLE FLOW",
        ],
        "scenes": [
            {
                "goal": "Hook: the jiggling atoms",
                "teaching_point": "Heat passes vibration, not mass",
                "shot": "graphic-style shot of atoms jiggling and passing motion along a chain",
                "motion": "jiggle wave travels through the atoms",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["atom chain", "jiggle wave", "heat motion"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an atom chain passing a jiggle wave on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The metals",
                "teaching_point": "Free electrons carry energy fast",
                "shot": "graphic-style shot of a metal lattice with free electrons moving",
                "motion": "electrons stream through the lattice",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["metal lattice", "free electrons", "energy flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a metal lattice diagram with free electrons streaming on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The hotend",
                "teaching_point": "Conductivity designs the hotend",
                "shot": "macro shot of a brass nozzle and aluminum heatsink",
                "motion": "heat block glows, heatsink stays cool",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["brass nozzle", "aluminum heatsink", "heat gradient"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a brass nozzle and aluminum heatsink with a visible heat gradient, warm task light, dark bench",
            },
            {
                "goal": "The comparison",
                "teaching_point": "Copper, aluminum, steel, plastic",
                "shot": "graphic-style shot of a conductivity bar chart",
                "motion": "bars rise in conductivity order",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["conductivity chart", "material bars"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a thermal conductivity bar chart for copper aluminum steel and plastic on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Area, gap, and material set the rate",
                "shot": "wide hero shot of a copper heat block and finned sink in a lab",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["copper heat block", "finned heatsink"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a copper heat block with a finned heatsink in a lab, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A metal bar with a heat gradient and jiggling atoms",
            "subject": "metal bar with conduction gradient",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "bar horizontal, gradient along it",
            "text": "CONDUCTION",
            "elements": ["metal bar", "heat gradient", "atom chain"],
            "style": "physics studio photography",
            "mood": "conductive, gradient, clear",
            "prompt": "macro photograph of a metal bar with a conduction heat gradient and atom chain, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Conduction: How Heat Walks",
            "title_variations": [
                "How Heat Moves Through Metal",
                "Thermal Conduction Explained",
                "Why Metals Conduct Heat",
                "Conduction Rate Factors",
                "Heat Transfer Basics",
            ],
            "description": "Conduction is heat moving through a material without the material moving: hot atoms jiggle, pass the motion to their neighbors, and the heat walks through. Metals conduct exceptionally well because free electrons carry energy fast through the lattice - why a brass nozzle heats in seconds and heatsinks are aluminum. Plastics conduct terribly, trapping heat, which is why printed parts cool unevenly. The conduction rate depends on three factors: the material's thermal conductivity, the cross-sectional area, and the temperature difference across it. Doubling the temperature gap doubles the heat flow. Copper beats aluminum, aluminum beats steel, and plastic beats nothing.",
            "hashtags": ["#Conduction", "#Physics", "#HeatTransfer", "#Thermodynamics"],
            "seo_keywords": [
                "how heat moves through metal",
                "thermal conduction explained",
                "why metals conduct heat",
                "conduction rate factors",
                "thermal conductivity comparison",
                "heat transfer basics",
                "hotend thermal design",
            ],
        },
        "fact_check": [
            "Conduction transfers heat by atomic vibration without bulk material motion.",
            "Free electrons give metals high thermal conductivity.",
            "Conduction rate scales with conductivity, area, and temperature difference.",
            "Doubling the temperature difference doubles the heat flow.",
            "Copper, aluminum, and steel differ significantly in conductivity.",
        ],
    },
    # ======================================================================
    {
        "topic": "Sheet Metal Bending",
        "core_question": "How does a press brake bend sheet metal, and why do flat patterns come out short?",
        "learning_objective": "The viewer can explain the bend allowance, K-factor, and minimum bend radius rules.",
        "engineering_summary": "Sheet metal bends because the outer fibers stretch and the inner fibers compress around the bend radius. A press brake pushes a punch into the sheet over a die, and the material yields and forms. The engineering secret is the bend allowance: inside the sheet, the neutral axis keeps its original length, and the flat pattern must account for the material stretched around the bend - get the allowance wrong, and the part comes out short. K-factor is the position of that neutral axis, usually about a third to half the material thickness from the inner face. Sharp bends crack the stretched outer fibers, so the bend radius should be at least the material thickness. Measure, bend, and the flat pattern pays the bill.",
        "real_world_application": "Enclosures, brackets, and frames are cut flat then bent; CAD software applies K-factor and bend allowance automatically, but operators still verify with bend tests.",
        "common_misconceptions": [
            "Bending stretches the whole sheet (only the outer fibers stretch; the neutral axis keeps length)",
            "Bend radius is cosmetic (too sharp a radius cracks the outside fibers)",
            "A flat pattern is just the part unfolded (the bend allowance must be added or the part comes out short)",
        ],
        "teaching_strategy": "Show the press brake operation, the neutral axis concept, then a flat pattern comparison and the radius rule.",
        "script": "Sheet metal bends because outer fibers stretch and inner fibers compress. A press brake pushes a punch into the sheet, and the material forms. The secret is the bend allowance: the neutral axis keeps its original length, and the flat pattern must account for the stretch around the bend - get it wrong, and the part comes out short. K-factor is the position of that neutral axis, usually a third to half the thickness. Sharp bends crack the outside fibers, so keep the bend radius at least one thickness. Measure, bend, and the pattern pays the bill.",
        "text_overlay": [
            "OUTER STRETCHES, INNER COMPRESSES",
            "NEUTRAL AXIS KEEPS LENGTH",
            "K-FACTOR = AXIS POSITION",
            "RADIUS ≥ THICKNESS",
        ],
        "scenes": [
            {
                "goal": "Hook: the press brake",
                "teaching_point": "Punch and die form the sheet",
                "shot": "medium shot of a press brake bending a sheet over a die",
                "motion": "punch descends, sheet folds",
                "lighting": "bright shop light",
                "background": "sheet metal shop",
                "objects": ["press brake", "punch", "die"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a press brake bending sheet metal over a die, bright shop lighting, sheet metal shop",
            },
            {
                "goal": "The fibers",
                "teaching_point": "Stretch outside, compress inside",
                "shot": "graphic-style shot of a bent sheet cross-section with fiber zones",
                "motion": "outer zone stretches, inner compresses",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bend cross-section", "stretch zone", "compress zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bent sheet metal cross-section with stretch and compress zones on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The allowance",
                "teaching_point": "The flat pattern must include the bend",
                "shot": "tabletop shot of a short bent part beside its flat pattern",
                "motion": "part measured against the pattern",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["bent part", "flat pattern", "measurement"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bent sheet metal part beside its flat pattern with measurements, neutral lab lighting, workbench",
            },
            {
                "goal": "The radius",
                "teaching_point": "Sharp bends crack the fibers",
                "shot": "macro shot of a cracked bend on a sharp radius",
                "motion": "crack line visible along the bend",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["cracked bend", "sharp radius"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a cracked bend caused by a too-sharp radius, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Allowance plus radius",
                "shot": "wide hero shot of a finished bent enclosure frame",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["bent enclosure", "clean bends"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished sheet metal enclosure with clean bends, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bent sheet with the neutral axis line highlighted",
            "subject": "sheet metal bend with neutral axis",
            "background": "dark workshop blur",
            "angle": "profile close-up",
            "lighting": "hard key with rim",
            "composition": "bend profile center, axis dashed",
            "text": "SHEET METAL BENDING",
            "elements": ["bent sheet", "neutral axis", "radius"],
            "style": "manufacturing studio photography",
            "mood": "formed, precise, industrial",
            "prompt": "profile photograph of a sheet metal bend with the neutral axis line highlighted, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Sheet Metal Bending: The Allowance",
            "title_variations": [
                "How Press Brakes Work",
                "Bend Allowance Explained",
                "K-Factor for Sheet Metal",
                "Why Bends Crack",
                "Flat Pattern Design",
            ],
            "description": "Sheet metal bends because the outer fibers stretch and the inner fibers compress around the bend radius. A press brake pushes a punch into the sheet over a die, and the material yields and forms. The engineering secret is the bend allowance: the neutral axis keeps its original length, and the flat pattern must account for the material stretched around the bend - get it wrong, and the part comes out short. K-factor is the position of that neutral axis, usually a third to half the material thickness. Sharp bends crack the stretched outer fibers, so the bend radius should be at least the material thickness. Measure, bend, and the flat pattern pays the bill.",
            "hashtags": ["#SheetMetal", "#PressBrake", "#Manufacturing", "#Metalworking"],
            "seo_keywords": [
                "sheet metal bending",
                "bend allowance explained",
                "k factor sheet metal",
                "press brake how it works",
                "minimum bend radius",
                "flat pattern design",
                "why sheet metal cracks at bends",
            ],
        },
        "fact_check": [
            "Bending stretches outer fibers and compresses inner fibers.",
            "The neutral axis keeps its original length through the bend.",
            "Bend allowance accounts for the stretch in the flat pattern.",
            "K-factor is the neutral axis position, typically a third to half the thickness.",
            "Bend radius should be at least the material thickness to avoid cracking.",
        ],
    },
]
