"""Batch 27: DFM, annealing, forging, die casting, threads, steppers, structural vibration, TIM."""

CURATED = [
    # ======================================================================
    {
        "topic": "DFM Principles",
        "core_question": "Why does the same part cost ten times more in one process?",
        "learning_objective": "The viewer understands design for manufacturing and process-aware design.",
        "engineering_summary": "Design for manufacturing means shaping a part for the way it will be made: draft for molds, straight pulls for dies, clearance for tools, and standard sizes for stock. The same geometry that prints for free can be impossible to cast or expensive to mill. Designers move the cost at the drawing stage, where changes are cheap. The part is easy to make, or the price says otherwise.",
        "real_world_application": "Molded, machined, and printed parts all punish designs that ignore the process.",
        "common_misconceptions": [
            "Design is finished before manufacturing (the process shapes the design)",
            "CAD makes anything (the process sets the limits)",
            "DFM is for factories (it applies to every process)",
        ],
        "teaching_strategy": "Take one part and show how casting, milling, and printing each reshape it.",
        "script": "Design for manufacturing means shaping a part for the way it will be made: draft for molds, straight pulls for dies, clearance for tools, and standard sizes for stock. The same geometry that prints for free can be impossible to cast or expensive to mill. Designers move the cost at the drawing stage, where changes are cheap. The part is easy to make, or the price says otherwise.",
        "text_overlay": [
            "SHAPE IT FOR THE PROCESS",
            "DRAFT FOR MOLDS",
            "CLEARANCE FOR TOOLS",
            "COST MOVES AT THE DRAWING",
        ],
        "scenes": [
            {
                "goal": "Hook: the same part",
                "teaching_point": "One part, three prices",
                "shot": "medium shot of one part designed for casting, milling, and printing",
                "motion": "camera pans the three versions",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["cast version", "milled version", "printed version"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of one part designed for casting, milling, and printing, neutral lab lighting, workbench",
            },
            {
                "goal": "The draft",
                "teaching_point": "Molds need draft",
                "shot": "diagram-style shot of a part with draft angles",
                "motion": "angled walls light up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["molded part", "draft angles", "pull direction"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of draft angles for molding, clean engineering visualization on a dark background",
            },
            {
                "goal": "The clearance",
                "teaching_point": "Tools need room",
                "shot": "diagram-style shot of a cutter reaching into a pocket",
                "motion": "tool path clears the walls",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pocket", "cutter", "clearance zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tool clearance in a milled pocket, clean engineering visualization on a dark background",
            },
            {
                "goal": "The stock",
                "teaching_point": "Standard sizes for stock",
                "shot": "medium shot of standard stock bars and sheets",
                "motion": "part snaps to stock sizes",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["stock bars", "sheets", "part outline"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of standard stock bars and sheets on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cost moves at the drawing",
                "shot": "wide hero shot of a drawing beside its finished parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["drawing", "finished parts", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a drawing beside its finished parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "One part with draft, tool clearance, and stock markers overlaid",
            "subject": "DFM principles",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, process markers around",
            "text": "SHAPE IT FOR THE PROCESS",
            "elements": ["part", "draft markers", "tool clearance"],
            "style": "geometry studio photography",
            "mood": "designed, manufacturable, cheap",
            "prompt": "photograph of one part with draft, tool clearance, and stock markers overlaid, and a mold pull direction, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "DFM Principles: Shape It for the Process",
            "title_variations": [
                "What Is Design for Manufacturing",
                "DFM Explained Simply",
                "Design for Manufacturing Basics",
                "Manufacturable Design Rules",
                "DFM vs DFA",
            ],
            "description": "Design for manufacturing means shaping a part for the way it will be made: draft for molds, straight pulls for dies, clearance for tools, and standard sizes for stock. The same geometry that prints for free can be impossible to cast or expensive to mill. Cost moves at the drawing stage, where changes are cheap. This short takes one part through casting, milling, and printing and shows the rules behind a manufacturable design.",
            "hashtags": ["#DFM", "#DesignForManufacturing", "#Manufacturing", "#Engineering"],
            "seo_keywords": [
                "what is design for manufacturing",
                "dfm principles",
                "manufacturable design",
                "draft angles molds",
                "tool clearance pockets",
                "standard stock sizes",
                "dfm vs dfa",
            ],
        },
        "fact_check": [
            "DFM shapes parts for their process.",
            "Molds need draft angles.",
            "Tools need clearance.",
            "Standard stock sizes reduce cost.",
            "Cost is set at the drawing stage.",
        ],
    },
    {
        "topic": "Annealing & Tempering",
        "core_question": "What does the heat do to the steel?",
        "learning_objective": "The viewer understands annealing and tempering as heat treatments.",
        "engineering_summary": "Annealing and tempering are heat treatments that rewrite a metal's internal structure. Annealing heats the metal, soaks it, and cools it slowly, leaving it soft, stress-free, and easy to machine. Tempering heats hardened steel to a lower temperature, trading a little hardness for toughness, so a blade bends instead of snapping. The temperature decides the result, and the cool is half the recipe.",
        "real_world_application": "Machined parts are annealed for workability, and tools are tempered for toughness.",
        "common_misconceptions": [
            "Heat only softens (it also relieves stress and tunes toughness)",
            "Annealing and tempering are the same (different goals, different heats)",
            "Cooling rate is optional (it sets the structure)",
        ],
        "teaching_strategy": "Annealed and tempered samples, then bend them to compare.",
        "script": "Annealing and tempering are heat treatments that rewrite a metal's internal structure. Annealing heats the metal, soaks it, and cools it slowly, leaving it soft, stress-free, and easy to machine. Tempering heats hardened steel to a lower temperature, trading a little hardness for toughness, so a blade bends instead of snapping. The temperature decides the result, and the cool is half the recipe.",
        "text_overlay": [
            "HEAT REWRITES THE METAL",
            "ANNEAL: SOFT, STRESS-FREE",
            "TEMPER: TOUGH, NOT BRITTLE",
            "THE COOL IS HALF THE RECIPE",
        ],
        "scenes": [
            {
                "goal": "Hook: the two bars",
                "teaching_point": "Same steel, different lives",
                "shot": "medium shot of annealed and tempered steel bars side by side",
                "motion": "camera pans both bars",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["annealed bar", "tempered bar", "steel samples"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of annealed and tempered steel bars side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "The anneal",
                "teaching_point": "Soft, stress-free, machinable",
                "shot": "diagram-style shot of a slow cooling curve for annealing",
                "motion": "temperature eases down slowly",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["annealing curve", "slow cool", "soft structure"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an annealing cooling curve, clean engineering visualization on a dark background",
            },
            {
                "goal": "The temper",
                "teaching_point": "Hardness traded for toughness",
                "shot": "diagram-style shot of the tempering temperature window",
                "motion": "temperature settles in the window",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temper window", "temperature line", "hardened steel"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the tempering temperature window, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bend",
                "teaching_point": "Bend instead of snap",
                "shot": "close-up shot of a tempered blade flexing in a vise",
                "motion": "blade bows and returns",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["tempered blade", "vise", "flex test"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a tempered blade flexing in a vise, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Temperature decides, cool completes",
                "shot": "wide hero shot of treated bars with their recipes",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["treated bars", "recipe cards", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of heat treated bars with recipe cards, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Annealed and tempered bars with their temperature curves",
            "subject": "annealing vs tempering",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two bars, curves above",
            "text": "SOFT OR TOUGH",
            "elements": ["annealed bar", "tempered bar", "temperature curves"],
            "style": "geometry studio photography",
            "mood": "heated, treated, rewritten",
            "prompt": "photograph of annealed and tempered steel bars with their temperature curves above and a bend test fixture, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Annealing & Tempering: Soft or Tough",
            "title_variations": [
                "Annealing vs Tempering",
                "Heat Treatment Basics",
                "Why Anneal Steel",
                "Tempering Explained",
                "Heat Treatment for Machining",
            ],
            "description": "Annealing and tempering are heat treatments that rewrite a metal's internal structure. Annealing heats, soaks, and cools slowly, leaving steel soft, stress-free, and easy to machine; tempering reheats hardened steel to a lower temperature, trading a little hardness for toughness so a blade bends instead of snapping. The temperature decides the result and the cool is half the recipe. This short shows both curves and bends both bars to compare.",
            "hashtags": ["#Annealing", "#Tempering", "#HeatTreatment", "#Metals"],
            "seo_keywords": [
                "annealing vs tempering",
                "heat treatment basics",
                "why anneal steel",
                "tempering explained",
                "soft steel machining",
                "toughness heat treat",
                "slow cooling anneal",
            ],
        },
        "fact_check": [
            "Annealing softens and relieves stress.",
            "It uses a slow cool.",
            "Tempering trades hardness for toughness.",
            "Tempering uses a lower temperature.",
            "The cool is half the recipe.",
        ],
    },
    {
        "topic": "Forging",
        "core_question": "Why does hammering metal make it stronger?",
        "learning_objective": "The viewer understands forging and how working metal builds grain flow.",
        "engineering_summary": "Forging shapes metal by hammering it while hot: the force squeezes the billet and the grain flows along the part's shape. Grain that follows the outline makes the part strong where it counts, which is why forged parts beat cast ones under impact. The hammer also closes voids and pushes out impurities. Heat softens the metal, and the hammer sets the structure. Strength follows the grain.",
        "real_world_application": "Crankshafts, wrenches, and connecting rods are forged for grain flow strength.",
        "common_misconceptions": [
            "Forging just shapes (it also builds the grain structure)",
            "Cast is as strong (cast grain is random, forged grain flows)",
            "The heat does the work (the hammer shapes the grain)",
        ],
        "teaching_strategy": "Forge a billet and compare its grain to a cast sample.",
        "script": "Forging shapes metal by hammering it while hot: the force squeezes the billet and the grain flows along the part's shape. Grain that follows the outline makes the part strong where it counts, which is why forged parts beat cast ones under impact. The hammer also closes voids and pushes out impurities. Heat softens the metal, and the hammer sets the structure. Strength follows the grain.",
        "text_overlay": [
            "HAMMERED WHILE HOT",
            "GRAIN FLOWS WITH THE SHAPE",
            "STRONG WHERE IT COUNTS",
            "STRENGTH FOLLOWS THE GRAIN",
        ],
        "scenes": [
            {
                "goal": "Hook: the hammer",
                "teaching_point": "Squeeze while hot",
                "shot": "medium shot of a forging hammer striking a hot billet",
                "motion": "hammer drives the glowing metal",
                "lighting": "hot glow light",
                "background": "workshop floor",
                "objects": ["forging hammer", "hot billet", "anvil"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a forging hammer striking a hot billet, hot glow lighting, workshop floor",
            },
            {
                "goal": "The grain",
                "teaching_point": "Grain flows with the shape",
                "shot": "diagram-style shot of grain flowing along a forged outline",
                "motion": "grain lines bend with the part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["forged outline", "grain lines", "flow path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of grain flow in a forged part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The comparison",
                "teaching_point": "Forged versus cast grain",
                "shot": "diagram-style shot comparing cast and forged grain",
                "motion": "two structures side by side",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cast grain", "forged grain", "comparison"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of cast versus forged grain structure, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cleanup",
                "teaching_point": "Voids close, impurities out",
                "shot": "diagram-style shot of voids closing under the hammer",
                "motion": "hammer squeezes the voids shut",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["billet section", "voids", "hammer pressure"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of voids closing during forging, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Strength follows the grain",
                "shot": "wide hero shot of forged parts on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["forged parts", "hammer", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of forged parts and a hammer on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A forged part with grain flow lines and a hot billet under a hammer",
            "subject": "forging grain flow",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, grain lines traced",
            "text": "STRENGTH FOLLOWS THE GRAIN",
            "elements": ["forged part", "grain lines", "hammer"],
            "style": "geometry studio photography",
            "mood": "hammered, hot, strengthened",
            "prompt": "photograph of a forged part with grain flow lines and a hot billet under a hammer, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Forging: Strength Follows the Grain",
            "title_variations": [
                "How Forging Works",
                "Forged vs Cast Metal",
                "Forging Grain Flow",
                "Why Forge Parts",
                "Hammer Forging Basics",
            ],
            "description": "Forging shapes metal by hammering it while hot: the force squeezes the billet and the grain flows along the part's shape, making the part strong where it counts. That is why forged parts beat cast ones under impact, and the hammer also closes voids and pushes out impurities. Heat softens the metal and the hammer sets the structure. This short forges a billet, draws the grain, and compares it to cast grain.",
            "hashtags": ["#Forging", "#MetalWorking", "#GrainFlow", "#Manufacturing"],
            "seo_keywords": [
                "how forging works",
                "forged vs cast metal",
                "forging grain flow",
                "why forge parts",
                "hammer forging",
                "forging strength impact",
                "wrought metal structure",
            ],
        },
        "fact_check": [
            "Forging hammers metal while hot.",
            "Grain flows along the part shape.",
            "Grain flow adds impact strength.",
            "The hammer closes voids.",
            "Forged grain beats cast grain.",
        ],
    },
    {
        "topic": "Die Casting",
        "core_question": "How does molten metal fill a mold in seconds?",
        "learning_objective": "The viewer understands die casting and its fast, precise parts.",
        "engineering_summary": "Die casting shoots molten metal into a steel mold at high pressure, so the cavity fills in a fraction of a second and the part cools fast. High pressure gives crisp details and thin walls, and the steel die lasts for hundreds of thousands of shots. The catch: the tooling is expensive, so the process pays off at volume. Aluminum and zinc fill dies daily. Speed and detail are the deal.",
        "real_world_application": "Phone frames, power tool housings, and motor end bells are die cast by the million.",
        "common_misconceptions": [
            "Casting is slow (the shot takes fractions of a second)",
            "Thin walls need machining (pressure fills them cleanly)",
            "Die casting is cheap to start (the die is the investment)",
        ],
        "teaching_strategy": "Show the shot sequence: close, inject, cool, eject.",
        "script": "Die casting shoots molten metal into a steel mold at high pressure, so the cavity fills in a fraction of a second and the part cools fast. High pressure gives crisp details and thin walls, and the steel die lasts for hundreds of thousands of shots. The catch: the tooling is expensive, so the process pays off at volume. Aluminum and zinc fill dies daily. Speed and detail are the deal.",
        "text_overlay": [
            "MOLTEN METAL, HIGH PRESSURE",
            "CAVITY FILLS IN A BLINK",
            "CRISP DETAIL, THIN WALLS",
            "TOOLING PAYS AT VOLUME",
        ],
        "scenes": [
            {
                "goal": "Hook: the shiny part",
                "teaching_point": "Crisp metal, straight from the die",
                "shot": "medium shot of a die cast part fresh from the mold",
                "motion": "part cools and shines",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["die cast part", "runner", "flash"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a die cast part fresh from the mold, neutral lab lighting, workbench",
            },
            {
                "goal": "The shot",
                "teaching_point": "Injection under pressure",
                "shot": "diagram-style shot of the die casting shot sequence",
                "motion": "metal shoots into the cavity",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shot plunger", "molten metal", "cavity"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the die casting injection sequence, clean engineering visualization on a dark background",
            },
            {
                "goal": "The detail",
                "teaching_point": "Pressure makes detail",
                "shot": "close-up shot of thin walls and crisp edges on a die cast part",
                "motion": "camera traces the detail",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["thin walls", "crisp edges", "die cast detail"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of thin walls and crisp edges on a die cast part, bright task lighting, print lab",
            },
            {
                "goal": "The cycle",
                "teaching_point": "Close, inject, cool, eject",
                "shot": "diagram-style shot of the die casting cycle",
                "motion": "four steps loop on screen",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["close step", "inject step", "eject step"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the die casting cycle steps, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Speed and detail",
                "shot": "wide hero shot of die cast parts and a die on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["die cast parts", "steel die", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of die cast parts with a steel die on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Molten metal shooting into a steel die cavity under pressure",
            "subject": "die casting shot",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "die center, metal stream entering",
            "text": "CRISP METAL, IN A BLINK",
            "elements": ["steel die", "molten metal", "cavity"],
            "style": "geometry studio photography",
            "mood": "injected, detailed, fast",
            "prompt": "photograph of molten metal shooting into a steel die cavity under pressure with a finished part beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Die Casting: Crisp Metal, In a Blink",
            "title_variations": [
                "How Die Casting Works",
                "Die Casting Explained",
                "Aluminum Die Casting",
                "Die Cast vs Machined",
                "Die Casting Basics",
            ],
            "description": "Die casting shoots molten metal into a steel mold at high pressure, filling the cavity in a fraction of a second and cooling the part fast. High pressure yields crisp details and thin walls, and the steel die lasts for hundreds of thousands of shots, though the tooling is expensive, so volume pays for it. This short runs the close-inject-cool-eject cycle and shows the speed and detail that make the deal.",
            "hashtags": ["#DieCasting", "#MetalCasting", "#Manufacturing", "#Aluminum"],
            "seo_keywords": [
                "how die casting works",
                "die casting explained",
                "aluminum die casting",
                "high pressure casting",
                "die cast thin walls",
                "die casting tooling cost",
                "zinc die casting",
            ],
        },
        "fact_check": [
            "Die casting injects molten metal under pressure.",
            "The cavity fills in a fraction of a second.",
            "High pressure creates crisp detail.",
            "Steel dies last hundreds of thousands of shots.",
            "Tooling pays off at volume.",
        ],
    },
    {
        "topic": "Thread Cutting Methods",
        "core_question": "How are threads actually made?",
        "learning_objective": "The viewer understands tapping, threading, and thread milling.",
        "engineering_summary": "Threads are cut, formed, or ground: a tap cuts the internal thread in a hole, a die cuts external threads on a rod, and a lathe single-points threads by tracking the spindle. A tap needs the right hole size and a straight start, or it snaps. Thread milling cuts with a rotating tool in a CNC machine. The method depends on the part: hole, rod, or production run.",
        "real_world_application": "Every bolt, tapped hole, and printed thread starts with a cutting method.",
        "common_misconceptions": [
            "Threads are molded in bolts (most are cut or rolled)",
            "A tap works in any hole (the hole size is the recipe)",
            "One method fits all (holes, rods, and runs differ)",
        ],
        "teaching_strategy": "Tap a hole, die a rod, and single-point a thread on the lathe.",
        "script": "Threads are cut, formed, or ground: a tap cuts the internal thread in a hole, a die cuts external threads on a rod, and a lathe single-points threads by tracking the spindle. A tap needs the right hole size and a straight start, or it snaps. Thread milling cuts with a rotating tool in a CNC machine. The method depends on the part: hole, rod, or production run.",
        "text_overlay": [
            "TAP: THE HOLE'S THREAD",
            "DIE: THE ROD'S THREAD",
            "LATHE: SPINDLE-TRACKED",
            "METHOD MATCHES THE PART",
        ],
        "scenes": [
            {
                "goal": "Hook: the snapped tap",
                "teaching_point": "Wrong hole, broken tap",
                "shot": "close-up shot of a broken tap stuck in a hole",
                "motion": "camera reveals the fracture",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["broken tap", "tapped hole", "workpiece"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a broken tap stuck in a hole, bright task lighting, print lab",
            },
            {
                "goal": "The tap",
                "teaching_point": "Internal threads in a hole",
                "shot": "close-up shot of a tap cutting threads in a hole",
                "motion": "tap turns and bites",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["tap", "hole", "cutting flutes"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a tap cutting threads in a hole, bright task lighting, print lab",
            },
            {
                "goal": "The die",
                "teaching_point": "External threads on a rod",
                "shot": "close-up shot of a die cutting threads on a rod",
                "motion": "die chases down the rod",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["die", "rod", "cut threads"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a die cutting threads on a rod, bright task lighting, print lab",
            },
            {
                "goal": "The lathe",
                "teaching_point": "Spindle-tracked single point",
                "shot": "medium shot of a lathe single-pointing a thread",
                "motion": "tool tracks the spinning part",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["lathe", "threading tool", "spinning part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a lathe single-pointing a thread, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Method matches the part",
                "shot": "wide hero shot of threaded parts and tools on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["threaded parts", "taps", "dies"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of threaded parts, taps, and dies on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A tap, a die, and a lathe tool with the threads they cut",
            "subject": "thread cutting methods",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "three tools in a row",
            "text": "TAP, DIE, OR LATHE",
            "elements": ["tap", "die", "threading tool"],
            "style": "geometry studio photography",
            "mood": "cut, formed, threaded",
            "prompt": "photograph of a tap, a die, and a lathe threading tool with the threads they cut, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Thread Cutting Methods: Tap, Die, or Lathe",
            "title_variations": [
                "How Are Threads Made",
                "Tap vs Die",
                "Thread Cutting Explained",
                "Thread Milling Basics",
                "Cutting Threads in Holes",
            ],
            "description": "Threads are cut, formed, or ground: a tap cuts internal threads in a hole, a die cuts external threads on a rod, and a lathe single-points threads by tracking the spindle. A tap needs the right hole size and a straight start or it snaps, while thread milling cuts with a rotating CNC tool. This short taps a hole, dies a rod, and single-points on the lathe, showing how the method matches the part.",
            "hashtags": ["#Threading", "#Taps", "#Dies", "#Machining"],
            "seo_keywords": [
                "how are threads made",
                "tap vs die",
                "thread cutting methods",
                "thread milling",
                "single point threading",
                "tap hole size",
                "cutting threads rod",
            ],
        },
        "fact_check": [
            "Taps cut internal threads.",
            "Dies cut external threads.",
            "Lathes single-point threads.",
            "Taps need the right hole size.",
            "The method matches the part.",
        ],
    },
    {
        "topic": "Stepper Motors",
        "core_question": "Why do printers and robots move in steps?",
        "learning_objective": "The viewer understands stepper motors and open-loop positioning.",
        "engineering_summary": "A stepper motor turns in exact steps: the driver energizes the coils in sequence, and each pulse moves the shaft a fixed angle, like one tooth of rotation. No encoder is needed, because the motor counts its own steps, which makes steppers cheap and precise for printers and CNC machines. The catch: if the torque is exceeded, steps are lost silently. Open-loop motion trusts the steps.",
        "real_world_application": "Printers, CNC machines, and cameras all position by stepping.",
        "common_misconceptions": [
            "Steppers need sensors (they count steps, open loop)",
            "Steps are tiny and weak (they hold strong positions)",
            "Lost steps are obvious (they happen silently)",
        ],
        "teaching_strategy": "Pulse a stepper and watch the shaft click through its angles.",
        "script": "A stepper motor turns in exact steps: the driver energizes the coils in sequence, and each pulse moves the shaft a fixed angle, like one tooth of rotation. No encoder is needed, because the motor counts its own steps, which makes steppers cheap and precise for printers and CNC machines. The catch: if the torque is exceeded, steps are lost silently. Open-loop motion trusts the steps.",
        "text_overlay": [
            "PULSES BECOME STEPS",
            "FIXED ANGLE PER PULSE",
            "COUNTS ITS OWN STEPS",
            "LOST STEPS ARE SILENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the clicking shaft",
                "teaching_point": "Steps are audible and exact",
                "shot": "close-up shot of a stepper shaft clicking through steps",
                "motion": "shaft jumps angle by angle",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["stepper motor", "shaft", "step pointer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a stepper motor shaft clicking through steps, bright task lighting, print lab",
            },
            {
                "goal": "The coils",
                "teaching_point": "Coils fire in sequence",
                "shot": "diagram-style shot of a stepper cross section with coils",
                "motion": "coils energize in order",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stepper section", "coils", "rotor teeth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a stepper motor cross section, clean engineering visualization on a dark background",
            },
            {
                "goal": "The counting",
                "teaching_point": "No encoder needed",
                "shot": "graphic-style shot of pulse counts becoming positions",
                "motion": "pulses add to position",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pulse train", "position counter", "step grid"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stepper pulse counting, clean engineering visualization on a dark background",
            },
            {
                "goal": "The catch",
                "teaching_point": "Lost steps are silent",
                "shot": "medium shot of a stalled stepper losing its position",
                "motion": "shaft slips, position drifts",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["stalled stepper", "load", "drift marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stalled stepper losing position under load, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Open-loop motion",
                "shot": "wide hero shot of stepper motors on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stepper motors", "driver boards", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of stepper motors and driver boards on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A stepper motor cross section with coils firing and a step counter",
            "subject": "stepper motor",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "motor center, step counter beside",
            "text": "EXACT STEPS, NO SENSOR",
            "elements": ["stepper motor", "coils", "step counter"],
            "style": "geometry studio photography",
            "mood": "stepped, counted, precise",
            "prompt": "photograph of a stepper motor cross section with coils firing and a step counter beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stepper Motors: Exact Steps, No Sensor",
            "title_variations": [
                "How Stepper Motors Work",
                "Stepper Motor Basics",
                "NEMA 17 Explained",
                "Open Loop Positioning",
                "Steppers for Printers",
            ],
            "description": "A stepper motor turns in exact steps: the driver energizes the coils in sequence and each pulse moves the shaft a fixed angle, like one tooth of rotation. No encoder is needed because the motor counts its own steps, which makes steppers cheap and precise for printers and CNC machines. The catch: if torque is exceeded, steps are lost silently. This short pulses a motor, fires the coils, and shows the trust behind open-loop motion.",
            "hashtags": ["#StepperMotor", "#NEMA17", "#Motors", "#3DPrinting"],
            "seo_keywords": [
                "how stepper motors work",
                "stepper motor basics",
                "nema 17",
                "open loop positioning",
                "stepper lost steps",
                "stepper torque steps",
                "steppers for printers",
            ],
        },
        "fact_check": [
            "Steppers move in exact angular steps.",
            "Coil pulses drive each step.",
            "No encoder is needed.",
            "Exceeded torque loses steps silently.",
            "Steppers are cheap and precise.",
        ],
    },
    {
        "topic": "Structural Vibration",
        "core_question": "Why does a machine hum at one speed and roar at another?",
        "learning_objective": "The viewer understands resonance and vibration modes in machines.",
        "engineering_summary": "Every machine part has natural frequencies: shapes of motion it prefers, called modes. When the running speed matches a mode, the motion grows with every cycle and the part hums or roars. Resonance is the multiplier: small forces become big motion at the matching speed. Stiffening the part or changing the mass moves the mode, and damping shrinks the response. The hum is a mode being fed.",
        "real_world_application": "Printer frames, spindles, and gantries are tuned away from their modes.",
        "common_misconceptions": [
            "Vibration is always a fault (it may be a natural mode at that speed)",
            "More stiffness always fixes it (it moves the mode, damping shrinks it)",
            "Speed changes fix everything (the mode follows the structure)",
        ],
        "teaching_strategy": "Run a flexible arm through speeds and watch it ring at its mode.",
        "script": "Every machine part has natural frequencies: shapes of motion it prefers, called modes. When the running speed matches a mode, the motion grows with every cycle and the part hums or roars. Resonance is the multiplier: small forces become big motion at the matching speed. Stiffening the part or changing the mass moves the mode, and damping shrinks the response. The hum is a mode being fed.",
        "text_overlay": [
            "NATURAL MODES, PREFERRED MOTION",
            "MATCH THE SPEED, IT GROWS",
            "RESONANCE IS THE MULTIPLIER",
            "DAMPING SHRINKS THE RESPONSE",
        ],
        "scenes": [
            {
                "goal": "Hook: the humming frame",
                "teaching_point": "One speed rings",
                "shot": "medium shot of a frame vibrating at one running speed",
                "motion": "frame shakes at the resonant speed",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["machine frame", "vibration", "running motor"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a machine frame vibrating at its resonant speed, neutral lab lighting, workbench",
            },
            {
                "goal": "The modes",
                "teaching_point": "Shapes of preferred motion",
                "shot": "diagram-style shot of a beam bending in its first modes",
                "motion": "mode shapes animate in sequence",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["beam modes", "first mode", "second mode"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of beam vibration modes, clean engineering visualization on a dark background",
            },
            {
                "goal": "The match",
                "teaching_point": "Speed meets the mode",
                "shot": "graphic-style shot of amplitude rising at the resonant speed",
                "motion": "response curve peaks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["response curve", "resonant peak", "speed axis"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a resonance response curve, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fixes",
                "teaching_point": "Stiffen, move, damp",
                "shot": "medium shot of a stiffened frame with a damper added",
                "motion": "braces and dampers quiet the frame",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["stiffening braces", "damper", "quiet frame"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stiffened frame with a damper added, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The hum is a fed mode",
                "shot": "wide hero shot of a machine with its mode chart",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["machine", "mode chart", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a machine with its vibration mode chart, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A vibrating frame with mode shapes and a response peak at one speed",
            "subject": "structural vibration",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "frame center, curve beside",
            "text": "THE HUM IS A MODE BEING FED",
            "elements": ["machine frame", "mode shapes", "response curve"],
            "style": "geometry studio photography",
            "mood": "ringing, resonant, tuned",
            "prompt": "photograph of a vibrating machine frame with mode shapes and a response peak at one speed, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Structural Vibration: The Hum Is a Mode Being Fed",
            "title_variations": [
                "Why Do Machines Vibrate",
                "Structural Vibration Explained",
                "Resonance in Machines",
                "Vibration Modes Basics",
                "Machine Resonance Fix",
            ],
            "description": "Every machine part has natural frequencies, shapes of motion called modes, and when the running speed matches a mode, the motion grows with every cycle and the part hums or roars. Resonance is the multiplier that turns small forces into big motion at the matching speed. Stiffening the part or changing the mass moves the mode, and damping shrinks the response. This short runs a frame through its speeds and feeds the mode to show the roar.",
            "hashtags": ["#Vibration", "#Resonance", "#MachineDesign", "#Engineering"],
            "seo_keywords": [
                "why do machines vibrate",
                "structural vibration",
                "resonance machines",
                "vibration modes",
                "machine resonance fix",
                "natural frequency structure",
                "damping response",
            ],
        },
        "fact_check": [
            "Parts have natural frequencies.",
            "Modes are preferred motion shapes.",
            "Matching speed grows the motion.",
            "Resonance multiplies small forces.",
            "Stiffening moves modes; damping shrinks response.",
        ],
    },
    {
        "topic": "Thermal Interface Materials",
        "core_question": "Thermal paste or pad: which one fills the gap?",
        "learning_objective": "The viewer understands TIMs and the gap between heat source and sink.",
        "engineering_summary": "A thermal interface material fills the microscopic air gaps between a hot part and its heat sink, because air is a terrible conductor. Paste is a soft compound that squishes into the gaps and transfers heat well, but it needs a small gap. Pads are solid, easy to place, and forgiving, but they conduct less. The rule: paste for performance, pad for convenience. The gap is the enemy, and the TIM is the bridge.",
        "real_world_application": "CPUs, stepper drivers, and hotends all need a TIM between part and sink.",
        "common_misconceptions": [
            "More paste is better (a thin layer conducts best)",
            "Pads are as good as paste (they conduct less)",
            "The sink touches well enough (air gaps kill the transfer)",
        ],
        "teaching_strategy": "Measure temperatures with no TIM, a pad, and paste.",
        "script": "A thermal interface material fills the microscopic air gaps between a hot part and its heat sink, because air is a terrible conductor. Paste is a soft compound that squishes into the gaps and transfers heat well, but it needs a small gap. Pads are solid, easy to place, and forgiving, but they conduct less. The rule: paste for performance, pad for convenience. The gap is the enemy, and the TIM is the bridge.",
        "text_overlay": [
            "AIR GAPS KILL TRANSFER",
            "PASTE: SQUISH INTO THE GAP",
            "PAD: EASY AND FORGIVING",
            "PASTE FOR PERFORMANCE",
        ],
        "scenes": [
            {
                "goal": "Hook: the hot chip",
                "teaching_point": "The gap is the enemy",
                "shot": "close-up shot of a chip and sink separated by air",
                "motion": "heat struggles across the gap",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["chip", "heat sink", "air gap"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a chip and heat sink separated by an air gap, bright task lighting, print lab",
            },
            {
                "goal": "The gap",
                "teaching_point": "Microscopic air pockets",
                "shot": "diagram-style shot of surface roughness with air pockets",
                "motion": "rough peaks touch, air between",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["rough surfaces", "air pockets", "contact peaks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of air gaps between surfaces, clean engineering visualization on a dark background",
            },
            {
                "goal": "The paste",
                "teaching_point": "Squish and transfer",
                "shot": "medium shot of paste being applied and squished",
                "motion": "spatula spreads the paste thin",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["thermal paste", "spatula", "chip"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of thermal paste being spread on a chip, neutral lab lighting, workbench",
            },
            {
                "goal": "The pad",
                "teaching_point": "Place and forget",
                "shot": "medium shot of a thermal pad being placed between parts",
                "motion": "pad presses into place",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["thermal pad", "heat sink", "chip"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a thermal pad being placed between a chip and sink, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Performance or convenience",
                "shot": "wide hero shot of paste, pads, and sinks on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["paste tube", "pads", "heat sinks"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of thermal paste, pads, and heat sinks on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A chip and sink with air gaps filled by paste on one side and a pad on the other",
            "subject": "thermal interface materials",
            "background": "dark workshop blur",
            "angle": "cross section view",
            "lighting": "hard key with rim",
            "composition": "cross section center, two fills compared",
            "text": "PASTE FOR PERFORMANCE",
            "elements": ["chip", "heat sink", "paste and pad"],
            "style": "geometry studio photography",
            "mood": "bridged, filled, cooled",
            "prompt": "photograph of a chip and heat sink cross section with paste and a pad filling the air gaps, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Thermal Interface Materials: Paste for Performance",
            "title_variations": [
                "Thermal Paste or Pad",
                "What Is Thermal Interface Material",
                "TIM Explained",
                "Heat Sink Gap Filler",
                "Paste vs Pad Cooling",
            ],
            "description": "A thermal interface material fills the microscopic air gaps between a hot part and its heat sink, because air is a terrible conductor. Paste squishes into the gaps and transfers heat well but needs a small gap, while pads are solid, easy to place, and forgiving but conduct less. The rule is simple: paste for performance, pad for convenience. This short shows the gap, spreads the paste, and places the pad.",
            "hashtags": ["#ThermalPaste", "#ThermalPad", "#TIM", "#Cooling"],
            "seo_keywords": [
                "thermal paste or pad",
                "thermal interface material",
                "tim heat sink",
                "air gap heat transfer",
                "paste vs pad cooling",
                "heat sink mounting",
                "cpu thermal paste",
            ],
        },
        "fact_check": [
            "Air is a terrible conductor.",
            "TIMs fill microscopic air gaps.",
            "Paste transfers heat well in thin layers.",
            "Pads are easy but conduct less.",
            "Paste for performance, pad for convenience.",
        ],
    },
]