"""Batch 12: travel behavior, wood composite, rails, moisture diagnostics, fits, print farms, couplings, and convection."""

CURATED = [
    # ======================================================================
    {
        "topic": "Z-Hop Explained",
        "core_question": "What is z-hop, and when should I use it?",
        "learning_objective": "The viewer can explain the travel-lift trade-off and set z-hop sensibly for different prints.",
        "engineering_summary": "Z-hop lifts the nozzle vertically off the print during travel moves: up a fraction of a millimeter, across, back down to the print. The purpose is to stop the hot nozzle dragging across the part surface, which leaves scars, bumps, and blobs, especially on tall prints and fully populated beds. The costs are real: every hop adds motion and time, and each lift requires a retract-and-prime cycle that can introduce stringing and ooze on retraction-sensitive filaments. Excessive hop also risks layer shifts and z-banding because the z-axis works harder; too little hop and the nozzle still knocks small details. The sensible rule: use a small hop for long travels across the part, and disable it for prints dominated by short moves, where the retraction work does more harm than the dragging.",
        "real_world_application": "Tall vases, multicolor builds, and parts with delicate top features benefit from z-hop; dense small-parts batches print better with it off.",
        "common_misconceptions": [
            "More z-hop is always safer (excess hop causes layer shifts and stringing)",
            "Z-hop replaces retraction (they work together; hop is vertical travel, retraction is filament pullback)",
            "It is free (every hop costs motion time and a prime-retract cycle)",
        ],
        "teaching_strategy": "Show the nozzle dragging without hop, then the lift travel, then the failure modes of too much hop.",
        "script": "Z-hop lifts the nozzle off the print during travel: up a fraction of a millimeter, across, back down. It stops the hot nozzle dragging through the part, leaving scars and blobs on tall prints and full beds. But every hop costs time, and each lift triggers a prime-and-retract cycle that can string. Too much hop invites layer shifts; too little, and the nozzle knocks the part. The rule: small hops when traveling across the part, none for prints full of short moves, where retraction work does more harm than dragging.",
        "text_overlay": [
            "LIFT, TRAVEL, LAND",
            "STOPS NOZZLE DRAG",
            "HOP = TIME + RETRACT",
            "SMALL HOPS, SHORT MOVES OFF",
        ],
        "scenes": [
            {
                "goal": "Hook: the drag",
                "teaching_point": "A hot nozzle scars the surface",
                "shot": "macro shot of a nozzle dragging across a finished top layer",
                "motion": "nozzle scars the surface as it travels",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["nozzle", "top layer", "drag scar"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a hot nozzle dragging scars across a printed top layer, bright task light, print lab",
            },
            {
                "goal": "The hop",
                "teaching_point": "Lift, travel, land",
                "shot": "side shot of a nozzle lifting, traveling, and landing",
                "motion": "nozzle rises, moves across, descends",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["nozzle", "lift path", "travel"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle lifting and traveling over a print with the hop path visible, neutral lab lighting, print lab",
            },
            {
                "goal": "The cost",
                "teaching_point": "Every lift retracts and primes",
                "shot": "close-up of filament oozing from a nozzle after a hop",
                "motion": "string forms at the landing point",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["nozzle", "ooze", "string"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of filament oozing and stringing from a nozzle after a z-hop, bright task light, dark bench",
            },
            {
                "goal": "Too much hop",
                "teaching_point": "Excess lift risks layer shifts",
                "shot": "tabletop shot of a print with a shifted layer near the top",
                "motion": "tilt up to the shifted layer",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["shifted print", "layer shift"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D print with a visibly shifted layer near the top, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Hop for long travels only",
                "shot": "wide hero shot of a tall vase printing with clean surfaces",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["tall vase", "printer", "clean surface"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tall vase printing with clean surfaces on the printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle arcing over a print with the hop path highlighted",
            "subject": "nozzle lifting over a print",
            "background": "dark print lab blur",
            "angle": "side profile",
            "lighting": "hard key with rim",
            "composition": "nozzle center, hop path arc",
            "text": "Z-HOP: LIFT AND LAND",
            "elements": ["nozzle", "hop arc", "printed part"],
            "style": "diagnostic studio photography",
            "mood": "lifted, precise, balanced",
            "prompt": "photograph of a nozzle arcing over a print with a highlighted hop path, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Z-Hop: When to Lift",
            "title_variations": [
                "What is Z-Hop",
                "Z-Hop Setting Guide",
                "Nozzle Drag Fix",
                "Z-Hop vs Retraction",
                "Printer Travel Moves",
            ],
            "description": "Z-hop lifts the nozzle off the print during travel moves: up a fraction of a millimeter, across, back down. It stops the hot nozzle dragging across the part, which leaves scars, bumps, and blobs on tall prints and populated beds. The costs: every hop adds motion and time, and each lift triggers a retract-and-prime cycle that can string. Excessive hop risks layer shifts and z-banding; too little leaves the nozzle knocking the part. The rule: use a small hop for long travels across the part, and disable it for prints dominated by short moves, where retraction work does more harm than the dragging.",
            "hashtags": ["#ZHop", "#3Dprinting", "#Slicer", "#Tips"],
            "seo_keywords": [
                "what is z hop",
                "z hop setting",
                "z hop vs retraction",
                "nozzle drag fix",
                "z hop stringing",
                "travel move settings",
                "z lift 3d printing",
            ],
        },
        "fact_check": [
            "Z-hop lifts the nozzle during travel to prevent surface dragging.",
            "Each hop costs motion time and a retract-and-prime cycle.",
            "Excessive z-hop can cause layer shifts and z-banding.",
            "Z-hop complements retraction; it does not replace it.",
            "Short-move prints generally run better with z-hop disabled.",
        ],
    },
    # ======================================================================
    {
        "topic": "Wood-Filled Filament",
        "core_question": "How do I print wood-filled filament without clogging?",
        "learning_objective": "The viewer can print wood composite reliably with the right nozzle, speeds, and drying routine.",
        "engineering_summary": "Wood-filled filament is PLA mixed with real wood fibers, typically 10-30 percent by weight, producing prints with a woody texture that sands, stains, and even smells like wood. It is abrasive: the fibers wear brass nozzles faster and clog small nozzles, so a 0.6 mm nozzle or larger is the standard recommendation. Printing discipline matters: lower speed and temperature than PLA (roughly 190-220 C) because overheated wood chars into brown streaks and under-extruded fibers cause gaps; the filament is brittle and snaps in tight bends, so a direct-drive or short Bowden path helps. Wood fibers hold moisture, so drying before printing prevents popping and steam bubbles. Expect to sand and seal the surface for a true wood finish.",
        "real_world_application": "Signs, frames, planters, and props use wood-filled PLA for a real-wood look; it is a display material, not a structural one.",
        "common_misconceptions": [
            "Wood filament prints like normal PLA (it is abrasive, brittle, and moisture-hungry)",
            "A 0.4 mm nozzle is fine (fibers clog it; 0.6 mm or larger is the standard advice)",
            "Hotter prints better (overheating chars the wood into brown streaks)",
        ],
        "teaching_strategy": "Show the clog prevention setup, the temperature failure, then the sanding and staining payoff.",
        "script": "Wood-filled filament is PLA mixed with real wood fibers, usually ten to thirty percent, and it prints with a woody texture that sanding and staining bring alive. The rules: use a 0.6 millimeter nozzle or larger - the fibers clog small nozzles - and slow down, because wood filament is brittle and stringy at speed. Dry it well: the fibers hold moisture and cause popping. Too hot, and the wood chars into brown streaks. The payoff: a part that looks and feels like carved wood. Expect sanding and sealing, and a brass nozzle that wears faster.",
        "text_overlay": [
            "PLA + 10-30% WOOD FIBERS",
            "0.6MM NOZZLE MINIMUM",
            "TOO HOT = CHARRED WOOD",
            "DRY IT, SAND IT, SEAL IT",
        ],
        "scenes": [
            {
                "goal": "Hook: the wood part",
                "teaching_point": "Real fibers make real grain",
                "shot": "macro shot of a wood-filled print showing visible grain texture",
                "motion": "slow push-in on the grain",
                "lighting": "warm side light",
                "background": "dark bench",
                "objects": ["wood print", "grain texture"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a wood-filled 3D print showing visible wood grain texture, warm side light, dark bench",
            },
            {
                "goal": "The nozzle",
                "teaching_point": "Fibers clog small nozzles",
                "shot": "close-up of a 0.6mm nozzle beside a clogged 0.4mm nozzle",
                "motion": "pan between the two nozzles",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["0.6mm nozzle", "clogged nozzle", "wood fibers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 0.6mm nozzle beside a clogged 0.4mm nozzle with wood fibers, bright task light, dark bench",
            },
            {
                "goal": "The temperature",
                "teaching_point": "Too hot chars the wood",
                "shot": "tabletop shot of a print with dark charred streaks",
                "motion": "tilt across the charred surface",
                "lighting": "raking side light",
                "background": "workbench",
                "objects": ["charred print", "brown streaks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a wood filament print with dark charred streaks from overheating, raking side light, workbench",
            },
            {
                "goal": "The finish",
                "teaching_point": "Sanding and staining bring it alive",
                "shot": "medium shot of sanding and staining a wood-filled part",
                "motion": "sandpaper moves across the surface, stain applied",
                "lighting": "warm task light",
                "background": "workshop bench",
                "objects": ["wood part", "sandpaper", "stain"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of sanding and staining a wood-filled 3D print on a workshop bench, warm task lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Big nozzle, slow, dry, sealed",
                "shot": "wide hero shot of a finished stained wood-look part on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stained part", "wood grain"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished stained wood-look 3D print on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spool of wood filament with a wood-grain print and a 0.6mm nozzle",
            "subject": "wood filament spool with grain print",
            "background": "warm workshop blur",
            "angle": "three-quarter close-up",
            "lighting": "warm key with rim",
            "composition": "spool center, nozzle foreground",
            "text": "WOOD-FILLED FILAMENT",
            "elements": ["wood spool", "grain print", "0.6mm nozzle"],
            "style": "material studio photography",
            "mood": "woody, warm, natural",
            "prompt": "photograph of a wood filament spool with a wood-grain printed part and 0.6mm nozzle, warm key light with rim, workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Wood-Filled Filament: Clog-Proof Guide",
            "title_variations": [
                "How to Print Wood Filament",
                "Wood PLA Settings",
                "Best Nozzle for Wood Filament",
                "Wood Filled PLA Tips",
                "Printing Wood Composites",
            ],
            "description": "Wood-filled filament is PLA mixed with real wood fibers, typically 10-30 percent, producing prints with a woody texture that sands and stains like wood. The fibers are abrasive and clog small nozzles, so a 0.6 mm nozzle or larger is the standard recommendation. Print slower and cooler than PLA, roughly 190-220 C, because overheating chars the wood into brown streaks. The filament is brittle and moisture-hungry: dry it before printing to avoid popping and steam bubbles. Expect to sand and seal the surface for a true wood finish, and know that your brass nozzle will wear faster.",
            "hashtags": ["#WoodFilament", "#3Dprinting", "#Materials", "#Composites"],
            "seo_keywords": [
                "wood filled filament",
                "how to print wood filament",
                "wood pla settings",
                "wood filament nozzle size",
                "wood filled pla clog",
                "wood filament temperature",
                "printing wood composites",
            ],
        },
        "fact_check": [
            "Wood-filled filament contains roughly 10-30 percent real wood fibers in PLA.",
            "Wood fibers are abrasive and clog small nozzles; 0.6 mm is the standard minimum.",
            "Overheating wood filament chars the fibers into brown streaks.",
            "Wood filament is brittle and prone to snapping in tight filament paths.",
            "Wood fibers absorb moisture, requiring drying to avoid popping and steam bubbles.",
        ],
    },
    # ======================================================================
    {
        "topic": "Linear Rails",
        "core_question": "Are linear rails worth the upgrade on my printer?",
        "learning_objective": "The viewer can explain the stiffness and accuracy benefits of rails and the real costs of the upgrade.",
        "engineering_summary": "Linear rails replace round rods with a hardened steel rail whose precision-ground raceways guide a ball-bearing carriage. The win is stiffness and accuracy: ball contacts carry load in every direction with minimal play, so the carriage moves with far less deflection than a rod and two bushings. That translates to crisp prints at higher acceleration and gantries that resist flex and sag, which is why high-speed and CoreXY machines use them. The costs are real: rails demand a flat, aligned mounting surface, precise spacing between paired rails, and lubrication; a misaligned rail binds and introduces layer artifacts. They are also heavier and more expensive. Verdict: on fast or cantilevered machines, rails earn their price; on slow budget builds, round rods remain perfectly honest.",
        "real_world_application": "Vorons, high-acceleration bedslingers, and tool-changer gantries use linear rails; budget bedslingers and beginners rarely need them.",
        "common_misconceptions": [
            "Rails instantly fix print quality (a bad frame and alignment still produce bad prints)",
            "Rails never need maintenance (they need lubrication and clean raceways)",
            "Bigger rails are always better (oversized rails add weight and cost with no benefit)",
        ],
        "teaching_strategy": "Show the rod vs rail geometry, the deflection comparison, then the alignment requirements and verdict.",
        "script": "Linear rails replace round rods: a hardened steel rail with a precision-ground raceway and a carriage full of balls riding in it. The win is stiffness and accuracy - the carriage moves with little play in any direction, so prints stay crisp at speed and the gantry resists flex. The costs are real: rails need alignment, a flat mounting face, and lubrication; a misaligned rail binds and leaves layer artifacts. They cost more than rods. For high-acceleration machines and cantilevered gantries, rails earn their price; for slow budget builds, rods remain perfectly honest.",
        "text_overlay": [
            "BALLS + GROUND RACEWAY",
            "STIFF IN EVERY DIRECTION",
            "ALIGNMENT IS EVERYTHING",
            "FAST MACHINES, HONEST RODS",
        ],
        "scenes": [
            {
                "goal": "Hook: rod vs rail",
                "teaching_point": "Two very different ways to guide motion",
                "shot": "macro shot of a linear rail carriage beside a round rod with bushings",
                "motion": "slow pan between the two",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["linear rail", "carriage", "round rod"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a linear rail carriage beside a round rod with bushings, bright task light, dark bench",
            },
            {
                "goal": "The geometry",
                "teaching_point": "Balls carry load in every direction",
                "shot": "graphic-style shot of a rail cross-section with ball contacts",
                "motion": "load arrows press on ball contact points",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["rail cross-section", "ball contacts", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a linear rail cross-section diagram with ball contact points on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The alignment",
                "teaching_point": "Misaligned rails bind",
                "shot": "close-up of a misaligned rail carriage binding during motion",
                "motion": "carriage sticks and jerks",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["misaligned rail", "carriage", "binding"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a misaligned linear rail carriage binding during motion, bright task lighting, print lab",
            },
            {
                "goal": "The payoff",
                "teaching_point": "Crisp prints at speed",
                "shot": "wide shot of a fast printer with rails printing a crisp part",
                "motion": "toolhead moves quickly with clean layers",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["rail printer", "crisp print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a linear rail printer printing a crisp part at speed, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Rails for speed, rods for budget",
                "shot": "wide hero shot of a rail-based CoreXY machine in a clean lab",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["CoreXY machine", "linear rails"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a linear rail CoreXY machine in a clean lab, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A rail carriage on a rail, half cut away to show balls",
            "subject": "cutaway linear rail with ball carriage",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "rail diagonal, balls highlighted",
            "text": "LINEAR RAILS",
            "elements": ["linear rail", "ball carriage", "raceway"],
            "style": "hardware macro photography",
            "mood": "rigid, precise, industrial",
            "prompt": "macro photograph of a cutaway linear rail showing the ball carriage and raceway, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Linear Rails: Worth the Upgrade?",
            "title_variations": [
                "Linear Rails vs Round Rods",
                "Are Linear Rails Worth It",
                "Printer Rail Upgrade Guide",
                "MGN12 Rails Explained",
                "Gantry Stiffness Explained",
            ],
            "description": "Linear rails replace round rods with a hardened steel rail whose precision-ground raceways guide a ball-bearing carriage. The win is stiffness and accuracy: ball contacts carry load in every direction with minimal play, so the carriage deflects far less than a rod and two bushings, producing crisp prints at higher acceleration and gantries that resist flex. The costs: rails demand a flat, aligned mounting surface, precise pairing, and lubrication; a misaligned rail binds and leaves layer artifacts. On fast or cantilevered machines, rails earn their price; on slow budget builds, round rods remain perfectly honest.",
            "hashtags": ["#LinearRails", "#3Dprinting", "#Upgrade", "#Hardware"],
            "seo_keywords": [
                "linear rails vs round rods",
                "are linear rails worth it",
                "printer rail upgrade",
                "mgn12 linear rail",
                "gantry stiffness",
                "linear rail alignment",
                "corexy linear rails",
            ],
        },
        "fact_check": [
            "Linear rails guide a ball carriage along a precision-ground steel rail.",
            "Ball contacts carry load in all directions with minimal play, improving stiffness.",
            "Rails require flat aligned mounting surfaces to avoid binding.",
            "Rails need lubrication and clean raceways for reliable long-term motion.",
            "Round rods remain adequate for slow, budget-oriented machines.",
        ],
    },
    # ======================================================================
    {
        "topic": "Wet Filament Symptoms",
        "core_question": "How can I tell my filament is wet before I waste a print?",
        "learning_objective": "The viewer can recognize moisture symptoms and dry filament correctly.",
        "engineering_summary": "Wet filament is moisture absorbed by hygroscopic polymers - nylon, PETG, TPU, and even PLA in humid conditions. When water inside the melt zone flashes to steam at printing temperature, it disrupts extrusion, and the symptoms are consistent: audible popping and crackling at the nozzle, visible steam puffs, rough bubbly surfaces, stringing that retraction settings cannot fix, and weak brittle parts that fracture along layer lines. The diagnostic tell is that every symptom appears together and only on that filament. The fix is a real drying session, not leaving the spool on the printer: 4-8 hours in a dryer at the material's recommended drying temperature, then storage sealed with desiccant. Dry filament prints clean; wet filament lies.",
        "real_world_application": "A spool left out overnight in a humid garage shows popping and rough surfaces the next day; drying restores normal quality.",
        "common_misconceptions": [
            "Popping is a retraction problem (it is steam flashing in the melt, fixed by drying)",
            "PLA never gets wet (PLA is less hygroscopic but still degrades in humid conditions)",
            "Leaving it on the printer dries it (only a real drying session at temperature works)",
        ],
        "teaching_strategy": "Show the popping symptom live, the bubbly surface, then the drying process and the before-after comparison.",
        "script": "Wet filament is the silent killer of print quality. Nylon, PETG, and TPU soak up moisture, and when that water hits the hot nozzle it flashes to steam inside the melt. The symptoms: popping and crackling, steam puffs, rough bubbly surfaces, stringing no retraction fixes, and brittle prints that break along layer lines. The tell is consistency: every symptom appears together, and only on that filament. The fix is a real drying session - an hour or more at the right temperature - then storage sealed with desiccant. Dry filament prints clean; wet filament lies.",
        "text_overlay": [
            "STEAM IN THE MELT",
            "POP + STEAM + BUBBLES",
            "STRINGING RETRACTION CAN'T FIX",
            "DRY IT: HOURS, NOT HOPES",
        ],
        "scenes": [
            {
                "goal": "Hook: the popping nozzle",
                "teaching_point": "Steam flashes inside the melt",
                "shot": "macro shot of a nozzle popping steam bubbles during a print",
                "motion": "tiny steam puffs burst at the nozzle",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["nozzle", "steam puffs", "popping"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a nozzle popping steam bubbles during a print, bright task light, print lab",
            },
            {
                "goal": "The surface",
                "teaching_point": "Rough and bubbly layers",
                "shot": "macro shot of a bubbly rough print surface",
                "motion": "slow push-in on the bubbles",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["bubbly surface", "rough layers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a rough bubbly print surface from wet filament, raking side light, dark bench",
            },
            {
                "goal": "The stringing",
                "teaching_point": "No retraction setting fixes it",
                "shot": "tabletop shot of a stringy print beside a retraction tuning screen",
                "motion": "strings hang, settings change",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["stringy print", "retraction settings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stringy wet-filament print beside a retraction settings screen, neutral lab lighting, test bench",
            },
            {
                "goal": "The fix",
                "teaching_point": "Real drying at temperature",
                "shot": "wide shot of a spool drying in a filament dryer",
                "motion": "dryer countdown and temperature visible",
                "lighting": "warm interior light",
                "background": "workbench",
                "objects": ["filament dryer", "spool", "temperature"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a filament spool drying in a filament dryer with temperature display, warm interior light, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Dry it and the quality returns",
                "shot": "wide hero shot of a smooth fresh print beside the dryer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth print", "filament dryer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth fresh print beside a filament dryer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spool with steam bubbles bursting from the nozzle",
            "subject": "nozzle with steam bursts and spool",
            "background": "dark print lab blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "nozzle center, spool behind",
            "text": "WET FILAMENT?",
            "elements": ["nozzle", "steam bursts", "spool"],
            "style": "diagnostic macro photography",
            "mood": "popping, bubbly, diagnostic",
            "prompt": "macro photograph of a nozzle with steam bursts over a filament spool, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Wet Filament: 5 Telltale Signs",
            "title_variations": [
                "Signs of Wet Filament",
                "Why Is My Filament Popping",
                "Wet Filament Fix",
                "Steam in the Nozzle",
                "Drying Filament Correctly",
            ],
            "description": "Wet filament is moisture absorbed by hygroscopic polymers like nylon, PETG, and TPU. When that water hits the hot nozzle it flashes to steam inside the melt, and the symptoms are consistent: popping and crackling at the nozzle, steam puffs, rough bubbly surfaces, stringing that no retraction setting fixes, and brittle parts that fracture along layer lines. The diagnostic tell is that every symptom appears together and only on that filament. The fix is a real drying session - hours at the material's drying temperature - then storage sealed with desiccant. Dry filament prints clean; wet filament lies.",
            "hashtags": ["#WetFilament", "#3Dprinting", "#Troubleshooting", "#Filament"],
            "seo_keywords": [
                "signs of wet filament",
                "filament popping steam",
                "wet filament fix",
                "drying filament",
                "hygroscopic filament",
                "rough surface 3d print",
                "stringing retraction can't fix",
            ],
        },
        "fact_check": [
            "Hygroscopic filaments absorb moisture that flashes to steam in the melt.",
            "Steam in the melt causes popping, steam puffs, and bubbly surfaces.",
            "Moisture-induced stringing cannot be fixed with retraction settings.",
            "Wet filament can produce weak, brittle parts that fracture along layer lines.",
            "Proper drying requires hours at the material's drying temperature, then sealed storage.",
        ],
    },
    # ======================================================================
    {
        "topic": "Tolerances & Clearances",
        "core_question": "How much clearance do I need between printed parts?",
        "learning_objective": "The viewer can choose clearances for moving, press, and threaded fits and test them before committing.",
        "engineering_summary": "Clearance is the intentional gap between mating printed parts that lets them move or fit. FDM parts cannot hold machined precision: filament shrinks as it cools, layer lines add roughness, and nozzle geometry rounds corners, so a modeled 3 mm hole typically prints closer to 2.8 mm. Standard practice: sliding and rotating joints want roughly 0.2-0.4 mm clearance per side; press fits want almost none (interference of 0.05-0.15 mm per side for common plastics); and threaded or snap fits need a test print because every filament shrinks differently. The non-negotiable habit is printing a test pair of the critical features before committing a full assembly, then measuring with calipers and adjusting the model. Clearance is what separates a working mechanism from a fused lump.",
        "real_world_application": "Hinges, drawer slides, and gear axles all depend on tuned clearances; print farms keep clearance test strips in every filament profile.",
        "common_misconceptions": [
            "The CAD dimension prints exactly (shrinkage and layer roughness change real size)",
            "One clearance fits all (moving, press, and thread fits need different gaps)",
            "Tighter is always better (moving parts fuse and press fits crack the walls)",
        ],
        "teaching_strategy": "Show the 3 mm hole printing at 2.8 mm, the three fit classes, then the test-pair habit with calipers.",
        "script": "Printed parts need clearance: the space between mating parts that lets them move or fit. A press-fit hole gets none; a hinge pin gets a bit; a sliding joint gets more. PLA shrinks as it cools, and FDM layers can't match machined precision, so a 3-millimeter hole prints closer to 2.8. The rules: moving joints need 0.2 to 0.4 millimeters of clearance per side, press fits need about zero, and threaded fits need a test print. Print a test pair before committing a full assembly. Measure, adjust, iterate - clearance separates a moving mechanism from a fused lump.",
        "text_overlay": [
            "3MM HOLE = 2.8MM REALITY",
            "MOVE: 0.2-0.4 PER SIDE",
            "PRESS: ~ZERO",
            "TEST PAIR FIRST",
        ],
        "scenes": [
            {
                "goal": "Hook: the fused lump",
                "teaching_point": "No clearance means no mechanism",
                "shot": "tabletop shot of two fused printed parts being forced apart",
                "motion": "parts crack as they separate",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["fused parts", "crack", "force"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two fused 3D printed parts being forced apart on a workbench, bright task light",
            },
            {
                "goal": "The shrink",
                "teaching_point": "CAD size is not real size",
                "shot": "macro shot of calipers measuring a hole that prints smaller",
                "motion": "calipers read the smaller dimension",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["calipers", "printed hole", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of calipers measuring a printed hole that shrank from the CAD size, bright task light, dark bench",
            },
            {
                "goal": "The fit classes",
                "teaching_point": "Move, press, thread - three gaps",
                "shot": "graphic-style shot of three fit diagrams with clearance callouts",
                "motion": "clearance arrows scale across the fits",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fit diagrams", "clearance callouts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of fit class diagrams with clearance callouts for sliding press and thread fits on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The test pair",
                "teaching_point": "Print the critical features first",
                "shot": "wide shot of a clearance test strip with several hole and pin pairs",
                "motion": "tilt across the test features",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["test strip", "pin pairs", "hole pairs"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a clearance test strip with multiple hole and pin pairs, neutral lab lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Measure, adjust, iterate",
                "shot": "wide hero shot of a smooth sliding mechanism working on a bench",
                "motion": "slow orbit, slider glides",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["sliding mechanism", "tuned clearance"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth sliding mechanism moving freely on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two gears with a visible gap, calipers measuring the space",
            "subject": "mating parts with clearance gap",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "parts center, caliper jaws on gap",
            "text": "CLEARANCE MATTERS",
            "elements": ["mating parts", "clearance gap", "calipers"],
            "style": "fits studio photography",
            "mood": "precise, gapped, measured",
            "prompt": "macro photograph of mating printed parts with a clearance gap measured by calipers, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Clearance: The Secret to Moving Parts",
            "title_variations": [
                "3D Print Clearance Guide",
                "How Much Clearance for Fits",
                "Print Tolerance Basics",
                "Sliding Fit Clearance",
                "Press Fit Clearance Printing",
            ],
            "description": "Clearance is the intentional gap between mating printed parts that lets them move or fit. FDM parts cannot hold machined precision: filament shrinks as it cools, layer lines add roughness, and nozzle geometry rounds corners, so a modeled 3 mm hole typically prints closer to 2.8 mm. Standard practice: sliding and rotating joints want roughly 0.2-0.4 mm clearance per side, press fits want near zero, and threaded or snap fits need a test print because every filament shrinks differently. Always print a test pair of the critical features before committing a full assembly, then measure with calipers and adjust. Clearance separates a working mechanism from a fused lump.",
            "hashtags": ["#Clearance", "#3Dprinting", "#Design", "#Fits"],
            "seo_keywords": [
                "3d print clearance",
                "clearance for sliding parts",
                "press fit clearance",
                "print tolerance guide",
                "moving parts 3d printing",
                "hole size compensation",
                "clearance between printed parts",
            ],
        },
        "fact_check": [
            "FDM shrinkage and roughness make printed holes smaller than the CAD dimension.",
            "Sliding and rotating joints typically want 0.2-0.4 mm clearance per side.",
            "Press fits use near-zero clearance with slight interference.",
            "Different filaments shrink differently, so fits need test prints.",
            "A 3 mm modeled hole commonly prints closer to 2.8 mm.",
        ],
    },
    # ======================================================================
    {
        "topic": "Industrial Print Farm",
        "core_question": "How do print farms turn slow printers into production lines?",
        "learning_objective": "The viewer can explain the fleet math, standardization, and monitoring that make print farms work.",
        "engineering_summary": "A print farm is a fleet of printers run like a production line: dozens of machines, one operator, and parts coming off at a steady rhythm. The math is the point: one machine takes hours per part, but twenty machines finish twenty parts in the same hours, so farms convert slow per-part printing into production volume. Discipline makes it work: every machine is standardized with the same known-good profile, maintenance is scheduled, and monitoring is continuous, because one sick printer quietly wastes an entire shift before anyone notices. Farms plan around failure rates, stagger prints so no single machine is the bottleneck, and track yield per machine to catch drift early. Volume is a fleet problem, not a speed problem.",
        "real_world_application": "Print-on-demand shops, prototyping services, and hobby scale-ups run farms with 5-50 printers to deliver batch orders overnight.",
        "common_misconceptions": [
            "A farm is just many printers (standardization and monitoring are what make it a line)",
            "Faster machines mean a smaller farm (volume is throughput over time, not speed alone)",
            "Unattended farms run themselves (failure rates make monitoring non-negotiable)",
        ],
        "teaching_strategy": "Show the fleet math with two machines, the standardized setup, then the monitoring dashboard and failure planning.",
        "script": "A print farm is a fleet of printers run like a production line: dozens of machines, one operator, parts coming off at a steady rate. The math is the point - one machine takes hours per part, but twenty machines finish twenty parts in the same hours. The discipline: standardize every machine, run a known-good profile, and monitor each one, because one sick printer quietly wastes a whole shift. Farms also plan around failure rates and stagger prints so no single machine is the bottleneck. Volume is a fleet problem, not a speed problem.",
        "text_overlay": [
            "20 MACHINES = 20 PARTS/HOURS",
            "ONE PROFILE FOR EVERY MACHINE",
            "MONITOR OR LOSE THE SHIFT",
            "VOLUME = FLEET, NOT SPEED",
        ],
        "scenes": [
            {
                "goal": "Hook: the fleet",
                "teaching_point": "Many machines, one operator",
                "shot": "wide shot of a print farm with rows of printers running",
                "motion": "slow pan across the rows",
                "lighting": "even shop light",
                "background": "print farm room",
                "objects": ["print farm", "rows of printers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a print farm with rows of running printers, even shop lighting, production room",
            },
            {
                "goal": "The math",
                "teaching_point": "Parallel machines multiply output",
                "shot": "graphic-style shot of one machine vs twenty machines producing parts",
                "motion": "parts stack faster in the fleet panel",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fleet math diagram", "machine counters", "parts stack"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a fleet throughput diagram comparing one machine to twenty on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The discipline",
                "teaching_point": "One known-good profile everywhere",
                "shot": "medium shot of an operator checking a standardized printer",
                "motion": "operator scans the print, checks the screen",
                "lighting": "neutral shop light",
                "background": "print farm",
                "objects": ["operator", "standardized printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an operator checking a standardized printer in a print farm, neutral shop lighting",
            },
            {
                "goal": "The monitoring",
                "teaching_point": "One sick printer wastes a shift",
                "shot": "wide shot of a monitoring dashboard with per-machine status",
                "motion": "status tiles update across the screen",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["monitoring dashboard", "status tiles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a print farm monitoring dashboard with per-machine status tiles on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Plan for failures, stagger prints",
                "shot": "wide hero shot of a farm finishing a batch order on time",
                "motion": "slow orbit across the finished parts",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished batch", "print farm"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a print farm completing a batch order, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A wall of printers with a throughput counter overlay",
            "subject": "rows of printers with dashboard overlay",
            "background": "dark production room blur",
            "angle": "wide low angle",
            "lighting": "hard key with rim",
            "composition": "fleet rows, counter top-right",
            "text": "PRINT FARM MATH",
            "elements": ["printer rows", "throughput counter", "parts"],
            "style": "industrial production photography",
            "mood": "scaled, systematic, productive",
            "prompt": "photograph of rows of 3D printers with a throughput counter overlay, hard key light with rim, dark production room, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Print Farms: Fleet Math",
            "title_variations": [
                "How Print Farms Work",
                "Scaling Up 3D Printing",
                "Print Farm Setup",
                "Fleet Printing Explained",
                "Production 3D Printing",
            ],
            "description": "A print farm is a fleet of printers run like a production line: dozens of machines, one operator, and parts coming off at a steady rhythm. The math is the point - one machine takes hours per part, but twenty machines finish twenty parts in the same hours, so farms convert slow per-part printing into production volume. Discipline makes it work: every machine runs the same known-good profile, maintenance is scheduled, and monitoring is continuous, because one sick printer quietly wastes a whole shift. Farms plan around failure rates, stagger prints so no single machine is the bottleneck, and track yield per machine to catch drift early. Volume is a fleet problem, not a speed problem.",
            "hashtags": ["#PrintFarm", "#3Dprinting", "#Business", "#Production"],
            "seo_keywords": [
                "how print farms work",
                "print farm setup",
                "scaling 3d printing",
                "fleet printing",
                "print farm monitoring",
                "production 3d printing",
                "batch printing multiple printers",
            ],
        },
        "fact_check": [
            "A print farm multiplies throughput by running many machines in parallel.",
            "Standardized profiles across machines keep output consistent.",
            "Continuous monitoring catches failing machines before they waste a shift.",
            "Failure-rate planning and staggered prints prevent single-machine bottlenecks.",
            "Per-machine yield tracking catches quality drift early.",
        ],
    },
    # ======================================================================
    {
        "topic": "Couplings",
        "core_question": "What kind of coupling do I need between a motor and a shaft?",
        "learning_objective": "The viewer can match rigid and flexible couplings to alignment and application needs.",
        "engineering_summary": "A coupling connects a motor shaft to whatever it drives - a lead screw, a gearbox input, a wheel - while transmitting torque. Rigid couplings bolt two hubs together and pass motion with zero compliance: perfect when shafts are perfectly aligned, brutal when they are not, since any misalignment loads the bearings and causes vibration. Flexible couplings tolerate small misalignment and shock: a beam coupling flexes its spiral cuts, a bellows coupling twists elastically, and a spider coupling uses a rubber star insert to absorb shock while damping vibration. The classic printer application is the z-axis: a flexible coupling joins the motor to the lead screw so motor wobble and screw wobble do not fight each other - a rigid coupling there transmits the wobble straight into z-banding. Rule: aligned rigid shafts take rigid couplings; real-world shafts take flexible.",
        "real_world_application": "Printer z-axes use beam or spider couplings; CNC spindles use rigid or bellows couplings depending on alignment precision.",
        "common_misconceptions": [
            "Rigid couplings are stronger and therefore better (misalignment destroys bearings and causes vibration)",
            "All flexible couplings are the same (beam, bellows, and spider have different torque and compliance)",
            "Couplings are optional (a direct hard mount passes every wobble and misalignment into the driven shaft)",
        ],
        "teaching_strategy": "Show the rigid coupling fail mode on a misaligned pair, then the three flexible types and the z-axis example.",
        "script": "A coupling connects a motor shaft to whatever it drives. Rigid couplings bolt two flanges together and pass motion exactly - perfect when shafts are perfectly aligned, brutal when they are not. Flexible couplings allow small misalignment: a beam coupling flexes its spiral cuts, a bellows coupling twists elastically, and a spider coupling lets a rubber star absorb shock. On a printer, the classic job is z: a flexible coupling joins motor to lead screw, so motor wobble and screw wobble don't fight - rigid there means banding. Rule: aligned shafts take rigid, real shafts take flexible.",
        "text_overlay": [
            "RIGID: EXACT, UNFORGIVING",
            "BEAM + BELLOWS + SPIDER",
            "Z-AXIS: FLEXIBLE OR BANDING",
            "ALIGNED=RIGID, REAL=FLEXIBLE",
        ],
        "scenes": [
            {
                "goal": "Hook: the wobble fight",
                "teaching_point": "Two shafts, one misalignment",
                "shot": "macro shot of a rigid coupling on slightly misaligned shafts",
                "motion": "coupling strains as shafts wobble",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["rigid coupling", "misaligned shafts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a rigid coupling straining on misaligned shafts, bright task light, dark bench",
            },
            {
                "goal": "The rigid type",
                "teaching_point": "Exact motion, zero compliance",
                "shot": "medium shot of a rigid clamp coupling on a spindle",
                "motion": "shafts turn in perfect sync",
                "lighting": "neutral lab light",
                "background": "machine bench",
                "objects": ["rigid coupling", "spindle", "flanges"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a rigid clamp coupling on a machine spindle, neutral lab lighting, machine bench",
            },
            {
                "goal": "The flexible types",
                "teaching_point": "Beam, bellows, spider",
                "shot": "tabletop shot of three flexible couplings side by side",
                "motion": "pan across beam, bellows, and spider couplings",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["beam coupling", "bellows coupling", "spider coupling"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of beam bellows and spider couplings side by side, bright task light, dark bench",
            },
            {
                "goal": "The z-axis",
                "teaching_point": "Flexible coupling prevents banding",
                "shot": "close-up of a flexible coupling joining a z motor to a lead screw",
                "motion": "coupling flexes as the screw turns",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["z motor", "flexible coupling", "lead screw"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a flexible coupling joining a z motor to a lead screw, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the coupling to the alignment",
                "shot": "wide hero shot of a smooth-running motor and lead screw assembly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["motor assembly", "coupling", "lead screw"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a motor and lead screw assembly with a flexible coupling running smoothly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Rigid and flexible couplings side by side with an alignment arrow",
            "subject": "couplings with alignment diagram",
            "background": "dark machine shop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "couplings center, alignment arrow",
            "text": "COUPLINGS: RIGID VS FLEX",
            "elements": ["rigid coupling", "flexible coupling", "alignment arrow"],
            "style": "mechanical studio photography",
            "mood": "aligned, precise, mechanical",
            "prompt": "photograph of rigid and flexible couplings with an alignment arrow diagram, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Couplings: Rigid vs Flexible",
            "title_variations": [
                "What Type of Coupling Do I Need",
                "Motor Shaft Couplings",
                "Beam vs Bellows vs Spider",
                "Z-Axis Coupling Guide",
                "Shaft Coupling Explained",
            ],
            "description": "A coupling connects a motor shaft to whatever it drives while transmitting torque. Rigid couplings bolt two hubs together and pass motion with zero compliance: perfect when shafts are perfectly aligned, brutal when they are not, because misalignment loads bearings and causes vibration. Flexible couplings tolerate small misalignment and shock: beam couplings flex spiral cuts, bellows couplings twist elastically, and spider couplings use a rubber star to absorb shock. The classic printer case is the z-axis, where a flexible coupling joins motor to lead screw so wobbles do not fight each other - rigid there means z-banding. Rule: aligned shafts take rigid couplings; real shafts take flexible.",
            "hashtags": ["#Couplings", "#Mechanics", "#3Dprinting", "#Hardware"],
            "seo_keywords": [
                "rigid vs flexible coupling",
                "motor shaft coupling",
                "beam coupling explained",
                "z axis coupling",
                "spider coupling",
                "shaft misalignment coupling",
                "which coupling do I need",
            ],
        },
        "fact_check": [
            "Rigid couplings transmit motion exactly but cannot tolerate misalignment.",
            "Flexible couplings accommodate small misalignment and damp shock.",
            "Beam, bellows, and spider couplings have different compliance and torque ratings.",
            "A flexible coupling on the z-axis prevents motor wobble from becoming z-banding.",
            "Misaligned rigid couplings load bearings and generate vibration.",
        ],
    },
    # ======================================================================
    {
        "topic": "Convection Cooling",
        "core_question": "How does air actually cool hot parts?",
        "learning_objective": "The viewer can explain natural and forced convection and why fins and fans multiply cooling.",
        "engineering_summary": "Convection moves heat through a moving fluid - air over a heatsink, water through a radiator. Hot metal warms the air touching it; the warmed air expands, becomes less dense, rises, and cooler air flows in to replace it. That natural cycle carries heat away, but slowly: a thin boundary layer of hot air clings to the surface and insulates it. Forced convection breaks that layer: a fan constantly sweeps the hot air away and delivers fresh cool air, multiplying heat removal several times over. That is why heatsinks have fins - they multiply the surface area exposed to the flow - and why printer part-cooling fans make overhangs and bridges printable. The design rule is simple: more surface, more flow, more heat moved.",
        "real_world_application": "Heatsinks on stepper drivers, part-cooling fans on printers, and PC radiator loops all run on the same convection principles.",
        "common_misconceptions": [
            "A fan cools because it is cold (it cools by sweeping away the hot boundary layer)",
            "Bigger heatsinks alone fix everything (flow direction and blockage matter as much as size)",
            "Still air is fine for hot parts (natural convection moves far less heat than forced)",
        ],
        "teaching_strategy": "Show the rising air cycle, the boundary layer, then the fan and fin multiplication and a printer example.",
        "script": "Convection is heat carried away by moving fluid - air over a heatsink, water through a radiator. Hot metal warms the air touching it, that air expands and rises, cool air replaces it, and the cycle carries heat away. Forced convection adds a fan: it swaps the hot boundary layer constantly, and airflow multiplies cooling several times over. That's why heatsinks have fins - they multiply surface area in the flow - and why printer fans make overhangs printable. The design rules: more surface, more flow, more heat moved. If your part overheats, check the airflow first.",
        "text_overlay": [
            "WARM AIR RISES, COOL REPLACES",
            "BOUNDARY LAYER = INSULATOR",
            "FANS SWEEP THE LAYER AWAY",
            "FINS = SURFACE × FLOW",
        ],
        "scenes": [
            {
                "goal": "Hook: the rising air",
                "teaching_point": "Heat rides on moving fluid",
                "shot": "graphic-style shot of a hot heatsink with air arrows rising",
                "motion": "warm air rises off the fins",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heatsink", "rising air arrows"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a heatsink with rising warm air arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The boundary layer",
                "teaching_point": "Still air insulates",
                "shot": "macro shot of the thin hot air layer clinging to a hot surface",
                "motion": "boundary layer glow pulses near the surface",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["hot surface", "boundary layer", "heat glow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a hot metal surface with a glowing boundary layer of air, warm task light, dark bench",
            },
            {
                "goal": "The fan",
                "teaching_point": "Forced air breaks the layer",
                "shot": "medium shot of a fan blowing across a heatsink",
                "motion": "air visibly sweeps the fins",
                "lighting": "neutral lab light",
                "background": "electronics bench",
                "objects": ["fan", "heatsink", "airflow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a fan blowing across a heatsink on an electronics bench, neutral lighting",
            },
            {
                "goal": "In the printer",
                "teaching_point": "Part cooling makes overhangs printable",
                "shot": "wide shot of a part-cooling fan blowing on an overhang during a print",
                "motion": "overhang layers cool and harden",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["part cooling fan", "overhang", "print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a part cooling fan blowing on an overhang during a print, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Surface, flow, and heat moved",
                "shot": "wide hero shot of a finned heatsink with a fan in a clean lab",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finned heatsink", "fan"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finned heatsink with a fan in a clean lab, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A heatsink with air arrows rising and a fan blowing",
            "subject": "heatsink with convection arrows",
            "background": "dark electronics bench blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "heatsink center, arrows around",
            "text": "HOW AIR COOLS",
            "elements": ["heatsink", "air arrows", "fan"],
            "style": "thermodynamics studio photography",
            "mood": "cooling, flowing, clear",
            "prompt": "photograph of a finned heatsink with convection air arrows and a fan, hard key light with rim, dark electronics bench, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Convection: How Air Cools",
            "title_variations": [
                "How Convection Cooling Works",
                "Natural vs Forced Convection",
                "Why Heatsinks Have Fins",
                "How Fans Cool Electronics",
                "Heat Transfer Basics",
            ],
            "description": "Convection moves heat through a moving fluid - air over a heatsink, water through a radiator. Hot metal warms the air touching it, that air expands and rises, and cooler air replaces it. Natural convection works, but slowly: a thin boundary layer of hot air clings to the surface and insulates it. Forced convection breaks that layer: a fan constantly sweeps hot air away and delivers cool air, multiplying heat removal several times over. That is why heatsinks have fins - they multiply surface area in the flow - and why printer part-cooling fans make overhangs printable. More surface, more flow, more heat moved.",
            "hashtags": ["#Convection", "#Physics", "#Cooling", "#Engineering"],
            "seo_keywords": [
                "how convection cooling works",
                "natural vs forced convection",
                "why heatsinks have fins",
                "how fans cool electronics",
                "heat transfer convection",
                "boundary layer cooling",
                "part cooling fan physics",
            ],
        },
        "fact_check": [
            "Convection transfers heat through a moving fluid.",
            "Natural convection relies on warm air rising and cool air replacing it.",
            "A boundary layer of hot air insulates the surface and slows cooling.",
            "Forced convection with a fan multiplies heat removal several times over.",
            "Fins increase the surface area exposed to the airflow.",
        ],
    },
]
