"""Batch 3: fundamentals - slicer basics, materials, adhesion, and classic mechanics."""

CURATED = [
    # ======================================================================
    {
        "topic": "Layer Height",
        "core_question": "How does layer height affect print quality and strength?",
        "learning_objective": "The viewer can trade resolution, strength, and speed by choosing layer height within the 25-75% nozzle rule.",
        "engineering_summary": "Layer height sets the vertical resolution of an FDM print. Smaller layers (0.08-0.12 mm) improve surface smoothness and capture fine detail, but roughly double print time versus 0.2 mm. Larger layers (0.28-0.32 mm) print faster but show visible ridges and lose small features. Practical range is 25-75% of nozzle diameter: 0.4 mm nozzles print well from 0.1 to 0.3 mm. Layer adhesion is a larger fraction of part strength at thin layers, while z-axis strength is always below x/y strength.",
        "real_world_application": "Print farms batch: draft parts at 0.28 mm, cosmetic parts at 0.12-0.16 mm; thread and text features often force 0.12 mm or lower.",
        "common_misconceptions": [
            "Thinner layers always make stronger parts (x/y strength improves slightly; z strength is governed by bonding temperature and time)",
            "You can print any layer height on any nozzle (range is roughly 25-75% of nozzle diameter)",
            "0.2 mm is the only sensible default (0.16 mm is a common quality/speed sweet spot)",
        ],
        "teaching_strategy": "Show the same part at 0.12, 0.2, and 0.3 mm under raking light, then a clock for each, making the trade a visible choice.",
        "script": "Every print is built from stacked pancakes of plastic. Layer height is how thick each one is, and it's your biggest quality lever. Drop to 0.12 millimeters and surfaces turn smooth, but print time climbs. Crank to 0.3 and you're fast, but you can see every ridge. The rule: keep layer height between a quarter and three quarters of your nozzle diameter. So for a 0.4 nozzle, that's 0.1 to 0.3 millimeters. Resolution costs time - choose your trade.",
        "text_overlay": [
            "STACKED PANCAKES",
            "0.12 mm = SMOOTH + SLOW",
            "0.30 mm = FAST + RIDGED",
            "25-75% OF NOZZLE",
            "RESOLUTION COSTS TIME",
        ],
        "scenes": [
            {
                "goal": "Hook: three layer heights",
                "teaching_point": "Layer height controls visible surface ridges",
                "shot": "macro side-by-side of parts printed at 0.12, 0.2, and 0.3 mm",
                "motion": "slow pan across the three surfaces",
                "lighting": "raking side light",
                "background": "dark bench blur",
                "objects": ["printed cubes", "0.12 mm sample", "0.3 mm sample"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of three 3D printed cubes with different layer heights showing smooth to ridged surfaces, raking side light, dark bench",
            },
            {
                "goal": "The stacking idea",
                "teaching_point": "Prints are stacked layers of plastic",
                "shot": "graphic-style shot of stacked layer lines building a cube",
                "motion": "layers stack one by one",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer stack", "cube outline"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D layer stack building a cube shape on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The quality trade",
                "teaching_point": "Small layers smooth surfaces but cost time",
                "shot": "clock overlay on the three cubes",
                "motion": "clock hands spin for each sample",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["printed cubes", "clock overlay"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of three 3D printed cubes with a clock overlay, even diffused lighting, neutral workbench",
            },
            {
                "goal": "The nozzle rule",
                "teaching_point": "Keep layer height at 25-75% of nozzle diameter",
                "shot": "macro shot of a 0.4 mm nozzle next to printed layers",
                "motion": "slow push-in on the nozzle",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["0.4 mm nozzle", "printed layers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 0.4 millimeter nozzle next to freshly printed layers, bright task lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match layer height to the part's purpose",
                "shot": "wide hero shot of a detailed print finishing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["detailed print", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a detailed 3D print on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three stacked cubes morphing from smooth to ridged with a ruler overlay",
            "subject": "three 3D printed cubes at different layer heights",
            "background": "dark bench blur",
            "angle": "macro three-quarter",
            "lighting": "raking side light",
            "composition": "three cubes lined up, ruler along the bottom",
            "text": "LAYER HEIGHT",
            "elements": ["smooth cube", "ridged cube", "layer lines"],
            "style": "diagnostic macro photography",
            "mood": "comparative, precise, clear",
            "prompt": "macro photograph of three 3D printed cubes at increasing layer heights from smooth to heavily ridged, raking side light, dark workbench, 9:16 vertical composition, ultra sharp layer detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Layer Height: The Quality-Speed Trade",
            "title_variations": [
                "What Layer Height Should You Use?",
                "0.12 vs 0.2 vs 0.3 mm Layer Height",
                "Why Thin Layers Cost You Time",
                "The 25-75% Nozzle Rule",
                "Layer Height and Print Strength",
            ],
            "description": "Layer height is the thickness of each stacked layer of plastic and your biggest quality lever. Smaller layers - around 0.12 mm - smooth out curved surfaces but can nearly double print time; larger layers like 0.3 mm are fast but leave visible ridges. The rule of thumb: keep layer height between a quarter and three quarters of your nozzle diameter, so 0.1 to 0.3 mm on a 0.4 mm nozzle. This short explains the trade, the strength effects, and how to match layer height to draft, cosmetic, and functional parts.",
            "hashtags": ["#3Dprinting", "#LayerHeight", "#3DPrintingTips", "#Slicer"],
            "seo_keywords": [
                "layer height",
                "layer height vs quality",
                "best layer height",
                "0.4 nozzle layer height",
                "print speed layer height",
                "smooth 3d prints layer height",
                "layer height strength",
            ],
        },
        "fact_check": [
            "Practical layer height range is roughly 25-75% of nozzle diameter; 0.4 mm nozzles print 0.1-0.3 mm.",
            "Halving layer height roughly doubles print time for identical geometry.",
            "Surface roughness in FDM is dominated by layer ridges (stair-stepping), so thinner layers visibly smooth curved surfaces.",
            "Z-axis (interlayer) strength is generally 30-50% lower than in-plane strength; thin layers increase layer count but bonding quality is governed by melt temperature and time, not layer count alone.",
            "Units: layer height in millimeters (mm).",
        ],
    },
    # ======================================================================
    {
        "topic": "TPU",
        "core_question": "How do you print flexible TPU without jams?",
        "learning_objective": "The viewer can set up a flexible filament profile: slow speed, tuned retraction, and extruder path management.",
        "engineering_summary": "TPU is a thermoplastic polyurethane with Shore hardness from 60A to 95A; softer grades are nearly rubber. Flexible filaments buckle and jam in constrained paths: they compress between drive gears and squirm inside long Bowden tubes. Direct-drive extruders, slow speeds (15-30 mm/s), near-zero retraction, and loose filament path tension prevent jams. Shore hardness drives settings: 95A is forgiving, 60A needs slow prints and wide tolerances.",
        "real_world_application": "Phone cases, gaskets, RC tires, drone bumpers, and vibration isolators; print farms use 95A TPU for durable functional parts and reserve 60-80A for soft sealing parts.",
        "common_misconceptions": [
            "TPU is impossible to print (95A on direct drive prints reliably at slow speed)",
            "You need a special nozzle (standard nozzles work; only the filament path matters)",
            "Retraction settings stay the same as PLA (flexible filament needs minimal retraction to avoid jams)",
        ],
        "teaching_strategy": "Show the buckling failure first: filament wadding up inside the extruder, then the three fixes: direct drive, slow speed, minimal retraction.",
        "script": "Rubber-like filament: that's TPU, and it prints... carefully. The problem? Flexibility. The filament squirms and buckles, jamming anywhere the path is tight. Three rules fix it. One: direct drive, so the path from gear to nozzle is short. Two: slow down - fifteen to thirty millimeters per second. Three: almost no retraction, because pulling soft filament back just kinks it. Start with 95A, the firmer shore hardness, and it prints like a charm. Flexible material, fixed rules.",
        "text_overlay": [
            "TPU = RUBBER PRINTS",
            "BUCKLING = JAM",
            "RULE 1: DIRECT DRIVE",
            "RULE 2: SLOW",
            "RULE 3: NO RETRACTION",
        ],
        "scenes": [
            {
                "goal": "Hook: the jam",
                "teaching_point": "Flexible filament buckles in tight paths",
                "shot": "macro close-up of TPU wadding up inside an extruder",
                "motion": "slow push-in on the jam",
                "lighting": "bright task light",
                "background": "printer in lab blur",
                "objects": ["extruder", "TPU filament jam"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of flexible TPU filament jamming and wadding inside a 3D printer extruder, bright task lighting, print lab background",
            },
            {
                "goal": "Why flexibility breaks it",
                "teaching_point": "Soft filament compresses instead of pushing",
                "shot": "graphic-style shot of a filament buckling in a tube",
                "motion": "compression and fold animation",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["filament", "tube", "buckle"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of flexible filament buckling inside a tube on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Fix 1: direct drive",
                "teaching_point": "A short filament path prevents squirming",
                "shot": "medium shot of a direct-drive extruder on a printer",
                "motion": "slow push-in on the drive gears",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["direct drive extruder", "TPU filament"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a direct-drive extruder loaded with TPU filament on a 3D printer, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Fix 2 and 3",
                "teaching_point": "Slow speed and minimal retraction prevent kinks",
                "shot": "slicer settings screen showing TPU speed and retraction values",
                "motion": "value callouts appear",
                "lighting": "screen glow in dark room",
                "background": "dark studio",
                "objects": ["slicer screen", "speed setting", "retraction setting"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer interface showing speed and retraction settings for TPU, screen glow in a dark studio, clean UI",
            },
            {
                "goal": "Takeaway: 95A",
                "teaching_point": "Start with firm 95A TPU for reliability",
                "shot": "wide hero shot of a flexible TPU part flexing",
                "motion": "slow flex demonstration",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["TPU part", "hands flexing it"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of hands flexing a rubbery TPU 3D printed part, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "TPU filament kinked in a clear tube vs the same filament printing clean on direct drive",
            "subject": "flexible TPU filament with a sharp kink next to a direct-drive extruder",
            "background": "dark print lab blur",
            "angle": "macro eye-level",
            "lighting": "hard key with rim",
            "composition": "kinked filament left, extruder right",
            "text": "PRINT TPU",
            "elements": ["kinked filament", "direct drive extruder", "flexible print"],
            "style": "diagnostic macro photography",
            "mood": "solved, practical, flexible",
            "prompt": "macro photograph of a kinked TPU filament on the left and a direct-drive extruder on the right, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp filament detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "TPU Without Jams: 3 Rules",
            "title_variations": [
                "How to Print Flexible Filament",
                "TPU Settings That Work",
                "Why TPU Keeps Jamming (And the Fix)",
                "Shore Hardness Explained for TPU",
                "Print Rubber Parts on FDM",
            ],
            "description": "TPU prints like rubber but jams like a nightmare, because flexible filament buckles and squirms inside tight filament paths. This short covers the three rules that fix it: use a direct-drive extruder so the path from drive gear to nozzle is short, slow down to roughly 15-30 mm/s, and run almost no retraction since pulling soft filament back just kinks it. It also explains shore hardness - starting with firm 95A makes flexible printing reliable - and why wet TPU still benefits from drying.",
            "hashtags": ["#3Dprinting", "#TPU", "#FlexibleFilament", "#3DPrintingTips"],
            "seo_keywords": [
                "tpu filament printing",
                "flexible filament settings",
                "tpu jamming fix",
                "direct drive tpu",
                "shore hardness tpu",
                "print flexible parts",
                "tpu retraction",
            ],
        },
        "fact_check": [
            "TPU Shore hardness ranges roughly 60A-95A; 95A is stiffest and most forgiving, 60A is nearly rubber.",
            "Flexible filament buckles because compressive extrusion force exceeds its column stability inside constrained paths; direct drive shortens that path.",
            "Typical TPU speeds are 15-30 mm/s for soft grades, higher for 95A; retraction is minimal (0-2 mm) to prevent kinking.",
            "TPU absorbs little moisture compared to nylon but still benefits from drying if stored long.",
            "Units: speed in mm/s; hardness in Shore A.",
        ],
    },
    # ======================================================================
    {
        "topic": "Bed Temperature Basics",
        "core_question": "What bed temperature should I use?",
        "learning_objective": "The viewer can pick bed temperature by material and understand why the first layer needs heat.",
        "engineering_summary": "A heated bed raises the temperature of the first layers, slowing their cooling so shrinkage stress builds gradually and adhesion to the plate wins the tug-of-war against warping. Typical bed temperatures: PLA 50-65 C, PETG 70-90 C, ABS 90-110 C, TPU 40-60 C. Excess bed heat can soften the lower layers of a print (softening point issues) and cause 'elephant foot' bulges, so temperature is tuned, not maximized.",
        "real_world_application": "Print farms standardize bed temperature per material profile; ABS parts rely on hot beds plus chambers; glass beds need higher settings than textured plates because the glass itself must reach temperature.",
        "common_misconceptions": [
            "Hotter bed always means better adhesion (too hot softens lower layers and bulges the print)",
            "Bed temperature heats the air (it heats the plate; the surface temperature matters, not the setpoint)",
            "You need the same temperature on all bed surfaces (glass needs more heat transfer time than PEI)",
        ],
        "teaching_strategy": "Show the first-layer tug-of-war with temperature on the adhesion side, then a temperature ladder for common materials.",
        "script": "Why does your printer heat the bed? It's a first-layer insurance policy. A warm plate slows cooling on the bottom of the print, so shrinkage happens gradually and the plastic stays glued down. The numbers? PLA likes fifty to sixty-five, PETG runs seventy to ninety, and ABS wants ninety to one-ten. But hotter isn't always better: a scorching bed softens the layers right above it, and your part grows an elephant foot. Heat the bed for the material - not for drama.",
        "text_overlay": [
            "WARM BED = SLOW COOLING",
            "PLA: 50-65°C",
            "PETG: 70-90°C",
            "ABS: 90-110°C",
            "TOO HOT = ELEPHANT FOOT",
        ],
        "scenes": [
            {
                "goal": "Hook: the first-layer tug of war",
                "teaching_point": "Heat slows cooling so shrinkage doesn't beat adhesion",
                "shot": "graphic-style shot of a cooling layer pulling against the bed",
                "motion": "tension arrows fight as bed warms",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["first layer", "bed", "tension arrows"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a first layer being pulled against a heated bed with tension arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The temperature ladder",
                "teaching_point": "Each material has a working bed range",
                "shot": "graphic-style shot of material spools with temperature readouts",
                "motion": "temperature values pop in per material",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["material spools", "temperature readouts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of filament spools with temperature readouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Too hot",
                "teaching_point": "Excess heat softens lower layers and bulges the base",
                "shot": "macro close-up of a print with elephant-foot bulge",
                "motion": "slow pan around the bulge",
                "lighting": "raking side light",
                "background": "dark bench blur",
                "objects": ["printed part with elephant foot"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a 3D printed part with an elephant foot bulge at the base, raking side light, dark bench",
            },
            {
                "goal": "Bed surface matters",
                "teaching_point": "Glass needs time to reach temperature; PEI transfers faster",
                "shot": "medium shot of a hand touching a bed surface thermometer",
                "motion": "temperature check action",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["bed surface", "surface thermometer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand checking the bed surface temperature with a thermometer, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match bed heat to material and let it stabilize",
                "shot": "wide hero shot of a printer with a perfectly flat first layer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "perfect first layer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer with a flawless first layer on a glossy bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Thermometer dial mounted on a heated bed with a flat perfect first layer",
            "subject": "printed first layer on a heated bed with a temperature dial overlay",
            "background": "dark print lab blur",
            "angle": "macro low-angle",
            "lighting": "hard key with rim",
            "composition": "first layer centered, dial in the corner",
            "text": "BED TEMP",
            "elements": ["first layer", "heated bed", "temperature dial"],
            "style": "technical macro photography",
            "mood": "warm, precise, practical",
            "prompt": "macro photograph of a glossy first layer on a heated print bed with a temperature dial overlay in the corner, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bed Temperature: Set It Right",
            "title_variations": [
                "What Bed Temperature for PLA, PETG, ABS?",
                "Why the Bed Needs Heat",
                "Elephant Foot? Your Bed's Too Hot",
                "First-Layer Insurance: Bed Heat",
                "Bed Temperature by Material",
            ],
            "description": "Why do printers heat the bed? A warm plate slows first-layer cooling so shrinkage happens gradually and adhesion wins the tug-of-war against warping. This short covers the working ranges - PLA 50-65 C, PETG 70-90 C, ABS 90-110 C - and why hotter is not always better: too much heat softens the layers above the plate and grows an elephant foot. It also explains why glass beds need time to soak to temperature while PEI and spring steel transfer heat faster. Set the bed for the material, not for drama.",
            "hashtags": ["#3Dprinting", "#BedTemperature", "#FirstLayer", "#3DPrintingTips"],
            "seo_keywords": [
                "bed temperature",
                "pla bed temp",
                "petg bed temperature",
                "abs bed temp",
                "elephant foot fix",
                "heated bed temperature",
                "first layer adhesion temperature",
            ],
        },
        "fact_check": [
            "PLA bed 50-65 C, PETG 70-90 C, ABS 90-110 C, TPU 40-60 C are typical starting ranges; surface thermometers can read 10-20 C below setpoint.",
            "A heated bed reduces the thermal gradient across the first layers, slowing warping-driven curling.",
            "Overheating the bed can push the part base above the material's glass transition region, causing softening and elephant foot.",
            "Glass has low thermal conductivity and needs soak time; textured PEI and spring steel transfer heat faster.",
            "Units: temperatures in degrees Celsius.",
        ],
    },
    # ======================================================================
    {
        "topic": "Poor Bed Adhesion",
        "core_question": "Why won't my print stick to the bed?",
        "learning_objective": "The viewer can run the adhesion checklist: surface cleanliness, temperature, z-offset, and surface choice.",
        "engineering_summary": "First-layer adhesion depends on four variables in order: cleanliness (oils and dust break the bond), temperature (material-appropriate bed heat), nozzle-to-bed distance (correct squish), and the bed surface itself (PEI, textured plates, or glass). A failed first layer is almost always one of these four, and glues and adhesives compensate for deficits rather than fixing the cause. PEI provides chemical and mechanical keying; glass is clean but slick without help.",
        "real_world_application": "Print farms clean plates with isopropyl alcohol between runs; ABS uses textured plates or heated chambers; flexible magnetic plates make removal part of the adhesion system.",
        "common_misconceptions": [
            "Glue stick is the fix (it masks cleanliness or temperature problems and gets spread around)",
            "Scratching the bed helps (damaged surfaces reduce consistency and can release suddenly)",
            "Bed adhesion problems are the printer's fault (surface prep is an operator discipline)",
        ],
        "teaching_strategy": "Run the checklist visually as a diagnostic flow: dirty plate -> clean it, cold bed -> heat it, high nozzle -> squish it, slick glass -> swap surface.",
        "script": "Your print won't stick. Before you rage-apply glue, run the four-check: One, is the plate clean? Finger oils are a release agent. Wipe with isopropyl. Two, is the bed hot enough? PLA wants fifty-plus. Three, is the nozzle close enough? Squish beats distance. Four, is the surface right? PEI grabs plastic chemically; bare glass is a skating rink. Nine times out of ten, one of these four is your problem. Fix the cause, not the symptom.",
        "text_overlay": [
            "1. CLEAN?",
            "2. HOT ENOUGH?",
            "3. CLOSE ENOUGH?",
            "4. RIGHT SURFACE?",
            "FIX THE CAUSE",
        ],
        "scenes": [
            {
                "goal": "Hook: the failed first layer",
                "teaching_point": "A lifting or detached first layer starts every failure chain",
                "shot": "macro close-up of a first layer peeling from the bed",
                "motion": "slow push-in on the peeling edge",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["peeling first layer", "build plate"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed first layer peeling off the build plate, raking side light, dark workshop background",
            },
            {
                "goal": "Check 1: cleanliness",
                "teaching_point": "Oils and dust are release agents",
                "shot": "medium shot of wiping a plate with isopropyl alcohol",
                "motion": "wipe action across the plate",
                "lighting": "bright workshop light",
                "background": "print lab",
                "objects": ["build plate", "alcohol wipe", "hands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand wiping a 3D printer build plate with an isopropyl alcohol wipe, bright workshop lighting, print lab",
            },
            {
                "goal": "Checks 2 and 3",
                "teaching_point": "Heat and squish are the two numbers that matter",
                "shot": "printer screen showing bed temp and a macro of the nozzle printing the first layer",
                "motion": "value callouts and print action",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer screen", "nozzle", "first layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer nozzle printing a first layer with a screen showing bed temperature, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Check 4: the surface",
                "teaching_point": "PEI bonds chemically; bare glass is slick",
                "shot": "split-screen of a PEI plate and a bare glass bed",
                "motion": "wipe between the two surfaces",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["PEI plate", "glass bed"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two print bed surfaces side by side, a textured PEI plate and a bare glass bed, even diffused lighting, neutral bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Run the four-check before adding helpers",
                "shot": "wide hero shot of a perfectly stuck part printing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "perfect first layer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer with a perfectly adhered first layer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Four numbered checkmarks over a build plate: clean, hot, close, right surface",
            "subject": "glossy build plate with a perfect first layer and four numbered markers",
            "background": "dark print lab blur",
            "angle": "macro overhead",
            "lighting": "hard key with rim",
            "composition": "plate filling the frame, markers in the corner",
            "text": "4-CHECK",
            "elements": ["build plate", "first layer", "checklist markers"],
            "style": "diagnostic macro photography",
            "mood": "ordered, corrective, confident",
            "prompt": "macro overhead photograph of a glossy build plate with a perfect printed first layer and four numbered checklist markers, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Print Not Sticking? Run the 4-Check",
            "title_variations": [
                "Why Your First Layer Won't Stick",
                "Bed Adhesion: Fix the Cause, Not the Symptom",
                "The 4-Step First Layer Checklist",
                "Glue Isn't the Answer: Bed Adhesion 101",
                "Make Every First Layer Stick",
            ],
            "description": "Why won't your print stick? Run the four-check before grabbing the glue stick: is the plate clean of finger oils, is the bed hot enough, is the nozzle close enough for proper squish, and is the surface right - PEI bonds chemically while bare glass is slick. Nine times out of ten the first layer fails because of one of these four. Fix the cause, not the symptom.",
            "hashtags": ["#3Dprinting", "#BedAdhesion", "#FirstLayer", "#Troubleshooting"],
            "seo_keywords": [
                "print not sticking",
                "bed adhesion fix",
                "first layer won't stick",
                "clean build plate",
                "pei bed adhesion",
                "z offset first layer",
                "glue stick bed",
            ],
        },
        "fact_check": [
            "Skin oils are hydrocarbon release agents; isopropyl alcohol is the standard degreaser for PEI and glass.",
            "PEI offers both mechanical keying and chemical bonding with melted thermoplastics; this is why PEI sheets release hot but grip hot.",
            "Bare glass is smooth and non-porous, requiring heat, squish, and often an adhesion aid.",
            "A clean, correctly heated, correctly squished first layer removes the need for glues on most common materials.",
            "Repeated plate damage (scratches, gouges) reduces adhesion consistency and can cause sudden release mid-print.",
        ],
    },
    # ======================================================================
    {
        "topic": "Brim vs Raft vs Skirt",
        "core_question": "Brim, raft, or skirt - which one do I need?",
        "learning_objective": "The viewer can select the right bed helper: skirt for priming, brim for adhesion, raft for bad beds and warping materials.",
        "engineering_summary": "The three bed helpers serve different jobs. A skirt primes the nozzle and checks bed level without touching the part (no cleanup). A brim is a single-layer ring attached to the part edge, multiplying adhesion area against warping and lifting (simple peel-off cleanup). A raft is a full sacrificial base under the part, leveling over an imperfect bed and protecting delicate first layers, at the cost of surface quality on the part bottom and extra material. Choice is driven by warping risk, bed quality, and part geometry.",
        "real_world_application": "ABS and nylon parts use brims for warp resistance; prints with tiny contact area (columns, vases) use brims; badly leveled beds and flexible materials sometimes get rafts; production runs use skirts to validate extrusion before the part starts.",
        "common_misconceptions": [
            "A raft fixes a bad bed forever (it masks level issues and adds cleanup and surface defects)",
            "A brim is a raft (a brim is one layer attached to the part; a raft is a separate base)",
            "Skirts help adhesion (skirts never touch the part; they prime the nozzle)",
        ],
        "teaching_strategy": "Show the three side by side on the bed with a decision line: no risk = skirt, warp risk = brim, bad bed = raft.",
        "script": "Skirt, brim, raft - three helpers, three jobs. The skirt is a test lap around the part: it primes the nozzle and confirms leveling, but never touches your print. The brim is a one-layer ring fused to the part edge: it multiplies the contact area, so warping corners have something to grip. The raft is a full sacrificial base: it gives a crooked bed a flat floor, but the part bottom looks rough. No risk, no worries: skirt. Warping material: brim. Bad bed: raft.",
        "text_overlay": [
            "SKIRT = TEST LAP",
            "BRIM = GRIP RING",
            "RAFT = SACRIFICIAL FLOOR",
            "WARP RISK = BRIM",
            "BAD BED = RAFT",
        ],
        "scenes": [
            {
                "goal": "Hook: the three helpers",
                "teaching_point": "All three sit on the bed but do different jobs",
                "shot": "wide shot of a bed with skirt, brim, and raft samples",
                "motion": "slow pan across the three",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["skirt sample", "brim sample", "raft sample"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a print bed with a skirt, a brim, and a raft sample side by side, neutral lab lighting, modern print lab",
            },
            {
                "goal": "The skirt",
                "teaching_point": "Priming and level check without touching the part",
                "shot": "macro close-up of a skirt line printing around a part",
                "motion": "nozzle traces the skirt loop",
                "lighting": "bright task light",
                "background": "dark blur",
                "objects": ["skirt line", "nozzle", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a nozzle printing a skirt line around a part on the build plate, bright task lighting, dark background",
            },
            {
                "goal": "The brim",
                "teaching_point": "Fused ring multiplies adhesion area against warping",
                "shot": "macro shot of a part with a brim ring, lifting corners held",
                "motion": "slow push-in on the brim edge",
                "lighting": "raking side light",
                "background": "dark bench blur",
                "objects": ["part with brim", "brim ring"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a 3D printed part with a brim ring on the build plate, raking side light, dark bench",
            },
            {
                "goal": "The raft",
                "teaching_point": "Sacrificial base levels over an imperfect bed",
                "shot": "macro shot of a part sitting on a raft with the interface visible",
                "motion": "slow tilt around the raft",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["part on raft", "raft base"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part sitting on a raft base, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Takeaway: the decision",
                "teaching_point": "Pick by risk: none = skirt, warp = brim, bad bed = raft",
                "shot": "wide hero shot of a part printing cleanly with a brim",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["part with brim", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer printing a part with a brim on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three bed helpers on a decision flow: skirt, brim, raft with arrows",
            "subject": "print bed with skirt line, brim ring, and raft base arranged left to right",
            "background": "dark print lab blur",
            "angle": "macro overhead",
            "lighting": "hard key with rim",
            "composition": "three helpers in a row with arrows between them",
            "text": "BRIM vs RAFT",
            "elements": ["skirt line", "brim ring", "raft base"],
            "style": "technical macro photography",
            "mood": "comparative, orderly, clear",
            "prompt": "macro overhead photograph of a print bed with a skirt line, a brim ring, and a raft base arranged in a row, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Brim, Raft, or Skirt? Pick Right",
            "title_variations": [
                "Skirt vs Brim vs Raft Explained",
                "When to Use a Brim (And When Not To)",
                "The Raft Myth: It Doesn't Fix Your Bed",
                "Bed Helpers: Three Jobs, Three Tools",
                "Which Bed Helper for Warping?",
            ],
            "description": "Skirt, brim, and raft do three different jobs. A skirt primes the nozzle and checks level without touching the part. A brim fuses to the part edge and multiplies adhesion area against warping. A raft provides a sacrificial base over a bad bed - at the cost of bottom surface quality. This short gives you the decision rule for every print.",
            "hashtags": ["#3Dprinting", "#Brim", "#Raft", "#3DPrintingTips"],
            "seo_keywords": [
                "brim vs raft",
                "skirt brim raft difference",
                "when to use a brim",
                "3d print raft",
                "bed adhesion helpers",
                "warping brim",
                "raft vs brim print",
            ],
        },
        "fact_check": [
            "A skirt is a nozzle-priming outline with zero contact with the part; it is also a quick leveling check.",
            "A brim is typically 3-15 mm wide, one layer tall, fused to the part perimeter; it resists corner lifting but requires trimming.",
            "A raft is a multi-layer sacrificial base; it can compensate for moderate bed unlevelness but roughens the part's bottom face and adds material and time.",
            "PETG can bond so strongly to brims and rafts that removal damages the part; interface settings or a larger gap help.",
            "Units: brim width and raft height in millimeters.",
        ],
    },
    # ======================================================================
    {
        "topic": "Calipers",
        "core_question": "How do calipers work and how do I read them?",
        "learning_objective": "The viewer can measure with digital or vernier calipers and knows the accuracy limits of the tool.",
        "engineering_summary": "Calipers measure outside, inside, and depth dimensions with a sliding jaw and a scale. Digital calipers resolve to 0.01 mm (0.0005 in); vernier calipers resolve to 0.02 mm. Accuracy is typically +/-0.02-0.03 mm for quality tools. Measurement technique dominates errors: measuring pressure, jaw alignment, and part cleanliness cause more error than the tool itself. Zero-check before use and calibrate against a standard.",
        "real_world_application": "3D printing workflows use calipers to check hole sizes against design intent, verify print shrinkage, and fit bearings; machinists use them for quick shop measurements before finer tools (micrometers) take over.",
        "common_misconceptions": [
            "Calipers are the most accurate tool in the shop (micrometers resolve 10x finer)",
            "The digital display is always right (jaw pressure and zero drift still matter)",
            "Measuring holes with the inside jaws gives the true size (jaw geometry and tilt introduce error)",
        ],
        "teaching_strategy": "Show the three measuring modes (outside, inside, depth) in one continuous action, then a reading check: print, measure, compare to CAD.",
        "script": "Every measurement starts with calipers. Slide the jaw shut, check zero, then squeeze the part gently - not hard. Digital calipers read to a hundredth of a millimeter, which is about a tenth of a human hair. Use the big jaws for outside dimensions, the small ones for holes and slots, and the tail for depth. Keep it square, keep it level, and zero it often. Calipers won't measure badly - people do. Treat them right, and every print fits.",
        "text_overlay": [
            "ZERO CHECK FIRST",
            "0.01 mm RESOLUTION",
            "OUTSIDE / INSIDE / DEPTH",
            "SQUARE + LEVEL",
            "CALIPERS DON'T LIE - PEOPLE DO",
        ],
        "scenes": [
            {
                "goal": "Hook: measuring a print",
                "teaching_point": "Calipers are the first tool for verifying a print",
                "shot": "macro close-up of calipers measuring a printed part",
                "motion": "slow jaw closure on the part",
                "lighting": "bright bench light",
                "background": "workbench blur",
                "objects": ["digital calipers", "printed part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of digital calipers measuring a 3D printed part on a workbench, bright bench lighting, shallow depth of field",
            },
            {
                "goal": "Zero and resolution",
                "teaching_point": "Check zero; digital reads to 0.01 mm",
                "shot": "macro close-up of the caliper display and closed jaws",
                "motion": "slow push-in on the display",
                "lighting": "soft studio light",
                "background": "dark bench blur",
                "objects": ["caliper display", "closed jaws"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a digital caliper display showing a reading with the jaws closed, soft studio lighting, dark bench",
            },
            {
                "goal": "The three modes",
                "teaching_point": "Outside jaws, inside jaws, depth tail",
                "shot": "three quick shots: outside, inside, depth measuring",
                "motion": "cuts between the three modes",
                "lighting": "bright bench light",
                "background": "workbench blur",
                "objects": ["calipers", "part", "hole", "slot"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of calipers measuring the outside dimension of a part on a workbench, bright bench lighting, workshop photography",
            },
            {
                "goal": "Technique",
                "teaching_point": "Square, level, and light pressure rule every measurement",
                "shot": "medium shot of a hand holding calipers squarely on a part",
                "motion": "slow alignment action",
                "lighting": "neutral workshop light",
                "background": "precision workshop",
                "objects": ["calipers", "hand", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand holding calipers squarely against a metal part in a precision workshop, neutral workshop lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Calipers fit prints to reality",
                "shot": "wide hero shot of a caliper over a finished print on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark workshop",
                "objects": ["calipers", "finished print"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of digital calipers resting on a finished 3D print on a workbench, dark workshop background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Calipers gripping a printed part with a huge digital readout",
            "subject": "digital calipers measuring a 3D printed cube, display prominent",
            "background": "dark workbench blur",
            "angle": "macro three-quarter",
            "lighting": "hard key with rim",
            "composition": "calipers diagonal across the frame, display near center",
            "text": "0.01 mm",
            "elements": ["caliper jaws", "printed cube", "digital display"],
            "style": "tool macro photography",
            "mood": "precise, tactile, confident",
            "prompt": "macro photograph of digital calipers measuring a 3D printed cube with a large digital readout, hard key light with rim, dark workbench, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Calipers: Measure Like a Machinist",
            "title_variations": [
                "How to Use Digital Calipers",
                "The 3 Modes of a Caliper",
                "Why Your Measurements Are Wrong",
                "Calipers for 3D Printing: Read the Truth",
                "Measure, Verify, Print Perfect",
            ],
            "description": "Calipers are the first tool for verifying any print or part. Learn the three measuring modes - outside jaws for outer dimensions, inside jaws for holes and slots, and the depth tail - plus why zero checking matters, how digital calipers resolve to 0.01 mm, and the technique errors that ruin readings: jaw pressure, tilt, and dirt. Calipers don't measure badly, people do. This short turns a quick measurement habit into print-perfect fitment, whether you work with digital or vernier tools.",
            "hashtags": ["#Tools", "#Calipers", "#Measurement", "#3DPrinting"],
            "seo_keywords": [
                "how to use calipers",
                "digital caliper reading",
                "caliper accuracy",
                "measure 3d prints",
                "vernier caliper",
                "caliper zeroing",
                "precision measurement tools",
            ],
        },
        "fact_check": [
            "Digital calipers typically resolve 0.01 mm; quality instruments hold +/-0.02-0.03 mm accuracy.",
            "Vernier calipers resolve 0.02 mm and require correct scale reading; digital avoids parallax but shares the same mechanical error sources.",
            "Measurement repeatability is limited by jaw pressure, parallelism, and cleanliness, not the display resolution.",
            "Micrometers resolve 0.001 mm and are the finer tool for smooth cylindrical surfaces.",
            "Units: millimeters (mm) or inches; 1 in = 25.4 mm.",
        ],
    },
    # ======================================================================
    {
        "topic": "Levers & Mechanical Advantage",
        "core_question": "How do levers multiply force?",
        "learning_objective": "The viewer can apply the lever balance rule (effort x effort arm = load x load arm) and classify the three lever classes.",
        "engineering_summary": "A lever pivots on a fulcrum and trades distance for force: the moments (force x distance from fulcrum) balance. Mechanical advantage equals the effort arm divided by the load arm. Class 1 levers (fulcrum between) include seesaws and pry bars; class 2 (load between) includes wheelbarrows and nutcrackers with advantage always above 1; class 3 (effort between) includes tweezers and brooms, trading force for reach and speed. Work is conserved minus friction.",
        "real_world_application": "Crowbars, wheelbarrows, bolt cutters, staplers, and human limbs all trade distance for force; 3D printed snap-fit clamps and linkage mechanisms use lever ratios to multiply grip force.",
        "common_misconceptions": [
            "Levers create energy (they trade distance for force; work in equals work out minus friction)",
            "Longer lever is always better (it multiplies force but costs travel and can overload the pivot)",
            "Only pry bars are levers (scissors, wheelbarrows, and your forearm are all levers)",
        ],
        "teaching_strategy": "Start with a crowbar lifting a crate: small effort, long arm, visible force multiplication; then classify everyday tools into the three classes with a single diagram.",
        "script": "One person, one crowbar, one crate. How? The lever. A lever pivots on a fulcrum and trades distance for force: push a long arm a long way, and the short arm hits harder. The balance is simple - effort times effort arm equals load times load arm. Crowbars, seesaws, wheelbarrows, even your forearm - every one is a lever trading motion for might. You never get something for nothing: the extra force comes from extra travel. Levers don't make energy. They just aim it.",
        "text_overlay": [
            "FULCRUM = PIVOT",
            "EFFORT x ARM = LOAD x ARM",
            "LONG ARM = MORE FORCE",
            "CLASS 1 / 2 / 3",
            "WORK IN = WORK OUT",
        ],
        "scenes": [
            {
                "goal": "Hook: the crowbar",
                "teaching_point": "One person lifts a crate with a long lever",
                "shot": "medium shot of hands prying a crate with a crowbar",
                "motion": "slow pry action",
                "lighting": "warm workshop light",
                "background": "workshop floor",
                "objects": ["crowbar", "crate", "fulcrum block"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of hands prying a wooden crate with a steel crowbar in a workshop, warm practical lighting",
            },
            {
                "goal": "The balance rule",
                "teaching_point": "Effort x effort arm = load x load arm",
                "shot": "graphic-style shot of a lever with distances and forces labeled",
                "motion": "force and arm lengths animate",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["lever diagram", "fulcrum", "force arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a lever diagram with force and distance arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The three classes",
                "teaching_point": "Fulcrum, load, effort positions define the classes",
                "shot": "three everyday tools: pry bar, wheelbarrow, tweezers",
                "motion": "cuts between the tools",
                "lighting": "bright studio light",
                "background": "minimal studio",
                "objects": ["pry bar", "wheelbarrow", "tweezers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a wheelbarrow in a minimal studio, bright even lighting, product photography",
            },
            {
                "goal": "The trade",
                "teaching_point": "Force multiplication costs travel",
                "shot": "graphic-style shot of effort traveling far while load moves little",
                "motion": "distance comparison animation",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["lever", "travel arrows"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a lever with travel distance arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Every tool is a lever aiming conserved energy",
                "shot": "wide hero shot of bolt cutters cutting a rod",
                "motion": "slow-motion cut",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["bolt cutters", "steel rod"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of bolt cutters cutting a steel rod in slow motion, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Giant crowbar on a fulcrum lifting a crate with a force-arrow overlay",
            "subject": "steel crowbar on a wooden fulcrum lifting a crate",
            "background": "dark workshop blur",
            "angle": "low-angle medium",
            "lighting": "hard key with rim",
            "composition": "crowbar diagonal across the frame, arrows in the space",
            "text": "LEVER POWER",
            "elements": ["crowbar", "fulcrum", "crate", "force arrows"],
            "style": "practical engineering photography",
            "mood": "powerful, simple, physical",
            "prompt": "photograph of a steel crowbar on a wooden fulcrum lifting a crate, hard key light with rim, dark workshop, 9:16 vertical composition, force arrows overlaid, realistic photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, logos",
        },
        "seo": {
            "title": "Levers: How One Person Lifts a Ton",
            "title_variations": [
                "Mechanical Advantage Explained",
                "The Three Lever Classes in 30 Seconds",
                "Why a Crowbar Multiplies Force",
                "Levers Don't Make Energy (They Aim It)",
                "Every Tool Is a Lever",
            ],
            "description": "How does a lever multiply force? It pivots on a fulcrum and trades distance for force: effort times effort arm equals load times load arm, so pushing a long arm a long way makes the short arm hit harder. Crowbars, seesaws, wheelbarrows, tweezers, and even your forearm are all levers in three classes, each trading motion for might. This 30-second physics short explains mechanical advantage, the three lever classes, and why levers never create energy - the force always costs extra travel.",
            "hashtags": ["#Engineering", "#Physics", "#Levers", "#MechanicalAdvantage"],
            "seo_keywords": [
                "lever mechanical advantage",
                "how levers work",
                "lever classes explained",
                "fulcrum force multiplication",
                "crowbar physics",
                "moment balance lever",
                "simple machines",
            ],
        },
        "fact_check": [
            "Lever balance: effort x effort arm = load x load arm (moments about the fulcrum).",
            "Mechanical advantage = effort arm / load arm; class 2 levers always give advantage greater than 1, class 3 less than 1.",
            "Work is conserved minus friction: force multiplication requires proportionally more distance.",
            "Class 1: fulcrum between effort and load (seesaw, crowbar); class 2: load between (wheelbarrow); class 3: effort between (tweezers, broom).",
            "Units: force in N, arm length in m or mm; moments in N-m.",
        ],
    },
    # ======================================================================
    {
        "topic": "Thermal Expansion",
        "core_question": "Why do metals grow when heated?",
        "learning_objective": "The viewer can predict thermal expansion behavior and design for it (expansion gaps, heat fits, bimetal effects).",
        "engineering_summary": "Heating a material increases atomic vibration amplitude, pushing atoms apart and expanding the solid. Linear expansion is proportional to the coefficient of thermal expansion (CTE) and temperature change: delta-L = alpha x L x delta-T. Steel expands about 12 ppm/C, aluminum 23 ppm/C, and brass about 19 ppm/C. Engineers use expansion deliberately (shrink fits, bimetal strips) and must manage it (bridge expansion joints, print dimensional shifts, nozzle/hotend assemblies).",
        "real_world_application": "Bridges use expansion joints; heat-set inserts expand and lock into printed plastic as they cool; train tracks have expansion gaps; bimetal strips drive thermostats.",
        "common_misconceptions": [
            "Everything expands at the same rate (CTE differs 2x between steel and aluminum)",
            "Thermal expansion only matters at huge temperatures (a 1 m steel bar grows 0.12 mm per 10 C)",
            "Expansion always causes problems (shrink fits and thermostats rely on it)",
        ],
        "teaching_strategy": "Show a brass ball expanding through a ring demo (ball fits cold, sticks hot), then apply the numbers to a 3D printer's hotend.",
        "script": "Heat a metal and it grows. That's thermal expansion: hot atoms vibrate harder and push apart. Steel grows about twelve parts per million per degree; aluminum almost twice that. Sounds tiny - until it isn't. A meter of steel grows over a tenth of a millimeter for every ten degrees. That's why bridges have expansion joints, train tracks leave gaps, and heat-set inserts lock into plastic as they cool and grip. Expansion is a fact of life. Design for it - or measure the consequences.",
        "text_overlay": [
            "HEAT = BIGGER ATOMS",
            "STEEL: 12 ppm/°C",
            "ALUMINUM: 23 ppm/°C",
            "1 m STEEL +10°C = +0.12 mm",
            "DESIGN THE GAP IN",
        ],
        "scenes": [
            {
                "goal": "Hook: the ball and ring",
                "teaching_point": "Hot ball expands and sticks in the ring",
                "shot": "medium shot of a brass ball and ring demo",
                "motion": "ball slides through cold, sticks hot",
                "lighting": "warm lab light",
                "background": "physics lab",
                "objects": ["brass ball", "brass ring", "heat source"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a brass ball and ring thermal expansion demonstration in a physics lab, warm lab lighting",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Hot atoms vibrate harder and push apart",
                "shot": "graphic-style shot of atoms vibrating more with heat",
                "motion": "vibration amplitude grows with temperature",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["atom lattice", "vibration animation"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an atomic lattice with vibration amplitude growing on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The numbers",
                "teaching_point": "CTE differs: steel 12, aluminum 23 ppm/C",
                "shot": "graphic-style shot of two metal bars with growth callouts",
                "motion": "bars grow at different rates",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["steel bar", "aluminum bar", "growth readouts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of steel and aluminum bars with thermal growth readouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Real-world design",
                "teaching_point": "Expansion joints and gaps are deliberate engineering",
                "shot": "wide shot of a bridge expansion joint close-up",
                "motion": "slow pan across the joint",
                "lighting": "bright daylight",
                "background": "bridge structure",
                "objects": ["bridge expansion joint", "steel structure"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a steel bridge expansion joint in bright daylight, engineering photography, clear detail",
            },
            {
                "goal": "Takeaway: heat-set inserts",
                "teaching_point": "Expansion is a tool: inserts lock in as they cool",
                "shot": "macro shot of a heat-set insert being pressed into a printed part",
                "motion": "slow insertion and lock",
                "lighting": "bright task light",
                "background": "workbench blur",
                "objects": ["heat-set insert", "printed part", "soldering iron tip"],
                "transition": "fade",
                "duration": 6,
                "prompt": "macro photograph of a brass heat-set insert being pressed into a 3D printed part, bright task lighting, workbench background",
            },
        ],
        "thumbnail": {
            "concept": "Brass ball stuck in a ring with a heat-glow gradient, half cold half hot",
            "subject": "brass ball and ring demo, hot side glowing subtly",
            "background": "dark physics lab blur",
            "angle": "macro eye-level",
            "lighting": "hard key with warm side light",
            "composition": "ball and ring centered, temperature gradient visible",
            "text": "HEAT = GROWTH",
            "elements": ["brass ball", "brass ring", "heat gradient"],
            "style": "physics demonstration photography",
            "mood": "simple, physical, warm",
            "prompt": "macro photograph of a brass ball stuck in a brass ring with a subtle heat glow on one side, hard key light with warm rim, dark physics lab, 9:16 vertical composition, ultra sharp metal detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Thermal Expansion: Why Metal Grows",
            "title_variations": [
                "Steel Grows When Heated: The Numbers",
                "Why Bridges Need Expansion Joints",
                "How Heat-Set Inserts Really Work",
                "Thermal Expansion in 30 Seconds",
                "Designing for Heat: The Gap Rule",
            ],
            "description": "Heat metal and it grows: atoms vibrate harder and push apart, and the growth follows a simple formula - change in length equals the material's expansion coefficient times original length times temperature rise. Steel expands about 12 parts per million per degree Celsius, aluminum about 23. That is why bridges carry expansion joints, train tracks leave gaps, and heat-set inserts expand and lock into plastic as they cool. This short covers the mechanism, the numbers, and how engineers design expansion in - or measure the consequences.",
            "hashtags": ["#Engineering", "#Physics", "#ThermalExpansion", "#Materials"],
            "seo_keywords": [
                "thermal expansion explained",
                "coefficient of thermal expansion",
                "steel expansion per degree",
                "bridge expansion joint",
                "heat set inserts how they work",
                "aluminum thermal expansion",
                "design for heat expansion",
            ],
        },
        "fact_check": [
            "Linear expansion: delta-L = alpha x L x delta-T; steel alpha ~12 ppm/C, aluminum ~23 ppm/C, brass ~19 ppm/C.",
            "A 1 m steel bar grows ~0.12 mm for a 10 C rise (about 0.012 mm per meter per degree).",
            "Anisotropy exists in some materials (wood, composites); metals are nearly isotropic in the bulk.",
            "Shrink fits exploit expansion: the outer part is heated, assembled, and grips as it cools to room temperature.",
            "Bimetal strips rely on differing CTEs to bend with temperature, driving thermostats and circuit breakers.",
            "Units: CTE in 10^-6 /C (ppm/C); length change in mm.",
        ],
    },
]