"""Batch 5: materials science, extrusion hardware, calibration, and design for strength."""

CURATED = [
    # ======================================================================
    {
        "topic": "Glass Transition Temperature",
        "core_question": "Why do printed parts soften in a hot car, and what is Tg?",
        "learning_objective": "The viewer can explain the glass transition, recall approximate Tg values for PLA, PETG, and ABS, and pick a material by service temperature.",
        "engineering_summary": "The glass transition temperature (Tg) is the point where an amorphous polymer changes from a hard, glassy solid to a soft, rubbery one. Below Tg, polymer chains are frozen in place and the part is rigid; above it, chain segments begin to move, stiffness drops sharply, and the part sags under load. Typical Tg values: PLA ~60 C, PETG ~80 C, ABS ~105 C, nylon ~50 C. Even below Tg, amorphous polymers creep under sustained stress (viscoelasticity), which is why stored parts under load slowly deform. Annealing raises crystallinity in semi-crystalline polymers like PLA and can push usable temperature higher, but the Tg itself stays close to the same value.",
        "real_world_application": "Dashboards, engine bays, and enclosures: a PLA bracket in a sealed car on a summer day exceeds its Tg and droops; the same part in ABS or PETG survives. Engineers read Tg on material datasheets before choosing a filament for a heated environment.",
        "common_misconceptions": [
            "Tg is the melting point (melting only applies to crystalline regions; Tg is where the amorphous part softens)",
            "Annealing changes Tg (it raises crystallinity and HDT but not Tg itself)",
            "Parts are safe right below Tg (creep still deforms them slowly under sustained load)",
        ],
        "teaching_strategy": "Open with the relatable hot-car failure, show the chain-level transition as an animation, then the real numbers for common filaments and the annealing caveat.",
        "script": "Take a printed part and leave it in a hot car. It sags, doesn't it? That's the glass transition, or T-g. Below it, the polymer is hard and glassy; above it, the molecular chains start to move, and the part goes soft and rubbery. PLA's T-g sits around sixty degrees Celsius; PETG about eighty; ABS around a hundred and five. Even below that temperature, slow creep happens under load. That's why hot environments demand the right material - and why annealing can push the usable range higher. Know the T-g, and your parts stop surprising you.",
        "text_overlay": [
            "HOT CAR = SAGGING PART",
            "BELOW Tg: GLASSY",
            "ABOVE Tg: RUBBERY",
            "PLA 60C | PETG 80C | ABS 105C",
        ],
        "scenes": [
            {
                "goal": "Hook: the hot car",
                "teaching_point": "Heat deforms printed parts",
                "shot": "macro shot of a sagging PLA part on a sun-heated dashboard",
                "motion": "slow push-in on the drooping edge",
                "lighting": "harsh sunlight through glass",
                "background": "car dashboard",
                "objects": ["sagging PLA part", "sunlit dashboard"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a melted sagging 3D printed part on a sun-heated car dashboard, harsh sunlight, realistic automotive interior",
            },
            {
                "goal": "The chain model",
                "teaching_point": "Tg is where polymer chains unlock",
                "shot": "graphic-style shot of polymer chains frozen, then wriggling",
                "motion": "chains animate from rigid to wavy",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["polymer chain diagram", "temperature scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a polymer chain molecular diagram frozen then wriggling on a dark screen, clean engineering visualization, temperature scale",
            },
            {
                "goal": "The numbers",
                "teaching_point": "Real Tg values for common filaments",
                "shot": "tablet-style graphic listing PLA, PETG, ABS with temperatures",
                "motion": "values pop in one by one",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["temperature table", "filament spools"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a temperature comparison table for PLA, PETG, and ABS filaments on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Creep below Tg",
                "teaching_point": "Sustained load deforms parts even when cool",
                "shot": "time-lapse style shot of a weighted printed bracket bowing slowly",
                "motion": "slow bend over time",
                "lighting": "neutral lab light",
                "background": "engineering bench",
                "objects": ["weighted bracket", "weights", "printed clamp"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a weighted 3D printed bracket slowly bowing under load, neutral lab lighting, engineering workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match material Tg to the environment",
                "shot": "wide hero shot of three parts in PLA, PETG, and ABS with temperature labels",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PLA part", "PETG part", "ABS part"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of three 3D printed parts in PLA, PETG, and ABS with temperature labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A sagging printed part overlaid with a Tg temperature scale",
            "subject": "drooping PLA part with a thermometer scale",
            "background": "sunlit car interior blur",
            "angle": "low eye-level",
            "lighting": "harsh sun with rim",
            "composition": "sagging part left, temperature scale right",
            "text": "Tg: 60C",
            "elements": ["sagging print", "temperature scale", "thermometer"],
            "style": "thermal macro photography",
            "mood": "hot, material-science, clear",
            "prompt": "macro photograph of a sagging 3D printed part with a glowing temperature scale overlay, harsh sunlight through glass, car interior blur, 9:16 vertical composition, ultra sharp surface detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Why Prints Soften in Hot Cars",
            "title_variations": [
                "Glass Transition Temperature Explained",
                "PLA vs PETG vs ABS: Heat Limits",
                "Why Your Part Sagged in the Sun",
                "Tg and Creep in Printed Parts",
                "Picking a Filament for Heat",
            ],
            "description": "The glass transition temperature, or Tg, is the point where a polymer changes from a hard, glassy solid to a soft, rubbery one. Below Tg, PLA parts are rigid; above it, molecular chains begin to move and the part sags under its own weight. That is why a print left in a hot car deforms while the same print on a desk stays perfect. PLA sits around 60 C, PETG around 80 C, and ABS around 105 C. Even below Tg, creep happens slowly under sustained load. This short explains the Tg concept, real material numbers, and why annealing can shift the practical limit.",
            "hashtags": ["#Materials", "#3Dprinting", "#Engineering", "#PLA"],
            "seo_keywords": [
                "glass transition temperature",
                "why do prints soften in heat",
                "PLA heat resistance",
                "PETG Tg",
                "ABS temperature limit",
                "annealing PLA",
                "polymer creep",
            ],
        },
        "fact_check": [
            "Tg for amorphous polymers like PLA is about 55-65 C; PETG ~78-85 C; ABS ~100-108 C.",
            "Tg is not a melting point: crystalline regions melt at a higher, distinct temperature.",
            "Annealing semi-crystalline PLA raises crystallinity and heat deflection temperature, not Tg itself.",
            "Amorphous polymers creep below Tg under sustained stress, so service loads must consider time as well as temperature.",
            "HDT (heat deflection temperature) is measured under load and is typically lower than Tg.",
        ],
    },
    # ======================================================================
    {
        "topic": "Filament Drying",
        "core_question": "Why do my prints pop and string, and does drying filament actually fix it?",
        "learning_objective": "The viewer can recognize wet-filament symptoms, identify hygroscopic materials, and run a correct drying routine per material.",
        "engineering_summary": "Many thermoplastics are hygroscopic: they absorb water vapor from the air, and water molecules wedge between polymer chains, weakening the material and lowering its mechanical performance. In the hotend, absorbed water flashes to steam at 100+ C, blasting bubbles through the extruded plastic - visible as popping, rough surfaces, and foamy stringing. Nylon, PETG, TPU, and PVA absorb the most; PLA absorbs the least. Drying temperatures: PLA ~50 C, PETG ~65 C, nylon ~70-80 C, for 4-12 hours depending on material and saturation, in a filament dryer or a sealed container with desiccant after drying. Even new sealed spools can arrive wet.",
        "real_world_application": "Print farms dry every spool on intake and store filament in dry boxes, because wet spools cost time and waste plastic; functional parts in nylon or TPU simply fail if printed wet.",
        "common_misconceptions": [
            "Wet filament looks wet (moisture is invisible; symptoms appear only at the nozzle)",
            "Sealed new spools are always dry (they often ship with absorbed moisture)",
            "Higher hotend temperature burns the water off (the damage and bubbles happen as steam blasts through the melt)",
        ],
        "teaching_strategy": "Open with audible popping, explain water flashing to steam in the hotend, show the drying setup, and end with a per-material temperature table.",
        "script": "Pop, hiss, and a rough surface - your filament is wet. Nylon, TPU, PETG, and even PLA absorb moisture from the air. Water molecules work their way between the polymer chains and weaken the whole print. In the hotend, that water flashes to steam, leaving bubbles, blobs, and stringing. The fix is drying, not heat soaking. Sixty degrees for PLA, seventy for PETG, and eight hours or more for nylon in a filament dryer or a sealed box with desiccant. Dry filament prints stronger, smoother, and quieter. Start with a dry spool, and most print problems disappear.",
        "text_overlay": [
            "POP + HISS = WATER",
            "STEAM BLASTS THROUGH",
            "PLA 50C | PETG 65C | NYLON 75C",
            "4-12 HOURS, SEALED BOX",
        ],
        "scenes": [
            {
                "goal": "Hook: the popping print",
                "teaching_point": "Audible pops signal steam in the melt",
                "shot": "macro shot of filament feeding with bubbles erupting at the nozzle",
                "motion": "slow-motion bubble burst",
                "lighting": "raking side light",
                "background": "dark print bay",
                "objects": ["nozzle", "bubbling melt", "filament"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of 3D printer nozzle with bubbles erupting from molten filament, slow motion feel, raking side light, dark print bay",
            },
            {
                "goal": "The science",
                "teaching_point": "Water molecules wedge between polymer chains",
                "shot": "graphic-style shot of a polymer chain with water molecules between links",
                "motion": "water molecules push chains apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["polymer chain diagram", "water molecules"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a polymer chain molecular diagram with water molecules between links on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The drying setup",
                "teaching_point": "Correct temperature, sealed storage",
                "shot": "medium shot of a filament dryer running, then a dry box with desiccant",
                "motion": "pan between dryer and dry box",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["filament dryer", "dry box", "desiccant packs", "spools"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a filament dryer running beside a sealed dry box with desiccant packs, neutral lab lighting, modern print lab",
            },
            {
                "goal": "The schedule",
                "teaching_point": "Per-material drying temperatures and times",
                "shot": "tablet-style graphic listing drying schedules",
                "motion": "rows highlight one by one",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["drying table", "spools", "hygrometer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a filament drying schedule table on a dark studio screen, even diffused lighting, spools and hygrometer nearby",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Dry spools solve whole classes of problems",
                "shot": "wide hero shot of a clean, glossy print fresh off the printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "dry box"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a clean glossy 3D print on the build plate beside a dry box, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spool with water droplets and steam arrows feeding a nozzle",
            "subject": "filament spool with steam symbols",
            "background": "dark workshop blur",
            "angle": "medium eye-level",
            "lighting": "hard key with rim",
            "composition": "spool left, nozzle right, steam in between",
            "text": "DRY YOUR FILAMENT",
            "elements": ["filament spool", "steam arrows", "nozzle"],
            "style": "diagnostic studio photography",
            "mood": "moist, scientific, corrective",
            "prompt": "studio photograph of a filament spool with visible steam arrows feeding a nozzle, hard key light with rim, dark workshop blur, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Wet Filament? Do This",
            "title_variations": [
                "Why Filament Pops and Strings",
                "The Filament Drying Guide",
                "Nylon and PETG Need Drying",
                "Signs Your Spool Is Wet",
                "Drying Temperatures Explained",
            ],
            "description": "Pop, hiss, and rough surfaces are the classic signs of wet filament. Nylon, TPU, PETG, and even PLA absorb moisture from the air, and water molecules slip between polymer chains, weakening every layer and flashing to steam inside the hotend. Drying is the fix: about 50 C for PLA, 65 C for PETG, and 70-80 C for hours for nylon, using a filament dryer or a sealed box with desiccant. Dry spools print stronger, smoother parts with less stringing and better layer adhesion. This short covers the symptoms, the science of hygroscopic materials, and a practical drying routine.",
            "hashtags": ["#Filament", "#3Dprinting", "#PrintQuality", "#Nylon"],
            "seo_keywords": [
                "how to dry filament",
                "wet filament symptoms",
                "filament dryer",
                "nylon moisture",
                "PETG drying temperature",
                "hygroscopic filament",
                "PLA moisture",
            ],
        },
        "fact_check": [
            "Nylon, PETG, TPU, PVA, and ASA are hygroscopic; PLA absorbs far less but still benefits from drying.",
            "Absorbed water flashes to steam above 100 C in the hotend, causing popping, bubbles, and foamy extrusion.",
            "Recommended drying: PLA ~45-55 C, PETG ~60-70 C, nylon ~70-80 C, typically 4-12 hours.",
            "Dry storage at <20% relative humidity in a sealed box with desiccant extends the dried state.",
            "New spools are not guaranteed dry; manufacturers dry before packaging but moisture returns in transit.",
        ],
    },
    # ======================================================================
    {
        "topic": "Bowden vs Direct Drive",
        "core_question": "Bowden or direct drive - which extruder setup should I use?",
        "learning_objective": "The viewer can explain the mechanical difference, name the trade-offs in mass and retraction, and choose a setup for their print priorities.",
        "engineering_summary": "In a Bowden system the extruder motor mounts on the printer frame and pushes filament through a long PTFE or Capricorn tube to the hotend. This keeps the toolhead light, allowing higher acceleration and speed, but the filament column flexes and stretches, so retraction must be longer and stringing is easier to trigger. Direct drive mounts the extruder on the toolhead, a few centimeters from the nozzle: retraction can be short and snappy, flexible filaments feed reliably, and stringing is reduced, at the cost of extra toolhead mass that lowers acceleration limits. High-speed printers favor Bowden or lightweight direct-drive variants; quality-oriented machines favor direct drive.",
        "real_world_application": "TPU and soft flexible parts are nearly unusable on long Bowden tubes but reliable on direct drive; Voron-style speed builds pair light toolheads with careful tuning, while engineering part printers go direct for detail.",
        "common_misconceptions": [
            "Direct drive is always better (Bowden wins on speed and low toolhead mass)",
            "Bowden can't print flexibles (short tubes and slow speeds work, but it is harder)",
            "The motor position doesn't matter for retraction (tube length directly scales retraction distance)",
        ],
        "teaching_strategy": "Show the two layouts side by side, then a retraction comparison and a flexible-filament test to make the trade-offs concrete.",
        "script": "In a Bowden setup, the motor sits on the frame and pushes filament through a long tube to the hotend. Direct drive puts the motor right on the print head, inches from the nozzle. Bowden means a lighter toolhead and faster acceleration, but more flex and stretch in the filament, so stringing is easier and retraction must be longer. Direct drive gives sharper retraction, crisper details, and easy flexible filament like TPU, at the cost of extra mass. Speed machines run Bowden, quality machines bolt the motor on. Pick by what you print most.",
        "text_overlay": [
            "BOWDEN: MOTOR ON FRAME",
            "DIRECT: MOTOR ON HEAD",
            "MASS vs RETRACTION",
            "TPU NEEDS DIRECT",
        ],
        "scenes": [
            {
                "goal": "Hook: two machines",
                "teaching_point": "Two ways to feed a hotend",
                "shot": "side-by-side shots of a Bowden printer and a direct-drive printer",
                "motion": "cross-cut between the two",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["Bowden printer", "direct drive printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two 3D printers side by side, one with a frame-mounted extruder and one with a toolhead extruder, neutral lab lighting",
            },
            {
                "goal": "The layouts",
                "teaching_point": "Motor position defines the system",
                "shot": "graphic-style shot of both extruder layouts with filament paths drawn",
                "motion": "filament path animates through tube and direct",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extruder diagram", "tube path", "toolhead"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Bowden versus direct drive extruder diagram with animated filament paths on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Retraction difference",
                "teaching_point": "Tube length scales retraction distance",
                "shot": "macro shot of filament retracting on each system",
                "motion": "long pull versus short snap",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["extruder", "filament", "PTFE tube"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of filament retracting through a Bowden tube versus a direct drive extruder, bright task lighting, print lab",
            },
            {
                "goal": "The flexible test",
                "teaching_point": "TPU feeds reliably on direct drive",
                "shot": "medium shot of TPU printing smoothly on a direct-drive toolhead",
                "motion": "slow feed of flexible filament",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["direct drive toolhead", "TPU filament", "flexible part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of flexible TPU filament feeding smoothly through a direct drive extruder, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the setup to your priorities",
                "shot": "wide hero shot of the two printers with speed and quality labels",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["Bowden printer", "direct drive printer", "labels"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a Bowden and a direct drive printer with speed and quality labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Split-frame comparison of both extruder layouts",
            "subject": "toolhead with and without a mounted motor",
            "background": "dark machine shop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "Bowden left, direct drive right, arrow between",
            "text": "BOWDEN vs DIRECT",
            "elements": ["toolhead", "extruder motor", "filament tube", "comparison arrow"],
            "style": "industrial comparison photography",
            "mood": "contrasting, mechanical, decisive",
            "prompt": "photograph of a Bowden toolhead on the left and a direct drive toolhead on the right with a comparison arrow, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bowden or Direct Drive?",
            "title_variations": [
                "Extruder Types Explained",
                "Which Extruder Is Better",
                "Bowden vs Direct: The Trade-offs",
                "Why TPU Prefers Direct Drive",
                "Retraction by Extruder Type",
            ],
            "description": "Bowden and direct drive are the two ways to feed filament into a hotend. In a Bowden setup the extruder motor sits on the frame and pushes filament through a long tube, keeping the toolhead light for fast acceleration and high print speeds. Direct drive mounts the motor right above the nozzle, giving shorter retraction, sharper detail, and the ability to print flexible materials like TPU, at the cost of extra toolhead mass. Neither is better; each suits a different job. This short compares the trade-offs, shows why stringing differs between the two, and gives a simple rule for choosing the right setup for your printer.",
            "hashtags": ["#Extruder", "#3Dprinting", "#Hardware", "#TPU"],
            "seo_keywords": [
                "bowden vs direct drive",
                "direct drive extruder",
                "bowden extruder",
                "printing TPU direct drive",
                "extruder type comparison",
                "retraction distance",
                "toolhead mass",
            ],
        },
        "fact_check": [
            "Bowden systems use a frame-mounted motor with a PTFE or Capricorn tube delivering filament to the hotend.",
            "Long Bowden tubes increase required retraction distance and make flexible filaments harder to feed.",
            "Direct drive reduces filament path length, improving retraction response and flexible material handling.",
            "Toolhead mass directly limits achievable acceleration; lightweight toolheads are a key speed-machine goal.",
            "Modern high-speed printers often use lightweight direct drive with short hotends to combine both advantages.",
        ],
    },
    # ======================================================================
    {
        "topic": "Nozzle Materials",
        "core_question": "When do I need a hardened nozzle, and what are the options?",
        "learning_objective": "The viewer can identify abrasive filaments, explain nozzle wear, and pick brass, hardened steel, or premium nozzles for their materials.",
        "engineering_summary": "Standard nozzles are brass, which conducts heat well but is soft: abrasive filaments - carbon fiber composites, glow-in-the-dark, glass-filled, and metal-filled plastics - contain hard particles that erode the bore, widening the nozzle over time. A worn nozzle changes line width and flow, causing over-extrusion, rough surfaces, and blobs. Hardened steel nozzles resist abrasion and print any material, but conduct heat about 15x worse than brass, so hotend temperature may need to rise a few degrees to compensate. Tungsten carbide and ruby-tipped nozzles offer premium wear life and thermal performance for high-throughput or abrasive-heavy printing.",
        "real_world_application": "Long-run print farms running carbon-fiber nylon track nozzle bores with test prints; a wear-compensated or hardened nozzle avoids mid-batch quality drift.",
        "common_misconceptions": [
            "Hardened steel prints exactly like brass (lower thermal conductivity changes melting dynamics)",
            "Wear only matters for exotic materials (even glow filament erodes brass noticeably)",
            "A worn nozzle just prints wider (wear is uneven, degrading extrusion consistency)",
        ],
        "teaching_strategy": "Open with a worn-nozzle close-up, explain the erosion mechanism, then a material table and a decision rule.",
        "script": "Your stock brass nozzle is soft, and abrasive filaments eat it fast. Glow-in-the-dark, carbon fiber, and glass-filled plastics contain hard particles that sand the hole wider. The result: over-extrusion, rough walls, and wasted plastic. Hardened steel nozzles resist that wear and handle any material, but they conduct heat worse, so you may need a few extra degrees. Tungsten and ruby are premium options for serious users. For everyday PLA and PETG, brass is fine. The rule: no abrasives in the filament, brass is great; abrasives in the spool, go hardened.",
        "text_overlay": [
            "BRASS IS SOFT",
            "ABRASIVES ERODE THE BORE",
            "HARDENED STEEL FIXES IT",
            "ABRASIVES? GO HARDENED",
        ],
        "scenes": [
            {
                "goal": "Hook: the worn nozzle",
                "teaching_point": "Abrasive filaments erode brass",
                "shot": "macro close-up of a worn, widened brass nozzle beside a new one",
                "motion": "slow push-in on the eroded bore",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["worn nozzle", "new brass nozzle"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a worn brass 3D printer nozzle beside a new one, eroded bore visible, raking side light, dark bench",
            },
            {
                "goal": "The erosion mechanism",
                "teaching_point": "Hard particles sand the hole wider",
                "shot": "graphic-style shot of hard particles scraping the bore wall",
                "motion": "particles grind the inner surface",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle cross-section", "abrasive particles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle cross-section with abrasive particles eroding the bore wall on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The symptom chain",
                "teaching_point": "Wider bore, wrong flow, rough parts",
                "shot": "medium shot of a rough, blobby print under inspection",
                "motion": "slow pan across the surface",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["rough print", "inspection light", "magnifier"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a rough blobby 3D print under an inspection light with a magnifier, bright task lighting, workbench",
            },
            {
                "goal": "The options",
                "teaching_point": "Brass, hardened steel, tungsten, ruby",
                "shot": "tabletop shot of the four nozzle types in a row",
                "motion": "camera slides down the row",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["brass nozzle", "hardened steel nozzle", "tungsten nozzle", "ruby nozzle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of brass, hardened steel, tungsten, and ruby nozzles lined up on a dark studio table, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match nozzle to filament",
                "shot": "wide hero shot of a nozzle threaded into a hotend with a spool behind",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["hotend", "nozzle", "abrasive spool"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a nozzle threaded into a hotend with a filament spool behind, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Abrasive particles visibly chewing a brass nozzle bore",
            "subject": "worn and new nozzle comparison",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "worn nozzle left, new nozzle right, particles between",
            "text": "WEAR CHECK",
            "elements": ["worn nozzle", "new nozzle", "abrasive particles"],
            "style": "industrial macro photography",
            "mood": "worn, precise, urgent",
            "prompt": "macro photograph of a worn brass nozzle beside a new one with abrasive particles between them, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Which Nozzle Material?",
            "title_variations": [
                "Hardened vs Brass Nozzles",
                "Nozzle Wear Explained",
                "Carbon Fiber Filament Eats Brass",
                "Nozzle Materials Compared",
                "When to Upgrade Your Nozzle",
            ],
            "description": "Brass nozzles are soft and cheap, which is perfect for PLA and PETG but a problem when abrasive filaments are involved. Carbon fiber, glow-in-the-dark, and glass-filled plastics contain hard particles that slowly sand the nozzle opening wider, causing over-extrusion and rough walls. Hardened steel nozzles resist that wear and print almost any material, though their lower thermal conductivity means a slightly higher hotend temperature. Tungsten carbide and ruby nozzles are premium long-life options for high-throughput users. This short explains nozzle wear, when to upgrade, and a simple rule: no abrasives, brass is fine; abrasives, go hardened.",
            "hashtags": ["#Nozzle", "#3Dprinting", "#Hardware", "#CarbonFiber"],
            "seo_keywords": [
                "hardened steel nozzle",
                "brass nozzle wear",
                "nozzle material comparison",
                "carbon fiber filament nozzle",
                "glow in the dark nozzle wear",
                "when to replace nozzle",
                "tungsten carbide nozzle",
            ],
        },
        "fact_check": [
            "Brass conducts heat far better than hardened steel but erodes quickly with abrasive filaments.",
            "Abrasive additives include carbon fiber, glass fiber, glow pigments, and metal powders.",
            "Worn nozzles widen and become non-circular, changing line width and causing uneven extrusion.",
            "Hardened steel nozzles typically require a slightly higher hotend temperature due to lower thermal conductivity.",
            "Tungsten carbide and ruby nozzles offer the longest wear life for continuous abrasive printing.",
        ],
    },
    # ======================================================================
    {
        "topic": "E-Step Calibration",
        "core_question": "How do I calibrate extruder steps per millimeter?",
        "learning_objective": "The viewer can run a ruler-based e-step calibration, compute the corrected value, and apply it in firmware.",
        "engineering_summary": "E-steps per millimeter (E-Steps/mm) is the firmware value that converts a requested filament length into the exact motor steps needed to push that length through the extruder. Because gear ratios and gear diameters vary between extruders, the stock value is an estimate. If it is too low, the printer under-extrudes every print - gaps, weak layers, and dimensional loss; too high, and it over-extrudes with blobs and elephant foot. Calibration: heat the hotend to the material's print temperature, mark filament 120 mm above the extruder intake, extrude 100 mm, measure the remaining distance, then new steps = old steps x (100 / actual extruded). Repeat once and save the value per machine.",
        "real_world_application": "Print farms calibrate e-steps on every new machine and after every extruder rebuild; one saved number fixes a whole class of consistent print defects.",
        "common_misconceptions": [
            "E-steps fix all extrusion problems (it only fixes systematic error; clogs and flow issues need their own tests)",
            "Calibrating once is enough forever (changing gears, motors, or extruders changes the value)",
            "The stock value is always right (factory values are generic across extruder variants)",
        ],
        "teaching_strategy": "Show the measurement with a ruler step by step, the math as an on-screen formula, then the firmware save procedure.",
        "script": "Under-extrusion? Gaps in your top layer? Before blaming the filament, check the extruder's math. E-steps tell the printer how many steps spin the motor to push one millimeter of filament. If the number is wrong, every single print is off by the same amount. Calibration is simple: mark the filament one hundred twenty millimeters above the extruder, extrude one hundred, measure what's left, then scale your steps by the ratio. The printer can now count filament exactly. Do this once per machine, after any extruder change, and watch layer quality improve everywhere.",
        "text_overlay": [
            "1. MARK 120MM",
            "2. EXTRUDE 100MM",
            "3. MEASURE + SCALE",
            "STEPS x (100 / ACTUAL)",
        ],
        "scenes": [
            {
                "goal": "Hook: the mystery gaps",
                "teaching_point": "Consistent gaps trace to the extruder math",
                "shot": "macro shot of a top layer with gaps between lines",
                "motion": "slow push-in on the gaps",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["printed part", "gapped top layer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed top layer with gaps between extrusion lines, raking side light, dark bench",
            },
            {
                "goal": "What e-steps mean",
                "teaching_point": "Steps per millimeter is the extruder's ruler",
                "shot": "graphic-style shot of motor steps and filament length",
                "motion": "steps and millimeters pair up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stepper motor", "filament length diagram"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stepper motor with a filament length diagram on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The measurement",
                "teaching_point": "Mark, extrude, measure",
                "shot": "close-up of a ruler marking filament above the extruder",
                "motion": "mark, extrude, then measure the remainder",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["ruler", "filament", "extruder", "marker"],
                "transition": "cut",
                "duration": 7,
                "prompt": "photograph of measuring filament with a ruler above a 3D printer extruder, bright task lighting, print lab",
            },
            {
                "goal": "The math",
                "teaching_point": "Scale by the measured ratio",
                "shot": "tablet-style graphic showing the formula with live numbers",
                "motion": "numbers swap in and the result pops",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["formula tablet", "calculator", "extruder"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of the e-step calibration formula displayed on a tablet with a calculator nearby, even diffused lighting, dark studio",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One saved number fixes the whole class",
                "shot": "wide hero shot of a perfect first layer with clean top lines",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["perfect print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flawless 3D print with clean top layers on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Ruler and filament marking the exact calibration procedure",
            "subject": "marked filament with a ruler at the extruder",
            "background": "dark print lab blur",
            "angle": "macro eye-level",
            "lighting": "bright key light",
            "composition": "ruler left, marked filament right",
            "text": "CALIBRATE E-STEPS",
            "elements": ["ruler", "marked filament", "extruder", "marker"],
            "style": "diagnostic macro photography",
            "mood": "precise, procedural, clean",
            "prompt": "macro photograph of filament marked with a marker being measured with a ruler above the extruder, bright key light, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "E-Steps: 10-Minute Fix",
            "title_variations": [
                "How to Calibrate E-Steps",
                "Fix Under-Extrusion at the Source",
                "Extruder Steps Per Millimeter",
                "The Ruler Trick for Extrusion",
                "E-Step Calibration Made Simple",
            ],
            "description": "E-step calibration fixes under-extrusion at the source by telling the printer exactly how many motor steps push one millimeter of filament. When this value is wrong, every print is systematically off - thin walls, gaps in the top layer, and weak parts that no other setting can fix. The calibration is a ruler and ten minutes: mark the filament above the extruder, extrude a known length, measure the difference, and scale the steps per millimeter by the ratio. Do it once per machine and after any extruder hardware change. This short walks through the measurement, the math, and how to apply the corrected value in firmware.",
            "hashtags": ["#Calibration", "#3Dprinting", "#Extrusion", "#Tips"],
            "seo_keywords": [
                "calibrate e steps",
                "extruder steps per mm",
                "under-extrusion fix",
                "e step calibration 3d printer",
                "esteps formula",
                "extruder calibration",
                "first layer gaps",
            ],
        },
        "fact_check": [
            "E-Steps/mm converts requested filament length into stepper motor steps via the extruder gear ratio.",
            "The ruler method: extrude 100 mm, measure actual, new = old x (100 / actual).",
            "E-step errors are systematic, affecting every print equally regardless of other settings.",
            "Changing the extruder motor, gears, or gear ratio requires recalibration.",
            "E-step calibration does not replace flow calibration, which tunes extrusion width during printing.",
        ],
    },
    # ======================================================================
    {
        "topic": "Temperature Towers",
        "core_question": "How do I read a temperature tower and find the best print temperature?",
        "learning_objective": "The viewer can print and read a temperature tower, identify hot and cold failure modes, and save a tuned material profile.",
        "engineering_summary": "A temperature tower is a calibration print that changes hotend temperature in steps every few millimeters of height, so a single print exposes how the material behaves across a temperature range. Too hot: glossy surfaces, stringing, sagging overhangs, and blobby detail because the melt is too fluid. Too cold: dull, matte surfaces, weak layer bonding, and gaps because the melt is too stiff. The ideal temperature is the lowest that still yields strong layer bonds, clean overhangs, and acceptable gloss. Towers typically span 5-10 C steps over 20-40 C, with temperature-change scripts inserted via filament change or M104 commands in the slicer's layer-change g-code.",
        "real_world_application": "Filament manufacturers and print farms run towers on every new spool: the tuned number becomes the saved profile, cutting stringing and failures across production runs.",
        "common_misconceptions": [
            "The box label is the right temperature (labels are ranges; every spool differs)",
            "Hotter is stronger (too hot degrades the polymer and causes sagging)",
            "The shiny section is the best section (shine can indicate over-melting, not quality)",
        ],
        "teaching_strategy": "Open with one tower and its eight sections, label the failure modes at both ends, and show how the winning range becomes a saved profile.",
        "script": "One print, eight temperatures, no wasted filament. A temperature tower steps the hotend down every few layers, so you can see exactly how each setting behaves. Too hot: shiny surface, strings, and overhangs that sag. Too cold: dull layers, weak bonding, and gaps. The sweet spot is the range that looks clean and breaks clean. Read the tower like a report: find the lowest temperature that still prints strong, then keep a few degrees of margin. That number becomes your material profile. Never trust a filament's box label - test the tower and let the print decide.",
        "text_overlay": [
            "ONE PRINT, EIGHT TEMPS",
            "HOT: SHINY + STRINGS",
            "COLD: DULL + GAPS",
            "SAVE THE SWEET SPOT",
        ],
        "scenes": [
            {
                "goal": "Hook: the tower",
                "teaching_point": "One print samples many temperatures",
                "shot": "wide shot of a temperature tower standing on the build plate",
                "motion": "slow tilt up the sections",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["temperature tower", "build plate", "printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a tall temperature tower print standing on a build plate, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Too hot",
                "teaching_point": "Fluid melt strings and sags",
                "shot": "macro close-up of the hot section with strings and sagging overhangs",
                "motion": "slow push-in on the defects",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["tower hot section", "strings", "sagging overhang"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a temperature tower hot section with stringing and sagging overhangs, raking side light, dark bench",
            },
            {
                "goal": "Too cold",
                "teaching_point": "Stiff melt under-bonds and gaps",
                "shot": "macro close-up of the cold section with dull matte layers and gaps",
                "motion": "slow pan across the weak layers",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["tower cold section", "dull layers", "layer gaps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a temperature tower cold section with dull matte layers and gaps between lines, bright task light, dark bench",
            },
            {
                "goal": "Reading the report",
                "teaching_point": "Pick the lowest clean, strong section",
                "shot": "tablet-style graphic highlighting the winning range on a tower photo",
                "motion": "best section glows and the number pops",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["tower photo", "highlight overlay", "temperature labels"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a temperature tower photo with the winning temperature range highlighted on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Turn the number into a saved profile",
                "shot": "wide hero shot of a saved slicer profile with the tuned temperature",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["slicer screen", "tuned profile", "clean print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a slicer profile screen showing a tuned temperature with a clean print beside it, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A temperature tower with hot and cold sections labeled",
            "subject": "standing temperature tower with temperature labels",
            "background": "dark print lab blur",
            "angle": "low eye-level tilt-up",
            "lighting": "hard key with rim",
            "composition": "tower center, labels down the side",
            "text": "FIND YOUR TEMP",
            "elements": ["temperature tower", "temperature labels", "build plate"],
            "style": "diagnostic studio photography",
            "mood": "scientific, ordered, decisive",
            "prompt": "photograph of a temperature tower with temperature labels down its side, hard key light with rim, dark print lab blur, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Temperature Towers Explained",
            "title_variations": [
                "How to Read a Temp Tower",
                "Find the Best Print Temperature",
                "The One-Print Temperature Test",
                "Why Box Labels Lie",
                "Tune Your Filament in One Print",
            ],
            "description": "A temperature tower is the fastest way to find a filament's best print temperature without wasting spools on guesswork. Each section of the tower prints at a lower temperature, so a single print shows stringing, surface finish, overhang quality, and layer bonding across the whole range. Too hot, you get shiny sagging sections with strings; too cold, you get dull, weak, under-bonded layers. The winning temperature is the lowest one that still prints clean and strong, with a few degrees of margin. This short explains how to read the tower like a report and turn it into a saved material profile.",
            "hashtags": ["#TemperatureTower", "#3Dprinting", "#Calibration", "#Filament"],
            "seo_keywords": [
                "temperature tower",
                "how to read a temp tower",
                "best print temperature",
                "temperature tower 3d print",
                "temp tower calibration",
                "filament temperature test",
                "tuning print temperature",
            ],
        },
        "fact_check": [
            "Towers change nozzle temperature in steps every few millimeters of height, typically 5-10 C per section.",
            "Too-hot sections show stringing, sagging overhangs, and glossy over-melted surfaces.",
            "Too-cold sections show matte surfaces, weak interlayer bonds, and extrusion gaps.",
            "The best temperature is the lowest with strong bonding and clean geometry; a few degrees of margin is kept for ambient variation.",
            "Tower temperature changes are automated in the slicer via layer-change g-code such as M104.",
        ],
    },
    # ======================================================================
    {
        "topic": "Threads: Cut vs Tapped vs Heat-Set",
        "core_question": "What is the strongest way to add threads to a 3D printed part?",
        "learning_objective": "The viewer can compare printed, tapped, and heat-set thread options and choose the right method by load, reuse, and geometry.",
        "engineering_summary": "Directly printed threads are the weakest option: the thread flanks are printed in steps, layer adhesion limits shear strength, and repeated tightening strips them. Cut threads use a tap on a printed undersized hole, producing clean flanks whose strength is still bounded by the plastic's layer bond, but suited to single-assembly parts. Heat-set inserts press or melt a brass insert with molded or knurled threads into a printed boss, giving metal threads, high pull-out and torque strength, and indefinite reusability. Design rules: boss outer diameter ~2x insert diameter, hole diameter per insert datasheet, and heat-set temperature around the material's softening point, typically 230-270 C for PLA and PETG.",
        "real_world_application": "Enclosures, camera mounts, and production jigs use heat-set inserts wherever screws go in more than once; tapped plastic is reserved for one-time assembly where inserts add cost.",
        "common_misconceptions": [
            "Printed threads are strong enough for load (flank steps and layer bond make them the weakest option)",
            "Tapping makes plastic as strong as metal (the plastic around the thread still limits strength)",
            "Any insert works in any material (boss size and hole diameter must match the insert datasheet)",
        ],
        "teaching_strategy": "Open with a stripped printed thread failure, then compare the three methods with a pull-out test visual and end with the boss design rule.",
        "script": "Printed threads look like threads, but they're fragile. Three better options. Cut threads: print an undersized hole and run a tap through it - clean, strong, and simple, as long as the hole is vertical. Tapped threads in a printed part share the print's weakness: layers can split under load. Heat-set inserts are the engineering answer: a brass insert melts into the plastic, giving you a metal thread with real clamping force. For parts you assemble once, tap it. For parts that come apart again and again, or carry load, heat-set inserts win every time.",
        "text_overlay": [
            "PRINTED = WEAK",
            "CUT: TAP THE HOLE",
            "HEAT-SET: METAL THREADS",
            "ONE-TIME: TAP | REUSE: INSERT",
        ],
        "scenes": [
            {
                "goal": "Hook: the stripped thread",
                "teaching_point": "Printed thread flanks fail under torque",
                "shot": "macro close-up of a stripped printed thread with plastic shavings",
                "motion": "slow push-in on the torn flanks",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["stripped printed thread", "bolt", "shavings"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a stripped 3D printed thread with torn flanks and plastic shavings, raking side light, dark bench",
            },
            {
                "goal": "Cut threads",
                "teaching_point": "Tap an undersized printed hole",
                "shot": "close-up of a hand tap cutting threads in a printed hole",
                "motion": "tap rotates slowly into the hole",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["hand tap", "printed block", "tap wrench"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hand tap cutting threads into a 3D printed block, bright task lighting, workbench",
            },
            {
                "goal": "Heat-set inserts",
                "teaching_point": "Brass inserts melt in for metal threads",
                "shot": "close-up of a soldering iron pushing a brass insert into a printed boss",
                "motion": "insert sinks into the boss with slight smoke",
                "lighting": "warm task light",
                "background": "workbench",
                "objects": ["soldering iron", "brass insert", "printed boss"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a soldering iron pressing a brass heat-set insert into a 3D printed boss, warm task lighting, workbench",
            },
            {
                "goal": "The pull test",
                "teaching_point": "Metal threads carry real load",
                "shot": "medium shot of a pull test on the three thread types",
                "motion": "force gauge pulls each block in turn",
                "lighting": "even diffused light",
                "background": "test bench",
                "objects": ["force gauge", "printed blocks", "bolts", "inserts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a pull test comparing printed, tapped, and heat-set insert threads with a force gauge, even diffused lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match method to reuse and load",
                "shot": "wide hero shot of a finished assembly with brass inserts and bolts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["assembled part", "brass inserts", "bolts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an assembled 3D printed part with visible brass heat-set inserts and bolts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three thread methods compared with a bolt in the center",
            "subject": "printed block with tap, and brass inserts",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "three blocks in a row, bolt center",
            "text": "THREADS THAT HOLD",
            "elements": ["printed threads", "tap", "brass inserts", "bolt"],
            "style": "industrial macro photography",
            "mood": "strong, engineered, comparative",
            "prompt": "macro photograph of three threaded test blocks with a tap and brass inserts around a center bolt, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Threads That Actually Hold",
            "title_variations": [
                "Printed vs Tapped vs Heat-Set Threads",
                "Best Way to Add Threads to Prints",
                "Heat-Set Inserts Explained",
                "Why Printed Threads Strip",
                "Metal Threads in Plastic Parts",
            ],
            "description": "Threads printed directly into plastic are weak: layer lines become failure planes when a bolt is torqued. The three practical options are cut threads, tapped threads, and heat-set inserts. Cut threads are printed undersized and then tapped, which is clean and strong when the hole is vertical and the part is thick. Heat-set inserts melt brass threads into the plastic for repeatable assembly and real clamp load, making them the standard for parts that see screws more than once. This short compares strength, cost, and when each method makes sense, plus the design rules for boss size and hole diameter.",
            "hashtags": ["#Threads", "#3Dprinting", "#Design", "#Hardware"],
            "seo_keywords": [
                "heat set inserts 3d printing",
                "threads in 3d prints",
                "tapped threads printed part",
                "printed vs heat set threads",
                "brass inserts for 3d printing",
                "boss design 3d print",
                "threads that hold plastic",
            ],
        },
        "fact_check": [
            "Printed threads have stepped flanks and weak layer bonds, making them the least strong option.",
            "Tapping a printed hole cuts clean flanks but strength remains limited by the plastic's interlayer bond.",
            "Heat-set inserts provide metal threads with high pull-out strength and are reusable indefinitely.",
            "Boss outer diameter is typically twice the insert diameter; hole size follows the insert manufacturer datasheet.",
            "Insert installation temperature is near the plastic's softening point, around 230-270 C for PLA and PETG.",
        ],
    },
    # ======================================================================
    {
        "topic": "Print Orientation Strength",
        "core_question": "Does how I orient a part change its strength, and how much?",
        "learning_objective": "The viewer can identify the weakest direction in an FDM part, orient for the main load, and know when walls matter more than infill.",
        "engineering_summary": "FDM parts are anisotropic: the strength across layer bonds is typically 30-50% lower than strength along the layers, because interlayer bonds are welded interfaces rather than continuous material. A part printed flat fails between layers when loaded to peel them apart; the same part printed upright carries that load along the layer direction. Orientation is free strength - it costs nothing and can double effective part strength. Walls (perimeters) carry most bending and tension loads, so increasing wall count often beats increasing infill percentage. For unknown or multidirectional loads, use more walls and thicker layers of bonding, or a 45-degree orientation as a compromise.",
        "real_world_application": "Structural brackets, printed gears, and frame parts are oriented so the main load pulls along layers; load-bearing printed parts for machines specify orientation in the drawing.",
        "common_misconceptions": [
            "Infill percentage is the main strength knob (walls carry most loads; orientation matters more)",
            "Layer lines are cosmetic only (they mark the weakest plane of the part)",
            "All orientations are equal for strength (anisotropy makes orientation a free strength lever)",
        ],
        "teaching_strategy": "Open with a two-copy break test showing flat vs upright, explain the layer-bond plane, then the walls-over-infill rule.",
        "script": "A printed part is a stack of welded layers, and layers have a direction. Pull along the layers and the bond between them carries the load; pull across and you're testing layer adhesion, which is usually the weak link. That's why parts break along layer lines. Rotate the model so the big forces pull along the layers, not peel them apart. Orientation often matters more than infill. If the load is unknown or multidirectional, add more walls instead of more infill - perimeters are the real strength skeleton. Orient first, print second.",
        "text_overlay": [
            "LAYERS = WELDED STACK",
            "ACROSS LAYERS = WEAK",
            "ALONG LAYERS = STRONG",
            "MORE WALLS > MORE INFILL",
        ],
        "scenes": [
            {
                "goal": "Hook: the break test",
                "teaching_point": "Two identical parts, two different results",
                "shot": "medium shot of a break test on two identical brackets printed flat and upright",
                "motion": "both snap, but the upright one holds longer",
                "lighting": "even diffused light",
                "background": "test bench",
                "objects": ["two brackets", "vise", "printed parts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a break test on two identical 3D printed brackets clamped in a vise, even diffused lighting, test bench",
            },
            {
                "goal": "The layer plane",
                "teaching_point": "Bonds between layers are the weak plane",
                "shot": "graphic-style shot of a stacked-layer block with a force arrow across the seams",
                "motion": "arrow splits the layers apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer stack diagram", "force arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a layer stack diagram with a force arrow splitting between layers on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Free strength",
                "teaching_point": "Rotation is free strength",
                "shot": "medium shot of a bracket model rotating in CAD to align with the load",
                "motion": "model rotates 90 degrees and locks",
                "lighting": "neutral lab light",
                "background": "CAD workstation",
                "objects": ["CAD screen", "bracket model", "load arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bracket model rotating in CAD software with a load arrow, neutral lab lighting, CAD workstation",
            },
            {
                "goal": "Walls vs infill",
                "teaching_point": "Perimeters carry the load",
                "shot": "macro shot of a cut part cross-section showing walls and infill",
                "motion": "slow push-in on the perimeter rings",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["cut print", "walls", "infill pattern"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a cut 3D print cross-section showing walls and infill, bright task light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Orient first, print second",
                "shot": "wide hero shot of a strong printed bracket mounted and holding load",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["mounted bracket", "load", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printed bracket mounted and carrying a load, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Same bracket twice: one splitting between layers, one intact",
            "subject": "broken flat bracket and intact upright bracket",
            "background": "dark machine shop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "broken part left, strong part right, arrow between",
            "text": "ORIENT = STRENGTH",
            "elements": ["broken bracket", "intact bracket", "layer lines", "arrow"],
            "style": "industrial macro photography",
            "mood": "strong, comparative, decisive",
            "prompt": "photograph of a broken flat 3D printed bracket on the left and an intact upright bracket on the right with a strength arrow, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Orientation Is Free Strength",
            "title_variations": [
                "How to Orient Parts for Strength",
                "Layer Direction vs Strength",
                "Why Prints Break Along Layer Lines",
                "Walls vs Infill: What Wins",
                "Stronger Prints Without New Settings",
            ],
            "description": "FDM parts are strongest along the direction of the printed layers and weakest across them, because the bond between layers is a weld, not a continuous material. A part printed flat fails between layers when you pull it apart; the same part printed upright carries the load along the layer direction. Choosing the right orientation is free strength: it costs nothing and can double or triple real-world part strength. Walls, not infill, carry most of the load, so orientation and perimeter count matter more than infill percentage. This short shows the failure modes and a practical rule for orienting parts before slicing.",
            "hashtags": ["#3Dprinting", "#Design", "#Strength", "#Engineering"],
            "seo_keywords": [
                "print orientation strength",
                "layer adhesion strength",
                "why parts break along layer lines",
                "strongest 3d print orientation",
                "walls vs infill strength",
                "anisotropic 3d printing",
                "design for 3d printing strength",
            ],
        },
        "fact_check": [
            "Interlayer strength in FDM is typically 30-50% lower than in-layer strength for the same material.",
            "Loads parallel to the layer direction are carried by the continuous strand material.",
            "Loads perpendicular to the layer plane test the welded interlayer bond, the weakest mode.",
            "Walls (perimeters) dominate bending and tension capacity; infill mostly provides buckling resistance.",
            "A 45-degree orientation is a common compromise for parts with unknown or multidirectional loading.",
        ],
    },
]
