"""Batch 32: combing, travel stringing, thin walls, layer time, small features, fuzzy skin, lightning infill, pressure advance."""

CURATED = [
    # ======================================================================
    {
        "topic": "Combing Mode",
        "core_question": "Why does the nozzle trace pretty loops inside your print?",
        "learning_objective": "The viewer understands combing and how it fights stringing.",
        "engineering_summary": "Combing keeps the nozzle inside the part's walls during travel moves, so the filament stays hidden in already-printed paths instead of crossing open air. Every time the head leaves the part, it risks leaving a string, so the slicer reroutes the travel through the infill, like a maze that hides the trail. The trade-off is time: the combed path is longer, and it can leave scars inside the walls. Combing is a route planner: hide the travel, or pay with strings.",
        "real_world_application": "Combing reduces the retraction needed for hidden internal moves.",
        "common_misconceptions": [
            "Combing removes stringing (it hides travel, retraction still handles tips)",
            "Combing always helps (it costs time and can scar walls)",
            "It affects the part's shape (it only reroutes travel paths)",
        ],
        "teaching_strategy": "Show the same travel with combing on and off.",
        "script": "Combing keeps the nozzle inside the part's walls during travel moves, so the filament stays hidden in already-printed paths instead of crossing open air. Every time the head leaves the part, it risks leaving a string, so the slicer reroutes the travel through the infill, like a maze that hides the trail. The trade-off is time: the combed path is longer, and it can leave scars inside the walls. Combing is a route planner: hide the travel, or pay with strings.",
        "text_overlay": [
            "STAY INSIDE THE WALLS",
            "REROUTE THROUGH INFILL",
            "HIDE THE TRAIL",
            "LONGER PATH, FEWER STRINGS",
        ],
        "scenes": [
            {
                "goal": "Hook: the open-air crossing",
                "teaching_point": "Travel across nothing",
                "shot": "diagram-style shot of a nozzle crossing open air",
                "motion": "head drags a string across a gap",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle path", "open gap", "string trail"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a diagram of a nozzle crossing open air, clean engineering visualization on a dark background",
            },
            {
                "goal": "The maze",
                "teaching_point": "Travel hidden in infill",
                "shot": "diagram-style shot of combed travel through infill",
                "motion": "path weaves inside the walls",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["combed path", "infill maze", "walls"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of combed travel through infill, clean engineering visualization on a dark background",
            },
            {
                "goal": "The comparison",
                "teaching_point": "Same travel, two routes",
                "shot": "diagram-style shot of direct versus combed paths",
                "motion": "two paths overlay and compare",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["direct path", "combed path", "string count"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of combing path comparison, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cost",
                "teaching_point": "Time and wall scars",
                "shot": "close-up shot of a combing scar on a wall",
                "motion": "light shows the internal scratch",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["wall scar", "combing path", "print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a combing scar on a printed wall, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Route the travel",
                "shot": "wide hero shot of a clean string-free print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "travel path", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean string-free print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle weaving through infill walls to hide its trail",
            "subject": "combing mode",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "nozzle center, maze behind",
            "text": "HIDE THE TRAIL",
            "elements": ["nozzle", "infill maze", "combed path"],
            "style": "geometry studio photography",
            "mood": "routed, hidden, clean",
            "prompt": "photograph of a nozzle weaving through infill walls with a combed travel path and open-air strings, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Combing Mode: Hide the Trail",
            "title_variations": [
                "What Does Combing Do",
                "Combing Mode Slicer",
                "Combing vs Retraction",
                "Travel Moves Combing",
                "Stringing Combing Fix",
            ],
            "description": "Combing keeps the nozzle inside the part's walls during travel moves, so the filament stays hidden in already-printed paths instead of crossing open air. Every time the head leaves the part it risks a string, so the slicer reroutes travel through the infill like a maze that hides the trail. The trade-off is time and possible wall scars. This short traces both routes and shows how combing is a route planner: hide the travel, or pay with strings.",
            "hashtags": ["#Combing", "#TravelMoves", "#Stringing", "#Slicer"],
            "seo_keywords": [
                "what does combing do",
                "combing mode slicer",
                "combing vs retraction",
                "travel moves combing",
                "stringing combing fix",
                "combing infill path",
                "nozzle travel inside",
            ],
        },
        "fact_check": [
            "Combing hides travel in infill.",
            "Crossing open air risks strings.",
            "The combed path is longer.",
            "Combing can scar walls.",
            "It is a travel route planner.",
        ],
    },
    {
        "topic": "Travel Moves & Stringing",
        "core_question": "Why do strings always appear between the towers?",
        "learning_objective": "The viewer understands travel moves and stringing.",
        "engineering_summary": "Stringing is born during travel: the nozzle moves to a new spot, and the plastic left in the nozzle tip pulls out into a hair-thin strand. The slicer fights it with three levers: retraction pulls the filament back, wiping drags the tip across a wall to shed the blob, and travel order picks the shortest safe route. Each lever moves the same problem around, so stringing is a triangle of pressure, distance, and heat. Clean travels are planned travels.",
        "real_world_application": "Stringing between towers and over gaps is a travel-planning problem.",
        "common_misconceptions": [
            "Retraction alone fixes strings (wipe and routing share the job)",
            "Stringing is a temperature-only issue (it is travel pressure)",
            "Strings are cosmetic (they scar functional surfaces)",
        ],
        "teaching_strategy": "Show a travel, then retraction, wipe, and routing each removing part of the string.",
        "script": "Stringing is born during travel: the nozzle moves to a new spot, and the plastic left in the nozzle tip pulls out into a hair-thin strand. The slicer fights it with three levers: retraction pulls the filament back, wiping drags the tip across a wall to shed the blob, and travel order picks the shortest safe route. Each lever moves the same problem around, so stringing is a triangle of pressure, distance, and heat. Clean travels are planned travels.",
        "text_overlay": [
            "TIP PLASTIC PULLS OUT",
            "RETRACTION, WIPE, ROUTE",
            "PRESSURE, DISTANCE, HEAT",
            "CLEAN TRAVELS ARE PLANNED",
        ],
        "scenes": [
            {
                "goal": "Hook: the strand",
                "teaching_point": "Hair between towers",
                "shot": "close-up shot of strings between two printed towers",
                "motion": "light catches the hair strands",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["hair strands", "towers", "gap"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of strings between two printed towers, bright task lighting, print lab",
            },
            {
                "goal": "The birth",
                "teaching_point": "Tip pulls a strand",
                "shot": "diagram-style shot of a nozzle pulling a strand during travel",
                "motion": "tip leaves a thin trail across the gap",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle", "pulled strand", "travel path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a nozzle pulling a string during travel, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pull",
                "teaching_point": "Retraction backs the filament",
                "shot": "diagram-style shot of retraction pulling filament back",
                "motion": "filament retreats from the hot zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["filament pull", "hot zone", "tip gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of retraction during travel, clean engineering visualization on a dark background",
            },
            {
                "goal": "The wipe",
                "teaching_point": "Tip sheds the blob",
                "shot": "diagram-style shot of a wipe move across a wall",
                "motion": "tip drags along the wall edge",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wipe path", "wall edge", "shed blob"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a wipe move during travel, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Planned travels win",
                "shot": "wide hero shot of a clean print with a planned path overlay",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "planned path", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean print with a planned travel path overlay, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle pulling a strand with retraction, wipe, and route arrows",
            "subject": "travel moves stringing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "nozzle center, three arrows",
            "text": "CLEAN TRAVELS ARE PLANNED",
            "elements": ["nozzle", "strand", "travel arrows"],
            "style": "geometry studio photography",
            "mood": "pulled, wiped, planned",
            "prompt": "photograph of a nozzle pulling a strand between two towers with retraction, wipe, and route arrows, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Travel Moves & Stringing: Clean Travels Are Planned",
            "title_variations": [
                "Why Travel Moves Cause Stringing",
                "Travel Stringing Fix",
                "Retraction Wipe Routing",
                "Stringing Between Towers",
                "Travel Moves Explained",
            ],
            "description": "Stringing is born during travel: the nozzle moves to a new spot, and the plastic left in the nozzle tip pulls out into a hair-thin strand. The slicer fights it with three levers: retraction pulls the filament back, wiping drags the tip across a wall to shed the blob, and travel order picks the shortest safe route. Stringing is a triangle of pressure, distance, and heat. This short strands a pair of towers and plans the travel that removes the web.",
            "hashtags": ["#TravelMoves", "#Stringing", "#Retraction", "#3DPrinting"],
            "seo_keywords": [
                "why travel moves cause stringing",
                "travel stringing fix",
                "retraction wipe routing",
                "stringing between towers",
                "travel moves explained",
                "wipe on travel",
                "nozzle tip strand",
            ],
        },
        "fact_check": [
            "Stringing starts during travel.",
            "The tip pulls out a strand.",
            "Retraction backs the filament.",
            "Wiping sheds the blob.",
            "Routing picks the safe path.",
        ],
    },
    {
        "topic": "Thin Wall Settings",
        "core_question": "How thin can a printed wall honestly be?",
        "learning_objective": "The viewer understands thin walls and how to print them.",
        "engineering_summary": "A thin wall is a feature too narrow for two full wall loops, and the slicer decides how to fill it: with a single thin line, or with a partial overlap that thickens the wall. Single-line walls print fast but are fragile and prone to gaps, so the slicer lets you choose the minimum wall width and how to handle narrow ribs. A wall that is a whole number of extrusion widths prints clean; anything between builds its own problems. The wall's width is a decision the slicer makes for you.",
        "real_world_application": "Vases, ribs, and thin brackets all live or die by thin-wall handling.",
        "common_misconceptions": [
            "Thinner walls are always better (single lines are fragile)",
            "The slicer is exact (walls between widths need compromise)",
            "Wall width is the wall thickness (extrusion width decides)",
        ],
        "teaching_strategy": "Show a rib printed as one line versus two overlapping lines.",
        "script": "A thin wall is a feature too narrow for two full wall loops, and the slicer decides how to fill it: with a single thin line, or with a partial overlap that thickens the wall. Single-line walls print fast but are fragile and prone to gaps, so the slicer lets you choose the minimum wall width and how to handle narrow ribs. A wall that is a whole number of extrusion widths prints clean; anything between builds its own problems. The wall's width is a decision the slicer makes for you.",
        "text_overlay": [
            "TOO NARROW FOR TWO LOOPS",
            "ONE LINE: FAST, FRAGILE",
            "PARTIAL OVERLAP FILLS",
            "WIDTHS ARE EXTRUSION WIDTHS",
        ],
        "scenes": [
            {
                "goal": "Hook: the fragile rib",
                "teaching_point": "One line, weak wall",
                "shot": "close-up shot of a thin wall with gaps",
                "motion": "light shows through the gaps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["thin wall", "gaps", "rib"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a thin wall with gaps in a print, bright task lighting, print lab",
            },
            {
                "goal": "The width math",
                "teaching_point": "Whole extrusion widths",
                "shot": "diagram-style shot of wall widths as multiples",
                "motion": "one, two, and three widths stack",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["one width", "two widths", "three widths"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of wall width multiples, clean engineering visualization on a dark background",
            },
            {
                "goal": "The overlap",
                "teaching_point": "Partial overlap fills",
                "shot": "diagram-style shot of overlapping wall lines",
                "motion": "two lines squeeze into one wall",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["overlap lines", "thin wall", "fill zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of thin wall overlap, clean engineering visualization on a dark background",
            },
            {
                "goal": "The decision",
                "teaching_point": "Minimum wall width set",
                "shot": "diagram-style shot of the thin wall setting",
                "motion": "slider sets the minimum width",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thin wall slider", "minimum width", "setting value"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of thin wall settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Decide the width",
                "shot": "wide hero shot of a clean ribbed part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["ribbed part", "clean walls", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean ribbed part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Wall widths stacking as extrusion multiples with a slider",
            "subject": "thin wall settings",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "width stack center, slider beside",
            "text": "DECIDE THE WIDTH",
            "elements": ["width stack", "thin wall", "slider"],
            "style": "geometry studio photography",
            "mood": "narrowed, filled, decided",
            "prompt": "photograph of wall widths stacking as extrusion multiples with a thin wall slider and a fragile rib, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Thin Wall Settings: Decide the Width",
            "title_variations": [
                "How to Print Thin Walls",
                "Thin Wall Slicer Setting",
                "Single Wall Print",
                "Minimum Wall Width",
                "Thin Feature Printing",
            ],
            "description": "A thin wall is a feature too narrow for two full wall loops, and the slicer decides how to fill it: with a single thin line, or with a partial overlap that thickens the wall. Single-line walls print fast but are fragile and prone to gaps, so the slicer lets you set the minimum wall width and how to handle narrow ribs. A wall that is a whole number of extrusion widths prints clean. This short stacks the widths and makes the call.",
            "hashtags": ["#ThinWalls", "#Slicer", "#PrintQuality", "#3DPrinting"],
            "seo_keywords": [
                "how to print thin walls",
                "thin wall slicer setting",
                "single wall print",
                "minimum wall width",
                "thin feature printing",
                "wall extrusion width",
                "thin rib print",
            ],
        },
        "fact_check": [
            "Thin walls are under two loops.",
            "Single lines are fragile.",
            "Partial overlap fills narrow walls.",
            "Extrusion width defines the unit.",
            "The slicer sets the minimum.",
        ],
    },
    {
        "topic": "Minimum Layer Time",
        "core_question": "Why do small parts turn to jelly?",
        "learning_objective": "The viewer understands minimum layer time.",
        "engineering_summary": "Every layer needs time to cool before the next lands, and tiny parts print each layer so fast that the plastic never sets, so the part softens, blobs, and leans. Minimum layer time is the slicer's clock: if a layer would finish too quickly, the printer slows down, adds a pause, or lifts the head so the plastic can solidify. The knob trades print speed for part health, and it matters most for small, tall, or pointy prints. Cooling is not automatic; it is scheduled.",
        "real_world_application": "Small pins, towers, and text all need their layer time respected.",
        "common_misconceptions": [
            "Small parts print faster (they need slower, scheduled layers)",
            "The fan fixes everything (the head must dwell too)",
            "Layer time only matters for tall parts (short hot layers blob too)",
        ],
        "teaching_strategy": "Show a tiny part blobbing, then the layer clock slowing it down.",
        "script": "Every layer needs time to cool before the next lands, and tiny parts print each layer so fast that the plastic never sets, so the part softens, blobs, and leans. Minimum layer time is the slicer's clock: if a layer would finish too quickly, the printer slows down, adds a pause, or lifts the head so the plastic can solidify. The knob trades print speed for part health, and it matters most for small, tall, or pointy prints. Cooling is not automatic; it is scheduled.",
        "text_overlay": [
            "FAST LAYERS, SOFT PLASTIC",
            "THE SLICER'S COOLING CLOCK",
            "SLOW, PAUSE, OR LIFT",
            "COOLING IS SCHEDULED",
        ],
        "scenes": [
            {
                "goal": "Hook: the jelly pin",
                "teaching_point": "Tiny part, soft layers",
                "shot": "close-up shot of a small blobby part leaning",
                "motion": "camera circles the soft column",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["blobby part", "lean", "soft layers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a small blobby leaning print, bright task lighting, print lab",
            },
            {
                "goal": "The clock",
                "teaching_point": "Layers need dwell time",
                "shot": "diagram-style shot of layer time on a clock",
                "motion": "layer finishes before the minimum",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer clock", "finish mark", "minimum line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of minimum layer time, clean engineering visualization on a dark background",
            },
            {
                "goal": "The brakes",
                "teaching_point": "Slow, pause, or lift",
                "shot": "diagram-style shot of the cooling strategies",
                "motion": "slow, pause, and lift options cycle",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slow option", "pause option", "lift option"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layer time cooling strategies, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Speed for health",
                "shot": "graphic-style shot of the speed trade curve",
                "motion": "speed drops as the clock enforces",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["speed curve", "clock line", "trade zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the layer time speed trade, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cooling is scheduled",
                "shot": "wide hero shot of a crisp small print on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["crisp small print", "layer clock", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a crisp small print on the bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A tiny part under a layer clock with slow, pause, and lift dials",
            "subject": "minimum layer time",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, clock behind",
            "text": "COOLING IS SCHEDULED",
            "elements": ["small part", "layer clock", "cooling dials"],
            "style": "geometry studio photography",
            "mood": "scheduled, dwelled, solid",
            "prompt": "photograph of a tiny part under a layer clock with cooling dials and a pause mark, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Minimum Layer Time: Cooling Is Scheduled",
            "title_variations": [
                "Why Do Small Parts Overheat",
                "Minimum Layer Time Setting",
                "Small Part Cooling",
                "Layer Cooling Slow Down",
                "Tiny Print Blob Fix",
            ],
            "description": "Every layer needs time to cool before the next lands, and tiny parts print each layer so fast that the plastic never sets, so the part softens, blobs, and leans. Minimum layer time is the slicer's clock: if a layer finishes too quickly, the printer slows down, adds a pause, or lifts the head so the plastic can solidify. This short jellies a pin, sets the clock, and shows how cooling is scheduled, not automatic.",
            "hashtags": ["#LayerTime", "#Cooling", "#SmallParts", "#3DPrinting"],
            "seo_keywords": [
                "why do small parts overheat",
                "minimum layer time",
                "small part cooling",
                "layer cooling slow down",
                "tiny print blob",
                "minimum layer time setting",
                "print pause cooling",
            ],
        },
        "fact_check": [
            "Layers need cooling time.",
            "Tiny parts print too fast.",
            "Minimum layer time is a clock.",
            "Slow, pause, or lift help.",
            "Speed trades for part health.",
        ],
    },
    {
        "topic": "Small Feature Speeds",
        "core_question": "Why do tiny details look like melted candles?",
        "learning_objective": "The viewer understands small feature speeds.",
        "engineering_summary": "Small details melt because they heat faster than they cool: the nozzle dwells over the same tiny patch, and the plastic softens and smears. Small feature speeds are the slicer's safety: when a move is shorter than a threshold, the head slows down, so the melt gets less heat and more control. Fast and small is the enemy, so the slicer swaps speed for definition on the details. The same logic that protects small parts with layer time applies to their moves.",
        "real_world_application": "Text, pins, and fine embossing all depend on small-feature speed control.",
        "common_misconceptions": [
            "Speed is uniform (small moves need their own limit)",
            "Slow details are a slicer bug (it is melt protection)",
            "Layer time handles it (move speed is a separate lever)",
        ],
        "teaching_strategy": "Show a melted detail, then the speed limit rescuing it.",
        "script": "Small details melt because they heat faster than they cool: the nozzle dwells over the same tiny patch, and the plastic softens and smears. Small feature speeds are the slicer's safety: when a move is shorter than a threshold, the head slows down, so the melt gets less heat and more control. Fast and small is the enemy, so the slicer swaps speed for definition on the details. The same logic that protects small parts with layer time applies to their moves.",
        "text_overlay": [
            "DWELL = HEAT BUILDUP",
            "SHORT MOVES, SLOW HEADS",
            "FAST AND SMALL IS THE ENEMY",
            "SPEED FOR DEFINITION",
        ],
        "scenes": [
            {
                "goal": "Hook: the melted letter",
                "teaching_point": "Detail turned to smear",
                "shot": "close-up shot of a melted embossed detail",
                "motion": "light shows the smeared edges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["melted detail", "smear", "emboss"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a melted embossed detail on a print, bright task lighting, print lab",
            },
            {
                "goal": "The dwell",
                "teaching_point": "Nozzle lingers, heat builds",
                "shot": "diagram-style shot of a nozzle dwelling on a small patch",
                "motion": "heat rings build under the tip",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dwelling nozzle", "heat rings", "small patch"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of nozzle dwell heat buildup, clean engineering visualization on a dark background",
            },
            {
                "goal": "The threshold",
                "teaching_point": "Short moves slow down",
                "shot": "diagram-style shot of the move length threshold",
                "motion": "short moves drop below the speed line",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["move lengths", "speed line", "threshold"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of small feature speed thresholds, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rescue",
                "teaching_point": "Slow head, crisp edges",
                "shot": "close-up shot of a crisp embossed detail printing",
                "motion": "head moves slow and clean",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["crisp detail", "slow head", "clean edges"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a crisp embossed detail printing slowly, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Swap speed for definition",
                "shot": "wide hero shot of a detail-rich print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["detail-rich print", "fine text", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a detail-rich print with fine text, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle slowing over a tiny detail with a speed threshold line",
            "subject": "small feature speeds",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "detail center, threshold line",
            "text": "SPEED FOR DEFINITION",
            "elements": ["tiny detail", "nozzle", "speed line"],
            "style": "geometry studio photography",
            "mood": "dwelled, slowed, defined",
            "prompt": "photograph of a nozzle slowing over a tiny detail with a speed threshold line, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Small Feature Speeds: Speed for Definition",
            "title_variations": [
                "How to Print Small Details Cleanly",
                "Small Feature Speed Setting",
                "Tiny Details Melting Fix",
                "Small Part Quality",
                "Feature Speed Slicer",
            ],
            "description": "Small details melt because they heat faster than they cool: the nozzle dwells over the same tiny patch and the plastic softens and smears. Small feature speeds are the slicer's safety: when a move is shorter than a threshold, the head slows down, so the melt gets less heat and more control. Fast and small is the enemy. This short melts a letter, sets the threshold, and swaps speed for definition on the details.",
            "hashtags": ["#SmallFeatures", "#PrintQuality", "#Speed", "#3DPrinting"],
            "seo_keywords": [
                "how to print small details cleanly",
                "small feature speed",
                "tiny details melting",
                "small part quality",
                "feature speed slicer",
                "nozzle dwell heat",
                "crisp embossed text",
            ],
        },
        "fact_check": [
            "Small details heat fast.",
            "The nozzle dwells on the patch.",
            "Short moves get speed limits.",
            "Slower heads control the melt.",
            "Speed trades for definition.",
        ],
    },
    {
        "topic": "Fuzzy Skin Setting",
        "core_question": "How do you print a grippy sandpaper surface on purpose?",
        "learning_objective": "The viewer understands the fuzzy skin setting.",
        "engineering_summary": "Fuzzy skin is a slicer trick that adds a controlled rough texture to the outer walls by wobbling the nozzle in tiny jitters while it prints the perimeter. The result looks and feels like stippled or sandblasted metal, it hides layer lines, and it gives parts grip. The knobs are the thickness and density of the wobble: gentle for a matte finish, aggressive for a grippy one. It is a texture generator, not a defect, and it turns the printer into a surface finishing tool.",
        "real_world_application": "Handles, grips, and covers use fuzzy skin for texture and feel.",
        "common_misconceptions": [
            "It is a printing error (it is a deliberate setting)",
            "It weakens parts badly (the wobble barely changes strength)",
            "It is only cosmetic (it changes grip and hides lines)",
        ],
        "teaching_strategy": "Show the wobble path, then the same part with and without skin.",
        "script": "Fuzzy skin is a slicer trick that adds a controlled rough texture to the outer walls by wobbling the nozzle in tiny jitters while it prints the perimeter. The result looks and feels like stippled or sandblasted metal, it hides layer lines, and it gives parts grip. The knobs are the thickness and density of the wobble: gentle for a matte finish, aggressive for a grippy one. It is a texture generator, not a defect, and it turns the printer into a surface finishing tool.",
        "text_overlay": [
            "WOBBLE THE NOZZLE ON PURPOSE",
            "STIPPLED, NOT SMOOTH",
            "HIDES LAYER LINES",
            "THICKNESS AND DENSITY",
        ],
        "scenes": [
            {
                "goal": "Hook: the stippled wall",
                "teaching_point": "Rough on purpose",
                "shot": "close-up shot of a fuzzy skin surface",
                "motion": "light rakes the stipple texture",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["fuzzy surface", "stipple", "grip texture"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a fuzzy skin textured surface, bright task lighting, print lab",
            },
            {
                "goal": "The wobble",
                "teaching_point": "Nozzle jitters on the wall",
                "shot": "diagram-style shot of the nozzle wobble path",
                "motion": "head jitters along the perimeter",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wobble path", "perimeter", "jitter dots"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fuzzy skin nozzle wobble, clean engineering visualization on a dark background",
            },
            {
                "goal": "The knobs",
                "teaching_point": "Thickness and density",
                "shot": "diagram-style shot of fuzzy skin knobs",
                "motion": "two sliders set the texture",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thickness slider", "density slider", "texture scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fuzzy skin settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "The compare",
                "teaching_point": "Smooth versus stippled",
                "shot": "medium shot of two parts side by side",
                "motion": "smooth and fuzzy parts compare",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["smooth part", "fuzzy part", "comparison"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of smooth and fuzzy skin parts side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A finishing tool",
                "shot": "wide hero shot of a grippy handle part with texture",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["grippy handle", "textured part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a grippy textured handle part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle wobbling along a wall with smooth and stippled halves",
            "subject": "fuzzy skin setting",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "wall center, knob sliders below",
            "text": "WOBBLE ON PURPOSE",
            "elements": ["wobble path", "stippled wall", "sliders"],
            "style": "geometry studio photography",
            "mood": "textured, stippled, grippy",
            "prompt": "photograph of a nozzle wobbling along a wall with smooth and stippled halves and grip sliders, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Fuzzy Skin Setting: Wobble on Purpose",
            "title_variations": [
                "What Does Fuzzy Skin Do",
                "Fuzzy Skin Slicer Setting",
                "Fuzzy Print Texture",
                "Grip Surface 3D Print",
                "Textured Wall Print",
            ],
            "description": "Fuzzy skin is a slicer trick that adds a controlled rough texture to the outer walls by wobbling the nozzle in tiny jitters while it prints the perimeter. The result looks and feels like stippled metal, hides layer lines, and gives parts grip. The knobs are wobble thickness and density: gentle for matte, aggressive for grippy. This short wobbles the nozzle, rakes the texture, and turns the printer into a surface finishing tool.",
            "hashtags": ["#FuzzySkin", "#Texture", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "what does fuzzy skin do",
                "fuzzy skin slicer setting",
                "fuzzy print texture",
                "grip surface print",
                "textured wall print",
                "fuzzy skin thickness",
                "hide layer lines texture",
            ],
        },
        "fact_check": [
            "Fuzzy skin is deliberate.",
            "The nozzle wobbles on purpose.",
            "It hides layer lines.",
            "Thickness and density tune it.",
            "It adds grip to parts.",
        ],
    },
    {
        "topic": "Lightning Infill",
        "core_question": "What if infill only grew where the top needs it?",
        "learning_objective": "The viewer understands lightning infill.",
        "engineering_summary": "Lightning infill is an adaptive pattern that grows tree-like branches only where the top surface needs support, leaving most of the part hollow. It uses a fraction of the material of grid or gyroid, prints fast because the nozzle does not crisscross, and still carries the top solidly, because the branches fan out under the ceiling. The trade is direction: lightning gives in one direction, so it suits display and lightweight parts, not loaded ones. It is infill that thinks about the top, not the whole volume.",
        "real_world_application": "Lightweight display parts and prototypes save material with lightning infill.",
        "common_misconceptions": [
            "It is a gimmick (it is a real material saver)",
            "It is as strong as grid (it is directional by design)",
            "Hollow parts always collapse (branches carry the top)",
        ],
        "teaching_strategy": "Show the branches growing to the top, then the material saved.",
        "script": "Lightning infill is an adaptive pattern that grows tree-like branches only where the top surface needs support, leaving most of the part hollow. It uses a fraction of the material of grid or gyroid, prints fast because the nozzle does not crisscross, and still carries the top solidly, because the branches fan out under the ceiling. The trade is direction: lightning gives in one direction, so it suits display and lightweight parts, not loaded ones. It is infill that thinks about the top, not the whole volume.",
        "text_overlay": [
            "BRANCHES UNDER THE CEILING",
            "MOSTLY HOLLOW",
            "FRACTION OF THE MATERIAL",
            "TOP STRONG, SIDES LIGHT",
        ],
        "scenes": [
            {
                "goal": "Hook: the hollow surprise",
                "teaching_point": "Infill only at the top",
                "shot": "diagram-style shot of a cut-open part with branch infill",
                "motion": "camera drops through the hollow volume",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["branch infill", "hollow volume", "top surface"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a diagram of lightning infill in a cut part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The growth",
                "teaching_point": "Trees reach the ceiling",
                "shot": "diagram-style shot of branches growing upward",
                "motion": "trees fan out under the top",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["branch trees", "ceiling fan", "growing tips"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of lightning infill branch growth, clean engineering visualization on a dark background",
            },
            {
                "goal": "The saving",
                "teaching_point": "Fraction of the material",
                "shot": "graphic-style shot of material bars comparing infills",
                "motion": "lightning bar shrinks below grid",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["material bars", "grid bar", "lightning bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of infill material comparison bars, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "One direction of strength",
                "shot": "diagram-style shot of load arrows on the part",
                "motion": "top load holds, side load flexes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["top load", "side load", "branch direction"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of lightning infill load directions, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Think about the top",
                "shot": "wide hero shot of a lightweight display part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["lightweight part", "display model", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a lightweight display part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cut part with tree branches under the ceiling and material bars",
            "subject": "lightning infill",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cut part center, bars beside",
            "text": "THINK ABOUT THE TOP",
            "elements": ["branch infill", "cut part", "material bars"],
            "style": "geometry studio photography",
            "mood": "branched, hollow, saved",
            "prompt": "photograph of a cut part with lightning infill branches under the ceiling and material bars, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Lightning Infill: Think About the Top",
            "title_variations": [
                "What Is Lightning Infill",
                "Lightning Infill Slicer",
                "Adaptive Infill Explained",
                "Tree Like Infill",
                "Lightweight Infill Pattern",
            ],
            "description": "Lightning infill is an adaptive pattern that grows tree-like branches only where the top surface needs support, leaving most of the part hollow. It uses a fraction of the material of grid or gyroid, prints fast because the nozzle does not crisscross, and still carries the top solidly because the branches fan out under the ceiling. The trade is direction: lightning gives in one direction. This short grows the branches, shrinks the material bar, and shows infill that thinks about the top.",
            "hashtags": ["#LightningInfill", "#Infill", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "what is lightning infill",
                "lightning infill slicer",
                "adaptive infill",
                "tree like infill",
                "lightweight infill",
                "infill material saving",
                "lightning vs grid infill",
            ],
        },
        "fact_check": [
            "Lightning grows to the top.",
            "Most of the part stays hollow.",
            "It saves material and time.",
            "It is directional in strength.",
            "It suits lightweight parts.",
        ],
    },
    {
        "topic": "Pressure Advance",
        "core_question": "How does Klipper tune the pressure in your nozzle?",
        "learning_objective": "The viewer understands pressure advance and how to tune it.",
        "engineering_summary": "Pressure advance is Klipper's cousin of linear advance: it predicts the pressure needed for the next move and starts pushing filament early, so the nozzle is already pressurized when speed changes happen. Without it, corners underextrude and blobs appear at every stop. The tuning is a single value, PA, measured by printing a test tower: too low leaves blobs, too high starves the corners, and the cleanest section wins. It is the same pressure math as linear advance, tuned for the Klipper motion stack.",
        "real_world_application": "Klipper users tune PA once per filament and nozzle.",
        "common_misconceptions": [
            "PA replaces retraction (it fixes pressure, not travel drips)",
            "One PA fits all (filament, temperature, and nozzle change it)",
            "It is only for advanced users (any Klipper print benefits)",
        ],
        "teaching_strategy": "Show the pressure prediction, then the PA test tower.",
        "script": "Pressure advance is Klipper's cousin of linear advance: it predicts the pressure needed for the next move and starts pushing filament early, so the nozzle is already pressurized when speed changes happen. Without it, corners underextrude and blobs appear at every stop. The tuning is a single value, PA, measured by printing a test tower: too low leaves blobs, too high starves the corners, and the cleanest section wins. It is the same pressure math as linear advance, tuned for the Klipper motion stack.",
        "text_overlay": [
            "PREDICT THE PRESSURE",
            "PUSH EARLY, STAY PRESSURIZED",
            "TOO HIGH STARVES CORNERS",
            "ONE VALUE, TUNED",
        ],
        "scenes": [
            {
                "goal": "Hook: the starved corner",
                "teaching_point": "Speed change, pressure gap",
                "shot": "close-up shot of underextruded corners on a print",
                "motion": "camera pans the starved edges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["starved corners", "print wall", "edges"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of underextruded corners on a print, bright task lighting, print lab",
            },
            {
                "goal": "The prediction",
                "teaching_point": "Push filament before the move",
                "shot": "diagram-style shot of early pressure ramping",
                "motion": "pressure rises ahead of motion",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pressure ramp", "motion line", "early push"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of pressure advance prediction, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tower",
                "teaching_point": "PA values per section",
                "shot": "diagram-style shot of a PA test tower",
                "motion": "sections scan through PA values",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["test tower", "PA sections", "value marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a pressure advance test tower, clean engineering visualization on a dark background",
            },
            {
                "goal": "The read",
                "teaching_point": "Too low blobs, too high starves",
                "shot": "close-up shot of tower sections being inspected",
                "motion": "blobby and starved sections pass by",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["tower sections", "blob zone", "starve zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of pressure advance tower sections being inspected, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Same math, Klipper stack",
                "shot": "wide hero shot of a clean print beside a PA tower",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "PA tower", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean print beside a pressure advance tower, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A pressure ramp pushing early with a PA test tower",
            "subject": "pressure advance",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "ramp center, tower beside",
            "text": "PUSH EARLY, STAY PRESSURIZED",
            "elements": ["pressure ramp", "test tower", "PA value"],
            "style": "geometry studio photography",
            "mood": "predicted, ramped, tuned",
            "prompt": "photograph of a pressure ramp pushing filament early with a PA test tower beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Pressure Advance: Push Early, Stay Pressurized",
            "title_variations": [
                "How to Tune Pressure Advance",
                "Pressure Advance Klipper",
                "PA Tuning Guide",
                "Klipper PA Test Tower",
                "Pressure Control Filament",
            ],
            "description": "Pressure advance is Klipper's cousin of linear advance: it predicts the pressure needed for the next move and starts pushing filament early, so the nozzle is already pressurized when speed changes happen. Without it, corners underextrude and blobs appear at every stop. The tuning is a single value, PA, measured with a test tower: too low blobs, too high starves. This short ramps the pressure early, scans the tower, and tunes the handshake for Klipper.",
            "hashtags": ["#PressureAdvance", "#Klipper", "#PATuning", "#3DPrinting"],
            "seo_keywords": [
                "how to tune pressure advance",
                "pressure advance klipper",
                "pa tuning",
                "klipper pa test tower",
                "pressure control filament",
                "pressure advance vs linear advance",
                "klipper corner underextrusion",
            ],
        },
        "fact_check": [
            "PA predicts nozzle pressure.",
            "It pushes filament early.",
            "Corners starve without it.",
            "One PA value is tuned.",
            "Too high starves corners.",
        ],
    },
]