"""Batch 45: MSLA and LCD resolution, DLP versus LCD versus laser, MJF technology, continuous carbon fiber, multi-material AM, binder jetting, rapid prototyping versus production, tolerancing in machining."""

CURATED = [
    # ======================================================================
    {
        "topic": "MSLA & LCD Resolution",
        "core_question": "What does resolution actually mean on a resin printer?",
        "learning_objective": "The viewer understands MSLA and LCD resolution.",
        "engineering_summary": "MSLA prints a whole layer at once: a UV screen backlights an LCD mask, and the mask lets light through only where the layer should cure, so one flash exposes the entire cross-section. The resolution is set by the screen: the pixel size decides the finest detail on the surface, while the layer height decides the vertical steps. The catch is the mask: the LCD blocks UV light, so it heats and wears, and its life is a real operating cost. MSLA trades a laser's sweep for a screen's flash, buying speed at the cost of pixel detail.",
        "real_world_application": "Desktop resin printers are almost all MSLA with LCD masks.",
        "common_misconceptions": [
            "All resin printers use lasers (most use a screen mask)",
            "Resolution is only layer height (pixel size matters too)",
            "Screens last forever (UV exposure wears them)",
        ],
        "teaching_strategy": "Show the screen flashing one layer, then the pixel grid.",
        "script": "MSLA prints a whole layer at once: a UV screen backlights an LCD mask, and the mask lets light through only where the layer should cure, so one flash exposes the entire cross-section. The resolution is set by the screen: the pixel size decides the finest detail on the surface, while the layer height decides the vertical steps. The catch is the mask: the LCD blocks UV light, so it heats and wears, and its life is a real operating cost. MSLA trades a laser's sweep for a screen's flash, buying speed at the cost of pixel detail.",
        "text_overlay": [
            "ONE FLASH, ONE FULL LAYER",
            "THE LCD MASK PICKS THE SHAPE",
            "PIXEL SIZE SETS THE DETAIL",
            "SCREENS WEAR, AND COST",
        ],
        "scenes": [
            {
                "goal": "Hook: the fast print",
                "teaching_point": "Whole layers at once",
                "shot": "wide shot of an MSLA printer flashing a layer",
                "motion": "screen flashes through the vat",
                "lighting": "dim room with screen glow",
                "background": "print lab",
                "objects": ["MSLA printer", "screen flash", "resin vat"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an MSLA printer flashing a layer, dim room with screen glow, print lab",
            },
            {
                "goal": "The mask",
                "teaching_point": "LCD picks the shape",
                "shot": "diagram-style shot of the LCD mask",
                "motion": "mask windows light the pattern",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["LCD mask", "light windows", "layer pattern"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an MSLA LCD mask, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pixels",
                "teaching_point": "Pixel size sets detail",
                "shot": "diagram-style shot of the pixel grid",
                "motion": "grid squares zoom to pixel size",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pixel grid", "pixel squares", "detail limit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an MSLA pixel grid, clean engineering visualization on a dark background",
            },
            {
                "goal": "The wear",
                "teaching_point": "UV wears the screen",
                "shot": "diagram-style shot of screen wear over time",
                "motion": "brightness fades across the panel",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["screen panel", "wear fade", "life curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of LCD screen wear in MSLA, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A screen's flash",
                "shot": "wide hero shot of a detailed resin part fresh from the vat",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["resin part", "detail surface", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a detailed resin part fresh from the vat, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A screen mask flashing a layer with a pixel grid zoom beside it",
            "subject": "MSLA and LCD resolution",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "screen center, grid beside",
            "text": "ONE FLASH, ONE FULL LAYER",
            "elements": ["LCD mask", "screen flash", "pixel grid"],
            "style": "geometry studio photography",
            "mood": "flashed, masked, detailed",
            "prompt": "photograph of a screen mask flashing a layer with a pixel grid zoom beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "MSLA & LCD Resolution: One Flash, One Full Layer",
            "title_variations": [
                "What Is MSLA Printing",
                "LCD Resin Printer Explained",
                "Resin Pixel Size",
                "MSLA vs SLA",
                "Screen Mask Resin Printing",
            ],
            "description": "MSLA prints a whole layer at once: a UV screen backlights an LCD mask that lets light through only where the layer should cure. The pixel size decides the finest surface detail, while layer height decides vertical steps. The catch is the mask, since UV exposure heats and wears the screen. This short flashes the mask, zooms the pixel grid, and shows the cost of the screen's wear.",
            "hashtags": ["#MSLA", "#LCD", "#ResinPrinting", "#3DPrinting"],
            "seo_keywords": [
                "what is MSLA printing",
                "LCD resin printer explained",
                "resin pixel size",
                "MSLA vs SLA",
                "screen mask resin printing",
                "MSLA LCD screen wear",
                "MSLA layer resolution",
            ],
        },
        "fact_check": [
            "MSLA flashes whole layers.",
            "The LCD mask picks shapes.",
            "Pixels set the detail.",
            "Layer height sets steps.",
            "UV wears the screen.",
        ],
    },
    {
        "topic": "DLP vs LCD vs Laser",
        "core_question": "Which resin printer technology is right for you?",
        "learning_objective": "The viewer understands DLP, LCD, and laser resin printing.",
        "engineering_summary": "The three resin technologies differ in how they shape light: a laser draws the layer point by point with a focused beam, an LCD masks the whole layer with a screen, and a DLP projector flashes the layer through a chip of micromirrors. The laser wins on smoothness because its spot is round and sharp; the LCD and DLP win on speed because they expose the whole layer at once. The trade-offs are real: DLP and LCD finish faster but show pixel steps, and their light sources age. Resin printing is a race between a beam, a screen, and a projector.",
        "real_world_application": "Jewelry uses laser SLA for smoothness; desktop users pick LCD speed.",
        "common_misconceptions": [
            "They all print the same (each shapes light differently)",
            "Laser is slow and old (it still wins on surface quality)",
            "Projectors never wear (lamps and chips age)",
        ],
        "teaching_strategy": "Show the three light paths, then the pixel steps.",
        "script": "The three resin technologies differ in how they shape light: a laser draws the layer point by point with a focused beam, an LCD masks the whole layer with a screen, and a DLP projector flashes it through a chip of micromirrors. The laser wins on smoothness because its spot is round and sharp; LCD and DLP win on speed by exposing the whole layer at once. The trade-offs are real: they finish faster but show pixel steps, and their light sources age. Resin printing is a race between a beam, a screen, and a projector.",
        "text_overlay": [
            "LASER DRAWS, LCD MASKS, DLP FLASHES",
            "BEAM SMOOTH, SCREEN AND PROJECTOR FAST",
            "PIXEL STEPS OR SHARP SPOTS",
            "A RACE OF THREE LIGHTS",
        ],
        "scenes": [
            {
                "goal": "Hook: three machines",
                "teaching_point": "Three ways to cure",
                "shot": "wide shot of three resin printers side by side",
                "motion": "camera pans the machines",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["laser printer", "LCD printer", "DLP printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of three resin printers side by side, neutral lab lighting, print lab",
            },
            {
                "goal": "The beam",
                "teaching_point": "Laser draws point by point",
                "shot": "diagram-style shot of a laser drawing a layer",
                "motion": "sharp spot traces the shape",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["laser spot", "draw path", "sharp trace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a laser drawing a resin layer, clean engineering visualization on a dark background",
            },
            {
                "goal": "The mask",
                "teaching_point": "LCD and DLP flash whole layers",
                "shot": "diagram-style shot of screen and projector flashing",
                "motion": "full layer pattern lights at once",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["screen mask", "projector flash", "full layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of LCD and DLP flashing whole layers, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Pixel steps versus sharp spots",
                "shot": "diagram-style shot of the finish comparison",
                "motion": "pixel grid appears, laser spot stays round",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pixel steps", "round spot", "finish pair"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of DLP pixel steps versus laser spots, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick the trade",
                "shot": "wide hero shot of prints from all three technologies",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["laser print", "LCD print", "DLP print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of prints from laser LCD and DLP resin printers, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A laser spot, a screen mask, and a projector flash curing three layers",
            "subject": "DLP vs LCD vs laser",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "three lights in a row",
            "text": "A RACE OF THREE LIGHTS",
            "elements": ["laser spot", "screen mask", "projector flash"],
            "style": "geometry studio photography",
            "mood": "drawn, masked, flashed",
            "prompt": "photograph of a laser spot, a screen mask, and a projector flash curing three layers, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "DLP vs LCD vs Laser: A Race of Three Lights",
            "title_variations": [
                "Which Resin Printer Technology",
                "DLP or LCD Resin",
                "Laser SLA vs LCD",
                "Resin Printer Comparison",
                "Pick a Resin Machine",
            ],
            "description": "The three resin technologies differ in how they shape light: a laser draws point by point, an LCD masks the whole layer with a screen, and a DLP flashes through micromirrors. The laser wins on smoothness; LCD and DLP win on speed. DLP and LCD show pixel steps, and their light sources age. This short traces the beam, flashes the screen, and races the three lights.",
            "hashtags": ["#DLP", "#LCD", "#LaserSLA", "#ResinPrinting"],
            "seo_keywords": [
                "which resin printer technology",
                "DLP or LCD resin",
                "laser SLA vs LCD",
                "resin printer comparison",
                "pick a resin machine",
                "DLP micromirror projector",
                "resin printer light source",
            ],
        },
        "fact_check": [
            "Laser draws point by point.",
            "LCD masks whole layers.",
            "DLP flashes through mirrors.",
            "Laser wins on smoothness.",
            "Screens and lamps age.",
        ],
    },
    {
        "topic": "MJF Technology",
        "core_question": "How does HP's Multi Jet Fusion print in powder?",
        "learning_objective": "The viewer understands Multi Jet Fusion.",
        "engineering_summary": "Multi Jet Fusion is powder printing with inkjets and heat: an inkjet bar sweeps the bed depositing fusing agent where the part should be solid and detailing agent where it should stay powder, then an IR lamp fuses the marked areas in one pass. The win is speed and strength: whole sections fuse at once, and the nylon parts come out dense with balanced properties in every direction. The trade is the platform: MJF is a production system with industrial costs. MJF fuses by marking and heating, not by a laser's sweep.",
        "real_world_application": "Production nylon parts for automotive and consumer goods run on MJF.",
        "common_misconceptions": [
            "MJF uses lasers (inkjets mark, lamps fuse)",
            "It is like SLS with detail (agents control the fusion zones)",
            "Parts need supports (unfused powder supports them)",
        ],
        "teaching_strategy": "Show the inkjet sweep, then the lamp fusing the marked area.",
        "script": "Multi Jet Fusion is powder printing with inkjets and heat: an inkjet bar sweeps the bed depositing fusing agent where the part should be solid and detailing agent where it should stay powder, then an IR lamp fuses the marked areas in one pass. The win is speed and strength: whole sections fuse at once, and the nylon parts come out dense with balanced properties in every direction. The trade is the platform: MJF is a production system with industrial costs. MJF fuses by marking and heating, not by a laser's sweep.",
        "text_overlay": [
            "INKJETS MARK, LAMPS FUSE",
            "AGENT DECIDES SOLID OR POWDER",
            "WHOLE SECTIONS FUSE AT ONCE",
            "A PRODUCTION SYSTEM, NOT A TOY",
        ],
        "scenes": [
            {
                "goal": "Hook: the dense part",
                "teaching_point": "Strong nylon parts",
                "shot": "close-up shot of a dense MJF nylon part",
                "motion": "camera pans the even surface",
                "lighting": "bright task light",
                "background": "production floor",
                "objects": ["MJF part", "even surface", "nylon body"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a dense MJF nylon part, bright task lighting, production floor",
            },
            {
                "goal": "The sweep",
                "teaching_point": "Inkjets deposit agents",
                "shot": "diagram-style shot of the inkjet bar sweeping",
                "motion": "fusing and detailing dots land",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["inkjet bar", "fusing dots", "detailing dots"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of MJF inkjets depositing agents, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fuse",
                "teaching_point": "IR lamp fuses marked areas",
                "shot": "diagram-style shot of the lamp fusing the section",
                "motion": "heat wave locks the marked zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["IR lamp", "marked zone", "fused section"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the IR lamp fusing an MJF layer, clean engineering visualization on a dark background",
            },
            {
                "goal": "The win",
                "teaching_point": "Speed and balanced strength",
                "shot": "diagram-style shot of property balance bars",
                "motion": "X, Y, and Z bars stay level",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["X bar", "Y bar", "Z bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of MJF property balance bars, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Marking and heating",
                "shot": "wide hero shot of MJF parts leaving the build unit",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["MJF parts", "build unit", "powder bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of MJF parts leaving the build unit, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An inkjet bar marking powder with an IR lamp fusing the section",
            "subject": "Multi Jet Fusion",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bar center, lamp above",
            "text": "INKJETS MARK, LAMPS FUSE",
            "elements": ["inkjet bar", "agent dots", "IR lamp"],
            "style": "geometry studio photography",
            "mood": "marked, fused, dense",
            "prompt": "photograph of an inkjet bar marking powder with an IR lamp fusing the section, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "MJF Technology: Inkjets Mark, Lamps Fuse",
            "title_variations": [
                "What Is Multi Jet Fusion",
                "HP MJF Explained",
                "MJF vs SLS",
                "Powder Fusion Printing",
                "Production Nylon Printing",
            ],
            "description": "Multi Jet Fusion is powder printing with inkjets and heat: an inkjet bar deposits fusing and detailing agents, then an IR lamp fuses the marked areas in one pass. The win is speed and strength, with dense nylon parts and balanced properties. The trade is the platform, since MJF is a production system with industrial costs. This short sweeps the bar, fires the lamp, and fuses by marking and heating.",
            "hashtags": ["#MJF", "#MultiJetFusion", "#IndustrialAM", "#3DPrinting"],
            "seo_keywords": [
                "what is multi jet fusion",
                "HP MJF explained",
                "MJF vs SLS",
                "powder fusion printing",
                "production nylon printing",
                "MJF fusing agent",
                "MJF inkjet detailing agent",
            ],
        },
        "fact_check": [
            "Inkjets deposit agents.",
            "The lamp fuses marked zones.",
            "Whole sections fuse at once.",
            "Nylon parts come out dense.",
            "MJF is a production system.",
        ],
    },
    {
        "topic": "Continuous Carbon Fiber",
        "core_question": "How do printers lay real carbon fiber, not just strands?",
        "learning_objective": "The viewer understands continuous carbon fiber printing.",
        "engineering_summary": "Continuous carbon fiber printing is a second filament path: alongside the plastic bead, a tow of real carbon fiber is fed through a nozzle and laid into the part in continuous lengths, so the fiber carries the load along its full run. The win is structure: a part with continuous fiber is stronger than steel per gram in its fiber direction, while chopped-fiber filaments only sprinkle short strands. The rules are geometry: the fiber lays flat in each layer, so strength is directional and the design must route the fiber where the load runs. Fiber is directional strength you design in.",
        "real_world_application": "Markforged-style parts reinforce arms and brackets with continuous tows.",
        "common_misconceptions": [
            "Chopped fiber equals continuous (short strands do not carry load)",
            "Fiber is strong everywhere (it is strong along its run)",
            "Any print can take fiber (the printer needs a fiber path)",
        ],
        "teaching_strategy": "Show the fiber tow laying in, then the directional strength test.",
        "script": "Continuous carbon fiber printing adds a second filament path: beside the plastic bead, a tow of carbon fiber feeds through a nozzle and lays into the part in continuous lengths, so the fiber carries the load along its full run. The win is structure: a part with continuous fiber is stronger than steel per gram in its fiber direction, while chopped filaments sprinkle short strands. The rules are geometry: the fiber lays flat in each layer, so strength is directional and the design must route it where the load runs. Fiber is directional strength you design in.",
        "text_overlay": [
            "A TOW, NOT A SPRINKLE",
            "STRONGER THAN STEEL PER GRAM",
            "STRENGTH RUNS WITH THE FIBER",
            "ROUTE THE FIBER WHERE LOAD RUNS",
        ],
        "scenes": [
            {
                "goal": "Hook: the reinforced arm",
                "teaching_point": "It bends, then it does not",
                "shot": "close-up shot of a fiber-reinforced printed arm",
                "motion": "camera pans the fiber lines",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["fiber arm", "fiber lines", "printed body"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a fiber-reinforced printed arm, bright task lighting, print lab",
            },
            {
                "goal": "The path",
                "teaching_point": "A second filament path",
                "shot": "diagram-style shot of the fiber tow feeding",
                "motion": "tow enters beside the plastic bead",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fiber tow", "plastic bead", "nozzle pair"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of continuous fiber feeding beside plastic, clean engineering visualization on a dark background",
            },
            {
                "goal": "The compare",
                "teaching_point": "Continuous versus chopped",
                "shot": "diagram-style shot of the fiber comparison",
                "motion": "long tow carries load, short strands snap",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["long tow", "short strands", "load test"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of continuous versus chopped fiber, clean engineering visualization on a dark background",
            },
            {
                "goal": "The direction",
                "teaching_point": "Strength follows the run",
                "shot": "diagram-style shot of directional strength arrows",
                "motion": "arrows ride the fiber direction only",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fiber arrows", "load direction", "weak axis"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of directional fiber strength, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the fiber in",
                "shot": "wide hero shot of a loaded fiber part under test",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fiber part", "load rig", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fiber-reinforced part under load, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A fiber tow laying beside a plastic bead with directional strength arrows",
            "subject": "continuous carbon fiber",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "tow center, arrows beside",
            "text": "ROUTE THE FIBER WHERE LOAD RUNS",
            "elements": ["fiber tow", "plastic bead", "strength arrows"],
            "style": "geometry studio photography",
            "mood": "laid, routed, reinforced",
            "prompt": "photograph of a fiber tow laying beside a plastic bead with directional strength arrows, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Continuous Carbon Fiber: Route the Fiber Where Load Runs",
            "title_variations": [
                "How Continuous Fiber Printing Works",
                "Markforged Fiber Explained",
                "Continuous vs Chopped Carbon",
                "Strongest 3D Printed Parts",
                "Carbon Fiber Reinforcement Print",
            ],
            "description": "Continuous carbon fiber printing is a second filament path: a tow of real fiber is fed through a nozzle and laid in continuous lengths, carrying load along its full run. A part with continuous fiber is stronger than steel per gram in its fiber direction, while chopped filaments only sprinkle short strands. The rules are geometry, since the fiber lays flat and strength is directional. This short feeds the tow, snaps the strands, and routes the fiber where the load runs.",
            "hashtags": ["#CarbonFiber", "#ContinuousFiber", "#Reinforcement", "#3DPrinting"],
            "seo_keywords": [
                "how continuous fiber printing works",
                "Markforged fiber explained",
                "continuous vs chopped carbon",
                "strongest 3D printed parts",
                "carbon fiber reinforcement print",
                "fiber tow nozzle print",
                "directional fiber strength",
            ],
        },
        "fact_check": [
            "Fiber lays in continuous tows.",
            "It carries load along its run.",
            "Chopped fiber is a sprinkle.",
            "Strength follows direction.",
            "Design routes the fiber.",
        ],
    },
    {
        "topic": "Multi-Material AM",
        "core_question": "Can one machine print with many materials at once?",
        "learning_objective": "The viewer understands multi-material AM.",
        "engineering_summary": "Multi-material AM blends materials inside one build: some machines swap extruders, some switch nozzle paths, and advanced systems jet multiple materials voxel by voxel, so a single part carries hard and soft zones, colors, and gradients. The win is function: one print can be rigid in the bracket and flexible in the hinge, with no assembly step between. The trade is process: each material has its own temperature and chemistry, so every interface is a compatibility question. Multi-material printing is not one process but a family, and the interfaces decide what is possible.",
        "real_world_application": "Printed shoes and grippers blend rigid and soft zones in one part.",
        "common_misconceptions": [
            "Multi-material means multiple colors (it means multiple properties)",
            "Any materials combine (temperatures and chemistry must match)",
            "It is one technology (it is a family of approaches)",
        ],
        "teaching_strategy": "Show hard and soft zones in one part, then the interface.",
        "script": "Multi-material AM blends materials inside one build: some machines swap extruders, some switch nozzle paths, and advanced systems jet multiple materials voxel by voxel, so a single part carries hard and soft zones, colors, and gradients. The win is function: one print can be rigid in the bracket and flexible in the hinge, with no assembly step between. The trade is process: each material has its own temperature and chemistry, so every interface is a compatibility question. Multi-material printing is not one process but a family, and the interfaces decide what is possible.",
        "text_overlay": [
            "HARD AND SOFT IN ONE BUILD",
            "EXTRUDERS, PATHS, OR VOXELS",
            "EVERY INTERFACE IS A QUESTION",
            "A FAMILY OF PROCESSES",
        ],
        "scenes": [
            {
                "goal": "Hook: the dual-property part",
                "teaching_point": "Rigid and flexible at once",
                "shot": "close-up shot of a part with hard and soft zones",
                "motion": "flex zone bends, rigid zone holds",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["dual part", "soft hinge", "rigid bracket"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part with hard and soft zones, bright task lighting, print lab",
            },
            {
                "goal": "The family",
                "teaching_point": "Extruders, paths, voxels",
                "shot": "diagram-style shot of the multi-material approaches",
                "motion": "three approach icons line up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["swap icon", "path icon", "voxel icon"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of multi-material approaches, clean engineering visualization on a dark background",
            },
            {
                "goal": "The voxel",
                "teaching_point": "Jet materials voxel by voxel",
                "shot": "diagram-style shot of voxel jetting",
                "motion": "tiny drops build a mixed grid",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["material drops", "voxel grid", "mixed build"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of voxel-by-voxel material jetting, clean engineering visualization on a dark background",
            },
            {
                "goal": "The interface",
                "teaching_point": "Compatibility decides",
                "shot": "diagram-style shot of two materials meeting",
                "motion": "interface line glows at the bond",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["material A", "material B", "interface line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a multi-material interface, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One part, many properties",
                "shot": "wide hero shot of a multi-material part in action",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["multi part", "flex action", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a multi-material part flexing, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Hard and soft zones in one part with a glowing interface line",
            "subject": "multi-material AM",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, interface glowing",
            "text": "A FAMILY OF PROCESSES",
            "elements": ["hard zone", "soft zone", "interface line"],
            "style": "geometry studio photography",
            "mood": "blended, jetted, interfaced",
            "prompt": "photograph of hard and soft zones in one part with a glowing interface line, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Multi-Material AM: A Family of Processes",
            "title_variations": [
                "Multi Material 3D Printing",
                "Print Hard and Soft Parts",
                "Voxel Printing Explained",
                "Multi Property Parts",
                "Blend Materials in One Print",
            ],
            "description": "Multi-material AM blends materials inside one build: some machines swap extruders, some switch nozzle paths, and advanced systems jet materials voxel by voxel, so a single part carries hard and soft zones. One print can be rigid in the bracket and flexible in the hinge, with no assembly. The trade is process, since every interface is a compatibility question. This short bends the soft zone, jettisons the voxels, and glows the interface.",
            "hashtags": ["#MultiMaterial", "#VoxelPrinting", "#AdvancedAM", "#3DPrinting"],
            "seo_keywords": [
                "multi material 3D printing",
                "print hard and soft parts",
                "voxel printing explained",
                "multi property parts",
                "blend materials in one print",
                "multi material interface",
                "material jetting voxel",
            ],
        },
        "fact_check": [
            "Materials blend in one build.",
            "Extruders, paths, or voxels.",
            "Properties mix in one part.",
            "Interfaces need compatibility.",
            "It is a family of processes.",
        ],
    },
    {
        "topic": "Binder Jetting",
        "core_question": "How do you print in sand, metal, or full color?",
        "learning_objective": "The viewer understands binder jetting.",
        "engineering_summary": "Binder jetting is powder printing with glue: an inkjet head sprays a liquid binder onto a powder bed, gluing each cross-section into shape, and the next powder layer spreads on top, so the machine prints in sand, metal, or ceramic by swapping the powder. The binder-only part is fragile, so metal parts go to a furnace where the binder burns out and the powder sinters into solid metal. The wins are the materials: full-color sand prints, metal without lasers, and parts that need no supports. Binder jetting prints with glue, then fire turns it to metal.",
        "real_world_application": "Sand casting molds and full-color prototypes are binder jet staples.",
        "common_misconceptions": [
            "Binder jetting uses lasers (it uses liquid glue)",
            "Metal parts print ready (they need sintering in a furnace)",
            "One material only (powder swaps by the job)",
        ],
        "teaching_strategy": "Show the binder spray, then the furnace step for metal.",
        "script": "Binder jetting is powder printing with glue: an inkjet head sprays a liquid binder onto a powder bed, gluing each cross-section into shape, and the next powder layer spreads on top, so the machine prints in sand, metal, or ceramic by swapping the powder. The binder-only part is fragile, so metal parts go to a furnace where the binder burns out and the powder sinters into solid metal. The wins are the materials: full-color sand prints, metal without lasers, and parts that need no supports. Binder jetting prints with glue, then fire turns it to metal.",
        "text_overlay": [
            "POWDER PLUS LIQUID GLUE",
            "SWAP THE POWDER, SWAP THE MATERIAL",
            "FURNACE BURNS BINDER, SINTERS METAL",
            "GLUE FIRST, FIRE AFTER",
        ],
        "scenes": [
            {
                "goal": "Hook: the sand part",
                "teaching_point": "Printed from sand",
                "shot": "close-up shot of a sand-printed part",
                "motion": "camera pans the grainy surface",
                "lighting": "bright task light",
                "background": "production floor",
                "objects": ["sand part", "grainy surface", "mold shape"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a sand-printed part, bright task lighting, production floor",
            },
            {
                "goal": "The spray",
                "teaching_point": "Inkjet glues the bed",
                "shot": "diagram-style shot of the binder spray",
                "motion": "binder drops glue each section",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["inkjet head", "binder drops", "powder bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of binder jetting spray, clean engineering visualization on a dark background",
            },
            {
                "goal": "The swap",
                "teaching_point": "Powder decides the material",
                "shot": "diagram-style shot of powder choices",
                "motion": "sand, metal, and ceramic bins rotate",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sand bin", "metal bin", "ceramic bin"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of binder jetting powder choices, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fire",
                "teaching_point": "Furnace sinters metal",
                "shot": "diagram-style shot of the sinter step",
                "motion": "binder burns, metal densifies",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["furnace glow", "burning binder", "solid metal"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of binder jetting sintering, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Glue first, fire after",
                "shot": "wide hero shot of full-color and metal prints",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["color print", "metal print", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of full-color and metal binder jet prints, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An inkjet spraying binder on powder beside a furnace sintering metal",
            "subject": "binder jetting",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spray left, furnace right",
            "text": "GLUE FIRST, FIRE AFTER",
            "elements": ["inkjet spray", "powder bed", "furnace glow"],
            "style": "geometry studio photography",
            "mood": "glued, sintered, colorful",
            "prompt": "photograph of an inkjet spraying liquid binder onto a powder bed beside a furnace sintering metal parts, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Binder Jetting: Glue First, Fire After",
            "title_variations": [
                "What Is Binder Jetting",
                "Sand Printing Explained",
                "Full Color Powder Printing",
                "Binder Jet Metal",
                "Print Molds in Sand",
            ],
            "description": "Binder jetting is powder printing with glue: an inkjet head sprays liquid binder onto a powder bed, gluing each cross-section into shape. Metal parts go to a furnace, where the binder burns out and the powder sinters into solid metal. The wins are materials: full-color sand, metal without lasers, and support-free parts. This short sprays the binder, swaps the powders, and fires the metal into place.",
            "hashtags": ["#BinderJetting", "#SandPrinting", "#FullColor", "#3DPrinting"],
            "seo_keywords": [
                "what is binder jetting",
                "sand printing explained",
                "full color powder printing",
                "binder jet metal",
                "print molds in sand",
                "binder jetting sintering",
                "binder jet powder swap",
            ],
        },
        "fact_check": [
            "Inkjets spray liquid binder.",
            "The bed is powder.",
            "Metal needs sintering.",
            "Powder swaps by job.",
            "Parts need no supports.",
        ],
    },
    {
        "topic": "Rapid Prototyping vs Production",
        "core_question": "When is a prototype a real part?",
        "learning_objective": "The viewer understands prototyping versus production.",
        "engineering_summary": "A prototype proves the design; a production part proves the process: prototyping is fast, cheap, and disposable, so it can fail and change, while production is repeatable, qualified, and consistent, so every unit matches the last. The mistake is mixing the two: a production process needs tooling, tolerances, and quality checks, and a prototype process has none of those. The rule is a gate: iterate on prototypes until the design is frozen, then build the process for production. Speed belongs to prototypes; consistency belongs to production.",
        "real_world_application": "Designs iterate on printers, then move to molding or milling for volume.",
        "common_misconceptions": [
            "Prototypes become production (the process changes at the gate)",
            "One print proves repeatability (one unit proves nothing)",
            "Speed is the goal everywhere (production needs consistency)",
        ],
        "teaching_strategy": "Show the fast iteration, then the qualified production line.",
        "script": "A prototype proves the design; a production part proves the process: prototyping is fast, cheap, and disposable, so it can fail and change, while production is repeatable, qualified, and consistent, so every unit matches the last. The mistake is mixing the two: a production process needs tooling, tolerances, and quality checks, and a prototype process has none of those. The rule is a gate: iterate on prototypes until the design is frozen, then build the process for production. Speed belongs to prototypes; consistency belongs to production.",
        "text_overlay": [
            "PROTOTYPE PROVES THE DESIGN",
            "PRODUCTION PROVES THE PROCESS",
            "ITERATE, FREEZE, THEN BUILD",
            "SPEED OR CONSISTENCY",
        ],
        "scenes": [
            {
                "goal": "Hook: the fast model",
                "teaching_point": "It exists to change",
                "shot": "wide shot of several prototype iterations",
                "motion": "camera pans the changed versions",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["prototype set", "changed versions", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of several prototype iterations, neutral lab lighting, print lab",
            },
            {
                "goal": "The two jobs",
                "teaching_point": "Design versus process",
                "shot": "diagram-style shot of the two goals",
                "motion": "design tile and process tile split",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["design tile", "process tile", "goal split"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of prototype versus production goals, clean engineering visualization on a dark background",
            },
            {
                "goal": "The gate",
                "teaching_point": "Freeze, then build",
                "shot": "diagram-style shot of the design gate",
                "motion": "iterations stop at the freeze line",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["iteration loop", "freeze line", "production arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the design freeze gate, clean engineering visualization on a dark background",
            },
            {
                "goal": "The line",
                "teaching_point": "Production needs tooling",
                "shot": "wide shot of a production line running parts",
                "motion": "identical parts move down the line",
                "lighting": "neutral lab light",
                "background": "production floor",
                "objects": ["production line", "identical parts", "tooling"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a production line running identical parts, neutral lab lighting, production floor",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Speed or consistency",
                "shot": "wide hero shot of a prototype beside a production part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["prototype", "production part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a prototype beside a production part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Prototype iterations beside a production line of identical parts",
            "subject": "prototyping vs production",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "prototypes left, line right",
            "text": "ITERATE, FREEZE, THEN BUILD",
            "elements": ["prototype set", "freeze line", "production row"],
            "style": "geometry studio photography",
            "mood": "iterated, frozen, qualified",
            "prompt": "photograph of several prototype iterations beside a long production line of identical finished parts, hard key light with rim, dark workshop background, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Rapid Prototyping vs Production: Iterate, Freeze, Then Build",
            "title_variations": [
                "Prototype or Production",
                "When Is a Prototype Real",
                "Design Freeze Gate",
                "Prototyping Methods",
                "Production Process Build",
            ],
            "description": "A prototype proves the design; a production part proves the process. Prototyping is fast and disposable, while production is repeatable and qualified. The mistake is mixing the two, since production needs tooling, tolerances, and quality checks. The rule is a gate: iterate until the design freezes, then build the process. This short iterates the models, freezes the line, and shows speed belonging to prototypes and consistency to production.",
            "hashtags": ["#Prototyping", "#Production", "#DesignGate", "#Engineering"],
            "seo_keywords": [
                "prototype or production",
                "when is a prototype real",
                "design freeze gate",
                "prototyping methods",
                "production process build",
                "prototype vs production part",
                "production repeatability",
            ],
        },
        "fact_check": [
            "Prototypes prove designs.",
            "Production proves processes.",
            "The process changes at the gate.",
            "One unit proves nothing.",
            "Speed or consistency.",
        ],
    },
    {
        "topic": "Tolerancing in Machining",
        "core_question": "How tight can a CNC machine actually hold?",
        "learning_objective": "The viewer understands machining tolerances.",
        "engineering_summary": "A CNC machine holds a promise: a standard mill holds about a hundredth of a millimeter, a good machine holds a few microns, and the tolerance callout decides the cost, because tighter means more setup, more passes, and more measuring. The practical rules are thermal and mechanical: heat grows the part while the machine warms, deflection bends the tool under load, and worn ways drift the position, so the tightest tolerance is the one the shop can hold on a warm day. Tolerance is a contract between the drawing and the machine, and the machine always quotes its price.",
        "real_world_application": "Shaft fits and bearing bores specify tolerances the shop can hold.",
        "common_misconceptions": [
            "Tighter is always free (each micron costs setup and time)",
            "The machine is exact (heat, deflection, and wear drift it)",
            "Tolerance is a single number (it is a contract on the drawing)",
        ],
        "teaching_strategy": "Show the tolerance ladder, then the thermal drift.",
        "script": "A CNC machine holds a promise: a standard mill holds about a hundredth of a millimeter, a good machine holds a few microns, and the tolerance callout sets the cost, because tighter means more setup, passes, and measuring. The practical rules are thermal and mechanical: heat grows the part while the machine warms, deflection bends the tool under load, and worn ways drift the position, so the tightest tolerance is the one the shop can hold on a warm day. Tolerance is a contract between the drawing and the machine, and the machine always quotes its price.",
        "text_overlay": [
            "STANDARD MILL: A HUNDREDTH",
            "GOOD MACHINE: A FEW MICRONS",
            "HEAT, DEFLECTION, WEAR DRIFT",
            "THE MACHINE QUOTES ITS PRICE",
        ],
        "scenes": [
            {
                "goal": "Hook: the bearing bore",
                "teaching_point": "It must fit exactly",
                "shot": "close-up shot of measuring a machined bore",
                "motion": "gauge reads the bore size",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["machined bore", "bore gauge", "reading"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of measuring a machined bore, bright task lighting, machine shop",
            },
            {
                "goal": "The ladder",
                "teaching_point": "Hundredths to microns",
                "shot": "diagram-style shot of the tolerance ladder",
                "motion": "rungs narrow from loose to tight",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["loose rung", "standard rung", "micron rung"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the machining tolerance ladder, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cost",
                "teaching_point": "Tighter costs more",
                "shot": "diagram-style shot of cost rising with tightness",
                "motion": "cost bar climbs as tolerance shrinks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cost bar", "tolerance axis", "setup steps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tolerance cost rising, clean engineering visualization on a dark background",
            },
            {
                "goal": "The drift",
                "teaching_point": "Heat, deflection, wear",
                "shot": "diagram-style shot of the three drifts",
                "motion": "warmth, bend, and wear arrows move the cut",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heat arrow", "deflection arrow", "wear arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of machining drift sources, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A contract with the machine",
                "shot": "wide hero shot of a fitted part in the machine",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fitted part", "machine", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fitted part in a CNC machine, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A tolerance ladder with a cost bar rising beside a drifting cut",
            "subject": "tolerancing in machining",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "ladder left, drift right",
            "text": "THE MACHINE QUOTES ITS PRICE",
            "elements": ["tolerance ladder", "cost bar", "drift arrows"],
            "style": "geometry studio photography",
            "mood": "held, drifted, contracted",
            "prompt": "photograph of a tolerance ladder with a cost bar rising beside a drifting cut, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Tolerancing in Machining: The Machine Quotes Its Price",
            "title_variations": [
                "What Tolerance Can CNC Hold",
                "Machining Tolerance Guide",
                "Tight Tolerance Cost",
                "CNC Precision Limits",
                "Bearing Bore Tolerance",
            ],
            "description": "A CNC machine holds a promise: a standard mill holds about a hundredth of a millimeter, a good machine holds a few microns, and the tolerance callout decides the cost. Heat grows the part, deflection bends the tool, and worn ways drift the position. This short climbs the tolerance ladder, watches the cost rise, and sees the machine quote its price.",
            "hashtags": ["#Tolerancing", "#CNC", "#Machining", "#Precision"],
            "seo_keywords": [
                "what tolerance can CNC hold",
                "machining tolerance guide",
                "tight tolerance cost",
                "CNC precision limits",
                "bearing bore tolerance",
                "thermal drift machining",
                "tolerance contract drawing",
            ],
        },
        "fact_check": [
            "Standard mills hold a hundredth.",
            "Good machines hold microns.",
            "Tighter tolerance costs more.",
            "Heat and wear drift cuts.",
            "Tolerance is a contract.",
        ],
    },
]