"""Batch 36: frame alignment, failed print recovery, filament grinding, probe accuracy, wall gaps, small part overheating, print-in-place, flow test."""

CURATED = [
    # ======================================================================
    {
        "topic": "Frame Alignment Check",
        "core_question": "Why does your printer print slanted no matter what you level?",
        "learning_objective": "The viewer understands frame alignment checks.",
        "engineering_summary": "If the frame is not square, every axis rides a tilted world: the gantry leans, the bed slopes, and leveling the bed cannot fix a frame that is out of square. The check is geometry with a square: measure the frame corners, the uprights against the base, and the gantry against the columns. A frame that is out by a degree prints tall parts that lean and layer shifts that wander. Alignment is the check that makes every other calibration valid, because a square frame is the machine's floor plan.",
        "real_world_application": "Tall prints and accurate dimensions start with a square frame.",
        "common_misconceptions": [
            "Leveling fixes everything (it only fixes the bed's tilt)",
            "Frames never move (shipping and use knock them out)",
            "The software compensates (it cannot fix a tilted world)",
        ],
        "teaching_strategy": "Show a leaning print, then the square check on the frame.",
        "script": "If the frame is not square, every axis rides a tilted world: the gantry leans, the bed slopes, and leveling the bed cannot fix a frame that is out of square. The check is geometry with a square: measure the frame corners, the uprights against the base, and the gantry against the columns. A frame that is out by a degree prints tall parts that lean and layer shifts that wander. Alignment is the check that makes every other calibration valid, because a square frame is the machine's floor plan.",
        "text_overlay": [
            "A TILTED WORLD",
            "MEASURE CORNERS AND UPRIGHTS",
            "OUT BY A DEGREE, PARTS LEAN",
            "THE MACHINE'S FLOOR PLAN",
        ],
        "scenes": [
            {
                "goal": "Hook: the leaning tower",
                "teaching_point": "Tall part leans",
                "shot": "wide shot of a tall print leaning visibly",
                "motion": "camera tilts with the lean",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["leaning print", "tall part", "slope"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a tall print leaning visibly, neutral lab lighting, print lab",
            },
            {
                "goal": "The tilt",
                "teaching_point": "Axes ride a tilted world",
                "shot": "diagram-style shot of an out-of-square frame",
                "motion": "gantry leans against the columns",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["leaning gantry", "base line", "tilt angle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an out-of-square frame, clean engineering visualization on a dark background",
            },
            {
                "goal": "The square",
                "teaching_point": "Square on the corners",
                "shot": "close-up shot of a square measuring a frame corner",
                "motion": "square seats against both faces",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["machinist square", "frame corner", "gap check"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a square measuring a printer frame corner, bright task lighting, print lab",
            },
            {
                "goal": "The wobble",
                "teaching_point": "Shifts wander upward",
                "shot": "diagram-style shot of layer shifts rising",
                "motion": "shifts accumulate up the height",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shift steps", "rising layers", "wander path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layer shift accumulation, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Floor plan first",
                "shot": "wide hero shot of a straight tall print on a squared frame",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["straight print", "squared frame", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a straight tall print on a squared frame, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A leaning gantry beside a square measuring a frame corner",
            "subject": "frame alignment check",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gantry center, square below",
            "text": "THE MACHINE'S FLOOR PLAN",
            "elements": ["leaning gantry", "machinist square", "frame corner"],
            "style": "geometry studio photography",
            "mood": "tilted, squared, aligned",
            "prompt": "photograph of a leaning gantry beside a square measuring a frame corner on a printer, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Frame Alignment Check: The Machine's Floor Plan",
            "title_variations": [
                "How to Check Frame Alignment",
                "Printer Squaring Guide",
                "Frame Square Check",
                "Leaning Print Fix",
                "Gantry Alignment Check",
            ],
            "description": "If the frame is not square, every axis rides a tilted world: the gantry leans, the bed slopes, and leveling the bed cannot fix it. The check is geometry with a square: measure the frame corners, the uprights against the base, and the gantry against the columns. A frame out by a degree prints tall parts that lean and shifts that wander. This short squares the corner and shows that alignment is the check that makes every other calibration valid.",
            "hashtags": ["#FrameAlignment", "#Squaring", "#MachineCheck", "#3DPrinting"],
            "seo_keywords": [
                "how to check frame alignment",
                "printer squaring",
                "frame square check",
                "leaning print fix",
                "gantry alignment",
                "out of square frame",
                "printer floor plan",
            ],
        },
        "fact_check": [
            "A tilted frame tilts the axes.",
            "Leveling cannot fix it.",
            "Squares measure the corners.",
            "Uprights must meet the base square.",
            "Small angles lean tall parts.",
        ],
    },
    {
        "topic": "Failed Print Recovery",
        "core_question": "Can you save a print that failed halfway?",
        "learning_objective": "The viewer understands failed print recovery options.",
        "engineering_summary": "A failed print does not have to be a total loss: the slicer and firmware can rescue parts of the job. Power-loss recovery resumes from the layer where power died, and a pause mid-print lets you fix a wobbling part or add a missing support. The slicer can even split the job so only the failed section reprints. Recovery is a trade: the rescues leave seams and can be as fragile as the failure, so the first decision is whether the part is worth saving. Salvage is a skill, not a setting.",
        "real_world_application": "Long prints and expensive filament make recovery worth planning.",
        "common_misconceptions": [
            "Recovery is automatic perfection (it resumes with seams and risk)",
            "Every failure is salvageable (warped geometry rarely is)",
            "Resume is always safe (the nozzle position can drift)",
        ],
        "teaching_strategy": "Show a paused print being repaired, then the resumed seam.",
        "script": "A failed print does not have to be a total loss: the slicer and firmware can rescue parts of the job. Power-loss recovery resumes from the layer where power died, and a pause mid-print lets you fix a wobbling part or add a missing support. The slicer can even split the job so only the failed section reprints. Recovery is a trade: the rescues leave seams and can be as fragile as the failure, so the first decision is whether the part is worth saving. Salvage is a skill, not a setting.",
        "text_overlay": [
            "RESUME FROM THE LAYER",
            "PAUSE, FIX, CONTINUE",
            "RECOVERY LEAVES SEAMS",
            "SALVAGE IS A SKILL",
        ],
        "scenes": [
            {
                "goal": "Hook: the half print",
                "teaching_point": "Failure mid-job",
                "shot": "medium shot of a print stopped halfway with a lifted corner",
                "motion": "camera pans the partial part",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["half print", "lifted corner", "paused job"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a print stopped halfway with a lifted corner, neutral lab lighting, print lab",
            },
            {
                "goal": "The resume",
                "teaching_point": "Power-loss recovery",
                "shot": "diagram-style shot of a print resuming mid-layer",
                "motion": "nozzle returns to the exact layer",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["resume point", "layer line", "return path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of power-loss print recovery, clean engineering visualization on a dark background",
            },
            {
                "goal": "The repair",
                "teaching_point": "Pause, fix, continue",
                "shot": "close-up shot of hands adding a brace to a paused print",
                "motion": "brace lands on the paused part",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["paused part", "added brace", "hands"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of hands adding a brace to a paused print, bright task lighting, print lab",
            },
            {
                "goal": "The split",
                "teaching_point": "Reprint only the section",
                "shot": "diagram-style shot of a job split into sections",
                "motion": "failed section alone reprints",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["split sections", "failed part", "reprint zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of splitting a job for recovery, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Worth saving?",
                "shot": "wide hero shot of a rescued part beside its seam",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["rescued part", "resume seam", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a rescued part beside its resume seam, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A paused half print with a brace and a resume seam",
            "subject": "failed print recovery",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "half print center, seam beside",
            "text": "SALVAGE IS A SKILL",
            "elements": ["half print", "added brace", "resume seam"],
            "style": "geometry studio photography",
            "mood": "paused, repaired, salvaged",
            "prompt": "photograph of a paused half print with an added brace and a resume seam, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Failed Print Recovery: Salvage Is a Skill",
            "title_variations": [
                "How to Recover a Failed Print",
                "Failed Print Rescue",
                "Resume Print Power Loss",
                "Print Recovery Guide",
                "Pause Print Repair",
            ],
            "description": "A failed print does not have to be a total loss: power-loss recovery resumes from the layer where power died, and a pause mid-print lets you fix a wobbling part or add a missing support. The slicer can even split the job so only the failed section reprints. Recovery is a trade: the rescues leave seams and can be fragile. This short pauses a half print, adds a brace, and shows that the first decision is whether the part is worth saving.",
            "hashtags": ["#PrintRecovery", "#ResumePrint", "#FailedPrint", "#3DPrinting"],
            "seo_keywords": [
                "how to recover a failed print",
                "failed print rescue",
                "resume print power loss",
                "print recovery",
                "pause print repair",
                "split job reprint",
                "salvage half print",
            ],
        },
        "fact_check": [
            "Failures can be partial.",
            "Power-loss recovery resumes.",
            "Pauses allow repairs.",
            "Jobs can split for reprint.",
            "Rescues leave seams.",
        ],
    },
    {
        "topic": "Filament Grinding",
        "core_question": "Why is your extruder chewing the filament instead of pushing it?",
        "learning_objective": "The viewer understands filament grinding.",
        "engineering_summary": "Grinding happens when the extruder's gear cannot get traction: the drive teeth chew shavings out of the filament while the feed stalls, so the print under-extrudes and the gear slips. The causes are resistance upstream or downstream: a clogged nozzle, too-low temperature, or a tangled spool all make the gear grind instead of push. The tell is shavings around the gear and a skipping sound. Fix the resistance, not the gear: clear the nozzle, raise the heat, or free the spool.",
        "real_world_application": "Skipping extruders signal a resistance problem, not a motor problem.",
        "common_misconceptions": [
            "The gear is worn (the resistance is the root cause)",
            "More pressure fixes it (it grinds harder)",
            "It is always the nozzle (tangles and temps grind too)",
        ],
        "teaching_strategy": "Show the shavings, then trace the resistance to the cause.",
        "script": "Grinding happens when the extruder's gear cannot get traction: the drive teeth chew shavings out of the filament while the feed stalls, so the print under-extrudes and the gear slips. The causes are resistance upstream or downstream: a clogged nozzle, too-low temperature, or a tangled spool all make the gear grind instead of push. The tell is shavings around the gear and a skipping sound. Fix the resistance, not the gear: clear the nozzle, raise the heat, or free the spool.",
        "text_overlay": [
            "GEAR CHEWS, FILAMENT STALLS",
            "RESISTANCE UPSTREAM OR DOWN",
            "SHAVINGS AND A SKIP",
            "FIX THE RESISTANCE, NOT THE GEAR",
        ],
        "scenes": [
            {
                "goal": "Hook: the shavings",
                "teaching_point": "Teeth chewing plastic",
                "shot": "close-up shot of filament shavings around an extruder gear",
                "motion": "camera zooms to the dust pile",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["shavings pile", "extruder gear", "dust"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of filament shavings around an extruder gear, bright task lighting, print lab",
            },
            {
                "goal": "The stall",
                "teaching_point": "Gear slips, feed stops",
                "shot": "diagram-style shot of the gear slipping on filament",
                "motion": "teeth spin and scrape",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["drive gear", "slipping filament", "shaving marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a slipping extruder gear, clean engineering visualization on a dark background",
            },
            {
                "goal": "The resistance",
                "teaching_point": "Clog, temp, or tangle",
                "shot": "diagram-style shot of resistance sources",
                "motion": "nozzle, heat, and spool light up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["clog icon", "temp icon", "tangle icon"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of grinding resistance sources, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Clear, heat, free",
                "shot": "close-up shot of clearing a nozzle and freeing a spool",
                "motion": "nozzle clears, spool spins free",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["cleared nozzle", "free spool", "clean gear"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of clearing a nozzle and freeing a tangled spool, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Root cause wins",
                "shot": "wide hero shot of a clean print from a healthy extruder",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["healthy extruder", "clean print", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean print from a healthy extruder, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A gear slipping on filament with shavings and resistance icons",
            "subject": "filament grinding",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gear center, icons around",
            "text": "FIX THE RESISTANCE, NOT THE GEAR",
            "elements": ["drive gear", "shavings", "clog icon"],
            "style": "geometry studio photography",
            "mood": "slipping, chewed, freed",
            "prompt": "photograph of an extruder gear slipping on filament with shavings and resistance icons around it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Filament Grinding: Fix the Resistance, Not the Gear",
            "title_variations": [
                "Why Is My Extruder Grinding",
                "Filament Grinding Fix",
                "Skipping Extruder",
                "Filament Shavings",
                "Extruder Gear Slip",
            ],
            "description": "Grinding happens when the extruder's gear cannot get traction: the drive teeth chew shavings out of the filament while the feed stalls, so the print under-extrudes and the gear slips. The causes are resistance upstream or downstream: a clogged nozzle, too-low temperature, or a tangled spool. The tell is shavings and a skipping sound. This short catches the dust, traces the resistance, and shows the fix: clear the nozzle, raise the heat, or free the spool.",
            "hashtags": ["#FilamentGrinding", "#Extruder", "#Skipping", "#3DPrinting"],
            "seo_keywords": [
                "why is my extruder grinding",
                "filament grinding",
                "skipping extruder",
                "filament shavings",
                "extruder gear slip",
                "clogged nozzle grind",
                "tangled spool extruder",
            ],
        },
        "fact_check": [
            "Grinding is lost traction.",
            "The gear chews shavings.",
            "A clog causes resistance.",
            "Low temperature causes it.",
            "A tangle causes it.",
        ],
    },
    {
        "topic": "Probe Accuracy & Repeatability",
        "core_question": "Can you trust what your probe says?",
        "learning_objective": "The viewer understands probe accuracy and repeatability.",
        "engineering_summary": "A probe can be wrong in two ways: accuracy is how close its readings are to the true height, and repeatability is how much the readings bounce between identical probes. Accuracy can be offset and fixed, but repeatability is the killer, because a probe that reads differently every time makes the mesh lie. The test is simple: probe one point dozens of times and watch the spread. A few hundredths of a millimeter of spread is normal; a few tenths means the probe is lying to your mesh. Trust is earned point by point.",
        "real_world_application": "Mesh quality is only as good as the probe's repeatability.",
        "common_misconceptions": [
            "Accuracy is what matters (repeatability decides the mesh's trust)",
            "One reading is enough (spread shows in repetition)",
            "Probes are perfect (they drift with temperature and wear)",
        ],
        "teaching_strategy": "Probe one point repeatedly and show the spread.",
        "script": "A probe can be wrong in two ways: accuracy is how close its readings are to the true height, and repeatability is how much the readings bounce between identical probes. Accuracy can be offset and fixed, but repeatability is the killer, because a probe that reads differently every time makes the mesh lie. The test is simple: probe one point dozens of times and watch the spread. A few hundredths of a millimeter of spread is normal; a few tenths means the probe is lying to your mesh. Trust is earned point by point.",
        "text_overlay": [
            "ACCURACY CAN BE OFFSET",
            "REPEATABILITY IS THE KILLER",
            "PROBE ONE POINT, DOZEN TIMES",
            "TRUST IS EARNED POINT BY POINT",
        ],
        "scenes": [
            {
                "goal": "Hook: the lying mesh",
                "teaching_point": "Mesh built on noise",
                "shot": "diagram-style shot of a noisy height map",
                "motion": "colors jump between probes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["noisy map", "jump colors", "mesh grid"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a diagram of a noisy height map, clean engineering visualization on a dark background",
            },
            {
                "goal": "The two words",
                "teaching_point": "Accuracy versus repeatability",
                "shot": "diagram-style shot of accuracy and repeatability targets",
                "motion": "shots cluster tight or drift off",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["accuracy target", "repeatability cluster", "spread"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of probe accuracy versus repeatability, clean engineering visualization on a dark background",
            },
            {
                "goal": "The test",
                "teaching_point": "Probe one point many times",
                "shot": "medium shot of a probe touching one spot repeatedly",
                "motion": "probe taps the same point",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["probing head", "same point", "tap rhythm"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a probe touching one point repeatedly, neutral lab lighting, print lab",
            },
            {
                "goal": "The spread",
                "teaching_point": "Hundredths versus tenths",
                "shot": "diagram-style shot of the reading spread graph",
                "motion": "readings fan out on the chart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["reading chart", "tight cluster", "wide spread"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of probe reading spread, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Trust the repeatable",
                "shot": "wide hero shot of a clean level print after a good probe",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "probe head", "level bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean print after a reliable probe, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A probe tapping one point with a tight and a wide spread chart",
            "subject": "probe accuracy repeatability",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "probe center, chart beside",
            "text": "TRUST IS EARNED POINT BY POINT",
            "elements": ["probe head", "tap point", "spread chart"],
            "style": "geometry studio photography",
            "mood": "tested, spread, trusted",
            "prompt": "photograph of a probe tapping one point with a tight and wide spread chart beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Probe Accuracy & Repeatability: Trust Is Earned Point by Point",
            "title_variations": [
                "How Accurate Is My Probe",
                "Probe Repeatability Test",
                "Z Probe Variance",
                "Leveling Quality Probe",
                "Probe Accuracy Guide",
            ],
            "description": "A probe can be wrong in two ways: accuracy is how close its readings are to the true height, and repeatability is how much the readings bounce between identical probes. Accuracy can be offset and fixed, but repeatability is the killer, because a probe that reads differently every time makes the mesh lie. The test is simple: probe one point dozens of times and watch the spread. This short taps the point, plots the spread, and shows when the probe is lying to your mesh.",
            "hashtags": ["#ProbeAccuracy", "#Repeatability", "#MeshLeveling", "#3DPrinting"],
            "seo_keywords": [
                "how accurate is my probe",
                "probe repeatability test",
                "z probe variance",
                "leveling quality probe",
                "probe accuracy",
                "mesh lies probe",
                "probe reading spread",
            ],
        },
        "fact_check": [
            "Accuracy is offsetable.",
            "Repeatability is critical.",
            "One point, many probes.",
            "Hundredths are normal.",
            "Tenths mean a lying probe.",
        ],
    },
    {
        "topic": "Gaps Between Walls",
        "core_question": "Why do thin dark lines appear inside your print walls?",
        "learning_objective": "The viewer understands gaps between walls.",
        "engineering_summary": "Gaps between walls are thin dark seams that show where wall loops and infill lines do not quite touch, often on curved or angled surfaces. The cause is usually under-extrusion in the tight corners, an overlap value that is too small, or walls printed with gaps where the geometry leaves a sliver too narrow for a line. The surface looks solid, but light finds the seams. The fixes are flow, overlap, and wall line counts: feed the slivers, fuse the lines, or cover the zone.",
        "real_world_application": "Curved parts and thin features show wall gaps that flat cubes never reveal.",
        "common_misconceptions": [
            "Gaps are a lighting trick (light only reveals the real seam)",
            "More walls always fix it (overlap and flow matter too)",
            "It is purely cosmetic (it hides structural weakness)",
        ],
        "teaching_strategy": "Show the dark seams, then the flow and overlap fixes.",
        "script": "Gaps between walls are thin dark seams that show where wall loops and infill lines do not quite touch, often on curved or angled surfaces. The cause is usually under-extrusion in the tight corners, an overlap value that is too small, or walls printed with gaps where the geometry leaves a sliver too narrow for a line. The surface looks solid, but light finds the seams. The fixes are flow, overlap, and wall line counts: feed the slivers, fuse the lines, or cover the zone.",
        "text_overlay": [
            "LIGHT FINDS THE SEAMS",
            "UNDER-EXTRUDED TIGHT CORNERS",
            "SLIVERS TOO NARROW FOR A LINE",
            "FEED, FUSE, OR COVER",
        ],
        "scenes": [
            {
                "goal": "Hook: the dark seams",
                "teaching_point": "Thin lines in the wall",
                "shot": "close-up shot of dark seam lines inside a curved wall",
                "motion": "light catches the thin gaps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["dark seams", "curved wall", "gap lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of dark seam lines inside a curved wall, bright task lighting, print lab",
            },
            {
                "goal": "The sliver",
                "teaching_point": "Too narrow for a line",
                "shot": "diagram-style shot of a gap too small for a wall",
                "motion": "sliver zone stays empty",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sliver zone", "wall loops", "empty gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a wall sliver gap, clean engineering visualization on a dark background",
            },
            {
                "goal": "The starve",
                "teaching_point": "Tight corners underfeed",
                "shot": "diagram-style shot of under-extrusion at a corner",
                "motion": "line thins as the corner bends",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thin line", "corner bend", "flow gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of corner under-extrusion, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fixes",
                "teaching_point": "Flow, overlap, walls",
                "shot": "diagram-style shot of fix levers",
                "motion": "flow, overlap, and wall count adjust",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flow lever", "overlap lever", "wall count lever"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of wall gap fix levers, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Solid through and through",
                "shot": "wide hero shot of a seamless curved part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["seamless part", "curved walls", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a seamless curved part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A curved wall with dark seams and flow, overlap, and wall levers",
            "subject": "gaps between walls",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "wall center, levers below",
            "text": "FEED, FUSE, OR COVER",
            "elements": ["dark seams", "curved wall", "fix levers"],
            "style": "geometry studio photography",
            "mood": "seamed, starved, fused",
            "prompt": "photograph of a curved wall with dark seams and flow, overlap, and wall levers, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Gaps Between Walls: Feed, Fuse, or Cover",
            "title_variations": [
                "Why Gaps Between Walls",
                "Wall Gaps Print Fix",
                "Infill Gaps Walls",
                "Perimeter Gaps",
                "Dark Seams Print Walls",
            ],
            "description": "Gaps between walls are thin dark seams where wall loops and infill lines do not quite touch, often on curved or angled surfaces. The cause is usually under-extrusion in tight corners, an overlap value too small, or slivers too narrow for a line. The fixes are flow, overlap, and wall line counts. This short lights the seams, finds the sliver, and shows how to feed the lines, fuse the zones, or cover the gap.",
            "hashtags": ["#WallGaps", "#PrintQuality", "#Overlap", "#3DPrinting"],
            "seo_keywords": [
                "why gaps between walls",
                "wall gaps print fix",
                "infill gaps walls",
                "perimeter gaps",
                "dark seams walls",
                "wall overlap fix",
                "sliver gap print",
            ],
        },
        "fact_check": [
            "Gaps show as dark seams.",
            "Tight corners underfeed.",
            "Overlap may be too small.",
            "Slivers are too narrow.",
            "Flow and wall count fix it.",
        ],
    },
    {
        "topic": "Overheating Small Parts",
        "core_question": "Why do tiny prints look like melted candles?",
        "learning_objective": "The viewer understands small part overheating.",
        "engineering_summary": "Small parts overheat because each layer is done before the plastic cools: the nozzle returns to hot plastic, the heat builds, and the part softens, blobs, and leans. The slicer counters with minimum layer time, which slows or pauses the head so each layer gets a cooldown, plus fan speed, which pulls the heat away faster. Two small parts can also be printed apart so each layer takes longer. The melt is a heat budget, and the budget is time and airflow.",
        "real_world_application": "Pins, text, and miniatures are all heat-budget problems.",
        "common_misconceptions": [
            "Small parts are fast wins (they need the slowest layers)",
            "The fan alone fixes it (dwell time matters too)",
            "It is a material issue (any filament melts without cooling)",
        ],
        "teaching_strategy": "Show a melted pin, then the layer clock and fan budget saving it.",
        "script": "Small parts overheat because each layer is done before the plastic cools: the nozzle returns to hot plastic, the heat builds, and the part softens, blobs, and leans. The slicer counters with minimum layer time, which slows or pauses the head so each layer gets a cooldown, plus fan speed, which pulls the heat away faster. Two small parts can also be printed apart so each layer takes longer. The melt is a heat budget, and the budget is time and airflow.",
        "text_overlay": [
            "LAYERS FASTER THAN COOLING",
            "HEAT BUILDS, PART LEANS",
            "MINIMUM LAYER TIME SLOWS",
            "TIME AND AIRFLOW BUDGET",
        ],
        "scenes": [
            {
                "goal": "Hook: the melted pin",
                "teaching_point": "Hot plastic, soft part",
                "shot": "close-up shot of a melted leaning pin on a print",
                "motion": "camera circles the soft column",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["melted pin", "lean", "blobs"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a melted leaning pin on a print, bright task lighting, print lab",
            },
            {
                "goal": "The budget",
                "teaching_point": "Heat in, heat out",
                "shot": "diagram-style shot of a heat budget gauge",
                "motion": "heat in outruns heat out",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heat in arrow", "heat out arrow", "budget gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a layer heat budget, clean engineering visualization on a dark background",
            },
            {
                "goal": "The clock",
                "teaching_point": "Layer time enforced",
                "shot": "diagram-style shot of a layer clock slowing the head",
                "motion": "head dwells until the clock clears",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer clock", "slow head", "dwell mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of minimum layer time enforcement, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fan",
                "teaching_point": "Air pulls the heat",
                "shot": "diagram-style shot of fan airflow over the part",
                "motion": "air stream carries heat away",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fan stream", "small part", "heat exit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fan cooling on a small part, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Spend the budget",
                "shot": "wide hero shot of a crisp small part set",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["crisp small parts", "cooling fan", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a crisp small part set with a cooling fan, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A melted pin beside a layer clock and a fan stream",
            "subject": "overheating small parts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pin center, clock and fan beside",
            "text": "TIME AND AIRFLOW BUDGET",
            "elements": ["melted pin", "layer clock", "fan stream"],
            "style": "geometry studio photography",
            "mood": "melted, budgeted, cooled",
            "prompt": "photograph of a melted pin beside a layer clock and a fan air stream, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Overheating Small Parts: A Time and Airflow Budget",
            "title_variations": [
                "Why Do Small Prints Overheat",
                "Small Part Overheating Fix",
                "Blobby Details Fix",
                "Minimum Layer Time Small Parts",
                "Melted Print Fix",
            ],
            "description": "Small parts overheat because each layer is done before the plastic cools: the nozzle returns to hot plastic, the heat builds, and the part softens, blobs, and leans. The slicer counters with minimum layer time, which slows or pauses the head so each layer gets a cooldown, plus fan speed, which pulls the heat away faster. This short melts a pin, sets the clock, and shows the melt as a heat budget of time and airflow.",
            "hashtags": ["#Overheating", "#LayerTime", "#Cooling", "#3DPrinting"],
            "seo_keywords": [
                "why do small prints overheat",
                "small part overheating",
                "blobby details fix",
                "minimum layer time",
                "melted print fix",
                "small part cooling budget",
                "pins text miniatures heat",
            ],
        },
        "fact_check": [
            "Small layers finish too fast.",
            "Heat builds in the part.",
            "Minimum layer time helps.",
            "Fan speed pulls heat away.",
            "Spacing parts extends layers.",
        ],
    },
    {
        "topic": "Print-in-Place Failures",
        "core_question": "Why did your hinge print into one solid block?",
        "learning_objective": "The viewer understands print-in-place failures.",
        "engineering_summary": "Print-in-place parts are made assembled, with joints that must stay separated by a hair: the clearance gap is the whole mechanism. When the gap is too small the layers weld together and the hinge becomes a block; when it is too big the joint rattles and wobbles. The slicer also matters: flow that bulges by a few hundredths closes the gap, and drooping bridges sag into the joint. The tolerance is a three-way agreement between the model's gap, the printer's accuracy, and the slicer's flow.",
        "real_world_application": "Hinges, boxes, and articulated models live or die by the joint gap.",
        "common_misconceptions": [
            "Bigger gaps are safer (they rattle and look bad)",
            "It is only a model problem (flow and droop close the gap)",
            "All printers hold the same tolerance (accuracy varies)",
        ],
        "teaching_strategy": "Show a fused joint, then the gap, flow, and droop fixes.",
        "script": "Print-in-place parts are made assembled, with joints that must stay separated by a hair: the clearance gap is the whole mechanism. When the gap is too small the layers weld together and the hinge becomes a block; when it is too big the joint rattles and wobbles. The slicer also matters: flow that bulges by a few hundredths closes the gap, and drooping bridges sag into the joint. The tolerance is a three-way agreement between the model's gap, the printer's accuracy, and the slicer's flow.",
        "text_overlay": [
            "THE GAP IS THE MECHANISM",
            "TOO SMALL WELDS, TOO BIG RATTLES",
            "FLOW AND DROOP CLOSE GAPS",
            "A THREE-WAY AGREEMENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the fused hinge",
                "teaching_point": "One solid block",
                "shot": "close-up shot of a fused print-in-place hinge",
                "motion": "camera tries to flex the block",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["fused hinge", "solid block", "frozen joint"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a fused print-in-place hinge, bright task lighting, print lab",
            },
            {
                "goal": "The hair",
                "teaching_point": "Clearance gap by design",
                "shot": "diagram-style shot of the joint clearance gap",
                "motion": "gap dimension marks the joint",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["clearance gap", "joint halves", "gap arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a print-in-place clearance gap, clean engineering visualization on a dark background",
            },
            {
                "goal": "The weld",
                "teaching_point": "Flow closes the gap",
                "shot": "diagram-style shot of bulging flow welding the joint",
                "motion": "lines grow and touch",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bulging lines", "joint gap", "weld point"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flow welding a joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sag",
                "teaching_point": "Bridges droop into it",
                "shot": "diagram-style shot of a sagging bridge into a joint",
                "motion": "strand dips into the gap",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sagging strand", "joint zone", "droop"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a sagging bridge into a joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Three-way agreement",
                "shot": "wide hero shot of a working articulated print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["working hinge", "articulated part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a working articulated print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A fused hinge beside a clearance gap with flow and sag arrows",
            "subject": "print-in-place failures",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "hinge center, gap diagram beside",
            "text": "THE GAP IS THE MECHANISM",
            "elements": ["fused hinge", "clearance gap", "flow arrows"],
            "style": "geometry studio photography",
            "mood": "fused, gapped, agreed",
            "prompt": "photograph of a fused hinge beside a clearance gap with flow and sag arrows, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Print-in-Place Failures: The Gap Is the Mechanism",
            "title_variations": [
                "Why Does Print in Place Stick",
                "Print in Place Fused Fix",
                "Print in Place Clearance",
                "Stuck Joints Print",
                "Articulated Print Failures",
            ],
            "description": "Print-in-place parts are made assembled, with joints that must stay separated by a hair: the clearance gap is the whole mechanism. When the gap is too small the layers weld together and the hinge becomes a block; when it is too big the joint rattles. Flow that bulges closes the gap, and drooping bridges sag into it. This short fuses a hinge, marks the gap, and shows the three-way agreement between model, printer, and slicer.",
            "hashtags": ["#PrintInPlace", "#Clearance", "#Hinges", "#3DPrinting"],
            "seo_keywords": [
                "why does print in place stick",
                "print in place fused",
                "print in place clearance",
                "stuck joints print",
                "articulated print failures",
                "hinge gap tolerance",
                "print in place flow",
            ],
        },
        "fact_check": [
            "The gap is the mechanism.",
            "Small gaps weld layers.",
            "Big gaps rattle joints.",
            "Flow closes the gap.",
            "Drooping bridges close it.",
        ],
    },
    {
        "topic": "Flow Test Method",
        "core_question": "What is the quickest honest way to check your flow?",
        "learning_objective": "The viewer understands flow test methods.",
        "engineering_summary": "The honest flow test measures walls, not looks: print a single-wall cube with no infill and no top, then measure the walls with calipers and divide the expected width by the actual one. The result is the multiplier that corrects every extrusion in the slicer. The single-wall design is the point: one line carries the whole signal, so the reading is clean. The test takes one print and one measurement, and it is the difference between guessing and knowing.",
        "real_world_application": "The single-wall cube is the standard flow test across slicer communities.",
        "common_misconceptions": [
            "Surface looks are the test (looks lie, calipers do not)",
            "Any cube works (infill and top pollute the reading)",
            "One reading is enough (measure multiple walls and average)",
        ],
        "teaching_strategy": "Print the single-wall cube, measure it, and compute the multiplier.",
        "script": "The honest flow test measures walls, not looks: print a single-wall cube with no infill and no top, then measure the walls with calipers and divide the expected width by the actual one. The result is the multiplier that corrects every extrusion in the slicer. The single-wall design is the point: one line carries the whole signal, so the reading is clean. The test takes one print and one measurement, and it is the difference between guessing and knowing.",
        "text_overlay": [
            "SINGLE WALL, NO INFILL, NO TOP",
            "MEASURE, THEN DIVIDE",
            "ONE LINE CARRIES THE SIGNAL",
            "GUESSING VERSUS KNOWING",
        ],
        "scenes": [
            {
                "goal": "Hook: the thin cube",
                "teaching_point": "One wall carries the truth",
                "shot": "close-up shot of a single-wall test cube",
                "motion": "light shines through the thin walls",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["test cube", "single walls", "hollow top"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a single-wall test cube, bright task lighting, workbench",
            },
            {
                "goal": "The design",
                "teaching_point": "No infill, no top",
                "shot": "diagram-style shot of the test cube settings",
                "motion": "wall count one, infill zero",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["one wall", "zero infill", "no top"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flow test cube settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "The measure",
                "teaching_point": "Caliper on the walls",
                "shot": "close-up shot of calipers reading a test cube wall",
                "motion": "jaws close on the thin wall",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper jaws", "thin wall", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of calipers reading a test cube wall, bright task lighting, workbench",
            },
            {
                "goal": "The math",
                "teaching_point": "Expected over actual",
                "shot": "diagram-style shot of the flow formula",
                "motion": "expected divided by actual",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["expected width", "actual width", "flow result"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the flow test formula, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Know, do not guess",
                "shot": "wide hero shot of a calibrated print beside the test cube",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["calibrated print", "test cube", "caliper"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a calibrated print beside a test cube, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A single-wall cube with calipers and the expected-over-actual formula",
            "subject": "flow test method",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cube center, formula above",
            "text": "GUESSING VERSUS KNOWING",
            "elements": ["test cube", "caliper", "flow formula"],
            "style": "geometry studio photography",
            "mood": "measured, divided, known",
            "prompt": "photograph of a single-wall test cube with calipers and the flow formula above it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Flow Test Method: Guessing Versus Knowing",
            "title_variations": [
                "How to Run a Flow Test",
                "Single Wall Flow Test",
                "Wall Thickness Test",
                "Flow Cube Method",
                "Extrusion Flow Test Guide",
            ],
            "description": "The honest flow test measures walls, not looks: print a single-wall cube with no infill and no top, then measure the walls with calipers and divide the expected width by the actual one. The result is the multiplier that corrects every extrusion in the slicer. The single-wall design is the point: one line carries the whole signal. This short prints the cube, reads the walls, and does the one-line math that turns guessing into knowing.",
            "hashtags": ["#FlowTest", "#Calibration", "#SingleWall", "#3DPrinting"],
            "seo_keywords": [
                "how to run a flow test",
                "single wall flow test",
                "wall thickness test",
                "flow cube",
                "extrusion flow test",
                "expected over actual",
                "flow multiplier cube",
            ],
        },
        "fact_check": [
            "Flow tests measure walls.",
            "Single-wall cubes isolate it.",
            "No infill or top pollutes.",
            "Divide expected by actual.",
            "One print, one measurement.",
        ],
    },
]