"""Batch 10: vertical artifacts, top-surface fixes, infill patterns, precision tools, welding, motors, and balance."""

CURATED = [
    # ======================================================================
    {
        "topic": "Z-Banding",
        "core_question": "Why do my prints have ribbed vertical stripes, and how do I fix z-banding?",
        "learning_objective": "The viewer can distinguish z-banding from other artifacts, and fix leadscrew, binding, and temperature causes.",
        "engineering_summary": "Z-banding is a periodic ribbed pattern along the print height, caused by the z-axis moving in uneven increments. The usual suspects: (1) a bent or low-quality leadscrew whose wobble repeats every revolution; (2) z-axis binding - misaligned lead screw nuts, tight z rails, or flexing couplings that make some steps taller; (3) periodic temperature oscillation, usually from a poorly tuned PID loop, changing layer width with the same rhythm; (4) layer-height rounding in the slicer. The pattern spacing identifies the source: a repeat equal to the screw pitch means leadscrew; a slow wobble that changes with print speed means temperature. Fixes: quality lead screws, proper z coupling, PID tuning, and even z steps.",
        "real_world_application": "Cosmetic enclosures and mechanical parts both suffer: print farms check z-banding first in the mechanical stack, because temperature and leadscrew causes need different repairs.",
        "common_misconceptions": [
            "Z-banding is a slicer setting (it is mechanical or thermal, not g-code)",
            "It's the same as ringing (ringing repeats near corners in x-y; z-banding runs along the height)",
            "Lubrication always fixes it (wobble is geometry, not friction; binding is alignment)",
        ],
        "teaching_strategy": "Show a banded print, measure the band spacing, then map the pattern to its cause with the fix for each.",
        "script": "Ribbed stripes marching up the print are z-banding: the z-axis moves unevenly, and every layer records it. Measure the spacing - that's the fingerprint. Spacing equals the screw pitch? The lead screw is bent or wobbling. Does it change with print speed? Suspect temperature oscillation - the PID loop breathing the nozzle hot and cold. Tight, binding z rails squeeze steps too, and a floppy coupling makes it worse. The fixes: straight screws, aligned nut, tuned PID, even steps. Measure the rhythm, name the cause, kill the banding.",
        "text_overlay": [
            "RHYTHM = THE FINGERPRINT",
            "SCREW PITCH = LEADSCREW",
            "SPEED-DEPENDENT = PID TEMP",
            "ALIGN, TUNE, STRAIGHTEN",
        ],
        "scenes": [
            {
                "goal": "Hook: the striped print",
                "teaching_point": "Periodic ribs along the height",
                "shot": "wide shot of a tall print with visible z-banding",
                "motion": "slow tilt up the ribs",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["banded print", "periodic ribs"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a tall 3D print with visible z-banding ribs, raking side light, dark bench",
            },
            {
                "goal": "The leadscrew",
                "teaching_point": "Bent screws wobble every turn",
                "shot": "macro shot of a lead screw wobbling beside a straight one",
                "motion": "wobble exaggerated in slow motion",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["lead screw", "straight screw", "wobble"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a wobbly lead screw beside a straight one on a printer, bright task lighting, print lab",
            },
            {
                "goal": "The coupling",
                "teaching_point": "Floppy couplings translate wobble",
                "shot": "close-up of a z coupling flexing between motor and screw",
                "motion": "coupling bends with the screw",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["z coupling", "motor shaft", "lead screw"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a z-axis coupling flexing between motor and lead screw, bright task lighting, print lab",
            },
            {
                "goal": "Temperature oscillation",
                "teaching_point": "PID breathing changes layer width",
                "shot": "graphic-style shot of a temperature trace oscillating with layer rhythm",
                "motion": "temp curve waves in sync with layers",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temperature trace", "layer diagram", "PID curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a temperature oscillation trace synchronized with a layer diagram on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Measure the rhythm, fix the cause",
                "shot": "wide hero shot of a smooth tall print completing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth tall print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth tall 3D print completing on the printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A striped print with a measuring scale on the ribs",
            "subject": "banded print with a spacing scale",
            "background": "dark print lab blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "banded print left, scale right",
            "text": "Z-BANDING?",
            "elements": ["banded print", "spacing scale", "ribs"],
            "style": "diagnostic studio photography",
            "mood": "ribbed, diagnostic, analytical",
            "prompt": "photograph of a z-banded 3D print with a spacing measurement scale beside it, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Z-Banding: Read the Rhythm",
            "title_variations": [
                "Why Prints Have Ribbed Stripes",
                "Fix Z-Banding",
                "Leadscrew Wobble Explained",
                "Z-Banding vs Ringing",
                "Vertical Ribbing Fix",
            ],
            "description": "Z-banding is a periodic ribbed pattern along the print height, and the spacing is the fingerprint. If the repeat equals the lead screw pitch, the screw is bent or wobbling; if the pattern changes with print speed, suspect PID temperature oscillation changing layer width; binding z rails squeeze steps, and floppy couplings translate motor wobble into the screw. The fixes are straight screws, an aligned nut, a proper z coupling, PID tuning, and even z steps. This short teaches you to measure the rhythm and map it to the right repair, because temperature and mechanical causes need different fixes.",
            "hashtags": ["#ZBanding", "#3Dprinting", "#Troubleshooting", "#Quality"],
            "seo_keywords": [
                "z banding fix",
                "ribbed 3d print",
                "leadscrew wobble",
                "z banding vs ringing",
                "vertical stripes 3d print",
                "z axis binding",
                "PID temperature oscillation",
            ],
        },
        "fact_check": [
            "Z-banding repeats at a spatial frequency tied to the z-axis mechanics or temperature cycle.",
            "A repeat matching the lead screw pitch indicates screw wobble or bend.",
            "Speed-dependent banding suggests thermal oscillation from PID tuning.",
            "Z-axis binding and misaligned couplings produce irregular or periodic layer height errors.",
            "Ringing is an x-y resonance artifact near features; z-banding runs along the full height.",
        ],
    },
    # ======================================================================
    {
        "topic": "Pillowing",
        "core_question": "Why is my top surface bumpy, and how do I fix pillowing?",
        "learning_objective": "The viewer can diagnose pillowing as sagging top layers and fix it with top layers, infill, and cooling.",
        "engineering_summary": "Pillowing is a bumpy, quilted top surface: the first top layers sag into the gaps between infill lines before they solidify, and each later layer mirrors the bumps. It happens when top layers are too few, infill spacing is too wide, or cooling is too weak to freeze the sagging plastic. Fixes in order: increase top layer count until the bridge over infill is solid; reduce infill spacing (higher density or a pattern with closer walls) so the sag spans are shorter; increase cooling and slow the top layers so the plastic sets before it droops. Top surfaces over sparse infill or large internal voids are the classic trigger.",
        "real_world_application": "Enclosure lids, lids, and display surfaces must look clean; print farms check pillowing when a part's top shows quilting and fix the profile rather than the part.",
        "common_misconceptions": [
            "Pillowing is a filament problem (it is geometry and cooling, not material)",
            "More infill percentage is the only fix (top layer count and cooling matter equally)",
            "It only affects looks (bumpy tops ruin sealing surfaces and stacking fit)",
        ],
        "teaching_strategy": "Show the quilted top, cut through it to reveal sagging layers, then the three fixes in order.",
        "script": "A quilted, bumpy top is pillowing: the first top layers sag into the infill gaps before they harden, and every layer after copies the bumps. Three levers. One: top layers - add enough solid plastic to bridge the pattern. Two: infill - closer lines mean shorter spans that can't sag as far. Three: cooling and speed - freeze the plastic before it droops. Wide voids under the top are the classic trigger, so a denser pattern near surfaces beats a sparse one. Sag, copy, repeat: break the chain anywhere and the top flattens out.",
        "text_overlay": [
            "SAG, COPY, REPEAT",
            "1. MORE TOP LAYERS",
            "2. CLOSER INFILL",
            "3. COOL + SLOW",
        ],
        "scenes": [
            {
                "goal": "Hook: the quilted top",
                "teaching_point": "Bumps mirror the sag below",
                "shot": "macro close-up of a pillowed top surface",
                "motion": "slow push-in on the bumps",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["pillowed top", "quilted bumps"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D print with a pillowed quilted top surface, raking side light, dark bench",
            },
            {
                "goal": "The cutaway",
                "teaching_point": "Top layers sag into infill gaps",
                "shot": "graphic-style shot of a cut part showing sagging first top layers",
                "motion": "layers droop into the gaps",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cut part diagram", "sagging layers", "infill gaps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a cut part diagram with top layers sagging into infill gaps on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The top layer fix",
                "teaching_point": "Solid plastic bridges the pattern",
                "shot": "tablet-style graphic showing top layer count and surface quality",
                "motion": "layer count rises, surface flattens",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["settings tablet", "top layer counts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a top layer count tablet showing surface quality improvement, even diffused lighting, dark studio",
            },
            {
                "goal": "The infill fix",
                "teaching_point": "Shorter spans sag less",
                "shot": "macro shot of two top surfaces: sparse and dense infill",
                "motion": "cross-cut between the two tops",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["sparse infill top", "dense infill top"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of two printed tops showing sparse infill pillowing and dense infill flat, bright task light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Break the sag chain anywhere",
                "shot": "wide hero shot of a part with a mirror-flat top surface",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flat top part", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D print with a mirror-flat top surface, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A quilted top beside a flat top with three fix levers",
            "subject": "pillowed and flat printed tops",
            "background": "dark print lab blur",
            "angle": "top-down macro",
            "lighting": "hard key with rim",
            "composition": "pillowed left, flat right, levers center",
            "text": "FIX PILLOWING",
            "elements": ["pillowed top", "flat top", "fix levers"],
            "style": "diagnostic macro photography",
            "mood": "bumpy, corrective, clear",
            "prompt": "macro photograph of a pillowed 3D print top beside a flat top with three fix labels between them, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Pillowing: Flatten the Top",
            "title_variations": [
                "Why Is My Top Layer Bumpy",
                "Fix Pillowing",
                "Quilted Top Surface Fix",
                "Top Surface Smoothing",
                "Pillowing Explained",
            ],
            "description": "Pillowing is a bumpy, quilted top surface caused by the first top layers sagging into infill gaps before they solidify - and every layer after copies the bumps. Three levers fix it: more top layers to bridge the infill pattern, closer infill spacing so the sag spans are shorter, and stronger cooling with slower top-layer speed so the plastic sets before it droops. Wide internal voids under the top are the classic trigger. This short cuts through a pillowed part to show the sag-copy-repeat chain and gives the three fixes in order.",
            "hashtags": ["#Pillowing", "#3Dprinting", "#Quality", "#TopSurface"],
            "seo_keywords": [
                "pillowing fix",
                "bumpy top layer",
                "quilted top 3d print",
                "top surface pillowing",
                "top layer sagging",
                "infill shows through top",
                "smooth top surface fix",
            ],
        },
        "fact_check": [
            "Pillowing starts when unsupported top layers sag into infill gaps before solidifying.",
            "Increasing top layer count provides a solid bridge over the infill pattern.",
            "Denser infill or closer walls shorten the spans the top layers must bridge.",
            "Stronger cooling and lower top-layer speed reduce sag during solidification.",
            "Large internal voids below a top surface are the classic pillowing trigger.",
        ],
    },
    # ======================================================================
    {
        "topic": "Infill Pattern Comparisons",
        "core_question": "Which infill pattern is actually strongest?",
        "learning_objective": "The viewer can compare gyroid, cubic, grid, and line patterns by strength, isotropy, and speed, and pick for the load.",
        "engineering_summary": "Infill patterns differ in strength per gram, directionality, and print speed. Gyroid is the engineering favorite: a triply periodic surface with no flat layers, giving near-isotropic strength, good energy absorption, and even stress distribution - at a small speed cost. Cubic builds stacked cubes for strong vertical structure but leaves 45-degree weak zones and takes time. Grid is fast, but its crossing lines create stress concentration at intersections and strong directional anisotropy. Lines and triangles are cheap and fine for light duty. Rule of thumb: gyroid for structural parts and impact, cubic for tall columns, grid for speed and low-load parts.",
        "real_world_application": "Functional brackets and drone parts ship with gyroid infill; print farms reserve grid and lightning for cosmetic parts where infill is invisible and time is money.",
        "common_misconceptions": [
            "The strongest pattern is strongest everywhere (patterns are directional; gyroid is the isotropic exception)",
            "Dense infill removes pattern differences (pattern matters most at 20-40% where parts actually print)",
            "Pattern choice is cosmetic (strength, energy absorption, and printing time all change)",
        ],
        "teaching_strategy": "Show compression and torsion tests across patterns, the stress distribution diagrams, then a decision table by load type.",
        "script": "Which infill is strongest? It depends on the direction, and that's the secret. Grid crosses lines, fast to print, but stress collects where lines intersect and it's weak along one axis. Cubic stacks solid cubes: strong columns, but angled weak zones and slow printing. Gyroid is the engineer's choice: a curved surface in every direction, near-isotropic, and it absorbs impacts instead of cracking. For real loads and drops: gyroid. For tall columns: cubic. For speed and light duty: grid. Match the pattern to the load, not the hype.",
        "text_overlay": [
            "GRID: FAST, DIRECTIONAL",
            "CUBIC: COLUMNS + SLOW",
            "GYROID: ALL DIRECTIONS",
            "IMPACT? GYROID",
        ],
        "scenes": [
            {
                "goal": "Hook: the pattern family",
                "teaching_point": "Patterns differ in structure and strength",
                "shot": "tabletop shot of grid, cubic, and gyroid infill samples",
                "motion": "camera slides across the samples",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["grid sample", "cubic sample", "gyroid sample"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of grid, cubic, and gyroid infill pattern samples on a dark studio table, even diffused lighting",
            },
            {
                "goal": "Grid's weakness",
                "teaching_point": "Intersections concentrate stress",
                "shot": "graphic-style shot of a grid pattern with stress hot spots",
                "motion": "stress glows at the intersections",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["grid diagram", "stress spots", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a grid infill diagram with stress concentrating at line intersections on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Gyroid's secret",
                "teaching_point": "Curved surface in every direction",
                "shot": "macro shot of a gyroid lattice with light passing through",
                "motion": "slow orbit around the lattice",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["gyroid lattice", "curved surfaces"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a gyroid infill lattice with light passing through the curved surfaces, bright task light, dark bench",
            },
            {
                "goal": "The tests",
                "teaching_point": "Compression and torsion tell the story",
                "shot": "tabletop shot of a torsion test on two pattern cubes",
                "motion": "cubes twist until failure",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["test cubes", "torsion rig", "dial gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a torsion test on infill pattern test cubes, neutral lab lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match pattern to load",
                "shot": "wide hero shot of a structural bracket with gyroid infill cut open",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["structural bracket", "gyroid cutaway"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a structural 3D printed bracket with a gyroid infill cutaway, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three infill patterns with load arrows showing directionality",
            "subject": "grid, cubic, and gyroid samples with arrows",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "three samples in a row, arrows over",
            "text": "INFILL MATTERS",
            "elements": ["grid sample", "cubic sample", "gyroid sample", "arrows"],
            "style": "industrial macro photography",
            "mood": "structural, comparative, clear",
            "prompt": "macro photograph of grid, cubic, and gyroid infill samples with load arrows over them, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Infill Patterns: Which Wins?",
            "title_variations": [
                "Gyroid vs Grid vs Cubic",
                "Strongest Infill Pattern",
                "Infill Pattern Comparison",
                "Which Infill Should I Use",
                "Infill Strength Explained",
            ],
            "description": "Infill patterns differ in strength per gram, directionality, and speed. Grid is fast but concentrates stress at line intersections and is weak along one axis. Cubic stacks strong columns with angled weak zones and prints slowly. Gyroid is the engineering favorite: a curved surface in every direction, near-isotropic, absorbing impacts instead of cracking. The rule: gyroid for structural parts and drops, cubic for tall columns, grid for speed and light duty. This short shows the patterns, the stress distributions, and the tests, then gives a decision table by load type.",
            "hashtags": ["#Infill", "#3Dprinting", "#Strength", "#Patterns"],
            "seo_keywords": [
                "gyroid vs grid vs cubic",
                "strongest infill pattern",
                "infill pattern comparison",
                "best infill for strength",
                "gyroid infill explained",
                "infill anisotropy",
                "infill energy absorption",
            ],
        },
        "fact_check": [
            "Gyroid infill is near-isotropic with good energy absorption across directions.",
            "Grid infill concentrates stress at line intersections and is directionally weak.",
            "Cubic infill forms vertical columns with 45-degree weak zones and slower printing.",
            "Pattern differences are most significant at practical 20-40% infill densities.",
            "Strength per gram varies strongly between patterns at the same density.",
        ],
    },
    # ======================================================================
    {
        "topic": "Ironing: What It Does",
        "core_question": "What does ironing do, and when is it worth the time?",
        "learning_objective": "The viewer can explain the ironing pass, tune its settings, and know when it pays off.",
        "engineering_summary": "Ironing is a slicer feature that runs the hot nozzle across the finished top surface with no extrusion, melting the top layers' peaks and dragging the plastic flat like an iron. The result is a smooth, near-injection-molded top surface. Cost: print time increases because the ironing pass covers every top surface, sometimes 20-40% longer. Tuning knobs: ironing flow (5-10% of normal, just enough to melt peaks), ironing speed (slow, around 20-30 mm/s), and spacing between passes. Ironing shines on flat horizontal tops; it wastes time on textured or curved surfaces where the nozzle drags on details. Silk and glossy filaments can show ironing streaks.",
        "real_world_application": "Display pieces, lids, and phone cases get glass-like tops with ironing; production shops enable it selectively per model because the time cost is real.",
        "common_misconceptions": [
            "Ironing extrudes plastic (it melts existing plastic with a dry pass)",
            "More flow irons better (excess flow builds blobs instead of flattening)",
            "Ironing is free (top-heavy parts can gain 20-40% print time)",
        ],
        "teaching_strategy": "Show an ironed top beside a raw top, the dry-pass mechanism, then the settings and the cost trade-off.",
        "script": "Ironing turns a ribbed top into a smooth plate: the hot nozzle crosses the finished surface dry, melting the layer peaks and dragging them flat, like a real iron on fabric. The flow is tiny - a fraction of normal - just enough to melt the ridges. The speed is slow, and the passes overlap slightly. The trade-off is time: every top surface gets a second trip, and flat-topped parts can print a third slower. Worth it? Flat cosmetic tops, yes. Curved parts with details, no. Silk filaments streak. Match the iron to the surface.",
        "text_overlay": [
            "DRY HOT PASS = IRON",
            "FLOW ~5-10%, SLOW SPEED",
            "FLAT TOPS: YES",
            "CURVES + SILK: NO",
        ],
        "scenes": [
            {
                "goal": "Hook: before and after",
                "teaching_point": "One feature, two tops",
                "shot": "macro shot of a part with a raw top and an ironed top",
                "motion": "camera pans between the halves",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["raw top", "ironed top", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D print with a raw top on one half and an ironed top on the other, raking side light, dark bench",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Dry pass melts peaks flat",
                "shot": "graphic-style shot of a nozzle dragging across layer peaks",
                "motion": "peaks melt and flatten under the nozzle",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle diagram", "layer peaks", "flattened surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle ironing diagram dragging across layer peaks on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The settings",
                "teaching_point": "Low flow, slow speed, close passes",
                "shot": "tablet-style graphic showing the three tuning knobs",
                "motion": "knobs adjust in sequence",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["settings tablet", "ironing knobs"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an ironing settings tablet with flow, speed, and spacing knobs, even diffused lighting, dark studio",
            },
            {
                "goal": "The time cost",
                "teaching_point": "Flat tops print slower",
                "shot": "tablet-style graphic comparing print time with and without ironing",
                "motion": "time bar grows for ironed part",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["time comparison", "ironed part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a print time comparison graphic with and without ironing on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the iron to the surface",
                "shot": "wide hero shot of a glass-smooth ironed lid part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["ironed lid", "smooth top"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printed lid with a glass-smooth ironed top surface, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle gliding over a top surface with a smooth trail",
            "subject": "nozzle ironing a print top",
            "background": "dark print lab blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "nozzle top, smooth trail behind",
            "text": "IRONING 101",
            "elements": ["nozzle", "ironed trail", "smooth top"],
            "style": "industrial macro photography",
            "mood": "smooth, glassy, precise",
            "prompt": "macro photograph of a nozzle ironing a 3D print top with a smooth trail behind it, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Ironing: Smooth Tops Explained",
            "title_variations": [
                "What Does Ironing Do",
                "Ironing Settings Guide",
                "Glass Smooth Top Layer",
                "Ironing vs More Top Layers",
                "Smooth Print Tops",
            ],
            "description": "Ironing is a slicer feature that runs the hot nozzle across the finished top surface with no extrusion, melting the layer peaks and dragging the plastic flat like an iron. The flow is a fraction of normal - just enough to melt ridges - with slow speed and overlapping passes. The cost is time: every top surface gets a second trip, and flat-topped parts can print 20-40% slower. Ironing shines on flat cosmetic tops, wastes time on curved or detailed surfaces, and can streak silk and glossy filaments. This short explains the mechanism, the tuning knobs, and when to enable it.",
            "hashtags": ["#Ironing", "#3Dprinting", "#Settings", "#SurfaceFinish"],
            "seo_keywords": [
                "ironing 3d print",
                "ironing settings",
                "smooth top layer",
                "what does ironing do",
                "ironing flow speed",
                "glass smooth print top",
                "ironing vs top layers",
            ],
        },
        "fact_check": [
            "Ironing melts existing top-layer peaks with a dry nozzle pass, without extruding.",
            "Typical ironing flow is 5-10% of normal extrusion to melt peaks without building blobs.",
            "Ironing speed is low, around 20-30 mm/s, with overlapping pass spacing.",
            "Ironing adds 20-40% time on parts with large flat top surfaces.",
            "Silk and glossy filaments can show visible streaks from the ironing pass.",
        ],
    },
    # ======================================================================
    {
        "topic": "Micrometers",
        "core_question": "How do I use a micrometer for real precision?",
        "learning_objective": "The viewer can read a micrometer scale, measure with correct technique, and avoid the classic errors.",
        "engineering_summary": "A micrometer measures to 0.01 mm (or 0.0001 inch): a precision screw with a 0.5 mm pitch turns a thimble with 50 divisions, each division moving the spindle 0.01 mm. Reading combines the barrel's 0.5 mm scale with the thimble's hundredths. Technique is everything: wipe the part clean, use the ratchet stop to apply consistent measuring force (never crank the thimble), measure at the widest point, and keep the micrometer at 20 C - the frame expands with heat. Calibration: zero the instrument against its standard anvil, and check it periodically. Micrometers excel where calipers run out of resolution.",
        "real_world_application": "Bearing journals, gear bores, and printer z-screws are measured with micrometers; a 0.01 mm difference decides a press fit from a slip fit.",
        "common_misconceptions": [
            "A micrometer is a fancy caliper (different mechanism, different resolution, different technique)",
            "More force means better contact (the ratchet sets consistent force; cranking distorts the frame)",
            "Readings are true at any temperature (thermal expansion shifts the frame and the part)",
        ],
        "teaching_strategy": "Show the scale anatomy, a wrong and right measurement technique, then the zero-check and a real press-fit decision.",
        "script": "A micrometer is a precision screw: half a millimeter per turn, fifty divisions on the thimble, and every division is a hundredth of a millimeter. Reading is easy once you see the two scales. Technique is the hard part. Clean the part. Use the ratchet stop, never the thimble, so every measurement presses with the same force. Measure at the widest point. And respect temperature: a warm frame lies to you. Zero it against the anvil first, and trust hundredths only when the ritual is right. Calipers for tenths, mics for hundredths.",
        "text_overlay": [
            "0.5MM PITCH / 50 DIVISIONS",
            "= 0.01MM PER DIVISION",
            "RATCHET, NOT THIMBLE",
            "ZERO IT FIRST",
        ],
        "scenes": [
            {
                "goal": "Hook: hundredths matter",
                "teaching_point": "A press fit is decided in 0.01mm",
                "shot": "macro shot of a micrometer measuring a bearing journal",
                "motion": "spindle closes on the part",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["micrometer", "bearing journal", "reading"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a micrometer measuring a bearing journal, bright task light, dark bench",
            },
            {
                "goal": "The scale",
                "teaching_point": "Barrel plus thimble",
                "shot": "graphic-style shot of a micrometer barrel with the two scales",
                "motion": "scales combine into a reading",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["micrometer diagram", "barrel scale", "thimble scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a micrometer scale diagram with barrel and thimble on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The technique",
                "teaching_point": "Ratchet force, widest point, clean part",
                "shot": "close-up of hands using the ratchet stop correctly",
                "motion": "ratchet clicks at proper force",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["micrometer", "ratchet stop", "hands"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of hands using a micrometer ratchet stop on a workbench, bright task light",
            },
            {
                "goal": "Temperature",
                "teaching_point": "A warm frame lies",
                "shot": "tabletop shot of a micrometer beside a thermometer",
                "motion": "thermometer reading rises",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["micrometer", "thermometer", "gauge block"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a micrometer beside a thermometer and gauge block, even diffused lighting, dark studio",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Mics for hundredths",
                "shot": "wide hero shot of a precision measurement station with a mic in use",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["measurement station", "micrometer", "parts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a precision measurement station with a micrometer in use, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A micrometer with its two scales magnified",
            "subject": "micrometer closed on a part",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "micrometer center, scale callouts",
            "text": "0.01MM PRECISION",
            "elements": ["micrometer", "barrel scale", "thimble scale"],
            "style": "precision macro photography",
            "mood": "fine, precise, disciplined",
            "prompt": "macro photograph of a micrometer closed on a metal part with scale callouts, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Micrometers: Read + Use",
            "title_variations": [
                "How to Use a Micrometer",
                "Reading a Micrometer",
                "Micrometer Technique",
                "0.01mm Measurement",
                "Micrometer vs Caliper",
            ],
            "description": "A micrometer is a precision screw: 0.5 millimeters per turn, fifty divisions on the thimble, each worth 0.01 millimeters. Reading combines the barrel's half-millimeter scale with the thimble's hundredths. Technique decides accuracy: clean the part, use the ratchet stop so every measurement presses with consistent force, measure at the widest point, and keep the tool at room temperature because a warm frame lies. Zero the micrometer against its anvil before measuring, and trust hundredths only when the ritual is right. This short covers the scale, the technique, and when a micrometer beats a caliper.",
            "hashtags": ["#Micrometer", "#Measuring", "#Tools", "#Precision"],
            "seo_keywords": [
                "how to use a micrometer",
                "reading a micrometer",
                "micrometer scale explained",
                "micrometer technique",
                "micrometer vs caliper",
                "0.01mm measurement",
                "precision measuring tools",
            ],
        },
        "fact_check": [
            "A 0.5 mm pitch screw with a 50-division thimble reads to 0.01 mm.",
            "The ratchet stop applies consistent measuring force without frame distortion.",
            "Thermal expansion of the frame and part shifts readings; 20 C is the reference.",
            "Zeroing against the anvil verifies calibration before measurement.",
            "Micrometers provide higher resolution than calipers for critical fits.",
        ],
    },
    # ======================================================================
    {
        "topic": "Welding Basics",
        "core_question": "How does welding join metal, and what are the main types?",
        "learning_objective": "The viewer can explain the weld pool concept, compare MIG, TIG, and stick, and pick a process for a job.",
        "engineering_summary": "Welding joins metal by melting the base pieces together, usually with filler metal, into a continuous joint that is as strong as - or stronger than - the parent material. The weld pool is molten metal that solidifies into the joint; the arc provides the heat. MIG (wire-fed, gas-shielded) is the easiest to learn, fast, and great for steel and aluminum production work. TIG (tungsten electrode, separate filler) gives the most control and cleanest welds for thin and exotic metals, with a steeper learning curve. Stick (consumable electrode, no gas bottle) is rugged and portable, ideal outdoors and on dirty steel. Safety: the arc is bright enough to damage eyes, so always wear a proper helmet.",
        "real_world_application": "Steel frames, brackets, and repairs are MIG-welded; aluminum bicycle frames and stainless work get TIG; field repairs and farm equipment run stick.",
        "common_misconceptions": [
            "Welding is just melting metal together (the arc, shielding, and filler define the joint quality)",
            "One welder does everything (each process trades speed, control, and portability)",
            "The weld is the weak point (a good weld is stronger than the base metal around it)",
        ],
        "teaching_strategy": "Show the weld pool formation, compare the three processes with sample welds, then safety and process selection.",
        "script": "Welding melts two pieces into one: the arc heats the base metal into a pool, filler joins it, and the solid joint is continuous metal - often stronger than the parent. Three workhorses. MIG: wire feeds itself, gas shields the pool; fast, easy to learn, great for steel. TIG: a tungsten arc and a hand-fed rod; most control, cleanest welds, steepest learning curve. Stick: a coated electrode, no gas bottle; rugged and portable, made for field work. The helmet isn't optional - the arc burns eyes before you feel it. Pick the process, respect the arc.",
        "text_overlay": [
            "ARC MELTS A SHARED POOL",
            "MIG: FAST + EASY",
            "TIG: CONTROL + CLEAN",
            "STICK: RUGGED + PORTABLE",
        ],
        "scenes": [
            {
                "goal": "Hook: the weld pool",
                "teaching_point": "Two pieces become one metal",
                "shot": "close-up of a weld pool forming under a MIG arc",
                "motion": "molten pool ripples and freezes",
                "lighting": "arc glow fills the frame",
                "background": "dark shop",
                "objects": ["weld pool", "arc", "molten metal"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a molten weld pool forming under a bright MIG arc, dark welding shop, arc glow lighting",
            },
            {
                "goal": "MIG",
                "teaching_point": "Self-feeding wire and gas",
                "shot": "medium shot of a MIG welder running a bead on steel",
                "motion": "bead lays down smoothly",
                "lighting": "arc glow light",
                "background": "welding shop",
                "objects": ["MIG welder", "steel plate", "bead"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a MIG welder laying a smooth bead on a steel plate, welding shop, arc glow lighting",
            },
            {
                "goal": "TIG",
                "teaching_point": "Tungsten arc, hand-fed rod",
                "shot": "medium shot of a TIG torch with a hand feeding filler rod",
                "motion": "rod dips into the pool",
                "lighting": "arc glow light",
                "background": "welding shop",
                "objects": ["TIG torch", "filler rod", "aluminum weld"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a TIG torch with a hand feeding filler rod into the weld pool, welding shop, arc glow lighting",
            },
            {
                "goal": "Stick",
                "teaching_point": "Coated electrode, no gas",
                "shot": "medium shot of stick welding outdoors on rusty steel",
                "motion": "electrode burns down, slag forms",
                "lighting": "daylight with arc glow",
                "background": "outdoor shop",
                "objects": ["stick electrode", "steel", "slag"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of stick welding outdoors on steel with a burning electrode, daylight with arc glow",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Respect the arc",
                "shot": "wide hero shot of a welded frame with a helmet on the bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["welded frame", "welding helmet", "samples"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a welded steel frame with a welding helmet beside it, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An arc close-up with the three process types labelled",
            "subject": "bright welding arc on steel",
            "background": "dark shop blur",
            "angle": "macro close-up",
            "lighting": "arc glow key",
            "composition": "arc center, process labels around",
            "text": "WELDING 101",
            "elements": ["welding arc", "weld pool", "process labels"],
            "style": "industrial macro photography",
            "mood": "molten, bright, skilled",
            "prompt": "macro photograph of a bright welding arc with a molten weld pool and process labels around it, dark welding shop background, 9:16 vertical composition, ultra sharp detail, cinematic",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Welding Basics: 3 Processes",
            "title_variations": [
                "How Welding Works",
                "MIG vs TIG vs Stick",
                "Welding for Beginners",
                "Which Welder Should I Get",
                "The Weld Pool Explained",
            ],
            "description": "Welding melts two metal pieces into one: the arc heats the base metal into a pool, filler joins it, and the solid joint is continuous metal, often stronger than the parent material. MIG is wire-fed and gas-shielded - fast, easy to learn, great for steel. TIG gives the most control and the cleanest welds for thin and exotic metals, with a steep learning curve. Stick welding needs no gas bottle and is rugged and portable for field work. Safety is non-negotiable: the arc burns eyes before you feel it. This short explains the weld pool and how to pick a process.",
            "hashtags": ["#Welding", "#MIG", "#TIG", "#Fabrication"],
            "seo_keywords": [
                "how welding works",
                "MIG vs TIG vs stick",
                "welding basics",
                "weld pool explained",
                "which welder to buy",
                "welding for beginners",
                "arc welding explained",
            ],
        },
        "fact_check": [
            "Welding fuses base metal into a continuous joint, typically with filler metal.",
            "MIG uses self-feeding wire with shielding gas; it is fast and beginner-friendly.",
            "TIG uses a tungsten electrode and hand-fed filler for maximum control.",
            "Stick welding uses a consumable coated electrode and needs no external gas.",
            "Properly executed welds are often stronger than the surrounding base metal.",
        ],
    },
    # ======================================================================
    {
        "topic": "DC Motors Basics",
        "core_question": "How does a simple DC motor spin, and how do I control its speed?",
        "learning_objective": "The viewer can explain the commutation mechanism, brush friction, and speed control via voltage and PWM.",
        "engineering_summary": "A brushed DC motor spins because current through the armature creates a magnetic field that interacts with the permanent magnet stator, producing torque; the commutator and brushes flip the current direction every half turn so the torque keeps pointing the same way. Speed is set by voltage: more volts, more current, more speed, up to the mechanical limit. Load pulls speed down and current up; a stalled motor draws maximum current and burns out quickly. Speed control comes from PWM (pulse width modulation) - switching full voltage on and off fast - rather than lowering voltage, keeping torque available. Brushes wear over thousands of hours; brushless motors swap them for electronics.",
        "real_world_application": "Cooling fans, drills, and window motors run on brushed DC; printer and drone builders know PWM speed control and stall current limits.",
        "common_misconceptions": [
            "A DC motor's speed is fixed (voltage and PWM set it continuously)",
            "Stalling is harmless (a stalled motor draws maximum current and can burn out)",
            "All DC motors have brushes (brushless DC motors use electronic commutation)",
        ],
        "teaching_strategy": "Open a motor to show the commutator, animate the current flip, then the voltage and PWM speed control with a stall warning.",
        "script": "Open a DC motor and the secret is the commutator: armature current makes a field that pushes against the magnet, and the brushes flip the current every half turn to keep the push going. Speed is voltage - more volts, more spin. Load it, and current climbs; stall it, and current maxes out while the motor cooks. That's why we control speed with PWM: switching full voltage fast keeps torque alive without the smoke. Brushes wear eventually - that's why brushless motors exist. Voltage sets speed, PWM keeps torque, stall kills motors.",
        "text_overlay": [
            "COMMUTATOR FLIPS CURRENT",
            "VOLTAGE = SPEED",
            "STALL = MAX CURRENT",
            "PWM KEEPS TORQUE",
        ],
        "scenes": [
            {
                "goal": "Hook: the torn-down motor",
                "teaching_point": "The commutator is the heart",
                "shot": "macro shot of a disassembled DC motor showing brushes and commutator",
                "motion": "slow push-in on the commutator",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["DC motor parts", "commutator", "brushes"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a disassembled DC motor showing the commutator and brushes, bright task light, dark bench",
            },
            {
                "goal": "The flip",
                "teaching_point": "Current flips keep torque spinning",
                "shot": "graphic-style shot of a motor cross-section with current arrows",
                "motion": "current flips as the armature turns",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["motor cross-section", "current arrows", "magnet"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a DC motor cross-section diagram with flipping current arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Voltage and PWM",
                "teaching_point": "Speed by voltage, torque by PWM",
                "shot": "tablet-style graphic showing voltage and PWM traces",
                "motion": "traces rise and pulse",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["voltage trace", "PWM trace", "motor"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of voltage and PWM control traces on a tablet beside a DC motor, even diffused lighting, dark studio",
            },
            {
                "goal": "The stall",
                "teaching_point": "Stall current cooks motors",
                "shot": "macro shot of a stalled motor with a current meter",
                "motion": "current needle spikes",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["stalled motor", "current meter", "wires"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stalled DC motor with a current meter spiking, warm task light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Voltage, PWM, stall - three rules",
                "shot": "wide hero shot of a PWM-controlled fan and drill on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fan", "drill", "motor controller"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a PWM controlled fan and drill on an engineering bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A motor cut open with current arrows and a PWM trace",
            "subject": "cutaway DC motor with control traces",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "motor center, traces around",
            "text": "DC MOTORS 101",
            "elements": ["cutaway motor", "commutator", "PWM trace"],
            "style": "electronics macro photography",
            "mood": "spinning, mechanical, clear",
            "prompt": "macro photograph of a cutaway DC motor with commutator and PWM traces, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "DC Motors Explained",
            "title_variations": [
                "How DC Motors Work",
                "Brushed Motor Basics",
                "Motor Speed Control PWM",
                "Why Motors Burn Out",
                "DC Motor Anatomy",
            ],
            "description": "A brushed DC motor spins because armature current creates a field that pushes against the permanent magnet, while the commutator and brushes flip the current every half turn to keep torque pointing the same way. Speed is voltage: more volts, more spin, up to the mechanical limit. Load pulls speed down and current up, and a stalled motor draws maximum current until it burns out - which is why speed control uses PWM, switching full voltage fast to keep torque alive. Brushes wear over time, which is why brushless motors exist. This short opens a motor, explains commutation, and gives the three rules of voltage, PWM, and stall.",
            "hashtags": ["#DCMotor", "#Electronics", "#Motors", "#PWM"],
            "seo_keywords": [
                "how dc motors work",
                "brushed dc motor explained",
                "PWM motor speed control",
                "motor stall current",
                "dc motor anatomy",
                "motor speed voltage",
                "brushed vs brushless",
            ],
        },
        "fact_check": [
            "Brushed DC motors use a commutator and brushes to flip armature current every half turn.",
            "Motor speed scales with applied voltage up to mechanical limits.",
            "A stalled DC motor draws maximum current and can overheat rapidly.",
            "PWM speed control switches full voltage to preserve torque at low speeds.",
            "Brushes wear mechanically; brushless motors use electronic commutation instead.",
        ],
    },
    # ======================================================================
    {
        "topic": "Center of Mass",
        "core_question": "Why do some objects tip over, and how does center of mass decide it?",
        "learning_objective": "The viewer can explain center of mass, stability rules, and use them to design balanced parts.",
        "engineering_summary": "Center of mass is the point where an object's mass balances in all directions - the average location of all its weight. An object is stable when the center of mass stays over its support area: tip it, and gravity pulls it back if the center stays inside the base; once the center passes the support edge, gravity tips it over. Lowering the center of mass or widening the base increases stability, which is why tall heavy objects need wide feet, and why a car with weight in the trunk handles corners better. In 3D printing, the model's center of mass decides what tips, what wobbles, and what needs a wider footprint.",
        "real_world_application": "Phone stands, camera mounts, and tool holders need balanced design; race cars lower centers of mass, and printer frames with heavy gantries need wide bases to resist tipping during acceleration.",
        "common_misconceptions": [
            "Heavier objects are more stable (base width and center height, not weight alone, decide)",
            "Center of mass is always the geometric center (it shifts toward dense regions)",
            "Stability is about strength (it is geometry: center over the support area)",
        ],
        "teaching_strategy": "Show a leaning block tipping at the critical angle, the support-area rule, then real printed parts with balanced bases.",
        "script": "Why does a tall mug tip but a wide one doesn't? Center of mass: the average point of all the weight. Stand it over the base, and gravity keeps it honest. Lean it until the center passes the edge of the base, and gravity flips it - no more recovery. Two levers: lower the center, widen the base. Same physics behind race car setups, camera mounts, and that tall print that wobbles on the bed. Heavy top, narrow feet? It falls. Wide feet, low weight? It laughs. Design the base for the mass above it.",
        "text_overlay": [
            "COM = AVERAGE OF WEIGHT",
            "INSIDE BASE = STABLE",
            "PAST THE EDGE = TIP",
            "WIDE BASE + LOW MASS",
        ],
        "scenes": [
            {
                "goal": "Hook: the tipping block",
                "teaching_point": "The critical angle decides everything",
                "shot": "tabletop shot of a block leaning at its critical angle",
                "motion": "block tips slowly past the edge",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["leaning block", "support edge", "weight arrows"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a block leaning at its critical tipping angle on a workbench, bright task light",
            },
            {
                "goal": "The definition",
                "teaching_point": "The average point of all weight",
                "shot": "graphic-style shot of an object with mass dots converging on the COM",
                "motion": "dots average into the center point",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["object diagram", "mass dots", "COM marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a center of mass diagram with mass dots converging to the COM point on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The stability rule",
                "teaching_point": "Inside the base, or over the edge",
                "shot": "tabletop shot of two blocks: stable base and narrow base",
                "motion": "both lean, one recovers one falls",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["wide-base block", "narrow-base block"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of wide and narrow base blocks on a test bench showing stability, neutral lab lighting",
            },
            {
                "goal": "In prints",
                "teaching_point": "Printed parts need balanced bases",
                "shot": "wide shot of a tall printed stand wobbling on the bed",
                "motion": "stand sways as the gantry moves",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["tall printed stand", "printer", "wobble"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a tall 3D printed stand wobbling on a printer bed, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the base for the mass",
                "shot": "wide hero shot of a redesigned wide-foot stand sitting steady",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["wide-foot stand", "balanced part"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a wide-foot 3D printed stand sitting perfectly steady, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A block with its center of mass crossing the base edge",
            "subject": "block leaning with a COM marker",
            "background": "dark workshop blur",
            "angle": "low side angle",
            "lighting": "hard key with rim",
            "composition": "block center, COM arrow, base line",
            "text": "WHY THINGS TIP",
            "elements": ["leaning block", "COM marker", "base edge"],
            "style": "physics studio photography",
            "mood": "balanced, geometric, clear",
            "prompt": "photograph of a leaning block with a center of mass marker crossing the base edge, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Center of Mass: Why Things Tip",
            "title_variations": [
                "Why Things Fall Over",
                "Center of Mass Explained",
                "Stability Physics Basics",
                "Designing Balanced Parts",
                "The Tipping Point Physics",
            ],
            "description": "Center of mass is the average location of all an object's weight. An object is stable when its center of mass stays over the support area: lean it and gravity pulls it back, but once the center crosses the support edge, gravity flips it over. Two levers rule stability: lower the center of mass and widen the base. The same physics drives race car setup, camera mount design, and the tall printed part that wobbles on the bed. This short explains the definition, the support-area rule, and how to design printed parts with bases that match the mass above them.",
            "hashtags": ["#Physics", "#CenterOfMass", "#Design", "#Stability"],
            "seo_keywords": [
                "center of mass explained",
                "why things tip over",
                "stability physics",
                "center of gravity basics",
                "balanced 3d print design",
                "support area stability",
                "designing stable parts",
            ],
        },
        "fact_check": [
            "Center of mass is the mass-weighted average position of an object.",
            "Stability requires the center of mass to remain over the support polygon.",
            "Tipping occurs when the center of mass passes the support edge.",
            "Lowering the center of mass and widening the base both increase stability.",
            "Center of mass shifts toward dense regions, not the geometric center.",
        ],
    },
]