"""Batch 42: square and flatness checks, dial versus digital readouts, micrometer versus caliper, tolerance measurement, precision squares, gauge blocks, workholding, cutting tools and bits."""

CURATED = [
    # ======================================================================
    {
        "topic": "Square & Flatness Checks",
        "core_question": "How do you know if a part is square and flat?",
        "learning_objective": "The viewer understands square and flatness checks.",
        "engineering_summary": "Square and flatness are measured against reference truth: a surface plate is a certified flat plane, and a precision square stands on it to test every ninety-degree corner against that plane. The check is simple: set the square on the plate, touch the part, and look for light under the blade, because light is the gap you can see. The same method checks flatness: a feeler gauge slides under a part to find a warp. Every good part starts from a flat reference.",
        "real_world_application": "Printer frames and fixtures are verified square before assembly.",
        "common_misconceptions": [
            "A ruler checks square (a plate and square do)",
            "Flatness is visible (light and feelers reveal the gap)",
            "One corner check is enough (every corner and face needs it)",
        ],
        "teaching_strategy": "Show light under the square, then the feeler finding the warp.",
        "script": "Square and flatness are measured against reference truth: a surface plate is a certified flat plane, and a precision square stands on it to test every ninety-degree corner against that plane. The check is simple: set the square on the plate, touch the part, and look for light under the blade, because light is the gap you can see. The same method checks flatness: a feeler gauge slides under a part to find a warp. Every good part starts from a flat reference.",
        "text_overlay": [
            "THE PLATE IS THE TRUTH",
            "LIGHT UNDER THE BLADE IS THE GAP",
            "FEELERS FIND THE WARP",
            "EVERY PART STARTS FROM FLAT",
        ],
        "scenes": [
            {
                "goal": "Hook: the wobbly corner",
                "teaching_point": "It looks square, is it?",
                "shot": "close-up shot of a part corner on a surface plate",
                "motion": "camera tilts to find the gap",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["surface plate", "part corner", "shadow gap"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part corner on a surface plate, bright task lighting, workshop",
            },
            {
                "goal": "The square",
                "teaching_point": "Ninety degrees to the plate",
                "shot": "medium shot of a precision square against a part",
                "motion": "square seats against the face",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["precision square", "part face", "plate"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a precision square against a part on a surface plate, bright task lighting, workshop",
            },
            {
                "goal": "The light",
                "teaching_point": "Light is the gap",
                "shot": "close-up shot of light under the square blade",
                "motion": "light slivers under the blade",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["light gap", "square blade", "part corner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of light showing under a square blade, bright task lighting, workshop",
            },
            {
                "goal": "The feeler",
                "teaching_point": "Feeler finds the warp",
                "shot": "close-up shot of a feeler sliding under a part",
                "motion": "gauge slips into the warp gap",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["feeler gauge", "warp gap", "flat plate"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a feeler gauge sliding under a printed part, bright task lighting, workshop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Flat truth first",
                "shot": "wide hero shot of a square frame checked on the plate",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["checked frame", "surface plate", "square"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a frame checked on a surface plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A precision square showing light under the blade on a surface plate",
            "subject": "square and flatness checks",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "square center, plate below",
            "text": "LIGHT UNDER THE BLADE IS THE GAP",
            "elements": ["precision square", "surface plate", "light gap"],
            "style": "geometry studio photography",
            "mood": "squared, flat, verified",
            "prompt": "photograph of a precision square showing light under the blade on a surface plate, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Square & Flatness Checks: Light Under the Blade Is the Gap",
            "title_variations": [
                "How to Check Square",
                "Check Flatness of a Part",
                "Surface Plate Truth",
                "Precision Square Use",
                "Square Frame Assembly",
            ],
            "description": "Square and flatness are measured against reference truth: a surface plate is a certified flat plane, and a precision square stands on it to test every ninety-degree corner. The check is simple: set the square on the plate, touch the part, and look for light under the blade. The same method checks flatness with a feeler gauge. This short seats the square, finds the light gap, and verifies the frame flat before assembly.",
            "hashtags": ["#SquareCheck", "#Flatness", "#SurfacePlate", "#Measurement"],
            "seo_keywords": [
                "how to check square",
                "check flatness of a part",
                "surface plate truth",
                "precision square use",
                "square frame assembly",
                "feeler gauge flatness",
                "square and flatness",
            ],
        },
        "fact_check": [
            "The plate is the reference.",
            "The square tests corners.",
            "Light under the blade is a gap.",
            "Feelers reveal warps.",
            "Parts start from flat.",
        ],
    },
    {
        "topic": "Dial vs Digital Readouts",
        "core_question": "Which readout should your machine use, dial or digital?",
        "learning_objective": "The viewer understands dial versus digital readouts.",
        "engineering_summary": "A readout turns motion into a number: a dial readout is a mechanical counter driven by the machine's screw, while a digital readout uses a glass scale to count position directly. The dial is rugged and cheap, but it drifts if the screw wears; the digital scale reads true position and adds features like zero offsets and presets. The choice is the job: hobby machines live with dials, and shops that need repeatability buy digital scales. The dial tells you the screw moved; the digital scale tells you the part actually moved.",
        "real_world_application": "Lathe and mill operators choose DROs for repeatable setups.",
        "common_misconceptions": [
            "Digital is always better (dials are rugged and cheap)",
            "The dial shows true position (it tracks the screw, which wears)",
            "Readouts need no setup (digital scales need calibration)",
        ],
        "teaching_strategy": "Show the dial, then the digital scale reading true position.",
        "script": "A readout turns motion into a number: a dial readout is a mechanical counter driven by the machine's screw, while a digital readout uses a glass scale to count position directly. The dial is rugged and cheap, but it drifts if the screw wears; the digital scale reads true position and adds features like zero offsets and presets. The choice is the job: hobby machines live with dials, and shops that need repeatability buy digital scales. The dial tells you the screw moved; the digital scale tells you the part actually moved.",
        "text_overlay": [
            "THE DIAL COUNTS THE SCREW",
            "THE DIGITAL SCALE READS TRUTH",
            "WEAR DRIFTS THE DIAL",
            "SHOPS BUY REPEATABILITY",
        ],
        "scenes": [
            {
                "goal": "Hook: the machine table",
                "teaching_point": "Position needs a number",
                "shot": "wide shot of a mill table with its handwheel",
                "motion": "handwheel turns, table moves",
                "lighting": "neutral lab light",
                "background": "machine shop",
                "objects": ["mill table", "handwheel", "screw"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a mill table with its handwheel, neutral lab lighting, machine shop",
            },
            {
                "goal": "The dial",
                "teaching_point": "Counter on the screw",
                "shot": "close-up shot of a dial readout on a machine",
                "motion": "dial ticks as the screw turns",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["dial readout", "screw counter", "knob"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a dial readout on a machine, bright task lighting, machine shop",
            },
            {
                "goal": "The scale",
                "teaching_point": "Glass scale reads true",
                "shot": "close-up shot of a digital readout on a machine",
                "motion": "numbers update as the table moves",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["digital readout", "glass scale", "display"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a digital readout on a machine, bright task lighting, machine shop",
            },
            {
                "goal": "The drift",
                "teaching_point": "Wear lies to the dial",
                "shot": "diagram-style shot of screw wear versus true position",
                "motion": "dial and truth diverge over time",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dial path", "true path", "drift gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of screw wear drifting a dial readout, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The part moved, not the screw",
                "shot": "wide hero shot of a machined part beside the readout",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["machined part", "digital readout", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a machined part beside a digital readout, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A dial readout beside a digital readout with a drift gap between them",
            "subject": "dial vs digital readouts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "dial left, digital right",
            "text": "THE DIGITAL SCALE READS TRUTH",
            "elements": ["dial readout", "digital display", "drift gap"],
            "style": "geometry studio photography",
            "mood": "counted, scaled, truthful",
            "prompt": "photograph of a dial readout beside a digital readout with a drift gap between them, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dial vs Digital Readouts: The Scale Reads Truth",
            "title_variations": [
                "Dial or Digital Readout",
                "Machine DRO Explained",
                "Readout for My Lathe",
                "Digital Scale vs Dial",
                "Repeatable Machine Setup",
            ],
            "description": "A readout turns motion into a number: a dial readout is a mechanical counter driven by the machine's screw, while a digital readout uses a glass scale to count position directly. The dial is rugged but drifts as the screw wears; the digital scale reads true position and adds presets. Hobby machines live with dials, and shops buy repeatability. This short counts the screw, reads the scale, and shows the drift gap between them.",
            "hashtags": ["#Readouts", "#DRO", "#MachineShop", "#Measurement"],
            "seo_keywords": [
                "dial or digital readout",
                "machine DRO explained",
                "readout for my lathe",
                "digital scale vs dial",
                "repeatable machine setup",
                "glass scale position",
                "screw wear readout drift",
            ],
        },
        "fact_check": [
            "The dial counts the screw.",
            "The scale reads true position.",
            "Wear drifts the dial.",
            "Digital adds presets.",
            "Shops buy repeatability.",
        ],
    },
    {
        "topic": "Micrometer vs Caliper",
        "core_question": "Which measuring tool do you actually need?",
        "learning_objective": "The viewer understands micrometer versus caliper choice.",
        "engineering_summary": "A caliper is the fast generalist and a micrometer is the precise specialist: the caliper reads most dimensions quickly to a few hundredths of a millimeter, while the micrometer reads one tight range to a thousandth with a threaded spindle and a ratchet that controls the force. The rule is range and resolution: for speed and variety, use the caliper; for a critical dimension that must be right, trust the micrometer. Each tool has one strength: the caliper measures everything, and the micrometer measures one thing perfectly.",
        "real_world_application": "Filament diameter checks use micrometers while layout work uses calipers.",
        "common_misconceptions": [
            "A caliper is precise enough (the micrometer wins at the thousandth)",
            "One tool does it all (each has a range and a job)",
            "Micrometers are hard to use (the ratchet does the force control)",
        ],
        "teaching_strategy": "Show the same part measured by both, then the resolution gap.",
        "script": "A caliper is the fast generalist and a micrometer is the precise specialist: the caliper reads most dimensions quickly to a few hundredths of a millimeter, while the micrometer reads one tight range to a thousandth with a threaded spindle and a ratchet that controls the force. The rule is range and resolution: for speed and variety, use the caliper; for a critical dimension that must be right, trust the micrometer. Each tool has one strength: the caliper measures everything, and the micrometer measures one thing perfectly.",
        "text_overlay": [
            "THE CALIPER: FAST GENERALIST",
            "THE MICROMETER: PRECISE SPECIALIST",
            "RATCHET CONTROLS THE FORCE",
            "SPEED OR THE THOUSANDTH",
        ],
        "scenes": [
            {
                "goal": "Hook: the critical pin",
                "teaching_point": "It must fit exactly",
                "shot": "close-up shot of a precision pin beside tools",
                "motion": "camera pans the pin",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["precision pin", "caliper", "micrometer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a precision pin beside a caliper and micrometer, bright task lighting, workbench",
            },
            {
                "goal": "The caliper",
                "teaching_point": "Fast, broad range",
                "shot": "medium shot of measuring with a caliper",
                "motion": "jaws close on the part",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper jaws", "measured part", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of measuring a part with a caliper, bright task lighting, workbench",
            },
            {
                "goal": "The micrometer",
                "teaching_point": "Threaded spindle, ratchet force",
                "shot": "close-up shot of a micrometer measuring the pin",
                "motion": "spindle closes with the ratchet click",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["micrometer spindle", "ratchet", "pin"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a micrometer measuring a pin, bright task lighting, workbench",
            },
            {
                "goal": "The gap",
                "teaching_point": "Hundredths versus thousandths",
                "shot": "diagram-style shot of the resolution ladder",
                "motion": "caliper rung then micrometer rung",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["caliper rung", "micrometer rung", "resolution ladder"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of caliper versus micrometer resolution, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Right tool, right job",
                "shot": "wide hero shot of both tools on the bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["caliper", "micrometer", "measured pin"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a caliper and micrometer beside a measured pin, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A caliper measuring fast beside a micrometer reading a pin to the thousandth",
            "subject": "micrometer vs caliper",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "caliper left, micrometer right",
            "text": "SPEED OR THE THOUSANDTH",
            "elements": ["caliper jaws", "micrometer spindle", "precision pin"],
            "style": "geometry studio photography",
            "mood": "measured, precise, chosen",
            "prompt": "photograph of a caliper measuring fast beside a micrometer reading a pin to the thousandth, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Micrometer vs Caliper: Speed or the Thousandth",
            "title_variations": [
                "Micrometer or Caliper",
                "Which Measuring Tool",
                "Caliper vs Micrometer",
                "Precision Measurement Tools",
                "Measure to the Thousandth",
            ],
            "description": "A caliper is the fast generalist and a micrometer is the precise specialist: the caliper reads most dimensions quickly to a few hundredths, while the micrometer reads one tight range to a thousandth with a ratchet that controls the force. For speed and variety, use the caliper; for a critical dimension, trust the micrometer. This short measures the same pin both ways and shows why each tool wins its own job.",
            "hashtags": ["#Micrometer", "#Caliper", "#Precision", "#Measurement"],
            "seo_keywords": [
                "micrometer or caliper",
                "which measuring tool",
                "caliper vs micrometer",
                "precision measurement tools",
                "measure to the thousandth",
                "micrometer ratchet force",
                "caliper resolution limits",
            ],
        },
        "fact_check": [
            "The caliper is the generalist.",
            "The micrometer is the specialist.",
            "The ratchet controls force.",
            "Resolution sets the trust.",
            "Each tool wins its job.",
        ],
    },
    {
        "topic": "Tolerance Measurement",
        "core_question": "How do you verify a part actually meets its dimension?",
        "learning_objective": "The viewer understands tolerance measurement.",
        "engineering_summary": "Verifying a dimension means comparing the part to its callout: the drawing says the hole is ten millimeters plus or minus a tenth, and the gauge says what the part really is, and the difference decides pass or fail. The method matters as much as the tool: measure at the right spot, at the right temperature, with the same force every time, or the reading lies. The practice is a loop: measure, compare to the zone, and decide, with the gauge calibrated against a reference. A dimension is only true when the measurement is trustworthy.",
        "real_world_application": "Quality checks on mating parts live or die by trustworthy measurements.",
        "common_misconceptions": [
            "Any reading is the truth (method and calibration decide it)",
            "One measurement is enough (position and force change it)",
            "Tight tolerance means a bigger tool (it means a better method)",
        ],
        "teaching_strategy": "Show the callout, the measurement, and the pass-fail decision.",
        "script": "Verifying a dimension means comparing the part to its callout: the drawing says the hole is ten millimeters plus or minus a tenth, and the gauge says what the part really is, and the difference decides pass or fail. The method matters as much as the tool: measure at the right spot, at the right temperature, with the same force every time, or the reading lies. The practice is a loop: measure, compare to the zone, and decide, with the gauge calibrated against a reference. A dimension is only true when the measurement is trustworthy.",
        "text_overlay": [
            "COMPARE THE PART TO THE CALLOUT",
            "METHOD DECIDES THE READING",
            "MEASURE, COMPARE, DECIDE",
            "CALIBRATE AGAINST TRUTH",
        ],
        "scenes": [
            {
                "goal": "Hook: the borderline hole",
                "teaching_point": "Pass or fail?",
                "shot": "close-up shot of a hole being gauged",
                "motion": "gauge enters the hole slowly",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["hole gauge", "borderline hole", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hole being gauged on a part, bright task lighting, workshop",
            },
            {
                "goal": "The callout",
                "teaching_point": "The zone is the truth",
                "shot": "diagram-style shot of a dimension with its tolerance zone",
                "motion": "plus and minus marks frame the value",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dimension line", "tolerance zone", "callout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a dimension with its tolerance zone, clean engineering visualization on a dark background",
            },
            {
                "goal": "The method",
                "teaching_point": "Spot, temperature, force",
                "shot": "diagram-style shot of the measurement conditions",
                "motion": "three condition icons line up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["spot marker", "temp icon", "force icon"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of measurement conditions, clean engineering visualization on a dark background",
            },
            {
                "goal": "The loop",
                "teaching_point": "Measure, compare, decide",
                "shot": "diagram-style shot of the pass-fail loop",
                "motion": "reading meets the zone and decides",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["reading value", "zone bar", "pass mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a pass-fail measurement loop, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Trustworthy measurements only",
                "shot": "wide hero shot of a verified part with its gauge",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["verified part", "gauge", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a verified part beside its gauge, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A gauge reading a hole against a dimension callout with a tolerance zone",
            "subject": "tolerance measurement",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gauge center, callout beside",
            "text": "MEASURE, COMPARE, DECIDE",
            "elements": ["hole gauge", "tolerance zone", "callout"],
            "style": "geometry studio photography",
            "mood": "gauged, compared, decided",
            "prompt": "photograph of a gauge reading a hole against a dimension callout with a tolerance zone, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Tolerance Measurement: Measure, Compare, Decide",
            "title_variations": [
                "How to Verify a Dimension",
                "Check a Part Tolerance",
                "Pass or Fail Gauging",
                "Measure Like Quality Control",
                "Tolerance Verification Guide",
            ],
            "description": "Verifying a dimension means comparing the part to its callout: the drawing says ten millimeters plus or minus a tenth, and the gauge says what the part really is. The method matters as much as the tool, since spot, temperature, and force change the reading. The practice is a loop: measure, compare to the zone, and decide, with the gauge calibrated against a reference. This short gauges the hole, frames the zone, and runs the pass-fail loop.",
            "hashtags": ["#Tolerance", "#QualityControl", "#Gauging", "#Measurement"],
            "seo_keywords": [
                "how to verify a dimension",
                "check a part tolerance",
                "pass or fail gauging",
                "measure like quality control",
                "tolerance verification guide",
                "gauge calibration reference",
                "measurement method repeatability",
            ],
        },
        "fact_check": [
            "The callout defines the zone.",
            "The gauge reads the part.",
            "Method decides the reading.",
            "Calibration anchors the truth.",
            "Measure, compare, decide.",
        ],
    },
    {
        "topic": "Precision Squares",
        "core_question": "How do you check a perfect ninety degrees?",
        "learning_objective": "The viewer understands precision squares.",
        "engineering_summary": "A precision square is a certified right angle: the beam and blade are ground flat and square to each other to a tiny fraction of a degree, so it turns any flat surface into a checkable reference. The test is contact and light: hold the square against the part, and the gap under the blade tells the truth about the corner. The square itself must be trusted, which means it is stored flat, never dropped, and verified against a master. A precision square is the shop's guarantee of ninety degrees.",
        "real_world_application": "Printer frames and jigs get their right angles from precision squares.",
        "common_misconceptions": [
            "Any corner tool works (only a certified square is truth)",
            "A dropped square is fine (it loses its calibration instantly)",
            "Squares only check outside corners (inside corners too)",
        ],
        "teaching_strategy": "Show the square checking a corner, then the light test.",
        "script": "A precision square is a certified right angle: the beam and blade are ground flat and square to each other to a tiny fraction of a degree, so it turns any flat surface into a checkable reference. The test is contact and light: hold the square against the part, and the gap under the blade tells the truth about the corner. The square itself must be trusted, which means it is stored flat, never dropped, and verified against a master. A precision square is the shop's guarantee of ninety degrees.",
        "text_overlay": [
            "A CERTIFIED RIGHT ANGLE",
            "THE GAP UNDER THE BLADE TELLS TRUTH",
            "NEVER DROP THE SQUARE",
            "THE SHOP'S NINETY-DEGREE GUARANTEE",
        ],
        "scenes": [
            {
                "goal": "Hook: the frame corner",
                "teaching_point": "Is it truly ninety?",
                "shot": "wide shot of a frame corner with a square",
                "motion": "camera closes on the joint",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["frame corner", "square", "joint"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a frame corner being checked with a square, neutral lab lighting, workshop",
            },
            {
                "goal": "The truth",
                "teaching_point": "Ground flat and square",
                "shot": "diagram-style shot of the square's geometry",
                "motion": "beam and blade lock at ninety",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["square beam", "square blade", "ninety angle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a precision square geometry, clean engineering visualization on a dark background",
            },
            {
                "goal": "The test",
                "teaching_point": "Contact and light",
                "shot": "close-up shot of light under the square blade",
                "motion": "gap slivers under the blade",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["light gap", "square blade", "part face"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of light under a square blade at a corner, bright task lighting, workshop",
            },
            {
                "goal": "The care",
                "teaching_point": "Flat, never dropped",
                "shot": "medium shot of a square stored flat in a drawer",
                "motion": "square rests on its side",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["stored square", "flat drawer", "tool box"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a precision square stored flat in a drawer, neutral lab lighting, workshop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Ninety degrees, guaranteed",
                "shot": "wide hero shot of a verified frame assembly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["verified frame", "square", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a verified frame assembly with a precision square, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A precision square at a corner with light showing under the blade",
            "subject": "precision squares",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "square center, corner behind",
            "text": "THE SHOP'S NINETY-DEGREE GUARANTEE",
            "elements": ["precision square", "light gap", "frame corner"],
            "style": "geometry studio photography",
            "mood": "squared, checked, guaranteed",
            "prompt": "photograph of a precision square at a corner with light showing under the blade, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Precision Squares: The Shop's Ninety-Degree Guarantee",
            "title_variations": [
                "How to Check 90 Degrees",
                "Engineers Square Use",
                "Precision Square Test",
                "Check Frame Squareness",
                "Right Angle Verification",
            ],
            "description": "A precision square is a certified right angle: the beam and blade are ground flat and square to each other to a tiny fraction of a degree. The test is contact and light, since the gap under the blade tells the truth about the corner. The square itself must be stored flat, never dropped, and verified against a master. This short seats the square at the corner, finds the light gap, and guarantees the frame's ninety degrees.",
            "hashtags": ["#PrecisionSquare", "#RightAngle", "#Workshop", "#Measurement"],
            "seo_keywords": [
                "how to check 90 degrees",
                "engineers square use",
                "precision square test",
                "check frame squareness",
                "right angle verification",
                "precision square care",
                "square blade light test",
            ],
        },
        "fact_check": [
            "The square is certified truth.",
            "Blade and beam meet at ninety.",
            "Light reveals the gap.",
            "Drops ruin the square.",
            "It guarantees right angles.",
        ],
    },
    {
        "topic": "Gauge Blocks",
        "core_question": "What are gauge blocks and why are they called truth?",
        "learning_objective": "The viewer understands gauge blocks.",
        "engineering_summary": "Gauge blocks are the reference standard of the shop: precision-ground steel slabs with faces flat and parallel to fractions of a micron, and when two are wrung together they stick by molecular adhesion and act as one exact length. They set the size that every other tool is compared to: micrometers get checked against blocks, and setups get built from them. The care is absolute: they stay clean, oiled, and handled by their edges, because a fingerprint changes the length. Gauge blocks are the closest thing a shop has to a measurement god.",
        "real_world_application": "Calibration labs and toolrooms build exact sizes from wrung blocks.",
        "common_misconceptions": [
            "Blocks are just steel slabs (their faces are flat to microns)",
            "They measure parts directly (they set sizes for other tools)",
            "Handling is casual (a fingerprint changes the length)",
        ],
        "teaching_strategy": "Show blocks wringing together, then a tool check against them.",
        "script": "Gauge blocks are the reference standard of the shop: precision-ground steel slabs with faces flat and parallel to fractions of a micron, and when two are wrung together they stick by molecular adhesion and act as one exact length. They set the size that every other tool is compared to: micrometers get checked against blocks, and setups get built from them. The care is absolute: they stay clean, oiled, and handled by their edges, because a fingerprint changes the length. Gauge blocks are the closest thing a shop has to a measurement god.",
        "text_overlay": [
            "FACES FLAT TO A MICRON",
            "WRUNG TOGETHER, THEY BECOME ONE LENGTH",
            "TOOLS GET CHECKED AGAINST THEM",
            "THE SHOP'S MEASUREMENT GOD",
        ],
        "scenes": [
            {
                "goal": "Hook: the gleaming set",
                "teaching_point": "The shop's standards",
                "shot": "wide shot of a gauge block set in its case",
                "motion": "camera glides over the rows",
                "lighting": "neutral lab light",
                "background": "toolroom",
                "objects": ["gauge set", "block rows", "case"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a gauge block set in its case, neutral lab lighting, toolroom",
            },
            {
                "goal": "The face",
                "teaching_point": "Flat to a micron",
                "shot": "diagram-style shot of a block face flatness",
                "motion": "magnified face shows perfect flat",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["block face", "flat line", "magnified view"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of gauge block face flatness, clean engineering visualization on a dark background",
            },
            {
                "goal": "The wring",
                "teaching_point": "Blocks stick as one",
                "shot": "close-up shot of two blocks wringing together",
                "motion": "blocks slide and bond",
                "lighting": "bright task light",
                "background": "toolroom",
                "objects": ["block pair", "wring slide", "bonded faces"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two gauge blocks wringing together, bright task lighting, toolroom",
            },
            {
                "goal": "The check",
                "teaching_point": "Tools compare to blocks",
                "shot": "medium shot of a micrometer checked against blocks",
                "motion": "spindle closes on the stack",
                "lighting": "bright task light",
                "background": "toolroom",
                "objects": ["micrometer", "block stack", "check"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a micrometer being checked against gauge blocks, bright task lighting, toolroom",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Care is absolute",
                "shot": "wide hero shot of blocks handled by the edges",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["block set", "gloved hand", "case"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of gauge blocks handled by their edges, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Gauge blocks wringing together with a micrometer check beside them",
            "subject": "gauge blocks",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "block stack center, check beside",
            "text": "THE SHOP'S MEASUREMENT GOD",
            "elements": ["block stack", "wring bond", "micrometer check"],
            "style": "geometry studio photography",
            "mood": "wruung, bonded, standard",
            "prompt": "photograph of gauge blocks wringing together with a micrometer check beside them in a toolroom, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Gauge Blocks: The Shop's Measurement God",
            "title_variations": [
                "What Are Gauge Blocks",
                "Gauge Block Wringing",
                "Jo Blocks Explained",
                "Calibrate With Gauge Blocks",
                "Reference Standards Shop",
            ],
            "description": "Gauge blocks are the reference standard of the shop: precision-ground steel slabs with faces flat and parallel to fractions of a micron, and when wrung together they stick by molecular adhesion and act as one exact length. They set the size every other tool is compared to. The care is absolute, since a fingerprint changes the length. This short wrings the pair, checks the micrometer, and meets the shop's measurement god.",
            "hashtags": ["#GaugeBlocks", "#Calibration", "#JoBlocks", "#Measurement"],
            "seo_keywords": [
                "what are gauge blocks",
                "gauge block wringing",
                "jo blocks explained",
                "calibrate with gauge blocks",
                "reference standards shop",
                "wring gauge blocks",
                "gauge block care",
            ],
        },
        "fact_check": [
            "Blocks are ground to microns.",
            "Wringing bonds them as one.",
            "Tools check against them.",
            "Fingerprints change length.",
            "They are the reference truth.",
        ],
    },
    {
        "topic": "Workholding",
        "core_question": "How do you hold a part while you machine it?",
        "learning_objective": "The viewer understands workholding.",
        "engineering_summary": "Workholding is the art of making a part stay put: a vise grips straight parts, clamps pin down plates, and soft jaws or fixtures cradle odd shapes, all fighting the cutter's force. The rules are support and access: the part must be rigid enough to cut without flexing, and open enough that the tool can reach the features. The trap is holding too little, so the part lifts, or holding too much, so the vise crushes it. Every machining job starts with the question of how the part will be held. Workholding is where machining is really won.",
        "real_world_application": "Fixtures and soft jaws hold one-off prints for every mill job.",
        "common_misconceptions": [
            "The vise holds anything (odd shapes need fixtures and jaws)",
            "Tighter is always better (crushing warps the part)",
            "Workholding is optional (the cutter force demands it)",
        ],
        "teaching_strategy": "Show a part lifting, then a fixture holding it rigid.",
        "script": "Workholding is the art of making a part stay put: a vise grips straight parts, clamps pin down plates, and soft jaws or fixtures cradle odd shapes, all fighting the cutter's force. The rules are support and access: the part must be rigid enough to cut without flexing, and open enough that the tool can reach the features. The trap is holding too little, so the part lifts, or holding too much, so the vise crushes it. Every machining job starts with the question of how the part will be held. Workholding is where machining is really won.",
        "text_overlay": [
            "FIGHT THE CUTTER'S FORCE",
            "SUPPORT AND ACCESS",
            "TOO LOOSE LIFTS, TOO TIGHT CRUSHES",
            "MACHINING IS WON AT THE HOLD",
        ],
        "scenes": [
            {
                "goal": "Hook: the lifting part",
                "teaching_point": "It moves under the cutter",
                "shot": "close-up shot of a part lifting in a loose vise",
                "motion": "part rises as the cutter passes",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["lifting part", "loose vise", "cutter"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part lifting in a loose vise, bright task lighting, machine shop",
            },
            {
                "goal": "The grip",
                "teaching_point": "Vise, clamps, fixtures",
                "shot": "diagram-style shot of the workholding family",
                "motion": "vise, clamps, and jaws line up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["vise grip", "clamp set", "soft jaw"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the workholding family, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Rigid but reachable",
                "shot": "diagram-style shot of support and access",
                "motion": "support arrows press, tool path stays open",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["support arrows", "open path", "held part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of workholding support and access, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fixture",
                "teaching_point": "Soft jaws cradle odd shapes",
                "shot": "medium shot of an odd part in a soft-jaw fixture",
                "motion": "jaws close around the shape",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["soft jaws", "odd part", "fixture"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an odd shaped part in soft jaws, bright task lighting, machine shop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Won at the hold",
                "shot": "wide hero shot of a machined part in its fixture",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["machined part", "fixture", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a machined part held in its fixture, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An odd part cradled in soft jaws with support and access arrows",
            "subject": "workholding",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, jaws around",
            "text": "MACHINING IS WON AT THE HOLD",
            "elements": ["soft jaws", "held part", "support arrows"],
            "style": "geometry studio photography",
            "mood": "cradled, rigid, accessed",
            "prompt": "photograph of an odd part cradled in soft jaws with support and access arrows, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Workholding: Machining Is Won at the Hold",
            "title_variations": [
                "How to Hold Parts for Machining",
                "Workholding Basics",
                "Soft Jaw Fixtures",
                "Stop Parts Lifting",
                "Vise vs Clamps vs Fixtures",
            ],
            "description": "Workholding is the art of making a part stay put: a vise grips straight parts, clamps pin down plates, and soft jaws or fixtures cradle odd shapes, all fighting the cutter's force. The rules are support and access: rigid enough to cut without flexing, open enough for the tool. The trap is holding too little or too much. This short lifts a loose part, cradles it in soft jaws, and wins the job at the hold.",
            "hashtags": ["#Workholding", "#Fixtures", "#MachineShop", "#Machining"],
            "seo_keywords": [
                "how to hold parts for machining",
                "workholding basics",
                "soft jaw fixtures",
                "stop parts lifting",
                "vise vs clamps vs fixtures",
                "workholding support access",
                "hold odd shapes machining",
            ],
        },
        "fact_check": [
            "The hold fights cutter force.",
            "Support and access rule.",
            "Too loose lets parts lift.",
            "Too tight crushes them.",
            "Fixtures cradle odd shapes.",
        ],
    },
    {
        "topic": "Cutting Tools & Bits",
        "core_question": "Which cutter do you reach for and why?",
        "learning_objective": "The viewer understands cutting tool selection.",
        "engineering_summary": "Every cutter is built for a motion: drill bits cut straight in, end mills cut sideways and plunge, and each geometry, from two-flute to four-flute, trades chip clearance for surface finish. The selection rules are material and motion: plastics and aluminum want sharp, two-flute cutters that clear chips fast, while steel wants rigid four-flute tools that finish smooth. The failure is misuse: plunging an end mill like a drill or running a dull bit hot. The right bit cuts in minutes; the wrong one burns in seconds.",
        "real_world_application": "Print shops pick two-flute end mills for plastic parts.",
        "common_misconceptions": [
            "One bit does everything (each geometry has a job)",
            "More flutes are better (they clog in plastics)",
            "Dull bits still work (they burn and deflect)",
        ],
        "teaching_strategy": "Show the bit family, then the right and wrong cuts.",
        "script": "Every cutter is built for a motion: drill bits cut straight in, end mills cut sideways and plunge, and each geometry, from two-flute to four-flute, trades chip clearance for surface finish. The selection rules are material and motion: plastics and aluminum want sharp, two-flute cutters that clear chips fast, while steel wants rigid four-flute tools that finish smooth. The failure is misuse: plunging an end mill like a drill or running a dull bit hot. The right bit cuts in minutes; the wrong one burns in seconds.",
        "text_overlay": [
            "DRILLS GO STRAIGHT, MILLS GO SIDEWAYS",
            "TWO FLUTES CLEAR, FOUR FINISH",
            "PLASTIC WANTS SHARP AND FAST",
            "RIGHT BIT, MINUTES; WRONG BIT, SMOKE",
        ],
        "scenes": [
            {
                "goal": "Hook: the smoking cut",
                "teaching_point": "Wrong bit burns",
                "shot": "close-up shot of a dull bit cutting plastic",
                "motion": "smoke rises from the hot cut",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["dull bit", "burning cut", "smoke"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a dull bit cutting plastic with smoke, bright task lighting, machine shop",
            },
            {
                "goal": "The family",
                "teaching_point": "Drills and end mills",
                "shot": "diagram-style shot of the cutter family",
                "motion": "drill, two-flute, and four-flute line up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["drill bit", "two-flute mill", "four-flute mill"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the cutting tool family, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Clearance versus finish",
                "shot": "diagram-style shot of flute trade-offs",
                "motion": "two-flute clears chips, four-flute smooths",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["chip clearance", "smooth finish", "flute count"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flute trade-offs, clean engineering visualization on a dark background",
            },
            {
                "goal": "The match",
                "teaching_point": "Material picks the bit",
                "shot": "medium shot of a two-flute bit cutting plastic",
                "motion": "clean chips fly from the cut",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["two-flute bit", "clean chips", "plastic part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a two-flute bit cutting plastic cleanly, bright task lighting, machine shop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the motion",
                "shot": "wide hero shot of a cleanly cut part with its bit",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["cut part", "right bit", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a cleanly cut part beside its bit, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A two-flute end mill cutting plastic cleanly beside a smoking dull bit",
            "subject": "cutting tools and bits",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "right bit center, wrong bit aside",
            "text": "RIGHT BIT, MINUTES; WRONG BIT, SMOKE",
            "elements": ["two-flute mill", "clean chips", "dull bit"],
            "style": "geometry studio photography",
            "mood": "matched, sharp, cutting",
            "prompt": "photograph of a two-flute end mill cutting plastic cleanly beside a smoking dull bit, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Cutting Tools & Bits: Right Bit, Minutes; Wrong Bit, Smoke",
            "title_variations": [
                "Which Cutting Tool for What",
                "End Mill vs Drill Bit",
                "Two Flute vs Four Flute",
                "Cut Plastic With a Mill",
                "Cutting Bit Selection Guide",
            ],
            "description": "Every cutter is built for a motion: drill bits cut straight in, end mills cut sideways and plunge, and each geometry trades chip clearance for surface finish. Plastics and aluminum want sharp, two-flute cutters, while steel wants rigid four-flute tools. The failure is misuse, from plunging a mill like a drill to running a dull bit hot. This short burns a dull bit, lines up the family, and matches the two-flute to the plastic.",
            "hashtags": ["#CuttingTools", "#EndMills", "#Machining", "#CNC"],
            "seo_keywords": [
                "which cutting tool for what",
                "end mill vs drill bit",
                "two flute vs four flute",
                "cut plastic with a mill",
                "cutting bit selection guide",
                "end mill flute count",
                "sharp bits plastic cutting",
            ],
        },
        "fact_check": [
            "Drills cut straight in.",
            "Mills cut sideways.",
            "Flutes trade clearance and finish.",
            "Plastics want two flutes.",
            "Dull bits burn the part.",
        ],
    },
]