"""Batch 38: drilling and tapping, metal 3D printing, vapor smoothing, heat gun deburring, resin smoothing, polishing clear prints, dyeing nylon, weatherproofing."""

CURATED = [
    # ======================================================================
    {
        "topic": "Drill & Tap Printed Parts",
        "core_question": "Can you machine a printed part like a metal one?",
        "learning_objective": "The viewer understands drilling and tapping printed parts.",
        "engineering_summary": "Printed parts can absolutely be drilled and tapped, but plastic behaves differently than metal: it cuts with a knife, not a chip, so the drill must be sharp and the speed low. Tapping works best with a sharp tap, a light touch, and a well-supported wall, because plastic threads strip easily and melt if the tap runs hot. The trick is printed holes slightly undersized so the tap cuts a full thread, and tapping while the part is cool. Machining a print is normal, but the rules are plastic rules.",
        "real_world_application": "Repairing stripped threads and adding bolt holes is everyday print finishing.",
        "common_misconceptions": [
            "Printed parts cannot be tapped (they tap cleanly with sharp tools)",
            "Use metal speeds (plastic melts with heat and pressure)",
            "Tap the printed size (print undersized, tap to size)",
        ],
        "teaching_strategy": "Drill and tap a test block, then show the clean thread.",
        "script": "Printed parts can absolutely be drilled and tapped, but plastic behaves differently than metal: it cuts with a knife, not a chip, so the drill must be sharp and the speed low. Tapping works best with a sharp tap, a light touch, and a well-supported wall, because plastic threads strip easily and melt if the tap runs hot. The trick is printed holes slightly undersized so the tap cuts a full thread, and tapping while the part is cool. Machining a print is normal, but the rules are plastic rules.",
        "text_overlay": [
            "PLASTIC CUTS WITH A KNIFE",
            "SHARP TOOLS, LOW SPEED",
            "PRINT UNDERSIZED, TAP TO SIZE",
            "MACHINING WITH PLASTIC RULES",
        ],
        "scenes": [
            {
                "goal": "Hook: the stripped hole",
                "teaching_point": "Threads strip easily",
                "shot": "close-up shot of a stripped plastic thread hole",
                "motion": "camera shows the chewed threads",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["stripped hole", "chewed threads", "plastic block"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a stripped plastic thread hole, bright task lighting, workbench",
            },
            {
                "goal": "The drill",
                "teaching_point": "Sharp drill, low speed",
                "shot": "close-up shot of drilling a printed block",
                "motion": "drill turns slow and clean",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["drill bit", "printed block", "clean bore"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of drilling a printed block slowly, bright task lighting, workbench",
            },
            {
                "goal": "The tap",
                "teaching_point": "Undersize then tap",
                "shot": "close-up shot of tapping a printed hole",
                "motion": "tap turns with a light touch",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["tap tool", "printed hole", "threads"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of tapping a printed hole, bright task lighting, workbench",
            },
            {
                "goal": "The rules",
                "teaching_point": "Cool part, support walls",
                "shot": "diagram-style shot of tapping rules",
                "motion": "cool part and wall support notes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cool part", "wall support", "thread depth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tapping rules for prints, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Plastic rules",
                "shot": "wide hero shot of a bolt seated in a tapped print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["seated bolt", "tapped print", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a bolt seated in a tapped printed part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A tap cutting clean threads in a printed block with a drill beside",
            "subject": "drill tap printed parts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "block center, drill and tap beside",
            "text": "PRINT UNDERSIZED, TAP TO SIZE",
            "elements": ["tap tool", "printed block", "drill bit"],
            "style": "geometry studio photography",
            "mood": "cut, tapped, machined",
            "prompt": "photograph of a tap cutting threads in a printed block with a drill bit beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Drill & Tap Printed Parts: Machining With Plastic Rules",
            "title_variations": [
                "Can You Tap Printed Parts",
                "Drill Printed Holes",
                "Thread Tap PLA",
                "Tap Printed Threads",
                "Machining 3D Prints",
            ],
            "description": "Printed parts can absolutely be drilled and tapped, but plastic behaves differently than metal: it cuts with a knife, not a chip, so the drill must be sharp and the speed low. Tapping works best with a sharp tap, a light touch, and a well-supported wall, because plastic threads strip easily and melt if the tap runs hot. This short strips a hole, drills it clean, and taps it to size, all under plastic rules.",
            "hashtags": ["#DrillTap", "#Threads", "#Finishing", "#3DPrinting"],
            "seo_keywords": [
                "can you tap printed parts",
                "drill printed holes",
                "thread tap PLA",
                "tap printed threads",
                "machining 3D prints",
                "tap print undersize",
                "plastic thread tapping",
            ],
        },
        "fact_check": [
            "Prints can be machined.",
            "Plastic cuts like a knife.",
            "Sharps tools and low speeds.",
            "Print holes undersized.",
            "Cool parts tap best.",
        ],
    },
    {
        "topic": "Metal 3D Printing",
        "core_question": "How do machines print solid metal parts?",
        "learning_objective": "The viewer understands metal 3D printing.",
        "engineering_summary": "Metal 3D printing builds parts layer by layer from powder or wire, and the workhorse is powder bed fusion: a laser or electron beam melts fine metal powder into a part, one layer at a time, inside a sealed machine with an inert atmosphere. The heat is extreme, so the process controls temperature tightly to avoid warping and cracking, and parts come out near their design shape. The result is real metal with real strength, at the cost of a machine that fills a room. Metal printing is a foundry that draws, not pours.",
        "real_world_application": "Aerospace and medical parts print metal where machining cannot reach.",
        "common_misconceptions": [
            "It is an exotic toy (it is production tooling for industry)",
            "Powder melts like plastic (it is a full metallurgical process)",
            "Parts need no support (overhangs need printed metal supports)",
        ],
        "teaching_strategy": "Show the powder bed and the laser building a layer.",
        "script": "Metal 3D printing builds parts layer by layer from powder or wire, and the workhorse is powder bed fusion: a laser or electron beam melts fine metal powder into a part, one layer at a time, inside a sealed machine with an inert atmosphere. The heat is extreme, so the process controls temperature tightly to avoid warping and cracking, and parts come out near their design shape. The result is real metal with real strength, at the cost of a machine that fills a room. Metal printing is a foundry that draws, not pours.",
        "text_overlay": [
            "POWDER BED, LASER, LAYER",
            "SEALED AND INERT",
            "HEAT CONTROLLED TIGHTLY",
            "A FOUNDRY THAT DRAWS",
        ],
        "scenes": [
            {
                "goal": "Hook: the sealed machine",
                "teaching_point": "A room-sized foundry",
                "shot": "wide shot of a metal printer machine bay",
                "motion": "camera pans the sealed chamber",
                "lighting": "neutral lab light",
                "background": "industrial lab",
                "objects": ["metal printer", "sealed chamber", "machine bay"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a metal 3D printer machine bay, neutral lab lighting, industrial lab",
            },
            {
                "goal": "The bed",
                "teaching_point": "Fine powder, thin layers",
                "shot": "diagram-style shot of a powder bed and recoater",
                "motion": "recoater spreads a thin layer",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["powder bed", "recoater", "thin layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a metal powder bed, clean engineering visualization on a dark background",
            },
            {
                "goal": "The melt",
                "teaching_point": "Laser melts the path",
                "shot": "diagram-style shot of a laser tracing a layer",
                "motion": "laser melts the powder path",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["laser beam", "melt pool", "layer path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a laser melting metal powder, clean engineering visualization on a dark background",
            },
            {
                "goal": "The control",
                "teaching_point": "Tight heat, no warp",
                "shot": "diagram-style shot of the thermal control curve",
                "motion": "temperature traces stay in bounds",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thermal curve", "safe band", "heat cycles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of metal printing thermal control, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Real metal, real strength",
                "shot": "wide hero shot of a finished metal part beside its build chamber",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["metal part", "build chamber", "powder"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished metal part beside its build chamber, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A laser melting a powder bed with a thermal control curve",
            "subject": "metal 3D printing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "melt pool center, curve above",
            "text": "A FOUNDRY THAT DRAWS",
            "elements": ["laser beam", "powder bed", "thermal curve"],
            "style": "geometry studio photography",
            "mood": "melted, sealed, drawn",
            "prompt": "photograph of a laser melting a metal powder bed with a thermal control curve, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Metal 3D Printing: A Foundry That Draws",
            "title_variations": [
                "How Does Metal 3D Printing Work",
                "Metal Additive Manufacturing",
                "DMLS Explained",
                "Printed Metal Parts",
                "Powder Bed Fusion",
            ],
            "description": "Metal 3D printing builds parts layer by layer from powder or wire, and the workhorse is powder bed fusion: a laser or electron beam melts fine metal powder into a part, one layer at a time, inside a sealed machine with an inert atmosphere. The heat is extreme, so temperature is controlled tightly to avoid warping and cracking. This short spreads the bed, melts the path, and shows a foundry that draws instead of pouring.",
            "hashtags": ["#Metal3DPrinting", "#DMLS", "#AdditiveManufacturing", "#SLM"],
            "seo_keywords": [
                "how does metal 3d printing work",
                "metal additive manufacturing",
                "DMLS explained",
                "printed metal parts",
                "powder bed fusion",
                "laser metal powder",
                "metal printing industry",
            ],
        },
        "fact_check": [
            "Metal prints from powder.",
            "Layers melt one by one.",
            "The chamber is inert.",
            "Heat control prevents warping.",
            "Parts are real metal.",
        ],
    },
    {
        "topic": "Vapor Smoothing Systems",
        "core_question": "How do you make a print look injection molded without sanding?",
        "learning_objective": "The viewer understands vapor smoothing.",
        "engineering_summary": "Vapor smoothing is a chemical bath for the surface: the part is exposed to a solvent vapor that melts a thin skin of plastic, and the skin flows together into a glossy layer as the vapor works. The classic is ABS with acetone, which turns the white layers into a smooth gloss; newer systems use engineered filaments with dedicated solvent machines. The catch is control: too much vapor melts the detail, too little leaves the layers, and the fumes demand ventilation. Vapor smoothing trades texture for gloss at the cost of precision.",
        "real_world_application": "Cosmetic ABS parts and prototypes get their gloss from vapor, not sanding.",
        "common_misconceptions": [
            "It works on any plastic (it needs a solvent that matches the material)",
            "It only shines (too much vapor melts fine detail)",
            "It is a garage trick (fumes make it a ventilation problem)",
        ],
        "teaching_strategy": "Show the vapor bath, then the glossy skin forming.",
        "script": "Vapor smoothing is a chemical bath for the surface: the part is exposed to a solvent vapor that melts a thin skin of plastic, and the skin flows together into a glossy layer as the vapor works. The classic is ABS with acetone, which turns the white layers into a smooth gloss; newer systems use engineered filaments with dedicated solvent machines. The catch is control: too much vapor melts the detail, too little leaves the layers, and the fumes demand ventilation. Vapor smoothing trades texture for gloss at the cost of precision.",
        "text_overlay": [
            "SOLVENT VAPOR, THIN SKIN",
            "ABS AND ACETONE CLASSIC",
            "TOO MUCH MELTS THE DETAIL",
            "GLOSS FOR PRECISION",
        ],
        "scenes": [
            {
                "goal": "Hook: the rough layers",
                "teaching_point": "White ridges everywhere",
                "shot": "close-up shot of rough layer lines on a print",
                "motion": "light rakes the ridges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["layer ridges", "rough surface", "print"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of rough layer lines on a print, bright task lighting, print lab",
            },
            {
                "goal": "The vapor",
                "teaching_point": "Solvent melts the skin",
                "shot": "diagram-style shot of a part in solvent vapor",
                "motion": "vapor wraps the part, skin melts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["vapor cloud", "part skin", "melting layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of vapor smoothing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The gloss",
                "teaching_point": "Skin flows smooth",
                "shot": "close-up shot of a glossy smoothed part surface",
                "motion": "light glides over the gloss",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["glossy surface", "smooth skin", "reflection"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a glossy vapor-smoothed surface, bright task lighting, print lab",
            },
            {
                "goal": "The catch",
                "teaching_point": "Detail melts, fumes vent",
                "shot": "diagram-style shot of control and ventilation notes",
                "motion": "time and fume warnings light up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["time dial", "fume vent", "detail warning"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of vapor smoothing control warnings, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Gloss for precision",
                "shot": "wide hero shot of a glossy part beside its rough twin",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["glossy part", "rough twin", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a glossy part beside its rough twin, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part in solvent vapor turning from rough to glossy",
            "subject": "vapor smoothing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, vapor around",
            "text": "GLOSS FOR PRECISION",
            "elements": ["vapor cloud", "glossy part", "rough twin"],
            "style": "geometry studio photography",
            "mood": "melted, glossy, traded",
            "prompt": "photograph of a part in solvent vapor turning from rough to glossy with a rough twin beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Vapor Smoothing Systems: Gloss for Precision",
            "title_variations": [
                "What Is Vapor Smoothing",
                "Vapor Smoothing ABS",
                "Polysmooth Vapor",
                "Fume Smoothing Print",
                "Vapor Polish Guide",
            ],
            "description": "Vapor smoothing is a chemical bath for the surface: the part is exposed to a solvent vapor that melts a thin skin of plastic, and the skin flows together into a glossy layer. The classic is ABS with acetone; newer systems use engineered filaments with dedicated machines. The catch is control: too much vapor melts the detail, and the fumes demand ventilation. This short roughs a part, baths it in vapor, and shows gloss traded for precision.",
            "hashtags": ["#VaporSmoothing", "#Acetone", "#Polysmooth", "#3DPrinting"],
            "seo_keywords": [
                "what is vapor smoothing",
                "vapor smoothing ABS",
                "polysmooth vapor",
                "fume smoothing",
                "vapor polish print",
                "acetone gloss print",
                "vapor smoothing detail",
            ],
        },
        "fact_check": [
            "Vapor melts a thin skin.",
            "ABS works with acetone.",
            "The skin flows glossy.",
            "Too much melts detail.",
            "Fumes need ventilation.",
        ],
    },
    {
        "topic": "Heat Gun Deburring",
        "core_question": "Can a heat gun actually clean up your prints?",
        "learning_objective": "The viewer understands heat gun deburring.",
        "engineering_summary": "A heat gun removes the lightest print flaws in seconds: thin strings and wisps shrink and vanish under a quick blast, and tiny zits can be kissed smooth. The danger is the same heat: too long on the surface melts detail, warps thin walls, and discolors the plastic, so the technique is a fast sweep, not a hover. The gun works best on strings and light burrs, and worst on deep damage. The heat gun is a finishing scalpel, and control is the whole trick.",
        "real_world_application": "String removal is the most common heat gun job on printed parts.",
        "common_misconceptions": [
            "The gun fixes everything (it only removes the lightest flaws)",
            "More heat is faster (it melts the part's detail)",
            "It is the same as a soldering iron (a sweep beats a touch)",
        ],
        "teaching_strategy": "Show a stringy part, then the fast sweep cleaning it.",
        "script": "A heat gun removes the lightest print flaws in seconds: thin strings and wisps shrink and vanish under a quick blast, and tiny zits can be kissed smooth. The danger is the same heat: too long on the surface melts detail, warps thin walls, and discolors the plastic, so the technique is a fast sweep, not a hover. The gun works best on strings and light burrs, and worst on deep damage. The heat gun is a finishing scalpel, and control is the whole trick.",
        "text_overlay": [
            "STRINGS SHRINK AND VANISH",
            "A FAST SWEEP, NOT A HOVER",
            "TOO LONG MELTS DETAIL",
            "A FINISHING SCALPEL",
        ],
        "scenes": [
            {
                "goal": "Hook: the stringy part",
                "teaching_point": "Wisps everywhere",
                "shot": "close-up shot of a stringy print with thin wisps",
                "motion": "light catches the strands",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["stringy print", "thin wisps", "strands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a stringy print with thin wisps, bright task lighting, print lab",
            },
            {
                "goal": "The sweep",
                "teaching_point": "Fast pass, strings vanish",
                "shot": "medium shot of a heat gun sweeping a print",
                "motion": "gun passes quickly, strings shrink",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["heat gun", "sweep pass", "print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a heat gun sweeping a print, neutral lab lighting, workbench",
            },
            {
                "goal": "The danger",
                "teaching_point": "Too long melts detail",
                "shot": "close-up shot of melted detail on an overheated print",
                "motion": "softened edge droops",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["melted detail", "drooped edge", "overheat"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of melted detail on an overheated print, bright task lighting, print lab",
            },
            {
                "goal": "The limits",
                "teaching_point": "Light flaws only",
                "shot": "diagram-style shot of what the gun can fix",
                "motion": "strings yes, deep damage no",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["string fix", "burr fix", "damage no"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of heat gun limits, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Control is the trick",
                "shot": "wide hero shot of a clean part beside the heat gun",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean part", "heat gun", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean part beside a heat gun, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A heat gun sweeping a stringy print with a melted edge warning",
            "subject": "heat gun deburring",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gun center, print below",
            "text": "A FAST SWEEP, NOT A HOVER",
            "elements": ["heat gun", "stringy print", "melt warning"],
            "style": "geometry studio photography",
            "mood": "swept, shrunk, controlled",
            "prompt": "photograph of a heat gun sweeping a stringy print with a melt warning beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heat Gun Deburring: A Fast Sweep, Not a Hover",
            "title_variations": [
                "Can I Use a Heat Gun on Prints",
                "Heat Gun Deburr Print",
                "String Removal Heat",
                "Heat Smoothing Print",
                "Heat Gun Stringing Fix",
            ],
            "description": "A heat gun removes the lightest print flaws in seconds: thin strings and wisps shrink and vanish under a quick blast, and tiny zits can be kissed smooth. The danger is the same heat: too long on the surface melts detail, warps thin walls, and discolors plastic, so the technique is a fast sweep, not a hover. This short sweeps a stringy part and shows the heat gun as a finishing scalpel where control is the whole trick.",
            "hashtags": ["#HeatGun", "#Deburring", "#Strings", "#3DPrinting"],
            "seo_keywords": [
                "can I use a heat gun on prints",
                "heat gun deburr",
                "string removal heat gun",
                "heat smoothing print",
                "heat gun stringing",
                "fast sweep heat gun",
                "melted detail warning",
            ],
        },
        "fact_check": [
            "Heat guns remove strings.",
            "Wisps shrink in a sweep.",
            "Hovering melts detail.",
            "Light flaws only.",
            "Control is the trick.",
        ],
    },
    {
        "topic": "Chemical Smoothing Resin",
        "core_question": "How do you get resin prints glassy without sanding?",
        "learning_objective": "The viewer understands resin smoothing.",
        "engineering_summary": "Resin prints cure hard, but a short dip in a solvent can soften and flow the surface: isopropyl alcohol dissolves the outermost layer of uncured and semi-cured resin, and the part dries smooth, though the technique needs care. The real glass comes from post-cure and clear coats, because the solvent cannot flow a fully cured shell. The method trades a little detail and a careful rinse for a glass-like finish. Resin smoothing is a chemistry step, not a sanding shortcut.",
        "real_world_application": "Miniatures and clear parts get their gloss from solvent and clear coat.",
        "common_misconceptions": [
            "Solvent makes anything glossy (cured resin needs clear coats)",
            "Longer dips are smoother (they eat detail and soften walls)",
            "It replaces curing (the part must still cure afterward)",
        ],
        "teaching_strategy": "Show the dip, then the gloss after cure and coat.",
        "script": "Resin prints cure hard, but a short dip in a solvent can soften and flow the surface: isopropyl alcohol dissolves the outermost layer of uncured and semi-cured resin, and the part dries smooth, though the technique needs care. The real glass comes from post-cure and clear coats, because the solvent cannot flow a fully cured shell. The method trades a little detail and a careful rinse for a glass-like finish. Resin smoothing is a chemistry step, not a sanding shortcut.",
        "text_overlay": [
            "SOLVENT SOFTENS THE SKIN",
            "GLASS COMES FROM CURE AND COAT",
            "LONGER DIPS EAT DETAIL",
            "A CHEMISTRY STEP, NOT SANDING",
        ],
        "scenes": [
            {
                "goal": "Hook: the matte part",
                "teaching_point": "Cured but not glossy",
                "shot": "close-up shot of a matte resin print",
                "motion": "light sits flat on the surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["matte print", "flat surface", "resin part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a matte resin print, bright task lighting, print lab",
            },
            {
                "goal": "The dip",
                "teaching_point": "Solvent flows the skin",
                "shot": "diagram-style shot of a part in an alcohol bath",
                "motion": "outer skin softens in the solvent",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["alcohol bath", "part skin", "softening layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a resin part in an alcohol bath, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cure",
                "teaching_point": "Post-cure sets the shell",
                "shot": "diagram-style shot of a part curing under light",
                "motion": "UV light hardens the surface",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["UV light", "curing part", "hard shell"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of post-curing a resin part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The coat",
                "teaching_point": "Clear coat brings glass",
                "shot": "close-up shot of clear coat being applied to a part",
                "motion": "glossy coat flows over the surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["clear coat", "glossy surface", "spray"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of clear coat being applied to a resin part, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Chemistry, not sanding",
                "shot": "wide hero shot of a glassy resin part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["glassy part", "clear surface", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a glassy resin part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part in an alcohol bath with cure light and clear coat stages",
            "subject": "resin smoothing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bath center, coat beside",
            "text": "A CHEMISTRY STEP, NOT SANDING",
            "elements": ["alcohol bath", "cure light", "clear coat"],
            "style": "geometry studio photography",
            "mood": "dipped, cured, glassed",
            "prompt": "photograph of a resin part in an alcohol bath with a cure light and clear coat, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Chemical Smoothing Resin: A Chemistry Step, Not Sanding",
            "title_variations": [
                "How to Smooth Resin Prints",
                "Chemical Polish Resin",
                "Solvent Dip Resin",
                "IPA Polish Resin",
                "Glossy Resin Finish",
            ],
            "description": "Resin prints cure hard, but a short dip in a solvent can soften and flow the surface: isopropyl alcohol dissolves the outermost layer of uncured and semi-cured resin, and the part dries smooth. The real glass comes from post-cure and clear coats, because the solvent cannot flow a fully cured shell. This short dips the part, cures the shell, and coats the gloss, showing resin smoothing as a chemistry step, not a sanding shortcut.",
            "hashtags": ["#ResinSmoothing", "#Resin", "#PostCure", "#3DPrinting"],
            "seo_keywords": [
                "how to smooth resin prints",
                "chemical polish resin",
                "solvent dip resin",
                "IPA polish resin",
                "glossy resin finish",
                "resin clear coat",
                "resin post cure gloss",
            ],
        },
        "fact_check": [
            "Solvent flows the skin.",
            "IPA dissolves uncured resin.",
            "Glass comes from coats.",
            "Long dips eat detail.",
            "Curing still matters.",
        ],
    },
    {
        "topic": "Polishing Clear Prints",
        "core_question": "How do you make transparent prints actually clear?",
        "learning_objective": "The viewer understands polishing clear prints.",
        "engineering_summary": "A clear print is translucent, not transparent, because the layer ridges scatter light; polishing removes the scatter by smoothing the surface into a continuous film. The process is a grit ladder: sand from coarse to very fine, then buff with a plastic polish until the ridges disappear and light passes straight through. The part also needs the right start: a thin-walled, high-temp print with the nozzle hot enough to weld layers, because polishing can only smooth what the layers already fused. Clarity is earned in layers and finished in grit.",
        "real_world_application": "Light pipes, lenses, and display covers are polished to true clarity.",
        "common_misconceptions": [
            "Sanding alone makes it clear (buffing and polish finish the job)",
            "Any print can go clear (thick walls stay cloudy inside)",
            "Clear filament prints clear (layers always scatter light)",
        ],
        "teaching_strategy": "Show the grit ladder, then the light passing through.",
        "script": "A clear print is translucent, not transparent, because the layer ridges scatter light; polishing removes the scatter by smoothing the surface into a continuous film. The process is a grit ladder: sand from coarse to very fine, then buff with a plastic polish until the ridges disappear and light passes straight through. The part also needs the right start: a thin-walled, high-temp print with the nozzle hot enough to weld layers, because polishing can only smooth what the layers already fused. Clarity is earned in layers and finished in grit.",
        "text_overlay": [
            "RIDGES SCATTER LIGHT",
            "SAND COARSE TO FINE, THEN BUFF",
            "WELD THE LAYERS FIRST",
            "CLARITY IN LAYERS, FINISHED IN GRIT",
        ],
        "scenes": [
            {
                "goal": "Hook: the cloudy lens",
                "teaching_point": "Ridges scatter light",
                "shot": "close-up shot of a cloudy transparent print",
                "motion": "light diffuses through the ridges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["cloudy print", "scattered light", "ridges"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a cloudy transparent print, bright task lighting, print lab",
            },
            {
                "goal": "The ladder",
                "teaching_point": "Coarse to fine grit",
                "shot": "diagram-style shot of the grit ladder",
                "motion": "grit steps from coarse to fine",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["coarse step", "fine step", "grit ladder"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the polishing grit ladder, clean engineering visualization on a dark background",
            },
            {
                "goal": "The buff",
                "teaching_point": "Polish into a film",
                "shot": "close-up shot of buffing a clear part",
                "motion": "buff pad glides on the surface",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["buff pad", "clear part", "polish film"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of buffing a clear printed part, bright task lighting, workbench",
            },
            {
                "goal": "The start",
                "teaching_point": "Thin walls, hot nozzle",
                "shot": "diagram-style shot of the clarity start recipe",
                "motion": "thin wall and hot nozzle notes set",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thin wall", "hot nozzle", "welded layers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the clear print recipe, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Light passes straight",
                "shot": "wide hero shot of light beaming through a polished part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["polished part", "light beam", "clear lens"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of light beaming through a polished clear part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A grit ladder beside a buffed part with light passing through",
            "subject": "polishing clear prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, ladder beside",
            "text": "CLARITY IN LAYERS, FINISHED IN GRIT",
            "elements": ["grit ladder", "buff pad", "light beam"],
            "style": "geometry studio photography",
            "mood": "scattered, buffed, clear",
            "prompt": "photograph of a grit ladder beside a buffed clear part with a light beam, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Polishing Clear Prints: Clarity in Layers, Finished in Grit",
            "title_variations": [
                "How to Make Prints Glossy",
                "Polishing Clear Prints",
                "Transparent Print Finish",
                "Buffing 3D Prints",
                "Clear PLA Polish",
            ],
            "description": "A clear print is translucent, not transparent, because the layer ridges scatter light; polishing removes the scatter by smoothing the surface into a continuous film. The process is a grit ladder: sand from coarse to very fine, then buff with a plastic polish until light passes straight through. The part also needs a thin wall and hot nozzle so the layers weld. This short climbs the ladder, buffs the film, and shows clarity earned in layers and finished in grit.",
            "hashtags": ["#ClearPrints", "#Polishing", "#Transparent", "#3DPrinting"],
            "seo_keywords": [
                "how to make prints glossy",
                "polishing clear prints",
                "transparent print finish",
                "buffing 3D prints",
                "clear PLA polish",
                "grit ladder sanding",
                "light pipe print",
            ],
        },
        "fact_check": [
            "Ridges scatter light.",
            "Sanding smooths the surface.",
            "Buffing makes the film.",
            "Layers must weld first.",
            "Thin walls help clarity.",
        ],
    },
    {
        "topic": "Dyeing Nylon Parts",
        "core_question": "Can you recolor a printed part after it is done?",
        "learning_objective": "The viewer understands dyeing nylon parts.",
        "engineering_summary": "Nylon parts can be dyed after printing because nylon is a thirsty polymer: the dye diffuses into the plastic itself, not just the surface, so the color is part of the part. The method is a hot dye bath, like fabric dye, with the part cleaned and soaked until the color penetrates. The catch is temperature: the bath must be hot to open the nylon, but not hot enough to warp the print. The result is a part colored through, not painted on. Dyeing is for the materials that drink, and nylon drinks.",
        "real_world_application": "Custom-colored nylon gears and brackets dye true without paint layers.",
        "common_misconceptions": [
            "Any filament dyes (only thirsty materials take the color)",
            "Dye paints the surface (it penetrates the polymer)",
            "Boiling makes it faster (heat warps the part first)",
        ],
        "teaching_strategy": "Show the dye bath, then the color diffusing inward.",
        "script": "Nylon parts can be dyed after printing because nylon is a thirsty polymer: the dye diffuses into the plastic itself, not just the surface, so the color is part of the part. The method is a hot dye bath, like fabric dye, with the part cleaned and soaked until the color penetrates. The catch is temperature: the bath must be hot to open the nylon, but not hot enough to warp the print. The result is a part colored through, not painted on. Dyeing is for the materials that drink, and nylon drinks.",
        "text_overlay": [
            "COLOR DIFFUSES INSIDE",
            "A HOT BATH, LIKE FABRIC DYE",
            "HOT TO OPEN, NOT TO WARP",
            "COLORED THROUGH, NOT PAINTED",
        ],
        "scenes": [
            {
                "goal": "Hook: the white gears",
                "teaching_point": "Printed, but only in white",
                "shot": "wide shot of white nylon parts on a bench",
                "motion": "camera pans the pale gears",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["white gears", "pale parts", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of white nylon parts on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "The drink",
                "teaching_point": "Dye diffuses inward",
                "shot": "diagram-style shot of dye entering the polymer",
                "motion": "color arrows soak into the part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dye arrows", "nylon part", "color front"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dye diffusing into nylon, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bath",
                "teaching_point": "Hot dye bath",
                "shot": "medium shot of parts soaking in a dye bath",
                "motion": "parts sit in the hot color",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["dye bath", "soaking parts", "hot color"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of nylon parts soaking in a hot dye bath, neutral lab lighting, workshop",
            },
            {
                "goal": "The catch",
                "teaching_point": "Hot to open, not to warp",
                "shot": "diagram-style shot of the temperature window",
                "motion": "needle sits in the safe band",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temp needle", "safe band", "warp zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the dye bath temperature window, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Colored through",
                "shot": "wide hero shot of a dyed part cut open showing color inside",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dyed part", "cut face", "color inside"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dyed part cut open showing color inside, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hot dye bath with color diffusing through a cut nylon part",
            "subject": "dyeing nylon parts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bath center, cut part beside",
            "text": "COLORED THROUGH, NOT PAINTED",
            "elements": ["dye bath", "cut part", "color front"],
            "style": "geometry studio photography",
            "mood": "soaked, diffused, through-colored",
            "prompt": "photograph of a hot dye bath with color diffusing through a cut nylon part, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dyeing Nylon Parts: Colored Through, Not Painted",
            "title_variations": [
                "How to Dye Nylon Parts",
                "Nylon Dye Guide",
                "Rit Dye Nylon Print",
                "Color Nylon Parts",
                "Dye 3D Printed Parts",
            ],
            "description": "Nylon parts can be dyed after printing because nylon is a thirsty polymer: the dye diffuses into the plastic itself, not just the surface, so the color is part of the part. The method is a hot dye bath, like fabric dye, with the part cleaned and soaked until the color penetrates. The bath must be hot to open the nylon, but not hot enough to warp the print. This short soaks the gears and cuts one open to show color through, not paint on.",
            "hashtags": ["#DyeNylon", "#Nylon", "#Dyeing", "#3DPrinting"],
            "seo_keywords": [
                "how to dye nylon parts",
                "nylon dye guide",
                "rit dye nylon print",
                "color nylon parts",
                "dye 3D printed parts",
                "dye bath temperature",
                "dye diffuses polymer",
            ],
        },
        "fact_check": [
            "Nylon accepts dye deeply.",
            "The dye diffuses inward.",
            "Hot baths open the nylon.",
            "Too hot warps the part.",
            "The color is in the part.",
        ],
    },
    {
        "topic": "Weatherproofing Prints",
        "core_question": "How do you stop outdoor prints from failing in a season?",
        "learning_objective": "The viewer understands weatherproofing prints.",
        "engineering_summary": "Outdoor prints die in layers: UV degrades the polymer, moisture works into the layers, and temperature cycles stress the walls, so weatherproofing is a layered defense. The first layer is the material: PETG and ASA resist UV better than PLA. The second is the surface: a UV-blocking coat or paint seals the layers from moisture. The third is the design: thick walls, rounded edges, and no water traps. Weatherproofing is not one product; it is material, coat, and geometry working together.",
        "real_world_application": "Garden brackets, mounts, and signs survive seasons with the full defense.",
        "common_misconceptions": [
            "One coat is enough (material and geometry matter too)",
            "PLA is fine outdoors (UV and heat break it down fast)",
            "Waterproofing is the whole job (UV kills it even dry)",
        ],
        "teaching_strategy": "Show an aged outdoor part, then the three-layer defense.",
        "script": "Outdoor prints die in layers: UV degrades the polymer, moisture works into the layers, and temperature cycles stress the walls, so weatherproofing is a layered defense. The first layer is the material: PETG and ASA resist UV better than PLA. The second is the surface: a UV-blocking coat or paint seals the layers from moisture. The third is the design: thick walls, rounded edges, and no water traps. Weatherproofing is not one product; it is material, coat, and geometry working together.",
        "text_overlay": [
            "UV, MOISTURE, TEMP CYCLES",
            "PETG AND ASA RESIST",
            "SEAL THE LAYERS, ROUND THE EDGES",
            "A LAYERED DEFENSE",
        ],
        "scenes": [
            {
                "goal": "Hook: the aged part",
                "teaching_point": "UV and moisture wreck it",
                "shot": "close-up shot of a faded cracked outdoor print",
                "motion": "camera pans the sun damage",
                "lighting": "bright daylight",
                "background": "outdoor wall",
                "objects": ["faded print", "cracks", "sun damage"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a faded cracked outdoor print, bright daylight, outdoor wall",
            },
            {
                "goal": "The killers",
                "teaching_point": "UV, water, thermal cycles",
                "shot": "diagram-style shot of the three attackers",
                "motion": "sun, rain, and heat arrows hit",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["UV arrow", "water arrow", "temp arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of outdoor print attackers, clean engineering visualization on a dark background",
            },
            {
                "goal": "The material",
                "teaching_point": "PETG and ASA resist",
                "shot": "diagram-style shot of material UV bars",
                "motion": "PLA bar drops, PETG and ASA hold",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["PLA bar", "PETG bar", "ASA bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of outdoor material resistance bars, clean engineering visualization on a dark background",
            },
            {
                "goal": "The coat",
                "teaching_point": "UV coat seals the layers",
                "shot": "close-up shot of a UV coat being applied to a print",
                "motion": "coat covers the surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["UV coat", "spray", "sealed surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a UV coat being applied to a print, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "All three layers",
                "shot": "wide hero shot of a healthy outdoor part mounted in sun",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["healthy part", "mount", "sunlight"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a healthy outdoor part mounted in sunlight, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A faded cracked print beside material bars and a UV coat spray",
            "subject": "weatherproofing prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "faded print center, coat beside",
            "text": "A LAYERED DEFENSE",
            "elements": ["faded print", "UV coat", "material bars"],
            "style": "geometry studio photography",
            "mood": "aged, sealed, defended",
            "prompt": "photograph of a faded cracked print beside material bars and a UV coat spray, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Weatherproofing Prints: A Layered Defense",
            "title_variations": [
                "How to Waterproof Prints",
                "Weatherproof Print Guide",
                "Seal Print UV Coat",
                "Outdoor 3D Print Fix",
                "UV Resistant Prints",
            ],
            "description": "Outdoor prints die in layers: UV degrades the polymer, moisture works into the layers, and temperature cycles stress the walls, so weatherproofing is a layered defense. The first layer is the material, with PETG and ASA resisting UV better than PLA. The second is the surface, with a UV-blocking coat sealing the layers. The third is the design, with thick walls and rounded edges. This short ages a part, ranks the materials, and builds the full defense.",
            "hashtags": ["#Weatherproofing", "#UVProtection", "#OutdoorPrints", "#3DPrinting"],
            "seo_keywords": [
                "how to waterproof prints",
                "weatherproof print",
                "seal print UV coat",
                "outdoor 3D print",
                "UV resistant prints",
                "PETG ASA outdoor",
                "outdoor print defense",
            ],
        },
        "fact_check": [
            "UV degrades the polymer.",
            "Moisture enters the layers.",
            "Temperature cycles stress walls.",
            "PETG and ASA resist UV.",
            "Coats seal the surface.",
        ],
    },
]