"""Batch 8: extrusion faults, speed trade-offs, fasteners, machining, physics, and measurement."""

CURATED = [
    # ======================================================================
    {
        "topic": "Under-Extrusion",
        "core_question": "Why is my print coming out thin and gappy, and how do I fix under-extrusion?",
        "learning_objective": "The viewer can trace under-extrusion through the extrusion chain: flow, temperature, clogs, feed, and speed.",
        "engineering_summary": "Under-extrusion means less plastic leaves the nozzle than the slicer expects: gaps between lines, thin walls, and weak layers. Work the chain in order: (1) partial clogs and heat creep restrict the melt path; (2) wrong temperature makes the melt too stiff to flow at the demanded rate; (3) low flow or e-step settings under-feed; (4) filament feed problems - grinding, tangled spools, or high friction in a Bowden tube - starve the hotend; (5) printing faster than the hotend can melt (volumetric flow limit) starves the nozzle. The diagnostic order is feed, temperature, flow, speed - and most cases end at speed or a partial clog.",
        "real_world_application": "Print farms log extrusion quality per job because under-extrusion is the top cause of rejected functional parts; a volumetric-flow test before fast prints saves hours of failed runs.",
        "common_misconceptions": [
            "Under-extrusion is always the extruder (speed and temperature starve the nozzle just as often)",
            "More flow fixes everything (it masks the cause and over-extrudes elsewhere)",
            "It's a slicer display issue (the print really is short of material)",
        ],
        "teaching_strategy": "Show a gappy part, then walk the extrusion chain with a checklist from feed to speed.",
        "script": "Gaps between lines? Thin walls? That's under-extrusion: less plastic than the slicer ordered. Chase the chain in order. First, the feed: is the extruder grinding, or the spool tangled? Next, temperature: too cold, and stiff melt can't flow fast enough. Then flow and e-steps - is the printer under-feeding on purpose? Last, speed: every hotend has a volumetric limit, and past it, no setting helps except slowing down. Nine times out of ten, the culprit is speed or a partial clog. Feed, heat, flow, speed - one of them is lying.",
        "text_overlay": [
            "GAPS = STARVED NOZZLE",
            "1. FEED 2. HEAT",
            "3. FLOW 4. SPEED",
            "HOTENDS HAVE A FLOW LIMIT",
        ],
        "scenes": [
            {
                "goal": "Hook: the gappy print",
                "teaching_point": "Thin walls and gaps mean missing plastic",
                "shot": "macro close-up of a print with gaps between extrusion lines",
                "motion": "slow push-in on the gaps",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["gappy print", "thin walls"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D print with gaps between extrusion lines, raking side light, dark bench",
            },
            {
                "goal": "The feed check",
                "teaching_point": "Grinding and tangles starve the hotend",
                "shot": "close-up of filament grinding in the extruder with shavings",
                "motion": "extruder skips and shavings fall",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["extruder", "grinding filament", "shavings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of filament grinding in a 3D printer extruder with plastic shavings, bright task lighting, print lab",
            },
            {
                "goal": "The temperature check",
                "teaching_point": "Cold melt flows too slowly",
                "shot": "macro shot of stiff, wavy extrusion from the nozzle",
                "motion": "plastic comes out rough and slow",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["nozzle", "stiff extrusion", "temperature readout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of stiff wavy extrusion flowing from a nozzle, warm task light, dark bench",
            },
            {
                "goal": "The speed check",
                "teaching_point": "Volumetric flow limits every hotend",
                "shot": "graphic-style shot of a nozzle starving at high speed",
                "motion": "speed rises and extrusion thins",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle diagram", "flow curve", "speed scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle starvation diagram with a flow curve on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fix the chain, not the symptom",
                "shot": "wide hero shot of a dense, solid print fresh off the printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dense print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dense solid 3D print with full walls on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle with a starvation gauge: feed, heat, flow, speed",
            "subject": "gappy print with a four-step checklist",
            "background": "dark print lab blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "gappy print left, checklist right",
            "text": "UNDER-EXTRUSION",
            "elements": ["gappy print", "checklist", "nozzle"],
            "style": "diagnostic macro photography",
            "mood": "thin, corrective, ordered",
            "prompt": "macro photograph of a gappy 3D print with a four-step under-extrusion checklist beside it, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Under-Extrusion: The Chain",
            "title_variations": [
                "Why Is My Print Gappy?",
                "Fix Under-Extrusion in Order",
                "Thin Walls and Gaps Explained",
                "Under-Extrusion Diagnostic",
                "How to Fix Starved Extrusion",
            ],
            "description": "Under-extrusion means less plastic leaves the nozzle than the slicer expects: gaps between lines, thin walls, and weak layers. Chase the chain in order: the feed (grinding filament, tangled spools, Bowden friction), temperature (cold melt can't flow), flow and e-steps (systematic under-feeding), and speed - every hotend has a volumetric flow limit, and past it the nozzle starves. Nine times out of ten the culprit is print speed or a partial clog. This short walks the extrusion chain as a checklist so you fix the actual cause instead of masking it with flow compensation.",
            "hashtags": ["#UnderExtrusion", "#3Dprinting", "#Troubleshooting", "#Extrusion"],
            "seo_keywords": [
                "under extrusion fix",
                "why is my print gappy",
                "thin walls 3d print",
                "under-extrusion causes",
                "extruder grinding filament",
                "volumetric flow limit",
                "gaps between lines 3d print",
            ],
        },
        "fact_check": [
            "Under-extrusion appears as gaps, thin walls, and weak interlayer bonding.",
            "Extruder grinding and spool tangles starve the hotend mechanically.",
            "Low melt temperature raises melt viscosity and reduces achievable flow rate.",
            "Every hotend has a volumetric flow ceiling set by heating power and melt zone length.",
            "Flow or e-step compensation masks causes and risks over-extrusion elsewhere in the print.",
        ],
    },
    # ======================================================================
    {
        "topic": "Print Speed vs Quality",
        "core_question": "How much does print speed actually cost in quality?",
        "learning_objective": "The viewer can explain where speed hurts quality, set per-feature speeds, and find their machine's quality ceiling.",
        "engineering_summary": "Speed affects quality through three mechanisms: (1) flow starvation - past the hotend's volumetric limit, the melt can't keep up, causing under-extrusion and gaps; (2) motion dynamics - high acceleration and jerk excite machine resonance, producing ringing and ghosting; (3) cooling - fast layers leave less time for plastic to solidify, so overhangs and bridges sag and small features soften. Slowing specific features buys quality: first layers, perimeters, overhangs, bridges, small features, and top layers. The flow limit is a wall; the resonance and cooling effects are continuous trade-offs. Many printers print 60-80% of their max speed with near-full quality.",
        "real_world_application": "Production shops fix cosmetic and structural features at lower speeds while printing fast interiors; speed is tuned per feature, not as one global number.",
        "common_misconceptions": [
            "Speed only affects cosmetics (flow starvation creates structural under-extrusion)",
            "Faster is always worse (motion resonance and cooling depend on acceleration, not just speed)",
            "One speed setting controls everything (per-feature speeds are the real control)",
        ],
        "teaching_strategy": "Print the same part at three speeds and compare, then reveal the three mechanisms and the per-feature speed menu.",
        "script": "Speed kills quality through three doors. One: flow. Every hotend has a melt limit; past it, the nozzle starves and gaps appear. Two: motion. Slam the acceleration and the frame rings - you see it as ghosting on walls. Three: cooling. Fast layers don't solidify, so overhangs sag and bridges droop. The fix isn't one speed - it's per-feature speed. Slow the first layer, perimeters, overhangs, and top layers. Print the boring interior fast. Same machine, same filament, near-perfect detail. Speed is a dial per feature, not one global number.",
        "text_overlay": [
            "FLOW | MOTION | COOLING",
            "STARVED NOZZLE = GAPS",
            "ACCELERATION = GHOSTING",
            "SLOW DETAIL, FAST CORE",
        ],
        "scenes": [
            {
                "goal": "Hook: three speeds",
                "teaching_point": "The same part, three quality levels",
                "shot": "wide shot of three identical parts printed at different speeds",
                "motion": "camera slides along the parts",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["three test parts", "speed labels"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of three identical 3D printed test parts at different quality levels, raking side light, dark bench",
            },
            {
                "goal": "Flow starvation",
                "teaching_point": "The hotend melt ceiling",
                "shot": "graphic-style shot of a nozzle thinning at high speed",
                "motion": "extrusion narrows as speed climbs",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle diagram", "extrusion width", "speed scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle flow starvation diagram with extrusion thinning at speed on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Motion resonance",
                "teaching_point": "Acceleration excites ghosting",
                "shot": "macro shot of a ringing print wall beside a clean wall",
                "motion": "cross-cut between the surfaces",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["ringing wall", "clean wall"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a ringing print wall beside a clean wall, raking side light, dark bench",
            },
            {
                "goal": "Cooling limits",
                "teaching_point": "Fast layers don't solidify",
                "shot": "macro shot of a sagging overhang on a fast print",
                "motion": "slow push-in on the droop",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["sagging overhang", "fast print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a sagging overhang on a fast 3D print, bright task light, dark bench",
            },
            {
                "goal": "Per-feature speeds",
                "teaching_point": "Slow detail, fast core",
                "shot": "CAD-slicer-style shot of a part with colored speed zones",
                "motion": "speed zones highlight by feature",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["slicer preview", "speed zones", "part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer preview with colored speed zones on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Tune per feature, not per number",
                "shot": "wide hero shot of a fast, clean print completing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fast clean print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fast clean 3D print completing on the printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A speed dial split into feature zones",
            "subject": "test part with a speed dial overlay",
            "background": "dark machine shop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "part left, speed dial right",
            "text": "SPEED vs QUALITY",
            "elements": ["test part", "speed dial", "feature zones"],
            "style": "industrial macro photography",
            "mood": "tuned, balanced, clear",
            "prompt": "macro photograph of a 3D printed test part with a speed dial overlay split into feature zones, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Speed vs Quality: The Truth",
            "title_variations": [
                "Does Print Speed Matter?",
                "Fast Printing Without Sacrifice",
                "Speed Settings Explained",
                "Why Fast Prints Look Bad",
                "Tuning Print Speed per Feature",
            ],
            "description": "Speed hurts quality through three doors. Flow: every hotend has a melt ceiling, and past it the nozzle starves with gaps and thin walls. Motion: high acceleration excites machine resonance, showing up as ringing and ghosting. Cooling: fast layers don't solidify, so overhangs sag and bridges droop. The fix is per-feature speed - slow first layers, perimeters, overhangs, bridges, and top layers, while printing the interior fast. Many printers hold near-full quality at 60-80% of maximum speed. This short shows the three mechanisms and the feature-based speed menu that gets both speed and quality.",
            "hashtags": ["#Speed", "#3Dprinting", "#PrintQuality", "#Settings"],
            "seo_keywords": [
                "print speed vs quality",
                "does print speed matter",
                "fast 3d printing quality",
                "per feature speed",
                "ringing from speed",
                "volumetric flow limit",
                "print speed settings",
            ],
        },
        "fact_check": [
            "Volumetric flow is capped by hotend heating power and melt-zone length.",
            "Resonance artifacts like ringing scale with acceleration, not top speed alone.",
            "Insufficient per-layer cooling time degrades overhangs, bridges, and small features.",
            "Slicers expose per-feature speeds for first layer, perimeters, overhangs, bridges, and top layers.",
            "Quality-focused profiles typically cap speed well below the machine's mechanical maximum.",
        ],
    },
    # ======================================================================
    {
        "topic": "Heat-Set Inserts",
        "core_question": "How do I install heat-set inserts correctly?",
        "learning_objective": "The viewer can size a boss and hole, set the correct iron temperature, and install inserts flush and square.",
        "engineering_summary": "Heat-set inserts are brass cylinders with knurled or ribbed bodies and internal threads. A soldering iron or dedicated press heats the insert; the hot brass melts a pocket in the plastic, and the ribs grip the softened material as it cools, locking the insert in place. Success needs three numbers: hole diameter per the insert datasheet (typically the outer diameter minus the rib depth, e.g., 4.2 mm for an M3 insert), boss outer diameter about twice the insert diameter to prevent splitting, and iron temperature near the plastic's softening point - 230-270 C for PLA and PETG, lower for ABS. Installation is straight-down, no wobble, and the insert must sit flush with the boss top. Depth stops or printed guides ensure repeatability.",
        "real_world_application": "Enclosures, camera rigs, and production jigs use inserts wherever screws cycle repeatedly; a jig with depth stops turns installs into a one-second operation on a print farm.",
        "common_misconceptions": [
            "Inserts can go in any hole size (too tight splits the boss, too loose spins in use)",
            "Hotter is better (overheating melts the surrounding plastic and weakens the grip)",
            "Wobbling is harmless (side-to-side motion melts the boss out of round and ruins the hold)",
        ],
        "teaching_strategy": "Show a split boss and a spun insert as failures, then the three critical numbers and a clean install demo.",
        "script": "Brass threads, locked into plastic. Heat-set inserts melt themselves into a printed boss, and the grip is pure geometry: ribs dig into softened plastic and hold when it cools. Three numbers make or break it. The hole: follow the datasheet, about four point two millimeters for an M3. The boss: twice the insert diameter, so the plastic doesn't split. The iron: around two-forty Celsius - hot enough to sink, cool enough not to wreck the part. Press straight down, hold still, stop flush. Three numbers, zero wobble, and the insert is in it for life.",
        "text_overlay": [
            "RIBS GRIP SOFTENED PLASTIC",
            "HOLE: 4.2MM FOR M3",
            "BOSS: 2x INSERT",
            "IRON: 240C, STRAIGHT DOWN",
        ],
        "scenes": [
            {
                "goal": "Hook: the spun insert",
                "teaching_point": "Wrong sizing spins and splits",
                "shot": "macro shot of a split boss and a spun insert in a part",
                "motion": "slow push-in on the damage",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["split boss", "spun insert", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a split 3D printed boss and a spun heat-set insert, raking side light, dark bench",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Ribs lock into melted plastic",
                "shot": "graphic-style shot of an insert cross-section sinking into a boss",
                "motion": "ribs engage the molten wall",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["insert cross-section", "boss", "ribs"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a heat-set insert cross-section sinking into a printed boss on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The three numbers",
                "teaching_point": "Hole, boss, temperature",
                "shot": "tablet-style graphic showing the three specifications",
                "motion": "numbers highlight in sequence",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["spec table", "inserts", "calipers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a heat-set insert specification table on a tablet beside inserts and calipers, even diffused lighting, dark studio",
            },
            {
                "goal": "The install",
                "teaching_point": "Straight down, still, flush",
                "shot": "close-up of a soldering iron pressing an insert straight into a boss",
                "motion": "insert sinks flush and stops",
                "lighting": "warm task light",
                "background": "workbench",
                "objects": ["soldering iron", "insert", "boss", "jig"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a soldering iron pressing a heat-set insert straight into a 3D printed boss, warm task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Jigs make it repeatable",
                "shot": "wide hero shot of a fixture with multiple inserts installed flush",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fixture", "flush inserts", "insert press"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printed fixture with flush brass heat-set inserts installed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A brass insert half-sunk into a printed boss with specs overlaid",
            "subject": "heat-set insert sinking into a boss",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "boss center, insert half-in, spec labels",
            "text": "HEAT-SET INSERTS",
            "elements": ["brass insert", "printed boss", "spec labels"],
            "style": "industrial macro photography",
            "mood": "precise, thermal, engineered",
            "prompt": "macro photograph of a brass heat-set insert half sunk into a 3D printed boss with specification labels, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heat-Set Inserts: 3 Numbers",
            "title_variations": [
                "How to Install Heat-Set Inserts",
                "Heat-Set Insert Sizing",
                "Why Inserts Spin Out",
                "Brass Inserts in PLA",
                "Insert Installation Guide",
            ],
            "description": "Heat-set inserts are brass threads that melt into plastic: the ribs dig into softened material and lock in when it cools. Three numbers decide success. The hole, from the insert datasheet - about 4.2 millimeters for an M3 insert. The boss, about twice the insert diameter, so the plastic doesn't split. The iron temperature, around 240 degrees for PLA and PETG, hot enough to sink the insert and cool enough not to wreck the part. Install straight down without wobble and stop flush with the boss top. This short covers the mechanism, the three sizing numbers, and jig-based repeatable installation.",
            "hashtags": ["#HeatSetInserts", "#3Dprinting", "#Design", "#Hardware"],
            "seo_keywords": [
                "heat set inserts",
                "how to install heat set inserts",
                "heat set insert sizing",
                "M3 heat set insert hole",
                "brass inserts 3d printing",
                "insert boss design",
                "heat set insert temperature",
            ],
        },
        "fact_check": [
            "Knurled or ribbed insert bodies create mechanical grip in the softened plastic wall.",
            "Hole diameter follows the insert datasheet, typically insert OD minus rib depth.",
            "Boss outer diameter of roughly twice the insert diameter prevents splitting.",
            "Installation temperature near the plastic softening point, 230-270 C for PLA and PETG.",
            "Insertion must be vertical and wobble-free; depth stops make installs repeatable.",
        ],
    },
    # ======================================================================
    {
        "topic": "CNC Milling",
        "core_question": "How does CNC milling work, and what can it do that 3D printing can't?",
        "learning_objective": "The viewer can explain the milling process, the role of axes and spindle, and when to choose milling over printing.",
        "engineering_summary": "CNC milling removes material: a rotating cutter (end mill) carves a block of stock into the final shape, moving in three or more axes under computer control. The spindle spins the cutter at high RPM while linear axes position it; chips carry heat away, so metal parts hold tight tolerances and smooth finishes with no layer lines. Speeds and feeds - spindle RPM, feed rate, and depth of cut - balance material removal rate against tool wear and chatter. Milling wins for metal parts, tight tolerances, smooth surfaces, and production; printing wins for complex internal geometry, low cost, and one-off plastic parts. The two are complementary: printed jigs hold milled parts, and milled fixtures hold prints.",
        "real_world_application": "Machined aluminum brackets replace printed prototypes in production; hybrid workflows mill a print's critical faces, and shops mill fixtures for printer maintenance.",
        "common_misconceptions": [
            "CNC is a type of 3D printer (it removes material instead of adding it)",
            "Milling is always more precise (setups and fixturing decide real accuracy)",
            "Any material mills the same (feeds and speeds are material-specific)",
        ],
        "teaching_strategy": "Show a raw block turning into a finished part, the axis diagram, and a mill-versus-print decision split.",
        "script": "A CNC mill carves: a spinning cutter chews a block into the part you drew. Three or more axes move the cutter, the spindle spins it fast, and the chips carry the heat away. That's why milled metal parts have smooth walls and tight tolerances, with no layer lines anywhere. The skill is speeds and feeds: too fast, tool chatter and broken cutters; too slow, wasted time. Print for complex hollow shapes and one-offs. Mill for metal, precision, and repeatability. Best of all? Use both: printed jigs hold milled parts, milled fixtures hold prints.",
        "text_overlay": [
            "SUBTRACTIVE, NOT ADDITIVE",
            "SPINDLE + AXES + CHIPS",
            "SPEEDS AND FEEDS BALANCE",
            "PRINT JIGS, MILL PARTS",
        ],
        "scenes": [
            {
                "goal": "Hook: block to part",
                "teaching_point": "Material is removed, not added",
                "shot": "wide shot of a CNC mill cutting a block with chips flying",
                "motion": "cutter carves while coolant sprays",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["CNC mill", "stock block", "chips", "coolant"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a CNC mill cutting a metal block with chips flying and coolant spray, bright task lighting, machine shop",
            },
            {
                "goal": "The anatomy",
                "teaching_point": "Spindle, axes, and cutter",
                "shot": "graphic-style shot of a mill with axis arrows",
                "motion": "axis arrows animate on the machine",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["mill diagram", "axis arrows", "spindle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a CNC mill diagram with axis arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Speeds and feeds",
                "teaching_point": "Balance cuts against chatter",
                "shot": "macro shot of a chattering cut leaving a rough surface",
                "motion": "cutter vibrates, surface roughens",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["end mill", "rough surface", "chatter marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of an end mill chattering and leaving a rough surface, raking side light, dark bench",
            },
            {
                "goal": "Mill vs print",
                "teaching_point": "Metal, tolerance, finish vs complexity, cost",
                "shot": "tabletop shot of a machined bracket beside a printed bracket",
                "motion": "camera pans between them",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["machined bracket", "printed bracket"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a machined aluminum bracket beside a 3D printed bracket on a dark studio table, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "They work together",
                "shot": "wide hero shot of a printed fixture holding a milled part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed fixture", "milled part", "clamps"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printed fixture holding a milled metal part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spinning end mill carving a block into a finished part",
            "subject": "end mill cutting with chips flying",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "cutter center, stock left, part emerging right",
            "text": "CNC MILLING",
            "elements": ["end mill", "stock block", "chips", "finished part"],
            "style": "industrial macro photography",
            "mood": "machined, powerful, precise",
            "prompt": "macro photograph of an end mill carving a metal block with chips flying, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "CNC Milling Explained",
            "title_variations": [
                "How CNC Milling Works",
                "CNC vs 3D Printing",
                "Milling for Beginners",
                "What Is an End Mill",
                "Speeds and Feeds Basics",
            ],
            "description": "CNC milling removes material: a spinning end mill carves a block of stock into the part you drew, moving under computer control in three or more axes. Chips carry heat away, which is why milled metal parts hold tight tolerances and smooth finishes with no layer lines. The craft is speeds and feeds - spindle RPM, feed rate, and depth of cut balance material removal against tool wear and chatter. Print for complex internal geometry and one-off plastic parts; mill for metal, precision, and repeatability. This short covers the process, the anatomy of a mill, and how printing and milling work together.",
            "hashtags": ["#CNC", "#Milling", "#Machining", "#Engineering"],
            "seo_keywords": [
                "how cnc milling works",
                "cnc vs 3d printing",
                "end mill explained",
                "speeds and feeds",
                "cnc machining basics",
                "milled metal parts",
                "cnc mill anatomy",
            ],
        },
        "fact_check": [
            "Milling is subtractive: a rotating cutter removes material from stock.",
            "CNC mills position the cutter with three or more linear axes under program control.",
            "Speeds and feeds (RPM, feed rate, depth of cut) balance removal rate against tool wear and chatter.",
            "Milling achieves tight tolerances and smooth finishes, especially in metal.",
            "Printing and milling are complementary: printed fixtures hold milled parts and vice versa.",
        ],
    },
    # ======================================================================
    {
        "topic": "Momentum & Impulse",
        "core_question": "Why does a falling part break, and what do momentum and impulse have to do with it?",
        "learning_objective": "The viewer can explain momentum, impulse, and force over time, and apply them to impacts and crashes.",
        "engineering_summary": "Momentum is mass times velocity, p = m v. Impulse is force times the time it acts, J = F delta-t, and it equals the change in momentum. A crash stops a moving object's momentum in milliseconds, so the force spikes: that is why a phone drops from a pocket shatters on concrete but survives on carpet - the carpet stretches the stop over more time, lowering the peak force. Crash padding, crumple zones, and airbags all extend stopping time. The same math explains extruder crash forces, print head collisions, and why you tighten machine mounts: decelerating a heavy toolhead quickly spikes the force transmitted into the frame.",
        "real_world_application": "Crumple zones in cars, foam packaging, and airbags are impulse devices; machine design uses soft limits and deceleration ramps to avoid force spikes on frames and parts.",
        "common_misconceptions": [
            "Heavier things always break more (peak force, not mass alone, decides - time matters)",
            "Momentum and force are the same thing (momentum is the state; force is what changes it over time)",
            "Softening a crash is about material (geometry that spreads the stop in time is the mechanism)",
        ],
        "teaching_strategy": "Drop the same part on concrete and foam, cut to slow motion, then the impulse equation and crumple-zone example.",
        "script": "Same phone, same fall, two floors. Concrete: shatter. Carpet: survives. The difference is time. Momentum is mass times speed, and stopping it takes impulse - force times time. Concrete stops the phone in a fraction of a millisecond, so the force spikes huge. Carpet stretches that stop over hundreds of milliseconds, and the peak force collapses. That's every crumple zone, airbag, and foam insert: they buy time. Crashes are force over time. Soften the timeline, and the same impact barely registers. Time is the cheapest shock absorber you have.",
        "text_overlay": [
            "MOMENTUM = MASS x VELOCITY",
            "IMPULSE = FORCE x TIME",
            "CONCRETE: SHORT TIME, HUGE FORCE",
            "TIME BUYS SURVIVAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the two drops",
                "teaching_point": "Same object, different floor, different result",
                "shot": "slow-motion-style shot of a phone dropping onto concrete",
                "motion": "impact shatters in slow motion",
                "lighting": "dramatic side light",
                "background": "street scene",
                "objects": ["phone", "concrete", "impact"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a phone dropping onto concrete in dramatic side light, slow motion feel, street scene",
            },
            {
                "goal": "The equation",
                "teaching_point": "Impulse equals change in momentum",
                "shot": "graphic-style shot of the impulse equation with animated terms",
                "motion": "force and time swap to show the balance",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["equation diagram", "force arrow", "time axis"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of the momentum and impulse equations on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The time stretch",
                "teaching_point": "Longer stop time, lower peak force",
                "shot": "side-by-side shots of impacts on concrete and foam",
                "motion": "cross-cut between the two landings",
                "lighting": "bright task light",
                "background": "test bench",
                "objects": ["concrete slab", "foam pad", "dropped part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a drop test showing concrete and foam landing surfaces with a dropped part, bright task light, test bench",
            },
            {
                "goal": "Real-world impulse",
                "teaching_point": "Crumple zones buy time",
                "shot": "medium shot of a crumpled car bumper and a foam insert",
                "motion": "slow push-in on the deformed zones",
                "lighting": "neutral lab light",
                "background": "garage",
                "objects": ["crumpled bumper", "foam insert", "crash structure"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a crumpled car bumper and foam crash insert, neutral lab lighting, garage",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design for time, not toughness",
                "shot": "wide hero shot of a protected device in a foam-lined case",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["foam-lined case", "protected part"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a device in a foam-lined protective case, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "The same drop on concrete and foam, split screen",
            "subject": "dropped part landing on two surfaces",
            "background": "dark lab blur",
            "angle": "low side angle",
            "lighting": "hard key with rim",
            "composition": "concrete left, foam right, part center",
            "text": "IMPULSE 101",
            "elements": ["dropped part", "concrete", "foam", "time arrows"],
            "style": "physics macro photography",
            "mood": "impactful, scientific, clear",
            "prompt": "photograph of a dropped part landing on concrete on the left and foam on the right with time arrows, hard key light with rim, dark lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Momentum & Impulse Explained",
            "title_variations": [
                "Why Crashes Break Things",
                "Force Over Time Explained",
                "Crumple Zones Physics",
                "Momentum vs Impulse",
                "The Physics of Soft Landings",
            ],
            "description": "Momentum is mass times velocity, and impulse - force times time - is what stops it. The same phone dropped on concrete shatters, but survives on carpet, because the carpet stretches the stop over hundreds of milliseconds and collapses the peak force. Every crumple zone, airbag, and foam insert is an impulse device: they buy time. Peak force, not mass alone, decides whether an impact breaks things, which is why machine designers use deceleration ramps and soft limits instead of just stronger frames. This short explains the physics with slow-motion drops and shows how to design for time instead of toughness.",
            "hashtags": ["#Physics", "#Momentum", "#Engineering", "#Impulse"],
            "seo_keywords": [
                "momentum and impulse explained",
                "impulse physics",
                "why things break on impact",
                "force over time",
                "crumple zone physics",
                "momentum mass velocity",
                "impact force explained",
            ],
        },
        "fact_check": [
            "Momentum is p = m v; impulse is J = F delta-t, equal to the change in momentum.",
            "Extending stopping time reduces peak force for the same momentum change.",
            "Crumple zones, airbags, and foam packaging are time-stretching impulse devices.",
            "Peak impact force, not mass alone, determines whether an object fractures.",
            "Machine design uses deceleration ramps and compliant mounts to limit transmitted force spikes.",
        ],
    },
    # ======================================================================
    {
        "topic": "Microcontrollers",
        "core_question": "What is a microcontroller, and how does it run my printer?",
        "learning_objective": "The viewer can explain what an MCU is, how it differs from a computer, and where microcontrollers live in the shop.",
        "engineering_summary": "A microcontroller (MCU) is a small computer on one chip: a CPU, memory, and input-output peripherals (GPIO, timers, ADCs, and communication buses) integrated together. It runs one program, in a loop, reading sensors and driving actuators in real time - unlike a PC, it has no OS overhead and responds in microseconds. That's why printers, drones, and controllers run on MCUs: an 8-bit or 32-bit chip can step motors, read thermistors, and run PID loops at thousands of times per second. Development boards like Arduino wrap the MCU with power, USB, and headers for hobby use; production boards strip it to the minimum for cost and reliability.",
        "real_world_application": "Every 3D printer mainboard, extruder controller, and sensor node is an MCU; print farms build custom controllers from off-the-shelf MCUs for fleet monitoring.",
        "common_misconceptions": [
            "Microcontrollers are mini-computers running an OS (they run one bare-metal program, no OS)",
            "Arduino is a microcontroller (Arduino is a development board built around an MCU)",
            "Faster CPU means better printer (deterministic real-time response matters more than clock speed)",
        ],
        "teaching_strategy": "Show the chip anatomy, the read-decide-act loop, and where MCUs hide in a printer, then the Arduino-versus-MCU distinction.",
        "script": "Your printer's brain is a microcontroller: a whole computer on one chip. CPU, memory, and input-output - no operating system, no boot time. It just runs one loop, millions of times a second: read the sensors, decide, drive the outputs. That's the real-time trick - the printer checks the thermistor, runs the PID loop, and steps the motors on schedule, every time, no delays. Arduino is not the chip; it's a board that makes the chip friendly. Strip the board away, and the same microcontroller runs your dryer, your fan controller, and your entire shop.",
        "text_overlay": [
            "ONE CHIP COMPUTER",
            "READ, DECIDE, ACT - FAST",
            "REAL TIME, NO OS",
            "ARDUINO = BOARD, NOT CHIP",
        ],
        "scenes": [
            {
                "goal": "Hook: the invisible brain",
                "teaching_point": "Every machine runs on a chip",
                "shot": "macro shot of a mainboard with the MCU highlighted",
                "motion": "slow push-in on the chip",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["mainboard", "MCU chip", "printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printer mainboard with the microcontroller chip highlighted, bright task light, dark bench",
            },
            {
                "goal": "The anatomy",
                "teaching_point": "CPU, memory, and IO on one die",
                "shot": "graphic-style shot of an MCU die with labeled blocks",
                "motion": "blocks highlight in sequence",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["chip diagram", "CPU block", "IO block"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a microcontroller chip diagram with CPU, memory, and IO blocks on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The loop",
                "teaching_point": "Read, decide, act, repeat",
                "shot": "tablet-style graphic showing the control loop with live values",
                "motion": "loop cycles with numbers updating",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["control loop diagram", "thermistor value", "motor output"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a microcontroller control loop diagram with live sensor values on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Real time",
                "teaching_point": "Microsecond response, no OS delays",
                "shot": "medium shot of a printer responding instantly to a sensor event",
                "motion": "thermistor spikes, heater reacts immediately",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer", "display", "sensor readout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer reacting instantly to a sensor reading, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "MCUs run the whole shop",
                "shot": "wide hero shot of multiple devices each with a small controller",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "fan controller", "dryer", "custom boards"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of several devices with small microcontroller boards, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A glowing chip with the read-decide-act loop around it",
            "subject": "microcontroller chip with loop diagram",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "chip center, loop arrows around",
            "text": "THE ONE-CHIP BRAIN",
            "elements": ["MCU chip", "loop arrows", "pins"],
            "style": "electronics macro photography",
            "mood": "technical, embedded, alive",
            "prompt": "macro photograph of a microcontroller chip with a control loop diagram around it, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Microcontrollers: The Chip Brain",
            "title_variations": [
                "What Is a Microcontroller",
                "How Printers Think",
                "MCU vs Computer",
                "Arduino vs Microcontroller",
                "Embedded Control Explained",
            ],
            "description": "A microcontroller is a whole computer on one chip: CPU, memory, and input-output with no operating system. It runs one loop - read the sensors, decide, drive the outputs - millions of times a second, responding in microseconds. That real-time determinism is exactly why printers, drones, and controllers run on MCUs: they can step motors, read thermistors, and run PID loops on schedule without OS delays. Arduino is a development board that wraps the chip in power, USB, and headers, not the chip itself. This short explains the anatomy, the control loop, and where microcontrollers hide in every machine.",
            "hashtags": ["#Microcontroller", "#Electronics", "#Arduino", "#Embedded"],
            "seo_keywords": [
                "what is a microcontroller",
                "microcontroller vs computer",
                "arduino microcontroller explained",
                "how 3d printer works electronics",
                "embedded systems basics",
                "MCU control loop",
                "microcontroller anatomy",
            ],
        },
        "fact_check": [
            "A microcontroller integrates CPU, memory, and peripherals on a single die.",
            "MCUs run bare-metal programs without an operating system, enabling deterministic timing.",
            "Printer mainboards use MCUs to run stepper timing, thermistor reading, and PID loops.",
            "Arduino is a development board; the microcontroller is the chip at its core.",
            "Deterministic real-time response, not raw clock speed, is the key MCU property.",
        ],
    },
    # ======================================================================
    {
        "topic": "Multimeter Skills",
        "core_question": "How do I actually use a multimeter safely and correctly?",
        "learning_objective": "The viewer can measure voltage, resistance, and continuity safely, and choose the right mode for a diagnosis.",
        "engineering_summary": "A multimeter measures voltage (in parallel), current (in series), resistance (with power off), and continuity. The golden rule: never measure resistance on a live circuit, never measure current without breaking the circuit, and start on the highest range if you don't know the value. Voltage mode reads the potential difference between probes - the first diagnostic for dead heaters, thermistors, and power supplies. Continuity mode beeps when resistance is near zero, perfect for finding broken wires, blown fuses, and bad connections. Thermistors change resistance with temperature, so a resistance reading at room temperature is a quick sanity check. Auto-ranging meters pick the scale; manual meters need range discipline.",
        "real_world_application": "Every printer repair starts with a meter: checking the heater cartridge reads 24V, the thermistor reads about 100 kOhm, and continuity finds the broken bed wire.",
        "common_misconceptions": [
            "The meter creates the reading regardless of mode (modes and leads placement change what you measure)",
            "Resistance can be measured live (it reads wrong and can damage the meter)",
            "Continuity and resistance are the same (continuity is a fast near-zero resistance check)",
        ],
        "teaching_strategy": "Show the three measurement setups on a bench, the live-circuit warning, then a real printer diagnostic sequence.",
        "script": "A multimeter is the shop's stethoscope - if you use it right. Voltage: probes in parallel, measure across the part, live circuit is fine. Resistance: power off, always - a live circuit will lie to you and can hurt the meter. Continuity: the beeper, for finding broken wires and blown fuses. Here's the power move: dead heater? Measure voltage across it - twenty-four volts missing means wiring, not the heater. Thermistor reading odd? Measure resistance cold, about a hundred kilo-ohms for most. Three modes, three rules: parallel, power-off, and trust the beep.",
        "text_overlay": [
            "VOLTAGE: IN PARALLEL",
            "RESISTANCE: POWER OFF",
            "CONTINUITY: TRUST THE BEEP",
            "24V MISSING = WIRING",
        ],
        "scenes": [
            {
                "goal": "Hook: the dead heater",
                "teaching_point": "One measurement localizes the fault",
                "shot": "medium shot of a multimeter probing a printer heater",
                "motion": "probes touch, reading appears",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["multimeter", "heater cartridge", "printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a multimeter probing a 3D printer heater cartridge, bright task lighting, print lab",
            },
            {
                "goal": "Voltage mode",
                "teaching_point": "Measure across, in parallel",
                "shot": "macro shot of probes across a power supply terminal",
                "motion": "reading settles on 24V",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["multimeter", "power supply", "probes"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of multimeter probes measuring voltage across a power supply terminal, neutral lab lighting, workbench",
            },
            {
                "goal": "Resistance mode",
                "teaching_point": "Power off, always",
                "shot": "macro shot of probes measuring a thermistor resistance",
                "motion": "reading settles near 100k",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["multimeter", "thermistor", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of multimeter probes measuring a thermistor's resistance on a dark bench, bright task light",
            },
            {
                "goal": "Continuity",
                "teaching_point": "The beeper finds broken wires",
                "shot": "close-up of probes tracing a suspected broken wire",
                "motion": "probes move along the wire, beep confirms",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["multimeter", "wire harness", "probes"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of continuity testing a wire harness with a multimeter, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Three modes, three rules",
                "shot": "wide hero shot of a repaired printer running with the meter on the bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["running printer", "multimeter", "workbench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a running 3D printer with a multimeter on the bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A multimeter with three mode labels radiating",
            "subject": "multimeter with probes on a bench",
            "background": "dark workbench blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "meter center, mode labels around",
            "text": "USE THE METER",
            "elements": ["multimeter", "probes", "mode labels"],
            "style": "electronics macro photography",
            "mood": "diagnostic, disciplined, clear",
            "prompt": "macro photograph of a multimeter with probes and mode labels around it on a dark workbench, hard key light with rim, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Multimeter Basics: 3 Modes",
            "title_variations": [
                "How to Use a Multimeter",
                "Voltage, Resistance, Continuity",
                "Multimeter for 3D Printing",
                "Troubleshoot with a Meter",
                "Meter Skills for Makers",
            ],
            "description": "A multimeter is the shop's stethoscope. Voltage mode measures across a component in parallel and is safe on live circuits. Resistance mode requires the power off - measuring a live circuit reads wrong and can damage the meter. Continuity mode beeps on near-zero resistance, the fastest way to find broken wires and blown fuses. The power move in printer repair: a dead heater with no voltage across it means wiring, not the heater, and a thermistor reading about 100 kilo-ohms cold is a sanity check. This short covers the three modes, the three rules, and a real diagnostic sequence you can run today.",
            "hashtags": ["#Multimeter", "#Electronics", "#Diagnostics", "#Makers"],
            "seo_keywords": [
                "how to use a multimeter",
                "multimeter voltage resistance continuity",
                "multimeter for 3d printer",
                "measure continuity",
                "check thermistor multimeter",
                "troubleshoot heater multimeter",
                "multimeter basics",
            ],
        },
        "fact_check": [
            "Voltage is measured in parallel across a component; the circuit can be live.",
            "Resistance is measured with the power off; live measurement reads falsely and may damage the meter.",
            "Continuity mode emits a tone for near-zero resistance, ideal for wire and fuse checks.",
            "NTC thermistors used in printers read roughly 100 kOhm at room temperature.",
            "Starting on the highest range and working down protects the meter from unknown values.",
        ],
    },
    # ======================================================================
    {
        "topic": "Precision Basics",
        "core_question": "What is the difference between precision and accuracy, and why does it matter?",
        "learning_objective": "The viewer can define accuracy, precision, and repeatability, and use them to judge measurements and machines.",
        "engineering_summary": "Accuracy is how close a measurement is to the true value; precision is how close repeated measurements are to each other; repeatability is how consistently a machine returns to the same position. A precise but inaccurate instrument consistently measures the wrong thing - like a printer that always prints 0.2 mm undersized. Fixes come from calibration (offsets and scales) and resolution (finer steps). Resolution - the smallest increment an instrument can show - is not accuracy: a digital caliper showing 0.01 mm can still be off by 0.1 mm if uncalibrated. The measurement error budget is the sum of instrument error, operator technique, and environmental effects like temperature.",
        "real_world_application": "Printers are calibrated for accuracy with test cubes and flow, while repeatability is guaranteed by quality motion components; a machine can be repeatable yet inaccurate - and that is a calibration fix.",
        "common_misconceptions": [
            "Precision and accuracy are the same (precision is spread; accuracy is closeness to truth)",
            "More decimal places mean more accuracy (resolution is not accuracy)",
            "A repeatable machine is accurate (repeatability plus calibration makes accuracy)",
        ],
        "teaching_strategy": "Show the classic dartboard analogy, then a real printer case: repeatable but undersized, fixed by flow calibration.",
        "script": "Precision and accuracy are not the same, and the difference decides whether you trust your measurements. Accuracy is hitting the true value. Precision is hitting the same spot again and again. A printer that always prints point two millimeters undersized is precise - beautifully repeatable - and inaccurate. Calibration fixes accuracy: flow, offsets, steps. Resolution is a trap: more decimals don't make a reading truer, just finer. Trust your tools, but verify them. Measure the same part ten times: tight spread means precise. Compare with a known part: closeness means accurate. Fix the spread, then fix the truth.",
        "text_overlay": [
            "ACCURACY: TRUE VALUE",
            "PRECISION: SAME SPOT",
            "REPEATABLE ≠ ACCURATE",
            "RESOLUTION ≠ ACCURACY",
        ],
        "scenes": [
            {
                "goal": "Hook: the dartboard",
                "teaching_point": "Four darts show the whole story",
                "shot": "tabletop shot of a dartboard with four dart patterns",
                "motion": "darts land in clusters",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["dartboard", "dart patterns", "bullseye"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a dartboard with dart clusters showing precision and accuracy, even diffused lighting, dark studio",
            },
            {
                "goal": "The precise printer",
                "teaching_point": "Repeatably wrong is a calibration fix",
                "shot": "macro shot of a printed cube measuring undersized",
                "motion": "calipers measure the cube",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["printed cube", "calipers", "measurement"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of calipers measuring a 3D printed test cube, bright task light, dark bench",
            },
            {
                "goal": "Resolution trap",
                "teaching_point": "Decimals are not truth",
                "shot": "macro shot of a digital caliper display on a part",
                "motion": "display flips to 0.01mm resolution",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["digital caliper", "display", "part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a digital caliper showing fine resolution on a machined part, bright task light, dark bench",
            },
            {
                "goal": "The error budget",
                "teaching_point": "Instrument, technique, environment",
                "shot": "tabletop shot of measuring tools, hands, and a temperature gauge",
                "motion": "camera moves across the three error sources",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["calipers", "hands measuring", "thermometer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of measuring tools with hands and a thermometer representing measurement error sources, neutral lab lighting, workshop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fix the spread, then the truth",
                "shot": "wide hero shot of a verified part passing inspection",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["verified part", "calipers", "inspection sheet"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part passing inspection with calipers and a check sheet, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A dartboard split into the four accuracy-precision cases",
            "subject": "dartboard with labeled dart clusters",
            "background": "dark workshop blur",
            "angle": "eye-level close-up",
            "lighting": "hard key with rim",
            "composition": "dartboard center, case labels around",
            "text": "PRECISION vs ACCURACY",
            "elements": ["dartboard", "dart clusters", "case labels"],
            "style": "studio photography",
            "mood": "educational, crisp, clear",
            "prompt": "photograph of a dartboard with labeled dart clusters showing precision and accuracy cases, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Precision vs Accuracy",
            "title_variations": [
                "Accuracy Explained Simply",
                "Precision and Repeatability",
                "Why Your Printer Prints Undersized",
                "Measurement Error Basics",
                "Trust Your Measurements",
            ],
            "description": "Accuracy is closeness to the true value; precision is how close repeated measurements are to each other; repeatability is how consistently a machine returns to the same position. A printer that always prints 0.2 millimeters undersized is precise but inaccurate - and calibration fixes that with flow, offsets, and steps. Resolution is another trap: more decimals on a display make a reading finer, not truer. The error budget is instrument error plus operator technique plus environment. This short explains the dartboard analogy, the repeatable-but-wrong printer case, and how to verify your tools before trusting them.",
            "hashtags": ["#Precision", "#Measurement", "#Calibration", "#Engineering"],
            "seo_keywords": [
                "precision vs accuracy",
                "accuracy precision repeatability",
                "measurement error explained",
                "printer calibration accuracy",
                "resolution vs accuracy",
                "calibrating measurements",
                "trust your measurements",
            ],
        },
        "fact_check": [
            "Accuracy is closeness to the true value; precision is repeatability of results.",
            "Repeatability is a machine property; accuracy requires calibration on top of repeatability.",
            "Resolution is the smallest displayed increment and does not imply accuracy.",
            "The measurement error budget includes instrument error, operator technique, and environmental effects.",
            "A systematic offset, like undersized printed parts, is corrected by calibration rather than by changing resolution.",
        ],
    },
]