"""Batch 2: beginner fundamentals across slicer, materials, troubleshooting, and mechanics."""

CURATED = [
    # ======================================================================
    {
        "topic": "Supports",
        "core_question": "When do 3D printed parts need supports?",
        "learning_objective": "The viewer can decide when supports are required, and knows how interface settings trade surface quality against removal effort.",
        "engineering_summary": "FDM prints each layer onto the layer below; features steeper than roughly 45 degrees have no floor and sag. Supports are sacrificial scaffolds printed under those regions. The contact interface - interface density, gap, and pattern - controls the trade between a clean removal surface (high interface density, small gap) and easy removal (low density, larger gap). Tree/organic supports minimize contact area and improve surface quality at the cost of slicer complexity.",
        "real_world_application": "Print farms use organic supports for cosmetic parts and tuned interface settings for snap-fit features; design-for-print eliminates supports by chamfering instead of supporting.",
        "common_misconceptions": [
            "Supports always ruin the surface (interface tuning can leave near-print-quality surfaces)",
            "More support contact is always better (it makes removal destructive)",
            "Tree supports are always slower (they can reduce material and print time)",
        ],
        "teaching_strategy": "Show a sagging unsupported overhang first, then the same part with a removable support and its clean interface surface.",
        "script": "Some features need a scaffold. When a part's angle tips past about 45 degrees, the printer can't print in thin air, so supports build a temporary floor. Here's the catch: supports touch your part, and where they touch, they leave scars. That's why interface settings matter: density, gap, and pattern control how clean the break is. Tree supports touch less surface. More contact, cleaner top, harder removal. Less contact, easier removal, rougher finish. It's a trade-off you design around.",
        "text_overlay": [
            ">45° = SCAFFOLD TIME",
            "SUPPORTS = TEMPORARY FLOOR",
            "INTERFACE = THE SCAR ZONE",
            "TREE = LESS CONTACT",
            "TRADE-OFF, NOT MAGIC",
        ],
        "scenes": [
            {
                "goal": "Hook: sagging overhang",
                "teaching_point": "Past ~45 degrees the print has no floor and sags",
                "shot": "macro close-up of a sagging unsupported overhang",
                "motion": "slow push-in on the droop",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["printed part with sagging overhang"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part with a sagging unsupported overhang, raking side light, dark workshop background",
            },
            {
                "goal": "Show supports being built",
                "teaching_point": "Supports are a sacrificial floor printed under the overhang",
                "shot": "medium shot of a printer building organic tree supports under a feature",
                "motion": "timelapse-style growth of the support",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer", "tree supports", "printed part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer building organic tree supports under a printed part, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Interface explained",
                "teaching_point": "Interface density and gap decide surface quality and removal effort",
                "shot": "macro shot of a support interface layer being removed from a part",
                "motion": "slow peel-away of the interface",
                "lighting": "bright task light",
                "background": "workbench blur",
                "objects": ["support structure", "interface layer", "printed part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a support interface layer being peeled from a 3D printed part, bright task lighting, workbench background",
            },
            {
                "goal": "Tree vs block supports",
                "teaching_point": "Organic supports minimize contact area",
                "shot": "split-screen of tree supports vs block supports on the same part",
                "motion": "wipe between the two",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["tree-supported part", "block-supported part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two 3D printed parts side by side, one with organic tree supports and one with block supports, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the trade-off: contact area vs removal effort",
                "shot": "wide hero shot of a clean part with supports removed on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean printed part", "removed supports"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a clean 3D printed part beside its removed supports on a build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Part half-covered in block supports, half clean, with a peel-away interface close-up",
            "subject": "3D printed part with supports still attached on one side",
            "background": "dark workshop blur",
            "angle": "macro side profile",
            "lighting": "hard key with rim",
            "composition": "supported half left, clean half right",
            "text": "SUPPORTS",
            "elements": ["block supports", "interface layer", "clean surface"],
            "style": "diagnostic macro photography",
            "mood": "decisive, practical, clear",
            "prompt": "macro photograph of a 3D printed part with block supports still attached on the left half and a clean surface on the right half, hard key light with rim, dark workshop background, 9:16 vertical composition, ultra sharp layer detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "When Do You Actually Need Supports?",
            "title_variations": [
                "Supports: The 45-Degree Rule",
                "Why Supports Leave Scars (And How to Fix It)",
                "Tree Supports vs Block Supports",
                "Support Interface: Clean or Destructive",
                "Print Overhangs Without Ugly Scars",
            ],
            "description": "When does a 3D print need supports? Past about 45 degrees the nozzle has nothing to print on and the plastic sags. Supports build a sacrificial floor under those features, but they leave contact scars. This short explains the 45-degree threshold, how interface density and gap control surface quality versus removal effort, and why tree supports touch less surface. Design the trade-off instead of guessing.",
            "hashtags": ["#3Dprinting", "#Supports", "#Overhang", "#3DPrintingTips"],
            "seo_keywords": [
                "3d print supports",
                "when to use supports",
                "tree supports",
                "support interface density",
                "remove supports cleanly",
                "overhang support settings",
                "support scars fix",
            ],
        },
        "fact_check": [
            "The 45-degree guideline varies with layer height, cooling, and material; lower layer heights push the practical limit higher.",
            "Support interface settings typically include interface density (e.g., 60-100%), interface gap (one or two layer heights), and pattern.",
            "Tree (organic) supports reduce contact area versus block supports and can reduce material use, but may increase slice time.",
            "PETG bonds aggressively to supports and often needs a larger interface gap or different support material to separate cleanly.",
            "Units: angles in degrees; interface gap in layer heights or millimeters.",
        ],
    },
    # ======================================================================
    {
        "topic": "Infill",
        "core_question": "What infill density should I actually use?",
        "learning_objective": "The viewer learns that walls dominate strength, and sets a practical 20% default with pattern awareness.",
        "engineering_summary": "Infill is the internal lattice that supports the top surfaces of a print. Strength scales with the outer walls first: perimeter count contributes more to bending and tensile strength than infill density, because walls carry the outermost fiber stresses. Above roughly 20-30% density, additional infill yields diminishing strength returns while adding time and material. Pattern choice matters: gyroid deforms isotropically and smoothly, cubic is strong in three axes, grid is fast but leaves crossing-node artifacts.",
        "real_world_application": "Functional brackets default to 3-4 walls at 20-25% infill; injection-molded-style parts use 100% only when sealing or pressing in hardware; lattices like gyroid are used for energy absorption in packaging and footwear.",
        "common_misconceptions": [
            "More infill means much stronger parts (walls dominate; infill above ~25% has diminishing returns)",
            "Infill density is the main strength setting (wall count and layer adhesion matter more)",
            "Grid infill is as strong as gyroid at the same density (crossing nodes create stress points)",
        ],
        "teaching_strategy": "Bend-test two identical parts with different wall counts at the same infill to make the wall dominance visible, then compare patterns.",
        "script": "Your print isn't solid on the inside, it's a skeleton. Infill is the internal lattice that stops the top from collapsing while it saves material and time. But here's the surprise: infill density barely matters for strength. Two walls and twenty percent infill beat ten percent walls any day. What matters is wall count, top layers, and the pattern. Gyroid prints smooth in every direction. Grid is fast, but crossing lines can wobble. So set twenty percent, and let the pattern do the work.",
        "text_overlay": [
            "INFILL = INTERNAL SKELETON",
            "WALLS > INFILL",
            "20% + 3 WALLS = DEFAULT",
            "GYROID: SMOOTH EVERY WAY",
            "DENSITY IS NOT STRENGTH",
        ],
        "scenes": [
            {
                "goal": "Hook: cutaway reveal",
                "teaching_point": "Prints are hollow lattices, not solid blocks",
                "shot": "macro cutaway shot of a printed part showing the internal infill lattice",
                "motion": "slow pan across the cutaway",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["cutaway printed part", "infill lattice"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part cut in half revealing the internal infill lattice, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Wall dominance",
                "teaching_point": "Bending strength lives in the walls, not the fill",
                "shot": "two test brackets, one 2-wall one 6-wall, being bent",
                "motion": "side-by-side flex test",
                "lighting": "bright task light",
                "background": "lab bench",
                "objects": ["printed brackets", "test rig"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two 3D printed brackets being flexed in a bench test, bright task lighting, engineering lab bench",
            },
            {
                "goal": "The practical default",
                "teaching_point": "20% infill with 3-4 walls covers most parts",
                "shot": "slicer screen showing 20% infill with wall callouts",
                "motion": "slow zoom on the settings panel",
                "lighting": "screen glow in dark room",
                "background": "dark studio",
                "objects": ["slicer screen", "infill slider", "wall count setting"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D slicer interface showing infill percentage and wall count settings, screen glow in a dark studio, clean UI",
            },
            {
                "goal": "Patterns compared",
                "teaching_point": "Gyroid is isotropic and smooth; grid has crossing nodes",
                "shot": "macro shots of gyroid, cubic, and grid infill samples",
                "motion": "wipe between the three patterns",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["gyroid sample", "cubic sample", "grid sample"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of three infill pattern samples showing gyroid, cubic, and grid structures, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Let walls carry load and infill support surfaces",
                "shot": "wide hero shot of a strong bracket printing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed bracket", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a functional 3D printed bracket on a build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Cutaway part with thick walls and a small 20% lattice, a wall-count callout",
            "subject": "3D printed block cut in half showing thick outer walls and sparse internal lattice",
            "background": "dark bench blur",
            "angle": "macro three-quarter",
            "lighting": "hard key with rim",
            "composition": "cutaway centered, walls and lattice clearly visible",
            "text": "20% INFILL",
            "elements": ["outer walls", "infill lattice", "cutaway face"],
            "style": "technical macro photography",
            "mood": "revealing, practical, clean",
            "prompt": "macro photograph of a 3D printed block cut in half showing thick outer walls and a sparse 20 percent internal lattice, hard key light with rim, dark workbench, 9:16 vertical composition, ultra sharp cutaway detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Infill 20% Is All You Need (Here's Why)",
            "title_variations": [
                "Why Infill Density Doesn't Make Parts Strong",
                "The Truth About Infill and Strength",
                "Walls vs Infill: What Actually Carries Load",
                "Best Infill Pattern for Functional Parts",
                "Stop Printing 100% Infill",
            ],
            "description": "How much infill do you really need? Strength lives in the outer walls, not the fill: two walls at 20% infill beat 100% infill with a single wall. This short explains why wall count dominates bending strength, why 20-25% is the practical default, and how gyroid, cubic, and grid patterns change the game. Save time and filament without weakening your parts.",
            "hashtags": ["#3Dprinting", "#Infill", "#3DPrintingTips", "#Slicer"],
            "seo_keywords": [
                "infill percentage",
                "infill strength",
                "best infill pattern",
                "gyroid infill",
                "wall count vs infill",
                "how much infill",
                "lightweight 3d prints",
            ],
        },
        "fact_check": [
            "Bending and tensile strength of a printed part scale primarily with wall/perimeter count because outer fibers carry peak stress.",
            "Above roughly 20-30% density, additional infill shows diminishing strength returns for typical loads.",
            "Gyroid infill provides near-isotropic mechanical response with smooth, gap-free layers; grid infill crosses at nodes that concentrate stress.",
            "Cubic infill is strong in all three axes due to its 3D cell structure.",
            "Infill percentage relates to material volume fraction, not directly to mechanical strength.",
        ],
    },
    # ======================================================================
    {
        "topic": "PETG",
        "core_question": "What is PETG and when should I use it?",
        "learning_objective": "The viewer knows PETG's print window, its moisture sensitivity, and its position between PLA and ABS.",
        "engineering_summary": "PETG is a glycol-modified copolyester combining PLA-like printability with superior toughness, chemical resistance, and UV tolerance. It prints at 230-250 C nozzle and 70-90 C bed, needs lower cooling than PLA, and is strongly hygroscopic: absorbed water hydrolyzes the polymer chains at temperature, producing cloudy, brittle prints with surface voids. Drying at 60-65 C for several hours restores quality. Parts bend before breaking and resist mild chemicals, making PETG the default functional filament.",
        "real_world_application": "PETG is used for outdoor brackets, water-contact parts, phone mounts, and food-safe (batch-dependent) containers; print farms select PETG where PLA fails and ABS is overkill.",
        "common_misconceptions": [
            "PETG is just stronger PLA (it is tougher, but softer and more flexible, and far more moisture sensitive)",
            "Wet filament looks wet (damage appears as cloudiness, popping sounds, and stringing)",
            "PETG is food safe by default (food safety depends on additives, print defects, and surface finish)",
        ],
        "teaching_strategy": "Anchor with the moisture story: show the same spool dried vs wet printing the same part, and let the surface finish tell the story.",
        "script": "PETG is the workhorse filament: tough, clear-ish, and easy enough for beginners. It sits between PLA and ABS: stronger than PLA, less fuss than ABS. Print it at 230 to 250 degrees with a hot bed around 80. The enemy? Moisture. PETG drinks water from the air, and wet PETG prints cloudy, stringy, and weak. Dry it, and you get parts that bend before they break. PETG is what you print when PLA just isn't enough.",
        "text_overlay": [
            "TOUGH + CLEAR-ISH",
            "230-250°C NOZZLE",
            "~80°C BED",
            "MOISTURE IS THE ENEMY",
            "BENDS BEFORE IT BREAKS",
        ],
        "scenes": [
            {
                "goal": "Hook: bend test",
                "teaching_point": "PETG deforms instead of snapping",
                "shot": "macro close-up of a clear PETG part bending under hand force",
                "motion": "slow flex, spring back",
                "lighting": "warm workbench light",
                "background": "materials lab shelf blur",
                "objects": ["clear PETG part", "hand"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a clear PETG 3D printed part flexing under hand pressure, warm workbench lighting, materials lab background",
            },
            {
                "goal": "Print window",
                "teaching_point": "230-250 C nozzle, 70-90 C bed, lower cooling than PLA",
                "shot": "medium shot of a printer extruding glossy PETG",
                "motion": "slow push-in on the hotend",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["hotend", "glossy PETG part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer extruding glossy transparent PETG, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Moisture story",
                "teaching_point": "Wet PETG prints cloudy, stringy, and brittle",
                "shot": "macro comparison of cloudy wet PETG print vs clear dried PETG print",
                "motion": "slow pan between the two",
                "lighting": "soft side light showing cloudiness",
                "background": "neutral bench",
                "objects": ["cloudy PETG sample", "clear PETG sample"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph comparing a cloudy brittle PETG sample with a clear glossy dried sample, soft side lighting, neutral workbench",
            },
            {
                "goal": "Drying fix",
                "teaching_point": "Dry at 60-65 C for several hours to restore quality",
                "shot": "medium shot of a filament drying box with a PETG spool",
                "motion": "slow push-in on the dryer display",
                "lighting": "warm ambient light",
                "background": "storage shelf",
                "objects": ["filament dryer", "PETG spool", "display"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a filament drying box with a PETG spool inside, warm ambient light, storage shelf background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "PETG is the default when PLA isn't enough",
                "shot": "wide hero shot of a functional PETG bracket outdoors",
                "motion": "slow orbit",
                "lighting": "bright daylight",
                "background": "outdoor wall",
                "objects": ["PETG bracket", "mounting hardware"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of a clear PETG 3D printed bracket mounted on an outdoor wall, bright daylight, realistic product photography",
            },
        ],
        "thumbnail": {
            "concept": "Clear PETG part bending without breaking beside a cloudy wet sample",
            "subject": "transparent PETG bracket flexing under load, cloudy sample beside it",
            "background": "dark materials lab blur",
            "angle": "macro eye-level",
            "lighting": "hard key with rim",
            "composition": "flexing bracket centered, cloudy sample in the corner",
            "text": "PETG",
            "elements": ["flexing PETG bracket", "cloudy sample", "spool edge"],
            "style": "macro product photography",
            "mood": "tough, practical, clear",
            "prompt": "macro photograph of a clear PETG 3D printed bracket flexing without breaking, a cloudy wet PETG sample in the corner, hard key light with rim, dark materials lab, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PETG: The Workhorse Filament Explained",
            "title_variations": [
                "PETG Print Settings You Actually Need",
                "Why PETG Bends Before It Breaks",
                "The Moisture Trap That Ruins PETG",
                "PETG vs PLA vs ABS in 30 Seconds",
                "Your Next Functional Print: PETG",
            ],
            "description": "What is PETG and why is it the workhorse filament? It sits between PLA and ABS: tougher than PLA, less fussy than ABS, printing at 230-250 C with a hot bed around 80 C. The catch is moisture - wet PETG prints cloudy, stringy, and weak. Learn the print window, the drying fix, and when to choose PETG for functional, outdoor, and water-contact parts.",
            "hashtags": ["#3Dprinting", "#PETG", "#Filament", "#3DPrintingTips"],
            "seo_keywords": [
                "petg filament",
                "petg print settings",
                "petg vs pla",
                "dry petg filament",
                "petg moisture",
                "petg temperature",
                "functional filament",
            ],
        },
        "fact_check": [
            "PETG prints typically at 230-250 C nozzle and 70-90 C bed; exact values vary by brand and should follow the spool label.",
            "PETG is hygroscopic; drying at 60-65 C for 4-6 hours is the common recommendation.",
            "Moisture hydrolysis at melt temperature produces surface voids, cloudiness, stringing, and reduced strength.",
            "PETG is generally tougher but less stiff than PLA and slightly softer; it shows greater elongation before break.",
            "Food safety is not guaranteed by material alone; additives, layer interfaces, and surface porosity matter.",
            "Units: temperatures in degrees Celsius.",
        ],
    },
    # ======================================================================
    {
        "topic": "Warping Causes & Fixes",
        "core_question": "Why does my print warp and curl off the bed?",
        "learning_objective": "The viewer can explain warping as cooling shrinkage fighting adhesion, and apply the standard fix sequence: bed temp, cooling, drafts, brim.",
        "engineering_summary": "Warping is differential thermal shrinkage. Newly deposited layers cool and shrink while already-printed, still-warm lower layers resist; when shrinkage stress exceeds the adhesion force between the part and the build plate, the corners or edges lift. High-shrinkage materials (ABS, nylon, PC) warp more than low-shrinkage PLA. The fix chain: raise bed temperature, reduce drafts and cooling fan on early layers, add an enclosure, and use a brim to multiply the contact area at the part edges.",
        "real_world_application": "ABS automotive prototypes are printed in heated enclosures at 90-110 C chamber; large flat PETG bases use brims and textured plates; production runs preheat the chamber before the first layer.",
        "common_misconceptions": [
            "Warping is a bed adhesion problem only (it is shrinkage stress exceeding adhesion - both sides matter)",
            "More glue always fixes warping (adhesion without heat management still loses to big parts)",
            "Only ABS warps (PETG and nylon warp too, just less)",
        ],
        "teaching_strategy": "Show the physics as a tug-of-war: shrinkage stress on one side, adhesion on the other; then apply each fix to the losing side.",
        "script": "Why does your print curl off the bed like a taco? Shrinkage. Plastic contracts as it cools, and the top layers cool fastest, pulling upward while the bottom is still stuck - something has to give, and the corners let go. Warping is a battle between cooling and adhesion. Slow the cooling, crank the bed temperature, and shield the printer from drafts. An enclosure is even better. For ABS and nylon, a brim gives the corners something to hold onto. You can't stop shrinkage - you can only manage it.",
        "text_overlay": [
            "SHRINKAGE = TACO",
            "COOLING vs ADHESION",
            "BED TEMP + NO DRAFTS",
            "ENCLOSURE = HEAT ZONE",
            "BRIM = MORE GRIP",
        ],
        "scenes": [
            {
                "goal": "Hook: curled corners",
                "teaching_point": "Shrinkage stress lifts the corners off the bed",
                "shot": "macro close-up of a warped print with lifted corners",
                "motion": "slow push-in on the curled edge",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["warped printed part", "build plate"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part with corners curled up off the build plate, raking side light, dark workshop background",
            },
            {
                "goal": "The physics",
                "teaching_point": "Cooling top layers pull against the stuck bottom",
                "shot": "graphic-style shot of a layer cross-section with tension arrows",
                "motion": "arrows grow as layers cool",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer cross-section", "tension arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D layer cross-section diagram with cooling shrinkage tension arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The fix chain",
                "teaching_point": "Bed temperature up, cooling down, drafts blocked",
                "shot": "medium shot of hands adjusting bed temperature on a printer screen",
                "motion": "hand action, value changing",
                "lighting": "neutral workshop light",
                "background": "print lab",
                "objects": ["printer screen", "bed temperature setting"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand adjusting the bed temperature on a 3D printer touchscreen, neutral workshop lighting, modern print lab",
            },
            {
                "goal": "Enclosure",
                "teaching_point": "A warm chamber keeps shrinkage uniform",
                "shot": "wide shot of a printer inside a clear enclosure",
                "motion": "slow dolly around the enclosure",
                "lighting": "warm chamber light",
                "background": "print lab",
                "objects": ["printer", "clear enclosure"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer inside a clear acrylic enclosure, warm chamber lighting, print lab background",
            },
            {
                "goal": "Brim takeaway",
                "teaching_point": "A brim multiplies edge contact area",
                "shot": "wide hero shot of a part with a brim on the build plate",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed part with brim", "build plate"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printed part with a brim ring on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Taco-shaped warped part with a red shrink arrow and a clean part with a brim beside it",
            "subject": "warped print with curled corners next to a flat print with a brim",
            "background": "dark workshop blur",
            "angle": "macro side profile",
            "lighting": "raking side light",
            "composition": "warped part left, flat brimmed part right",
            "text": "WHY IT WARPS",
            "elements": ["curled corners", "brim ring", "build plate"],
            "style": "diagnostic macro photography",
            "mood": "frustrated then solved, instructive",
            "prompt": "macro photograph of a warped 3D printed part with curled corners on the left and a flat part with a brim on the right, raking side light, dark workshop background, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Why Prints Warp (And the 4-Step Fix)",
            "title_variations": [
                "Stop Corner Lifting for Good",
                "Warping Isn't a Glue Problem",
                "The Taco Print: Causes and Fixes",
                "ABS Warping? Here's the Physics",
                "How to Keep Prints Flat",
            ],
            "description": "Why do 3D prints curl up like tacos? Warping is cooling shrinkage fighting bed adhesion: the top layers shrink as they cool and pull the corners free. This short explains the physics and the four fixes that actually work - raise bed temperature, cut cooling on early layers, block drafts, and add an enclosure. Plus why a brim gives stubborn materials like ABS and nylon the extra grip they need.",
            "hashtags": ["#3Dprinting", "#Warping", "#Troubleshooting", "#ABS"],
            "seo_keywords": [
                "3d print warping",
                "corners lifting print",
                "fix warping abs",
                "bed adhesion warping",
                "printer enclosure warping",
                "brim for warping",
                "curling edges print",
            ],
        },
        "fact_check": [
            "Warping severity correlates with material shrinkage coefficient: PLA ~0.3-0.5%, ABS ~0.7-1%, nylon and PC higher.",
            "The fix chain (bed temp, cooling, drafts, enclosure) applies across materials; ABS commonly needs a 90-110 C chamber for large parts.",
            "A brim increases edge contact area with the build plate, resisting lift without the vertical interface of a raft.",
            "First-layer fan off and reduced cooling in the first few layers reduces thermal gradient.",
            "Textured PEI and engineering-grade build surfaces add mechanical keying that outperforms most glues.",
            "Units: temperatures in degrees Celsius; shrinkage as percentage of dimension.",
        ],
    },
    # ======================================================================
    {
        "topic": "Steel vs Aluminum",
        "core_question": "Should this part be steel or aluminum?",
        "learning_objective": "The viewer can reason about stiffness, weight, and strength to pick between steel and aluminum for a part.",
        "engineering_summary": "Steel is roughly three times stiffer and three times denser than aluminum (Young's modulus ~200 vs ~70 GPa; density ~7.85 vs ~2.70 g/cm3). Yield strength depends on alloy and heat treatment: mild steel ~250 MPa, common 6061-T6 aluminum ~276 MPa, so strength-per-mass can favor aluminum. For stiffness-limited design, aluminum wins stiffness-per-kilo because the density advantage outweighs the modulus deficit; steel wins where space is limited or strength-per-area matters.",
        "real_world_application": "Bicycle frames and aircraft structures use aluminum or steel tubes sized for stiffness-per-weight; machine spindles and thin linkages use steel for compact strength; 3D printer gantries use aluminum extrusion for light stiffness.",
        "common_misconceptions": [
            "Steel is always stronger (6061-T6 yields around the same stress as mild steel, at a third of the weight)",
            "Aluminum is never as stiff (it is stiffer per kilogram than steel)",
            "All aluminum is the same (6061, 7075, and cast grades differ by 3x in yield strength)",
        ],
        "teaching_strategy": "Do the geometry trick: compare a solid steel bar with a hollow aluminum tube of the same bending stiffness - one is much lighter, which is the whole engineering story.",
        "script": "Steel or aluminum? It depends on what the part does. Steel is about three times stiffer and three times denser than aluminum. If it carries load and space is tight, steel wins. Aluminum is one third the weight for the same shape - so when the part moves, like a bracket on a robot arm, aluminum wins. Same stiffness with a fraction of the weight? Add more material. That's why aluminum beams have thick walls: they trade size for mass. Stiffness per kilo: aluminum. Strength per millimeter: steel.",
        "text_overlay": [
            "STEEL: 3x STIFFER, 3x DENSER",
            "TIGHT SPACE = STEEL",
            "MOVING PART = ALUMINUM",
            "HOLLOW TUBE = SAME STIFFNESS",
            "STIFFNESS/kg: ALUMINUM",
        ],
        "scenes": [
            {
                "goal": "Hook: the weight test",
                "teaching_point": "Same-size steel and aluminum parts weigh very differently",
                "shot": "two identical brackets, one steel one aluminum, held side by side",
                "motion": "hand-off weight comparison",
                "lighting": "bright workbench light",
                "background": "machine shop blur",
                "objects": ["steel bracket", "aluminum bracket"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand holding a steel bracket next to an identical aluminum bracket, bright workbench lighting, machine shop background",
            },
            {
                "goal": "The numbers",
                "teaching_point": "Three times the stiffness, three times the density",
                "shot": "graphic-style shot of steel vs aluminum bars under a load",
                "motion": "bending comparison animation",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["steel bar", "aluminum bar", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a steel bar and an aluminum bar under bending load with force arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Stiffness per kilo",
                "teaching_point": "Hollow aluminum sections match steel stiffness at less weight",
                "shot": "solid steel bar vs hollow aluminum tube side by side",
                "motion": "slow orbit around both",
                "lighting": "workshop key light",
                "background": "machine shop",
                "objects": ["solid steel bar", "hollow aluminum tube"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a solid steel round bar next to a hollow aluminum square tube, workshop key lighting, machine shop background",
            },
            {
                "goal": "When each wins",
                "teaching_point": "Moving parts favor aluminum; tight spaces favor steel",
                "shot": "robot arm with aluminum bracket vs compact steel linkage",
                "motion": "cross-fade between the two",
                "lighting": "neutral lab light",
                "background": "engineering lab",
                "objects": ["robot arm", "aluminum bracket", "steel linkage"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a robot arm with an aluminum bracket in an engineering lab, neutral lighting, industrial robotics",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match material to the loading direction and weight budget",
                "shot": "wide hero shot of an aluminum extrusion gantry printing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["aluminum extrusion gantry", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer with an aluminum extrusion gantry, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Solid steel bar vs hollow aluminum tube, scale-balanced with a weight badge",
            "subject": "steel bar and aluminum tube crossing diagonally, hollow cross-section visible",
            "background": "dark machine shop blur",
            "angle": "macro low-angle",
            "lighting": "hard key with rim",
            "composition": "two bars crossing, cross-section facing camera",
            "text": "STEEL vs ALU",
            "elements": ["steel bar", "aluminum tube", "cross-sections"],
            "style": "industrial macro photography",
            "mood": "comparative, precise, weighty",
            "prompt": "macro photograph of a solid steel round bar crossing a hollow aluminum square tube with visible cross-sections, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp metal detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Steel vs Aluminum: Which Do You Need?",
            "title_variations": [
                "Steel Is 3x Stiffer, 3x Denser - So What?",
                "Why Aluminum Wins for Moving Parts",
                "Stiffness per Kilogram, Explained",
                "The Hollow Tube Trick",
                "Pick the Right Metal for the Job",
            ],
            "description": "Steel or aluminum? Steel is about three times stiffer and three times denser; common 6061-T6 aluminum actually matches mild steel in yield strength at one third the weight. This short explains the stiffness-per-kilogram trade, why hollow aluminum sections beat solid steel for moving parts, and when compact strength still makes steel the right call. Engineering material selection in 30 seconds.",
            "hashtags": ["#Engineering", "#Materials", "#MechanicalEngineering", "#SteelVsAluminum"],
            "seo_keywords": [
                "steel vs aluminum",
                "aluminum vs steel stiffness",
                "which metal is stronger",
                "6061 t6 strength",
                "stiffness per weight",
                "aluminum extrusion gantry",
                "lightweight metal parts",
            ],
        },
        "fact_check": [
            "Steel E ~200 GPa vs aluminum ~70 GPa; density 7.85 vs 2.70 g/cm3; both ratios are approximately 3:1.",
            "Mild steel yield ~250 MPa; 6061-T6 aluminum yield ~276 MPa - aluminum can match or exceed mild steel strength per area while weighing a third as much.",
            "For bending stiffness-limited design, aluminum outperforms steel on stiffness-per-mass; steel wins on stiffness-per-cross-section-area.",
            "7075-T6 aluminum yields ~503 MPa, showing why alloy choice matters as much as metal family.",
            "Units: modulus in GPa, density in g/cm3, yield in MPa.",
        ],
    },
    # ======================================================================
    {
        "topic": "Bearings: How They Work",
        "core_question": "How do bearings reduce friction so dramatically?",
        "learning_objective": "The viewer can explain sliding vs rolling friction, and the role of balls, cage, and grease in a ball bearing.",
        "engineering_summary": "A plain shaft on a journal drags with sliding friction, which for steel-on-steel has a coefficient around 0.1-0.2 (lubricated lower). A ball bearing replaces sliding contact with rolling contact at point contacts: rolling friction coefficients are roughly 50-100x lower (0.001-0.002 for ball bearings). The balls carry radial and axial loads through small contact patches (Hertzian contacts), the cage keeps balls evenly spaced, and grease manages wear and contamination. Load rating and preload trade friction against life and stiffness.",
        "real_world_application": "3D printer spindles, skateboard wheels, car wheel hubs, and machine tool spindles all rely on rolling elements; preloaded angular-contact pairs give machine spindles their stiffness.",
        "common_misconceptions": [
            "Bearings eliminate friction (they reduce it by about two orders of magnitude, not remove it)",
            "More grease is better (overgreasing adds drag and can overheat bearings)",
            "Bearings are maintenance free (they fail from contamination, and life is rated with L10 statistics)",
        ],
        "teaching_strategy": "Show the friction drop live: a spinning skateboard wheel vs a plain-axle wheel coasting, then open the bearing to reveal balls, cage, and race.",
        "script": "Push a wheel on a plain axle and it drags - sliding friction eats your energy. Now drop steel balls between the shaft and the housing. Sliding becomes rolling, and rolling friction is about fifty times lower. That's the whole trick of a ball bearing. The balls carry the load in tiny contact points, the cage keeps them evenly spaced, and grease absorbs what's left. It's why your printer's spindles spin freely, why skateboards roll on, and why heavy machines don't melt their axles. Friction doesn't disappear - it just rolls away.",
        "text_overlay": [
            "SLIDING = DRAG",
            "ROLLING ≈ 50x LOWER",
            "BALLS + CAGE + GREASE",
            "POINT CONTACTS CARRY LOAD",
            "FRICTION ROLLS AWAY",
        ],
        "scenes": [
            {
                "goal": "Hook: coasting test",
                "teaching_point": "Rolling beats sliding in the energy check",
                "shot": "two wheels on a ramp, one plain axle one bearing",
                "motion": "slow-motion coast to a stop",
                "lighting": "bright studio light",
                "background": "minimal studio",
                "objects": ["plain-axle wheel", "bearing wheel", "ramp"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two skateboard-style wheels racing down a ramp in a minimal studio, bright even lighting, product photography",
            },
            {
                "goal": "Open the bearing",
                "teaching_point": "Balls, cage, and race are the whole system",
                "shot": "macro close-up of a disassembled ball bearing",
                "motion": "slow orbit over the parts",
                "lighting": "soft studio light",
                "background": "dark bench blur",
                "objects": ["ball bearing parts", "steel balls", "cage", "races"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a disassembled ball bearing showing steel balls, cage, and races, soft studio lighting, dark bench",
            },
            {
                "goal": "The contact physics",
                "teaching_point": "Tiny point contacts carry the load",
                "shot": "graphic-style shot of a ball pressing into a race",
                "motion": "load arrows converging on contact patches",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bearing ball", "raceway", "contact patches"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bearing ball pressing into a raceway with contact force arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Where bearings live",
                "teaching_point": "Printers, skateboards, cars all run on rolling elements",
                "shot": "wide shot of a 3D printer axis with bearings visible",
                "motion": "slow pan along the linear rail",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer axis", "linear rail bearings"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer axis with exposed linear rail bearings, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Rolling converts drag into tiny contact costs",
                "shot": "wide hero shot of a spinning spindle in a machine",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["machine spindle", "bearings"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a machine spindle assembly with bearings, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Disassembled ball bearing with one ball rolling through a race, macro",
            "subject": "steel ball bearing with cage and balls spread across a race",
            "background": "dark bench blur",
            "angle": "macro top-down",
            "lighting": "hard key with rim",
            "composition": "bearing parts filling the frame, ball centered",
            "text": "HOW IT WORKS",
            "elements": ["steel balls", "cage", "race", "grease"],
            "style": "industrial macro photography",
            "mood": "revealing, precise, smooth",
            "prompt": "macro top-down photograph of a disassembled steel ball bearing with balls and cage spread across the race, hard key light with rim, dark bench, 9:16 vertical composition, ultra sharp steel detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "How Ball Bearings Beat Friction",
            "title_variations": [
                "Rolling vs Sliding: The Friction Drop",
                "Inside a Ball Bearing in 30 Seconds",
                "Why Bearings Spin So Freely",
                "Balls, Cage, and Grease Explained",
                "The Physics of Your Skateboard Wheel",
            ],
            "description": "How do ball bearings work? A wheel on a plain axle drags with sliding friction; put steel balls between shaft and housing and sliding becomes rolling, cutting friction by about fifty times. The balls carry load through tiny contact patches, the cage keeps them spaced, grease handles the rest. See the disassembled parts and the physics behind printers, skateboards, and machine spindles.",
            "hashtags": ["#Engineering", "#Bearings", "#MechanicalEngineering", "#Physics"],
            "seo_keywords": [
                "how bearings work",
                "ball bearing explained",
                "rolling friction vs sliding",
                "bearing parts cage race",
                "why bearings reduce friction",
                "bearing preload",
                "l10 bearing life",
            ],
        },
        "fact_check": [
            "Sliding steel-on-steel friction coefficient is typically 0.1-0.2 (lower when lubricated); ball bearing rolling friction is ~0.001-0.002, roughly 50-100x lower.",
            "Load transfers through Hertzian point contacts; contact area is small, so bearings need hardened steel (typically 52100 or similar).",
            "The cage prevents ball-to-ball contact and maintains spacing for even load sharing.",
            "Bearing life is statistically rated (L10: life at which 90% of a population survives), not a fixed lifetime.",
            "Over-lubrication causes churning losses and heating; bearings need a thin grease film, not a pack.",
            "Units: friction coefficients dimensionless; load in N.",
        ],
    },
    # ======================================================================
    {
        "topic": "Friction: Static vs Kinetic",
        "core_question": "Why is starting to push something harder than keeping it moving?",
        "learning_objective": "The viewer can distinguish static from kinetic friction and explain why anti-lock brakes pulse.",
        "engineering_summary": "Static friction acts between surfaces at rest and matches applied force up to a maximum roughly proportional to normal force (mu_s x N). Once motion starts, kinetic friction (mu_k x N) takes over, typically 10-30% lower. This peak-and-drop behavior explains the box-starting problem and, critically, why tires grip best just before slip: anti-lock brakes pulse the brake to keep the tire near the static limit, where grip is highest, and to keep steering control.",
        "real_world_application": "Tire braking and acceleration, clutch engagement, torque spec of bolted joints (clamp load resists slip via static friction), and 3D printer belt tension (friction keeps pulleys from slipping).",
        "common_misconceptions": [
            "Friction is a constant (static friction varies with applied load up to its maximum)",
            "Rougher surfaces always mean more friction (real contact area and adhesion dominate over macro roughness)",
            "Anti-lock brakes stop faster by locking wheels (they stop shorter on most surfaces by avoiding the kinetic slip regime)",
        ],
        "teaching_strategy": "Use the box push as the tactile anchor, then pivot to the tire: same physics, life-and-death stakes, memorable because of the 'pop' when it starts.",
        "script": "Why is it harder to start pushing a box than to keep pushing it? Static friction. Static friction holds things still, and it's usually stronger than kinetic friction, the sliding kind. Once you break static and the box moves, friction drops. That's why you feel the pop when it starts, and why anti-lock brakes pulse: they keep the wheel near the static limit, where grip is highest. Every launch, every brake, every grip: a friction story.",
        "text_overlay": [
            "STATIC HOLDS",
            "KINETIC SLIDES",
            "STATIC > KINETIC",
            "ABS = STAY NEAR STATIC",
            "GRIP IS A FRICTION STORY",
        ],
        "scenes": [
            {
                "goal": "Hook: the box",
                "teaching_point": "Starting a box takes more force than keeping it going",
                "shot": "medium shot of hands pushing a heavy box, then sliding it",
                "motion": "initial push, pop, smooth slide",
                "lighting": "warm warehouse light",
                "background": "storage room",
                "objects": ["heavy box", "hands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of hands pushing a heavy cardboard box across a floor in a storage room, warm practical lighting",
            },
            {
                "goal": "Define the two types",
                "teaching_point": "Static holds still, kinetic slides; static is stronger",
                "shot": "graphic-style shot of a block on a surface with force arrows",
                "motion": "force arrow grows to the breaking point, then drops",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["block", "surface", "force arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a block on a surface with friction force arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The drop",
                "teaching_point": "Friction peaks at the static limit then drops into kinetic",
                "shot": "macro shot of a scale showing the push force peaking and dropping",
                "motion": "needle spikes then settles",
                "lighting": "bright bench light",
                "background": "lab bench blur",
                "objects": ["force scale", "block", "surface"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a force scale needle measuring a block's push force on a lab bench, bright lighting, shallow depth of field",
            },
            {
                "goal": "The tire payoff",
                "teaching_point": "Brakes pulse to hold the tire at the static limit",
                "shot": "medium shot of a car tire braking on asphalt, close to lockup",
                "motion": "slow-motion brake, tire shudders then grips",
                "lighting": "bright daylight",
                "background": "test track",
                "objects": ["car tire", "asphalt"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a car tire braking hard on asphalt in slow motion, bright daylight, automotive photography, motion detail",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Every grip event is a static-versus-kinetic decision",
                "shot": "wide hero shot of a racing car launching off the line",
                "motion": "slow-motion launch",
                "lighting": "stadium light",
                "background": "race track",
                "objects": ["racing car", "launch"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of a racing car launching from a standing start on a race track, stadium lighting, automotive photography",
            },
        ],
        "thumbnail": {
            "concept": "Block at the tipping point with two arrows: one big static, one small kinetic, a tire inset",
            "subject": "wooden block on a floor with a hand pushing it, force arrows overlaid",
            "background": "dark studio blur",
            "angle": "medium eye-level",
            "lighting": "hard key with rim",
            "composition": "block left, hand right, arrows in negative space",
            "text": "STATIC > KINETIC",
            "elements": ["wooden block", "pushing hand", "force arrows"],
            "style": "educational photography",
            "mood": "simple, decisive, physical",
            "prompt": "photograph of a wooden block on a floor with a hand pushing it, large force arrows overlaid showing static and kinetic friction, hard key light with rim, dark studio, 9:16 vertical composition, crisp product style",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, logos",
        },
        "seo": {
            "title": "Static vs Kinetic Friction in 30 Seconds",
            "title_variations": [
                "Why Pushing a Box Is Harder at First",
                "The Friction Peak Behind ABS Brakes",
                "Why Tires Grip Best Before They Slip",
                "Static Friction Explained Simply",
                "Every Grip Is a Friction Story",
            ],
            "description": "Why is it harder to start pushing a box than to keep pushing it? Static friction holds things still and is usually stronger than kinetic friction, the sliding kind. Once motion starts, friction drops - that's the pop you feel. The same physics is why anti-lock brakes pulse: keeping the tire near the static limit maximizes grip. Understand friction, tires, clutches, and bolted joints in 30 seconds.",
            "hashtags": ["#Physics", "#Friction", "#Engineering", "#HowItWorks"],
            "seo_keywords": [
                "static vs kinetic friction",
                "static friction explained",
                "why is it harder to start pushing",
                "anti lock brakes physics",
                "coefficient of friction",
                "friction peak",
                "tire grip friction",
            ],
        },
        "fact_check": [
            "Static friction equals applied force up to a maximum of mu_s x N; kinetic friction is approximately constant at mu_k x N with mu_k typically 10-30% lower than mu_s.",
            "Friction laws are approximations (Amontons-Coulomb); real contact area, adhesion, and velocity effects complicate real surfaces.",
            "ABS pulses brakes to stay near the static limit where tire grip peaks, and to preserve steering.",
            "Clamp load in bolted joints resists shear via static friction between clamped surfaces.",
            "Units: friction coefficients dimensionless; force in N.",
        ],
    },
    # ======================================================================
    {
        "topic": "Torque vs Power",
        "core_question": "Is a car fast because of torque or horsepower?",
        "learning_objective": "The viewer can relate torque, power, and rpm through the power equation, and interpret engine curves.",
        "engineering_summary": "Torque is the twisting force at the crankshaft; power is the rate of energy delivery. Power (W) = torque (N-m) x angular speed (rad/s), so a high-torque diesel and a high-rpm motorcycle engine can produce equal power at different speeds. Vehicle acceleration is set by power at the wheels and gearing; the gearbox trades engine rpm for wheel torque. Broad torque curves feel strong at low rpm; high-rpm power is what determines top speed.",
        "real_world_application": "Electric motors deliver full torque from standstill - one reason EVs launch hard; diesels towing loads run low rpm with high torque; 3D printer steppers are chosen by their torque curve, not just step count.",
        "common_misconceptions": [
            "Torque alone makes a car fast (acceleration comes from wheel power, which includes gearing)",
            "Power and torque are competing properties (they are linked by rpm: P = T x omega)",
            "A flat torque curve and high power are mutually exclusive (modern engines and EVs have both)",
        ],
        "teaching_strategy": "Show the same power from two machines at different rpm (diesel truck vs motorcycle) to make the torque-rpm trade visceral, then state P = T x rpm once.",
        "script": "Is your car fast because of torque or horsepower? They're two sides of the same equation. Torque is the twisting force at the wheels; power is how fast you can deliver it. Power equals torque times rpm - so a diesel has huge torque but low rpm, and a sport bike has small torque at insane rpm, and they make similar power. Accelerating hard needs torque at the wheel; top speed needs power. So when someone argues torque vs power, they're both right: it's torque times revs, full stop.",
        "text_overlay": [
            "TORQUE = TWIST",
            "POWER = RATE OF WORK",
            "P = T x RPM",
            "DIESEL: BIG T, LOW RPM",
            "BIKE: SMALL T, HUGE RPM",
        ],
        "scenes": [
            {
                "goal": "Hook: the diesel vs the bike",
                "teaching_point": "Very different machines, similar power",
                "shot": "split-screen of a diesel truck and a sport bike",
                "motion": "cross-fade between the two",
                "lighting": "bright daylight",
                "background": "test road",
                "objects": ["diesel truck", "sport bike"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a diesel truck on a test road, bright daylight, automotive photography",
            },
            {
                "goal": "Define the terms",
                "teaching_point": "Torque is the twist; power is how fast you deliver it",
                "shot": "graphic-style shot of a wrench on a bolt and a clock overlay",
                "motion": "wrench turns, power readout climbs with speed",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wrench", "bolt", "power readout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a torque wrench turning a bolt with a power readout overlay on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The equation",
                "teaching_point": "Power = torque x rpm (with the right units)",
                "shot": "dynamometer screen with torque and power curves",
                "motion": "curves sweep across the display",
                "lighting": "screen glow in dark room",
                "background": "dyno cell",
                "objects": ["dyno display", "torque curve", "power curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a dynamometer screen showing torque and power curves in a dyno cell, screen glow in a dark room, automotive engineering",
            },
            {
                "goal": "The gearing twist",
                "teaching_point": "The gearbox turns engine rpm into wheel torque",
                "shot": "medium shot of a gearbox and driveshaft under a car on a lift",
                "motion": "slow orbit",
                "lighting": "workshop light",
                "background": "workshop",
                "objects": ["gearbox", "driveshaft", "car on lift"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a gearbox and driveshaft under a car on a workshop lift, practical workshop lighting, automotive engineering",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Torque at the wheel plus revs equals performance",
                "shot": "wide hero shot of an EV launching",
                "motion": "slow-motion launch from standstill",
                "lighting": "evening track light",
                "background": "race track",
                "objects": ["EV", "launch"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of an electric car launching from standstill on a race track at evening, track lighting, automotive photography",
            },
        ],
        "thumbnail": {
            "concept": "Diesel truck and sport bike split-screen with P = T x rpm overlaid",
            "subject": "truck on the left, sport bike on the right, equation in the middle",
            "background": "dark test-road blur",
            "angle": "medium low-angle",
            "lighting": "hard key with rim",
            "composition": "two vehicles mirrored, equation centered",
            "text": "P = T x RPM",
            "elements": ["diesel truck", "sport bike", "equation"],
            "style": "automotive photography",
            "mood": "fast, decisive, comparative",
            "prompt": "photograph of a diesel truck on the left and a sport bike on the right with a power equals torque times rpm equation between them, hard key light with rim, dark test road, 9:16 vertical composition, automotive photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, logos",
        },
        "seo": {
            "title": "Torque vs Power: Same Equation, Two Opinions",
            "title_variations": [
                "Why Diesels and Bikes Make the Same Power",
                "Power = Torque x RPM Explained",
                "Torque or Horsepower: Who's Right?",
                "How the Gearbox Turns Revs Into Torque",
                "Why EVs Launch So Hard",
            ],
            "description": "Torque or horsepower - which makes a car fast? They are two sides of one equation: power equals torque times rpm. A diesel makes huge torque at low revs, a sport bike makes small torque at insane revs, and they produce similar power. Learn why acceleration needs wheel torque, why top speed needs power, and how the gearbox connects both - in 30 seconds.",
            "hashtags": ["#Engineering", "#Torque", "#Horsepower", "#Automotive"],
            "seo_keywords": [
                "torque vs horsepower",
                "power equals torque times rpm",
                "why diesels have torque",
                "torque curve explained",
                "horsepower explained",
                "gearbox torque multiplication",
                "electric car torque",
            ],
        },
        "fact_check": [
            "Power (W) = torque (N-m) x angular speed (rad/s); in imperial terms hp = torque (lb-ft) x rpm / 5252.",
            "Wheel torque = engine torque x gear ratio x final drive ratio (minus drivetrain losses); acceleration depends on wheel torque and mass.",
            "EVs deliver near-full torque from zero rpm, which is why they launch hard off the line.",
            "Top speed is limited by power (aerodynamic drag), not raw torque.",
            "A broad, flat torque curve keeps power available across the rev range; peak power typically occurs at high rpm.",
        ],
    },
]