"""Batch 18: bed leveling, corner lifting, z-offset, stuck filament, thin walls, text, splitting, and support tools."""

CURATED = [
    # ======================================================================
    {
        "topic": "Bed Leveling Routine",
        "core_question": "How do you actually level a bed, and why does it drift?",
        "learning_objective": "The viewer can run a paper-method leveling pass and knows why it must be repeated.",
        "engineering_summary": "A level bed is the difference between a print that sticks and a print that drags. The paper method: heat the bed, home the printer, then slide paper under the nozzle at every corner and adjust until it drags with slight friction. Move in a spiral, corner to corner, because every adjustment nudges the others. Check the center too: a warped bed resists all corner work. Repeat after a few prints, since tramming drifts. Bed leveling is not a one-time setup; it is maintenance.",
        "real_world_application": "Every print starts with a level bed; the paper method is the universal baseline before probes and mesh compensation.",
        "common_misconceptions": [
            "Level once and forget it (tramming drifts with use)",
            "The corners are all that matter (the center sags on warped beds)",
            "Paper should slide freely (it should drag with slight friction)",
        ],
        "teaching_strategy": "Demonstrate the paper drag feel, then show a spiral corner pass and a center check.",
        "script": "A level bed is the difference between a print that sticks and a print that drags. The paper method: heat the bed, home the printer, then slide paper under the nozzle at every corner and adjust until it drags with slight friction. Move in a spiral, corner to corner, because every adjustment nudges the others. Check the center too: a warped bed resists all corner work. Repeat after a few prints, since tramming drifts. Bed leveling is not a one-time setup; it is maintenance.",
        "text_overlay": [
            "PAPER DRAGS WITH FRICTION",
            "SPIRAL CORNER TO CORNER",
            "CHECK THE CENTER TOO",
            "IT IS MAINTENANCE",
        ],
        "scenes": [
            {
                "goal": "Hook: the failed first layer",
                "teaching_point": "Level bed, print sticks",
                "shot": "close-up shot of a first layer dragging on the bed",
                "motion": "plastic smears across the plate",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["first layer", "print bed", "dragging plastic"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a first layer dragging across a print bed, bright task lighting, print lab",
            },
            {
                "goal": "The paper method",
                "teaching_point": "Paper drags with slight friction",
                "shot": "medium shot of paper sliding under the nozzle",
                "motion": "paper pulls with a drag",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["paper", "nozzle", "bed corner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of paper sliding under a nozzle at a bed corner, neutral lab lighting, workbench",
            },
            {
                "goal": "The spiral",
                "teaching_point": "Every corner nudges the others",
                "shot": "diagram-style shot of a bed with a spiral corner path",
                "motion": "path traces corner to corner",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bed diagram", "spiral path", "corner marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bed diagram with a spiral leveling path, clean engineering visualization on a dark background",
            },
            {
                "goal": "The center check",
                "teaching_point": "Warped beds sag in the middle",
                "shot": "close-up shot of a straightedge across the bed center",
                "motion": "light shows the gap",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["straightedge", "bed center", "gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a straightedge checking the center of a print bed, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Repeat after a few prints",
                "shot": "wide hero shot of a printer mid leveling check",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "leveling wrench", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer during a bed leveling check, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Paper under the nozzle with a drag arrow and a spiral bed path",
            "subject": "paper under nozzle",
            "background": "dark workshop blur",
            "angle": "close-up low angle",
            "lighting": "hard key with rim",
            "composition": "nozzle center, spiral path inset",
            "text": "LEVEL THE BED",
            "elements": ["paper", "nozzle", "spiral path"],
            "style": "geometry studio photography",
            "mood": "precise, repeatable, maintenance",
            "prompt": "photograph of paper sliding under a nozzle with a drag arrow and a spiral bed path, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bed Leveling: The Paper Method That Works",
            "title_variations": [
                "How to Level Your Print Bed",
                "Paper Method Leveling",
                "Why Bed Leveling Drifts",
                "Level Bed in Minutes",
                "First Layer Sticking Fix",
            ],
            "description": "A level bed is the foundation of every good print: if the first layer drags or floats, nothing after it can recover. The paper method is the universal baseline: heat the bed, home the machine, and slide a sheet of paper under the nozzle at each corner, adjusting until it drags with slight friction. Work in a spiral because each corner change nudges the others, and check the center, where warped beds sag. Tramming drifts with use, so leveling is maintenance, not a one-time fix. This short walks the full routine with the feel, the order, and the center check.",
            "hashtags": ["#BedLeveling", "#3Dprinting", "#Adhesion", "#Tips"],
            "seo_keywords": [
                "how to level print bed",
                "paper method leveling",
                "bed leveling spiral",
                "why first layer drags",
                "warped bed center",
                "level bed with paper",
                "bed tramming maintenance",
            ],
        },
        "fact_check": [
            "The paper method uses slight drag as the gap reference.",
            "Heat the bed before leveling, since it changes shape.",
            "Adjustments at one corner shift the others.",
            "Warped beds sag in the center and resist corner fixes.",
            "Tramming drifts, so repeat the routine periodically.",
        ],
    },
    {
        "topic": "Corner Lifting",
        "core_question": "Why do print corners peel up, and how do you stop it?",
        "learning_objective": "The viewer understands shrinkage-driven warping and the fixes that counter it.",
        "engineering_summary": "Corner lifting happens when the print's edges peel up as the plastic cools and shrinks. The bottom layer cools first and shrinks; the layers above cool later and pull the corners upward. Warping gets worse with big flat parts, high bed temperatures, and materials that shrink a lot, like ABS. Fixes: a hotter bed and enclosed chamber warm the part evenly, a brim adds a sacrificial edge, and a rougher surface grips harder. If corners still lift, the geometry fights the material. Shrinkage is the engine; adhesion is the brake.",
        "real_world_application": "Big flat bases, ABS and PETG prints, and unenclosed machines are the classic corner-lifting cases.",
        "common_misconceptions": [
            "More heat always helps (too hot softens the part base)",
            "Corners lift from bad first layers (it is cooling shrinkage)",
            "Brims are waste (they are cheap insurance for flat parts)",
        ],
        "teaching_strategy": "Show the cooling sequence, then the three counters: heat, brim, and surface grip.",
        "script": "Corner lifting happens when the print's edges peel up as the plastic cools and shrinks. The bottom layer cools first and shrinks; the layers above cool later and pull the corners upward. Warping gets worse with big flat parts, high bed temperatures, and materials that shrink a lot, like ABS. Fixes: a hotter bed and enclosed chamber warm the part evenly, a brim adds a sacrificial edge, and a rougher surface grips harder. If corners still lift, the geometry fights the material. Shrinkage is the engine; adhesion is the brake.",
        "text_overlay": [
            "COOL = SHRINK",
            "LAYERS PULL THE CORNERS UP",
            "BRIM = SACRIFICIAL EDGE",
            "SHRINKAGE VS ADHESION",
        ],
        "scenes": [
            {
                "goal": "Hook: the peeled corner",
                "teaching_point": "Edges curl up off the bed",
                "shot": "close-up shot of a print corner lifting off the bed",
                "motion": "corner curls upward slowly",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["lifting corner", "print bed", "curled edge"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a print corner lifting off the bed, bright task lighting, print lab",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Bottom cools first and shrinks",
                "shot": "diagram-style shot of layers cooling with shrink arrows",
                "motion": "shrink arrows pull the edges",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer diagram", "shrink arrows", "corner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layers cooling with shrink arrows, clean engineering visualization on a dark background",
            },
            {
                "goal": "The counters",
                "teaching_point": "Heat, brim, and grip",
                "shot": "medium shot of a printer with a brim and enclosure",
                "motion": "chamber warms as brim prints",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["enclosure", "brim", "hot bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printer printing a brim inside an enclosure, neutral lab lighting, workbench",
            },
            {
                "goal": "The surface",
                "teaching_point": "Rougher surfaces grip harder",
                "shot": "close-up shot of a textured build surface",
                "motion": "surface detail catches light",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["textured surface", "part base", "grip"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a textured build surface gripping a part base, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Shrinkage is the engine, adhesion the brake",
                "shot": "wide hero shot of a flat part printing flat with no lift",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flat part", "level print", "brim"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flat part printing with no corner lift, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A curled corner with shrink arrows and a brim counter beside it",
            "subject": "curled corner with arrows",
            "background": "dark workshop blur",
            "angle": "low side angle",
            "lighting": "hard key with rim",
            "composition": "corner center, brim counter at the side",
            "text": "STOP CORNER LIFT",
            "elements": ["curled corner", "shrink arrows", "brim"],
            "style": "geometry studio photography",
            "mood": "curling, fixable, hot",
            "prompt": "photograph of a curled print corner with shrink arrows and a brim counter beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Corner Lifting: Shrinkage vs Adhesion",
            "title_variations": [
                "Why Print Corners Lift",
                "Fix Warped Corners",
                "ABS Corner Warping Fix",
                "Brim vs Corner Lift",
                "Stop Print Curling",
            ],
            "description": "Corner lifting is plastic shrinkage made visible: the first layers cool and shrink against the bed while later layers pull the edges upward, and big flat parts make it worse. ABS warps hardest, PETG joins in, and even PLA curls on large bases. The counters are three: keep the part warm with a hot bed and an enclosure so it cools evenly, add a brim as a sacrificial edge that takes the curl, and use a surface with real grip. If corners still lift, the geometry is fighting the material. This short explains the mechanism and the fixes in order of impact.",
            "hashtags": ["#CornerLifting", "#Warping", "#3Dprinting", "#Adhesion"],
            "seo_keywords": [
                "why corners lift 3d printing",
                "corner warping fix",
                "abs corner lift",
                "brim vs corner lift",
                "print curling edges",
                "warped print base",
                "first layer adhesion warping",
            ],
        },
        "fact_check": [
            "Lifting is caused by cooling and shrinkage.",
            "Bottom layers shrink against the bed; later layers pull up.",
            "Big flat parts and high-shrink materials warp most.",
            "Hot beds, enclosures, and brims counter the pull.",
            "Rougher surfaces grip better against lifting.",
        ],
    },
    {
        "topic": "Z-Offset vs Z-Probe",
        "core_question": "What is the difference, and which one do you tune?",
        "learning_objective": "The viewer can separate probe offset from Z-offset and fix first-layer gaps correctly.",
        "engineering_summary": "Z-offset is the gap between the nozzle and the bed when the printer thinks it is at zero. Z-probe offset is how far the probe's trigger point sits from the nozzle tip. They work together: the probe measures the bed, the firmware subtracts the probe offset, and the Z-offset then fine-tunes the actual nozzle gap. Set the probe offset first, then tune Z-offset by tiny steps until a line of filament squishes flat. Confusing the two is the classic first-layer mistake. One measures the sensor; the other sets the nozzle.",
        "real_world_application": "First-layer gaps and squishy elephant-foot lines are fixed by tuning the right number in the firmware menu.",
        "common_misconceptions": [
            "Z-offset and probe offset are the same (they are different axes of the same system)",
            "The probe reads the nozzle position (it reads its own trigger point)",
            "Big Z-offset steps are fine (tenths of a millimeter change everything)",
        ],
        "teaching_strategy": "Show the two gaps on a diagram, then tune both on a live first layer.",
        "script": "Z-offset is the gap between the nozzle and the bed when the printer thinks it is at zero. Z-probe offset is how far the probe's trigger point sits from the nozzle tip. They work together: the probe measures the bed, the firmware subtracts the probe offset, and the Z-offset then fine-tunes the actual nozzle gap. Set the probe offset first, then tune Z-offset by tiny steps until a line of filament squishes flat. Confusing the two is the classic first-layer mistake. One measures the sensor; the other sets the nozzle.",
        "text_overlay": [
            "PROBE OFFSET = SENSOR POSITION",
            "Z-OFFSET = NOZZLE GAP",
            "SET PROBE FIRST",
            "SQUISH THE LINE FLAT",
        ],
        "scenes": [
            {
                "goal": "Hook: the bad first layer",
                "teaching_point": "Gaps or squish trace to offsets",
                "shot": "close-up shot of a first layer with gaps between lines",
                "motion": "gaps show along the lines",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["gapped first layer", "bed", "lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a gapped first layer on a print bed, bright task lighting, print lab",
            },
            {
                "goal": "The two offsets",
                "teaching_point": "Sensor gap versus nozzle gap",
                "shot": "diagram-style shot of the probe and nozzle with two gaps",
                "motion": "two gap markers highlight",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["probe", "nozzle", "gap markers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the probe and nozzle with two offset gaps, clean engineering visualization on a dark background",
            },
            {
                "goal": "The chain",
                "teaching_point": "Probe measures, firmware subtracts, offset tunes",
                "shot": "graphic-style shot of the measurement chain",
                "motion": "numbers flow probe to nozzle",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["measurement chain", "probe number", "nozzle gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a measurement chain from probe to nozzle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tuning",
                "teaching_point": "Tiny steps until the line squishes",
                "shot": "close-up shot of a live first layer being tuned",
                "motion": "lines change as the offset steps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["first layer line", "tuning steps", "nozzle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a first layer line being tuned in small steps, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Probe first, then the gap",
                "shot": "wide hero shot of a clean first layer completing",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean first layer", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean completed first layer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A probe and nozzle with two labeled gaps and a tuning arrow",
            "subject": "probe and nozzle gaps",
            "background": "dark workshop blur",
            "angle": "profile cutaway",
            "lighting": "hard key with rim",
            "composition": "two gaps labeled, arrow between them",
            "text": "TWO OFFSETS, ONE FIRST LAYER",
            "elements": ["probe", "nozzle", "gap labels"],
            "style": "geometry studio photography",
            "mood": "measured, tuned, distinct",
            "prompt": "photograph of a probe and nozzle with two labeled offset gaps and a tuning arrow, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Z-Offset vs Z-Probe: Two Gaps, One First Layer",
            "title_variations": [
                "Z Offset vs Probe Offset",
                "Fix First Layer Gaps",
                "Probe Offset Explained",
                "Tune Z Offset Correctly",
                "Nozzle Gap Calibration",
            ],
            "description": "Every auto-leveling printer has two numbers to understand: the Z-probe offset, which tells firmware how far the probe trigger sits from the nozzle tip, and the Z-offset, which sets the real gap between the nozzle and the bed. The probe measures the bed surface, firmware subtracts the probe offset, and the Z-offset does the final tuning. Set the probe offset once and correctly, then adjust Z-offset in tiny steps while watching a live first layer until the filament squishes flat. Mixing them up produces the classic gap or elephant foot. This short separates the two and shows the tuning sequence.",
            "hashtags": ["#ZOffset", "#ZProbe", "#FirstLayer", "#3Dprinting"],
            "seo_keywords": [
                "z offset vs probe offset",
                "z probe offset explained",
                "fix first layer gaps",
                "tune z offset",
                "nozzle bed gap",
                "elephant foot fix",
                "auto level calibration",
            ],
        },
        "fact_check": [
            "Z-offset is the nozzle-to-bed gap at zero.",
            "Probe offset is the probe trigger distance from the nozzle.",
            "Firmware subtracts probe offset from probe readings.",
            "Tune probe offset first, then Z-offset in small steps.",
            "A squished flat line is the target for the first layer.",
        ],
    },
    {
        "topic": "Stuck Filament",
        "core_question": "Filament won't move. What is actually wrong, and how do you fix it?",
        "learning_objective": "The viewer can diagnose jam, tangle, and break cases and clear them safely.",
        "engineering_summary": "A stuck filament is usually a jam, a tangler, or a break. First: heat the hotend to the material's temperature and pull gently; softened filament usually slides free. If it will not move, cool down and remove the nozzle, then push the plug out from above. Tangles come from careless spool handling; breaks hide above the extruder. A partial clog shows as skipped extrusion long before the filament jams. Fix the cause, not just the symptom. Heat, pull, clean, and check the spool: ninety percent of jams die in that order.",
        "real_world_application": "Mid-print jams, cold pulls, and spool tangles are routine maintenance that stops wasted hours.",
        "common_misconceptions": [
            "Pull hard when cold (heat first, then pull gently)",
            "Jams are always the nozzle (spool tangles and breaks are common)",
            "The jam is fixed when it clears (the cause must be removed too)",
        ],
        "teaching_strategy": "Walk the order: heat, pull, disassemble, clean, and check the spool.",
        "script": "A stuck filament is usually a jam, a tangler, or a break. First: heat the hotend to the material's temperature and pull gently; softened filament usually slides free. If it will not move, cool down and remove the nozzle, then push the plug out from above. Tangles come from careless spool handling; breaks hide above the extruder. A partial clog shows as skipped extrusion long before the filament jams. Fix the cause, not just the symptom. Heat, pull, clean, and check the spool: ninety percent of jams die in that order.",
        "text_overlay": [
            "HEAT, THEN PULL GENTLY",
            "PLUG OUT FROM ABOVE",
            "TANGLES AND BREAKS COUNT",
            "FIX THE CAUSE",
        ],
        "scenes": [
            {
                "goal": "Hook: the stuck strand",
                "teaching_point": "Nothing moves and the print stops",
                "shot": "close-up shot of filament stalled at the extruder",
                "motion": "gear spins without feeding",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["extruder gear", "stalled filament", "hotend"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of filament stalled at an extruder gear, bright task lighting, print lab",
            },
            {
                "goal": "Heat and pull",
                "teaching_point": "Softened plastic slides free",
                "shot": "medium shot of a hotend heating with filament being pulled",
                "motion": "strand eases out",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["hotend", "heated nozzle", "pulled strand"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a heated hotend with filament being pulled free, neutral lab lighting, workbench",
            },
            {
                "goal": "The nozzle",
                "teaching_point": "Remove and push the plug from above",
                "shot": "close-up shot of a nozzle being removed and cleaned",
                "motion": "plug pushes out of the nozzle",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["nozzle", "plug", "cleaning"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle with a plug being pushed out, bright task lighting, print lab",
            },
            {
                "goal": "The hidden causes",
                "teaching_point": "Tangles and breaks above the extruder",
                "shot": "medium shot of a spool with a tangle",
                "motion": "tangled loop tightens",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["spool", "tangle", "filament path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a filament spool with a tangle, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Heat, pull, clean, check the spool",
                "shot": "wide hero shot of a printer printing after the fix",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["running printer", "fresh spool"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer printing after a jam fix, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hotend with a filament strand being pulled and a tangle warning inset",
            "subject": "filament pull and tangle",
            "background": "dark workshop blur",
            "angle": "close-up side view",
            "lighting": "hard key with rim",
            "composition": "pull center, tangle inset corner",
            "text": "UNJAM IN ORDER",
            "elements": ["hotend", "filament pull", "tangle inset"],
            "style": "geometry studio photography",
            "mood": "stuck, ordered, fixable",
            "prompt": "photograph of a hotend with filament being pulled free and a tangle warning inset, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stuck Filament: The Fix Order That Works",
            "title_variations": [
                "How to Remove Stuck Filament",
                "Clear a Filament Jam",
                "Nozzle Jam Fix",
                "Spool Tangle Prevention",
                "Cold Pull Explained",
            ],
            "description": "When filament stops moving, the cause is usually one of three: a jam in the hotend, a tangle on the spool, or a break above the extruder. The fix order matters: heat the hotend to the material's temperature and pull gently, and softened plastic usually comes free; if not, cool the block, remove the nozzle, and push the plug out from above. Then find the cause, because a cleaned jam returns if the spool still tangles or the filament keeps breaking. Partial clogs announce themselves as skipped extrusion first. This short walks the whole order with the handling tips that prevent a repeat.",
            "hashtags": ["#StuckFilament", "#Jam", "#3Dprinting", "#Fix"],
            "seo_keywords": [
                "stuck filament fix",
                "how to remove filament jam",
                "nozzle clog cleared",
                "cold pull technique",
                "spool tangle prevention",
                "extruder skipping",
                "filament break above extruder",
            ],
        },
        "fact_check": [
            "Stuck filament is usually a jam, tangle, or break.",
            "Heat first, then pull gently.",
            "A plugged nozzle clears from above once removed.",
            "Partial clogs show as skipped extrusion first.",
            "Fix the cause or the jam returns.",
        ],
    },
    {
        "topic": "Wall Thickness Minimums",
        "core_question": "How thin can a wall actually print?",
        "learning_objective": "The viewer knows the two-wall minimum rule and why thin features fail.",
        "engineering_summary": "Wall thickness is the smallest a feature can be and still print as walls, not blobs. The rule of thumb: at least two times the nozzle diameter, so a 0.4 nozzle needs about 0.8 millimeters. Thinner walls come out as scattered dots because the slicer cannot fit a full extrusion. Fine details like letters need depth: thin features shrink to nothing or fuse together. When a model insists on thin walls, scale it up or change the design. Geometry thinner than the nozzle is not printable; it is a sketch.",
        "real_world_application": "Text, grilles, ribs, and lattice details fail predictably when their walls fall below two nozzle widths.",
        "common_misconceptions": [
            "One wall width is enough (it needs two for clean extrusion)",
            "Thinner is sharper (thin features fuse into blobs)",
            "The nozzle dictates the minimum (nozzle diameter times two is the rule)",
        ],
        "teaching_strategy": "Print a thickness ladder from 0.2 to 1.0 millimeters and show where it breaks.",
        "script": "Wall thickness is the smallest a feature can be and still print as walls, not blobs. The rule of thumb: at least two times the nozzle diameter, so a 0.4 nozzle needs about 0.8 millimeters. Thinner walls come out as scattered dots because the slicer cannot fit a full extrusion. Fine details like letters need depth: thin features shrink to nothing or fuse together. When a model insists on thin walls, scale it up or change the design. Geometry thinner than the nozzle is not printable; it is a sketch.",
        "text_overlay": [
            "2X NOZZLE DIAMETER MINIMUM",
            "0.4 NOZZLE = 0.8 MM WALL",
            "THIN = SCATTERED DOTS",
            "THINNER THAN THE NOZZLE IS A SKETCH",
        ],
        "scenes": [
            {
                "goal": "Hook: the wall ladder",
                "teaching_point": "Some widths print, some break",
                "shot": "close-up shot of a wall thickness test ladder",
                "motion": "camera pans from thin to thick",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["thickness ladder", "broken walls", "printed walls"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a wall thickness test ladder with broken and clean walls, bright task lighting, print lab",
            },
            {
                "goal": "The rule",
                "teaching_point": "Two times the nozzle diameter",
                "shot": "graphic-style shot of a nozzle with a two-width marker",
                "motion": "marker doubles to the wall width",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle", "two-width marker", "wall"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle with a two width wall marker, clean engineering visualization on a dark background",
            },
            {
                "goal": "The failure",
                "teaching_point": "Dots and fusing instead of walls",
                "shot": "diagram-style shot of thin walls breaking into dots",
                "motion": "walls crumble into scattered dots",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thin wall", "scattered dots", "break point"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of thin walls breaking into scattered dots, clean engineering visualization on a dark background",
            },
            {
                "goal": "The letters",
                "teaching_point": "Fine details need depth",
                "shot": "close-up shot of embossed letters failing on a print",
                "motion": "letters fill and blur",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["letters", "thin features", "print surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of thin letters failing on a printed surface, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Scale up or redesign",
                "shot": "wide hero shot of a redesigned part with clean thick walls",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["redesigned part", "thick walls", "clean details"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a redesigned part with clean thick walls, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle with a two-width rule and a thin wall breaking into dots",
            "subject": "nozzle and wall rule",
            "background": "dark workshop blur",
            "angle": "profile close-up",
            "lighting": "hard key with rim",
            "composition": "nozzle left, wall ladder right",
            "text": "2X NOZZLE MINIMUM",
            "elements": ["nozzle", "two-width rule", "wall ladder"],
            "style": "geometry studio photography",
            "mood": "minimal, precise, broken",
            "prompt": "photograph of a nozzle with a two width rule and a wall ladder breaking into dots, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Wall Thickness Minimums: The 2X Rule",
            "title_variations": [
                "How Thin Can a Wall Print",
                "Minimum Wall Thickness",
                "Thin Wall 3D Printing",
                "Why Thin Walls Fail",
                "0.4 Nozzle Wall Minimum",
            ],
            "description": "Every printer has a wall thickness floor: features need about twice the nozzle diameter to print as clean walls, so a 0.4 millimeter nozzle needs walls near 0.8 millimeters. Below that, the slicer cannot fit a full extrusion and thin features collapse into scattered dots, or fuse into blobs. Letters, ribs, and lattices fail exactly this way, and the fix is design: thicken the feature, scale the model, or swap to a smaller nozzle. This short shows the rule, the failure mode on a thickness ladder, and what to change when a model insists on thin geometry.",
            "hashtags": ["#WallThickness", "#Design", "#3Dprinting", "#Tips"],
            "seo_keywords": [
                "minimum wall thickness 3d printing",
                "2x nozzle wall rule",
                "how thin can a wall print",
                "thin walls fail",
                "0.4 nozzle minimum wall",
                "wall thickness ladder",
                "thin features fuse",
            ],
        },
        "fact_check": [
            "Walls need about two times the nozzle diameter.",
            "A 0.4 nozzle needs roughly 0.8 millimeter walls.",
            "Thinner features print as scattered dots or fused blobs.",
            "Text and ribs fail below the minimum.",
            "Thicken, scale up, or redesign to fix thin geometry.",
        ],
    },
    {
        "topic": "Embossed Text Orientation",
        "core_question": "Raised or engraved: which prints better, and how should you orient it?",
        "learning_objective": "The viewer knows embossed versus engraved trade-offs and the size rules for readable text.",
        "engineering_summary": "Text on a print either sticks out as embossed letters or sits cut into the surface as engraved ones. Embossed text prints cleaner: raised letters survive first layers, catch light, and tolerate small sizes. Engraved text needs enough depth for the slicer to carve real walls, or it reads as a shallow smudge. Keep letters at least a couple of millimeters tall and walls two widths thick, and print text-facing-up so the nozzle works on the flat face. Lettering is geometry; respect the minimums.",
        "real_world_application": "Name plates, panels, and label embossing fail on shallow engraves and undersized letters.",
        "common_misconceptions": [
            "Engraved text is easier (it needs more depth and walls)",
            "Any font size works (tiny letters fuse into blobs)",
            "Orientation does not matter (side walls show layer lines)",
        ],
        "teaching_strategy": "Print the same word both ways, then show the size and orientation rules.",
        "script": "Text on a print either sticks out as embossed letters or sits cut into the surface as engraved ones. Embossed text prints cleaner: raised letters survive first layers, catch light, and tolerate small sizes. Engraved text needs enough depth for the slicer to carve real walls, or it reads as a shallow smudge. Keep letters at least a couple of millimeters tall and walls two widths thick, and print text-facing-up so the nozzle works on the flat face. Lettering is geometry; respect the minimums.",
        "text_overlay": [
            "RAISED PRINTS CLEANER",
            "ENGRAVED NEEDS DEPTH",
            "2+ MM TALL LETTERS",
            "PRINT TEXT FACING UP",
        ],
        "scenes": [
            {
                "goal": "Hook: the smudged word",
                "teaching_point": "Shallow text reads as a blur",
                "shot": "close-up shot of a shallow engraved word on a print",
                "motion": "light rakes across the smudge",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["engraved word", "shallow depth", "surface"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a shallow engraved word on a printed surface, bright task lighting, print lab",
            },
            {
                "goal": "The comparison",
                "teaching_point": "Embossed versus engraved",
                "shot": "medium shot of two plates side by side",
                "motion": "camera pans between them",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["embossed plate", "engraved plate", "comparison"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of embossed and engraved text plates side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "The depth",
                "teaching_point": "Engraves need real wall depth",
                "shot": "diagram-style shot of an engrave cross section",
                "motion": "depth marker shows the walls",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["engrave section", "depth marker", "walls"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an engraved text cross section, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Size, wall width, orientation",
                "shot": "graphic-style shot of letters with size markers",
                "motion": "markers show height and width",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["letters", "height marker", "width marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of printed letters with height and width markers, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Raised, thick, facing up",
                "shot": "wide hero shot of a clean name plate printing",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["name plate", "raised letters"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean name plate with raised letters printing, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Raised letters next to a shallow engrave with a depth marker",
            "subject": "raised vs engraved text",
            "background": "dark workshop blur",
            "angle": "low raking angle",
            "lighting": "hard key with rim",
            "composition": "two words side by side, depth marker on the engrave",
            "text": "RAISED WINS",
            "elements": ["raised letters", "engraved word", "depth marker"],
            "style": "geometry studio photography",
            "mood": "readable, sharp, simple",
            "prompt": "photograph of raised letters beside a shallow engrave with a depth marker and a smooth surface finish, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Embossed vs Engraved Text: Print It Right",
            "title_variations": [
                "Raised or Engraved Text",
                "3D Print Text Tips",
                "Embossed Text Printing",
                "How to Print Readable Text",
                "Text Orientation for Prints",
            ],
            "description": "Text on a 3D print either rises as embossed letters or sinks as engraved ones, and the two need different treatment. Embossed text is the safer pick: raised letters survive the first layers, catch raking light, and print acceptably at small sizes. Engraved text demands real depth and wall width or it becomes a smudge. Either way, keep letters a couple of millimeters tall, walls at two nozzle widths, and orient the text face-up so the nozzle prints on the flat face instead of the side walls. This short compares both, shows the failure modes, and gives the size rules.",
            "hashtags": ["#EmbossedText", "#Text", "#3Dprinting", "#Design"],
            "seo_keywords": [
                "embossed vs engraved text",
                "print readable text 3d printing",
                "text orientation prints",
                "raised text printing",
                "engraved text depth",
                "letter size for printing",
                "name plate printing",
            ],
        },
        "fact_check": [
            "Embossed letters print cleaner than shallow engraves.",
            "Engraved text needs enough depth for real walls.",
            "Letters need at least a couple of millimeters of height.",
            "Walls should be about two nozzle widths.",
            "Print text facing up for the cleanest result.",
        ],
    },
    {
        "topic": "Splitting Large Parts",
        "core_question": "How do you print something bigger than the build volume?",
        "learning_objective": "The viewer can split a model into printable pieces with alignment features and sound joints.",
        "engineering_summary": "When a part is bigger than the build volume, you split it into pieces and join them after. Cut along flat planes so the seams hide in corners, and add alignment features: dowel holes, tabs, or a tongue and groove. Glue with the right adhesive, use screws when the part carries load, and orient each piece for its best surface finish. Splitting also rescues overhangs and makes parts stronger, since layer direction can change per piece. The seam is a design decision. Cut where it matters, align, and join.",
        "real_world_application": "Large enclosures, helmets, and structural brackets are routinely split, aligned, and joined with glue or screws.",
        "common_misconceptions": [
            "A straight cut is always best (seams hide better along feature lines)",
            "Glue alone holds everything (loads need screws or pins)",
            "Splitting weakens the part (orientation changes can strengthen it)",
        ],
        "teaching_strategy": "Show a big model, the cut planes, the alignment features, and the joined result.",
        "script": "When a part is bigger than the build volume, you split it into pieces and join them after. Cut along flat planes so the seams hide in corners, and add alignment features: dowel holes, tabs, or a tongue and groove. Glue with the right adhesive, use screws when the part carries load, and orient each piece for its best surface finish. Splitting also rescues overhangs and makes parts stronger, since layer direction can change per piece. The seam is a design decision. Cut where it matters, align, and join.",
        "text_overlay": [
            "CUT ALONG FLAT PLANES",
            "SEAMS HIDE IN CORNERS",
            "ALIGN: DOWELS, TABS, TONGUE",
            "GLUE FOR LOOKS, SCREWS FOR LOAD",
        ],
        "scenes": [
            {
                "goal": "Hook: the oversized model",
                "teaching_point": "Bigger than the build volume",
                "shot": "wide shot of a model exceeding the printer build volume",
                "motion": "model floats beyond the frame",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["big model", "build volume", "printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a large model beside a printer build volume, neutral lab lighting, workbench",
            },
            {
                "goal": "The cuts",
                "teaching_point": "Flat planes hide seams",
                "shot": "diagram-style shot of a model with cut planes",
                "motion": "planes slice the model apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["model", "cut planes", "split pieces"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a model splitting along cut planes, clean engineering visualization on a dark background",
            },
            {
                "goal": "Alignment",
                "teaching_point": "Dowel holes, tabs, tongue and groove",
                "shot": "close-up shot of alignment features on split edges",
                "motion": "pieces slide and lock",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["dowel holes", "tabs", "split edge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of dowel holes and tabs aligning split parts, bright task lighting, print lab",
            },
            {
                "goal": "Joining",
                "teaching_point": "Glue for looks, screws for load",
                "shot": "medium shot of pieces being glued and screwed",
                "motion": "seam closes and clamps",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["adhesive", "screws", "joined seam"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of split parts being glued and screwed together, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cut where it matters, align, join",
                "shot": "wide hero shot of the assembled large part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["assembled part", "hidden seam"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an assembled large printed part with hidden seams, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A model split along planes with alignment pins and a joined seam",
            "subject": "split model with pins",
            "background": "dark workshop blur",
            "angle": "exploded view",
            "lighting": "hard key with rim",
            "composition": "pieces explode from a center seam",
            "text": "SPLIT AND JOIN",
            "elements": ["split pieces", "alignment pins", "center seam"],
            "style": "geometry studio photography",
            "mood": "exploded, aligned, joinable",
            "prompt": "photograph of a model split along planes with alignment pins and a joined seam, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Splitting Large Parts: Cut, Align, Join",
            "title_variations": [
                "Print Parts Bigger Than the Bed",
                "Split a 3D Model for Printing",
                "How to Join Split Prints",
                "Alignment Features for Splits",
                "Large Print Assembly",
            ],
            "description": "When a part exceeds the build volume, the answer is a clean split: cut along flat planes where seams hide, add alignment features like dowel holes, tabs, or a tongue and groove, and join with the right adhesive or screws when the part carries load. Splitting also helps overhangs and strength, because each piece can be oriented for its own layer direction and best surface finish. The seam is a design decision, not a failure: placed well, it disappears. This short shows the cutting rules, the alignment options, and the joining methods that hold.",
            "hashtags": ["#Splitting", "#LargeParts", "#3Dprinting", "#Assembly"],
            "seo_keywords": [
                "split large 3d prints",
                "print bigger than bed",
                "join split prints",
                "alignment features printing",
                "large part assembly 3d print",
                "tongue and groove print",
                "hidden seams printing",
            ],
        },
        "fact_check": [
            "Cut along flat planes to hide seams.",
            "Alignment features make joining accurate.",
            "Glue suits light parts; screws carry load.",
            "Orientation can change per piece for strength and finish.",
            "Splitting rescues overhangs and big geometry.",
        ],
    },
    {
        "topic": "Support Removal Tools",
        "core_question": "What is the right way to take supports off without wrecking the part?",
        "learning_objective": "The viewer knows the tool set, the technique, and the settings that make removal easy.",
        "engineering_summary": "Support removal is a craft: the right tool leaves clean scars, the wrong one gouges the part. Flush cutters snap thin supports near the contact point; needle-nose pliers grip and twist bulk supports free. A deburring tool smooths the leftover nubs, and a heat gun softens stubborn bases without melting detail. Work from the outside in, and cut close, then sand the last hundredth. The contact interface matters more than the tool: tuned support settings halve the cleanup. Tools finish; settings start.",
        "real_world_application": "Post-processing every overhang needs the right cutter, plier, and deburring pass to keep parts clean.",
        "common_misconceptions": [
            "Pliers are the main tool (flush cutters work first)",
            "Scars are unavoidable (interface settings control them)",
            "One pass removes it all (cut close, then sand)",
        ],
        "teaching_strategy": "Show each tool on a real support, then the interface setting that prevents the fight.",
        "script": "Support removal is a craft: the right tool leaves clean scars, the wrong one gouges the part. Flush cutters snap thin supports near the contact point; needle-nose pliers grip and twist bulk supports free. A deburring tool smooths the leftover nubs, and a heat gun softens stubborn bases without melting detail. Work from the outside in, and cut close, then sand the last hundredth. The contact interface matters more than the tool: tuned support settings halve the cleanup. Tools finish; settings start.",
        "text_overlay": [
            "FLUSH CUTTERS FIRST",
            "TWIST BULK SUPPORTS FREE",
            "DEBURR THE NUBS",
            "TOOLS FINISH, SETTINGS START",
        ],
        "scenes": [
            {
                "goal": "Hook: the gouged part",
                "teaching_point": "Wrong tools leave scars",
                "shot": "close-up shot of a part with gouge marks from removal",
                "motion": "light shows the gouges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["gouged part", "scars", "support remnants"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part with gouge marks from support removal, bright task lighting, print lab",
            },
            {
                "goal": "The cutters",
                "teaching_point": "Snap close, then finish",
                "shot": "close-up shot of flush cutters snipping a support",
                "motion": "support snaps at the contact",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["flush cutters", "support", "contact point"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of flush cutters snapping a support at the contact point, bright task lighting, print lab",
            },
            {
                "goal": "The pliers",
                "teaching_point": "Grip and twist bulk supports",
                "shot": "medium shot of needle-nose pliers twisting a support block",
                "motion": "block twists and releases",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["needle-nose pliers", "support block", "twist"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of needle-nose pliers twisting a support block free, neutral lab lighting, workbench",
            },
            {
                "goal": "The finish",
                "teaching_point": "Deburr, sand the last hundredth",
                "shot": "close-up shot of a deburring tool on a nub",
                "motion": "nub smooths away",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["deburring tool", "nub", "smooth surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a deburring tool smoothing a support nub, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Settings start the fight",
                "shot": "wide hero shot of a clean part and the tool set",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean part", "tool set", "sandpaper"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean part with the support removal tool set, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Flush cutters snapping a support beside a clean part",
            "subject": "cutters on support",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "cutters center, clean part behind",
            "text": "REMOVE, DON'T GOUGE",
            "elements": ["flush cutters", "support", "clean part"],
            "style": "geometry studio photography",
            "mood": "clean, sharp, careful",
            "prompt": "photograph of flush cutters snapping a support at the contact point beside a clean part, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Support Removal: The Right Tools and Order",
            "title_variations": [
                "How to Remove Supports Cleanly",
                "Best Support Removal Tools",
                "No Scars Support Removal",
                "Deburring Prints",
                "Support Settings for Easy Removal",
            ],
            "description": "Support removal should leave a clean part, and the difference is tools and order. Flush cutters snap thin supports right at the contact point, needle-nose pliers grip and twist bulk supports free, a deburring tool smooths the leftover nubs, and a heat gun softens stubborn bases without melting detail. Work from the outside in, cut close, and sand the last little bit. The bigger win is prevention: support interface settings control how hard the fight is, so tuned settings halve the cleanup before you pick up a tool. This short covers the tool kit, the technique, and the settings.",
            "hashtags": ["#SupportRemoval", "#PostProcessing", "#3Dprinting", "#Tools"],
            "seo_keywords": [
                "support removal tools",
                "remove supports cleanly",
                "flush cutters 3d printing",
                "deburr printed parts",
                "support interface settings",
                "clean support scars",
                "remove tree supports",
            ],
        },
        "fact_check": [
            "Flush cutters snap supports at the contact point.",
            "Pliers grip and twist bulk supports free.",
            "Deburring tools smooth leftover nubs.",
            "A heat gun softens stubborn support bases.",
            "Interface settings reduce the cleanup more than tools do.",
        ],
    },
]