"""Batch 26: statics, RPM, F=ma, damping, Reynolds number, Poisson's ratio, heat sinks, cantilevers."""

CURATED = [
    # ======================================================================
    {
        "topic": "Statics: Balanced Forces",
        "core_question": "Why does nothing move when the forces balance?",
        "learning_objective": "The viewer understands equilibrium and balanced force sums.",
        "engineering_summary": "Statics is the study of parts that do not move: when all the forces on a body add to zero, it is in equilibrium, and nothing accelerates. The same rule covers rotation: the torques must cancel too, or the part spins. A ladder, a bridge, and a loaded bracket all sit still because their forces balance. Unbalance one force and the part moves until balance returns. Motionless does not mean force-free, it means summed.",
        "real_world_application": "Every support, frame, and bracket stands still because its forces cancel.",
        "common_misconceptions": [
            "Still parts have no forces (balance, not absence, holds them)",
            "Only forces matter (torques must cancel too)",
            "Equilibrium means weak (balanced systems can carry huge loads)",
        ],
        "teaching_strategy": "Show a load on a bracket and draw the balancing forces.",
        "script": "Statics is the study of parts that do not move: when all the forces on a body add to zero, it is in equilibrium, and nothing accelerates. The same rule covers rotation: the torques must cancel too, or the part spins. A ladder, a bridge, and a loaded bracket all sit still because their forces balance. Unbalance one force and the part moves until balance returns. Motionless does not mean force-free, it means summed.",
        "text_overlay": [
            "FORCES ADD TO ZERO",
            "TORQUES MUST CANCEL TOO",
            "BALANCE, NOT ABSENCE",
            "UNBALANCE IT AND IT MOVES",
        ],
        "scenes": [
            {
                "goal": "Hook: the loaded bracket",
                "teaching_point": "Still, but loaded",
                "shot": "medium shot of a loaded bracket hanging still on a wall",
                "motion": "bracket holds steady",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["bracket", "load", "wall mount"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a loaded bracket hanging still on a wall, neutral lab lighting, workbench",
            },
            {
                "goal": "The sum",
                "teaching_point": "Forces add to zero",
                "shot": "diagram-style shot of force arrows balancing on a body",
                "motion": "arrows cancel to zero",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["force arrows", "body", "zero sum"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of balanced force arrows, clean engineering visualization on a dark background",
            },
            {
                "goal": "The torques",
                "teaching_point": "Rotation must cancel too",
                "shot": "diagram-style shot of torque arrows balancing",
                "motion": "rotation arrows cancel",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["torque arrows", "pivot", "balance"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of balanced torques, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ladder",
                "teaching_point": "Wall and ground share the load",
                "shot": "medium shot of a ladder leaning against a wall",
                "motion": "contact forces hold it still",
                "lighting": "neutral lab light",
                "background": "workshop floor",
                "objects": ["ladder", "wall contact", "ground contact"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a ladder leaning against a wall, neutral lab lighting, workshop floor",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Motionless means summed",
                "shot": "wide hero shot of a balanced rig on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["balanced rig", "weights", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a balanced rig with weights on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bracket with force arrows cancelling to a zero sum",
            "subject": "balanced forces",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bracket center, arrows balancing",
            "text": "MOTIONLESS MEANS SUMMED",
            "elements": ["bracket", "force arrows", "zero sum"],
            "style": "geometry studio photography",
            "mood": "balanced, still, summed",
            "prompt": "photograph of a bracket with force arrows cancelling to a zero sum and a still loaded arm, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Statics: Balanced Forces, Motionless Means Summed",
            "title_variations": [
                "What Is Equilibrium",
                "Balanced Forces Explained",
                "Statics for Machines",
                "Force Balance Basics",
                "Why Parts Don't Move",
            ],
            "description": "Statics is the study of parts that do not move: when all the forces on a body add to zero it is in equilibrium and nothing accelerates, and the torques must cancel too or the part spins. A ladder, a bridge, and a loaded bracket all sit still because their forces balance, and unbalancing one force makes the part move until balance returns. This short sums the arrows, balances the torques, and shows the bracket that holds.",
            "hashtags": ["#Statics", "#Equilibrium", "#Forces", "#Engineering"],
            "seo_keywords": [
                "what is equilibrium",
                "balanced forces explained",
                "statics force balance",
                "torque balance rotation",
                "why parts don't move",
                "force sum zero",
                "statics for machines",
            ],
        },
        "fact_check": [
            "Equilibrium means forces sum to zero.",
            "Torques must cancel too.",
            "A still part can carry huge loads.",
            "Unbalancing a force makes the part move.",
            "Motionless means balanced, not force-free.",
        ],
    },
    {
        "topic": "RPM & Speed",
        "core_question": "What does RPM really mean on a motor?",
        "learning_objective": "The viewer understands RPM, speed ratios, and how gears trade speed.",
        "engineering_summary": "RPM counts revolutions per minute: how many full turns a shaft makes in sixty seconds, and it is the standard speed for rotating parts. Torque and RPM trade through gears: a small gear driving a big one cuts the speed and multiplies the force. The motor spins fast with little torque, and the gearbox converts that into slow and strong. RPM is the speed side of the power deal.",
        "real_world_application": "Every motor label, gearbox, and spindle spec is quoted in RPM.",
        "common_misconceptions": [
            "Higher RPM means more power (it is speed, not power)",
            "RPM and torque are fixed (gears trade them)",
            "RPM tells the surface speed (diameter matters for that)",
        ],
        "teaching_strategy": "Run a motor through two gear pairs and watch RPM drop as torque rises.",
        "script": "RPM counts revolutions per minute: how many full turns a shaft makes in sixty seconds, and it is the standard speed for rotating parts. Torque and RPM trade through gears: a small gear driving a big one cuts the speed and multiplies the force. The motor spins fast with little torque, and the gearbox converts that into slow and strong. RPM is the speed side of the power deal.",
        "text_overlay": [
            "TURNS PER MINUTE",
            "SIXTY SECONDS, FULL TURNS",
            "GEARS TRADE SPEED FOR FORCE",
            "FAST MOTOR, SLOW OUTPUT",
        ],
        "scenes": [
            {
                "goal": "Hook: the spinning shaft",
                "teaching_point": "Turns counted per minute",
                "shot": "close-up shot of a motor shaft spinning with a tachometer",
                "motion": "shaft turns, tach reads RPM",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["motor shaft", "tachometer", "spinning mark"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a motor shaft spinning with a tachometer, bright task lighting, print lab",
            },
            {
                "goal": "The count",
                "teaching_point": "Full turns in sixty seconds",
                "shot": "diagram-style shot of a shaft counting turns",
                "motion": "turn counter climbs",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shaft diagram", "turn counter", "minute mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram counting shaft turns per minute, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Speed for force",
                "shot": "diagram-style shot of a gear pair trading RPM and torque",
                "motion": "big gear slows and strengthens",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gear pair", "RPM arrows", "torque arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a gear pair trading RPM for torque, clean engineering visualization on a dark background",
            },
            {
                "goal": "The gearbox",
                "teaching_point": "Fast motor, strong output",
                "shot": "medium shot of a motor through a gearbox driving a load",
                "motion": "fast input becomes strong output",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["motor", "gearbox", "driven load"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a motor driving a load through a gearbox, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The speed side of power",
                "shot": "wide hero shot of motors and gearboxes on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["motors", "gearboxes", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of motors and gearboxes on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spinning shaft with an RPM readout and a gear pair trading speed",
            "subject": "RPM and speed ratio",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "shaft center, readout above",
            "text": "SPEED, NOT POWER",
            "elements": ["motor shaft", "RPM readout", "gear pair"],
            "style": "geometry studio photography",
            "mood": "spinning, counted, traded",
            "prompt": "photograph of a spinning motor shaft with an RPM readout and a gear pair trading speed, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "RPM & Speed: Turns Per Minute",
            "title_variations": [
                "What Does RPM Mean",
                "RPM vs Torque",
                "Motor Speed Explained",
                "Gear Speed Ratio",
                "Revolutions Per Minute",
            ],
            "description": "RPM counts revolutions per minute, the full turns a shaft makes in sixty seconds, and it is the standard speed for rotating parts. Torque and RPM trade through gears: a small gear driving a big one cuts the speed and multiplies the force, so a fast motor with little torque becomes a slow and strong output through a gearbox. This short spins a shaft, counts the turns, and shows the speed side of the power deal.",
            "hashtags": ["#RPM", "#MotorSpeed", "#Gears", "#Engineering"],
            "seo_keywords": [
                "what does rpm mean",
                "rpm vs torque",
                "motor speed explained",
                "gear speed ratio",
                "revolutions per minute",
                "gearbox speed trade",
                "rpm tachometer",
            ],
        },
        "fact_check": [
            "RPM counts turns per minute.",
            "It is the standard rotating speed.",
            "Gears trade speed for torque.",
            "A motor spins fast with little torque.",
            "Gearboxes convert speed into force.",
        ],
    },
    {
        "topic": "Dynamics: F=ma in Machines",
        "core_question": "How does Newton's second law size your motor?",
        "learning_objective": "The viewer understands F=ma and how acceleration sets force needs.",
        "engineering_summary": "Dynamics is the physics of parts in motion, and the engine is Newton's second law: force equals mass times acceleration. A heavier part needs more force to reach the same speed in the same time, and quick starts need more force than slow ones. Machines feel this as motor torque: acceleration demands peak torque, cruising needs almost none. The mass is fixed, the acceleration is your choice, and the force follows.",
        "real_world_application": "Printers, robots, and conveyors are sized by the acceleration they must deliver.",
        "common_misconceptions": [
            "Speed needs the force (acceleration, not speed, demands it)",
            "Mass only matters when still (it fights every change of speed)",
            "Bigger motors fix everything (acceleration is your choice)",
        ],
        "teaching_strategy": "Accelerate the same cart slowly and fast, and watch the force meter.",
        "script": "Dynamics is the physics of parts in motion, and the engine is Newton's second law: force equals mass times acceleration. A heavier part needs more force to reach the same speed in the same time, and quick starts need more force than slow ones. Machines feel this as motor torque: acceleration demands peak torque, cruising needs almost none. The mass is fixed, the acceleration is your choice, and the force follows.",
        "text_overlay": [
            "FORCE = MASS x ACCELERATION",
            "HEAVY NEEDS MORE FORCE",
            "QUICK STARTS, PEAK TORQUE",
            "CRUISING NEEDS ALMOST NONE",
        ],
        "scenes": [
            {
                "goal": "Hook: the quick start",
                "teaching_point": "Starts demand force",
                "shot": "medium shot of a cart accelerating quickly from a stop",
                "motion": "cart leaps forward",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["cart", "track", "start line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a cart accelerating quickly from a stop, neutral lab lighting, workbench",
            },
            {
                "goal": "The law",
                "teaching_point": "Force equals mass times acceleration",
                "shot": "diagram-style shot of the F=ma equation",
                "motion": "mass and acceleration multiply",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["F=ma equation", "mass term", "acceleration term"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Newton's second law equation, clean engineering visualization on a dark background",
            },
            {
                "goal": "The mass",
                "teaching_point": "Heavier needs more force",
                "shot": "diagram-style shot comparing two masses accelerating",
                "motion": "big mass lags the small one",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heavy mass", "light mass", "same target speed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram comparing heavy and light mass acceleration, clean engineering visualization on a dark background",
            },
            {
                "goal": "The torque",
                "teaching_point": "Peak at start, none at cruise",
                "shot": "graphic-style shot of a torque curve over speed",
                "motion": "torque peaks at start, falls off",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["torque curve", "start peak", "cruise line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of torque during acceleration and cruise, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Acceleration is your choice",
                "shot": "wide hero shot of a motion test rig on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["motion rig", "cart", "force meter"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a motion test rig on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cart with the F=ma equation and a torque peak at start",
            "subject": "F=ma in machines",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cart center, equation above",
            "text": "STARTS DEMAND TORQUE",
            "elements": ["cart", "F=ma equation", "torque curve"],
            "style": "geometry studio photography",
            "mood": "accelerating, sized, moving",
            "prompt": "photograph of a cart with the F=ma equation and a torque curve showing the start peak, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dynamics: F=ma in Machines, Starts Demand Torque",
            "title_variations": [
                "How F=ma Applies to Machines",
                "Newton's Second Law Explained",
                "Motor Sizing by Acceleration",
                "Acceleration Force Basics",
                "Dynamics for Design",
            ],
            "description": "Dynamics is the physics of parts in motion, and the engine is Newton's second law: force equals mass times acceleration. Heavier parts need more force to reach the same speed in the same time, and quick starts need far more force than cruising. Machines feel this as motor torque, with peak torque demanded at the start. This short accelerates a cart slowly and fast, and shows how the acceleration you choose sets the force you must build.",
            "hashtags": ["#FMA", "#Dynamics", "#Newton", "#Engineering"],
            "seo_keywords": [
                "f=ma machines",
                "newton's second law",
                "motor sizing acceleration",
                "acceleration force",
                "peak torque start",
                "mass times acceleration",
                "machine dynamics basics",
            ],
        },
        "fact_check": [
            "Force equals mass times acceleration.",
            "Heavier parts need more force.",
            "Quick starts demand peak torque.",
            "Cruising needs little force.",
            "The acceleration choice sets the force.",
        ],
    },
    {
        "topic": "Damping",
        "core_question": "How do machines swallow vibration?",
        "learning_objective": "The viewer understands damping and how energy is absorbed from motion.",
        "engineering_summary": "Damping is the art of draining energy from motion: every swing of a vibrating part fights a resisting force that turns the motion into heat. Springs store the energy, but dampers remove it, so a tuned damper makes a ringing part settle in one smooth decay. Too little damping and the part rings; too much and the part freezes like a door in honey. The balance is the tuning.",
        "real_world_application": "Car shocks, printer frames, and anti-vibration feet all tune damping.",
        "common_misconceptions": [
            "Damping is stiffness (springs store, dampers drain)",
            "More damping is always better (over-damping freezes response)",
            "Vibration dies on its own (it needs something to drain it)",
        ],
        "teaching_strategy": "Ring a springy arm and watch it settle with and without a damper.",
        "script": "Damping is the art of draining energy from motion: every swing of a vibrating part fights a resisting force that turns the motion into heat. Springs store the energy, but dampers remove it, so a tuned damper makes a ringing part settle in one smooth decay. Too little damping and the part rings; too much and the part freezes like a door in honey. The balance is the tuning.",
        "text_overlay": [
            "DRAIN THE MOTION",
            "SPRINGS STORE, DAMPERS REMOVE",
            "ONE SMOOTH DECAY",
            "TOO MUCH FREEZES",
        ],
        "scenes": [
            {
                "goal": "Hook: the ringing arm",
                "teaching_point": "Rings without damping",
                "shot": "medium shot of a springy arm ringing after a tap",
                "motion": "arm oscillates and decays slowly",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["springy arm", "tap point", "oscillation"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a springy arm ringing after a tap, neutral lab lighting, workbench",
            },
            {
                "goal": "The drain",
                "teaching_point": "Motion becomes heat",
                "shot": "diagram-style shot of vibration energy draining into heat",
                "motion": "oscillation shrinks as heat rises",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["oscillation trace", "heat arrow", "decay curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of damping draining vibration into heat, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pair",
                "teaching_point": "Spring stores, damper removes",
                "shot": "diagram-style shot of a spring and damper pair",
                "motion": "damper absorbs the swing",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["spring", "damper", "mass"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a spring and damper pair, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tuning",
                "teaching_point": "Balance the decay",
                "shot": "graphic-style shot comparing under, tuned, and over damping",
                "motion": "three decay curves compare",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["under damping", "tuned decay", "over damping"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of damping tuning curves, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Balance is the tuning",
                "shot": "wide hero shot of dampers and springs on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dampers", "springs", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of dampers and springs on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spring and damper pair with a decay curve settling",
            "subject": "damping tuned decay",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spring-damper center, curve beside",
            "text": "SPRINGS STORE, DAMPERS REMOVE",
            "elements": ["spring", "damper", "decay curve"],
            "style": "geometry studio photography",
            "mood": "drained, settled, tuned",
            "prompt": "photograph of a spring and damper pair with a settling decay curve beside them and a ringing arm, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Damping: Springs Store, Dampers Remove",
            "title_variations": [
                "What Is Damping",
                "Vibration Damping Explained",
                "How Shock Absorbers Work",
                "Damping Tuning Basics",
                "Energy Absorption in Machines",
            ],
            "description": "Damping is the art of draining energy from motion: every swing of a vibrating part fights a resisting force that turns the motion into heat. Springs store the energy, but dampers remove it, so a tuned damper makes a ringing part settle in one smooth decay. Too little damping rings forever and too much freezes the response. This short taps a springy arm, draws the decay curves, and shows the balance behind every shock absorber.",
            "hashtags": ["#Damping", "#Vibration", "#Shock", "#Engineering"],
            "seo_keywords": [
                "what is damping",
                "vibration damping explained",
                "how shock absorbers work",
                "damping tuning",
                "energy absorption motion",
                "under vs over damping",
                "spring damper system",
            ],
        },
        "fact_check": [
            "Damping drains energy from motion.",
            "Dampers turn motion into heat.",
            "Springs store, dampers remove.",
            "Too little damping rings.",
            "Too much damping freezes response.",
        ],
    },
    {
        "topic": "Reynolds Number",
        "core_question": "Laminar or turbulent: which flow are you designing for?",
        "learning_objective": "The viewer understands Reynolds number as the flow regime predictor.",
        "engineering_summary": "The Reynolds number predicts how fluid flows: it compares the push of motion to the pull of viscosity. Low numbers mean smooth laminar flow, where layers slide quietly; high numbers mean turbulent flow, where the fluid churns and mixes. The number grows with speed and size and falls with viscosity, so a pipe, a wing, and a nozzle all have their own regime. The flow is decided by one dimensionless number.",
        "real_world_application": "Nozzles, heat exchangers, and cooling channels are tuned by their Reynolds regime.",
        "common_misconceptions": [
            "Fast always means turbulent (size and viscosity matter too)",
            "Laminar is always better (mixing wants turbulence)",
            "Reynolds is a measurement (it is a dimensionless prediction)",
        ],
        "teaching_strategy": "Dye a slow stream and a fast stream and compare the regimes.",
        "script": "The Reynolds number predicts how fluid flows: it compares the push of motion to the pull of viscosity. Low numbers mean smooth laminar flow, where layers slide quietly; high numbers mean turbulent flow, where the fluid churns and mixes. The number grows with speed and size and falls with viscosity, so a pipe, a wing, and a nozzle all have their own regime. The flow is decided by one dimensionless number.",
        "text_overlay": [
            "MOTION PUSH VS VISCOSITY PULL",
            "LOW: LAMINAR, SMOOTH LAYERS",
            "HIGH: TURBULENT, CHURNING",
            "SPEED, SIZE, VISCOSITY",
        ],
        "scenes": [
            {
                "goal": "Hook: the dyed stream",
                "teaching_point": "Slow is smooth, fast churns",
                "shot": "close-up shot of dye flowing in a clear tube",
                "motion": "dye stays a thread, then churns",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["clear tube", "dye thread", "flowing water"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of dye flowing in a clear tube, bright task lighting, print lab",
            },
            {
                "goal": "The regimes",
                "teaching_point": "Laminar versus turbulent",
                "shot": "diagram-style shot comparing laminar layers and turbulent churn",
                "motion": "two flow patterns side by side",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["laminar layers", "turbulent churn", "comparison"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of laminar and turbulent flow, clean engineering visualization on a dark background",
            },
            {
                "goal": "The factors",
                "teaching_point": "Speed, size, viscosity",
                "shot": "graphic-style shot of the Reynolds factors scaling",
                "motion": "factors push the number up and down",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["speed term", "size term", "viscosity term"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Reynolds number factors, clean engineering visualization on a dark background",
            },
            {
                "goal": "The jobs",
                "teaching_point": "Pipes, wings, nozzles",
                "shot": "medium shot of flow parts on a bench",
                "motion": "parts shift between regimes",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["nozzle", "pipe section", "wing model"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle, pipe section, and wing model on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One number decides the flow",
                "shot": "wide hero shot of a flow test rig on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flow rig", "clear tube", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flow test rig on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Laminar layers and turbulent churn with the Reynolds number between",
            "subject": "Reynolds number flow",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two flow patterns side by side",
            "text": "ONE NUMBER DECIDES THE FLOW",
            "elements": ["laminar layers", "turbulent churn", "Reynolds number"],
            "style": "geometry studio photography",
            "mood": "flowing, predicted, compared",
            "prompt": "photograph of laminar layers and turbulent churn with the Reynolds number marked between them, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Reynolds Number: One Number Decides the Flow",
            "title_variations": [
                "What Is the Reynolds Number",
                "Laminar vs Turbulent Flow",
                "Reynolds Number Explained",
                "Flow Regime Prediction",
                "Reynolds for Nozzles",
            ],
            "description": "The Reynolds number predicts how a fluid flows by comparing the push of motion to the pull of viscosity. Low numbers mean smooth laminar flow where layers slide quietly; high numbers mean turbulent flow that churns and mixes. The number grows with speed and size and falls with viscosity, so every pipe, wing, and nozzle lives in its own regime. This short dyes a stream, compares the patterns, and shows the one number that decides the flow.",
            "hashtags": ["#ReynoldsNumber", "#FluidDynamics", "#Laminar", "#Turbulence"],
            "seo_keywords": [
                "what is the reynolds number",
                "laminar vs turbulent flow",
                "reynolds number explained",
                "flow regime prediction",
                "reynolds number formula",
                "viscosity flow speed",
                "nozzle flow regime",
            ],
        },
        "fact_check": [
            "Reynolds compares motion push to viscosity pull.",
            "Low numbers mean laminar flow.",
            "High numbers mean turbulent flow.",
            "The number grows with speed and size.",
            "It falls with higher viscosity.",
        ],
    },
    {
        "topic": "Poisson's Ratio",
        "core_question": "Why does stretching a material make it thinner?",
        "learning_objective": "The viewer understands Poisson's ratio and lateral squeeze.",
        "engineering_summary": "Poisson's ratio measures the sideways squeeze that comes with stretching: pull a material and it gets longer but thinner, and the ratio says how much thinner. Most materials sit around a third, so a stretched bar loses width about a third as fast as it gains length. Rubber is high and cork is nearly zero. The squeeze matters in every bearing press and seal. Stretch makes it thin, and the ratio predicts how thin.",
        "real_world_application": "Seals, press fits, and rubber mounts all depend on lateral squeeze.",
        "common_misconceptions": [
            "Stretching only changes length (it thins the sides too)",
            "All materials squeeze the same (rubber and cork differ wildly)",
            "The ratio is a guess (it is a measured material constant)",
        ],
        "teaching_strategy": "Stretch a rubber band and a metal wire and compare the thinning.",
        "script": "Poisson's ratio measures the sideways squeeze that comes with stretching: pull a material and it gets longer but thinner, and the ratio says how much thinner. Most materials sit around a third, so a stretched bar loses width about a third as fast as it gains length. Rubber is high and cork is nearly zero. The squeeze matters in every bearing press and seal. Stretch makes it thin, and the ratio predicts how thin.",
        "text_overlay": [
            "LONGER BUT THINNER",
            "ABOUT A THIRD FOR MOST",
            "RUBBER HIGH, CORK NEAR ZERO",
            "THE RATIO PREDICTS THE SQUEEZE",
        ],
        "scenes": [
            {
                "goal": "Hook: the rubber band",
                "teaching_point": "Pull long, it thins",
                "shot": "close-up shot of a rubber band being stretched",
                "motion": "band lengthens and narrows",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["rubber band", "stretch", "narrowing"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a rubber band stretching and narrowing, bright task lighting, print lab",
            },
            {
                "goal": "The ratio",
                "teaching_point": "Sideways over lengthwise",
                "shot": "diagram-style shot of a bar with stretch and squeeze arrows",
                "motion": "side squeeze scales with stretch",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stretched bar", "stretch arrow", "squeeze arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Poisson's ratio arrows, clean engineering visualization on a dark background",
            },
            {
                "goal": "The range",
                "teaching_point": "Rubber high, cork near zero",
                "shot": "graphic-style shot of materials on a Poisson scale",
                "motion": "materials slide along the scale",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["Poisson scale", "rubber marker", "cork marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Poisson's ratio across materials, clean engineering visualization on a dark background",
            },
            {
                "goal": "The jobs",
                "teaching_point": "Seals and press fits",
                "shot": "medium shot of a seal and a press fit on a bench",
                "motion": "squeeze shows in both parts",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["seal ring", "press fit", "squeezed parts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a seal ring and a press fit on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Stretch predicts thin",
                "shot": "wide hero shot of stretched samples on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stretched samples", "rubber band", "wire"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of stretched material samples on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A stretched bar with stretch and squeeze arrows and a material scale",
            "subject": "Poisson's ratio",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "stretched bar center, scale beside",
            "text": "LONGER BUT THINNER",
            "elements": ["stretched bar", "squeeze arrow", "material scale"],
            "style": "geometry studio photography",
            "mood": "stretched, squeezed, predicted",
            "prompt": "photograph of a stretched bar with stretch and squeeze arrows and a material scale beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Poisson's Ratio: Longer but Thinner",
            "title_variations": [
                "What Is Poisson's Ratio",
                "Poisson's Ratio Explained",
                "Lateral Strain Material",
                "Why Stretching Thins Material",
                "Poisson's Ratio for Seals",
            ],
            "description": "Poisson's ratio measures the sideways squeeze that comes with stretching: pull a material and it gets longer but thinner, and the ratio says how much thinner. Most materials sit around a third, rubber sits high, and cork sits near zero. The squeeze matters in every bearing press and seal. This short stretches a rubber band, draws the arrows, and shows how the ratio predicts the thinning that comes with every stretch.",
            "hashtags": ["#PoissonsRatio", "#Materials", "#Mechanics", "#Engineering"],
            "seo_keywords": [
                "what is poisson's ratio",
                "poisson's ratio explained",
                "lateral strain",
                "stretch thin material",
                "poisson's ratio rubber",
                "poisson ratio seals",
                "material squeeze stretch",
            ],
        },
        "fact_check": [
            "Stretching a material thins it sideways.",
            "Poisson's ratio predicts the squeeze.",
            "Most materials sit around a third.",
            "Rubber has a high ratio.",
            "Cork is nearly zero.",
        ],
    },
    {
        "topic": "Heat Sink Design",
        "core_question": "How do fins steal heat from a chip?",
        "learning_objective": "The viewer understands heat sinks, fins, and thermal resistance.",
        "engineering_summary": "A heat sink spreads heat out of a hot part into air: the base soaks the heat and the fins multiply the surface that touches the air. More surface means more cooling, which is why sinks are finned and blackened. The path has resistances: base, interface, and fins, and the bottleneck sets the temperature. Wider and taller fins help, but air must move past them. Cooling is surface area, and air flow is the partner.",
        "real_world_application": "Stepper drivers, CPUs, and hotends all shed heat through finned sinks.",
        "common_misconceptions": [
            "Bigger sink always cools (air flow must match)",
            "The base does the cooling (the fins expose the surface)",
            "Fin gaps are free (packed fins choke the airflow)",
        ],
        "teaching_strategy": "Run a heated block with no sink, a flat plate, and a finned sink.",
        "script": "A heat sink spreads heat out of a hot part into air: the base soaks the heat and the fins multiply the surface that touches the air. More surface means more cooling, which is why sinks are finned and blackened. The path has resistances: base, interface, and fins, and the bottleneck sets the temperature. Wider and taller fins help, but air must move past them. Cooling is surface area, and air flow is the partner.",
        "text_overlay": [
            "BASE SOAKS, FINS EXPOSE",
            "SURFACE AREA IS COOLING",
            "THE BOTTLENECK SETS THE HEAT",
            "AIR MUST MOVE PAST",
        ],
        "scenes": [
            {
                "goal": "Hook: the hot driver",
                "teaching_point": "Finned sink, cooler chip",
                "shot": "close-up shot of a finned heat sink on a hot part",
                "motion": "heat spreads into the fins",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["heat sink", "hot part", "fins"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a finned heat sink on a hot part, bright task lighting, print lab",
            },
            {
                "goal": "The surface",
                "teaching_point": "Fins multiply the air contact",
                "shot": "diagram-style shot of fins multiplying surface area",
                "motion": "surface count climbs with fins",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flat plate", "finned profile", "surface count"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fins multiplying surface area, clean engineering visualization on a dark background",
            },
            {
                "goal": "The path",
                "teaching_point": "Resistances in a row",
                "shot": "graphic-style shot of the thermal path resistances",
                "motion": "blocks stack base to fins",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["base block", "interface block", "fin block"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of heat sink thermal resistances, clean engineering visualization on a dark background",
            },
            {
                "goal": "The air",
                "teaching_point": "Air flow is the partner",
                "shot": "medium shot of a fan blowing across a finned sink",
                "motion": "air streams between the fins",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["cooling fan", "finned sink", "air stream"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a fan blowing air across a finned heat sink, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Surface area and air flow",
                "shot": "wide hero shot of heat sinks on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["heat sinks", "finned profiles", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of finned heat sinks on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A finned heat sink with heat spreading and air flowing past",
            "subject": "heat sink fins",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "sink center, air arrows crossing",
            "text": "SURFACE AREA IS COOLING",
            "elements": ["finned sink", "heat arrows", "air stream"],
            "style": "geometry studio photography",
            "mood": "cooled, finned, flowing",
            "prompt": "photograph of a finned heat sink with heat spreading into the fins and air flowing past, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heat Sink Design: Surface Area Is Cooling",
            "title_variations": [
                "How to Design a Heat Sink",
                "Heat Sink Fins Explained",
                "Thermal Resistance Basics",
                "Cooling Fins Design",
                "Heat Sink Air Flow",
            ],
            "description": "A heat sink spreads heat out of a hot part into air: the base soaks the heat and the fins multiply the surface that touches the air. More surface means more cooling, and the path has resistances through the base, the interface, and the fins, with the bottleneck setting the temperature. Wider and taller fins help, but air must move past them. This short heats a block with no sink, a plate, and a finned sink, and shows why cooling is surface area with airflow as the partner.",
            "hashtags": ["#HeatSink", "#Cooling", "#ThermalDesign", "#Electronics"],
            "seo_keywords": [
                "how to design a heat sink",
                "heat sink fins",
                "thermal resistance",
                "cooling fins design",
                "heat sink air flow",
                "finned surface cooling",
                "heat sink bottleneck",
            ],
        },
        "fact_check": [
            "The base soaks heat from the part.",
            "Fins multiply the air contact surface.",
            "Thermal resistance stacks along the path.",
            "The bottleneck sets the temperature.",
            "Air flow must move past the fins.",
        ],
    },
    {
        "topic": "Cantilever Loads",
        "core_question": "How much can a cantilever hold before it sags?",
        "learning_objective": "The viewer understands cantilever bending, moment, and tip deflection.",
        "engineering_summary": "A cantilever is a beam fixed at one end and free at the other, and the load at the tip is the worst case in statics. The fixed end feels the bending moment: the force times the arm, so doubling the length doubles the load felt and multiplies the sag. The tip drops with the load and with the length cubed, so short and deep wins. Every shelf and arm is a cantilever bet.",
        "real_world_application": "Shelf brackets, tool arms, and gantry overhangs are all cantilevers.",
        "common_misconceptions": [
            "The load feels the same everywhere (the fixed end carries the moment)",
            "Length matters a little (deflection grows with length cubed)",
            "Thicker always helps more than deeper (depth wins again)",
        ],
        "teaching_strategy": "Load a fixed arm at the tip and watch the sag grow with length.",
        "script": "A cantilever is a beam fixed at one end and free at the other, and the load at the tip is the worst case in statics. The fixed end feels the bending moment: the force times the arm, so doubling the length doubles the load felt and multiplies the sag. The tip drops with the load and with the length cubed, so short and deep wins. Every shelf and arm is a cantilever bet.",
        "text_overlay": [
            "FIXED ONE END, FREE THE OTHER",
            "TIP LOAD, WORST CASE",
            "DOUBLE LENGTH, MUCH MORE SAG",
            "SHORT AND DEEP WINS",
        ],
        "scenes": [
            {
                "goal": "Hook: the sagging arm",
                "teaching_point": "Fixed end, loaded tip",
                "shot": "medium shot of a cantilever arm sagging under a tip load",
                "motion": "tip drops as the load lands",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["cantilever arm", "tip load", "fixed base"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a cantilever arm sagging under a tip load, neutral lab lighting, workbench",
            },
            {
                "goal": "The moment",
                "teaching_point": "Force times the arm",
                "shot": "diagram-style shot of the bending moment at the fixed end",
                "motion": "moment grows with the arm",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cantilever diagram", "moment arrow", "arm length"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of cantilever bending moment, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sag",
                "teaching_point": "Length cubed",
                "shot": "graphic-style shot of deflection growing with length",
                "motion": "sag curve climbs steeply",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["deflection curve", "length axis", "sag line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of cantilever deflection versus length, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Short and deep wins",
                "shot": "diagram-style shot comparing short deep and long thin arms",
                "motion": "deep arm sags less",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["short deep arm", "long thin arm", "sag compare"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram comparing short deep and long thin cantilevers, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Every arm is a bet",
                "shot": "wide hero shot of cantilever arms on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["cantilever arms", "loads", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of cantilever arms with loads on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cantilever arm with a tip load and the bending moment at the fixed end",
            "subject": "cantilever load",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "arm center, moment arrow at base",
            "text": "SHORT AND DEEP WINS",
            "elements": ["cantilever arm", "tip load", "moment arrow"],
            "style": "geometry studio photography",
            "mood": "loaded, sagging, fixed",
            "prompt": "photograph of a cantilever arm with a tip load and the bending moment marked at the fixed end, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Cantilever Loads: Short and Deep Wins",
            "title_variations": [
                "How Much Can a Cantilever Hold",
                "Cantilever Beam Explained",
                "Cantilever Bending Moment",
                "Tip Deflection Basics",
                "Cantilever Design Rules",
            ],
            "description": "A cantilever is a beam fixed at one end and free at the other, and a tip load is the worst case in statics. The fixed end feels the bending moment, the force times the arm, and the tip drops with the load and with the length cubed, so doubling the length multiplies the sag. This short loads an arm at the tip, draws the moment, and shows why short and deep wins for every shelf and gantry overhang.",
            "hashtags": ["#Cantilever", "#Statics", "#Beams", "#Engineering"],
            "seo_keywords": [
                "how much can a cantilever hold",
                "cantilever beam",
                "cantilever bending moment",
                "tip deflection",
                "cantilever design",
                "length cubed deflection",
                "cantilever sag load",
            ],
        },
        "fact_check": [
            "A cantilever is fixed at one end.",
            "Tip loads are the worst case.",
            "The fixed end feels the bending moment.",
            "Deflection grows with length cubed.",
            "Short and deep beams sag least.",
        ],
    },
]