"""Batch 34: slicing speed, negative expansion, profiles, support-free design, hygroscopic filaments, nylon moisture, PETG vs ABS, HDT."""

CURATED = [
    # ======================================================================
    {
        "topic": "Slicing Speed vs Print Speed",
        "core_question": "Does your slicer really need to be fast?",
        "learning_objective": "The viewer understands the difference between slicing and print speed.",
        "engineering_summary": "Slicing speed is how fast the computer turns a model into g-code, and print speed is how fast the machine turns that g-code into plastic. They are completely separate clocks: a slow slicer takes minutes to plan but changes nothing about the print time, because the g-code is identical either way. Fast slicing matters when you iterate settings, because a quick reslice keeps you in the loop. The printer does not care how long the slicing took; the person waiting does.",
        "real_world_application": "Iterating profiles favors a fast slicer, not a fast print setting.",
        "common_misconceptions": [
            "Fast slicing prints faster (they are separate clocks)",
            "The slicer affects print speed (settings do, slicing time does not)",
            "Slow slicers are smarter (speed is tooling, not quality)",
        ],
        "teaching_strategy": "Show the same g-code produced by slow and fast slicing.",
        "script": "Slicing speed is how fast the computer turns a model into g-code, and print speed is how fast the machine turns that g-code into plastic. They are completely separate clocks: a slow slicer takes minutes to plan but changes nothing about the print time, because the g-code is identical either way. Fast slicing matters when you iterate settings, because a quick reslice keeps you in the loop. The printer does not care how long the slicing took; the person waiting does.",
        "text_overlay": [
            "TWO SEPARATE CLOCKS",
            "COMPUTER PLANS, MACHINE PRINTS",
            "SAME G-CODE EITHER WAY",
            "FAST SLICING KEEPS YOU ITERATING",
        ],
        "scenes": [
            {
                "goal": "Hook: the waiting bar",
                "teaching_point": "Slicing takes its own time",
                "shot": "medium shot of a computer showing a slicing progress bar",
                "motion": "progress bar crawls forward",
                "lighting": "screen glow light",
                "background": "work desk",
                "objects": ["computer", "progress bar", "model"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a computer showing a slicing progress bar, screen glow lighting, work desk",
            },
            {
                "goal": "The plan",
                "teaching_point": "Model becomes g-code",
                "shot": "diagram-style shot of a model turning into g-code lines",
                "motion": "model grid becomes path lines",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["model", "g-code paths", "layer lines"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a model becoming g-code, clean engineering visualization on a dark background",
            },
            {
                "goal": "The clocks",
                "teaching_point": "Plan time versus print time",
                "shot": "diagram-style shot of two clocks side by side",
                "motion": "slicing clock and print clock tick apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slicing clock", "print clock", "time bars"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of slicing and print clocks, clean engineering visualization on a dark background",
            },
            {
                "goal": "The iterate",
                "teaching_point": "Quick reslices keep the loop",
                "shot": "medium shot of a fast reslice finishing a new test",
                "motion": "settings change, slice completes fast",
                "lighting": "screen glow light",
                "background": "work desk",
                "objects": ["settings panel", "fast slice", "new g-code"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a fast slicer reslice completing, screen glow lighting, work desk",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The waiter cares",
                "shot": "wide hero shot of a printer printing from the finished g-code",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printing machine", "g-code file", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer printing from a g-code file, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two clocks: one for the computer, one for the machine",
            "subject": "slicing speed print speed",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two clocks side by side",
            "text": "TWO SEPARATE CLOCKS",
            "elements": ["slicing clock", "print clock", "g-code lines"],
            "style": "geometry studio photography",
            "mood": "planned, separated, iterated",
            "prompt": "photograph of two clocks side by side for slicing and print speed with g-code lines, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Slicing Speed vs Print Speed: Two Separate Clocks",
            "title_variations": [
                "Does Slicer Speed Matter",
                "Slicing Speed vs Print Speed",
                "Fast Slicing Explained",
                "Slicer Iteration Speed",
                "Slicing Time vs Print Time",
            ],
            "description": "Slicing speed is how fast the computer turns a model into g-code, and print speed is how fast the machine turns that g-code into plastic. They are completely separate clocks: a slow slicer takes minutes to plan but changes nothing about the print time, because the g-code is identical either way. Fast slicing matters when you iterate settings. This short runs both clocks and shows that the printer does not care how long slicing took, but the person waiting does.",
            "hashtags": ["#Slicing", "#PrintSpeed", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "does slicer speed matter",
                "slicing speed vs print speed",
                "fast slicing",
                "slicing time vs print time",
                "slicer iterate settings",
                "g-code generation time",
                "slow slicer print time",
            ],
        },
        "fact_check": [
            "Slicing plans the g-code.",
            "Printing executes the g-code.",
            "The clocks are separate.",
            "G-code is identical either way.",
            "Fast slicing helps iteration.",
        ],
    },
    {
        "topic": "Negative Expansion Offsets",
        "core_question": "Why do your holes always print a little too small?",
        "learning_objective": "The viewer understands negative expansion offsets.",
        "engineering_summary": "Printed holes come out smaller than designed because the nozzle rounds off corners and the walls sag inward: the hole eats a few tenths of a millimeter from the design. Negative expansion offsets (XY compensation) shift the part's outline inward or outward by a fixed amount, so a hole gets its designed size back by printing slightly larger. The offset is a global nudge that fixes the systematic error, not the filament-specific one. Holes are eaten, so the design grows them back.",
        "real_world_application": "Screw holes, bearing bores, and pins rely on a calibrated XY offset.",
        "common_misconceptions": [
            "Hole size is a model error (it is a printer-wide systematic bias)",
            "Scaling fixes holes (scaling changes everything, not just holes)",
            "Offset is cheating (it compensates for a real physical bias)",
        ],
        "teaching_strategy": "Measure a hole, then show the offset restoring the design size.",
        "script": "Printed holes come out smaller than designed because the nozzle rounds off corners and the walls sag inward: the hole eats a few tenths of a millimeter from the design. Negative expansion offsets (XY compensation) shift the part's outline inward or outward by a fixed amount, so a hole gets its designed size back by printing slightly larger. The offset is a global nudge that fixes the systematic error, not the filament-specific one. Holes are eaten, so the design grows them back.",
        "text_overlay": [
            "HOLES EAT TENTHS",
            "NOZZLE ROUNDS THE CORNERS",
            "XY COMPENSATION NUDGES THE OUTLINE",
            "GROW THEM BACK",
        ],
        "scenes": [
            {
                "goal": "Hook: the tight pin",
                "teaching_point": "Hole smaller than designed",
                "shot": "close-up shot of a pin refusing to enter a printed hole",
                "motion": "pin stops at the rim",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["pin", "printed hole", "tight fit"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a pin refusing to enter a printed hole, bright task lighting, workbench",
            },
            {
                "goal": "The eat",
                "teaching_point": "Corners round, walls sag",
                "shot": "diagram-style shot of a hole shrinking inward",
                "motion": "outline closes in on the hole",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["designed hole", "printed hole", "shrink arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a hole shrinking when printed, clean engineering visualization on a dark background",
            },
            {
                "goal": "The nudge",
                "teaching_point": "Outline shifted outward",
                "shot": "diagram-style shot of the offset outline",
                "motion": "offset line sits outside the design",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["design line", "offset line", "nudge arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of XY compensation offset, clean engineering visualization on a dark background",
            },
            {
                "goal": "The measure",
                "teaching_point": "Caliper checks the fix",
                "shot": "close-up shot of a caliper measuring the corrected hole",
                "motion": "jaws read the restored size",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper", "corrected hole", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a caliper measuring a corrected printed hole, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Grow the holes back",
                "shot": "wide hero shot of a pin sliding into a clean hole",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["sliding pin", "clean hole", "part"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a pin sliding into a clean printed hole, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hole shrinking inward with an offset outline restoring it",
            "subject": "negative expansion offsets",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "hole center, offset rings around",
            "text": "HOLES ARE EATEN, GROW THEM BACK",
            "elements": ["printed hole", "offset ring", "caliper"],
            "style": "geometry studio photography",
            "mood": "shrunk, nudged, restored",
            "prompt": "photograph of a printed hole with an offset outline ring, a caliper, and a tight pin, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Negative Expansion Offsets: Grow the Holes Back",
            "title_variations": [
                "How to Fix Holes Printing Too Small",
                "Negative Expansion Offset",
                "XY Compensation Guide",
                "Hole Compensation Slicer",
                "Size Accuracy Holes",
            ],
            "description": "Printed holes come out smaller than designed because the nozzle rounds off corners and the walls sag inward: the hole eats a few tenths of a millimeter. Negative expansion offsets (XY compensation) shift the part's outline inward or outward by a fixed amount, so a hole gets its designed size back by printing slightly larger. This short jams a pin, nudges the outline, and shows how holes are eaten, so the design grows them back.",
            "hashtags": ["#XYCompensation", "#HoleSize", "#SizeAccuracy", "#3DPrinting"],
            "seo_keywords": [
                "how to fix holes printing too small",
                "negative expansion offset",
                "xy compensation",
                "hole compensation slicer",
                "size accuracy holes",
                "hole shrink print",
                "screw hole too tight",
            ],
        },
        "fact_check": [
            "Holes print smaller than designed.",
            "The nozzle rounds the corners.",
            "XY compensation nudges the outline.",
            "The offset is a fixed shift.",
            "It fixes a systematic bias.",
        ],
    },
    {
        "topic": "Slicer Profiles: What Matters",
        "core_question": "Which profile settings actually matter?",
        "learning_objective": "The viewer understands what a slicer profile is and what matters in it.",
        "engineering_summary": "A slicer profile is a named bundle of every setting for a machine and material: temperatures, speeds, widths, and the start g-code. The numbers that matter are the machine-critical ones: temperatures, extrusion widths, and the start sequence, because getting them wrong can damage the printer or ruin the print. The rest, like infill patterns and seam placement, are taste. A good profile is a recipe tuned to one machine and one material, not a copy from the internet.",
        "real_world_application": "Profiles carry the calibrated truth of a specific printer.",
        "common_misconceptions": [
            "Internet profiles are optimal (they are guesses for other machines)",
            "All settings matter equally (temperatures and widths dominate)",
            "Profiles are one-time (materials and machines change)",
        ],
        "teaching_strategy": "Show a profile bundle, then rank the settings by importance.",
        "script": "A slicer profile is a named bundle of every setting for a machine and material: temperatures, speeds, widths, and the start g-code. The numbers that matter are the machine-critical ones: temperatures, extrusion widths, and the start sequence, because getting them wrong can damage the printer or ruin the print. The rest, like infill patterns and seam placement, are taste. A good profile is a recipe tuned to one machine and one material, not a copy from the internet.",
        "text_overlay": [
            "A NAMED BUNDLE OF SETTINGS",
            "MACHINE-CRITICAL NUMBERS",
            "TEMP, WIDTH, START G-CODE",
            "A RECIPE, NOT A COPY",
        ],
        "scenes": [
            {
                "goal": "Hook: the profile list",
                "teaching_point": "Many profiles, one truth",
                "shot": "medium shot of a slicer profile list on screen",
                "motion": "profile names scroll past",
                "lighting": "screen glow light",
                "background": "work desk",
                "objects": ["profile list", "names", "screen"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a slicer profile list on screen, screen glow lighting, work desk",
            },
            {
                "goal": "The bundle",
                "teaching_point": "Every setting in one place",
                "shot": "diagram-style shot of a profile card with settings",
                "motion": "temp, speed, width tiles fill the card",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["profile card", "setting tiles", "machine name"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a slicer profile bundle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The criticals",
                "teaching_point": "Temp, width, start g-code",
                "shot": "diagram-style shot of critical settings highlighted",
                "motion": "three tiles light up above the rest",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temperature tile", "width tile", "start g-code tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of critical slicer profile settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "The taste",
                "teaching_point": "Infill and seam are taste",
                "shot": "diagram-style shot of taste settings dimmed",
                "motion": "infill and seam tiles fade down",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["infill tile", "seam tile", "dimmed row"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of non-critical slicer settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Tune to your machine",
                "shot": "wide hero shot of a printer beside its profile card",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "profile card", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer beside its profile card, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A profile card with critical settings glowing above taste settings",
            "subject": "slicer profiles",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "card center, tiles glowing",
            "text": "A RECIPE, NOT A COPY",
            "elements": ["profile card", "critical tiles", "printer"],
            "style": "geometry studio photography",
            "mood": "bundled, ranked, tuned",
            "prompt": "photograph of a slicer profile card with critical settings glowing above taste settings and a printer, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Slicer Profiles: A Recipe, Not a Copy",
            "title_variations": [
                "Which Slicer Profile Should I Use",
                "Slicer Profile Settings",
                "Machine Profile Guide",
                "Print Profile Essentials",
                "Profile Settings That Matter",
            ],
            "description": "A slicer profile is a named bundle of every setting for a machine and material: temperatures, speeds, widths, and the start g-code. The numbers that matter are the machine-critical ones: temperatures, extrusion widths, and the start sequence, because getting them wrong can damage the printer or ruin the print. The rest, like infill patterns and seam placement, are taste. This short opens the bundle, ranks the settings, and shows why a good profile is a recipe tuned to one machine.",
            "hashtags": ["#SlicerProfiles", "#Slicer", "#Settings", "#3DPrinting"],
            "seo_keywords": [
                "which slicer profile should I use",
                "slicer profile settings",
                "machine profile",
                "print profile essentials",
                "profile settings matter",
                "temperature extrusion width profile",
                "start g-code profile",
            ],
        },
        "fact_check": [
            "A profile bundles all settings.",
            "Temperatures are critical.",
            "Extrusion widths are critical.",
            "Start g-code is critical.",
            "Infill and seam are taste.",
        ],
    },
    {
        "topic": "Supports-Free Design",
        "core_question": "What if the part designed itself to need no supports?",
        "learning_objective": "The viewer understands support-free design principles.",
        "engineering_summary": "Designing without supports means every overhang stays within the printer's self-supporting angle, usually about forty-five degrees or less from vertical. The moves are the designer's: split the part so nothing hangs, add chamfers and fillets to soften steps, stand holes and pockets vertically, and orient the strong direction along the layers. Every feature is a geometry question: can the printer reach it, and can it print it without a crutch? Support-free design is not a setting; it is a set of choices.",
        "real_world_application": "Print-in-place and production parts go support-free to save time and cleanup.",
        "common_misconceptions": [
            "Supports are a slicer problem (the geometry invites them)",
            "Forty-five degrees is a hard law (it is a starting rule of thumb)",
            "Support-free parts are weaker (orientation, not support, sets strength)",
        ],
        "teaching_strategy": "Show a part with supports, then the redesigned support-free version.",
        "script": "Designing without supports means every overhang stays within the printer's self-supporting angle, usually about forty-five degrees or less from vertical. The moves are the designer's: split the part so nothing hangs, add chamfers and fillets to soften steps, stand holes and pockets vertically, and orient the strong direction along the layers. Every feature is a geometry question: can the printer reach it, and can it print it without a crutch? Support-free design is not a setting; it is a set of choices.",
        "text_overlay": [
            "UNDER FORTY-FIVE DEGREES",
            "SPLIT, CHAMFER, STAND, ORIENT",
            "EVERY FEATURE IS A GEOMETRY QUESTION",
            "A SET OF CHOICES",
        ],
        "scenes": [
            {
                "goal": "Hook: the support forest",
                "teaching_point": "Geometry invites crutches",
                "shot": "wide shot of a part under a forest of supports",
                "motion": "camera pans the support towers",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["support forest", "overhang part", "towers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part under a forest of supports, neutral lab lighting, print lab",
            },
            {
                "goal": "The angle",
                "teaching_point": "Self-supporting overhangs",
                "shot": "diagram-style shot of the forty-five degree cone",
                "motion": "angle cone opens under the overhang",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["angle cone", "overhang edge", "safe zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the self-supporting angle cone, clean engineering visualization on a dark background",
            },
            {
                "goal": "The moves",
                "teaching_point": "Split, chamfer, stand, orient",
                "shot": "diagram-style shot of redesign moves on a part",
                "motion": "part splits and features soften",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["split line", "chamfer edge", "vertical hole"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of support-free redesign moves, clean engineering visualization on a dark background",
            },
            {
                "goal": "The result",
                "teaching_point": "Same part, no crutch",
                "shot": "medium shot of the redesigned part printing bare",
                "motion": "part builds with no supports",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["bare part", "no supports", "clean bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a redesigned part printing without supports, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Choices, not settings",
                "shot": "wide hero shot of the finished support-free part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished part", "clean surfaces", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished support-free part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part redesigned under a forty-five degree cone with no supports",
            "subject": "support-free design",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, cone around",
            "text": "A SET OF CHOICES",
            "elements": ["angle cone", "chamfer edge", "vertical hole"],
            "style": "geometry studio photography",
            "mood": "redesigned, angled, bare",
            "prompt": "photograph of a redesigned part under a forty-five degree cone printing without supports and with chamfered edges, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Supports-Free Design: A Set of Choices",
            "title_variations": [
                "How to Design Without Supports",
                "Support Free Design",
                "Self Supporting Overhangs",
                "Design No Supports Print",
                "Overhang Angle Design",
            ],
            "description": "Designing without supports means every overhang stays within the printer's self-supporting angle, usually about forty-five degrees or less from vertical. The moves are the designer's: split the part so nothing hangs, add chamfers and fillets to soften steps, stand holes and pockets vertically, and orient the strong direction along the layers. This short shows the same part under a support forest and redesigned bare, and proves support-free design is a set of choices, not a setting.",
            "hashtags": ["#SupportFree", "#Design", "#Overhang", "#3DPrinting"],
            "seo_keywords": [
                "how to design without supports",
                "support free design",
                "self supporting overhangs",
                "design no supports",
                "overhang angle design",
                "45 degree overhang",
                "print in place design",
            ],
        },
        "fact_check": [
            "Overhangs under forty-five degrees work.",
            "Splitting removes hanging parts.",
            "Chamfers soften overhang steps.",
            "Holes and pockets stand vertical.",
            "Orientation sets the strong direction.",
        ],
    },
    {
        "topic": "Hygroscopic Filaments",
        "core_question": "Why does your filament hiss and pop?",
        "learning_objective": "The viewer understands hygroscopic filaments and moisture.",
        "engineering_summary": "Hygroscopic filaments absorb water from the air, and the water turns to steam inside the hot nozzle: it hisses, pops, and spits bubbles that wreck the surface and weaken the walls. The usual suspects are Nylon, PETG, and TPU, which soak up water fast, while PLA is slower but still drinks over time. The symptoms are a dull, bubbly surface and brittle, snapping filament. The fix is heat: dry the filament at its spec temperature, then store it sealed with desiccant. Dry filament is a material choice and a storage habit.",
        "real_world_application": "Moisture management decides quality between dry and humid seasons.",
        "common_misconceptions": [
            "Moisture is a printing myth (the hiss and bubbles are real)",
            "All filaments absorb equally (Nylon and PETG are thirsty)",
            "A dry box fixes wet filament (drying needs heat, storage needs sealing)",
        ],
        "teaching_strategy": "Show the hiss and bubbles, then the drying and storage cycle.",
        "script": "Hygroscopic filaments absorb water from the air, and the water turns to steam inside the hot nozzle: it hisses, pops, and spits bubbles that wreck the surface and weaken the walls. The usual suspects are Nylon, PETG, and TPU, which soak up water fast, while PLA is slower but still drinks over time. The symptoms are a dull, bubbly surface and brittle, snapping filament. The fix is heat: dry the filament at its spec temperature, then store it sealed with desiccant. Dry filament is a material choice and a storage habit.",
        "text_overlay": [
            "WATER BECOMES STEAM",
            "NYLON, PETG, TPU DRINK FAST",
            "DULL AND BUBBLY SURFACE",
            "DRY WITH HEAT, STORE SEALED",
        ],
        "scenes": [
            {
                "goal": "Hook: the hiss",
                "teaching_point": "Steam in the nozzle",
                "shot": "close-up shot of a nozzle hissing with popping bubbles",
                "motion": "steam puffs and spits from the tip",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["hissing nozzle", "steam puffs", "bubbles"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a nozzle hissing with popping bubbles, bright task light, print lab",
            },
            {
                "goal": "The drink",
                "teaching_point": "Filaments absorb water",
                "shot": "diagram-style shot of moisture entering a filament roll",
                "motion": "water arrows soak into the spool",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["filament roll", "water arrows", "moisture front"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of moisture entering a filament roll, clean engineering visualization on a dark background",
            },
            {
                "goal": "The damage",
                "teaching_point": "Bubbles and dull walls",
                "shot": "close-up shot of a bubbly dull print surface",
                "motion": "light rakes the bubble craters",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["bubble craters", "dull surface", "print wall"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bubbly dull print surface, bright task lighting, print lab",
            },
            {
                "goal": "The dry",
                "teaching_point": "Heat drives the water out",
                "shot": "diagram-style shot of a filament dryer with temperature",
                "motion": "heat arrows pull moisture out",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dryer box", "heat arrows", "spec temp"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a filament dryer, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Seal after drying",
                "shot": "wide hero shot of filament stored with desiccant",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["sealed bags", "desiccant", "dry rolls"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of filament sealed with desiccant, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hissing nozzle over a filament roll with moisture arrows and a dryer",
            "subject": "hygroscopic filaments",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "nozzle center, dryer beside",
            "text": "DRY WITH HEAT, STORE SEALED",
            "elements": ["hissing nozzle", "filament roll", "dryer box"],
            "style": "geometry studio photography",
            "mood": "wet, hissing, dried",
            "prompt": "photograph of a hissing nozzle above a filament roll with a dryer box beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Hygroscopic Filaments: Dry With Heat, Store Sealed",
            "title_variations": [
                "Which Filaments Absorb Water",
                "Hygroscopic Filament Guide",
                "Wet Filament Symptoms",
                "Filament Moisture Fix",
                "Dry Filament Storage",
            ],
            "description": "Hygroscopic filaments absorb water from the air, and the water turns to steam inside the hot nozzle: it hisses, pops, and spits bubbles that wreck the surface and weaken the walls. Nylon, PETG, and TPU soak up water fast, while PLA is slower but still drinks over time. The symptoms are a dull, bubbly surface and brittle filament. This short catches the hiss, drives the water out with heat, and seals the spool: dry with heat, store sealed.",
            "hashtags": ["#Hygroscopic", "#FilamentDrying", "#Moisture", "#3DPrinting"],
            "seo_keywords": [
                "which filaments absorb water",
                "hygroscopic filament",
                "wet filament symptoms",
                "filament moisture fix",
                "dry filament storage",
                "nylon PETG moisture",
                "filament hiss pop",
            ],
        },
        "fact_check": [
            "Water becomes steam in the nozzle.",
            "Nylon, PETG, and TPU absorb fast.",
            "Bubbles ruin the surface.",
            "Heat drives the water out.",
            "Sealed storage keeps it dry.",
        ],
    },
    {
        "topic": "Moisture & Nylon",
        "core_question": "Why is nylon the thirstiest filament in the room?",
        "learning_objective": "The viewer understands why nylon absorbs water and how to manage it.",
        "engineering_summary": "Nylon is built to drink: its chemical structure grabs water molecules from the air, and a roll can gain a noticeable percentage of its weight in moisture within a day or two. Inside the hot nozzle that water flashes to steam, so wet nylon prints with bubbles, stringing, and layer delamination, and it can even hydrolyze, breaking the polymer chains themselves. The routine is religious: dry nylon before every long print, print from a dry box, and seal it the moment it comes off the machine.",
        "real_world_application": "Nylon parts fail from moisture long before they fail from load.",
        "common_misconceptions": [
            "A day of exposure is fine (nylon drinks within hours)",
            "Drying once is enough (it reabsorbs quickly after)",
            "Bubbles are a temperature issue (they are steam from water)",
        ],
        "teaching_strategy": "Show the water gain curve, then the steam damage, then the dry routine.",
        "script": "Nylon is built to drink: its chemical structure grabs water molecules from the air, and a roll can gain a noticeable percentage of its weight in moisture within a day or two. Inside the hot nozzle that water flashes to steam, so wet nylon prints with bubbles, stringing, and layer delamination, and it can even hydrolyze, breaking the polymer chains themselves. The routine is religious: dry nylon before every long print, print from a dry box, and seal it the moment it comes off the machine.",
        "text_overlay": [
            "NYLON GRABS WATER BY DESIGN",
            "STEAM, BUBBLES, DELAMINATION",
            "HYDROLYSIS BREAKS THE CHAINS",
            "DRY, PRINT FROM THE BOX, SEAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the weight gain",
                "teaching_point": "Nylon drinks by weight",
                "shot": "close-up shot of a scale showing a nylon roll gaining weight",
                "motion": "weight ticks upward",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["scale", "nylon roll", "weight readout"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a scale showing a nylon roll gaining weight, bright task lighting, workbench",
            },
            {
                "goal": "The grab",
                "teaching_point": "Chemistry pulls the water",
                "shot": "diagram-style shot of water molecules bonding to nylon chains",
                "motion": "water dots latch onto the chains",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["polymer chains", "water molecules", "bonds"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of water bonding to nylon chains, clean engineering visualization on a dark background",
            },
            {
                "goal": "The steam",
                "teaching_point": "Flash to bubbles",
                "shot": "close-up shot of a wet nylon print with bubbles",
                "motion": "steam pockets burst in the walls",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["steam pockets", "bubble walls", "print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a wet nylon print with steam bubbles, bright task lighting, print lab",
            },
            {
                "goal": "The routine",
                "teaching_point": "Dry, box, seal",
                "shot": "medium shot of a dry box feeding a printer",
                "motion": "filament feeds from the sealed box",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["dry box", "feed tube", "printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a dry box feeding a printer, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Religious routine",
                "shot": "wide hero shot of clean nylon parts beside sealed rolls",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean nylon parts", "sealed rolls", "desiccant"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of clean nylon parts beside sealed rolls, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Water molecules latching onto nylon chains with a dry box",
            "subject": "moisture and nylon",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "chains center, dry box beside",
            "text": "DRY, PRINT FROM THE BOX, SEAL",
            "elements": ["nylon chains", "water molecules", "dry box"],
            "style": "geometry studio photography",
            "mood": "thirsty, steamed, sealed",
            "prompt": "photograph of water molecules latching onto nylon chains with a dry box and a bubble print beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Moisture & Nylon: The Thirstiest Filament",
            "title_variations": [
                "Why Does Nylon Absorb Water",
                "Wet Nylon Printing",
                "Drying Nylon Filament",
                "Nylon Moisture Guide",
                "Hygroscopic Nylon Fix",
            ],
            "description": "Nylon is built to drink: its chemical structure grabs water molecules from the air, and a roll can gain a noticeable percentage of its weight in moisture within a day or two. In the hot nozzle that water flashes to steam, so wet nylon prints with bubbles, stringing, and delamination, and it can even hydrolyze, breaking the polymer chains. This short weighs the drink, flashes the steam, and shows the religious routine: dry, print from the box, seal.",
            "hashtags": ["#Nylon", "#Moisture", "#Drying", "#3DPrinting"],
            "seo_keywords": [
                "why does nylon absorb water",
                "wet nylon printing",
                "drying nylon filament",
                "nylon moisture",
                "hygroscopic nylon",
                "nylon hydrolysis",
                "nylon dry box",
            ],
        },
        "fact_check": [
            "Nylon absorbs water fast.",
            "Water flashes to steam in the nozzle.",
            "Wet nylon prints with bubbles.",
            "Hydrolysis can break the chains.",
            "Dry and seal nylon always.",
        ],
    },
    {
        "topic": "PETG vs ABS",
        "core_question": "Which tough filament should you actually print?",
        "learning_objective": "The viewer understands the PETG versus ABS trade-off.",
        "engineering_summary": "PETG and ABS both promise toughness, but they earn it differently. ABS is strong, heat-resistant, and smooth with acetone, yet it needs an enclosure, warps, and stinks. PETG is easier: it prints without a chamber, sticks well, and resists impact and moisture better, but it strings, sags, and softens at lower heat. The choice is a temperature test: parts that sit in a hot car need ABS; parts that just need to survive a drop can run PETG. Tough is not one material; it is the right trade.",
        "real_world_application": "Automotive and functional parts pick between the two by heat and ease.",
        "common_misconceptions": [
            "ABS is always stronger (PETG wins in impact and ease)",
            "PETG is waterproof enough everywhere (it still absorbs slowly)",
            "They print the same (ABS wants heat, PETG wants dry air)",
        ],
        "teaching_strategy": "Show the same part in both materials failing at different tests.",
        "script": "PETG and ABS both promise toughness, but they earn it differently. ABS is strong, heat-resistant, and smooth with acetone, yet it needs an enclosure, warps, and stinks. PETG is easier: it prints without a chamber, sticks well, and resists impact and moisture better, but it strings, sags, and softens at lower heat. The choice is a temperature test: parts that sit in a hot car need ABS; parts that just need to survive a drop can run PETG. Tough is not one material; it is the right trade.",
        "text_overlay": [
            "ABS: HEAT AND WARPS",
            "PETG: EASY, IMPACT, STRINGS",
            "HOT CAR NEEDS ABS",
            "TOUGH IS THE RIGHT TRADE",
        ],
        "scenes": [
            {
                "goal": "Hook: two spools",
                "teaching_point": "Two tough promises",
                "shot": "wide shot of PETG and ABS spools side by side",
                "motion": "camera pans between the spools",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["PETG spool", "ABS spool", "labels"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of PETG and ABS spools side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "The ABS case",
                "teaching_point": "Heat-resistant, needs a chamber",
                "shot": "diagram-style shot of ABS traits and its enclosure",
                "motion": "heat arrow up, chamber wraps around",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heat arrow", "enclosure", "ABS part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of ABS heat resistance and enclosure, clean engineering visualization on a dark background",
            },
            {
                "goal": "The PETG case",
                "teaching_point": "Easy, impact, strings",
                "shot": "diagram-style shot of PETG traits and its strings",
                "motion": "impact arrow, strings trail behind",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["impact arrow", "stringing", "PETG part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of PETG impact and stringing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The test",
                "teaching_point": "Heat and drop tests",
                "shot": "medium shot of both parts in a heat test and a drop",
                "motion": "hot plate and drop rig test the parts",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["heat test", "drop rig", "both parts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of PETG and ABS parts in heat and drop tests, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick the right trade",
                "shot": "wide hero shot of the winning parts per test",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["ABS part", "PETG part", "test results"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of PETG and ABS parts with test results, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two spools feeding a heat test and a drop test",
            "subject": "PETG vs ABS",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two spools center, tests below",
            "text": "TOUGH IS THE RIGHT TRADE",
            "elements": ["PETG spool", "ABS spool", "test rigs"],
            "style": "geometry studio photography",
            "mood": "traded, tested, chosen",
            "prompt": "photograph of PETG and ABS spools feeding a heat test and a drop test, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PETG vs ABS: Tough Is the Right Trade",
            "title_variations": [
                "PETG or ABS Which Is Better",
                "PETG vs ABS Comparison",
                "ABS or PETG for Parts",
                "PETG vs ABS Strength",
                "Strong Filament Choice",
            ],
            "description": "PETG and ABS both promise toughness, but they earn it differently. ABS is strong, heat-resistant, and smooth with acetone, yet it needs an enclosure, warps, and stinks. PETG is easier: it prints without a chamber, sticks well, and resists impact and moisture better, but it strings, sags, and softens at lower heat. The choice is a temperature test: hot cars want ABS, hard drops want PETG. This short runs both tests and shows that tough is the right trade.",
            "hashtags": ["#PETG", "#ABS", "#MaterialChoice", "#3DPrinting"],
            "seo_keywords": [
                "PETG or ABS which is better",
                "PETG vs ABS comparison",
                "ABS or PETG for parts",
                "PETG vs ABS strength",
                "strong filament choice",
                "PETG stringing ABS warping",
                "hot car part ABS PETG",
            ],
        },
        "fact_check": [
            "ABS resists heat well.",
            "ABS needs an enclosure.",
            "PETG prints more easily.",
            "PETG wins in impact.",
            "The choice is a temperature test.",
        ],
    },
    {
        "topic": "Heat Deflection Temperature",
        "core_question": "At what temperature does your part start to droop?",
        "learning_objective": "The viewer understands heat deflection temperature.",
        "engineering_summary": "Heat deflection temperature (HDT) is the temperature at which a loaded test bar sags a set distance under a fixed bending load, and it tells you when a printed part stops holding its shape. It is measured under stress, so it sits well below the melting point: PLA can soften below sixty degrees, while ABS and nylon hold on longer, and the printed layer structure lowers HDT further. The rule of thumb is to keep parts a safe margin below their HDT. A material's melt point is when it flows; its HDT is when it fails.",
        "real_world_application": "Parts near engines, hot cars, and heated enclosures need HDT margins.",
        "common_misconceptions": [
            "Melting point sets the limit (parts sag far below it)",
            "HDT is the same as glass transition (it is a loaded test, not a transition)",
            "Printing does not change HDT (layer bonds lower it)",
        ],
        "teaching_strategy": "Show the loaded bar test and the sagging failure.",
        "script": "Heat deflection temperature (HDT) is the temperature at which a loaded test bar sags a set distance under a fixed bending load, and it tells you when a printed part stops holding its shape. It is measured under stress, so it sits well below the melting point: PLA can soften below sixty degrees, while ABS and nylon hold on longer, and the printed layer structure lowers HDT further. The rule of thumb is to keep parts a safe margin below their HDT. A material's melt point is when it flows; its HDT is when it fails.",
        "text_overlay": [
            "LOADED BAR, SET SAG",
            "FAR BELOW THE MELT POINT",
            "LAYERS LOWER HDT",
            "MELT POINT FLOWS, HDT FAILS",
        ],
        "scenes": [
            {
                "goal": "Hook: the drooping shelf",
                "teaching_point": "Part sags under heat",
                "shot": "close-up shot of a sagging printed bracket in warm air",
                "motion": "bracket slowly droops",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["sagging bracket", "warm air", "droop"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a sagging printed bracket in warm air, bright task light, print lab",
            },
            {
                "goal": "The test",
                "teaching_point": "Loaded bar in a bath",
                "shot": "diagram-style shot of the HDT test rig",
                "motion": "bar sags under the load as heat rises",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["test bar", "bending load", "heat bath"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the HDT test rig, clean engineering visualization on a dark background",
            },
            {
                "goal": "The numbers",
                "teaching_point": "PLA soft, ABS and nylon higher",
                "shot": "graphic-style shot of HDT bars per material",
                "motion": "bars rank from PLA to nylon",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["PLA bar", "ABS bar", "nylon bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of HDT values per material, clean engineering visualization on a dark background",
            },
            {
                "goal": "The layers",
                "teaching_point": "Printed parts sit lower",
                "shot": "diagram-style shot of a printed bar versus solid bar",
                "motion": "layer bonds weaken the printed bar",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["printed bar", "solid bar", "bond lines"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of printed versus solid HDT, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Keep the margin",
                "shot": "wide hero shot of a part working safely near heat",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["working part", "heat source", "safe margin"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part working safely near a heat source, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A loaded bar sagging in a heat bath with material HDT bars",
            "subject": "heat deflection temperature",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "test rig center, HDT bars beside",
            "text": "MELT POINT FLOWS, HDT FAILS",
            "elements": ["test bar", "heat bath", "HDT bars"],
            "style": "geometry studio photography",
            "mood": "loaded, sagging, margined",
            "prompt": "photograph of a loaded test bar sagging in a heat bath with HDT bars beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heat Deflection Temperature: Melt Point Flows, HDT Fails",
            "title_variations": [
                "What Is HDT in Materials",
                "Heat Deflection Temperature",
                "HDT vs Melting Point",
                "Heat Resistance Testing",
                "High Temp Print Use",
            ],
            "description": "Heat deflection temperature (HDT) is the temperature at which a loaded test bar sags a set distance under a fixed bending load, and it tells you when a printed part stops holding its shape. It sits well below the melting point: PLA can soften below sixty degrees, while ABS and nylon hold on longer, and printed layer structure lowers HDT further. This short loads the bar, ranks the materials, and shows that a material's melt point is when it flows, but its HDT is when it fails.",
            "hashtags": ["#HDT", "#HeatDeflection", "#Materials", "#3DPrinting"],
            "seo_keywords": [
                "what is HDT in materials",
                "heat deflection temperature",
                "HDT vs melting point",
                "heat resistance testing",
                "high temp print use",
                "PLA HDT soft",
                "printed part heat sag",
            ],
        },
        "fact_check": [
            "HDT is a loaded test.",
            "It sits below the melt point.",
            "PLA softens below sixty degrees.",
            "Printed layers lower HDT.",
            "Keep a safe margin below it.",
        ],
    },
]