"""Batch 48: izod versus charpy impact, filament reel issues, XY gantry deflection, PSU and wiring safety, closed-loop control, resonance and vertical fine artifacts, stepper motor mounts, Young's modulus for printers."""

CURATED = [
    # ======================================================================
    {
        "topic": "Izod vs Charpy Impact",
        "core_question": "Izod vs Charpy impact test?",
        "learning_objective": "The viewer understands Izod versus Charpy impact.",
        "engineering_summary": "Impact tests break plastic on purpose: a swinging pendulum slams a notched sample, and the energy the sample absorbs tells how tough the material is. The two classics differ in setup: the Charpy test holds the sample at both ends and hits it in the middle, while the Izod test clamps it at one end and swings at the free tip, and the notch faces the hammer either way. The numbers only compare like for like, so an Izod score never translates to a Charpy score directly. Toughness is measured by what a break takes.",
        "real_world_application": "Datasheets quote Izod or Charpy numbers for impact strength.",
        "common_misconceptions": [
            "Izod and Charpy scores match (they cannot be compared directly)",
            "A notch weakens the test (the notch is the point)",
            "Higher energy means stronger (it means tougher)",
        ],
        "teaching_strategy": "Show the two setups, then the broken samples.",
        "script": "Impact tests break plastic on purpose: a swinging pendulum slams a notched sample, and the energy the sample absorbs tells how tough the material is. The two classics differ in setup: the Charpy test holds the sample at both ends and hits it in the middle, while the Izod test clamps it at one end and swings at the free tip, and the notch faces the hammer either way. The numbers only compare like for like, so an Izod score never translates to a Charpy score directly. Toughness is measured by what a break takes.",
        "text_overlay": [
            "BREAK IT ON PURPOSE",
            "CHARPY: HELD BOTH ENDS",
            "IZOD: CLAMPED AT ONE",
            "SCORES DO NOT CONVERT",
        ],
        "scenes": [
            {
                "goal": "Hook: the pendulum",
                "teaching_point": "Swing, slam, measure",
                "shot": "close-up shot of a pendulum tester",
                "motion": "camera pans the swinging arm",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["pendulum arm", "impact tester", "notched sample"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a pendulum impact tester, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The Charpy",
                "teaching_point": "Held at both ends",
                "shot": "diagram-style shot of the Charpy setup",
                "motion": "hammer hits the middle of the sample",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["Charpy anvils", "center hit", "both-end hold"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the Charpy impact setup, clean engineering visualization on a dark background",
            },
            {
                "goal": "The Izod",
                "teaching_point": "Clamped at one end",
                "shot": "diagram-style shot of the Izod setup",
                "motion": "hammer swings at the free tip",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["Izod clamp", "free tip", "swing path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the Izod impact setup, clean engineering visualization on a dark background",
            },
            {
                "goal": "The numbers",
                "teaching_point": "Compare like for like",
                "shot": "diagram-style shot of the score sheets",
                "motion": "Izod and Charpy columns split",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["Izod column", "Charpy column", "score sheets"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Izod versus Charpy scores, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Energy tells toughness",
                "shot": "wide hero shot of broken samples",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["broken samples", "notched breaks", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of broken impact test samples, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A pendulum tester with one clamped sample and one held at both ends",
            "subject": "izod versus charpy impact",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pendulum left, samples right",
            "text": "SCORES DO NOT CONVERT",
            "elements": ["pendulum arm", "notched sample", "sample clamps"],
            "style": "geometry studio photography",
            "mood": "swung, slammed, measured",
            "prompt": "photograph of a pendulum impact tester with a notched sample clamped at one end beside a sample held at both ends, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Izod vs Charpy Impact: Scores Do Not Convert",
            "title_variations": [
                "Izod vs Charpy Test",
                "Impact Strength Explained",
                "Notch Impact Testing",
                "Pendulum Impact Test",
                "Plastic Toughness Tests",
            ],
            "description": "Impact tests break plastic on purpose: a swinging pendulum slams a notched sample, and the energy the sample absorbs tells how tough the material is. The two classics differ in setup: the Charpy test holds the sample at both ends and hits it in the middle, while the Izod test clamps it at one end and swings at the free tip, and the notch faces the hammer either way. The numbers only compare like for like, so an Izod score never translates to a Charpy score directly. This short swings the hammer, breaks the samples, and reads the energy. Toughness is measured by what a break takes.",
            "hashtags": ["#ImpactTesting", "#Izod", "#Charpy", "#MaterialScience"],
            "seo_keywords": [
                "izod vs charpy impact test",
                "izod",
                "charpy",
                "impact strength",
                "notch test",
                "izod vs charpy difference",
                "pendulum impact test",
            ],
        },
        "fact_check": [
            "Pendulums break samples.",
            "Energy reads toughness.",
            "Charpy holds both ends.",
            "Izod clamps one end.",
            "Scores do not convert.",
        ],
    },
    {
        "topic": "Filament Reel Issues",
        "core_question": "Why does filament tangle?",
        "learning_objective": "The viewer understands filament reel issues.",
        "engineering_summary": "Most filament tangles are made at the factory, not on the printer: when the spool winds loose or crosses over, the loop rides under a strand, and the knot only bites after fifty meters of smooth printing. The tangle announces itself: the extruder starts clicking and the print underextrudes, because the stuck strand stretches instead of feeding. The rules are loose ends, crossed loops, and straight pulls: never let the end snap free, keep the spool from turning backward, and pull straight up. A tangled spool is a knot waiting for a print.",
        "real_world_application": "A snagged spool mid-print is the classic overnight failure.",
        "common_misconceptions": [
            "The printer ties the knot (the spool wound it at the factory)",
            "Yanking the filament fixes it (it tightens the knot)",
            "Tangles show immediately (they bite after meters)",
        ],
        "teaching_strategy": "Show the crossed loop, then the clicking extruder.",
        "script": "Most filament tangles are made at the factory, not on the printer: when the spool winds loose or crosses over, the loop rides under a strand, and the knot only bites after fifty meters of smooth printing. The tangle announces itself: the extruder starts clicking and the print underextrudes, because the stuck strand stretches instead of feeding. The rules are loose ends, crossed loops, and straight pulls: never let the end snap free, keep the spool from turning backward, and pull straight up. A tangled spool is a knot waiting for a print.",
        "text_overlay": [
            "MADE AT THE FACTORY",
            "THE KNOT WAITS FOR METERS",
            "CLICKING MEANS STRETCH",
            "NEVER LET THE END SNAP FREE",
        ],
        "scenes": [
            {
                "goal": "Hook: the spool",
                "teaching_point": "It looks fine, until it bites",
                "shot": "close-up shot of a filament spool",
                "motion": "camera pans the crossed loop",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["filament spool", "crossed loop", "loose wind"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a filament spool with a crossed loop, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The knot",
                "teaching_point": "A loop rides under a strand",
                "shot": "diagram-style shot of the loop trap",
                "motion": "loop slides under the strand and locks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["loop trap", "under strand", "locked knot"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a filament knot forming, clean engineering visualization on a dark background",
            },
            {
                "goal": "The signal",
                "teaching_point": "Clicking and underextrusion",
                "shot": "diagram-style shot of the clicking extruder",
                "motion": "gear slips while the strand stretches",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extruder gear", "stretched strand", "skipped teeth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an extruder clicking on a tangle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Straight pulls prevent knots",
                "shot": "diagram-style shot of the spool feed",
                "motion": "straight pull keeps the loop open",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["straight pull", "open loop", "spool hub"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of correct spool feeding, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Check the spool first",
                "shot": "wide hero shot of a clean spool setup",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean spool", "straight feed", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tidy filament spool feeding straight, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A tangled spool with a crossed loop and a clicking extruder",
            "subject": "filament reel issues",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spool left, extruder right",
            "text": "THE KNOT WAITS FOR METERS",
            "elements": ["filament spool", "crossed loop", "clicking extruder"],
            "style": "geometry studio photography",
            "mood": "wound, knotted, stretched",
            "prompt": "photograph of a tangled filament spool with a crossed loop under a strand and an extruder clicking beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Filament Reel Issues: The Knot Waits for Meters",
            "title_variations": [
                "Why Does Filament Tangle",
                "Fix Filament Tangles",
                "Spool Knot Prevention",
                "Filament Tangle Mid Print",
                "Spool Winding Problems",
            ],
            "description": "Most filament tangles are made at the factory, not on the printer: when the spool winds loose or crosses over, the loop rides under a strand, and the knot only bites after fifty meters of smooth printing. The tangle announces itself: the extruder starts clicking and the print underextrudes, because the stuck strand stretches instead of feeding. The rules are loose ends, crossed loops, and straight pulls: never let the end snap free, keep the spool from turning backward, and pull straight up. This short finds the loop, reads the click, and saves the print. A tangled spool is a knot waiting for a print.",
            "hashtags": ["#Filament", "#3DPrinting", "#SpoolTangle", "#PrintFails"],
            "seo_keywords": [
                "why does filament tangle",
                "filament tangles",
                "reel issues",
                "filament knot",
                "spool tangling",
                "filament tangle mid print",
                "prevent filament tangles",
            ],
        },
        "fact_check": [
            "Tangles start at the factory.",
            "The knot bites after meters.",
            "Clicking means stretching.",
            "Straight pulls prevent knots.",
            "Never let the end snap free.",
        ],
    },
    {
        "topic": "XY Gantry Deflection",
        "core_question": "What is gantry deflection?",
        "learning_objective": "The viewer understands XY gantry deflection.",
        "engineering_summary": "Every gantry flexes a little: the toolhead rides on rails across a bridge, and the bridge bends under its own weight and the print's forces, so the nozzle drops a fraction of a millimeter off the planned path. Deflection hides in the print: the top layers shift, the walls lean, and fast printing makes the flex worse, because acceleration shoves the whole carriage. The fixes are mechanical: a stiffer bridge, twin rails, and a shorter span all cut the sag, and speed is limited by stiffness. The machine bends before the plastic does.",
        "real_world_application": "Large prints show gantry sag as leaning walls and shifted tops.",
        "common_misconceptions": [
            "Metal bridges never bend (every bridge flexes a little)",
            "Speed is free (acceleration feeds the deflection)",
            "The nozzle is the cause (the bridge sags under load)",
        ],
        "teaching_strategy": "Show the bowing bridge, then the stiffening fixes.",
        "script": "Every gantry flexes a little: the toolhead rides on rails across a bridge, and the bridge bends under its own weight and the print's forces, so the nozzle drops a fraction of a millimeter off the planned path. Deflection hides in the print: the top layers shift, the walls lean, and fast printing makes the flex worse, because acceleration shoves the whole carriage. The fixes are mechanical: a stiffer bridge, twin rails, and a shorter span all cut the sag, and speed is limited by stiffness. The machine bends before the plastic does.",
        "text_overlay": [
            "EVERY BRIDGE FLEXES",
            "SAG HIDES IN THE WALLS",
            "SPEED FEEDS THE FLEX",
            "STIFFNESS LIMITS SPEED",
        ],
        "scenes": [
            {
                "goal": "Hook: the long bridge",
                "teaching_point": "It bows in the middle",
                "shot": "wide shot of a gantry across a big printer",
                "motion": "camera pans the long bridge",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["gantry bridge", "toolhead", "long span"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printer gantry bridge, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The bend",
                "teaching_point": "Weight and force flex it",
                "shot": "diagram-style shot of the bowing bridge",
                "motion": "bridge sags under the toolhead",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bowing bridge", "sag arrows", "toolhead load"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of gantry bridge sag, clean engineering visualization on a dark background",
            },
            {
                "goal": "The print",
                "teaching_point": "Leaning walls and shifted tops",
                "shot": "diagram-style shot of the deflected print",
                "motion": "top layers shift as the sag grows",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["leaning wall", "shifted top", "sag trace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of deflection hiding in a print, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fixes",
                "teaching_point": "Stiffer, twin, shorter",
                "shot": "diagram-style shot of the stiffening fixes",
                "motion": "twin rails and ribs brace the bridge",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["twin rails", "stiffener ribs", "short span"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of gantry stiffening fixes, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Stiffness sets the speed",
                "shot": "wide hero shot of a tall rigid printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["rigid frame", "stiff gantry", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a rigid 3D printer frame, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A gantry bridge bowing under the toolhead with a sag indicator",
            "subject": "XY gantry deflection",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bridge left, toolhead right",
            "text": "EVERY BRIDGE FLEXES",
            "elements": ["gantry bridge", "toolhead", "deflection indicator"],
            "style": "geometry studio photography",
            "mood": "bowed, flexed, stiffened",
            "prompt": "photograph of a 3D printer gantry bridge bowing slightly under the toolhead with a deflection indicator showing the sag, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "XY Gantry Deflection: The Machine Bends Before the Plastic Does",
            "title_variations": [
                "What Is Gantry Deflection",
                "Gantry Sag Explained",
                "Toolhead Sag Fix",
                "XY Flex in 3D Printers",
                "Stiffen Your Printer Gantry",
            ],
            "description": "Every gantry flexes a little: the toolhead rides on rails across a bridge, and the bridge bends under its own weight and the print's forces, so the nozzle drops a fraction of a millimeter off the planned path. Deflection hides in the print: the top layers shift, the walls lean, and fast printing makes the flex worse, because acceleration shoves the whole carriage. The fixes are mechanical: a stiffer bridge, twin rails, and a shorter span all cut the sag, and speed is limited by stiffness. This short finds the bow, reads the print, and stiffens the frame. The machine bends before the plastic does.",
            "hashtags": ["#Gantry", "#3DPrinting", "#Stiffness", "#MachineDesign"],
            "seo_keywords": [
                "what is gantry deflection",
                "gantry deflection",
                "xy flex",
                "toolhead sag",
                "stiffness",
                "fix gantry sag",
                "printer frame stiffness",
            ],
        },
        "fact_check": [
            "Every gantry flexes.",
            "Sag shifts the walls.",
            "Acceleration feeds the flex.",
            "Twin rails cut the sag.",
            "Stiffness limits speed.",
        ],
    },
    {
        "topic": "PSU & Wiring Safety",
        "core_question": "What power supply do I need?",
        "learning_objective": "The viewer understands PSU and wiring safety.",
        "engineering_summary": "Your printer's power supply is the one part that can hurt you: a 12 or 24 volt rail runs big current, and a loose connector, a chafed wire, or a bare terminal can melt, arc, or start a fire. The rules are rating, crimping, and fusing: size the supply for the peak heat load, crimp real connectors instead of soldering bad joints, and keep the fuse close to the battery or supply. Heated beds draw the most, so their wires get the thickest gauge, and every connection gets rechecked. Electricity is the silent failure mode.",
        "real_world_application": "Heated-bed wires and screw terminals are the classic failure points.",
        "common_misconceptions": [
            "Bigger voltage is always better (rating must match the parts)",
            "Soldered joints are best (loose solder connections arc)",
            "The supply protects the printer (the fuse does)",
        ],
        "teaching_strategy": "Show the current path, then the crimped connection.",
        "script": "Your printer's power supply is the one part that can hurt you: a 12 or 24 volt rail runs big current, and a loose connector, a chafed wire, or a bare terminal can melt, arc, or start a fire. The rules are rating, crimping, and fusing: size the supply for the peak heat load, crimp real connectors instead of soldering bad joints, and keep the fuse close to the battery or supply. Heated beds draw the most, so their wires get the thickest gauge, and every connection gets rechecked. Electricity is the silent failure mode.",
        "text_overlay": [
            "THE PART THAT CAN HURT YOU",
            "RATING, CRIMPING, FUSING",
            "HEATED BED DRAWS THE MOST",
            "ELECTRICITY IS SILENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the supply",
                "teaching_point": "Big current hides in small wires",
                "shot": "close-up shot of a printer power supply",
                "motion": "camera pans the wire bundle",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["power supply", "wire bundle", "terminal block"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printer power supply and wiring, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The current",
                "teaching_point": "12 or 24 volts, big amps",
                "shot": "diagram-style shot of the current path",
                "motion": "current flows from supply to heat bed",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["current arrows", "heat bed", "wire gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of printer power flow, clean engineering visualization on a dark background",
            },
            {
                "goal": "The danger",
                "teaching_point": "Loose joints melt and arc",
                "shot": "diagram-style shot of a bad joint",
                "motion": "loose terminal sparks and melts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["loose terminal", "arcing spark", "melted wire"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a failing wire connection, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Crimp, rate, and fuse",
                "shot": "diagram-style shot of the crimped connector",
                "motion": "crimp tool closes on the terminal",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["crimp tool", "crimped terminal", "fuse block"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of crimping a wire connector, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Recheck every connection",
                "shot": "wide hero shot of a tidy electronics bay",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["tidy bay", "fused supply", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tidy printer electronics bay, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A 24 volt supply with thick wires, a crimped connector, and a fuse",
            "subject": "PSU and wiring safety",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "supply left, fuse right",
            "text": "RATING, CRIMPING, FUSING",
            "elements": ["power supply", "crimped connector", "fuse block"],
            "style": "geometry studio photography",
            "mood": "rated, crimped, fused",
            "prompt": "photograph of a 24 volt power supply with thick wires and a proper crimped connector beside a fuse on a workbench, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PSU & Wiring Safety: Rating, Crimping, Fusing",
            "title_variations": [
                "What Power Supply Do I Need",
                "Printer Wiring Safety",
                "PSU Selection Guide",
                "Crimp vs Solder Wires",
                "3D Printer Fire Safety",
            ],
            "description": "Your printer's power supply is the one part that can hurt you: a 12 or 24 volt rail runs big current, and a loose connector, a chafed wire, or a bare terminal can melt, arc, or start a fire. The rules are rating, crimping, and fusing: size the supply for the peak heat load, crimp real connectors instead of soldering bad joints, and keep the fuse close to the battery or supply. Heated beds draw the most, so their wires get the thickest gauge, and every connection gets rechecked. This short follows the current, finds the weak joint, and fixes the wire. Electricity is the silent failure mode.",
            "hashtags": ["#PSU", "#WiringSafety", "#3DPrinting", "#Electronics"],
            "seo_keywords": [
                "what power supply do I need",
                "psu",
                "power supply",
                "wiring safety",
                "electrical printer",
                "crimp vs solder wires",
                "3d printer fire safety",
            ],
        },
        "fact_check": [
            "Big current can melt wires.",
            "Crimp real connectors.",
            "Rate for the peak load.",
            "Keep the fuse close.",
            "Heated beds draw the most.",
        ],
    },
    {
        "topic": "Closed-Loop Control",
        "core_question": "What is closed-loop control?",
        "learning_objective": "The viewer understands closed-loop control.",
        "engineering_summary": "An open-loop stepper takes orders and hopes: the motor steps, and the controller assumes the move happened, so a skipped step becomes a shifted layer. Closed-loop adds feedback: an encoder on the shaft reports real position, and the controller corrects on the fly, so a missed step gets caught and fixed in the next move. The wins are reliability and torque: the loop senses a stall and never lets the error compound. The rules are encoders, tuning, and trust: the sensor reads the true angle, and the loop reacts. Feedback turns guessing into knowing.",
        "real_world_application": "Servo steppers and coreXY builds use encoders for reliability.",
        "common_misconceptions": [
            "Steppers never skip (stalls happen under load)",
            "Closed loop is automatic (the loop needs tuning)",
            "Feedback slows printing (it reacts in milliseconds)",
        ],
        "teaching_strategy": "Show the skipped step, then the encoder catching it.",
        "script": "An open-loop stepper takes orders and hopes: the motor steps, and the controller assumes the move happened, so a skipped step becomes a shifted layer. Closed-loop adds feedback: an encoder on the shaft reports real position, and the controller corrects on the fly, so a missed step gets caught and fixed in the next move. The wins are reliability and torque: the loop senses a stall and never lets the error compound. The rules are encoders, tuning, and trust: the sensor reads the true angle, and the loop reacts. Feedback turns guessing into knowing.",
        "text_overlay": [
            "OPEN LOOP: ORDER AND HOPE",
            "ENCODER REPORTS REAL POSITION",
            "THE LOOP CATCHES THE STALL",
            "FEEDBACK TURNS GUESSING INTO KNOWING",
        ],
        "scenes": [
            {
                "goal": "Hook: the skipping step",
                "teaching_point": "Lost steps shift layers",
                "shot": "close-up shot of a stepper under load",
                "motion": "camera pans to the skipped shift",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stepper motor", "skipped shift", "loaded axis"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a stepper motor on a printer axis, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The open loop",
                "teaching_point": "Orders without proof",
                "shot": "diagram-style shot of the open loop",
                "motion": "commands flow out, nothing reports back",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["command flow", "stepper coil", "no feedback"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an open-loop stepper, clean engineering visualization on a dark background",
            },
            {
                "goal": "The feedback",
                "teaching_point": "The encoder watches the shaft",
                "shot": "diagram-style shot of the encoder",
                "motion": "disc spins and reports the true angle",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["encoder disc", "sensor head", "true angle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an encoder on a motor shaft, clean engineering visualization on a dark background",
            },
            {
                "goal": "The correction",
                "teaching_point": "Catch and fix the error",
                "shot": "diagram-style shot of the correction cycle",
                "motion": "error arrow swings back to the path",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["error arrow", "correction pulse", "return path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of closed-loop correction, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Know, don't guess",
                "shot": "wide hero shot of a printer with servo steppers",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["servo stepper", "encoder wiring", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer with servo stepper motors, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A stepper motor with an encoder disc and a controller readout",
            "subject": "closed-loop control",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "motor left, controller right",
            "text": "FEEDBACK TURNS GUESSING INTO KNOWING",
            "elements": ["stepper motor", "encoder disc", "controller readout"],
            "style": "geometry studio photography",
            "mood": "measured, corrected, known",
            "prompt": "photograph of a stepper motor with an encoder disc on the shaft and a controller showing the measured position, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Closed-Loop Control: Feedback Turns Guessing into Knowing",
            "title_variations": [
                "What Is Closed-Loop Control",
                "Open Loop vs Closed Loop",
                "Encoder Feedback Steppers",
                "Servo Steppers Explained",
                "Skip Step Prevention",
            ],
            "description": "An open-loop stepper takes orders and hopes: the motor steps, and the controller assumes the move happened, so a skipped step becomes a shifted layer. Closed-loop adds feedback: an encoder on the shaft reports real position, and the controller corrects on the fly, so a missed step gets caught and fixed in the next move. The wins are reliability and torque: the loop senses a stall and never lets the error compound. The rules are encoders, tuning, and trust: the sensor reads the true angle, and the loop reacts. This short skips a step, catches it, and shows the fix.",
            "hashtags": ["#ClosedLoop", "#StepperMotors", "#Encoder", "#3DPrinting"],
            "seo_keywords": [
                "what is closed-loop control",
                "closed loop",
                "encoder feedback",
                "open loop",
                "servo steppers",
                "closed loop vs open loop stepper",
                "skip step prevention",
            ],
        },
        "fact_check": [
            "Open loops guess.",
            "Encoders report position.",
            "The loop corrects errors.",
            "Stalls get caught.",
            "Errors never compound.",
        ],
    },
    {
        "topic": "Resonance & VFAs",
        "core_question": "What causes vertical fine artifacts?",
        "learning_objective": "The viewer understands resonance and vertical fine artifacts.",
        "engineering_summary": "Vertical fine artifacts are the ghosts of vibration: the nozzle shakes at a natural frequency, and the shaking echoes through every layer, drawing faint vertical ribs and waves on flat walls. The vibration has sources: ringing from sudden direction changes, resonance between the frame and the print speed, and slack in belts or bearings that lets the head wobble. The fixes are mechanical and digital: tighten the belts, brace the frame, and let input shaping cancel the vibration by knowing its frequency. The walls remember every shake.",
        "real_world_application": "Fast printers rely on input shaping to quiet VFAs.",
        "common_misconceptions": [
            "VFAs are extrusion errors (they are vibration echoes)",
            "Slower speed always fixes them (resonance needs a frequency match)",
            "New filament cures the ribs (the frame is shaking)",
        ],
        "teaching_strategy": "Show the shaking nozzle, then the input shaping fix.",
        "script": "Vertical fine artifacts are the ghosts of vibration: the nozzle shakes at a natural frequency, and the shaking echoes through every layer, drawing faint vertical ribs and waves on flat walls. The vibration has sources: ringing from sudden direction changes, resonance between the frame and the print speed, and slack in belts or bearings that lets the head wobble. The fixes are mechanical and digital: tighten the belts, brace the frame, and let input shaping cancel the vibration by knowing its frequency. The walls remember every shake.",
        "text_overlay": [
            "GHOSTS OF VIBRATION",
            "RINGING, RESONANCE, SLACK",
            "INPUT SHAPING KNOWS THE FREQUENCY",
            "THE WALLS REMEMBER",
        ],
        "scenes": [
            {
                "goal": "Hook: the ribbed wall",
                "teaching_point": "Faint waves on flat faces",
                "shot": "close-up shot of a printed wall with VFAs",
                "motion": "camera tilts along the ribs",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed wall", "vertical ribs", "wave pattern"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printed wall with vertical fine artifacts, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The shake",
                "teaching_point": "The nozzle rings at a frequency",
                "shot": "diagram-style shot of the shaking nozzle",
                "motion": "nozzle vibrates like a struck bell",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shaking nozzle", "ringing arrows", "frequency trace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of nozzle vibration, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sources",
                "teaching_point": "Ringing, resonance, slack",
                "shot": "diagram-style shot of the vibration sources",
                "motion": "three sources feed the shake",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["ringing tile", "resonance tile", "slack tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of vibration sources in a printer, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Input shaping cancels the shake",
                "shot": "diagram-style shot of the shaping waveform",
                "motion": "counter-pulse flattens the ringing",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shaping pulse", "flat result", "frequency graph"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of input shaping cancelling vibration, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Quiet the machine",
                "shot": "wide hero shot of a smooth-walled print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth wall", "clean surface", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth-walled 3D print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed wall with faint ribs beside a vibration diagram",
            "subject": "resonance and vertical fine artifacts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "wall left, diagram right",
            "text": "THE WALLS REMEMBER",
            "elements": ["ribbed wall", "vibration trace", "nozzle shake"],
            "style": "geometry studio photography",
            "mood": "rung, shaken, quieted",
            "prompt": "photograph of a printed wall with faint vertical ribs and wave artifacts beside a vibration diagram of a shaking nozzle, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Resonance & VFAs: The Walls Remember Every Shake",
            "title_variations": [
                "What Causes Vertical Fine Artifacts",
                "VFA Fix 3D Prints",
                "Ringing and Resonance",
                "Input Shaping Explained",
                "Quiet Nozzle Vibration",
            ],
            "description": "Vertical fine artifacts are the ghosts of vibration: the nozzle shakes at a natural frequency, and the shaking echoes through every layer, drawing faint vertical ribs and waves on flat walls. The vibration has sources: ringing from sudden direction changes, resonance between the frame and the print speed, and slack in belts or bearings that lets the head wobble. The fixes are mechanical and digital: tighten the belts, brace the frame, and let input shaping cancel the vibration by knowing its frequency. This short finds the shake, maps the sources, and shapes the signal. The walls remember every shake.",
            "hashtags": ["#VFA", "#Resonance", "#InputShaping", "#3DPrinting"],
            "seo_keywords": [
                "what causes vertical fine artifacts",
                "vfa",
                "resonance",
                "ringing",
                "vertical fine artifacts",
                "input shaping 3d printer",
                "fix ringing 3d prints",
            ],
        },
        "fact_check": [
            "VFAs are vibration echoes.",
            "The nozzle rings at a frequency.",
            "Belts and frames wobble.",
            "Input shaping cancels the shake.",
            "Walls record the vibration.",
        ],
    },
    {
        "topic": "Stepper Motor Mounts",
        "core_question": "How to mount a stepper?",
        "learning_objective": "The viewer understands stepper motor mounts.",
        "engineering_summary": "Stepper mounts are a fit problem: the motor face carries a bolt pattern, the shaft needs a clear bore, and the mount must hold the motor square so the shaft lines up with the pulley or lead screw. The NEMA standard sets the pattern: a NEMA 17 stepper has four holes on a square, and the mount positions them exactly. The rules are alignment, clearance, and stiffness: the shaft bore must clear the shoulder, the mount must not flex under torque, and the screws need thread bite. A loose motor is a wobbling axis.",
        "real_world_application": "Every extruder and Z axis hangs on a NEMA mount.",
        "common_misconceptions": [
            "Any hole spacing works (NEMA sets the pattern)",
            "Tight screws are enough (the mount must also be stiff)",
            "The shaft can rub the mount (it needs a clear bore)",
        ],
        "teaching_strategy": "Show the bolt pattern, then the aligned pulley.",
        "script": "Stepper mounts are a fit problem: the motor face carries a bolt pattern, the shaft needs a clear bore, and the mount must hold the motor square so the shaft lines up with the pulley or lead screw. The NEMA standard sets the pattern: a NEMA 17 stepper has four holes on a square, and the mount positions them exactly. The rules are alignment, clearance, and stiffness: the shaft bore must clear the shoulder, the mount must not flex under torque, and the screws need thread bite. A loose motor is a wobbling axis.",
        "text_overlay": [
            "NEMA SETS THE PATTERN",
            "ALIGNMENT, CLEARANCE, STIFFNESS",
            "SQUARE MOTOR, STRAIGHT SHAFT",
            "A LOOSE MOTOR WOBBLES",
        ],
        "scenes": [
            {
                "goal": "Hook: the mount",
                "teaching_point": "The axis hangs on four bolts",
                "shot": "close-up shot of a mounted stepper",
                "motion": "camera pans the bolt pattern",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stepper motor", "mount bracket", "bolt pattern"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a stepper motor mounted on a bracket, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The pattern",
                "teaching_point": "NEMA 17 geometry",
                "shot": "diagram-style shot of the NEMA face",
                "motion": "four holes snap onto the square",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["NEMA face", "hole square", "pilot bore"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the NEMA 17 mount pattern, clean engineering visualization on a dark background",
            },
            {
                "goal": "The alignment",
                "teaching_point": "Shaft meets pulley square",
                "shot": "diagram-style shot of the shaft line",
                "motion": "shaft centers in the pulley bore",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shaft line", "pulley bore", "alignment mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stepper shaft alignment, clean engineering visualization on a dark background",
            },
            {
                "goal": "The stiffness",
                "teaching_point": "Torque flexes weak mounts",
                "shot": "diagram-style shot of the flexing mount",
                "motion": "mount bends under rapid torque",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flexing mount", "torque arrow", "stiff brace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a stepper mount flexing, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Square, clear, and stiff",
                "shot": "wide hero shot of a complete axis",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["mounted axis", "aligned pulley", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fully assembled printer axis, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A NEMA 17 stepper on a bracket with bolts and an aligned pulley",
            "subject": "stepper motor mounts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "motor left, pulley right",
            "text": "SQUARE MOTOR, STRAIGHT SHAFT",
            "elements": ["stepper motor", "mount bracket", "aligned pulley"],
            "style": "geometry studio photography",
            "mood": "squared, aligned, stiff",
            "prompt": "photograph of a NEMA 17 stepper motor mounted on a printed bracket with four bolts and a pulley lined up on the shaft, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stepper Motor Mounts: Square Motor, Straight Shaft",
            "title_variations": [
                "How to Mount a Stepper",
                "NEMA 17 Mount Guide",
                "Motor Bracket Fit",
                "Stepper Mount Holes",
                "Printer Axis Assembly",
            ],
            "description": "Stepper mounts are a fit problem: the motor face carries a bolt pattern, the shaft needs a clear bore, and the mount must hold the motor square so the shaft lines up with the pulley or lead screw. The NEMA standard sets the pattern: a NEMA 17 stepper has four holes on a square, and the mount positions them exactly. The rules are alignment, clearance, and stiffness: the shaft bore must clear the shoulder, the mount must not flex under torque, and the screws need thread bite. This short lines up the bolt pattern, centers the shaft, and braces the mount. A loose motor is a wobbling axis.",
            "hashtags": ["#StepperMotor", "#NEMA17", "#3DPrinting", "#Fits"],
            "seo_keywords": [
                "how to mount a stepper",
                "stepper mount",
                "nema 17 mount",
                "motor bracket",
                "mount holes",
                "nema 17 hole pattern",
                "stepper alignment pulley",
            ],
        },
        "fact_check": [
            "NEMA sets the pattern.",
            "The bore must clear the shoulder.",
            "Mounts must stay square.",
            "Torque flexes weak mounts.",
            "A loose motor wobbles.",
        ],
    },
    {
        "topic": "Young's Modulus for Printers",
        "core_question": "What does Young's modulus mean for prints?",
        "learning_objective": "The viewer understands Young's modulus for printers.",
        "engineering_summary": "Young's modulus is the stiffness ruler: it tells how much a material stretches for a given stress, and a high modulus means the part resists bending, while a low one means it sags. The numbers explain prints: PETG bends more than ABS, which bends more than carbon-filled nylon, and modulus decides whether a bracket holds its shape or flexes under load. The rules are modulus, geometry, and loading: stiffness comes from material and shape, so a thick rib beats a stiff filament, and the load direction matters. Choose modulus for stiffness, geometry for strength.",
        "real_world_application": "Datasheet modulus numbers predict which bracket stays straight.",
        "common_misconceptions": [
            "Stiffer filament always wins (geometry matters more)",
            "Strength and stiffness are the same (modulus is only stiffness)",
            "All plastics bend alike (modulus ranks them)",
        ],
        "teaching_strategy": "Show the bending bars, then the ribbed fix.",
        "script": "Young's modulus is the stiffness ruler: it tells how much a material stretches for a given stress, and a high modulus means the part resists bending, while a low one means it sags. The numbers explain prints: PETG bends more than ABS, which bends more than carbon-filled nylon, and modulus decides whether a bracket holds its shape or flexes under load. The rules are modulus, geometry, and loading: stiffness comes from material and shape, so a thick rib beats a stiff filament, and the load direction matters. Choose modulus for stiffness, geometry for strength.",
        "text_overlay": [
            "THE STIFFNESS RULER",
            "HIGH MODULUS RESISTS BENDING",
            "PETG BENDS MORE THAN ABS",
            "RIBS BEAT FILAMENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the bending bars",
                "teaching_point": "Some plastics flex more",
                "shot": "close-up shot of three bent samples",
                "motion": "camera pans the flexing bars",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["bent bars", "sample trio", "flex compare"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of three filament samples bending, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The ruler",
                "teaching_point": "Stress over strain",
                "shot": "diagram-style shot of the modulus slope",
                "motion": "steeper slope means stiffer",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stress axis", "strain axis", "stiff slope"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of Young's modulus slope, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ranking",
                "teaching_point": "PETG, ABS, carbon nylon",
                "shot": "diagram-style shot of the material ladder",
                "motion": "bars stiffen up the ladder",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["PETG rung", "ABS rung", "carbon rung"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of filament stiffness ranking, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shape",
                "teaching_point": "Geometry beats material",
                "shot": "diagram-style shot of the ribbed bracket",
                "motion": "thin part flexes, ribbed part stays",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thin part", "ribbed part", "flex compare"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of ribbed versus thin brackets, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick modulus for stiffness",
                "shot": "wide hero shot of a stiff bracket",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stiff bracket", "ribbed frame", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a stiff ribbed printed bracket, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three filament bars bending in a stiffness test",
            "subject": "Young's modulus for printers",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bars left, chart right",
            "text": "RIBS BEAT FILAMENT",
            "elements": ["bending bars", "stiffness chart", "sample trio"],
            "style": "geometry studio photography",
            "mood": "bent, ranked, stiffened",
            "prompt": "photograph of a stiffness test bending three filament samples side by side with PETG, ABS, and carbon nylon bars on a bench, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Young's Modulus for Printers: The Stiffness Ruler",
            "title_variations": [
                "What Is Young's Modulus",
                "Filament Stiffness Guide",
                "Material Modulus Comparison",
                "Stiffness vs Strength",
                "Which Filament Bends Least",
            ],
            "description": "Young's modulus is the stiffness ruler: it tells how much a material stretches for a given stress, and a high modulus means the part resists bending, while a low one means it sags. The numbers explain prints: PETG bends more than ABS, which bends more than carbon-filled nylon, and modulus decides whether a bracket holds its shape or flexes under load. The rules are modulus, geometry, and loading: stiffness comes from material and shape, so a thick rib beats a stiff filament, and the load direction matters. This short bends the bars, ranks the materials, and ribs the bracket. Choose modulus for stiffness, geometry for strength.",
            "hashtags": ["#YoungsModulus", "#Stiffness", "#Materials", "#3DPrinting"],
            "seo_keywords": [
                "what does young's modulus mean for prints",
                "youngs modulus",
                "stiffness filament",
                "material stiffness",
                "modulus comparison",
                "petg vs abs stiffness",
                "carbon nylon modulus",
            ],
        },
        "fact_check": [
            "Modulus ranks stiffness.",
            "High modulus resists bending.",
            "Carbon nylon is stiffer.",
            "Geometry beats material.",
            "Ribs stiffen parts.",
        ],
    },
]