"""Batch 39: avoiding sharp corners, generous radii, layer adhesion strength, gyroid lattices, lightweighting, compliant mechanisms, keyways and D-shafts, bolt bosses and ribs."""

CURATED = [
    # ======================================================================
    {
        "topic": "Avoid Sharp Corners",
        "core_question": "Why do printed parts crack at sharp corners?",
        "learning_objective": "The viewer understands why sharp corners fail and how to round them.",
        "engineering_summary": "Sharp corners are stress risers: loads concentrate at the crisp edge like water pressing on a crack, so a printed bracket cracks exactly where the corner is square. The fix is a fillet or a radius: a rounded corner spreads the same load across a wide arc, and the stress drops dramatically for just a little material. The rule of thumb is the biggest radius the design allows, because each print direction and each layer corner matters. Rounding the corner is the cheapest strength in design.",
        "real_world_application": "Brackets, mounts, and frames get their longest life from fillets at the corners.",
        "common_misconceptions": [
            "Sharp corners look fine (they concentrate stress invisibly)",
            "Only thick walls matter (the corner is where cracks start)",
            "A tiny fillet is enough (the biggest radius wins)",
        ],
        "teaching_strategy": "Show a square corner cracking, then the same part with a fillet surviving.",
        "script": "Sharp corners are stress risers: loads concentrate at the crisp edge like water pressing on a crack, so a printed bracket cracks exactly where the corner is square. The fix is a fillet or a radius: a rounded corner spreads the same load across a wide arc, and the stress drops dramatically for just a little material. The rule of thumb is the biggest radius the design allows, because each print direction and each layer corner matters. Round the corner, and the part stops failing at the corner.",
        "text_overlay": [
            "SHARP CORNERS ARE STRESS RISERS",
            "LOADS PILE AT THE CRISP EDGE",
            "A FILLET SPREADS THE LOAD",
            "THE BIGGEST RADIUS WINS",
        ],
        "scenes": [
            {
                "goal": "Hook: the cracked bracket",
                "teaching_point": "It cracks at the square corner",
                "shot": "close-up shot of a crack at a sharp printed corner",
                "motion": "camera traces the crack line",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["cracked bracket", "sharp corner", "crack line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a crack at a sharp printed corner, bright task lighting, print lab",
            },
            {
                "goal": "The pile-up",
                "teaching_point": "Stress concentrates at the notch",
                "shot": "diagram-style shot of load lines piling at a corner",
                "motion": "arrows bunch at the sharp edge",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["load lines", "sharp corner", "stress pile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stress lines piling at a sharp corner, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fillet",
                "teaching_point": "Radius spreads the load",
                "shot": "diagram-style shot of load lines flowing around a fillet",
                "motion": "arrows sweep the rounded arc",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flowing arrows", "fillet arc", "wide spread"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stress lines flowing around a fillet, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rule",
                "teaching_point": "Biggest radius you can fit",
                "shot": "comparison shot of small and large fillet corners",
                "motion": "the larger fillet is highlighted",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["small fillet", "large fillet", "bracket pair"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two printed brackets with small and large fillet corners, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cheapest strength in design",
                "shot": "wide hero shot of a filleted bracket under load",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["filleted bracket", "load rig", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a filleted bracket under load, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cracked square corner beside a rounded filleted corner on a bracket",
            "subject": "avoiding sharp corners",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cracked corner left, fillet right",
            "text": "THE BIGGEST RADIUS WINS",
            "elements": ["cracked corner", "fillet corner", "bracket"],
            "style": "geometry studio photography",
            "mood": "cracked, rounded, relieved",
            "prompt": "macro photograph of a cracked square corner beside a rounded filleted corner on a printed bracket, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Avoid Sharp Corners: The Biggest Radius Wins",
            "title_variations": [
                "Why Prints Crack at Corners",
                "Fillet Your Print Corners",
                "Sharp Corner Stress Risers",
                "Strengthen Printed Brackets",
                "Corner Radius Design Rule",
            ],
            "description": "Sharp corners are stress risers: loads concentrate at the crisp edge like water pressing on a crack, so a printed bracket cracks exactly where the corner is square. The fix is a fillet or a radius, which spreads the same load across a wide arc and drops the stress dramatically. The rule of thumb is the biggest radius the design allows. This short cracks a square corner, piles the load lines, and rounds the part into its cheapest strength.",
            "hashtags": ["#StressRisers", "#Fillets", "#Design", "#3DPrinting"],
            "seo_keywords": [
                "why prints crack at corners",
                "fillet your print corners",
                "sharp corner stress riser",
                "strengthen printed brackets",
                "corner radius design rule",
                "print stress concentration",
                "rounded corners strength",
            ],
        },
        "fact_check": [
            "Sharp corners concentrate stress.",
            "Loads pile at the crisp edge.",
            "Fillets spread the load.",
            "Bigger radii cut the stress.",
            "Radius is cheap strength.",
        ],
    },
    {
        "topic": "Generous Radii & Stress",
        "core_question": "Why do sharp corners crack under load?",
        "learning_objective": "The viewer understands stress concentration and generous radii.",
        "engineering_summary": "Sharp corners crack because they concentrate stress: the load line bends around a crisp corner and piles up at the notch, sometimes tripling the local stress. A generous radius spreads that load over a broad arc, and the stress concentration factor falls dramatically, so the same part survives the same load. The science is the stress concentration factor, and the practice is a radius at every internal and external corner, as large as the geometry allows. Radii are the cheapest reinforcement in design: they cost one fillet and buy real strength.",
        "real_world_application": "Frames, arms, and loaded housings get their fatigue life from corner radii.",
        "common_misconceptions": [
            "A small radius is enough (the factor still spikes at tight notches)",
            "Only the outside corner matters (internal corners concentrate too)",
            "Thick material forgives corners (notches concentrate regardless)",
        ],
        "teaching_strategy": "Show the stress concentration diagram, then the radius lowering it.",
        "script": "Sharp corners crack because they concentrate stress: the load line bends around a crisp corner and piles up at the notch, sometimes tripling the local stress. A generous radius spreads that load over a broad arc, and the stress concentration factor falls dramatically, so the same part survives the same load. The science is the stress concentration factor, and the practice is a radius at every internal and external corner, and the radius should be as large as the geometry allows. Radii are the cheapest reinforcement in design: they cost one fillet and buy real strength.",
        "text_overlay": [
            "LOADS PILE AT NOTCHES",
            "TRIPLED LOCAL STRESS",
            "RADII SPREAD THE LOAD",
            "THE CHEAPEST REINFORCEMENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the snapped arm",
                "teaching_point": "It failed at the notch",
                "shot": "close-up shot of a broken arm at a sharp notch",
                "motion": "camera pans the fracture face",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["broken arm", "sharp notch", "fracture face"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a broken printed arm at a sharp notch, bright task lighting, print lab",
            },
            {
                "goal": "The factor",
                "teaching_point": "Stress concentration factor",
                "shot": "diagram-style shot of the stress factor curve",
                "motion": "factor spikes as radius shrinks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["factor curve", "radius axis", "spike zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the stress concentration factor curve, clean engineering visualization on a dark background",
            },
            {
                "goal": "The radius",
                "teaching_point": "Broad arc, lower peak",
                "shot": "diagram-style shot of stress flow with a large radius",
                "motion": "arrows sweep smoothly around the arc",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["smooth arrows", "large radius", "low peak"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stress flow around a large radius, clean engineering visualization on a dark background",
            },
            {
                "goal": "Both corners",
                "teaching_point": "Internal and external",
                "shot": "comparison shot of internal and external corner radii",
                "motion": "each radius is highlighted in turn",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["internal radius", "external radius", "test part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of internal and external corner radii on a printed test part, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One fillet buys strength",
                "shot": "wide hero shot of a radiused frame under test",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["radiused frame", "test rig", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a radiused printed frame under test, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A stress factor curve spiking at a sharp notch beside a smooth radius arc",
            "subject": "generous radii and stress",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "notch left, arc right",
            "text": "THE CHEAPEST REINFORCEMENT",
            "elements": ["factor curve", "sharp notch", "radius arc"],
            "style": "geometry studio photography",
            "mood": "spiked, spread, strengthened",
            "prompt": "photograph of a stress concentration curve spiking at a sharp notch beside a smooth radius arc, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Generous Radii & Stress: The Cheapest Reinforcement",
            "title_variations": [
                "Stress Concentration Explained",
                "Why Sharp Corners Crack",
                "Radius Your Part Corners",
                "Notch Stress Fix",
                "Filament Design Strength",
            ],
            "description": "Sharp corners crack because they concentrate stress: the load line bends around a crisp corner and piles up at the notch, sometimes tripling the local stress. A generous radius spreads that load over a broad arc, and the stress concentration factor falls dramatically. The practice is a radius at every internal and external corner, as large as the geometry allows. This short spikes the factor curve, sweeps the arcs, and shows radii as the cheapest reinforcement in design.",
            "hashtags": ["#StressConcentration", "#Radii", "#DesignStrength", "#3DPrinting"],
            "seo_keywords": [
                "stress concentration explained",
                "why sharp corners crack",
                "radius your part corners",
                "notch stress fix",
                "generous radii design",
                "stress concentration factor",
                "fillet reinforcement print",
            ],
        },
        "fact_check": [
            "Notches concentrate stress.",
            "The factor can triple.",
            "Radii spread the load.",
            "Internal corners matter too.",
            "Radii are cheap strength.",
        ],
    },
    {
        "topic": "Layer Adhesion & Part Strength",
        "core_question": "How strong is a printed part in every direction?",
        "learning_objective": "The viewer understands layer adhesion and directional strength.",
        "engineering_summary": "A printed part is two materials in one: the solid polymer that flows between layers, and the bonded seams between them, so strength is directional. Pull along the layers and the part is close to the filament's strength; pull across them and the bond must hold, so parts fail first across layer lines. The bond strength comes from the print itself: hotter nozzles and slower speeds let each layer weld into the last, while a cool nozzle leaves weak seams. The design answer is orientation: put the load along the layers, not across them. Direction decides which way a part breaks.",
        "real_world_application": "Load-bearing brackets are oriented so forces run along the layers.",
        "common_misconceptions": [
            "Prints are equally strong everywhere (they fail across the seams first)",
            "Infill decides all strength (the layer bond decides it first)",
            "Any layer welds well (cool nozzles leave weak seams)",
        ],
        "teaching_strategy": "Show a test bar breaking across layers, then the orientation fix.",
        "script": "A printed part is two materials in one: the solid polymer between the layers, and the bonded seams holding them, so strength is directional. Pull along the layers and the part is close to the filament's strength; pull across and the bond must hold, so parts fail first across layer lines. The bond comes from printing: hotter nozzles and slower speeds let each layer weld into the last. The design answer is orientation: put the load along the layers, not across them. Direction decides which way a part breaks.",
        "text_overlay": [
            "STRENGTH IS DIRECTIONAL",
            "PARTS FAIL ACROSS THE SEAMS",
            "HOT NOZZLE WELDS LAYERS",
            "ORIENT THE LOAD ALONG LAYERS",
        ],
        "scenes": [
            {
                "goal": "Hook: the split part",
                "teaching_point": "It broke across the layers",
                "shot": "close-up shot of a part split along layer lines",
                "motion": "camera follows the seam failure",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["split part", "layer seams", "failure face"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printed part split along layer lines, bright task lighting, print lab",
            },
            {
                "goal": "The two materials",
                "teaching_point": "Polymer and bonded seams",
                "shot": "diagram-style shot of a part's layer structure",
                "motion": "solid and seam layers are labeled",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["solid polymer", "bonded seams", "layer stack"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a part's layer structure, clean engineering visualization on a dark background",
            },
            {
                "goal": "The weld",
                "teaching_point": "Hot and slow welds better",
                "shot": "diagram-style shot of layer welding at the nozzle",
                "motion": "fresh layer fuses into the last",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hot nozzle", "fusing layer", "weld zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layers welding at the nozzle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The orientation",
                "teaching_point": "Load along the layers",
                "shot": "comparison shot of two bar orientations under load",
                "motion": "cross-layer bar breaks, along-layer holds",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["cross-layer bar", "along-layer bar", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two printed test bars under load in different orientations, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Direction decides the break",
                "shot": "wide hero shot of a loaded bracket oriented with the layers",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["loaded bracket", "layer orientation", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a loaded bracket oriented with its layers, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A test bar split across layer seams beside an oriented bar holding load",
            "subject": "layer adhesion strength",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "split bar left, oriented bar right",
            "text": "ORIENT THE LOAD ALONG LAYERS",
            "elements": ["split seams", "oriented bar", "load arrows"],
            "style": "geometry studio photography",
            "mood": "split, welded, oriented",
            "prompt": "photograph of a test bar split across layer seams beside an oriented bar holding a load, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Layer Adhesion & Part Strength: Direction Decides",
            "title_variations": [
                "Why Prints Split at Layers",
                "Layer Bond Strength",
                "Print Orientation Strength",
                "Stronger Layer Adhesion",
                "Z Strength vs XY Strength",
            ],
            "description": "A printed part is two materials in one: the solid polymer that flows between layers, and the bonded seams between them. Pull along the layers and the part is close to the filament's strength; pull across them and parts fail first across layer lines. Hotter nozzles and slower speeds let each layer weld into the last. This short splits a test bar, welds the seams, and shows why orientation decides which way a part breaks.",
            "hashtags": ["#LayerAdhesion", "#PartStrength", "#Orientation", "#3DPrinting"],
            "seo_keywords": [
                "why prints split at layers",
                "layer bond strength",
                "print orientation strength",
                "stronger layer adhesion",
                "z strength vs xy strength",
                "layer weld nozzle temp",
                "directional print strength",
            ],
        },
        "fact_check": [
            "Strength is directional.",
            "Parts fail across seams.",
            "Heat welds the layers.",
            "Orientation sets the load path.",
            "Infill is not the first limit.",
        ],
    },
    {
        "topic": "Gyroid Lattice Parts",
        "core_question": "What is a gyroid lattice and why does it make parts lighter?",
        "learning_objective": "The viewer understands gyroid lattice structures.",
        "engineering_summary": "A gyroid is a mathematical surface that winds through space in a smooth wave, and printed as an infill it becomes a lattice with a rare property: it is strong in every direction because no flat walls stack up. The wave spreads loads through the whole volume, so a gyroid part carries more force per gram than simple grid patterns, and it needs no support because the wave is self-supporting as it prints. The trade-off is machine time: the smooth curves mean more motion than straight lines. A gyroid is strength without a preferred direction.",
        "real_world_application": "Lightweight brackets and cushioning parts use gyroid infill for strength per gram.",
        "common_misconceptions": [
            "Gyroid is only cosmetic (the wave structure carries real load)",
            "Any infill works the same (the gyroid spreads load in all directions)",
            "It prints like a grid (the curves are slower to machine)",
        ],
        "teaching_strategy": "Show the gyroid wave, then a load test against a grid.",
        "script": "A gyroid is a mathematical surface that winds through space in a smooth wave, and printed as an infill it becomes a lattice with a rare property: it is strong in every direction because no flat walls stack up. The wave spreads loads through the whole volume, so a gyroid part carries more force per gram than simple grid patterns, and it needs no support because the wave is self-supporting as it prints. The trade-off is machine time: the smooth curves mean more motion than straight lines. A gyroid is strength without a preferred direction.",
        "text_overlay": [
            "A WAVE THAT FILLS SPACE",
            "STRONG IN EVERY DIRECTION",
            "SELF-SUPPORTING AS IT PRINTS",
            "STRENGTH PER GRAM",
        ],
        "scenes": [
            {
                "goal": "Hook: the floating lattice",
                "teaching_point": "Light but strong",
                "shot": "wide shot of a gyroid lattice part held up",
                "motion": "camera orbits the wavy structure",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["gyroid part", "wavy surface", "open lattice"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a gyroid lattice part held up, bright task lighting, print lab",
            },
            {
                "goal": "The surface",
                "teaching_point": "A wave through space",
                "shot": "diagram-style shot of the gyroid wave surface",
                "motion": "the wave curls through the volume",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gyroid wave", "curved sheet", "volume fill"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a gyroid wave surface, clean engineering visualization on a dark background",
            },
            {
                "goal": "The spread",
                "teaching_point": "Loads go every direction",
                "shot": "diagram-style shot of load arrows spreading through the wave",
                "motion": "arrows fan into the curves",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["load arrows", "curved paths", "wave lattice"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of loads spreading through a gyroid, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade-off",
                "teaching_point": "More motion, more time",
                "shot": "comparison shot of gyroid and grid infill sections",
                "motion": "grid runs straight, gyroid sweeps",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["gyroid section", "grid section", "print head"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of gyroid and grid infill sections side by side, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Strength without a direction",
                "shot": "wide hero shot of a gyroid part under load",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["gyroid part", "load rig", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a gyroid part under load, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A wavy gyroid lattice part floating with load arrows spreading through it",
            "subject": "gyroid lattice parts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "lattice center, arrows around",
            "text": "STRENGTH PER GRAM",
            "elements": ["gyroid lattice", "load arrows", "wave surface"],
            "style": "geometry studio photography",
            "mood": "wavy, spread, weightless",
            "prompt": "photograph of a wavy gyroid lattice part floating with load arrows spreading through its curves, hard key light with rim, dark workshop background, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Gyroid Lattice Parts: Strength Per Gram",
            "title_variations": [
                "What Is Gyroid Infill",
                "Gyroid vs Grid Infill",
                "Lightweight Lattice Print",
                "Gyroid Strength Test",
                "Self-Supporting Gyroid",
            ],
            "description": "A gyroid is a mathematical surface that winds through space in a smooth wave, and printed as infill it becomes a lattice that is strong in every direction because no flat walls stack up. The wave spreads loads through the whole volume, so a gyroid part carries more force per gram than grid patterns, and it needs no support because the wave is self-supporting. The trade-off is machine time. This short rides the wave, spreads the arrows, and shows strength without a preferred direction.",
            "hashtags": ["#Gyroid", "#Lattice", "#Infill", "#3DPrinting"],
            "seo_keywords": [
                "what is gyroid infill",
                "gyroid vs grid infill",
                "lightweight lattice print",
                "gyroid strength test",
                "self-supporting gyroid",
                "gyroid per gram strength",
                "gyroid lattice design",
            ],
        },
        "fact_check": [
            "The gyroid is a wave surface.",
            "It is strong in every direction.",
            "The wave spreads loads.",
            "It prints without supports.",
            "Curves cost machine time.",
        ],
    },
    {
        "topic": "Lightweighting",
        "core_question": "How do you make a printed part lighter without making it weak?",
        "learning_objective": "The viewer understands lightweighting strategies.",
        "engineering_summary": "Lightweighting is the engineer's game of removing material where the load is not: hollow the core, keep the shell, and add ribs where the forces concentrate. The shell carries the bending load, so thin walls around a hollow center keep stiffness while cutting weight, and ribs transfer load across the open spans. The enemy is added complexity: each hole and lattice costs print time, and each thin wall risks the failure of the part. The rule is material where the load flows, air everywhere else. Lightweighting is a load map, not guesswork.",
        "real_world_application": "Robot arms and mounts shave grams with shells, ribs, and lattices.",
        "common_misconceptions": [
            "Less material always means weaker (shells and ribs keep the strength)",
            "Every hole helps (holes where load flows hurt)",
            "Infill percent is the only knob (geometry does the real work)",
        ],
        "teaching_strategy": "Show the load map, then the shell and rib design.",
        "script": "Lightweighting is the engineer's game of removing material where the load is not: hollow the core, keep the shell, and add ribs where the forces concentrate. The shell carries the bending load, so thin walls around a hollow center keep stiffness while cutting weight, and ribs transfer load across the open spans. The enemy is added complexity: each hole and lattice costs print time, and each thin wall risks the failure of the part. The rule is material where the load flows, air everywhere else. Lightweighting is a load map, not guesswork.",
        "text_overlay": [
            "REMOVE MATERIAL WHERE LOAD IS NOT",
            "THE SHELL CARRIES THE BEND",
            "RIBS SPAN THE OPEN GAPS",
            "A LOAD MAP, NOT GUESSWORK",
        ],
        "scenes": [
            {
                "goal": "Hook: the heavy bracket",
                "teaching_point": "Solid means heavy",
                "shot": "wide shot of a solid heavy bracket on a scale",
                "motion": "scale reads the mass",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["solid bracket", "scale", "reading"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a solid heavy bracket on a scale, neutral lab lighting, workbench",
            },
            {
                "goal": "The load map",
                "teaching_point": "Material where load flows",
                "shot": "diagram-style shot of the load map on the part",
                "motion": "hot zones glow where force flows",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["load map", "hot zones", "cool zones"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a load map on a bracket, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shell",
                "teaching_point": "Hollow core, thin walls",
                "shot": "diagram-style shot of a cross-section with a hollow core",
                "motion": "solid becomes shell and air",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shell walls", "hollow core", "cross-section"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a hollowed bracket cross-section, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ribs",
                "teaching_point": "Ribs span the gaps",
                "shot": "diagram-style shot of ribs crossing an open span",
                "motion": "ribs carry the arrows across",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["rib grid", "open span", "load path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of ribs spanning a bracket opening, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Same strength, less mass",
                "shot": "wide hero shot of the lightweight bracket on the scale",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["light bracket", "scale", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a lightweight bracket on a scale, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A load map glowing on a bracket beside a hollowed shell with ribs",
            "subject": "lightweighting",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bracket center, section beside",
            "text": "A LOAD MAP, NOT GUESSWORK",
            "elements": ["load map", "hollow shell", "rib grid"],
            "style": "geometry studio photography",
            "mood": "mapped, hollowed, ribbed",
            "prompt": "photograph of a load map glowing on a bracket beside a hollowed shell with ribs, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Lightweighting: A Load Map, Not Guesswork",
            "title_variations": [
                "How to Lighten a Print",
                "Shell and Rib Design",
                "Weight Reduction Parts",
                "Lightweight Bracket Design",
                "Remove Material Wisely",
            ],
            "description": "Lightweighting removes material where the load is not: hollow the core, keep the shell, and add ribs where forces concentrate. The shell carries the bending load, so thin walls around a hollow center keep stiffness while cutting weight, and ribs transfer load across open spans. The enemy is complexity, since each hole and lattice costs print time. This short maps the load, shells the core, and ribs the gaps, showing material where the load flows and air everywhere else.",
            "hashtags": ["#Lightweighting", "#ShellDesign", "#Ribs", "#3DPrinting"],
            "seo_keywords": [
                "how to lighten a print",
                "shell and rib design",
                "weight reduction parts",
                "lightweight bracket design",
                "remove material wisely",
                "hollow core print",
                "ribbed bracket strength",
            ],
        },
        "fact_check": [
            "The shell carries bending.",
            "Ribs span open gaps.",
            "Air replaces unloaded material.",
            "Complexity costs print time.",
            "The load map guides it.",
        ],
    },
    {
        "topic": "Compliant Mechanisms",
        "core_question": "Can a mechanism work with no hinges or springs?",
        "learning_objective": "The viewer understands compliant mechanisms.",
        "engineering_summary": "A compliant mechanism bends instead of hinges: a flexure is a thin section of material that flexes like a spring and returns when the load stops, so the whole mechanism is one printed piece with no joints and no assembly. The beauty is the cost: no bearings, no pins, no wear surfaces, and no assembly time, all from a single print. The catch is the material: the flexure must stay below its elastic limit every cycle, or the hinge creeps and snaps. A compliant mechanism trades a moving joint for a bending beam, and design picks which one lives longer.",
        "real_world_application": "Clips, clamps, and snap closures are flexures in everyday parts.",
        "common_misconceptions": [
            "It needs metal parts inside (the flexure is the whole joint)",
            "Any plastic can flex forever (each cycle must stay elastic)",
            "It is weaker than a hinge (well-designed flexures last longer)",
        ],
        "teaching_strategy": "Show a printed flexure bending, then the elastic limit warning.",
        "script": "A compliant mechanism bends instead of hinges: a flexure is a thin section that flexes like a spring and returns when the load stops, so the whole mechanism is one printed piece with no joints and no assembly. The beauty is the cost: no bearings, no pins, no wear surfaces, all from a single print. The catch is the material: the flexure must stay below its elastic limit every cycle, or the hinge creeps and snaps. A compliant mechanism trades a moving joint for a bending beam, and design picks which one lives longer.",
        "text_overlay": [
            "THE PART IS THE MECHANISM",
            "ONE PIECE, NO JOINTS",
            "STAY BELOW THE ELASTIC LIMIT",
            "A BENDING BEAM, NOT A HINGE",
        ],
        "scenes": [
            {
                "goal": "Hook: the one-piece clip",
                "teaching_point": "A joint with no parts",
                "shot": "wide shot of a one-piece printed clip opening",
                "motion": "the clip flexes and snaps back",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["one-piece clip", "flexing arm", "print"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a one-piece printed clip flexing open, bright task lighting, print lab",
            },
            {
                "goal": "The flexure",
                "teaching_point": "Thin beam, elastic bend",
                "shot": "diagram-style shot of a flexure beam bending",
                "motion": "beam curves and springs back",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flexure beam", "bend curve", "return arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a flexure beam bending, clean engineering visualization on a dark background",
            },
            {
                "goal": "The savings",
                "teaching_point": "No bearings, no assembly",
                "shot": "comparison shot of a hinged and a compliant part",
                "motion": "hinge parts scatter, compliant piece sits whole",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["hinge parts", "compliant piece", "single print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hinged assembly beside a one-piece compliant part, bright task lighting, workbench",
            },
            {
                "goal": "The limit",
                "teaching_point": "Elastic limit every cycle",
                "shot": "diagram-style shot of the elastic limit zone",
                "motion": "bend stays in the safe zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["elastic zone", "limit line", "bend curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the elastic limit zone for a flexure, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The part is the mechanism",
                "shot": "wide hero shot of a compliant mechanism in action",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["compliant part", "flexing joint", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a compliant mechanism in action, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A one-piece printed clamp bending at a thin flexure beam",
            "subject": "compliant mechanisms",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "clamp center, flexure highlighted",
            "text": "THE PART IS THE MECHANISM",
            "elements": ["flexure beam", "one-piece clamp", "bend curve"],
            "style": "geometry studio photography",
            "mood": "flexed, elastic, jointless",
            "prompt": "macro photograph of a one-piece printed clamp bending at a thin flexure beam with a return arrow, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Compliant Mechanisms: The Part Is the Mechanism",
            "title_variations": [
                "What Is a Flexure",
                "Print a Jointless Clamp",
                "Compliant Mechanism Design",
                "Flexure Joint Printing",
                "No-Hinge Mechanism",
            ],
            "description": "A compliant mechanism bends instead of hinges: a flexure is a thin section of material that flexes like a spring and returns when the load stops, so the whole mechanism is one printed piece with no joints and no assembly. The beauty is the cost, since there are no bearings, pins, or wear surfaces. The catch is the material: the flexure must stay below its elastic limit every cycle. This short bends the beam, scatters the hinge parts, and shows a mechanism that is one print.",
            "hashtags": ["#CompliantMechanisms", "#Flexures", "#MechanismDesign", "#3DPrinting"],
            "seo_keywords": [
                "what is a flexure",
                "print a jointless clamp",
                "compliant mechanism design",
                "flexure joint printing",
                "no-hinge mechanism",
                "elastic limit flexure",
                "one-piece mechanism print",
            ],
        },
        "fact_check": [
            "Flexures bend, not hinge.",
            "One piece needs no assembly.",
            "No bearings or pins.",
            "Cycles must stay elastic.",
            "Design picks the survivor.",
        ],
    },
    {
        "topic": "Keyways & D-Shafts",
        "core_question": "How do you fit a gear or knob to a motor shaft without slipping?",
        "learning_objective": "The viewer understands keyways and D-shafts.",
        "engineering_summary": "A round shaft cannot turn a part reliably, because the grip of a press fit slips under torque, so shafts use shapes: a D-shaft has one flat cut on the round, and a keyway cuts a slot that a key fills, locking hub to shaft. The key sits half in the shaft and half in the hub, and the torque passes through the key's sides, not through friction. The design rules are a snug fit and the right hole: D-shafts need a printed D-hole, and keyways need a slot matching the key. Shape, not squeeze, carries the torque.",
        "real_world_application": "Motor gears, knobs, and pulleys use D-flats and keys for positive drive.",
        "common_misconceptions": [
            "A press fit is enough (it slips under torque)",
            "A round hole works (the shaft spins inside it)",
            "Keys only matter on big machines (small shafts slip too)",
        ],
        "teaching_strategy": "Show a slipping round hole, then the D-flat and key locking it.",
        "script": "A round shaft cannot turn a part reliably, because the grip of a press fit slips under torque, so shafts use shapes: a D-shaft has one flat cut on the round, and a keyway cuts a slot that a key fills, locking hub to shaft. The key sits half in the shaft and half in the hub, and the torque passes through the key's sides, not through friction. The design rules are a snug fit and the right hole: D-shafts need a printed D-hole, and keyways need a slot matching the key. Shape, not squeeze, carries the torque.",
        "text_overlay": [
            "PRESS FITS SLIP UNDER TORQUE",
            "THE D-FLAT LOCKS THE HUB",
            "THE KEY CARRIES THE TORQUE",
            "SHAPE, NOT SQUEEZE",
        ],
        "scenes": [
            {
                "goal": "Hook: the slipping knob",
                "teaching_point": "The round hole spins free",
                "shot": "close-up shot of a knob spinning on a round shaft",
                "motion": "knob turns while the shaft lags",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["spinning knob", "round shaft", "slip gap"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a knob spinning on a round motor shaft, bright task lighting, workbench",
            },
            {
                "goal": "The D-flat",
                "teaching_point": "One flat locks it",
                "shot": "diagram-style shot of a D-shaft and D-hole",
                "motion": "flat meets flat and stops",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["D-flat", "D-hole", "locked fit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a D-shaft and D-hole fit, clean engineering visualization on a dark background",
            },
            {
                "goal": "The key",
                "teaching_point": "Key fills shaft and hub",
                "shot": "diagram-style shot of a key locking hub to shaft",
                "motion": "key slides in, halves meet",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["key block", "shaft slot", "hub slot"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a key locking a hub to a shaft, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Snug fit, right hole",
                "shot": "close-up shot of measuring a shaft flat for a print",
                "motion": "caliper reads the flat width",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper", "shaft flat", "hole sketch"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of measuring a motor shaft flat with a caliper, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Shape carries the torque",
                "shot": "wide hero shot of a gear locked to a motor shaft",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["locked gear", "motor shaft", "D-hole"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a gear locked to a motor shaft, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A D-shaft with a key locking a hub beside a slipping round fit",
            "subject": "keyways and D-shafts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "D-fit center, round slip beside",
            "text": "SHAPE, NOT SQUEEZE",
            "elements": ["D-shaft", "key block", "round slip"],
            "style": "geometry studio photography",
            "mood": "locked, keyed, positive",
            "prompt": "photograph of a D-shaft with a key locking a hub beside a slipping round fit, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Keyways & D-Shafts: Shape, Not Squeeze",
            "title_variations": [
                "How to Fit a Gear to a Shaft",
                "D-Shaft Hub Design",
                "Keyway Locking Explained",
                "Stop Print Hub Slipping",
                "Motor Shaft Coupling Print",
            ],
            "description": "A round shaft cannot turn a part reliably, because the grip of a press fit slips under torque. A D-shaft has one flat cut on the round, and a keyway cuts a slot that a key fills, locking hub to shaft. The key sits half in the shaft and half in the hub, so the torque passes through the key's sides, not through friction. This short spins a slipping knob, flats the shaft, and keys the hub, showing that shape, not squeeze, carries the torque.",
            "hashtags": ["#Keyways", "#DShafts", "#Fits", "#3DPrinting"],
            "seo_keywords": [
                "how to fit a gear to a shaft",
                "D-shaft hub design",
                "keyway locking explained",
                "stop print hub slipping",
                "motor shaft coupling print",
                "D-hole print fit",
                "shaft key torque transfer",
            ],
        },
        "fact_check": [
            "Press fits slip under torque.",
            "The D-flat locks the hub.",
            "The key fills two slots.",
            "Torque passes the key sides.",
            "Shape carries the load.",
        ],
    },
    {
        "topic": "Bolt Bosses & Ribs",
        "core_question": "How do you design a strong bolt hole in a print?",
        "learning_objective": "The viewer understands bolt boss design.",
        "engineering_summary": "A bolt boss is the printed tube that carries a screw into a part: the wall around the hole takes the clamp load, and its design decides whether the part strips or holds. The rules are thickness and reinforcement: the wall needs enough material for the thread, a rib or gusset carries the load down into the body, and a counterbore or countersink seats the head flat. The common failure is the split: too thin a wall and the boss cracks along the layer seam when the bolt torques. A boss is a structural column, not a hole.",
        "real_world_application": "Enclosures and brackets hold screws through bosses with gusset ribs.",
        "common_misconceptions": [
            "Any hole works (a thin wall boss cracks under torque)",
            "The screw holds the load (the wall and rib carry it)",
            "Bigger holes are stronger (walls need material, not air)",
        ],
        "teaching_strategy": "Show a split boss, then the ribbed boss holding the bolt.",
        "script": "A bolt boss is the printed tube that carries a screw into a part: the wall around the hole takes the clamp load, and its design decides whether the part strips or holds. The rules are thickness and reinforcement: the wall needs enough material for the thread, a rib or gusset carries the load down into the body, and a counterbore or countersink seats the head flat. The common failure is the split: too thin a wall and the boss cracks along the layer seam when the bolt torques. A boss is a structural column, not a hole.",
        "text_overlay": [
            "THE WALL TAKES THE CLAMP LOAD",
            "A RIB CARRIES IT DOWN",
            "SEAT THE HEAD FLAT",
            "A STRUCTURAL COLUMN, NOT A HOLE",
        ],
        "scenes": [
            {
                "goal": "Hook: the split boss",
                "teaching_point": "Thin walls crack under torque",
                "shot": "close-up shot of a split bolt boss on a print",
                "motion": "camera pans the crack line",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["split boss", "crack line", "bolt hole"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a split bolt boss on a printed part, bright task lighting, print lab",
            },
            {
                "goal": "The column",
                "teaching_point": "The wall carries the load",
                "shot": "diagram-style shot of a boss wall under clamp load",
                "motion": "load arrows press the wall ring",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["boss wall", "clamp arrows", "ring section"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a boss wall under clamp load, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rib",
                "teaching_point": "Gusset carries it down",
                "shot": "diagram-style shot of a rib under a boss",
                "motion": "load flows down the gusset",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gusset rib", "boss base", "load flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a gusset rib under a bolt boss, clean engineering visualization on a dark background",
            },
            {
                "goal": "The seat",
                "teaching_point": "Counterbore seats the head",
                "shot": "close-up shot of a bolt seated in a counterbored boss",
                "motion": "head lands flat in the seat",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["bolt head", "counterbore", "flat seat"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bolt seated in a counterbored printed boss, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A column, not a hole",
                "shot": "wide hero shot of a ribbed boss holding a bolted assembly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["ribbed boss", "bolted plate", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a ribbed boss holding a bolted assembly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A split thin boss beside a ribbed boss holding a seated bolt",
            "subject": "bolt boss design",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "split boss left, ribbed right",
            "text": "A STRUCTURAL COLUMN, NOT A HOLE",
            "elements": ["split boss", "gusset rib", "seated bolt"],
            "style": "geometry studio photography",
            "mood": "split, ribbed, seated",
            "prompt": "photograph of a split thin boss beside a ribbed boss holding a seated bolt, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bolt Bosses & Ribs: A Structural Column, Not a Hole",
            "title_variations": [
                "How to Design a Bolt Boss",
                "Strong Printed Screw Hole",
                "Boss Gusset Design",
                "Stop Boss Cracking",
                "Countersink Printed Boss",
            ],
            "description": "A bolt boss is the printed tube that carries a screw into a part: the wall around the hole takes the clamp load, and its design decides whether the part strips or holds. The wall needs enough material for the thread, a rib or gusset carries the load down into the body, and a counterbore seats the head flat. The common failure is the split, when a thin wall cracks along the layer seam. This short cracks a thin boss, ribs the gusset, and seats the bolt, treating the boss as a structural column.",
            "hashtags": ["#BoltBoss", "#Ribs", "#Fasteners", "#3DPrinting"],
            "seo_keywords": [
                "how to design a bolt boss",
                "strong printed screw hole",
                "boss gusset design",
                "stop boss cracking",
                "countersink printed boss",
                "bolt boss wall thickness",
                "boss rib reinforcement print",
            ],
        },
        "fact_check": [
            "The wall takes the clamp load.",
            "Ribs carry load into the body.",
            "Counterbores seat the head.",
            "Thin walls split under torque.",
            "A boss is a column.",
        ],
    },
]