"""Batch 1: flagship topics across the channel's core categories."""

CURATED = [
    # ======================================================================
    {
        "topic": "First-Layer Squish: Dial It In",
        "core_question": "How much should the first layer be pressed into the build plate?",
        "learning_objective": "The viewer can diagnose first-layer quality by reading line shape and adjust z-offset in 0.02 mm steps.",
        "engineering_summary": "The first layer transfers 100% of the load of the print to the build plate. Fused deposition bonds only when molten filament is pressed into the surface below, so the nozzle must extrude lines that are slightly wider than the set line width, with a flat glossy top. Zero squish leaves round, under-bonded lines; excess squish drags the nozzle through the plastic and creates ripples.",
        "real_world_application": "Every print's success, dimensional accuracy, and warp resistance starts at the first layer; print farms standardize z-offset before any production run.",
        "common_misconceptions": [
            "The z-offset number on screen is what matters, not what the nozzle does",
            "Lower z-offset always fixes adhesion",
            "A raft fixes a bad first layer (it only hides the bed problem)",
        ],
        "teaching_strategy": "Show a visual gradient of first-layer line shapes, from round to transparent, and anchor each state to a single sentence the viewer can repeat.",
        "script": "Why does your first layer look like a tire tread? That's zero squish. The nozzle is too high. Dial the z-offset down until lines are flat, slightly wide, and glossy, but not see-through. Glossy means plastic is actually bonding to the bed. Too low? You'll see ripples and ridges where the nozzle drags. Get it right and prints stick without glue. The first layer sets the tone for every layer after. So watch the nozzle, not the numbers.",
        "text_overlay": [
            "ZERO SQUISH = NO BOND",
            "GLOSSY = STICKING",
            "RIDGES = TOO LOW",
            "0.02 mm STEPS",
            "WATCH THE NOZZLE",
        ],
        "scenes": [
            {
                "goal": "Hook: a bad first layer with round, gapped lines",
                "teaching_point": "Round tire-tread lines mean the nozzle is too far from the bed",
                "shot": "macro low-angle close-up of printed first-layer lines with visible gaps",
                "motion": "slow push-in toward the line gaps",
                "lighting": "bright raking task light across the surface",
                "background": "print bed in a dark workshop, soft blur",
                "objects": ["first-layer test lines", "nozzle tip", "build plate"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a bad 3D printed first layer with round tire-tread lines and gaps, nozzle tip hovering above, glossy build plate below",
            },
            {
                "goal": "Define squish",
                "teaching_point": "Squish flattens each line into the bed, creating real bond area",
                "shot": "overhead macro of a perfect glossy first layer, lines fused into one surface",
                "motion": "gentle dolly along the fused lines",
                "lighting": "soft studio light, low glare",
                "background": "neutral workbench surface",
                "objects": ["perfect first layer", "fused line texture"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a perfect 3D printed first layer, flat glossy fused lines forming one smooth surface, soft studio lighting, neutral workbench",
            },
            {
                "goal": "Show too-low symptoms",
                "teaching_point": "Ripples and ridges mean the nozzle plows through the plastic",
                "shot": "extreme close-up macro on ridged, rippled first layer",
                "motion": "slow pan across the ridges",
                "lighting": "raking side light to amplify texture",
                "background": "dark blurred background",
                "objects": ["ridged first layer", "drag marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "extreme macro photograph of an over-squished 3D printed first layer with ripples and drag ridges, raking side light, dark background",
            },
            {
                "goal": "Show the adjustment action",
                "teaching_point": "Move z-offset in small steps, around 0.02 mm at a time",
                "shot": "medium shot of a hand adjusting z-offset on a printer touchscreen",
                "motion": "hand action, screen value updating",
                "lighting": "neutral workshop light",
                "background": "printer in a clean lab",
                "objects": ["printer touchscreen", "z-offset setting", "hand"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hand adjusting the z-offset setting on a 3D printer touchscreen in a modern print lab, clean workshop lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Judge the print by the nozzle's output, not the displayed number",
                "shot": "wide hero shot of a flawless glossy first layer on the build plate",
                "motion": "slow orbit around the plate",
                "lighting": "studio key light with cool rim",
                "background": "dark lab, subtle depth",
                "objects": ["flawless print base", "build plate"],
                "transition": "fade",
                "duration": 6,
                "prompt": "wide studio photograph of a flawless glossy 3D printed first layer on a build plate, dark engineering lab background, cinematic key light with rim",
            },
        ],
        "thumbnail": {
            "concept": "Half-and-half macro split: perfect glossy first layer against ridged, gapped first layer, one nozzle hovering between them",
            "subject": "printed first-layer test patch split diagonally between perfect and defective halves",
            "background": "dark workshop blur",
            "angle": "overhead macro, tight crop",
            "lighting": "raking side light for texture contrast",
            "composition": "diagonal split filling the frame, nozzle tip at the center seam",
            "text": "FIRST LAYER",
            "elements": ["nozzle tip", "glossy fused lines", "ridged gapped lines"],
            "style": "diagnostic macro photography",
            "mood": "precise, curious, high contrast",
            "prompt": "extreme macro photograph of a 3D printer first layer split diagonally: left half perfect flat glossy fused lines, right half defective round gapped tire-tread lines, a metal nozzle tip hovering at the center seam, raking side lighting that amplifies texture, dark workshop background, 9:16 vertical composition, ultra sharp, high detail, professional diagnostic photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "The First Layer Trick That Fixes 90% of Prints",
            "title_variations": [
                "Why Your First Layer Looks Like a Tire Tread",
                "First Layer Squish: The 0.02 mm Fix",
                "How to Nail the Perfect First Layer",
                "Fix Bed Adhesion With One Setting",
                "Read Your First Layer Like a Pro",
            ],
            "description": "Why does your print look terrible on the bottom? It's squish. Learn how z-offset controls the bond between molten filament and the build plate, how to read a glossy flattened first layer against round tire-tread lines, and how 0.02 mm z-offset steps get you a perfect foundation every time. The first layer carries the entire print, so getting squish right fixes adhesion, warping, and dimensional accuracy in one move. This 30-second short shows you exactly what to look for at the nozzle tip and what to change on the touchscreen, with real macro footage of good and bad first layers.",
            "hashtags": ["#3Dprinting", "#FirstLayer", "#3DPrintingTips", "#ZOffset"],
            "seo_keywords": [
                "first layer squish",
                "z offset calibration",
                "first layer not sticking",
                "3d print bed adhesion",
                "perfect first layer",
                "z offset too low",
                "first layer troubleshooting",
            ],
        },
        "fact_check": [
            "Z-offset adjustment steps of 0.02-0.05 mm are typical for FDM printers; values vary by printer and bed mesh quality.",
            "A glossy first layer indicates the line was flattened against the bed, increasing contact area; this is standard FDM practice.",
            "Ridging occurs when the nozzle drags through previously deposited plastic, which also risks nozzle and bed damage.",
            "Adhesion also depends on bed temperature, surface condition, and filament; squish alone is not sufficient.",
            "The '90% of prints' claim in the title is marketing framing, not a measured statistic.",
            "Units: z-offset is measured in millimeters (mm); common range -0.05 to -0.2 mm below the probe zero.",
        ],
    },
    # ======================================================================
    {
        "topic": "Gear Ratios",
        "core_question": "How do gear ratios trade speed for torque?",
        "learning_objective": "The viewer can compute a gear ratio from tooth counts and predict whether a meshing pair multiplies torque or speed.",
        "engineering_summary": "Two meshing gears rotate in opposite directions at speeds inversely proportional to their tooth counts. Ratio = driven teeth / driving teeth. A small driving gear turning a large driven gear multiplies torque and divides speed; the reverse trades torque for speed. Mechanical power (torque x angular speed) is conserved apart from friction losses, so gears never create power.",
        "real_world_application": "Vehicle transmissions use low ratios for hill climbing and high ratios for cruising; 3D printer extruders use geared drives (often 3:1 or 5:1) to gain extruder torque; planetary gearboxes in servos multiply torque in a compact package.",
        "common_misconceptions": [
            "Gears multiply power (they only trade speed for force)",
            "Bigger gear always means more torque output regardless of which gear is driven",
            "Gear ratio is set by diameter alone, not tooth count",
        ],
        "teaching_strategy": "Animate a marked tooth counting rotations to make the inverse relationship visible, then connect it to first gear vs fifth gear driving.",
        "script": "One gear spins twice, the other once. That's a two-to-one gear ratio, and it's a trade machine. Drive the small gear and you halve speed but double torque. Drive the big one and you double speed but lose torque. That's how a car climbs hills in first gear, then cruises at speed in fifth. Gears never create power - they trade it between speed and force. Next time you see a gearbox, you'll know the secret: ratio in, trade out.",
        "text_overlay": [
            "2:1 RATIO",
            "SMALL DRIVES BIG = MORE TORQUE",
            "FIRST GEAR = TORQUE",
            "FIFTH GEAR = SPEED",
            "POWER IN = POWER OUT (MINUS LOSS)",
        ],
        "scenes": [
            {
                "goal": "Hook: two gears meshing",
                "teaching_point": "Meshing teeth drive opposite rotation",
                "shot": "macro close-up of two meshing steel spur gears rotating",
                "motion": "slow-motion rotation of both gears",
                "lighting": "hard key light with brass reflections",
                "background": "machine shop, soft blur",
                "objects": ["steel spur gears", "shafts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of two meshing steel spur gears rotating in slow motion, machine shop background, hard key light with metallic reflections",
            },
            {
                "goal": "Show the 2:1 ratio",
                "teaching_point": "Tooth count sets the ratio: small gear spins twice per big gear revolution",
                "shot": "overhead macro on gears with one marked tooth",
                "motion": "marked tooth counts rotations as gears turn",
                "lighting": "even diffused lighting",
                "background": "dark workbench",
                "objects": ["gears with painted tooth marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "overhead macro photograph of two spur gears with one marked white tooth on each gear, even diffused lighting, dark workbench, technical photography",
            },
            {
                "goal": "Torque trade: hill climb",
                "teaching_point": "Small gear driving a big gear multiplies torque and divides speed",
                "shot": "medium shot of a car climbing a steep hill in slow motion",
                "motion": "slow-motion climb, wheels turning slowly",
                "lighting": "golden-hour side light",
                "background": "mountain road",
                "objects": ["car", "steep road"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a car climbing a steep mountain road in slow motion, golden-hour lighting, realistic automotive photography",
            },
            {
                "goal": "Speed trade: highway",
                "teaching_point": "Big gear driving a small gear multiplies speed and divides torque",
                "shot": "wide shot of a car cruising on a highway",
                "motion": "fast pan with motion streaks",
                "lighting": "bright daylight",
                "background": "open highway",
                "objects": ["car", "highway"],
                "transition": "cut",
                "duration": 5,
                "prompt": "wide photograph of a car cruising fast on an open highway, bright daylight, motion blur on the road, automotive photography",
            },
            {
                "goal": "Takeaway: the gearbox",
                "teaching_point": "Power is conserved minus friction; gears only rebalance speed and force",
                "shot": "medium hero shot of an open gearbox with turning shafts and gears",
                "motion": "slow orbit around the gearbox",
                "lighting": "studio key with rim light",
                "background": "dark studio",
                "objects": ["gearbox", "gears", "shafts"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of an open industrial gearbox with meshing gears and shafts, dark studio background, cinematic key light with rim, product photography",
            },
        ],
        "thumbnail": {
            "concept": "Two gears face-to-face, one marked tooth glowing with a ratio callout, giant-tooth vs small-tooth visual trade",
            "subject": "steel spur gears of different sizes meshing, large gear left, small gear right",
            "background": "dark machine shop blur",
            "angle": "low-angle macro",
            "lighting": "hard key with rim light",
            "composition": "gears filling the frame, ratio callout in the negative space",
            "text": "2:1 = ?",
            "elements": ["large gear", "small gear", "shafts", "marked tooth"],
            "style": "industrial macro photography",
            "mood": "curious, mechanical, bold",
            "prompt": "macro photograph of two meshing steel spur gears, one large and one small, filling the frame, hard key light with strong rim light, dark machine shop background, marked tooth on each gear, 9:16 vertical composition, ultra sharp metal detail, high contrast industrial photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Gears Never Create Power (They Trade It)",
            "title_variations": [
                "What a 2:1 Gear Ratio Actually Means",
                "How Gearboxes Trade Speed for Torque",
                "Gear Ratios Explained in 30 Seconds",
                "Why Your Car Needs First Gear",
                "The Gearbox Secret: Ratio In, Trade Out",
            ],
            "description": "How do gear ratios work? One gear spins twice, the other once - that's a 2:1 ratio. Small gear driving a big gear multiplies torque and divides speed. Big gear driving a small gear does the reverse. Gears never create power, they trade it between speed and force. Understand gearboxes, transmissions, and geared extruders with this 30-second mechanical engineering explainer.",
            "hashtags": ["#Engineering", "#Gears", "#MechanicalEngineering", "#HowItWorks"],
            "seo_keywords": [
                "gear ratio explained",
                "how gears work",
                "torque vs speed gears",
                "gear reduction",
                "first gear torque",
                "mechanical advantage gears",
                "transmission gear ratio",
            ],
        },
        "fact_check": [
            "Gear ratio equals driven teeth divided by driving teeth; speed ratio is the inverse of the tooth ratio.",
            "For an ideal (frictionless) gear pair, power in equals power out; real gears lose 1-3% per mesh depending on type and lubrication.",
            "A 2:1 reduction doubles output torque and halves output speed (ignoring losses).",
            "First gear in a typical car is roughly 3.5:1 reduction; fifth gear is often 1:1 or overdrive (below 1:1).",
            "Gears in contact rotate in opposite directions; idler gears only reverse direction, they do not change the ratio.",
            "Units: ratio is dimensionless; torque in N-m, angular speed in rad/s or rpm.",
        ],
    },
    # ======================================================================
    {
        "topic": "PLA vs PETG",
        "core_question": "When should I choose PETG over PLA?",
        "learning_objective": "The viewer can match material to application: PLA for decorative/low-load, PETG for mechanical and outdoor parts, and knows PETG needs drying.",
        "engineering_summary": "PLA is a brittle bioplastic with a low glass transition (~60 C), excellent printability, and poor impact and outdoor durability. PETG is a tough copolyester that resists impacts, chemicals, and UV better, at the cost of higher print temperature (230-250 C), slower cooling, and strong moisture sensitivity. Wet PETG hydrolyzes and prints cloudy and brittle.",
        "real_world_application": "PLA suits prototypes, display parts, and lithophanes; PETG suits functional brackets, outdoor mounts, and parts in contact with water or mild chemicals. Print farms switch to PETG for end-use parts while keeping PLA for fit-check prototyping.",
        "common_misconceptions": [
            "PETG is just stronger PLA (it's tougher, not always stiffer, and much harder to print cleanly)",
            "Wet filament looks wet (moisture damage shows as cloudy prints, popping, and brittleness)",
            "PETG sticks fine on bare glass (it can bond too well and damage the surface)",
        ],
        "teaching_strategy": "Anchor with a physical demo: snapping a PLA part vs bending a PETG part, then a moisture warning with a visibly cloudy wet sample.",
        "script": "PLA prints like a dream and snaps like a cracker. PETG is tougher, but it's picky: hotter, slower, stringier. The rule of thumb? Decorative? PLA. Anything that bends, carries load, or lives outdoors? PETG. Here's the catch: PETG loves moisture. Wet PETG prints cloudy and brittle, so dry it first. Same printer, different universe of parts. Choose the material for the job, not the hype.",
        "text_overlay": [
            "PLA: PRETTY, BRITTLE",
            "PETG: TOUGH, PICKY",
            "DECORATIVE = PLA",
            "LOAD = PETG",
            "DRY YOUR PETG",
        ],
        "scenes": [
            {
                "goal": "Hook: snap test",
                "teaching_point": "PLA is brittle; PETG deforms before breaking",
                "shot": "macro close-up of hands snapping a PLA part and bending a PETG part",
                "motion": "action cut between the two materials",
                "lighting": "warm workbench light",
                "background": "materials lab shelf blur",
                "objects": ["PLA test part", "PETG test part", "hands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a hand snapping a white PLA 3D printed part, warm workshop lighting, materials lab background",
            },
            {
                "goal": "Show PETG printing conditions",
                "teaching_point": "PETG needs 230-250 C, slower speeds, and tuned retraction",
                "shot": "medium shot of a printer extruding glossy PETG",
                "motion": "slow push-in on the hotend",
                "lighting": "neutral lab lighting",
                "background": "print lab",
                "objects": ["hotend", "glossy PETG part", "printer gantry"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer extruding glossy transparent PETG filament, neutral lab lighting, modern print lab background",
            },
            {
                "goal": "Application rule",
                "teaching_point": "Match material to load and environment",
                "shot": "split-screen: decorative vase (PLA) vs outdoor bracket (PETG) in rain",
                "motion": "cross-fade between the two",
                "lighting": "bright daylight on the bracket side",
                "background": "desk on one side, outdoor wall on the other",
                "objects": ["PLA vase", "PETG outdoor bracket", "water droplets"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printed bracket mounted outdoors with water droplets, bright daylight, realistic product photography",
            },
            {
                "goal": "Moisture warning",
                "teaching_point": "Wet PETG prints cloudy and brittle; dry it before use",
                "shot": "macro close-up of cloudy vs clear PETG printed samples",
                "motion": "slow pan between the two samples",
                "lighting": "soft side light showing cloudiness",
                "background": "neutral bench",
                "objects": ["cloudy PETG sample", "clear PETG sample", "drying box"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph comparing a cloudy brittle PETG printed sample against a clear glossy one, soft side lighting, neutral workbench, materials lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Choose the material for the job",
                "shot": "wide hero shot of a printer with both spools visible",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "PLA spool", "PETG spool"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printer with a PLA spool and a PETG spool beside it, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Snap-and-bend contrast: PLA part cracking in half, PETG part bending, split lighting warm vs cool",
            "subject": "white PLA part snapped in half next to a clear PETG part bending under force",
            "background": "materials lab bench, dark blur",
            "angle": "macro eye-level",
            "lighting": "warm light on PLA side, cool light on PETG side",
            "composition": "two halves split by a center seam, materials filling the frame",
            "text": "PLA vs PETG",
            "elements": ["snapped PLA part", "bent PETG part", "spool edges"],
            "style": "macro product photography",
            "mood": "decisive, tactile, contrasting",
            "prompt": "macro photograph of a snapped white PLA 3D printed part on the left and a clear PETG part bending on the right, warm lighting on the left half and cool lighting on the right half, materials lab bench, 9:16 vertical composition, ultra sharp, high contrast product photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PLA vs PETG: Pick the Right Material",
            "title_variations": [
                "Why PETG Beats PLA for Functional Parts",
                "PLA Snaps, PETG Bends: Choose Wisely",
                "Which Filament Should You Really Use?",
                "PETG vs PLA in 30 Seconds",
                "The Right Filament for Every Job",
            ],
            "description": "PLA or PETG - which filament should you use? PLA prints beautifully but snaps like a cracker, and its low glass transition temperature means it cannot handle heat or outdoor loads. PETG is tougher, bends before breaking, survives impacts and weather better, but needs 230-250 C, slower speeds, tuned retraction, and dry filament. Wet PETG hydrolyzes and prints cloudy and brittle. This 30-second engineering comparison anchors the decision rule: decorative goes PLA, anything that bends, carries load, or lives outdoors goes PETG, and drying the spool is non-negotiable either way.",
            "hashtags": ["#3Dprinting", "#PLAvsPETG", "#Filament", "#3DPrintingTips"],
            "seo_keywords": [
                "pla vs petg",
                "petg filament guide",
                "which filament to use",
                "petg print settings",
                "pla brittleness",
                "petg moisture",
                "functional 3d printed parts",
            ],
        },
        "fact_check": [
            "PLA glass transition is roughly 55-65 C; PETG roughly 80 C, giving PETG better heat resistance in service.",
            "Typical PETG print range is 230-250 C nozzle, 70-90 C bed; PLA is 190-220 C nozzle, 50-65 C bed.",
            "PETG is hygroscopic; absorbed moisture hydrolyzes the polymer at temperature, causing cloudy prints, popping, and reduced strength.",
            "PLA is stiffer (Young's modulus ~3.5 GPa) but far more brittle; PETG (~2.0-2.2 GPa) yields instead of cracking.",
            "PETG can adhere aggressively to bare glass and pull chips from it; a textured plate or release layer is commonly used.",
            "UV resistance of PETG is better than PLA but still limited; neither is a substitute for ASA for long outdoor life.",
            "Units: temperatures in degrees Celsius; modulus in GPa.",
        ],
    },
    # ======================================================================
    {
        "topic": "Retraction Settings",
        "core_question": "How does retraction stop stringing?",
        "learning_objective": "The viewer can set starting retraction values for their extruder type and knows the failure modes of over-retraction.",
        "engineering_summary": "Stringing happens when molten filament oozes from the nozzle during travel moves. Retraction pulls the filament backward in the hotend to relieve melt pressure, cutting the drip. Typical starting values: 4-6 mm at 30-45 mm/s for Bowden, 0.8-1.5 mm at 25-40 mm/s for direct drive. Excess retraction pulls melted material into the cold zone, causing clogs and restart gaps; too little leaves strings.",
        "real_world_application": "Retraction tuning is the standard first step for cosmetic quality on any FDM machine; print farms set per-material retraction profiles because PETG and flexible filaments behave differently.",
        "common_misconceptions": [
            "More retraction is always better (it causes clogs and gaps)",
            "Retraction speed doesn't matter (too slow creates blobs, too fast grinds filament)",
            "Stringing is a material defect (it is a melt-pressure problem at the nozzle)",
        ],
        "teaching_strategy": "Visualize the melt chamber with an animated cross-section: filament pulled back, drip cut, ooze stopped; then show over- and under-retraction failure prints.",
        "script": "Stringing isn't a material problem, it's a nozzle ooze problem. Molten plastic keeps leaking while the nozzle travels. Retraction yanks the filament backward to stop the drip. Start around four millimeters on Bowden, one millimeter direct drive. Too much retraction? Clogs and gaps. Too little? Spider webs. Add a small z-hop for sticky filaments. The goal isn't zero strings, it's a clean nozzle during travel. Tune it once, and your prints go from fuzzy to factory.",
        "text_overlay": [
            "OOZE = TRAVEL PROBLEM",
            "PULL BACK = STOP DRIP",
            "BOWDEN: ~4 mm",
            "DIRECT: ~1 mm",
            "BALANCE, NOT MAX",
        ],
        "scenes": [
            {
                "goal": "Hook: stringy print",
                "teaching_point": "Strings appear during travel moves, not on the part itself",
                "shot": "macro close-up of a stringy 3D printed part with spider webs",
                "motion": "slow push-in on the webs",
                "lighting": "raking light to show thin strands",
                "background": "dark workshop blur",
                "objects": ["stringy printed part", "fine filament webs"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part covered in fine filament strings, raking light revealing thin strands, dark workshop background",
            },
            {
                "goal": "Explain ooze",
                "teaching_point": "Melt pressure at the nozzle leaks during travel",
                "shot": "animated-style close-up of a hotend cross-section with filament oozing",
                "motion": "melt chamber pressure visualized as it drips",
                "lighting": "soft studio light",
                "background": "dark lab",
                "objects": ["hotend cutaway", "filament", "nozzle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hotend cross-section cutaway showing filament and nozzle, dark engineering lab background, soft studio lighting, technical visualization",
            },
            {
                "goal": "Show the retraction action",
                "teaching_point": "Pulling filament back relieves melt pressure",
                "shot": "macro shot of filament being pulled back through the extruder",
                "motion": "slow pull-back motion, repeated",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["extruder", "filament", "hotend"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of filament being retracted through a dual-gear extruder, bright task lighting, 3D printer in a modern lab background",
            },
            {
                "goal": "Show failure modes",
                "teaching_point": "Over-retraction clogs and creates gaps; under-retraction strings",
                "shot": "split-screen: clogged nozzle print with gaps vs stringy print",
                "motion": "wipe between the two",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["print with gaps", "print with strings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two 3D printed test parts side by side, one with gaps and one with strings, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Tune retraction once per material and printer",
                "shot": "wide hero shot of a clean printed part on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean printed part", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flawless clean 3D printed part on the build plate, dark engineering lab, cinematic key light with rim",
            },
        ],
        "thumbnail": {
            "concept": "Clean vs stringy printed part, a hotend cutaway with an arrow showing filament pulled back, and a balance-meter overlay",
            "subject": "3D printed part half clean, half stringy, with a hotend cross-section beside it",
            "background": "dark lab blur",
            "angle": "macro eye-level",
            "lighting": "hard key with rim",
            "composition": "diagonal split between clean and stringy halves, hotend cutaway inset",
            "text": "RETRACTION",
            "elements": ["stringy part", "clean part", "hotend cutaway", "filament arrow"],
            "style": "diagnostic macro photography",
            "mood": "technical, corrective, sharp",
            "prompt": "macro photograph of a 3D printed part split diagonally, left half clean and smooth, right half covered in filament strings, a hotend cross-section cutaway in the corner, hard key light with rim, dark engineering lab, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stop Stringing With the Right Retraction",
            "title_variations": [
                "Why Your Print Has Spider Webs",
                "Retraction Tuning: Bowden vs Direct Drive",
                "The One Setting That Kills Stringing",
                "Fix Ooze at the Nozzle",
                "Stringing Isn't a Material Problem",
            ],
            "description": "Stringing isn't a material problem, it's a nozzle ooze problem: molten plastic leaks while the nozzle travels, and retraction pulls the filament back to stop the drip. Learn realistic starting values - about 4-6 mm for Bowden extruders and 0.8-1.5 mm for direct drive - plus why too much retraction causes clogs and restart gaps, and why a small z-hop helps with sticky filaments. This 30-second tuning guide shows the melt-chamber mechanics behind the fix, the failure modes on both sides of the dial, and the balance that gives factory-clean surfaces instead of spider webs.",
            "hashtags": ["#3Dprinting", "#Stringing", "#Retraction", "#3DPrintingTips"],
            "seo_keywords": [
                "retraction settings",
                "fix stringing",
                "retraction distance bowden",
                "retraction direct drive",
                "3d print stringing fix",
                "retraction speed",
                "nozzle ooze",
            ],
        },
        "fact_check": [
            "Typical Bowden retraction starts at 4-6 mm at 30-45 mm/s; direct drive at 0.8-1.5 mm at 25-40 mm/s. Values are starting points, not absolutes.",
            "Retraction pulls filament from the melt zone, lowering pressure; a too-large retraction can pull molten plastic into the cold zone and clog.",
            "Restart gaps appear when retraction is so high the nozzle runs dry at the start of the next segment.",
            "Z-hop lifts the nozzle during travel to clear already-printed features, complementing but not replacing retraction.",
            "Flexible filaments often need near-zero retraction with tuned speed to avoid grinding.",
            "Units: retraction distance in millimeters (mm), speed in millimeters per second (mm/s).",
        ],
    },
    # ======================================================================
    {
        "topic": "Overhang Angles",
        "core_question": "At what angle do overhangs need support?",
        "learning_objective": "The viewer can identify the 45-degree rule, explain why bridges behave differently, and design self-supporting geometry.",
        "engineering_summary": "FDM prints each layer on the layer below; when a layer extends beyond the previous one, deposited plastic sags until it exceeds the material's ability to hold its bead shape. In practice, 45 degrees from vertical (i.e., 45-degree surface inclination) prints reliably on most machines, while steeper overhangs need supports or tuned bridges. A bridge spans a gap by stretching filament between two supported edges and can often print flat without support over short spans.",
        "real_world_application": "CAD models for printing set chamfers at 45 degrees and below, split parts along the angle, or orient parts so features align with self-supporting directions; rocket and bracket designs use 45-degree conical transitions to print support-free.",
        "common_misconceptions": [
            "The 45-degree rule is a hard law (it is a practical guideline that shifts with layer height, speed, and cooling)",
            "Bridges are impossible without supports (short spans bridge cleanly)",
            "Steeper is fine if speed is low (cooling and layer time matter more)",
        ],
        "teaching_strategy": "Animate a cross-section of layer steps at 30, 45, and 60 degrees showing where the bead loses support, then demonstrate a clean bridge.",
        "script": "Why does your print droop on one side? Gravity. Every layer prints on the layer below, and if that floor isn't underneath, plastic sags. The magic number is 45 degrees: past that, overhangs need help. Under 45, layers support themselves. But bridges are the exception: a straight span with nothing below can work, because filament pulls tight between two edges. Design under 45, support what you can't, and the slicer becomes your friend, not your enemy.",
        "text_overlay": [
            "45° = SELF-SUPPORTING",
            "STEEPER = SUPPORTS",
            "BRIDGES: TENSION NOT SAG",
            "DESIGN THE ANGLE",
        ],
        "scenes": [
            {
                "goal": "Hook: drooping overhang",
                "teaching_point": "Overhangs sag because plastic prints on air",
                "shot": "macro close-up of a sagging overhang on a printed part",
                "motion": "slow push-in on the drooping edge",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["printed part with sagging overhang"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part with a sagging drooping overhang edge, raking side light, dark workshop background",
            },
            {
                "goal": "Show the angle gradient",
                "teaching_point": "Layer steps at 30, 45, and 60 degrees show where support runs out",
                "shot": "overhead macro of a calibration overhang test with angled steps",
                "motion": "slow pan across the steps",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["overhang calibration print", "angled steps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "overhead macro photograph of a 3D printed overhang calibration test with stepped angles, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Bridges as the exception",
                "teaching_point": "Filament stretches between two edges and holds its shape over short spans",
                "shot": "macro shot of a clean bridge spanning two printed towers",
                "motion": "slow dolly under the bridge",
                "lighting": "bright task light",
                "background": "dark blur",
                "objects": ["printed bridge", "two towers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a clean 3D printed bridge spanning between two towers, bright task lighting, dark background, precise engineering detail",
            },
            {
                "goal": "Design rule",
                "teaching_point": "Chamfers at or below 45 degrees print clean without supports",
                "shot": "CAD viewport orbit of a part with 45-degree chamfers",
                "motion": "orbiting turntable around the model",
                "lighting": "clean viewport lighting",
                "background": "dark CAD viewport",
                "objects": ["CAD model", "45-degree chamfers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a CAD viewport showing a 3D model with clean 45-degree chamfers on a dark screen, modern design studio",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Geometry decides whether the slicer needs help",
                "shot": "wide hero shot of a complex part printing cleanly with a chamfered transition",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["chamfered printed part", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printed part with clean chamfered edges on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Angled cross-section stepping from 30 to 60 degrees with a glowing 45-degree line, one side perfect one side sagging",
            "subject": "3D printed overhang test wedge with three stepped angles",
            "background": "dark workshop blur",
            "angle": "macro side profile",
            "lighting": "raking side light",
            "composition": "wedge crossing the frame diagonally, angle callouts along the edge",
            "text": "45° RULE",
            "elements": ["overhang wedge", "step edges", "angle markers"],
            "style": "diagnostic macro photography",
            "mood": "geometric, instructive, clean",
            "prompt": "macro photograph of a 3D printed overhang test wedge with three stepped angles at 30, 45, and 60 degrees, each step showing a different surface quality from clean to sagging, raking side light that reveals every layer line, dark workshop background with soft blur, 9:16 vertical composition, ultra sharp layer detail, professional diagnostic engineering photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, rounded objects",
        },
        "seo": {
            "title": "The 45-Degree Rule for Overhangs",
            "title_variations": [
                "Why Overhangs Sag (And How to Fix Them)",
                "Overhang Angles: Support or No Support?",
                "Design Parts That Print Without Supports",
                "Bridges vs Overhangs in 3D Printing",
                "The Angle That Saves Your Prints",
            ],
            "description": "Why do overhangs droop and sag? Because every FDM layer prints on the layer below it, and past about 45 degrees the plastic runs out of support. This short explains the 45-degree rule, why short bridges are the exception that prints clean because filament stretches taut between two edges, and how chamfers and tapers under 45 degrees let you design parts that need no supports at all. If you design or print functional parts, this is the geometry rule that saves the most failed prints.",
            "hashtags": ["#3Dprinting", "#Overhang", "#DesignForPrinting", "#3DPrintingTips"],
            "seo_keywords": [
                "overhang angle 45 degrees",
                "3d print overhang sagging",
                "design for 3d printing",
                "self supporting overhangs",
                "bridging 3d print",
                "chamfer design print",
                "no supports design",
            ],
        },
        "fact_check": [
            "The 45-degree guideline assumes typical layer heights (0.2 mm) and adequate cooling; low layer heights and high cooling can push the practical limit slightly higher.",
            "Bridges rely on the filament's surface tension and viscosity pulling it taut between edges; maximum clean bridge length is typically 10-15 mm for most materials, longer with tuned bridge settings.",
            "Overhang quality degrades with increasing angle and speed; minimum layer time and fan speed are the controlling cooling parameters.",
            "Support-free design uses chamfers and tapers at or below 45 degrees, which also improves layer alignment and part strength.",
            "Units: angles in degrees; bridge span in millimeters.",
        ],
    },
    # ======================================================================
    {
        "topic": "Stepper Motors Deep Dive",
        "core_question": "How do stepper motors control position without feedback?",
        "learning_objective": "The viewer understands full steps, microstepping, open-loop positioning, and why skipped steps cause layer shifts.",
        "engineering_summary": "A stepper motor moves in discrete angular steps set by energizing stator coil pairs. Standard motors do 200 full steps per revolution (1.8 degrees per step). Drivers microstep by proportioning coil currents, dividing each full step into fractions (e.g., 16 or 64) for smoother motion and finer resolution. The system is open-loop: without an encoder, the controller assumes every commanded step was completed, so a skipped step produces a permanent positional error, visible as a shifted layer.",
        "real_world_application": "3D printers, CNC machines, and camera sliders use open-loop steppers for repeatable low-cost positioning; printers with input shaping pair high microstepping with current tuning to avoid skipped steps under resonance.",
        "common_misconceptions": [
            "Microstepping increases torque (it reduces effective step torque per step at high divisions)",
            "Steppers are silent motors (they hum; drivers and microstepping reduce the noise)",
            "Open-loop means no errors possible (it means errors are not detected)",
        ],
        "teaching_strategy": "Animate the stator coil sequence stepping the rotor, then show a skipped step propagating into a shifted layer to make the open-loop consequence visible.",
        "script": "Your printer moves in invisible jumps. A stepper motor turns in fixed steps: 200 per full revolution. The driver splits each step into microsteps, so the nozzle glides instead of lurching. Position is open-loop: the motor assumes it made every step. Skip one under load, and the layer shifts, and the error never corrects itself. That's why torque matters, and why modern drivers run quietly at higher microstepping. Every print path is just a long list of tiny steps.",
        "text_overlay": [
            "200 STEPS / REVOLUTION",
            "1.8° PER STEP",
            "MICROSTEPS = SMOOTH",
            "OPEN-LOOP = TRUST",
            "SKIP = PERMANENT ERROR",
        ],
        "scenes": [
            {
                "goal": "Hook: a shifted layer",
                "teaching_point": "A skipped step shows up as a permanent layer shift",
                "shot": "macro close-up of a printed part with a shifted layer",
                "motion": "slow push-in on the shift line",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["printed part with shifted layer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part with a visibly shifted layer line, raking side light, dark workshop background",
            },
            {
                "goal": "Show the stepping principle",
                "teaching_point": "Coil pairs energize in sequence, rotating the rotor in discrete steps",
                "shot": "macro shot of an open stepper motor with exposed stator and rotor",
                "motion": "slow rotation as coils sequence",
                "lighting": "soft studio light",
                "background": "electronics bench blur",
                "objects": ["stepper motor", "stator coils", "rotor"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of an open NEMA 17 stepper motor with exposed stator coils and rotor, soft studio lighting, electronics bench background",
            },
            {
                "goal": "Explain microstepping",
                "teaching_point": "Drivers divide each full step to smooth motion",
                "shot": "medium shot of a stepper driver board with a motor attached",
                "motion": "slow push-in on the driver board",
                "lighting": "bench task light",
                "background": "electronics bench",
                "objects": ["stepper driver board", "motor", "wiring"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stepper motor driver board connected to a stepper motor on an electronics bench, task lighting, real components",
            },
            {
                "goal": "Open-loop consequence",
                "teaching_point": "No encoder means a missed step is never corrected",
                "shot": "graphic-style shot of a gantry axis with a marked skipped step",
                "motion": "axis moves, position error grows and stays",
                "lighting": "neutral lab light",
                "background": "printer in lab",
                "objects": ["printer gantry", "axis belt"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer XY gantry with exposed belts and pulleys, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Torque headroom and good drivers prevent skipped steps",
                "shot": "wide hero shot of a printer printing smoothly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "smooth printing part"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer printing a part smoothly, dark engineering lab, cinematic key light with rim",
            },
        ],
        "thumbnail": {
            "concept": "Open stepper motor with 200-step dial and a split printed part: smooth side vs shifted side",
            "subject": "NEMA 17 stepper motor with exposed rotor, a printed part beside it with one shifted layer",
            "background": "dark electronics bench blur",
            "angle": "low-angle macro",
            "lighting": "hard key with rim",
            "composition": "motor dominating the left, shifted print on the right",
            "text": "200 STEPS",
            "elements": ["stepper motor", "stator coils", "shifted layer print"],
            "style": "technical macro photography",
            "mood": "precise, mechanical, revealing",
            "prompt": "macro photograph of an open NEMA 17 stepper motor with exposed coils on the left and a 3D printed part with a shifted layer on the right, hard key light with rim, dark electronics bench, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "How Stepper Motors Move Your Printer",
            "title_variations": [
                "Stepper Motors: 200 Steps Per Revolution",
                "Why Skipped Steps Shift Your Print",
                "Microstepping Explained in 30 Seconds",
                "Open-Loop Motion: What Could Go Wrong?",
                "The Motor Inside Every 3D Printer",
            ],
            "description": "How do stepper motors work? Standard hybrid steppers make exactly 200 full steps per revolution - 1.8 degrees each - and the driver microsteps between them so the nozzle glides instead of lurching. The system is open-loop: the controller trusts that every commanded step was completed. That trust is why a skipped step under load becomes a permanent layer shift that never corrects itself. This short explains the coil sequencing, the role of drivers like the TMC2209, and why torque headroom prevents the most common printer failure.",
            "hashtags": ["#3Dprinting", "#StepperMotor", "#Electronics", "#Engineering"],
            "seo_keywords": [
                "stepper motor how it works",
                "microstepping explained",
                "layer shift stepper motor",
                "open loop positioning",
                "nema 17 motor",
                "stepper driver",
                "3d printer stepper",
            ],
        },
        "fact_check": [
            "Standard hybrid steppers provide 200 full steps per revolution, i.e., 1.8 degrees per step; 400-step (0.9 degree) variants exist.",
            "Microstepping divides each full step by proportioning coil currents; common divisions are 8, 16, 32, 64.",
            "Position accuracy at rest is bounded by detent and holding torque; at high microstep counts, step size uniformity degrades.",
            "Open-loop control means no feedback; a skipped step creates a permanent positional error until homing.",
            "Stepper torque falls with speed; resonance and missed steps typically occur near the torque curve knee or under acceleration.",
            "Units: steps per revolution (dimensionless), angle in degrees, torque in N-cm.",
        ],
    },
    # ======================================================================
    {
        "topic": "Stress vs Strain",
        "core_question": "What is the difference between stress and strain?",
        "learning_objective": "The viewer can define stress and strain, read a stress-strain curve, and identify the yield point.",
        "engineering_summary": "Stress is force per unit area (load normalized by cross-section); strain is dimensionless deformation (change in length divided by original length). The stress-strain curve maps a material's response: a linear elastic region obeying Hooke's law, a yield point where permanent deformation begins, strain hardening, necking, and finally fracture. Engineers size parts to remain in the elastic region with a safety factor against yield.",
        "real_world_application": "Bridges, pressure vessels, and printed brackets are designed so service loads stay below yield; a paperclip bending past its yield point shows exactly why plastic deformation is permanent.",
        "common_misconceptions": [
            "Stress and strain are the same thing (stress is the cause, strain is the effect)",
            "A part is fine as long as it hasn't broken (yield happens long before fracture and permanently deforms the part)",
            "Stronger material is always stiffer (strength and stiffness are different properties)",
        ],
        "teaching_strategy": "Use a paperclip as the mental model: pull it, measure the stretch (strain), feel the fight (stress), then bend it past yield and show it never straightens.",
        "script": "Stretch a paperclip and it fights back. That's stress. How much it stretches? That's strain. Stress is force divided by area; strain is stretch divided by length. Together they draw the stress-strain curve: straight at first, elastic, then bending over at the yield point, where damage becomes permanent. Pull past that and it necks, then snaps. Engineers design parts to live in the straight region, far from the bend. Stress is the push. Strain is the give. The curve is the whole story.",
        "text_overlay": [
            "STRESS = FORCE / AREA",
            "STRAIN = STRETCH / LENGTH",
            "YIELD = PERMANENT",
            "DESIGN IN THE STRAIGHT REGION",
        ],
        "scenes": [
            {
                "goal": "Hook: the paperclip",
                "teaching_point": "Pulling a clip shows stress (fight) and strain (stretch)",
                "shot": "macro close-up of hands stretching a paperclip",
                "motion": "slow pull and release",
                "lighting": "bright workbench light",
                "background": "physics lab bench blur",
                "objects": ["paperclip", "hands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of hands stretching a steel paperclip on a physics lab bench, bright even lighting, clean lab background",
            },
            {
                "goal": "Define both quantities",
                "teaching_point": "Stress normalizes force by area; strain normalizes stretch by length",
                "shot": "clean lab shot of a tensile test specimen in a small test frame",
                "motion": "slow tension pull with scale readouts",
                "lighting": "even diffused light",
                "background": "minimal physics lab",
                "objects": ["tensile specimen", "test frame", "scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a steel tensile test specimen in a small mechanical test frame, even diffused lighting, minimal physics laboratory",
            },
            {
                "goal": "The curve",
                "teaching_point": "Elastic region, yield point, strain hardening, necking, fracture",
                "shot": "graphic-style shot of a stress-strain curve over a specimen",
                "motion": "trace the curve as the specimen is pulled",
                "lighting": "clean viewport lighting",
                "background": "dark viewport",
                "objects": ["stress-strain curve", "specimen illustration"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stress-strain curve diagram displayed over a tensile specimen on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Yield in the real world",
                "teaching_point": "Bend a clip past yield and it never straightens",
                "shot": "macro shot of a bent paperclip that stays bent",
                "motion": "bend, release, hold the permanent bend",
                "lighting": "warm workbench light",
                "background": "lab bench blur",
                "objects": ["bent paperclip"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a permanently bent steel paperclip on a lab bench, warm workbench lighting, shallow depth of field",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Engineers keep service loads in the elastic region with a safety factor",
                "shot": "wide hero shot of a steel bridge deck in daylight",
                "motion": "slow pan along the structure",
                "lighting": "bright daylight",
                "background": "city skyline",
                "objects": ["steel bridge", "structural beams"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of a steel bridge with structural beams in bright daylight, engineering photography, clear sky",
            },
        ],
        "thumbnail": {
            "concept": "Bent paperclip morphing into a stress-strain curve with the yield point marked",
            "subject": "steel paperclip bent at a sharp angle on a printed curve backdrop",
            "background": "dark lab bench blur",
            "angle": "macro eye-level",
            "lighting": "hard key with rim",
            "composition": "paperclip crossing the frame diagonally with the curve behind it",
            "text": "STRESS ≠ STRAIN",
            "elements": ["bent paperclip", "stress-strain curve", "yield marker"],
            "style": "macro technical photography",
            "mood": "revelatory, precise, simple",
            "prompt": "macro photograph of a bent steel paperclip lying over a printed stress-strain curve diagram with the yield point marked, hard key light with a strong rim light on the metal, dark lab bench background with soft blur, 9:16 vertical composition, ultra sharp focus on the wire bend and the curve axis, high contrast professional technical photography",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, rulers",
        },
        "seo": {
            "title": "Stress vs Strain: The Whole Story",
            "title_variations": [
                "The Stress-Strain Curve in 30 Seconds",
                "Why a Bent Paperclip Never Straightens",
                "Stress Is the Push, Strain Is the Give",
                "How Engineers Read Materials",
                "Yield Point Explained Simply",
            ],
            "description": "What's the difference between stress and strain? Stress is force divided by area, the push; strain is stretch divided by length, the give. Together they draw the stress-strain curve: a straight elastic region obeying Hooke's law, a yield point where damage becomes permanent, then necking and fracture. That's why a bent paperclip never straightens and why engineers size every bridge and bracket to live in the straight region with a safety factor. Understand materials the way engineers do, in 30 seconds.",
            "hashtags": ["#Engineering", "#Physics", "#MaterialsScience", "#HowItWorks"],
            "seo_keywords": [
                "stress vs strain",
                "stress strain curve explained",
                "yield point",
                "hooke's law",
                "material strength basics",
                "elastic deformation",
                "engineering mechanics",
            ],
        },
        "fact_check": [
            "Engineering stress = force / original cross-sectional area (MPa); engineering strain = change in length / original length (dimensionless).",
            "The elastic region obeys Hooke's law: stress = E x strain, where E is Young's modulus.",
            "Yield strength marks the onset of plastic (permanent) deformation; ultimate tensile strength is the maximum stress before necking.",
            "Necking is a local reduction of cross-section that precedes ductile fracture.",
            "The paperclip example is valid: bending steel wire past yield produces permanent deformation because dislocation motion is irreversible at room temperature.",
            "Units: stress in MPa (N/mm^2); strain dimensionless; E in GPa.",
        ],
    },
    # ======================================================================
    {
        "topic": "Injection Molding",
        "core_question": "Why is injection molding so fast and so expensive?",
        "learning_objective": "The viewer can explain the molding cycle and why the tooling cost forces high production volumes.",
        "engineering_summary": "Injection molding melts polymer pellets and injects them under high pressure (thousands of psi) into a closed steel mold cavity. The part cools, the mold opens along the parting line, ejector pins push the part out, and the cycle repeats in seconds. The mold is precision-machined steel costing tens of thousands of dollars, so per-part cost collapses only at high volumes. Break-even analysis decides when a part should be molded instead of printed or machined.",
        "real_world_application": "Phone cases, bottle caps, and automotive clips are molded at millions per year; 3D printing or CNC is used for low volumes and fit checks because there is no tooling cost.",
        "common_misconceptions": [
            "Molding is always cheaper (tooling dominates until volume pays it back)",
            "Molded parts are weaker than printed parts (they are typically stronger with no layer interfaces)",
            "Any geometry can be molded (undercuts need slides, and draft angles are mandatory)",
        ],
        "teaching_strategy": "Show one molded part next to its printed equivalent with a clock: 4 seconds vs 40 minutes, then reveal the mold cost to explain the volume game.",
        "script": "Your printed part took forty minutes. This cup took four seconds. Injection molding melts plastic and blasts it into a steel cavity under thousands of pounds per square inch. It cools, the mold splits, and the part pops out. The catch? The mold costs tens of thousands of dollars. So molding is a volume game: printed parts for ten, molded parts for a million. That's why your phone case costs a dollar and a printed one costs ten. Speed has a price.",
        "text_overlay": [
            "4 SECONDS vs 40 MINUTES",
            "STEEL CAVITY + PRESSURE",
            "TOOLING: $$$",
            "VOLUME PAYS IT BACK",
        ],
        "scenes": [
            {
                "goal": "Hook: speed contrast",
                "teaching_point": "A molded cup takes seconds; a printed one takes minutes",
                "shot": "split-screen: injection molding machine cycle vs 3D printer with clock",
                "motion": "cross-fade between the two processes",
                "lighting": "bright factory light",
                "background": "factory floor on one side, print lab on the other",
                "objects": ["injection molding machine", "3D printer", "molded cup", "printed cup"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an injection molding machine in a bright factory, industrial documentary style, realistic machine detail",
            },
            {
                "goal": "Show the cycle",
                "teaching_point": "Melt, inject under pressure, cool, eject",
                "shot": "macro close-up of the mold opening and ejecting a part",
                "motion": "cycle loop: clamp, inject, cool, open, eject",
                "lighting": "high-bay industrial light",
                "background": "molding cell",
                "objects": ["steel mold", "ejected part", "ejector pins"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a steel injection mold opening with a plastic part being ejected, high-bay industrial lighting, realistic factory photography",
            },
            {
                "goal": "Reveal the tooling cost",
                "teaching_point": "Precision steel molds cost tens of thousands of dollars",
                "shot": "medium shot of a machined steel mold half on a workbench",
                "motion": "slow orbit around the mold",
                "lighting": "workshop key light",
                "background": "toolroom blur",
                "objects": ["steel mold half", "cavity detail"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a precision-machined steel injection mold half on a toolroom workbench, workshop key lighting, realistic machining detail",
            },
            {
                "goal": "The volume game",
                "teaching_point": "Per-part cost collapses only at high volumes",
                "shot": "wide shot of molded phone cases stacked in production",
                "motion": "slow pan across the stack",
                "lighting": "bright daylight",
                "background": "packaging line",
                "objects": ["molded phone cases", "packaging"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of stacks of molded plastic phone cases on a packaging line, bright daylight, industrial photography",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Choose the process by volume and speed needs",
                "shot": "wide hero shot of a molded part and a printed part side by side",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["molded cup", "printed cup"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a glossy injection molded cup next to a layered 3D printed cup, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Glossy molded cup vs layered printed cup, a clock and a dollar sign in the corners, steel mold behind",
            "subject": "injection molded cup next to a 3D printed cup, steel mold half in the background",
            "background": "dark factory blur",
            "angle": "slightly low macro",
            "lighting": "hard key with rim",
            "composition": "two cups mirrored left-right, mold behind center",
            "text": "4s vs 40min",
            "elements": ["molded cup", "printed cup", "steel mold"],
            "style": "industrial product photography",
            "mood": "comparative, fast, revealing",
            "prompt": "photograph of a glossy injection molded plastic cup on the left and a layered 3D printed cup on the right, a machined steel mold half behind them, hard key light with rim, dark factory background, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Why Injection Molding Is So Fast",
            "title_variations": [
                "Injection Molding vs 3D Printing",
                "The 4-Second Cup (And the Catch)",
                "How Molded Parts Are Made",
                "Why Molds Cost Tens of Thousands",
                "When Printing Loses to Molding",
            ],
            "description": "Injection molding makes a plastic cup in four seconds: pellets are melted and blasted into a precision steel cavity under thousands of psi, the part cools, the mold splits along the parting line, and ejector pins pop it out. The catch is the tool itself - a precision-machined steel mold that costs tens of thousands of dollars. That is why the process only wins at volume: printed parts for ten, molded parts for a million. Learn the molding cycle, the break-even logic, and why manufacturers choose each process.",
            "hashtags": ["#Manufacturing", "#InjectionMolding", "#Engineering", "#HowItWorks"],
            "seo_keywords": [
                "injection molding explained",
                "injection molding vs 3d printing",
                "why molds cost so much",
                "injection molding cycle",
                "plastic part manufacturing",
                "tooling cost",
                "molding vs printing",
            ],
        },
        "fact_check": [
            "Typical injection pressures are 5,000-30,000 psi depending on material and part geometry.",
            "Cycle times range from seconds for thin-wall parts to minutes for thick sections; a thin cup is a multi-second cycle.",
            "Mold tooling for simple parts starts around $10k-$50k and rises steeply with complexity, slides, and multi-cavity designs.",
            "Molded parts are generally stronger than FDM printed parts because there are no layer interfaces.",
            "Draft angles (1-2 degrees typical) and parting-line design are mandatory; undercuts require slides or lifters.",
            "Break-even volume between molding and printing depends on tooling cost, per-part cost, and machine rates; for the cup example it is in the tens of thousands of units.",
            "Units: pressure in psi (or MPa in SI); 1 MPa = 145 psi.",
        ],
    },
]