"""Batch 30: tuning order, benchy, retraction, belts, spaghetti, infill, fan cooling, input shaping."""

CURATED = [
    # ======================================================================
    {
        "topic": "Tuning Order",
        "core_question": "What order should you calibrate your printer?",
        "learning_objective": "The viewer understands a sane calibration sequence.",
        "engineering_summary": "Calibration has an order, because each step depends on the last: mechanical first, then extrusion, then quality. Check the frame and belts, level the bed, then set extrusion flow and temperature, and only then chase retraction and ringing. Skip a step and the next test is meaningless, because a loose belt hides a stringing problem. The foundation comes first. Tune the base, then the details.",
        "real_world_application": "Every printer setup follows the same sequence of dependent checks.",
        "common_misconceptions": [
            "Any order works (each test needs the last one clean)",
            "Speed settings are first (mechanics and flow come first)",
            "One test fixes everything (each test isolates one variable)",
        ],
        "teaching_strategy": "Walk a print through the sequence and show each test's dependency.",
        "script": "Calibration has an order, because each step depends on the last: mechanical first, then extrusion, then quality. Check the frame and belts, level the bed, then set extrusion flow and temperature, and only then chase retraction and ringing. Skip a step and the next test is meaningless, because a loose belt hides a stringing problem. The foundation comes first. Tune the base, then the details.",
        "text_overlay": [
            "MECHANICAL, EXTRUSION, QUALITY",
            "EACH TEST NEEDS THE LAST",
            "A LOOSE BELT HIDES STRINGING",
            "TUNE THE BASE, THEN DETAILS",
        ],
        "scenes": [
            {
                "goal": "Hook: the jumbled test",
                "teaching_point": "One variable at a time",
                "shot": "medium shot of a printer surrounded by test prints",
                "motion": "camera scans the failed tests",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer", "test prints", "failed parts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printer surrounded by test prints, neutral lab lighting, print lab",
            },
            {
                "goal": "The base",
                "teaching_point": "Frame, belts, bed first",
                "shot": "medium shot of a frame and belts being checked",
                "motion": "wrench and gauge check the machine",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["frame check", "belt tension", "bed level"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of frame and belt checks on a printer, neutral lab lighting, print lab",
            },
            {
                "goal": "The flow",
                "teaching_point": "Extrusion and temperature next",
                "shot": "medium shot of a flow test part being measured",
                "motion": "caliper reads the walls",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["flow test", "caliper", "wall reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a flow test part being measured with a caliper, neutral lab lighting, workbench",
            },
            {
                "goal": "The details",
                "teaching_point": "Retraction and ringing last",
                "shot": "medium shot of a retraction tower and ringing test printing",
                "motion": "detail tests run clean",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["retraction tower", "ringing test", "clean print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a retraction tower and ringing test printing, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The foundation comes first",
                "shot": "wide hero shot of a tuned printer with its test parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["tuned printer", "test parts", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tuned printer with its test parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A calibration sequence ladder from frame to retraction",
            "subject": "printer tuning order",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "printer center, sequence steps up",
            "text": "TUNE THE BASE, THEN DETAILS",
            "elements": ["printer", "sequence steps", "test parts"],
            "style": "geometry studio photography",
            "mood": "ordered, dependent, tuned",
            "prompt": "photograph of a printer with a calibration sequence ladder from frame to retraction and test parts, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Tuning Order: Tune the Base, Then Details",
            "title_variations": [
                "What Order Should I Calibrate",
                "Printer Calibration Order",
                "First Calibration Steps",
                "Tuning Sequence 3D Printer",
                "Calibrate Printer Basics",
            ],
            "description": "Calibration has an order because each step depends on the last: mechanical first, then extrusion, then quality. Check the frame and belts, level the bed, set flow and temperature, and only then chase retraction and ringing, because a loose belt hides a stringing problem. This short walks the sequence and shows why skipping a step makes the next test meaningless. Tune the base, then the details.",
            "hashtags": ["#Calibration", "#3DPrinting", "#Tuning", "#PrinterSetup"],
            "seo_keywords": [
                "what order should I calibrate",
                "printer calibration order",
                "first calibration steps",
                "tuning sequence printer",
                "flow before retraction",
                "belt check first",
                "calibrate 3d printer",
            ],
        },
        "fact_check": [
            "Calibration has a dependency order.",
            "Mechanics come before extrusion.",
            "Quality tests come last.",
            "Skipping steps hides problems.",
            "Each test isolates one variable.",
        ],
    },
    {
        "topic": "Benchy as Diagnostic",
        "core_question": "What can one little boat tell you?",
        "learning_objective": "The viewer understands the Benchy print as a full diagnostic.",
        "engineering_summary": "The Benchy is a tiny boat that packs every printing challenge into one hull: overhangs, bridges, small details, and smooth surfaces all in one part. Each feature is a test: the hull checks layer quality, the cabin windows check bridges, the bow checks overhangs, and the text checks detail. Compare benchies across settings changes and the differences point to the fault. One boat, every question.",
        "real_world_application": "The Benchy is the standard baseline print for comparing settings.",
        "common_misconceptions": [
            "Benchy is a toy (it is a full test suite)",
            "A clean Benchy means perfect (it covers common faults, not all)",
            "Any model works (Benchy is calibrated by its known features)",
        ],
        "teaching_strategy": "Point at each Benchy feature and name the fault it exposes.",
        "script": "The Benchy is a tiny boat that packs every printing challenge into one hull: overhangs, bridges, small details, and smooth surfaces all in one part. Each feature is a test: the hull checks layer quality, the cabin windows check bridges, the bow checks overhangs, and the text checks detail. Compare benchies across settings changes and the differences point to the fault. One boat, every question.",
        "text_overlay": [
            "A TEST SUITE IN ONE HULL",
            "WINDOWS = BRIDGES",
            "BOW = OVERHANGS",
            "COMPARE, THEN DIAGNOSE",
        ],
        "scenes": [
            {
                "goal": "Hook: the tiny boat",
                "teaching_point": "Small print, big test",
                "shot": "close-up shot of a printed Benchy on a bench",
                "motion": "camera circles the hull",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["printed Benchy", "hull", "details"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printed Benchy on a bench, bright task lighting, workbench",
            },
            {
                "goal": "The hull",
                "teaching_point": "Layer quality shows",
                "shot": "close-up shot of the hull side walls",
                "motion": "light rakes across the layers",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["hull walls", "layer lines", "surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Benchy hull showing layer quality, bright task lighting, print lab",
            },
            {
                "goal": "The bridges",
                "teaching_point": "Windows test bridging",
                "shot": "close-up shot of the cabin windows and roof",
                "motion": "camera inspects the spans",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["cabin windows", "roof bridge", "span"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Benchy cabin windows testing bridges, bright task lighting, print lab",
            },
            {
                "goal": "The bow",
                "teaching_point": "Overhangs and text",
                "shot": "close-up shot of the bow and the deck text",
                "motion": "camera tilts down the bow",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["bow overhang", "deck text", "detail"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Benchy bow overhang and deck text, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One boat, every question",
                "shot": "wide hero shot of benchies compared side by side",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["benchy prints", "comparison row", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of Benchy prints compared side by side, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A Benchy with hull, windows, and bow labeled as tests",
            "subject": "Benchy diagnostic",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "boat center, labels around",
            "text": "ONE BOAT, EVERY QUESTION",
            "elements": ["Benchy", "hull", "cabin windows"],
            "style": "geometry studio photography",
            "mood": "tested, compared, diagnosed",
            "prompt": "photograph of a Benchy with the hull, windows, and bow labeled as tests and deck text, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Benchy as Diagnostic: One Boat, Every Question",
            "title_variations": [
                "What Can Benchy Tell Me",
                "3D Benchy Test Print",
                "Benchy Diagnosis Guide",
                "Benchy Overhangs Bridges",
                "Calibration Boat Print",
            ],
            "description": "The Benchy is a tiny boat that packs every printing challenge into one hull: overhangs, bridges, small details, and smooth surfaces all in one part. The hull checks layer quality, the cabin windows check bridges, the bow checks overhangs, and the text checks detail. Comparing benchies across settings changes points to the fault. This short circles the boat and names what each feature is testing.",
            "hashtags": ["#Benchy", "#3DBenchy", "#TestPrint", "#Calibration"],
            "seo_keywords": [
                "what can benchy tell me",
                "3d benchy test print",
                "benchy diagnosis",
                "benchy bridges overhangs",
                "benchmark print boat",
                "benchy layer quality",
                "calibration boat",
            ],
        },
        "fact_check": [
            "Benchy packs many print challenges.",
            "The hull tests layer quality.",
            "The windows test bridges.",
            "The bow tests overhangs.",
            "Comparing benchies diagnoses changes.",
        ],
    },
    {
        "topic": "Retraction Calibration",
        "core_question": "Why does your print look like a spider web?",
        "learning_objective": "The viewer understands retraction and how to calibrate it.",
        "engineering_summary": "Stringing is plastic that leaks from the nozzle during travel, and retraction fixes it: the filament is pulled back before the head moves, so the pressure at the tip releases. Too little retraction and the nozzle drips strings; too much and it clogs and under-extrudes. The calibration is a tower: distance or speed changing per step, and the cleanest zone wins. Bowden tubes need more pull than direct drives.",
        "real_world_application": "Every printer tunes retraction distance and speed with a tower.",
        "common_misconceptions": [
            "More retraction is always better (too much clogs)",
            "Temperature is irrelevant (heat raises the leak pressure)",
            "One setting fits all (Bowden and direct differ)",
        ],
        "teaching_strategy": "Print a retraction tower and pick the cleanest step.",
        "script": "Stringing is plastic that leaks from the nozzle during travel, and retraction fixes it: the filament is pulled back before the head moves, so the pressure at the tip releases. Too little retraction and the nozzle drips strings; too much and it clogs and under-extrudes. The calibration is a tower: distance or speed changing per step, and the cleanest zone wins. Bowden tubes need more pull than direct drives.",
        "text_overlay": [
            "PULL BACK BEFORE TRAVEL",
            "LEAK = PRESSURE AT THE TIP",
            "TOO MUCH CLOGS",
            "TOWER, PICK, CLEANEST WINS",
        ],
        "scenes": [
            {
                "goal": "Hook: the web",
                "teaching_point": "Leak during travel",
                "shot": "close-up shot of a stringy print covered in webs",
                "motion": "camera reveals the strands",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["stringy print", "webs", "strands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a stringy print covered in webs, bright task lighting, print lab",
            },
            {
                "goal": "The pull",
                "teaching_point": "Filament pulled back",
                "shot": "diagram-style shot of the extruder pulling filament back",
                "motion": "filament retracts from the hot zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extruder", "filament", "retraction arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of filament retraction, clean engineering visualization on a dark background",
            },
            {
                "goal": "The balance",
                "teaching_point": "Too little drips, too much clogs",
                "shot": "graphic-style shot of stringing and clogging trade curves",
                "motion": "two curves cross at the sweet spot",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stringing curve", "clog curve", "sweet spot"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of retraction balance curves, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tower",
                "teaching_point": "Steps change, pick the clean",
                "shot": "medium shot of a retraction tower print finishing",
                "motion": "tower builds step by step",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["retraction tower", "steps", "clean zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a retraction tower print finishing, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Bowden pulls more",
                "shot": "wide hero shot of direct and Bowden extruders on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["direct extruder", "Bowden tube", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of direct and Bowden extruders on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An extruder pulling filament back with a stringing tower beside",
            "subject": "retraction calibration",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "extruder center, tower beside",
            "text": "PULL BACK BEFORE TRAVEL",
            "elements": ["extruder", "retraction arrow", "tower"],
            "style": "geometry studio photography",
            "mood": "pulled, tuned, clean",
            "prompt": "photograph of an extruder pulling filament back with a retraction tower beside and a stringing web, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Retraction Calibration: Pull Back Before Travel",
            "title_variations": [
                "How to Calibrate Retraction",
                "Retraction Tower Guide",
                "Stringing Fix",
                "Retraction Distance Speed",
                "Stop Print Strings",
            ],
            "description": "Stringing is plastic that leaks from the nozzle during travel, and retraction fixes it by pulling the filament back so the tip pressure releases. Too little retraction drips strings and too much clogs, so the calibration is a tower where distance or speed changes per step and the cleanest zone wins. Bowden tubes need more pull than direct drives. This short webs a print, pulls the filament, and picks the cleanest step.",
            "hashtags": ["#Retraction", "#Stringing", "#Calibration", "#3DPrinting"],
            "seo_keywords": [
                "how to calibrate retraction",
                "retraction tower",
                "stringing fix",
                "retraction distance",
                "retraction speed",
                "bowden retraction",
                "nozzle leak travel",
            ],
        },
        "fact_check": [
            "Stringing comes from tip pressure.",
            "Retraction pulls filament back.",
            "Too little retraction strings.",
            "Too much retraction clogs.",
            "Bowden needs more pull than direct.",
        ],
    },
    {
        "topic": "Belt Tension Diagnosis",
        "core_question": "How can you tell your belts are too loose?",
        "learning_objective": "The viewer understands belt tension signs and how to set it.",
        "engineering_summary": "Belts drive the axes, and loose belts turn into print faults: ghosting, rounded corners, and a machine that sounds sloppy. A slack belt lets the carriage lag behind the motor, so the toolhead arrives late and the motion rings. The check is the pluck: a correctly tensioned belt twangs with a musical note, and a floppy one thuds. Tension is a sound, and the print is the witness.",
        "real_world_application": "Ghosting and corner rounding on any printer trace back to belt tension.",
        "common_misconceptions": [
            "Tension is for the belt's sake (the print shows it instantly)",
            "Tighter is always better (over-tight belts eat bearings)",
            "Belts stretch permanently (they need periodic re-tensioning)",
        ],
        "teaching_strategy": "Pluck a loose and a tuned belt and compare the notes and prints.",
        "script": "Belts drive the axes, and loose belts turn into print faults: ghosting, rounded corners, and a machine that sounds sloppy. A slack belt lets the carriage lag behind the motor, so the toolhead arrives late and the motion rings. The check is the pluck: a correctly tensioned belt twangs with a musical note, and a floppy one thuds. Tension is a sound, and the print is the witness.",
        "text_overlay": [
            "SLACK = LAG = GHOSTS",
            "CORNER ROUNDING",
            "PLUCK THE BELT",
            "TENSION IS A SOUND",
        ],
        "scenes": [
            {
                "goal": "Hook: the ghosted wall",
                "teaching_point": "Loose belt, ghosted print",
                "shot": "close-up shot of ghosting on a printed wall",
                "motion": "echo ripples repeat down the wall",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["printed wall", "ghosting", "echo lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of ghosting on a printed wall, bright task lighting, print lab",
            },
            {
                "goal": "The lag",
                "teaching_point": "Carriage lags the motor",
                "shot": "diagram-style shot of a slack belt lagging the pulley",
                "motion": "belt flexes before the carriage moves",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["belt", "pulley", "lag gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a slack belt lagging, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pluck",
                "teaching_point": "Twang versus thud",
                "shot": "close-up shot of a belt being plucked",
                "motion": "belt vibrates and rings",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["belt", "pluck", "vibration"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a belt being plucked to check tension, bright task lighting, print lab",
            },
            {
                "goal": "The range",
                "teaching_point": "Tight enough, not too tight",
                "shot": "graphic-style shot of the tension sweet zone",
                "motion": "needle sits in the zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["tension scale", "sweet zone", "over tight"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of belt tension zones, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The print is the witness",
                "shot": "wide hero shot of a tuned axis with its belt",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["belt axis", "tensioner", "print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tuned belt axis on a printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A plucked belt with a ghosted wall and a tension zone scale",
            "subject": "belt tension",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "belt center, ghost wall behind",
            "text": "TENSION IS A SOUND",
            "elements": ["belt", "ghosted print", "tension scale"],
            "style": "geometry studio photography",
            "mood": "plucked, lagging, tuned",
            "prompt": "photograph of a plucked belt with a ghosted print wall and a tension zone scale, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Belt Tension Diagnosis: Tension Is a Sound",
            "title_variations": [
                "How to Tell If Belts Are Loose",
                "Belt Tension Printer",
                "Ghosting Fix Belt",
                "Belt Pluck Test",
                "Loose Belt Symptoms",
            ],
            "description": "Belts drive the axes, and loose belts turn into print faults: ghosting, rounded corners, and a machine that sounds sloppy. A slack belt lets the carriage lag behind the motor, so the toolhead arrives late and the motion rings. The check is the pluck: a tuned belt twangs with a musical note and a floppy one thuds. This short ghosts a wall, plucks the belt, and shows how the print is the witness.",
            "hashtags": ["#BeltTension", "#Ghosting", "#3DPrinting", "#Tuning"],
            "seo_keywords": [
                "how to tell if belts are loose",
                "belt tension printer",
                "ghosting fix belt",
                "belt pluck test",
                "loose belt symptoms",
                "belt tension tune",
                "carriage lag motor",
            ],
        },
        "fact_check": [
            "Loose belts cause ghosting.",
            "Slack belts let the carriage lag.",
            "Rounded corners trace to tension.",
            "The pluck test checks it.",
            "Over-tight belts wear bearings.",
        ],
    },
    {
        "topic": "Spaghetti Detection",
        "core_question": "Why does a print suddenly become a plate of pasta?",
        "learning_objective": "The viewer understands print failures and spaghetti detection.",
        "engineering_summary": "Spaghetti happens when the part lets go of the bed or the nozzle drags it: the print breaks free, the nozzle keeps extruding, and plastic piles into noodle loops. The causes are the usual suspects: poor adhesion, a lifted corner, or a collision. Detection watches the print with a camera and flags the failure mid-print, so nothing is wasted. The failure is a symptom; the adhesion was the cause.",
        "real_world_application": "Cameras and detection software catch spaghetti before it ruins hours of print.",
        "common_misconceptions": [
            "Spaghetti is a random event (it has a cause, usually adhesion)",
            "The printer knows (detection needs a camera and eyes)",
            "More filament fixes it (the part must stay put first)",
        ],
        "teaching_strategy": "Show a print losing its part, then a camera flagging the failure.",
        "script": "Spaghetti happens when the part lets go of the bed or the nozzle drags it: the print breaks free, the nozzle keeps extruding, and plastic piles into noodle loops. The causes are the usual suspects: poor adhesion, a lifted corner, or a collision. Detection watches the print with a camera and flags the failure mid-print, so nothing is wasted. The failure is a symptom; the adhesion was the cause.",
        "text_overlay": [
            "THE PART LETS GO",
            "NOZZLE KEEPS EXTRUDING",
            "ADHESION WAS THE CAUSE",
            "CAMERA EYES, FLAG, STOP",
        ],
        "scenes": [
            {
                "goal": "Hook: the noodle pile",
                "teaching_point": "Part gone, plastic loops",
                "shot": "close-up shot of a spaghetti pile under a moving nozzle",
                "motion": "nozzle drags noodle loops",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["spaghetti pile", "nozzle", "loops"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a spaghetti pile under a moving nozzle, bright task lighting, print lab",
            },
            {
                "goal": "The break",
                "teaching_point": "The part lets go",
                "shot": "diagram-style shot of a part lifting off the bed",
                "motion": "corner curls and breaks free",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["lifted corner", "bed", "breakaway"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a part breaking free of the bed, clean engineering visualization on a dark background",
            },
            {
                "goal": "The causes",
                "teaching_point": "Adhesion, corners, collisions",
                "shot": "graphic-style shot of failure causes listed",
                "motion": "causes light up in turn",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["adhesion cause", "corner cause", "collision cause"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of spaghetti failure causes, clean engineering visualization on a dark background",
            },
            {
                "goal": "The watch",
                "teaching_point": "Camera flags mid-print",
                "shot": "medium shot of a camera watching a printer bed",
                "motion": "frame marks the failure",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["camera", "printer bed", "failure flag"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a camera watching a printer bed for failures, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fix the adhesion",
                "shot": "wide hero shot of a clean print finishing on a good bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "bed", "finished part"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean print finishing on a good bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spaghetti pile with a camera flagging the failure mid-print",
            "subject": "spaghetti detection",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pile center, camera above",
            "text": "THE FAILURE IS A SYMPTOM",
            "elements": ["spaghetti pile", "camera", "nozzle"],
            "style": "geometry studio photography",
            "mood": "failed, watched, flagged",
            "prompt": "photograph of a spaghetti pile under a nozzle with a camera flagging the failure, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Spaghetti Detection: The Failure Is a Symptom",
            "title_variations": [
                "What Causes Spaghetti Prints",
                "Spaghetti Detection Explained",
                "Print Failure Causes",
                "Failed Print Recovery",
                "Adhesion Failure Fix",
            ],
            "description": "Spaghetti happens when the part lets go of the bed or the nozzle drags it: the print breaks free, the nozzle keeps extruding, and plastic piles into noodle loops. The causes are poor adhesion, a lifted corner, or a collision, and detection watches the print with a camera to flag the failure mid-print. This short breaks a part free, lists the causes, and shows the camera that stops the waste.",
            "hashtags": ["#Spaghetti", "#PrintFailure", "#3DPrinting", "#Detection"],
            "seo_keywords": [
                "what causes spaghetti prints",
                "spaghetti detection",
                "print failure causes",
                "failed print fix",
                "adhesion failure",
                "camera print watch",
                "noodle loops nozzle",
            ],
        },
        "fact_check": [
            "Spaghetti follows a part breaking free.",
            "The nozzle keeps extruding.",
            "Adhesion is the usual cause.",
            "Detection needs a camera.",
            "The failure is a symptom of adhesion.",
        ],
    },
    {
        "topic": "Grid vs Gyroid vs Cubic",
        "core_question": "Which infill pattern should you trust?",
        "learning_objective": "The viewer understands infill pattern trade-offs.",
        "engineering_summary": "Infill fills the part's shell with patterns, and each one trades strength, speed, and direction. Grid is fast and simple, with straight lines crossing in one plane. Cubic builds in all three directions, so it holds load from any side. Gyroid is a smooth wave that is strong, light, and fast in every direction, and it resists shearing well. Pick by the load: grid for drafts, cubic for all-direction, gyroid for strength per gram.",
        "real_world_application": "Functional parts run cubic or gyroid; display parts run grid.",
        "common_misconceptions": [
            "More infill is the fix (the pattern matters too)",
            "Grid is strongest (it is planar and direction-dependent)",
            "All patterns print the same speed (gyroid moves are longer)",
        ],
        "teaching_strategy": "Print the same part with each pattern and squash it.",
        "script": "Infill fills the part's shell with patterns, and each one trades strength, speed, and direction. Grid is fast and simple, with straight lines crossing in one plane. Cubic builds in all three directions, so it holds load from any side. Gyroid is a smooth wave that is strong, light, and fast in every direction, and it resists shearing well. Pick by the load: grid for drafts, cubic for all-direction, gyroid for strength per gram.",
        "text_overlay": [
            "GRID: FAST, PLANAR",
            "CUBIC: ALL DIRECTIONS",
            "GYROID: STRENGTH PER GRAM",
            "PICK BY THE LOAD",
        ],
        "scenes": [
            {
                "goal": "Hook: three cubes",
                "teaching_point": "Same shell, three insides",
                "shot": "medium shot of three infill cubes cut open",
                "motion": "camera pans the insides",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["grid cube", "cubic cube", "gyroid cube"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of three infill cubes cut open, neutral lab lighting, workbench",
            },
            {
                "goal": "The grid",
                "teaching_point": "Fast, simple, planar",
                "shot": "diagram-style shot of grid infill crossing lines",
                "motion": "lines cross in one plane",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["grid lines", "plane", "cross pattern"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of grid infill, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cubic",
                "teaching_point": "Load from any side",
                "shot": "diagram-style shot of cubic infill in three axes",
                "motion": "cube cells stack in all directions",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cubic cells", "three axes", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of cubic infill, clean engineering visualization on a dark background",
            },
            {
                "goal": "The gyroid",
                "teaching_point": "Smooth wave, shear resistant",
                "shot": "diagram-style shot of the gyroid wave structure",
                "motion": "waves curve through the volume",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gyroid waves", "smooth curves", "volume"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of gyroid infill, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick by the load",
                "shot": "wide hero shot of infill samples on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["infill samples", "cut cubes", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of infill samples on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three cut cubes showing grid, cubic, and gyroid infill",
            "subject": "infill patterns",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "three cubes in a row",
            "text": "PICK BY THE LOAD",
            "elements": ["grid cube", "cubic cube", "gyroid cube"],
            "style": "geometry studio photography",
            "mood": "compared, structured, chosen",
            "prompt": "photograph of three cut cubes showing grid, cubic, and gyroid infill on a bench, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Grid vs Gyroid vs Cubic: Pick by the Load",
            "title_variations": [
                "Gyroid vs Grid Infill",
                "Infill Patterns Compared",
                "Best Infill for Strength",
                "Cubic Infill Explained",
                "Infill Pattern Guide",
            ],
            "description": "Infill fills a part's shell with patterns, and each one trades strength, speed, and direction. Grid is fast and simple with planar lines, cubic builds in all three directions to hold load from any side, and gyroid is a smooth wave that is strong, light, and fast in every direction. Pick by the load: grid for drafts, cubic for all-direction, gyroid for strength per gram. This short cuts three cubes open and squashes them to compare.",
            "hashtags": ["#Infill", "#Gyroid", "#CubicInfill", "#3DPrinting"],
            "seo_keywords": [
                "gyroid vs grid infill",
                "infill patterns compared",
                "best infill strength",
                "cubic infill",
                "gyroid infill",
                "infill shear resistance",
                "infill pattern guide",
            ],
        },
        "fact_check": [
            "Grid is fast and planar.",
            "Cubic builds in all directions.",
            "Gyroid is strong in every direction.",
            "Gyroid resists shearing well.",
            "Pattern choice depends on the load.",
        ],
    },
    {
        "topic": "Fan Cooling & Warping",
        "core_question": "Does the fan cause warping?",
        "learning_objective": "The viewer understands cooling and warping trade-offs.",
        "engineering_summary": "Warping is the corners pulling up, and it comes from uneven shrinkage: the fresh hot layer cools and contracts while the older layers hold their size, so the corner curls. The fan makes it worse only when it cools the part unevenly, especially the bottom layers. PLA loves a strong fan for details and bridges, but ABS and PETG crack and curl under drafts. The fan is not the enemy; the uneven cooling is.",
        "real_world_application": "Each filament family runs its own fan and chamber strategy.",
        "common_misconceptions": [
            "The fan is the enemy (uneven cooling is)",
            "Cooler is always better (cold drafts warp ABS)",
            "One fan speed fits all (PLA and ABS differ hugely)",
        ],
        "teaching_strategy": "Shrink a curled corner on screen, then show the per-filament fan curve.",
        "script": "Warping is the corners pulling up, and it comes from uneven shrinkage: the fresh hot layer cools and contracts while the older layers hold their size, so the corner curls. The fan makes it worse only when it cools the part unevenly, especially the bottom layers. PLA loves a strong fan for details and bridges, but ABS and PETG crack and curl under drafts. The fan is not the enemy; the uneven cooling is.",
        "text_overlay": [
            "FRESH LAYER SHRINKS, OLD HOLDS",
            "THE CORNER CURLS",
            "PLA: FAN ON",
            "ABS: DRAFT OFF",
        ],
        "scenes": [
            {
                "goal": "Hook: the curled corner",
                "teaching_point": "Uneven shrinkage",
                "shot": "close-up shot of a part corner peeling off the bed",
                "motion": "corner lifts as layers cool",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["curled corner", "bed", "peel"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part corner peeling off the bed, bright task lighting, print lab",
            },
            {
                "goal": "The shrinkage",
                "teaching_point": "Hot cools, old holds",
                "shot": "diagram-style shot of the shrinking layer pair",
                "motion": "top layer contracts while the base holds",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fresh layer", "old layer", "shrink arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layer shrinkage warping, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fan",
                "teaching_point": "Uneven cooling hurts",
                "shot": "diagram-style shot of the fan blowing on one side",
                "motion": "air blast cools one corner",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fan blast", "uneven side", "corner draft"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fan cooling on one side, clean engineering visualization on a dark background",
            },
            {
                "goal": "The families",
                "teaching_point": "PLA fan on, ABS off",
                "shot": "graphic-style shot of filament cooling curves",
                "motion": "fan curves differ by filament",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["PLA curve", "ABS curve", "PETG curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of filament cooling curves, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Even cooling wins",
                "shot": "wide hero shot of a flat clean print with a fan above",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flat print", "fan", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flat clean print with a fan above, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A curled corner under a fan blast with filament cooling curves",
            "subject": "fan cooling warping",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "corner center, fan above",
            "text": "UNEQUAL COOLING IS THE ENEMY",
            "elements": ["curled corner", "fan", "cooling curves"],
            "style": "geometry studio photography",
            "mood": "curled, cooled, balanced",
            "prompt": "photograph of a curled print corner under a fan blast with cooling curves beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Fan Cooling & Warping: Unequal Cooling Is the Enemy",
            "title_variations": [
                "Does Fan Cooling Cause Warping",
                "Warping Corner Fix",
                "PLA ABS Fan Speed",
                "Warping Shrinkage Explained",
                "Cooling Trade Offs Print",
            ],
            "description": "Warping is corners pulling up from uneven shrinkage: the fresh hot layer cools and contracts while the older layers hold their size, so the corner curls. The fan only makes it worse when it cools the part unevenly, especially the bottom layers. PLA loves a strong fan for details and bridges, but ABS and PETG crack under drafts. This short curls a corner, blows the fan, and shows that the fan is not the enemy: the uneven cooling is.",
            "hashtags": ["#Warping", "#FanCooling", "#PLA", "#ABS"],
            "seo_keywords": [
                "does fan cooling cause warping",
                "warping corner fix",
                "PLA fan speed",
                "ABS draft warping",
                "warping shrinkage",
                "uneven cooling",
                "PETG fan settings",
            ],
        },
        "fact_check": [
            "Warping comes from uneven shrinkage.",
            "The fresh layer contracts.",
            "The fan can cool unevenly.",
            "PLA favors a strong fan.",
            "ABS and PETG avoid drafts.",
        ],
    },
    {
        "topic": "Input Shaping",
        "core_question": "What actually kills printer ringing?",
        "learning_objective": "The viewer understands input shaping and how it removes ringing.",
        "engineering_summary": "Ringing is the toolhead vibrating after a direction change: the head overshoots, bounces, and the printed wall echoes the wobble. Input shaping fixes it in software: the firmware shapes the motion command so the machine's own vibration cancels the bounce. The printer moves with a shaped curve instead of a step, and the echo dies. It is a vibration canceler, not a speed hack, and it is the reason modern printers print fast and clean.",
        "real_world_application": "Klipper and modern firmware ship input shaping as a default.",
        "common_misconceptions": [
            "It is a speed cheat (it removes resonance, speed is the bonus)",
            "It fixes all artifacts (it cures ringing, not adhesion or flow)",
            "It is hardware (it is a software motion curve)",
        ],
        "teaching_strategy": "Show a ringing wall, then the shaped motion canceling it.",
        "script": "Ringing is the toolhead vibrating after a direction change: the head overshoots, bounces, and the printed wall echoes the wobble. Input shaping fixes it in software: the firmware shapes the motion command so the machine's own vibration cancels the bounce. The printer moves with a shaped curve instead of a step, and the echo dies. It is a vibration canceler, not a speed hack, and it is the reason modern printers print fast and clean.",
        "text_overlay": [
            "OVERSHOOT, BOUNCE, ECHO",
            "SHAPE THE COMMAND",
            "VIBRATION CANCELS VIBRATION",
            "FAST AND CLEAN",
        ],
        "scenes": [
            {
                "goal": "Hook: the echo wall",
                "teaching_point": "Toolhead wobble prints ghosts",
                "shot": "close-up shot of ringing ripples on a printed wall",
                "motion": "echo ripples repeat down the wall",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["printed wall", "ringing ripples", "echo lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of ringing ripples on a printed wall, bright task lighting, print lab",
            },
            {
                "goal": "The bounce",
                "teaching_point": "Overshoot after the turn",
                "shot": "diagram-style shot of a toolhead overshooting a corner",
                "motion": "head overshoots and bounces back",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["toolhead", "overshoot", "bounce path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of toolhead overshoot and bounce, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shape",
                "teaching_point": "Firmware shapes the motion",
                "shot": "diagram-style shot of a shaped motion curve",
                "motion": "step becomes a smooth shaped curve",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["step command", "shaped curve", "motion trace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of input shaping motion curves, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cancel",
                "teaching_point": "Vibration cancels vibration",
                "shot": "diagram-style shot of wave cancellation",
                "motion": "two waves meet and flatten",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["command wave", "echo wave", "flat result"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of vibration cancellation, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fast and clean",
                "shot": "wide hero shot of a fast clean print on a modern printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["modern printer", "clean print", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fast clean print on a modern printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A toolhead bounce becoming a shaped curve that flattens the echo",
            "subject": "input shaping",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "curve center, printer behind",
            "text": "VIBRATION CANCELS VIBRATION",
            "elements": ["shaped curve", "toolhead", "echo wall"],
            "style": "geometry studio photography",
            "mood": "shaped, canceled, clean",
            "prompt": "photograph of a shaped motion curve canceling toolhead vibration on a printer with an echo wall, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Input Shaping: Vibration Cancels Vibration",
            "title_variations": [
                "What Is Input Shaping",
                "Input Shaping Explained",
                "Klipper Input Shaper",
                "Ringing Fix Input Shaping",
                "Resonance Compensation",
            ],
            "description": "Ringing is the toolhead vibrating after a direction change: the head overshoots, bounces, and the printed wall echoes the wobble. Input shaping fixes it in software by shaping the motion command so the machine's own vibration cancels the bounce. The printer moves on a shaped curve instead of a step and the echo dies. This short bounces a toolhead, shapes the command, and shows why modern printers print fast and clean.",
            "hashtags": ["#InputShaping", "#Klipper", "#Ringing", "#3DPrinting"],
            "seo_keywords": [
                "what is input shaping",
                "input shaping explained",
                "klipper input shaper",
                "ringing fix",
                "resonance compensation",
                "vibration cancellation print",
                "fast clean printer",
            ],
        },
        "fact_check": [
            "Ringing is toolhead vibration.",
            "The head overshoots and bounces.",
            "Input shaping is software.",
            "It cancels the machine's resonance.",
            "It removes ringing, not all faults.",
        ],
    },
]