"""Batch 49: self-supporting lattices, scaling parts and shrinkage, slot and tab assembly, text and fonts on parts, QR codes and logos, tolerance stacks, shim and spacer fit, slicer skeleton g-code paths."""

CURATED = [
    # ======================================================================
    {
        "topic": "Self-Supporting Lattices",
        "core_question": "What lattices print without supports?",
        "learning_objective": "The viewer understands self-supporting lattices.",
        "engineering_summary": "Lattices print without supports when every strut leans on the layer below: a lattice whose members meet at about forty-five degrees lets each new strut bridge from an existing one, so the whole structure grows without scaffolding. The geometry that wins is the triply periodic shape, a repeating wave that interlocks in every direction, and its struts never overhang past the printable angle. The rules are angle, cell size, and direction: keep struts under the overhang limit, size cells to the nozzle, and orient with the build. Lattices that support themselves print light and strong.",
        "real_world_application": "Gyroid infill and lattice shoe soles need no supports.",
        "common_misconceptions": [
            "Every lattice prints clean (steep struts need supports)",
            "Cells can be any size (the nozzle sets the floor)",
            "Lattices are decoration (they carry real load)",
        ],
        "teaching_strategy": "Show the leaning struts, then the wave cells.",
        "script": "Lattices print without supports when every strut leans on the layer below: a lattice whose members meet at about forty-five degrees lets each new strut bridge from an existing one, so the whole structure grows without scaffolding. The geometry that wins is the triply periodic shape, a repeating wave that interlocks in every direction, and its struts never overhang past the printable angle. The rules are angle, cell size, and direction: keep struts under the overhang limit, size cells to the nozzle, and orient with the build. Lattices that support themselves print light and strong.",
        "text_overlay": [
            "STRUTS LEAN, NEVER HANG",
            "FORTY-FIVE DEGREES OR LESS",
            "THE WAVE INTERLOCKS",
            "LIGHT, STRONG, SUPPORT-FREE",
        ],
        "scenes": [
            {
                "goal": "Hook: the lattice cube",
                "teaching_point": "It grew with no scaffolding",
                "shot": "close-up shot of a gyroid lattice cube",
                "motion": "camera orbits the open cells",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["lattice cube", "open cells", "wave struts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a self-supporting lattice cube, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The lean",
                "teaching_point": "Struts bridge at forty-five",
                "shot": "diagram-style shot of the strut angle",
                "motion": "new strut bridges from the one below",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["strut angle", "bridge arrow", "layer below"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of self-supporting strut angles, clean engineering visualization on a dark background",
            },
            {
                "goal": "The wave",
                "teaching_point": "Triply periodic cells",
                "shot": "diagram-style shot of the wave cells",
                "motion": "wave interlocks in every direction",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wave cells", "interlock arrows", "periodic shape"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a triply periodic lattice, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Angle, size, direction",
                "shot": "diagram-style shot of the lattice controls",
                "motion": "cells scale to the nozzle size",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cell size", "nozzle scale", "build direction"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of lattice cell sizing, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the lean in",
                "shot": "wide hero shot of lattice parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["lattice part", "light frame", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of lightweight lattice parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A gyroid lattice cube with struts leaning on each other",
            "subject": "self-supporting lattices",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cube left, struts right",
            "text": "STRUTS LEAN, NEVER HANG",
            "elements": ["gyroid cube", "diagonal struts", "open cells"],
            "style": "geometry studio photography",
            "mood": "leaning, interlocked, light",
            "prompt": "photograph of a gyroid lattice cube with diagonal struts leaning on each other and no support structure underneath, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Self-Supporting Lattices: Struts Lean, Never Hang",
            "title_variations": [
                "What Lattices Print Without Supports",
                "Gyroid Lattice Design",
                "Support-Free Lattice Printing",
                "Triply Periodic Lattice",
                "Lightweight Lattice Parts",
            ],
            "description": "Lattices print without supports when every strut leans on the layer below: a lattice whose members meet at about forty-five degrees lets each new strut bridge from an existing one, so the whole structure grows without scaffolding. The geometry that wins is the triply periodic shape, a repeating wave that interlocks in every direction, and its struts never overhang past the printable angle. The rules are angle, cell size, and direction: keep struts under the overhang limit, size cells to the nozzle, and orient with the build. This short grows the wave, bridges the struts, and drops the supports. Lattices that support themselves print light and strong.",
            "hashtags": ["#Lattices", "#Gyroid", "#3DPrinting", "#GenerativeDesign"],
            "seo_keywords": [
                "what lattices print without supports",
                "lattice",
                "self supporting lattice",
                "lattice design",
                "triply periodic",
                "gyroid infill",
                "support free lattice printing",
            ],
        },
        "fact_check": [
            "Struts lean on the layer below.",
            "Forty-five degrees is the rule.",
            "Waves interlock in all directions.",
            "Cells scale to the nozzle.",
            "Self-supporting lattices save material.",
        ],
    },
    {
        "topic": "Scaling Parts & Shrinkage",
        "core_question": "Why scale up printed parts?",
        "learning_objective": "The viewer understands scaling parts and shrinkage.",
        "engineering_summary": "Printed parts come out small on purpose: the slicer compensates for material shrinkage, and the model gets scaled up by a factor, so the finished part lands at the drawing size after the plastic cools and contracts. Different materials shrink differently, and the factor is not just the material: the infill, wall count, and print direction all pull the part a little differently. The rules are measure, print, and remeasure: print a test cube, measure the real deviation, and scale the model to cancel it. Shrinkage is a correction you measure, not guess.",
        "real_world_application": "Fit-critical parts get a calibration cube before the final print.",
        "common_misconceptions": [
            "Shrinkage is uniform (direction and infill change it)",
            "The CAD file is exact (the printer adds its own scale)",
            "One factor fits all (every material shrinks differently)",
        ],
        "teaching_strategy": "Show the calibration cube, then the scaled model.",
        "script": "Printed parts come out small on purpose: the slicer compensates for material shrinkage, and the model gets scaled up by a factor, so the finished part lands at the drawing size after the plastic cools and contracts. Different materials shrink differently, and the factor is not just the material: the infill, wall count, and print direction all pull the part a little differently. The rules are measure, print, and remeasure: print a test cube, measure the real deviation, and scale the model to cancel it. Shrinkage is a correction you measure, not guess.",
        "text_overlay": [
            "COME OUT SMALL ON PURPOSE",
            "SHRINKAGE IS MEASURED, NOT GUESSED",
            "TEST CUBE, CALIPERS, SCALE",
            "FIT IS A CORRECTION",
        ],
        "scenes": [
            {
                "goal": "Hook: the test cube",
                "teaching_point": "Measure the real part",
                "shot": "close-up shot of a calibration cube",
                "motion": "camera pans to the calipers",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["calibration cube", "calipers", "measure mark"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a calibration cube being measured, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The shrink",
                "teaching_point": "Cooling pulls the part small",
                "shot": "diagram-style shot of the cooling part",
                "motion": "dimensions shrink as the plastic cools",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cooling part", "shrink arrows", "drawing size"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of plastic shrinkage after printing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The factors",
                "teaching_point": "Material, infill, direction",
                "shot": "diagram-style shot of the shrink factors",
                "motion": "three factors pull the part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["material tile", "infill tile", "direction tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of shrinkage factors, clean engineering visualization on a dark background",
            },
            {
                "goal": "The correction",
                "teaching_point": "Scale to cancel the error",
                "shot": "diagram-style shot of the scale factor",
                "motion": "model grows to match the drawing",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["scale slider", "grown model", "match line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of scaling a model to cancel shrinkage, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Measure, print, remeasure",
                "shot": "wide hero shot of a fit-critical part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fitted part", "mating piece", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a perfectly fitted printed part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A test cube measured with calipers beside a scaled model on screen",
            "subject": "scaling parts and shrinkage",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cube left, screen right",
            "text": "MEASURED, NOT GUESSED",
            "elements": ["test cube", "calipers", "scaled model"],
            "style": "geometry studio photography",
            "mood": "measured, scaled, fitted",
            "prompt": "photograph of a printed test cube being measured with calipers beside a scaled model file on a monitor screen, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Scaling Parts & Shrinkage: Measured, Not Guessed",
            "title_variations": [
                "Why Scale Up Printed Parts",
                "3D Print Shrinkage Fix",
                "Calibration Cube Guide",
                "Print Scale Correction",
                "Oversize Your Model",
            ],
            "description": "Printed parts come out small on purpose: the slicer compensates for material shrinkage, and the model gets scaled up by a factor, so the finished part lands at the drawing size after the plastic cools and contracts. Different materials shrink differently, and the factor is not just the material: the infill, wall count, and print direction all pull the part a little differently. The rules are measure, print, and remeasure: print a test cube, measure the real deviation, and scale the model to cancel it. This short prints the cube, reads the calipers, and sets the factor. Shrinkage is a correction you measure, not guess.",
            "hashtags": ["#Shrinkage", "#Calibration", "#3DPrinting", "#Fits"],
            "seo_keywords": [
                "why scale up printed parts",
                "scale parts",
                "shrinkage",
                "print scale",
                "oversize part",
                "calibration cube scale",
                "3d print shrinkage fix",
            ],
        },
        "fact_check": [
            "Parts shrink as they cool.",
            "Slicers scale the model up.",
            "Materials shrink differently.",
            "Infill pulls the part.",
            "Calibrate with a test cube.",
        ],
    },
    {
        "topic": "Slot & Tab Assembly",
        "core_question": "What is slot and tab joinery?",
        "learning_objective": "The viewer understands slot and tab assembly.",
        "engineering_summary": "Slot and tab joinery locks parts without glue: one piece carries a tab, the other carries a matching slot, and the two slide together like a puzzle, so the joint holds one direction and comes apart again. The details decide the fit: tabs get a small radius where they meet the base, slots get clearance on the press side, and the joint counts on friction to stay put. The rules are fit, direction, and repair: a snug tab locks, the slot must be oriented against the load, and the joint stays removable. Assembly that comes apart.",
        "real_world_application": "Laser-cut and printed furniture panels join with tabs.",
        "common_misconceptions": [
            "Tabs need glue to hold (friction and direction hold them)",
            "Any fit works (loose joints wobble, tight ones crack)",
            "The joint is permanent (it is designed to come apart)",
        ],
        "teaching_strategy": "Show the tab sliding in, then the locked joint.",
        "script": "Slot and tab joinery locks parts without glue: one piece carries a tab, the other carries a matching slot, and the two slide together like a puzzle, so the joint holds one direction and comes apart again. The details decide the fit: tabs get a small radius where they meet the base, slots get clearance on the press side, and the joint counts on friction to stay put. The rules are fit, direction, and repair: a snug tab locks, the slot must be oriented against the load, and the joint stays removable. Assembly that comes apart.",
        "text_overlay": [
            "LOCKS WITHOUT GLUE",
            "TAB MEETS SLOT",
            "FRICTION AND DIRECTION HOLD",
            "ASSEMBLY THAT COMES APART",
        ],
        "scenes": [
            {
                "goal": "Hook: the puzzle fit",
                "teaching_point": "Two parts become one",
                "shot": "close-up shot of a tab sliding into a slot",
                "motion": "camera pans the interlocking panels",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["tab panel", "slot panel", "puzzle joint"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of printed panels locking with a tab and slot, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The lock",
                "teaching_point": "One direction holds",
                "shot": "diagram-style shot of the joint direction",
                "motion": "load arrow presses the tab into the slot",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["tab edge", "slot wall", "load arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a slot and tab lock, clean engineering visualization on a dark background",
            },
            {
                "goal": "The details",
                "teaching_point": "Radius and clearance",
                "shot": "diagram-style shot of the joint details",
                "motion": "radius and clearance callouts appear",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["base radius", "press clearance", "fit marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tab radius and slot clearance, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Fit, direction, repair",
                "shot": "diagram-style shot of the joint rules",
                "motion": "snug tab locks, wrong direction slips",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["snug tab", "wrong direction", "repair arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of slot and tab fit rules, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Build it to rebuild",
                "shot": "wide hero shot of the assembled box",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["assembled box", "panel joints", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an assembled panel box, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two panels locking with a tab sliding into a slot",
            "subject": "slot and tab assembly",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "tab panel left, slot panel right",
            "text": "LOCKS WITHOUT GLUE",
            "elements": ["tab panel", "slot panel", "puzzle joint"],
            "style": "geometry studio photography",
            "mood": "slid, locked, detachable",
            "prompt": "photograph of two printed panels locking together with a tab sliding into a matching slot without glue or fasteners, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Slot & Tab Assembly: Locks Without Glue",
            "title_variations": [
                "What Is Slot and Tab Joinery",
                "Tab Assembly Joints",
                "Finger Joint Prints",
                "Knockdown Joints",
                "Glue-Free Panel Joining",
            ],
            "description": "Slot and tab joinery locks parts without glue: one piece carries a tab, the other carries a matching slot, and the two slide together like a puzzle, so the joint holds one direction and comes apart again. The details decide the fit: tabs get a small radius where they meet the base, slots get clearance on the press side, and the joint counts on friction to stay put. The rules are fit, direction, and repair: a snug tab locks, the slot must be oriented against the load, and the joint stays removable. This short slides the tab, locks the panel, and rebuilds the box. Assembly that comes apart.",
            "hashtags": ["#SlotAndTab", "#Joinery", "#Assembly", "#3DPrinting"],
            "seo_keywords": [
                "what is slot and tab joinery",
                "slot and tab",
                "tab assembly",
                "finger joint",
                "knockdown joints",
                "glue free panel joints",
                "tab slot 3d print",
            ],
        },
        "fact_check": [
            "Tabs lock without glue.",
            "Direction holds the joint.",
            "Radius saves the tab base.",
            "Friction keeps it put.",
            "The joint comes apart.",
        ],
    },
    {
        "topic": "Text & Fonts on Parts",
        "core_question": "How small can text be?",
        "learning_objective": "The viewer understands text and fonts on parts.",
        "engineering_summary": "Text on a print is limited by the nozzle: embossed letters need at least a two wall stroke and a readable height, so tiny text turns into a blur of melted bumps. The rules come from the layer line: walls that are too thin vanish, small letter counters fill in, and the font matters, because a bold block font survives better than a thin script. The fixes are design: emboss instead of deboss for detail, raise the letters enough, and keep the height above the floor. If the nozzle cannot trace it, it will not print.",
        "real_world_application": "Labels and part numbers need minimum stroke widths to read.",
        "common_misconceptions": [
            "Smaller text always works (the nozzle sets the floor)",
            "Any font prints fine (thin scripts smear)",
            "Debossed text is clearer (emboss holds detail better)",
        ],
        "teaching_strategy": "Show the stroke width, then the bold font fix.",
        "script": "Text on a print is limited by the nozzle: embossed letters need at least a two wall stroke and a readable height, so tiny text turns into a blur of melted bumps. The rules come from the layer line: walls that are too thin vanish, small letter counters fill in, and the font matters, because a bold block font survives better than a thin script. The fixes are design: emboss instead of deboss for detail, raise the letters enough, and keep the height above the floor. If the nozzle cannot trace it, it will not print.",
        "text_overlay": [
            "TWO WALLS MINIMUM",
            "TINY TEXT TURNS TO BLUR",
            "BOLD BLOCKS SURVIVE",
            "EMBOSS FOR DETAIL",
        ],
        "scenes": [
            {
                "goal": "Hook: the name plate",
                "teaching_point": "Readable or melted",
                "shot": "close-up shot of printed embossed letters",
                "motion": "camera pans the crisp text",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["name plate", "embossed letters", "crisp stroke"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printed name plate with embossed letters, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The limit",
                "teaching_point": "The nozzle sets the floor",
                "shot": "diagram-style shot of the stroke width",
                "motion": "two walls trace the letter stroke",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["letter stroke", "wall pair", "nozzle size"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of text stroke width, clean engineering visualization on a dark background",
            },
            {
                "goal": "The blur",
                "teaching_point": "Counters fill with plastic",
                "shot": "diagram-style shot of the tiny text",
                "motion": "letter holes close into bumps",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["letter counters", "filled holes", "blurred bumps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tiny text filling in, clean engineering visualization on a dark background",
            },
            {
                "goal": "The font",
                "teaching_point": "Bold blocks beat thin scripts",
                "shot": "diagram-style shot of the font compare",
                "motion": "block font stays crisp, script smears",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["block font", "script font", "crisp pair"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of block versus script fonts, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the text for the nozzle",
                "shot": "wide hero shot of labeled parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["labeled part", "crisp text", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of printed parts with crisp labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Embossed bold letters on a part beside a blurry tiny text sample",
            "subject": "text and fonts on parts",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bold left, blurry right",
            "text": "TWO WALLS MINIMUM",
            "elements": ["embossed letters", "tiny text", "nozzle floor"],
            "style": "geometry studio photography",
            "mood": "raised, crisp, traced",
            "prompt": "photograph of a printed part with embossed bold letters showing crisp raised text beside a blurry tiny text sample, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Text & Fonts on Parts: If the Nozzle Cannot Trace It, It Will Not Print",
            "title_variations": [
                "How Small Can Text Be",
                "Text on 3D Prints",
                "Best Fonts for Printing",
                "Emboss vs Deboss Text",
                "Legible Print Labels",
            ],
            "description": "Text on a print is limited by the nozzle: embossed letters need at least a two wall stroke and a readable height, so tiny text turns into a blur of melted bumps. The rules come from the layer line: walls that are too thin vanish, small letter counters fill in, and the font matters, because a bold block font survives better than a thin script. The fixes are design: emboss instead of deboss for detail, raise the letters enough, and keep the height above the floor. This short traces the stroke, fills the counters, and picks the font. If the nozzle cannot trace it, it will not print.",
            "hashtags": ["#3DPrinting", "#Typography", "#Text", "#Design"],
            "seo_keywords": [
                "how small can text be",
                "text on 3d prints",
                "fonts",
                "small text",
                "emboss text",
                "best fonts for 3d printing",
                "emboss vs deboss text",
            ],
        },
        "fact_check": [
            "The nozzle sets the floor.",
            "Two walls trace a stroke.",
            "Counters fill with plastic.",
            "Bold fonts survive best.",
            "Emboss holds more detail.",
        ],
    },
    {
        "topic": "QR Codes & Logos",
        "core_question": "How to print a QR code?",
        "learning_objective": "The viewer understands QR codes and logos on parts.",
        "engineering_summary": "QR codes print if they stay scannable: the modules need flat contrast, so black blocks sit in a recessed or raised tile, and the camera needs a clean margin, so the quiet zone stays free of texture. The slicer sees a QR as a logo shape: the modules must be wide enough for the nozzle, and a too-fine draft smears the pattern. The rules are contrast, size, and quiet: keep the modules square and crisp, print the code large enough, and leave the border clean. A printed QR needs flat, bold, and quiet.",
        "real_world_application": "Printed jigs and tools carry scannable QR links to docs.",
        "common_misconceptions": [
            "Any QR size scans (modules must clear the nozzle width)",
            "Texture around the code is fine (the quiet zone must stay clean)",
            "Raised modules are best (flat contrast scans best)",
        ],
        "teaching_strategy": "Show the module grid, then the clean border.",
        "script": "QR codes print if they stay scannable: the modules need flat contrast, so black blocks sit in a recessed or raised tile, and the camera needs a clean margin, so the quiet zone stays free of texture. The slicer sees a QR as a logo shape: the modules must be wide enough for the nozzle, and a too-fine draft smears the pattern. The rules are contrast, size, and quiet: keep the modules square and crisp, print the code large enough, and leave the border clean. A printed QR needs flat, bold, and quiet.",
        "text_overlay": [
            "FLAT CONTRAST SCANS",
            "MODULES NEED NOZZLE WIDTH",
            "KEEP THE QUIET ZONE CLEAN",
            "FLAT, BOLD, QUIET",
        ],
        "scenes": [
            {
                "goal": "Hook: the scanning code",
                "teaching_point": "It must read on the first try",
                "shot": "close-up shot of a printed QR code",
                "motion": "camera pans to the scanner",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed QR", "scanner phone", "module grid"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printed QR code being scanned, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The modules",
                "teaching_point": "Blocks need nozzle width",
                "shot": "diagram-style shot of the module grid",
                "motion": "modules scale to the nozzle size",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["module blocks", "nozzle width", "crisp grid"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of QR module sizing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The smear",
                "teaching_point": "Fine drafts blur the pattern",
                "shot": "diagram-style shot of the smeared code",
                "motion": "too-fine draft fuses the blocks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fused blocks", "smear pattern", "failed scan"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a smeared QR print, clean engineering visualization on a dark background",
            },
            {
                "goal": "The quiet",
                "teaching_point": "The border stays clean",
                "shot": "diagram-style shot of the quiet zone",
                "motion": "clean margin rings the code",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["quiet zone", "clean margin", "raised tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a QR quiet zone, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Flat, bold, and quiet",
                "shot": "wide hero shot of labeled tools",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["labeled jig", "QR tile", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of tools with printed QR labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed QR code with crisp modules and a clean border",
            "subject": "QR codes and logos",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "code left, scanner right",
            "text": "FLAT, BOLD, QUIET",
            "elements": ["crisp modules", "raised tile", "scanner phone"],
            "style": "geometry studio photography",
            "mood": "crisp, flat, scannable",
            "prompt": "photograph of a printed QR code with crisp black modules on a raised tile with a clean quiet zone and a scanner checking it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "QR Codes & Logos: Flat, Bold, and Quiet",
            "title_variations": [
                "How to Print a QR Code",
                "Scannable QR on Prints",
                "Logo on 3D Prints",
                "Embedded QR Tile",
                "Relief Logo Design",
            ],
            "description": "QR codes print if they stay scannable: the modules need flat contrast, so black blocks sit in a recessed or raised tile, and the camera needs a clean margin, so the quiet zone stays free of texture. The slicer sees a QR as a logo shape: the modules must be wide enough for the nozzle, and a too-fine draft smears the pattern. The rules are contrast, size, and quiet: keep the modules square and crisp, print the code large enough, and leave the border clean. This short sizes the modules, clears the border, and scans the result. A printed QR needs flat, bold, and quiet.",
            "hashtags": ["#QRCode", "#Logos", "#3DPrinting", "#Embedded"],
            "seo_keywords": [
                "how to print a QR code",
                "qr code print",
                "logo on print",
                "embedded logo",
                "relief logo",
                "scannable printed qr",
                "qr quiet zone print",
            ],
        },
        "fact_check": [
            "Modules need flat contrast.",
            "Nozzle width sets module size.",
            "Fine drafts smear the pattern.",
            "The quiet zone stays clean.",
            "Raised tiles scan well.",
        ],
    },
    {
        "topic": "Tolerance Stacks",
        "core_question": "What is a tolerance stack?",
        "learning_objective": "The viewer understands tolerance stacks.",
        "engineering_summary": "A tolerance stack is error adding up: every part in a chain carries a small variation, and when the parts line up, the variations add, so three parts at a tenth of a millimeter each stack into a gap or interference. The analysis is worst case: take every limit at its extreme and sum the chain; the statistical method lets real distributions share the slack. The rules are chain length, limits, and analysis: shorter chains stack less, tight limits cost more, and the analysis decides the callouts. Tolerances add even when you do not.",
        "real_world_application": "Assemblies with many parts need stack analysis to fit.",
        "common_misconceptions": [
            "Tolerances cancel out (errors add in the same direction)",
            "Tight limits everywhere is free (each one costs money)",
            "Worst case never happens (it happens in production)",
        ],
        "teaching_strategy": "Show the parts adding up, then the analysis table.",
        "script": "A tolerance stack is error adding up: every part in a chain carries a small variation, and when the parts line up, the variations add, so three parts at a tenth of a millimeter each stack into a gap or interference. The analysis is worst case: take every limit at its extreme and sum the chain; the statistical method lets real distributions share the slack. The rules are chain length, limits, and analysis: shorter chains stack less, tight limits cost more, and the analysis decides the callouts. Tolerances add even when you do not.",
        "text_overlay": [
            "ERROR ADDS UP",
            "THREE TENTHS BECOME A GAP",
            "WORST CASE OR STATISTICAL",
            "SHORTER CHAINS STACK LESS",
        ],
        "scenes": [
            {
                "goal": "Hook: the stacked parts",
                "teaching_point": "Every part adds a little",
                "shot": "close-up shot of a three-part assembly",
                "motion": "camera pans the stacked chain",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stacked parts", "assembly chain", "joint gap"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a stacked three-part assembly, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The add",
                "teaching_point": "Variations sum up",
                "shot": "diagram-style shot of the stack math",
                "motion": "three variations add into one gap",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["variation bars", "sum arrow", "resulting gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tolerance stack addition, clean engineering visualization on a dark background",
            },
            {
                "goal": "The analysis",
                "teaching_point": "Worst case versus statistical",
                "shot": "diagram-style shot of the two methods",
                "motion": "worst case sums extremes, statistics spreads",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["worst case bar", "statistics curve", "method split"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of worst case versus statistical analysis, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cost",
                "teaching_point": "Tight limits cost more",
                "shot": "diagram-style shot of the cost curve",
                "motion": "cost climbs as limits tighten",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cost curve", "tight limit", "price mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of tolerance cost rising, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Analyze before you build",
                "shot": "wide hero shot of the fitted assembly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fitted assembly", "clean joint", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a perfectly fitted assembly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three stacked parts with a gap and a dial indicator at the joint",
            "subject": "tolerance stacks",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "parts left, indicator right",
            "text": "ERROR ADDS UP",
            "elements": ["stacked parts", "joint gap", "dial indicator"],
            "style": "geometry studio photography",
            "mood": "added, analyzed, fitted",
            "prompt": "photograph of three stacked machined parts with a gap and a dial indicator showing the accumulated error at the joint, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Tolerance Stacks: Error Adds Up",
            "title_variations": [
                "What Is a Tolerance Stack",
                "Tolerance Stack Up Analysis",
                "Fit Accumulation Explained",
                "Worst Case vs Statistical",
                "Assembly Tolerance Analysis",
            ],
            "description": "A tolerance stack is error adding up: every part in a chain carries a small variation, and when the parts line up, the variations add, so three parts at a tenth of a millimeter each stack into a gap or interference. The analysis is worst case: take every limit at its extreme and sum the chain; the statistical method lets real distributions share the slack. The rules are chain length, limits, and analysis: shorter chains stack less, tight limits cost more, and the analysis decides the callouts. This short sums the chain, runs the analysis, and fits the assembly. Tolerances add even when you do not.",
            "hashtags": ["#ToleranceStacks", "#GD&T", "#Engineering", "#Assembly"],
            "seo_keywords": [
                "what is a tolerance stack",
                "tolerance stack",
                "stack up",
                "tolerance analysis",
                "fit accumulation",
                "worst case tolerance analysis",
                "statistical tolerance stack",
            ],
        },
        "fact_check": [
            "Errors add in a chain.",
            "Three parts can stack a gap.",
            "Worst case sums extremes.",
            "Statistics shares the slack.",
            "Tight limits cost more.",
        ],
    },
    {
        "topic": "Shim & Spacer Fit",
        "core_question": "How are shims used?",
        "learning_objective": "The viewer understands shim and spacer fit.",
        "engineering_summary": "Shims are the precision fix: a thin flat piece slips under or beside a part to close a gap, kill a wobble, or set an exact position, and stacking shims tunes the fit in tiny steps. A spacer fills a fixed gap at build time; a shim adjusts on the spot, and printed shims are cheap because thickness is just another layer. The rules are thickness, flatness, and stack count: measure the gap, add shims to the target, and keep the stack parallel. Shims turn a sloppy fit into a tuned one.",
        "real_world_application": "Machine feet and brackets are shimmed for alignment.",
        "common_misconceptions": [
            "Shims and spacers are the same (shims adjust, spacers fill)",
            "One thick shim beats a stack (parallel stacks stay flat)",
            "Shims are metal only (printed shims tune fits cheaply)",
        ],
        "teaching_strategy": "Show the gap measurement, then the tuned stack.",
        "script": "Shims are the precision fix: a thin flat piece slips under or beside a part to close a gap, kill a wobble, or set an exact position, and stacking shims tunes the fit in tiny steps. A spacer fills a fixed gap at build time; a shim adjusts on the spot, and printed shims are cheap because thickness is just another layer. The rules are thickness, flatness, and stack count: measure the gap, add shims to the target, and keep the stack parallel. Shims turn a sloppy fit into a tuned one.",
        "text_overlay": [
            "THE PRECISION FIX",
            "SHIMS ADJUST, SPACERS FILL",
            "MEASURE, ADD, TUNE",
            "TINY STEPS TO PERFECT FIT",
        ],
        "scenes": [
            {
                "goal": "Hook: the wobbly part",
                "teaching_point": "Close the gap, kill the wobble",
                "shot": "close-up shot of a shimmed bracket",
                "motion": "camera pans to the thin shims",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["shimmed bracket", "thin shims", "gap line"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a bracket shimmed with thin shims, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The tune",
                "teaching_point": "Stacking sets the height",
                "shot": "diagram-style shot of the shim stack",
                "motion": "shims add up to the target height",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shim stack", "height target", "tiny steps"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of stacking shims, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pair",
                "teaching_point": "Shim versus spacer",
                "shot": "diagram-style shot of the two jobs",
                "motion": "spacer fills, shim adjusts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["spacer block", "adjusting shim", "job split"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of shims versus spacers, clean engineering visualization on a dark background",
            },
            {
                "goal": "The print",
                "teaching_point": "Thickness is just a layer",
                "shot": "diagram-style shot of a printed shim",
                "motion": "shim layers build the exact height",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["printed shim", "layer lines", "exact height"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a printed shim, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Tune the fit",
                "shot": "wide hero shot of the aligned machine",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["aligned machine", "level bracket", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an aligned shimmed machine, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Thin shims stacked under a bracket with a feeler gauge",
            "subject": "shim and spacer fit",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "stack left, gauge right",
            "text": "SHIMS ADJUST, SPACERS FILL",
            "elements": ["thin shims", "bracket base", "feeler gauge"],
            "style": "geometry studio photography",
            "mood": "stacked, tuned, aligned",
            "prompt": "photograph of thin brass shims stacked under a bracket with a feeler gauge checking the gap between the parts, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Shim & Spacer Fit: Tiny Steps to a Tuned Fit",
            "title_variations": [
                "How Are Shims Used",
                "Shimming Basics",
                "Alignment Shim Guide",
                "Shim vs Spacer",
                "Tune a Loose Fit",
            ],
            "description": "Shims are the precision fix: a thin flat piece slips under or beside a part to close a gap, kill a wobble, or set an exact position, and stacking shims tunes the fit in tiny steps. A spacer fills a fixed gap at build time; a shim adjusts on the spot, and printed shims are cheap because thickness is just another layer. The rules are thickness, flatness, and stack count: measure the gap, add shims to the target, and keep the stack parallel. This short measures the gap, stacks the shims, and tunes the fit. Shims turn a sloppy fit into a tuned one.",
            "hashtags": ["#Shims", "#Spacers", "#Fitting", "#Workshop"],
            "seo_keywords": [
                "how are shims used",
                "shim",
                "spacer",
                "shimming",
                "alignment shim",
                "shim vs spacer difference",
                "printed shim tuning",
            ],
        },
        "fact_check": [
            "Shims close gaps.",
            "Shims adjust, spacers fill.",
            "Stacks tune in tiny steps.",
            "Printed shims are cheap.",
            "Keep the stack parallel.",
        ],
    },
    {
        "topic": "Slicer Skeleton: G-Code Paths",
        "core_question": "How does a slicer plan print paths?",
        "learning_objective": "The viewer understands slicer G-code paths.",
        "engineering_summary": "The slicer plans the toolpath like a skeleton: it slices the model into layers, then sketches the moves the nozzle will make, drawing outlines first and filling the interior with hatch lines. The path has two kinds of moves: print moves lay down plastic while travel moves rush the nozzle across open air, and every move is a decision about speed, retraction, and order. The rules are perimeter, infill, and travel: walls get the outline, infill fills the inside, and smart travel keeps the nozzle out of the part. The path is the print.",
        "real_world_application": "Slicer previews show the exact moves before the print starts.",
        "common_misconceptions": [
            "G-code is magic (it is a planned toolpath)",
            "Infill comes first (the outline prints first)",
            "Travel moves are free (they set speed and retraction)",
        ],
        "teaching_strategy": "Show the preview path, then the move types.",
        "script": "The slicer plans the toolpath like a skeleton: it slices the model into layers, then sketches the moves the nozzle will make, drawing outlines first and filling the interior with hatch lines. The path has two kinds of moves: print moves lay down plastic while travel moves rush the nozzle across open air, and every move is a decision about speed, retraction, and order. The rules are perimeter, infill, and travel: walls get the outline, infill fills the inside, and smart travel keeps the nozzle out of the part. The path is the print.",
        "text_overlay": [
            "THE PATH IS THE PRINT",
            "OUTLINES FIRST, HATCH AFTER",
            "PRINT MOVES AND TRAVEL MOVES",
            "PLAN, PREVIEW, PRINT",
        ],
        "scenes": [
            {
                "goal": "Hook: the preview",
                "teaching_point": "See the path before plastic",
                "shot": "close-up shot of a slicer preview",
                "motion": "camera pans the highlighted moves",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["slicer preview", "toolpath lines", "layer view"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a slicer toolpath preview, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The skeleton",
                "teaching_point": "Outlines first, then fill",
                "shot": "diagram-style shot of the path order",
                "motion": "outline draws, hatch fills inside",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["outline loop", "hatch lines", "layer slice"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of slicer path order, clean engineering visualization on a dark background",
            },
            {
                "goal": "The moves",
                "teaching_point": "Print versus travel",
                "shot": "diagram-style shot of the move types",
                "motion": "print lines lay plastic, travel jumps",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["print moves", "travel jumps", "move legend"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of print and travel moves, clean engineering visualization on a dark background",
            },
            {
                "goal": "The decisions",
                "teaching_point": "Speed, retraction, order",
                "shot": "diagram-style shot of the move settings",
                "motion": "sliders tune every move",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["speed slider", "retraction dial", "order list"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of slicer move settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Read the path",
                "shot": "wide hero shot of a finished print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished print", "clean walls", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished print matching its preview, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A slicer toolpath with outline and infill moves highlighted",
            "subject": "slicer g-code paths",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "preview left, moves right",
            "text": "THE PATH IS THE PRINT",
            "elements": ["toolpath view", "outline loop", "infill hatch"],
            "style": "geometry studio photography",
            "mood": "planned, traced, printed",
            "prompt": "photograph of a slicer toolpath view showing the outline and infill moves with the nozzle path highlighted on the screen, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Slicer Skeleton: G-Code Paths — The Path Is the Print",
            "title_variations": [
                "How a Slicer Plans Paths",
                "G-Code Toolpaths Explained",
                "Print Moves vs Travel",
                "Read Slicer Preview",
                "Slicer Path Planning",
            ],
            "description": "The slicer plans the toolpath like a skeleton: it slices the model into layers, then sketches the moves the nozzle will make, drawing outlines first and filling the interior with hatch lines. The path has two kinds of moves: print moves lay down plastic while travel moves rush the nozzle across open air, and every move is a decision about speed, retraction, and order. The rules are perimeter, infill, and travel: walls get the outline, infill fills the inside, and smart travel keeps the nozzle out of the part. This short traces the outline, fills the hatch, and reads the preview. The path is the print.",
            "hashtags": ["#Slicer", "#GCode", "#Toolpath", "#3DPrinting"],
            "seo_keywords": [
                "how a slicer plans print paths",
                "g-code paths",
                "slicer skeleton",
                "print moves",
                "toolpath",
                "slicer preview reading",
                "travel moves vs print moves",
            ],
        },
        "fact_check": [
            "Slicers sketch every move.",
            "Outlines print first.",
            "Infill fills the inside.",
            "Travel moves cross open air.",
            "The path is the print.",
        ],
    },
]