"""Batch 47: dual extrusion and ooze, material creep and deformation, stress relaxation, PA-CF in practice, HIPS support, flexible versus rigid materials, PLA colorants and dyes, additive masterbatches."""

CURATED = [
    # ======================================================================
    {
        "topic": "Dual Extrusion & Ooze",
        "core_question": "Why does dual extrusion ooze?",
        "learning_objective": "The viewer understands dual extrusion and ooze.",
        "engineering_summary": "Dual extrusion runs two hotends, but hot plastic does not stay put: when the idle nozzle sits at temperature, molten filament drips from the tip, and the blob lands on the print, so machines add a prime tower and a wipe wall to catch the drips. The fix is retraction: the idle hotend pulls its filament back, and the nozzle parks over the tower between moves. The rules are temperature, retraction, and timing: lower temps ooze less, more retraction dries the tip, and the tower primes the flow before each return. Two nozzles, one job: keep the idle one dry.",
        "real_world_application": "Multi-color and multi-material prints rely on towers and wipes.",
        "common_misconceptions": [
            "Two nozzles double the speed (they double the ooze problem)",
            "Retraction is optional (the idle tip drips)",
            "Towers are waste (they prime the flow)",
        ],
        "teaching_strategy": "Show the dripping idle nozzle, then the tower catching it.",
        "script": "Dual extrusion runs two hotends, but hot plastic does not stay put: an idle hotend at temperature drips molten filament, and the blob lands on the print, so machines use a prime tower and wipe wall to catch the drips. The fix is retraction: the idle hotend pulls its filament back, and the nozzle parks over the tower between moves. The rules are temperature, retraction, and timing: lower temps ooze less, more retraction dries the tip, and the tower primes flow before each return. Two nozzles, one job: keep the idle one dry.",
        "text_overlay": [
            "TWO HOTENDS, ONE JOB",
            "IDLE NOZZLES DRIP",
            "PRIME TOWER CATCHES THE OOZE",
            "RETRACT, PARK, PRIME",
        ],
        "scenes": [
            {
                "goal": "Hook: the dripping nozzle",
                "teaching_point": "Idle plastic does not stay put",
                "shot": "close-up shot of a dual-nozzle head",
                "motion": "camera pans to the drips",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dual nozzle head", "molten drip", "hotend pair"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dual-nozzle print head with a molten drip, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The ooze",
                "teaching_point": "Heat makes filament flow",
                "shot": "diagram-style shot of the dripping tip",
                "motion": "molten drop forms and falls",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["molten drop", "idle nozzle", "falling blob"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an oozing idle nozzle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tower",
                "teaching_point": "Catch the drips",
                "shot": "diagram-style shot of the prime tower",
                "motion": "tower catches the drip before the print",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["prime tower", "wipe wall", "parked nozzle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a prime tower catching ooze, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Retract, park, prime",
                "shot": "diagram-style shot of the retraction cycle",
                "motion": "filament pulls back, nozzle parks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["retraction arrow", "park position", "prime flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dual extrusion retraction, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Keep the idle tip dry",
                "shot": "wide hero shot of a multi-color print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["multi-color print", "clean surface", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean multi-color 3D print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A dual-nozzle head with a prime tower catching dripping filament",
            "subject": "dual extrusion and ooze",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "head left, tower right",
            "text": "KEEP THE IDLE TIP DRY",
            "elements": ["dual nozzle head", "prime tower", "molten drip"],
            "style": "geometry studio photography",
            "mood": "dripped, parked, primed",
            "prompt": "photograph of a dual-nozzle print head with a prime tower and molten filament dripping beside the parked nozzle, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dual Extrusion & Ooze: Keep the Idle Tip Dry",
            "title_variations": [
                "Why Does Dual Extrusion Ooze",
                "Prime Tower Explained",
                "Ooze Control on Dual Nozzles",
                "Dual Extrusion Basics",
                "Stop Filament Dripping",
            ],
            "description": "Dual extrusion runs two hotends, but hot plastic does not stay put: when the idle nozzle sits at temperature, molten filament drips from the tip and the blob lands on the print, so machines add a prime tower and a wipe wall to catch the drips. The fix is retraction: the idle hotend pulls its filament back a few millimeters, and the nozzle parks over the tower between moves. This short parks the nozzle, catches the drips, and primes the flow before every return. The rules are temperature, retraction, and timing.",
            "hashtags": ["#DualExtrusion", "#3DPrinting", "#OozeControl", "#PrimeTower"],
            "seo_keywords": [
                "why does dual extrusion ooze",
                "dual extrusion",
                "ooze",
                "prime tower",
                "dual nozzle",
                "dual extrusion retraction",
                "stop filament oozing",
            ],
        },
        "fact_check": [
            "Idle nozzles drip.",
            "Towers catch the ooze.",
            "Retraction dries the tip.",
            "Lower temps ooze less.",
            "Prime flow before return.",
        ],
    },
    {
        "topic": "Material Creep & Deformation",
        "core_question": "What is material creep in prints?",
        "learning_objective": "The viewer understands material creep and deformation.",
        "engineering_summary": "Creep is slow plastic flow: a printed part under a steady load bends a little more every day, because the polymer chains slide past each other over time, even at room temperature. The classic victim is the shelf bracket: it holds for a month, then sags, and the failure is not a snap but a slow droop. The rules are stress, heat, and time: higher load creeps faster, warmth speeds the slide, and hours turn to sag. Design against creep with low stress, cooling, and geometry, because time is a load too.",
        "real_world_application": "Shelf brackets and clamps sag long before they snap.",
        "common_misconceptions": [
            "Plastic fails by snapping (it often sags slowly)",
            "Creep needs heat (it happens at room temperature)",
            "A part that holds stays holding (time keeps bending it)",
        ],
        "teaching_strategy": "Show the loaded bracket, then the slow droop.",
        "script": "Creep is slow plastic flow: a printed part under a steady load bends a little more every day, because the polymer chains slide past each other over time, even at room temperature. The classic victim is the shelf bracket: it holds for a month, then sags, and the failure is not a snap but a slow droop. The rules are stress, heat, and time: higher load creeps faster, warmth speeds the slide, and hours turn to sag. Design against creep with low stress, cooling, and geometry, because time is a load too.",
        "text_overlay": [
            "SLOW PLASTIC FLOW",
            "TIME IS A LOAD",
            "THE BRACKET SAGS, IT DOES NOT SNAP",
            "LOW STRESS, COOLING, GEOMETRY",
        ],
        "scenes": [
            {
                "goal": "Hook: the loaded shelf",
                "teaching_point": "It holds, then it sags",
                "shot": "close-up shot of a loaded printed bracket",
                "motion": "camera pans the drooping curve",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["shelf bracket", "loaded shelf", "droop curve"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a loaded printed shelf bracket, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The flow",
                "teaching_point": "Chains slide past each other",
                "shot": "diagram-style shot of polymer chains",
                "motion": "chains slide slowly under load",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["polymer chains", "slide arrows", "steady load"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of polymer chains creeping, clean engineering visualization on a dark background",
            },
            {
                "goal": "The victim",
                "teaching_point": "The bracket droops over weeks",
                "shot": "diagram-style shot of the sag timeline",
                "motion": "bracket bends a little more each month",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sag timeline", "drooping shelf", "month marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a bracket sagging over time, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Stress, heat, and time",
                "shot": "diagram-style shot of the creep factors",
                "motion": "heat and load speed the slide",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stress arrow", "heat gauge", "time clock"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of creep stress heat and time, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design against time",
                "shot": "wide hero shot of a reinforced bracket",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["reinforced bracket", "rib geometry", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a ribbed reinforced bracket, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A sagging printed bracket under a steady load",
            "subject": "material creep",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bracket left, load right",
            "text": "TIME IS A LOAD",
            "elements": ["shelf bracket", "droop curve", "steady load"],
            "style": "geometry studio photography",
            "mood": "loaded, sagged, timed",
            "prompt": "photograph of a sagging printed shelf bracket with a drooping curve and a load resting on the shelf above, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Material Creep & Deformation: Time Is a Load",
            "title_variations": [
                "What Is Material Creep",
                "Creep in 3D Prints",
                "Why Prints Sag Over Time",
                "Cold Flow in Plastic",
                "Creep vs Snap Failure",
            ],
            "description": "Creep is slow plastic flow: a printed part under a steady load bends a little more every day, because polymer chains slide past each other over time, even at room temperature. The classic victim is the shelf bracket: it holds for a month, then sags, and the failure is not a snap but a slow droop. The rules are stress, heat, and time: higher load creeps faster, warmth speeds the slide, and hours turn to sag. This short loads the bracket, watches the droop, and designs against time. Design with low stress and geometry.",
            "hashtags": ["#Creep", "#MaterialScience", "#3DPrinting", "#Engineering"],
            "seo_keywords": [
                "what is material creep in prints",
                "creep",
                "cold flow",
                "deformation",
                "load over time",
                "why do printed brackets sag",
                "plastic creep design",
            ],
        },
        "fact_check": [
            "Creep is slow flow.",
            "Time bends loaded parts.",
            "Brackets sag, not snap.",
            "Heat speeds the slide.",
            "Low stress slows creep.",
        ],
    },
    {
        "topic": "Stress Relaxation in Parts",
        "core_question": "Why do printed parts loosen over time?",
        "learning_objective": "The viewer understands stress relaxation in parts.",
        "engineering_summary": "A printed bolt and nut can loosen without turning: the plastic between the threads squeezes, relaxes slowly under that compression, and the preload fades, so the joint feels tight today and rattles next week. This is stress relaxation, the creep cousin: the part holds its shape while the internal stress bleeds away, and printed threads are the classic victims. The rules are compression, temperature, and time: high squeeze relaxes fastest, warmth speeds the bleed, and metal inserts hold what plastic forgets. Tighten once, check again.",
        "real_world_application": "Printed fasteners and clamps lose preload within days.",
        "common_misconceptions": [
            "Loosening means turning (stress fades without motion)",
            "Tightening harder fixes it (more squeeze relaxes faster)",
            "All materials hold preload (plastic forgets, metal remembers)",
        ],
        "teaching_strategy": "Show the preload fading, then the metal insert fix.",
        "script": "A printed bolt and nut can loosen without turning: the plastic between the threads squeezes, relaxes slowly under that compression, and the preload fades, so the joint feels tight today and rattles next week. This is stress relaxation, the creep cousin: the part holds its shape while the internal stress bleeds away, and printed threads are the classic victims. The rules are compression, temperature, and time: high squeeze relaxes fastest, warmth speeds the bleed, and metal inserts hold what plastic forgets. Tighten once, check again.",
        "text_overlay": [
            "LOOSE WITHOUT TURNING",
            "PRELOAD FADES IN PLASTIC",
            "THE CREEP COUSIN",
            "TIGHTEN ONCE, CHECK AGAIN",
        ],
        "scenes": [
            {
                "goal": "Hook: the rattling joint",
                "teaching_point": "Tight today, loose next week",
                "shot": "close-up shot of a printed bolt and nut",
                "motion": "camera pans to the loosened joint",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printed bolt", "printed nut", "rattling joint"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printed bolt and nut joint, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The squeeze",
                "teaching_point": "Compression builds preload",
                "shot": "diagram-style shot of thread compression",
                "motion": "threads squeeze under the nut",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thread squeeze", "compression arrows", "bolt shank"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of thread compression in a plastic joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fade",
                "teaching_point": "Stress bleeds away",
                "shot": "diagram-style shot of the preload fading",
                "motion": "stress gauge falls without turning",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stress gauge", "fading needle", "still nut"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of preload fading in plastic, clean engineering visualization on a dark background",
            },
            {
                "goal": "The fix",
                "teaching_point": "Metal inserts remember",
                "shot": "diagram-style shot of a threaded insert",
                "motion": "brass insert carries the squeeze",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["brass insert", "metal threads", "held preload"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a metal threaded insert, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Check the joint again",
                "shot": "wide hero shot of a reassembled bracket",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["rebuilt bracket", "inserted threads", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a bracket with metal thread inserts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed bolt and nut with a wrench showing preload fading",
            "subject": "stress relaxation",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "joint left, wrench right",
            "text": "LOOSE WITHOUT TURNING",
            "elements": ["printed bolt", "printed nut", "torque wrench"],
            "style": "geometry studio photography",
            "mood": "squeezed, relaxed, faded",
            "prompt": "photograph of a printed bolt and nut with a torque wrench showing the joint loosening over time, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stress Relaxation in Parts: Loose Without Turning",
            "title_variations": [
                "Why Printed Parts Loosen",
                "Bolt Preload Loss in Plastic",
                "Stress Relaxation Explained",
                "Plastic Fastener Creep",
                "Threaded Inserts for Prints",
            ],
            "description": "A printed bolt and nut can loosen without turning: the plastic between the threads squeezes, relaxes slowly under that compression, and the preload fades, so the joint feels tight today and rattles next week. This is stress relaxation, the creep cousin: the part holds its shape while the internal stress bleeds away, and printed threads are the classic victims. The rules are compression, temperature, and time: high squeeze relaxes fastest, warmth speeds the bleed, and metal inserts hold what plastic forgets. This short tightens the joint and watches it relax.",
            "hashtags": ["#StressRelaxation", "#3DPrinting", "#Fasteners", "#Creep"],
            "seo_keywords": [
                "why do printed parts loosen over time",
                "stress relaxation",
                "bolt preload loss",
                "printed fastener",
                "plastic creep",
                "threaded inserts for prints",
                "plastic fastener preload",
            ],
        },
        "fact_check": [
            "Preload fades in plastic.",
            "Loosening needs no turning.",
            "High squeeze relaxes fastest.",
            "Warmth speeds the bleed.",
            "Metal inserts hold preload.",
        ],
    },
    {
        "topic": "PA-CF in Practice",
        "core_question": "What is PA-CF filament?",
        "learning_objective": "The viewer understands PA-CF in practice.",
        "engineering_summary": "PA-CF is nylon reinforced with chopped carbon fiber: the short black strands stiffen the nylon, so the filament prints parts that are stiff, strong, and stable, where plain nylon would flex and sag. The fiber does the work and the nylon carries the toughness; the trade is hardware, because the abrasive strands eat brass nozzles in a weekend, so a hardened steel nozzle is mandatory. The rules are drying, heat, and enclosure: nylon drinks moisture, the carbon needs high temps, and drafts cause warping. Reinforced nylon means reinforced hardware.",
        "real_world_application": "Brackets, gears, and jigs are printed in PA-CF for stiffness.",
        "common_misconceptions": [
            "Carbon makes it unbreakable (it adds stiffness, not magic)",
            "Any nozzle works (brass wears in days)",
            "Dry storage is optional (nylon drinks moisture fast)",
        ],
        "teaching_strategy": "Show the fiber stiffening, then the nozzle upgrade.",
        "script": "PA-CF is nylon reinforced with chopped carbon fiber: the short black strands stiffen the nylon, so the filament prints parts that are stiff, strong, and stable, where plain nylon would flex and sag. The fiber does the work and the nylon carries the toughness; the trade is hardware, because the abrasive strands eat brass nozzles in a weekend, so a hardened steel nozzle is mandatory. The rules are drying, heat, and enclosure: nylon drinks moisture, the carbon needs high temps, and drafts cause warping. Reinforced nylon means reinforced hardware.",
        "text_overlay": [
            "NYLON WITH CARBON STRANDS",
            "STIFF, STRONG, STABLE",
            "ABRASIVE EATS BRASS",
            "HARDENED STEEL OR NOTHING",
        ],
        "scenes": [
            {
                "goal": "Hook: the black part",
                "teaching_point": "It looks like carbon",
                "shot": "close-up shot of a PA-CF bracket",
                "motion": "camera pans the matte black surface",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PA-CF bracket", "matte surface", "carbon strands"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a matte black PA-CF bracket, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The fiber",
                "teaching_point": "Short strands stiffen",
                "shot": "diagram-style shot of chopped fibers",
                "motion": "strands lock inside the nylon",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["chopped fibers", "nylon matrix", "stiffness arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of chopped carbon fiber in nylon, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Abrasion wears brass",
                "shot": "diagram-style shot of nozzle wear",
                "motion": "brass nozzle erodes, steel stays",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["brass nozzle", "steel nozzle", "wear compare"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of brass versus steel nozzle wear, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Dry, hot, enclosed",
                "shot": "diagram-style shot of the drying box",
                "motion": "moisture leaves the filament",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["drying box", "moisture arrow", "enclosed printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of drying PA-CF filament, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Reinforce the hardware",
                "shot": "wide hero shot of PA-CF parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PA-CF parts", "hardened nozzle", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of printed PA-CF parts with a hardened nozzle, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A black carbon fiber reinforced part with PA-CF filament and steel nozzle",
            "subject": "PA-CF in practice",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part left, nozzle right",
            "text": "HARDENED STEEL OR NOTHING",
            "elements": ["PA-CF part", "filament spool", "steel nozzle"],
            "style": "geometry studio photography",
            "mood": "stiff, strong, worn",
            "prompt": "photograph of a black carbon fiber reinforced nylon part next to a roll of PA-CF filament with a hardened steel nozzle, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PA-CF in Practice: Reinforced Nylon Means Reinforced Hardware",
            "title_variations": [
                "What Is PA-CF Filament",
                "Nylon Carbon Printing",
                "CF Nylon Print Guide",
                "PA-CF Nozzle Wear",
                "Engineering Filament Basics",
            ],
            "description": "PA-CF is nylon reinforced with chopped carbon fiber: the short black strands stiffen the nylon, so the filament prints parts that are stiff, strong, and stable, where plain nylon would flex and sag. The fiber does the work and the nylon carries the toughness; the trade is hardware, because the abrasive strands eat brass nozzles in a weekend, so a hardened steel nozzle is mandatory. The rules are drying, heat, and enclosure: nylon drinks moisture, the carbon needs high temps, and drafts cause warping. This short prints the part and upgrades the nozzle.",
            "hashtags": ["#PA_CF", "#CarbonFiber", "#Nylon", "#3DPrinting"],
            "seo_keywords": [
                "what is PA-CF filament",
                "pa cf",
                "nylon carbon",
                "cf nylon print",
                "engineering filament",
                "pa cf nozzle wear",
                "pa cf drying and enclosure",
            ],
        },
        "fact_check": [
            "Chopped fiber stiffens nylon.",
            "The fiber carries stiffness.",
            "Brass nozzles wear fast.",
            "Steel nozzles are required.",
            "Nylon must stay dry.",
        ],
    },
    {
        "topic": "HIPS Support Material",
        "core_question": "What is HIPS filament?",
        "learning_objective": "The viewer understands HIPS support material.",
        "engineering_summary": "HIPS is the support partner for ABS: it prints like ABS, sticks to ABS, and then dissolves away in limonene, a citrus solvent, leaving clean surfaces where breakaway supports would scar. The system is two materials: the model prints in ABS, the support in HIPS, and the solvent finds the support without touching the model, because limonene attacks HIPS but leaves ABS alone. The rules are pairing, drying, and soak time: HIPS must pair with ABS, damp filament foams, and thick supports soak for hours. The solvent does the delicate work.",
        "real_world_application": "Overhangs and cavities in ABS parts dissolve free in limonene.",
        "common_misconceptions": [
            "HIPS dissolves in water (it needs limonene)",
            "It pairs with PLA (it is tuned for ABS)",
            "Supports vanish instantly (thick supports soak for hours)",
        ],
        "teaching_strategy": "Show the paired prints, then the dissolving bath.",
        "script": "HIPS is the support partner for ABS: it prints like ABS, sticks to ABS, and then dissolves away in limonene, a citrus solvent, leaving clean surfaces where breakaway supports would scar. The system is two materials: the model prints in ABS, the support in HIPS, and the solvent finds the support without touching the model, because limonene attacks HIPS but leaves ABS alone. The rules are pairing, drying, and soak time: HIPS must pair with ABS, damp filament foams, and thick supports soak for hours. The solvent does the delicate work.",
        "text_overlay": [
            "THE ABS SUPPORT PARTNER",
            "DISSOLVES IN LIMONENE",
            "SOLVENT FINDS THE SUPPORT",
            "CLEAN SURFACES, NO SCARS",
        ],
        "scenes": [
            {
                "goal": "Hook: the paired part",
                "teaching_point": "Two materials, one print",
                "shot": "close-up shot of an ABS part with HIPS support",
                "motion": "camera pans the white support",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["ABS model", "HIPS support", "paired print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an ABS part with white HIPS support, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The partner",
                "teaching_point": "Prints like ABS, sticks to ABS",
                "shot": "diagram-style shot of the material pair",
                "motion": "two filaments merge into one print",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["ABS filament", "HIPS filament", "bonded layers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of ABS with HIPS support, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bath",
                "teaching_point": "Limonene finds the support",
                "shot": "diagram-style shot of the solvent bath",
                "motion": "support melts away, model stays",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["limonene bath", "dissolving support", "safe model"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of HIPS dissolving in limonene, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Pair, dry, and soak",
                "shot": "diagram-style shot of the soak timeline",
                "motion": "thick support fades over hours",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["soak clock", "thick support", "clean surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of HIPS soak time, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Clean surfaces win",
                "shot": "wide hero shot of the finished ABS part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished ABS part", "clean surface", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished ABS part with clean surfaces, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An ABS part with HIPS support dissolving in a limonene bath",
            "subject": "HIPS support material",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bath left, part right",
            "text": "SOLVENT FINDS THE SUPPORT",
            "elements": ["HIPS support", "limonene bath", "clean ABS part"],
            "style": "geometry studio photography",
            "mood": "paired, dissolved, clean",
            "prompt": "photograph of a printed ABS part with HIPS support being dissolved in a limonene bath with clean surfaces emerging, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "HIPS Support Material: The Solvent Does the Delicate Work",
            "title_variations": [
                "What Is HIPS Filament",
                "Dissolvable ABS Supports",
                "HIPS vs PVA Support",
                "Limonene Solvent Supports",
                "Clean Support Removal",
            ],
            "description": "HIPS is the support partner for ABS: it prints like ABS, sticks to ABS, and then dissolves away in limonene, a citrus solvent, leaving clean surfaces where breakaway supports would scar. The system is two materials: the model prints in ABS, the support in HIPS, and the solvent finds the support without touching the model, because limonene attacks HIPS but leaves ABS alone. The rules are pairing, drying, and soak time: HIPS must pair with ABS, damp filament foams, and thick supports soak for hours. This short dips the part and dissolves the support.",
            "hashtags": ["#HIPS", "#SupportMaterial", "#ABS", "#3DPrinting"],
            "seo_keywords": [
                "what is HIPS filament",
                "hips",
                "hips filament",
                "limonene supports",
                "dissolvable abs",
                "hips vs pva support",
                "hips support removal",
            ],
        },
        "fact_check": [
            "HIPS pairs with ABS.",
            "Limonene dissolves it.",
            "The model stays safe.",
            "Thick supports soak long.",
            "Damp HIPS foams.",
        ],
    },
    {
        "topic": "Flexible vs Rigid Materials",
        "core_question": "Flexible or rigid filament?",
        "learning_objective": "The viewer understands flexible versus rigid materials.",
        "engineering_summary": "Flexible and rigid filaments are two ends of one scale: shore hardness numbers the squish, from hard plastics that barely bend to rubbers that fold in half, and soft TPU needs a printer that pushes without buckling. The choice is the job: a phone case wants shock and grip, a bracket wants stiffness, and the two need different extrusion paths, since soft filament prefers direct drive at slow speeds. The rules are hardness, path, and speed: pick the shore for the flex, feed it straight, and print slow. Stiffness is a design choice.",
        "real_world_application": "Cases and gaskets flex, brackets and frames stay rigid.",
        "common_misconceptions": [
            "Softer is always better (stiff parts need rigidity)",
            "Any printer feeds soft filament (it buckles in bowden tubes)",
            "Shore hardness is a brand (it is a standardized scale)",
        ],
        "teaching_strategy": "Show the squish scale, then the extrusion path.",
        "script": "Flexible and rigid filaments are two ends of one scale: shore hardness numbers the squish, from hard plastics that barely bend to rubbers that fold in half, and soft TPU needs a printer that pushes without buckling. The choice is the job: a phone case wants shock and grip, a bracket wants stiffness, and the two need different extrusion paths, since soft filament prefers direct drive at slow speeds. The rules are hardness, path, and speed: pick the shore for the flex, feed it straight, and print slow. Stiffness is a design choice.",
        "text_overlay": [
            "ONE SCALE OF SQUISH",
            "SHORE NUMBERS THE FLEX",
            "CASE FLEXES, BRACKET STAYS",
            "STIFFNESS IS A CHOICE",
        ],
        "scenes": [
            {
                "goal": "Hook: the two parts",
                "teaching_point": "Flex versus rigid",
                "shot": "close-up shot of a TPU case and a rigid bracket",
                "motion": "camera pans between the pair",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["TPU case", "rigid bracket", "flex test"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flexible TPU case beside a rigid bracket, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The scale",
                "teaching_point": "Shore hardness ranks squish",
                "shot": "diagram-style shot of the shore scale",
                "motion": "durometer needle rides the scale",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shore scale", "durometer needle", "flex samples"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the shore hardness scale, clean engineering visualization on a dark background",
            },
            {
                "goal": "The job",
                "teaching_point": "Pick by function",
                "shot": "diagram-style shot of use cases",
                "motion": "case flexes, bracket holds load",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["shock case", "load bracket", "job tiles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flexible versus rigid use cases, clean engineering visualization on a dark background",
            },
            {
                "goal": "The path",
                "teaching_point": "Soft filament needs direct drive",
                "shot": "diagram-style shot of the extruder path",
                "motion": "soft filament buckles in a long tube",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["direct drive", "bowden tube", "buckling filament"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of direct drive feeding soft filament, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the stiffness in",
                "shot": "wide hero shot of flexible and rigid prints",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flexible prints", "rigid prints", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of flexible and rigid printed parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A flexible TPU part bending beside a stiff bracket on the shore scale",
            "subject": "flexible versus rigid materials",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "flex left, rigid right",
            "text": "STIFFNESS IS A CHOICE",
            "elements": ["TPU part", "rigid bracket", "shore scale"],
            "style": "geometry studio photography",
            "mood": "flexed, stiff, scaled",
            "prompt": "photograph of a flexible TPU part bending in half beside a stiff rigid bracket on a scale showing shore hardness, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Flexible vs Rigid Materials: Stiffness Is a Choice",
            "title_variations": [
                "Flexible or Rigid Filament",
                "Shore Hardness Explained",
                "TPU vs Rigid Plastic",
                "Flexible Filament Guide",
                "Rigid vs Flexible Parts",
            ],
            "description": "Flexible and rigid filaments are two ends of one scale: shore hardness numbers the squish, from hard plastics that barely bend to soft rubbers that fold in half, and TPU at the soft end needs a printer that can push it without buckling. The choice is the job: a phone case wants shock and grip, a bracket wants stiffness, and the two need different extrusion paths, because soft filament prefers direct drive and slow speeds. This short flexes both ends of the scale and picks the material for the job. The rules are hardness, path, and speed.",
            "hashtags": ["#TPU", "#FlexibleFilament", "#ShoreHardness", "#3DPrinting"],
            "seo_keywords": [
                "flexible or rigid filament",
                "flexible filament",
                "rigid vs flexible",
                "shore hardness",
                "tpu hardness",
                "tpu vs rigid plastic",
                "flexible filament direct drive",
            ],
        },
        "fact_check": [
            "Shore ranks the squish.",
            "Soft TPU needs direct drive.",
            "Cases want shock and grip.",
            "Brackets want stiffness.",
            "Print soft filament slow.",
        ],
    },
    {
        "topic": "PLA Colorants & Dyes",
        "core_question": "Can you dye PLA?",
        "learning_objective": "The viewer understands PLA colorants and dyes.",
        "engineering_summary": "PLA color comes from pigment mixed in at the factory: the pellet is dyed before extrusion, so every spool is a uniform batch, and the pigment sits inside the plastic, not on top, so printed color never rubs off. Dyeing finished parts is a surface game: hot dye colors the outer layers only, and light-colored prints take dye best, while dark pigment stays as it is. The rules are light parts, hot baths, and short soaks: dye penetrates a few layers deep, and sanding before the bath lets color in. Color is a batch decision.",
        "real_world_application": "Light PLA parts take hot dye baths for custom colors.",
        "common_misconceptions": [
            "Printed color rubs off (pigment is inside the plastic)",
            "Dye penetrates deeply (it colors the outer layers)",
            "Dark parts take dye (light parts take it best)",
        ],
        "teaching_strategy": "Show the pigment mix, then the dye bath.",
        "script": "PLA color comes from pigment mixed in at the factory: the pellet is dyed before extrusion, so every spool is a uniform batch, and the pigment sits inside the plastic, not on top, so printed color never rubs off. Dyeing finished parts is a surface game: hot dye colors the outer layers only, and light-colored prints take dye best, while dark pigment stays as it is. The rules are light parts, hot baths, and short soaks: dye penetrates a few layers deep, and sanding before the bath lets color in. Color is a batch decision.",
        "text_overlay": [
            "PIGMENT IS INSIDE, NOT ON TOP",
            "HOT DYE COLORS THE OUTER LAYERS",
            "LIGHT PARTS TAKE DYE BEST",
            "COLOR IS A BATCH DECISION",
        ],
        "scenes": [
            {
                "goal": "Hook: the spool wall",
                "teaching_point": "Color comes from the factory",
                "shot": "close-up shot of colorful PLA spools",
                "motion": "camera pans the spool wall",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["colorful spools", "PLA rolls", "color wall"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of colorful PLA filament spools, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The pigment",
                "teaching_point": "Mixed in, not painted on",
                "shot": "diagram-style shot of pellet coloring",
                "motion": "pigment blends through the melt",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["clear pellets", "pigment grains", "colored melt"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of pigment mixing into PLA, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bath",
                "teaching_point": "Dye colors the surface",
                "shot": "diagram-style shot of the dye bath",
                "motion": "outer layers darken, core stays",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hot dye bath", "dyed shell", "white core"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dyeing a printed part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Light parts, hot baths",
                "shot": "diagram-style shot of the dye steps",
                "motion": "sanded part dips and colors",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["light part", "sanding pass", "short soak"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the PLA dyeing steps, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match from the batch",
                "shot": "wide hero shot of dyed prints",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dyed prints", "matched parts", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of color-matched dyed PLA prints, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Colorful PLA spools beside a hot dye bath with a dipped part",
            "subject": "PLA colorants and dyes",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spools left, bath right",
            "text": "LIGHT PARTS TAKE DYE BEST",
            "elements": ["PLA spools", "dye bath", "dipped part"],
            "style": "geometry studio photography",
            "mood": "pigmented, dyed, matched",
            "prompt": "photograph of colorful PLA spools beside a dye bath with a light-colored printed part being dipped in hot dye, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PLA Colorants & Dyes: Color Is a Batch Decision",
            "title_variations": [
                "Can You Dye PLA",
                "How to Dye 3D Prints",
                "PLA Pigment Explained",
                "Custom Color Filament",
                "Dyeing Printed Parts",
            ],
            "description": "PLA color comes from pigment mixed in at the factory: the pellet is dyed before extrusion, so every spool is a uniform batch, and the pigment sits inside the plastic, not on top, which is why printed color does not rub off. Dyeing finished parts is a surface game: hot water and dye color the outer layers only, and light-colored prints take dye best. This short mixes the batch, dips the part, and shows where color lives. The rules are light parts, hot baths, and short soaks.",
            "hashtags": ["#PLA", "#Dyeing", "#3DPrinting", "#Color"],
            "seo_keywords": [
                "can you dye PLA",
                "pla colors",
                "pigments",
                "dyeing pla",
                "custom color filament",
                "how to dye 3d prints",
                "pla color matching",
            ],
        },
        "fact_check": [
            "Pigment mixes in the melt.",
            "Spools match by batch.",
            "Dye colors the surface.",
            "Light parts take dye best.",
            "Sanding opens the pores.",
        ],
    },
    {
        "topic": "Additive Masterbatches",
        "core_question": "What are masterbatches in filament?",
        "learning_objective": "The viewer understands additive masterbatches.",
        "engineering_summary": "Masterbatches are the color shot in filament: a factory takes pure plastic pellets and mixes in a masterbatch, a pellet of concentrated pigment and additives, so the color disperses evenly through the melt. It is why two spools from the same batch match: the concentrate is metered precisely, and what you see in the print was tuned at the factory. The rules are concentration, dispersion, and heat: too little concentrate washes out, poor mixing leaves streaks, and excess heat degrades the color. Color is engineered before the spool is wound.",
        "real_world_application": "Every colored spool is a masterbatch formula from the maker.",
        "common_misconceptions": [
            "Color is painted on pellets (it is concentrated and metered)",
            "More pigment means richer color (too much ruins the part)",
            "Any heat is fine (excess heat degrades the color)",
        ],
        "teaching_strategy": "Show the concentrate metering, then the mixed melt.",
        "script": "Masterbatches are the color shot in filament: a factory takes pure plastic pellets and mixes in a masterbatch, a pellet of concentrated pigment and additives, so the color disperses evenly through the melt. It is why two spools from the same batch match: the concentrate is metered precisely, and what you see in the print was tuned at the factory. The rules are concentration, dispersion, and heat: too little concentrate washes out, poor mixing leaves streaks, and excess heat degrades the color. Color is engineered before the spool is wound.",
        "text_overlay": [
            "THE COLOR SHOT",
            "CONCENTRATED AND METERED",
            "SPOOLS MATCH BY BATCH",
            "ENGINEERED BEFORE WINDING",
        ],
        "scenes": [
            {
                "goal": "Hook: the pellet pile",
                "teaching_point": "Color starts as pellets",
                "shot": "close-up shot of masterbatch pellets",
                "motion": "camera pans the colored grains",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["masterbatch pellets", "color grains", "pellet pile"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of bright masterbatch pellets, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The shot",
                "teaching_point": "Concentrate meets the melt",
                "shot": "diagram-style shot of the dosing hopper",
                "motion": "concentrate meters into clear pellets",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dosing hopper", "concentrate stream", "clear pellets"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of masterbatch dosing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The match",
                "teaching_point": "Precise metering matches spools",
                "shot": "diagram-style shot of the batch compare",
                "motion": "two spools show the same shade",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["spool pair", "shade match", "meter dial"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of matching spool shades, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Concentration, dispersion, heat",
                "shot": "diagram-style shot of the mix controls",
                "motion": "streaks fade as mixing improves",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["mix barrel", "streak sample", "heat gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of masterbatch mixing controls, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The spool is engineered",
                "shot": "wide hero shot of a wound spool",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["wound spool", "uniform color", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a freshly wound filament spool, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Masterbatch pellets metered into clear pellets with a color chart",
            "subject": "additive masterbatches",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pellets left, chart right",
            "text": "THE COLOR SHOT",
            "elements": ["masterbatch pellets", "clear pellets", "color chart"],
            "style": "geometry studio photography",
            "mood": "metered, dispersed, matched",
            "prompt": "photograph of colored masterbatch pellets being measured into clear plastic pellets with a color chart on the workbench, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Additive Masterbatches: The Color Shot in Filament",
            "title_variations": [
                "What Are Masterbatches",
                "Color Concentrate Explained",
                "How Filament Gets Its Color",
                "Masterbatch Additives",
                "Filament Production Basics",
            ],
            "description": "Masterbatches are the color shot in filament: a factory takes pure plastic pellets and mixes in a masterbatch, a pellet of concentrated pigment and additives, so the color disperses evenly through the melt. It is why two spools from the same batch match: the concentrate is metered precisely, and what you see in the print was tuned at the factory. This short meters the concentrate, mixes the melt, and shows how spools match. The rules are concentration, dispersion, and heat.",
            "hashtags": ["#Masterbatch", "#Filament", "#Color", "#Manufacturing"],
            "seo_keywords": [
                "what are masterbatches in filament",
                "masterbatch",
                "color concentrate",
                "filament production",
                "additives plastic",
                "how filament gets its color",
                "masterbatch dosage",
            ],
        },
        "fact_check": [
            "Concentrate meters into pellets.",
            "Spools match by batch.",
            "Poor mixing leaves streaks.",
            "Excess heat degrades color.",
            "Color is engineered early.",
        ],
    },
]