"""Batch 28: magnetic beds, dual Z, couplings, extruder gears, nozzle diameter, heated chambers, frame stiffness, aluminum extrusion."""

CURATED = [
    # ======================================================================
    {
        "topic": "Magnetic Beds",
        "core_question": "Why do printers fall in love with magnetic beds?",
        "learning_objective": "The viewer understands magnetic bed systems and spring steel plates.",
        "engineering_summary": "A magnetic bed pairs a magnet sheet with a flexible steel plate: the plate snaps down flat for printing and peels off for flexing prints loose. The steel gives a flat, stiff surface that keeps its shape, and the magnet holds it without clips. Bed heat passes through the steel quickly, so the surface tracks the heater. The plate pops off, the print flexes, and the bed is clean. Simple and repeatable.",
        "real_world_application": "Most modern printers use spring steel plates on magnetic beds for easy removal.",
        "common_misconceptions": [
            "The magnet does the printing work (the steel plate does, the magnet holds)",
            "Flexible means floppy (spring steel snaps back flat)",
            "Magnets weaken with heat (bed heat is well within their range)",
        ],
        "teaching_strategy": "Snap a plate on, print, peel the plate off, and flex the part free.",
        "script": "A magnetic bed pairs a magnet sheet with a flexible steel plate: the plate snaps down flat for printing and peels off for flexing prints loose. The steel gives a flat, stiff surface that keeps its shape, and the magnet holds it without clips. Bed heat passes through the steel quickly, so the surface tracks the heater. The plate pops off, the print flexes, and the bed is clean. Simple and repeatable.",
        "text_overlay": [
            "MAGNET HOLDS, STEEL PRINTS",
            "SNAPS FLAT, PEELS OFF",
            "HEAT TRACKS THE HEATER",
            "FLEX THE PART FREE",
        ],
        "scenes": [
            {
                "goal": "Hook: the plate peel",
                "teaching_point": "Peel, flex, done",
                "shot": "medium shot of a steel plate peeling off a magnetic bed",
                "motion": "plate bends off the magnet",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["steel plate", "magnetic bed", "printed part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a steel plate peeling off a magnetic bed, neutral lab lighting, print lab",
            },
            {
                "goal": "The pair",
                "teaching_point": "Magnet holds, steel prints",
                "shot": "diagram-style shot of the magnet sheet and steel plate stack",
                "motion": "layers snap together",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["magnet sheet", "steel plate", "bed stack"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a magnetic bed stack, clean engineering visualization on a dark background",
            },
            {
                "goal": "The heat",
                "teaching_point": "Steel tracks the heater",
                "shot": "diagram-style shot of heat passing through the plate",
                "motion": "heat flows plate to surface",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heater", "steel plate", "heat arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of heat passing through a magnetic bed plate, clean engineering visualization on a dark background",
            },
            {
                "goal": "The flex",
                "teaching_point": "Bend it, part pops",
                "shot": "close-up shot of a plate flexing to release a part",
                "motion": "part pops free from the bend",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["flexed plate", "part", "pop release"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a plate flexing to release a printed part, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Simple and repeatable",
                "shot": "wide hero shot of a magnetic bed with its plate on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["magnetic bed", "steel plate", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a magnetic bed with its steel plate on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A steel plate snapping onto a magnetic bed with a flexed part release",
            "subject": "magnetic bed system",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bed center, plate angled off",
            "text": "SNAP, PRINT, PEEL",
            "elements": ["magnetic bed", "steel plate", "printed part"],
            "style": "geometry studio photography",
            "mood": "snapped, flexible, clean",
            "prompt": "photograph of a steel plate snapping onto a magnetic bed with a flexed part releasing, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Magnetic Beds: Snap, Print, Peel",
            "title_variations": [
                "Are Magnetic Beds Good",
                "Magnetic Bed Explained",
                "Spring Steel Print Plate",
                "Flexible Print Surfaces",
                "Magnetic Bed vs Glass",
            ],
            "description": "A magnetic bed pairs a magnet sheet with a flexible steel plate: the plate snaps down flat for printing and peels off for flexing prints loose. The steel stays flat and stiff, the magnet holds it without clips, and bed heat passes through quickly so the surface tracks the heater. This short snaps a plate on, prints, peels it off, and flexes the part free, showing why magnetic beds made clips obsolete.",
            "hashtags": ["#MagneticBed", "#3DPrinting", "#SpringSteel", "#PrintSurface"],
            "seo_keywords": [
                "are magnetic beds good",
                "magnetic bed explained",
                "spring steel print plate",
                "flexible print surface",
                "magnetic bed vs glass",
                "peel print plate",
                "magnet sheet steel plate",
            ],
        },
        "fact_check": [
            "Magnetic beds use a magnet sheet and steel plate.",
            "The plate snaps flat for printing.",
            "The plate peels off for removal.",
            "Heat passes through the steel quickly.",
            "Flexing the plate releases prints.",
        ],
    },
    {
        "topic": "Dual Z-Axis",
        "core_question": "Do you really need a second Z motor?",
        "learning_objective": "The viewer understands dual Z benefits and alignment requirements.",
        "engineering_summary": "A single Z motor drives one screw, and the gantry can sag on the far side, tilting the print. A dual Z axis adds a second lead screw so both sides lift together, which stops sag and tilt. The catch: the two screws must stay synchronized, or the gantry binds and the printer loses level. Dual Z helps heavy toolheads and tall prints. Two screws, one goal: both sides rise as one.",
        "real_world_application": "Large-format and heavy-toolhead printers use dual Z to keep gantries level.",
        "common_misconceptions": [
            "Dual Z always fixes layer lines (misaligned screws make it worse)",
            "Two motors double the torque (one motor can drive both screws)",
            "Any dual Z installs cleanly (synchronization is the whole game)",
        ],
        "teaching_strategy": "Lift a gantry on one screw and show the tilt, then add the second.",
        "script": "A single Z motor drives one screw, and the gantry can sag on the far side, tilting the print. A dual Z axis adds a second lead screw so both sides lift together, which stops sag and tilt. The catch: the two screws must stay synchronized, or the gantry binds and the printer loses level. Dual Z helps heavy toolheads and tall prints. Two screws, one goal: both sides rise as one.",
        "text_overlay": [
            "ONE SCREW, ONE SIDE",
            "FAR SIDE SAGS, PRINT TILTS",
            "TWO SCREWS MUST SYNC",
            "BOTH SIDES RISE AS ONE",
        ],
        "scenes": [
            {
                "goal": "Hook: the tilted gantry",
                "teaching_point": "One screw, one sag",
                "shot": "medium shot of a gantry sagging on its far side",
                "motion": "far side drops as the screw lifts",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["gantry", "lead screw", "tilt"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a gantry sagging on its far side, neutral lab lighting, print lab",
            },
            {
                "goal": "The pair",
                "teaching_point": "Two screws, level lift",
                "shot": "diagram-style shot of a dual Z gantry with two screws",
                "motion": "both screws rise together",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dual Z gantry", "two screws", "level bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a dual Z gantry, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sync",
                "teaching_point": "Sync or bind",
                "shot": "diagram-style shot of misaligned screws binding the gantry",
                "motion": "gantry cocks between the screws",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["misaligned screws", "binding gantry", "cock angle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of misaligned dual Z screws, clean engineering visualization on a dark background",
            },
            {
                "goal": "The payoff",
                "teaching_point": "Heavy heads and tall prints",
                "shot": "medium shot of a heavy toolhead printing on a dual Z machine",
                "motion": "toolhead moves, gantry level",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["heavy toolhead", "dual Z printer", "level gantry"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a heavy toolhead printing on a dual Z machine, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Both sides rise as one",
                "shot": "wide hero shot of a dual Z printer frame",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dual Z frame", "lead screws", "gantry"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dual Z printer frame, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A gantry with two lead screws lifting both sides level",
            "subject": "dual Z axis",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gantry center, screws both sides",
            "text": "BOTH SIDES RISE AS ONE",
            "elements": ["gantry", "two lead screws", "level bar"],
            "style": "geometry studio photography",
            "mood": "lifted, synchronized, level",
            "prompt": "photograph of a gantry with two lead screws lifting both sides level and a level bar, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dual Z-Axis: Both Sides Rise as One",
            "title_variations": [
                "Do I Need Dual Z",
                "Dual Z Axis Explained",
                "Dual Z for Printers",
                "Z Axis Sag Fix",
                "Dual Lead Screw Setup",
            ],
            "description": "A single Z motor drives one screw, letting the gantry sag on the far side and tilt the print. A dual Z axis adds a second lead screw so both sides lift together, stopping sag and tilt for heavy toolheads and tall prints. The catch is synchronization: misaligned screws bind the gantry and make things worse. This short tilts a gantry on one screw, adds the second, and shows the level lift.",
            "hashtags": ["#DualZ", "#3DPrinting", "#ZAxis", "#PrinterUpgrade"],
            "seo_keywords": [
                "do i need dual z",
                "dual z axis",
                "dual z printer",
                "z axis sag",
                "dual lead screw",
                "gantry level lift",
                "dual z sync",
            ],
        },
        "fact_check": [
            "A single Z screw lets the gantry sag.",
            "Dual Z lifts both sides together.",
            "The screws must stay synchronized.",
            "Misaligned screws bind the gantry.",
            "Dual Z suits heavy toolheads and tall prints.",
        ],
    },
    {
        "topic": "Flexible Couplings",
        "core_question": "Why does a straight shaft need a bendy joint?",
        "learning_objective": "The viewer understands flexible couplings and their misalignment tolerance.",
        "engineering_summary": "A flexible coupling joins a motor shaft to a lead screw, forgiving small misalignments that rigid joints cannot. Motors and screws are never perfectly aligned: they are off by fractions, and a rigid link turns that into binding and wear. The coupling flexes to absorb the offset while still turning the screw, like a wrist that bends but still passes motion. Alignment matters, but the coupling buys forgiveness.",
        "real_world_application": "Every Z axis, pump, and encoder shaft runs through a flexible coupling.",
        "common_misconceptions": [
            "Couplings fix any misalignment (they forgive small offsets, not big ones)",
            "Rigid joints are more precise (they transmit the binding too)",
            "Couplings are weak links (they are engineered to twist and hold)",
        ],
        "teaching_strategy": "Mount a motor and screw with a slight offset and show the coupling flex.",
        "script": "A flexible coupling joins a motor shaft to a lead screw, forgiving small misalignments that rigid joints cannot. Motors and screws are never perfectly aligned: they are off by fractions, and a rigid link turns that into binding and wear. The coupling flexes to absorb the offset while still turning the screw, like a wrist that bends but still passes motion. Alignment matters, but the coupling buys forgiveness.",
        "text_overlay": [
            "MOTOR TO SCREW",
            "OFF BY FRACTIONS",
            "RIGID LINKS BIND",
            "THE WRIST THAT PASSES MOTION",
        ],
        "scenes": [
            {
                "goal": "Hook: the bent wrist",
                "teaching_point": "Bends but still drives",
                "shot": "close-up shot of a flexible coupling driving a lead screw",
                "motion": "coupling flexes as the screw turns",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["flexible coupling", "lead screw", "motor shaft"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a flexible coupling driving a lead screw, bright task lighting, print lab",
            },
            {
                "goal": "The offset",
                "teaching_point": "Shafts are off by fractions",
                "shot": "diagram-style shot of misaligned shafts exaggerated",
                "motion": "offset gap highlights",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["motor shaft", "screw shaft", "offset gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of misaligned shafts and a coupling, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bind",
                "teaching_point": "Rigid links bind",
                "shot": "diagram-style shot of a rigid joint cocking under offset",
                "motion": "rigid joint strains",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["rigid joint", "strain marks", "binding angle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a rigid joint binding, clean engineering visualization on a dark background",
            },
            {
                "goal": "The flex",
                "teaching_point": "Absorb and turn",
                "shot": "diagram-style shot of a coupling flexing around the offset",
                "motion": "coupling bends and rotates",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flexing coupling", "offset path", "rotation"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a coupling flexing around misalignment, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Forgiveness, not precision",
                "shot": "wide hero shot of couplings on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flexible couplings", "lead screws", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of flexible couplings and lead screws on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A flexible coupling joining a motor shaft to a screw with the offset marked",
            "subject": "flexible coupling",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "coupling center, shafts either side",
            "text": "THE WRIST THAT PASSES MOTION",
            "elements": ["flexible coupling", "motor shaft", "lead screw"],
            "style": "geometry studio photography",
            "mood": "flexed, forgiving, driven",
            "prompt": "photograph of a flexible coupling joining a motor shaft to a lead screw with the offset marked, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Flexible Couplings: The Wrist That Passes Motion",
            "title_variations": [
                "What Do Flexible Couplings Do",
                "Flexible Coupling Explained",
                "Motor Coupling Basics",
                "Z Axis Coupling",
                "Misalignment Forgiveness",
            ],
            "description": "A flexible coupling joins a motor shaft to a lead screw, forgiving the small misalignments that rigid joints cannot. Motors and screws are never perfectly aligned, and a rigid link turns the offset into binding and wear. The coupling flexes to absorb the offset while still turning the screw, like a wrist that bends but passes motion. This short shows the offset, the rigid bind, and the flex that buys forgiveness.",
            "hashtags": ["#FlexibleCoupling", "#MotorCoupling", "#3DPrinting", "#Mechanics"],
            "seo_keywords": [
                "what do flexible couplings do",
                "flexible coupling explained",
                "motor coupling basics",
                "z axis coupling",
                "shaft misalignment coupling",
                "coupling binding wear",
                "flex coupling lead screw",
            ],
        },
        "fact_check": [
            "Couplings join motor shafts to screws.",
            "Shafts are never perfectly aligned.",
            "Rigid links turn offset into binding.",
            "The coupling flexes to absorb it.",
            "The coupling still passes the rotation.",
        ],
    },
    {
        "topic": "Extruder Gears & Grip",
        "core_question": "Why does your extruder skip and grind the filament?",
        "learning_objective": "The viewer understands extruder grip, gear ratio, and skip causes.",
        "engineering_summary": "The extruder moves filament with gears: a drive gear bites the filament and a bearing or idler presses it in, so the teeth grip like a tire on pavement. Dual drive gears bite from both sides and grip even soft filament. The extruder skips when the grip cannot push the plastic: too fast, too cold, or a nozzle clog, and the gear grinds the filament instead. Grip is the deal, and the skip is a symptom.",
        "real_world_application": "Bondtech and dual-drive extruders exist to hold grip on soft materials.",
        "common_misconceptions": [
            "Skipping is an extruder fault (it is a symptom of too much resistance)",
            "More gear pressure always grips (crushing the filament jams it)",
            "Any gear works (tooth bite and dual drive matter)",
        ],
        "teaching_strategy": "Feed filament by hand against resistance and watch the gear slip.",
        "script": "The extruder moves filament with gears: a drive gear bites the filament and a bearing or idler presses it in, so the teeth grip like a tire on pavement. Dual drive gears bite from both sides and grip even soft filament. The extruder skips when the grip cannot push the plastic: too fast, too cold, or a nozzle clog, and the gear grinds the filament instead. Grip is the deal, and the skip is a symptom.",
        "text_overlay": [
            "GEAR BITES, IDLER PRESSES",
            "DUAL DRIVE GRIPS BOTH SIDES",
            "SKIP = TOO MUCH RESISTANCE",
            "THE GRIND IS A SYMPTOM",
        ],
        "scenes": [
            {
                "goal": "Hook: the grinding gear",
                "teaching_point": "Gear slips, filament grinds",
                "shot": "close-up shot of an extruder gear grinding filament",
                "motion": "gear slips with shavings",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["extruder gear", "filament", "shavings"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an extruder gear grinding filament, bright task lighting, print lab",
            },
            {
                "goal": "The grip",
                "teaching_point": "Teeth bite, idler presses",
                "shot": "diagram-style shot of the gear and idler gripping filament",
                "motion": "teeth and roller close on the filament",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["drive gear", "idler", "filament cross"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of extruder gear and idler grip, clean engineering visualization on a dark background",
            },
            {
                "goal": "The dual drive",
                "teaching_point": "Both sides bite",
                "shot": "diagram-style shot of dual drive gears",
                "motion": "two gears squeeze the filament",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dual gears", "filament", "squeeze zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dual drive extruder gears, clean engineering visualization on a dark background",
            },
            {
                "goal": "The skip",
                "teaching_point": "Resistance beats the grip",
                "shot": "medium shot of an extruder skipping under a clog",
                "motion": "gear clicks and stalls",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["skipping extruder", "clogged nozzle", "clicking gear"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an extruder skipping under a clogged nozzle, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Grip is the deal",
                "shot": "wide hero shot of extruder gears on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["extruder gears", "drive gears", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of extruder drive gears on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An extruder gear biting filament with an idler and shavings",
            "subject": "extruder gear grip",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "gear center, filament through",
            "text": "GRIP IS THE DEAL",
            "elements": ["drive gear", "filament", "idler"],
            "style": "geometry studio photography",
            "mood": "biting, gripping, grinding",
            "prompt": "photograph of an extruder gear biting filament with an idler pressing and shavings below, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Extruder Gears & Grip: The Skip Is a Symptom",
            "title_variations": [
                "Why Does My Extruder Skip",
                "Extruder Gear Grip",
                "Dual Drive Extruder",
                "Filament Grinding Fix",
                "Extruder Skip Causes",
            ],
            "description": "The extruder moves filament with gears: a drive gear bites the filament and an idler presses it in, with dual drive gears gripping from both sides for soft materials. The extruder skips when the grip cannot push the plastic, from too fast, too cold, or a clogged nozzle, and the gear grinds the filament instead. This short shows the bite, the dual drive, and the skip that is really a symptom of resistance.",
            "hashtags": ["#Extruder", "#Bondtech", "#3DPrinting", "#Filament"],
            "seo_keywords": [
                "why does my extruder skip",
                "extruder gear grip",
                "dual drive extruder",
                "filament grinding",
                "extruder skip fix",
                "filament grip idler",
                "bondtech gears",
            ],
        },
        "fact_check": [
            "The drive gear bites the filament.",
            "An idler presses the filament in.",
            "Dual drive gears grip both sides.",
            "Skipping means resistance beats the grip.",
            "Grinding is a symptom, not the fault.",
        ],
    },
    {
        "topic": "Nozzle Diameter Effects",
        "core_question": "Does the nozzle size really change the print?",
        "learning_objective": "The viewer understands nozzle diameter effects on speed, detail, and strength.",
        "engineering_summary": "The nozzle diameter sets the line width: a 0.4 millimeter nozzle is the standard, a 0.6 is faster and stronger, and a 0.2 captures fine detail. Wider lines lay more plastic per pass, so big nozzles print faster and build stronger parts, but they lose small features and shallow details. Narrow nozzles carve detail but print slowly. The choice is a trade: detail versus speed and strength.",
        "real_world_application": "Functional parts run 0.6 nozzles, and miniatures run 0.2.",
        "common_misconceptions": [
            "Smaller always means better (it trades speed and strength)",
            "Layer height alone sets detail (line width matters too)",
            "Big nozzles clog more (they clog less, and faster)",
        ],
        "teaching_strategy": "Print the same part with 0.2, 0.4, and 0.6 nozzles.",
        "script": "The nozzle diameter sets the line width: a 0.4 millimeter nozzle is the standard, a 0.6 is faster and stronger, and a 0.2 captures fine detail. Wider lines lay more plastic per pass, so big nozzles print faster and build stronger parts, but they lose small features and shallow details. Narrow nozzles carve detail but print slowly. The choice is a trade: detail versus speed and strength.",
        "text_overlay": [
            "NOZZLE SETS LINE WIDTH",
            "0.2 DETAIL, 0.6 SPEED",
            "WIDE LINES, STRONG PARTS",
            "DETAIL VS SPEED",
        ],
        "scenes": [
            {
                "goal": "Hook: three nozzles",
                "teaching_point": "Same printer, three results",
                "shot": "medium shot of three nozzles lined up on a bench",
                "motion": "camera pans the sizes",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["0.2 nozzle", "0.4 nozzle", "0.6 nozzle"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of three nozzle sizes lined up on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "The width",
                "teaching_point": "Nozzle sets line width",
                "shot": "diagram-style shot of lines laid by each nozzle",
                "motion": "line widths compare",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["line widths", "nozzle sizes", "comparison"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of nozzle diameter line widths, clean engineering visualization on a dark background",
            },
            {
                "goal": "The detail",
                "teaching_point": "Narrow carves detail",
                "shot": "close-up shot of a fine part printed with a small nozzle",
                "motion": "small features resolve",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["fine print", "small features", "miniature"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a fine part printed with a small nozzle, bright task lighting, print lab",
            },
            {
                "goal": "The speed",
                "teaching_point": "Wide lays plastic fast",
                "shot": "medium shot of a big nozzle printing a strong part",
                "motion": "thick lines build fast",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["big nozzle", "strong part", "thick lines"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a big nozzle printing a strong part, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick by the part",
                "shot": "wide hero shot of prints from all three nozzles",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["nozzle prints", "samples", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of prints from three nozzle sizes on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three nozzles with their line widths and the prints they make",
            "subject": "nozzle diameter effects",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "three nozzles in a row, prints below",
            "text": "DETAIL VS SPEED",
            "elements": ["nozzles", "line widths", "prints"],
            "style": "geometry studio photography",
            "mood": "sized, compared, traded",
            "prompt": "photograph of three nozzle sizes with their line widths and the prints they make, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Nozzle Diameter Effects: Detail Versus Speed",
            "title_variations": [
                "Does Nozzle Size Matter",
                "0.4 vs 0.6 Nozzle",
                "Nozzle Size Explained",
                "0.2 Nozzle Detail",
                "Big Nozzle Faster Prints",
            ],
            "description": "The nozzle diameter sets the line width: 0.4 millimeter is the standard, 0.6 is faster and stronger, and 0.2 captures fine detail. Wider lines lay more plastic per pass, building faster and stronger parts while losing small features, and narrow nozzles carve detail but print slowly. This short prints the same part with three nozzles and shows the trade: detail versus speed and strength.",
            "hashtags": ["#Nozzle", "#3DPrinting", "#LineWidth", "#PrintQuality"],
            "seo_keywords": [
                "does nozzle size matter",
                "0.4 vs 0.6 nozzle",
                "nozzle diameter effects",
                "0.2 nozzle detail",
                "big nozzle speed",
                "line width nozzle",
                "nozzle strength print",
            ],
        },
        "fact_check": [
            "Nozzle diameter sets line width.",
            "0.4 millimeter is the standard.",
            "Wider lines print faster and stronger.",
            "Narrow nozzles capture fine detail.",
            "The choice trades detail against speed.",
        ],
    },
    {
        "topic": "Heated Chambers",
        "core_question": "Why do pro printers heat the whole chamber?",
        "learning_objective": "The viewer understands heated chambers and why high-temp materials need them.",
        "engineering_summary": "A heated chamber keeps the air around the print hot, so the part cools slowly and evenly as it builds. That slow cool stops warping, curling, and layer cracks in materials like ABS and polycarbonate. It also keeps the nozzle and bed heat from leaking away, which improves layer bonding and dimensional accuracy. The chamber is the environment; the material sets the temperature. Drafts are the enemy, and the chamber is the shield.",
        "real_world_application": "ABS, nylon, and polycarbonate parts need chamber heat to stay flat.",
        "common_misconceptions": [
            "Chambers are for cold rooms (they tune the cooling rate)",
            "PLA needs chamber heat (it prefers cooling, so chambers suit high-temp materials)",
            "Heat alone stops warping (even, slow cooling does)",
        ],
        "teaching_strategy": "Print ABS with and without chamber heat and compare the corners.",
        "script": "A heated chamber keeps the air around the print hot, so the part cools slowly and evenly as it builds. That slow cool stops warping, curling, and layer cracks in materials like ABS and polycarbonate. It also keeps the nozzle and bed heat from leaking away, which improves layer bonding and dimensional accuracy. The chamber is the environment; the material sets the temperature. Drafts are the enemy, and the chamber is the shield.",
        "text_overlay": [
            "AIR STAYS HOT",
            "SLOW, EVEN COOL",
            "NO WARPS, NO CRACKS",
            "THE CHAMBER IS THE SHIELD",
        ],
        "scenes": [
            {
                "goal": "Hook: the curled corner",
                "teaching_point": "Drafts curl the part",
                "shot": "close-up shot of an ABS part with curled corners",
                "motion": "corners lift off the bed",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["ABS part", "curled corners", "bed"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an ABS part with curled corners, bright task lighting, print lab",
            },
            {
                "goal": "The cool",
                "teaching_point": "Slow and even",
                "shot": "diagram-style shot of a part cooling evenly in a chamber",
                "motion": "temperature holds steady around the part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["chamber", "cooling part", "even temperature"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of even cooling in a heated chamber, clean engineering visualization on a dark background",
            },
            {
                "goal": "The materials",
                "teaching_point": "ABS and polycarbonate need it",
                "shot": "medium shot of ABS and PC spools beside a chamber printer",
                "motion": "materials pair with the chamber",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["ABS spool", "PC spool", "chamber printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of ABS and PC spools beside a chamber printer, neutral lab lighting, print lab",
            },
            {
                "goal": "The bonding",
                "teaching_point": "Layers fuse better",
                "shot": "diagram-style shot of layers bonding in heat",
                "motion": "layer seams heal in the warmth",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer stack", "bonding seam", "warmth zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layer bonding in chamber heat, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The chamber is the shield",
                "shot": "wide hero shot of a chamber printer with its door open",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["chamber printer", "enclosure", "print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a chamber printer with its door open, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A print inside a heated chamber with even cooling arrows",
            "subject": "heated chamber printing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "chamber center, even heat around",
            "text": "SLOW COOL, NO WARP",
            "elements": ["chamber printer", "print", "even heat arrows"],
            "style": "geometry studio photography",
            "mood": "warm, even, shielded",
            "prompt": "photograph of a print inside a heated chamber with even cooling arrows around it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heated Chambers: Slow Cool, No Warp",
            "title_variations": [
                "Why Do Pro Printers Heat the Chamber",
                "Heated Chamber Printing",
                "Chamber Temperature ABS",
                "Warping Fix Chamber",
                "High Temp Printing Enclosure",
            ],
            "description": "A heated chamber keeps the air around the print hot so the part cools slowly and evenly, stopping warping, curling, and layer cracks in ABS and polycarbonate. Chamber heat also stops nozzle and bed heat from leaking, improving layer bonding and accuracy. The chamber is the environment and the material sets the temperature. This short curls a corner in a draft, then shields it in a chamber to show the difference.",
            "hashtags": ["#HeatedChamber", "#ABS", "#3DPrinting", "#Warping"],
            "seo_keywords": [
                "why heated chamber printing",
                "heated chamber 3d printer",
                "chamber temperature ABS",
                "warping fix chamber",
                "high temp material enclosure",
                "slow even cooling print",
                "layer bonding heat",
            ],
        },
        "fact_check": [
            "Chambers keep the air around the print hot.",
            "Slow even cooling stops warping.",
            "ABS and PC need chamber heat.",
            "Chamber heat improves layer bonding.",
            "The material sets the chamber temperature.",
        ],
    },
    {
        "topic": "Frame Stiffness",
        "core_question": "Why does a flexing frame ruin a print?",
        "learning_objective": "The viewer understands frame stiffness and machine flex.",
        "engineering_summary": "The frame is the backbone of the printer: every move pushes against it, and if it flexes, the nozzle and bed drift out of alignment. Stiff frames keep the toolhead path true at speed, which is why braced frames print faster with less ringing. The stiffness comes from the shape: closed boxes and triangles beat open beams. A flexing frame turns motion into wobble, and wobble becomes the print's surface.",
        "real_world_application": "Racing and pro printers brace frames to hold accuracy at high acceleration.",
        "common_misconceptions": [
            "Heavier frames are always stiffer (shape, not weight, decides it)",
            "Flex shows in the frame (it shows up as print artifacts)",
            "Speed needs softer frames (speed needs stiffer ones)",
        ],
        "teaching_strategy": "Push a frame and measure the flex, then brace it and push again.",
        "script": "The frame is the backbone of the printer: every move pushes against it, and if it flexes, the nozzle and bed drift out of alignment. Stiff frames keep the toolhead path true at speed, which is why braced frames print faster with less ringing. The stiffness comes from the shape: closed boxes and triangles beat open beams. A flexing frame turns motion into wobble, and wobble becomes the print's surface.",
        "text_overlay": [
            "EVERY MOVE PUSHES THE FRAME",
            "FLEX DRIFTS THE TOOLHEAD",
            "BOXES AND TRIANGLES WIN",
            "WOBBLE BECOMES THE SURFACE",
        ],
        "scenes": [
            {
                "goal": "Hook: the flexing frame",
                "teaching_point": "Push a frame, it gives",
                "shot": "medium shot of a frame flexing under a hand push",
                "motion": "frame bows and springs back",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer frame", "hand push", "flex"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printer frame flexing under a push, neutral lab lighting, print lab",
            },
            {
                "goal": "The path",
                "teaching_point": "Flex drifts the toolhead",
                "shot": "diagram-style shot of a toolhead path wobbling on a flexing frame",
                "motion": "path deviates as the frame flexes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["toolhead path", "frame flex", "deviation"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of toolhead path deviation from frame flex, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shapes",
                "teaching_point": "Boxes and triangles",
                "shot": "diagram-style shot comparing open beams and braced shapes",
                "motion": "closed shapes resist the push",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["open beam", "closed box", "triangle brace"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram comparing frame stiffness shapes, clean engineering visualization on a dark background",
            },
            {
                "goal": "The surface",
                "teaching_point": "Wobble becomes the print",
                "shot": "close-up shot of ringing artifacts on a print surface",
                "motion": "ghosting ripples across the wall",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["print surface", "ringing", "ghost lines"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of ringing artifacts on a print surface, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Stiffness is the backbone",
                "shot": "wide hero shot of a braced printer frame",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["braced frame", "braces", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a braced printer frame, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printer frame with brace triangles and a wobbling toolhead path",
            "subject": "frame stiffness",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "frame center, braces marked",
            "text": "WOBBLE BECOMES THE SURFACE",
            "elements": ["printer frame", "triangle braces", "toolhead path"],
            "style": "geometry studio photography",
            "mood": "rigid, braced, true",
            "prompt": "photograph of a printer frame with triangle braces and a wobbling toolhead path marked, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Frame Stiffness: Wobble Becomes the Surface",
            "title_variations": [
                "Why Frame Stiffness Matters",
                "Printer Frame Stiffness",
                "Printer Rigidity Basics",
                "Frame Braces for Printers",
                "Machine Flex and Ringing",
            ],
            "description": "The frame is the backbone of the printer: every move pushes against it, and flex drifts the nozzle and bed out of alignment. Stiff frames keep the toolhead path true at speed, which is why braced frames print faster with less ringing, and stiffness comes from shape, with closed boxes and triangles beating open beams. This short pushes a frame, traces the wobbling path, and shows how flex becomes the print's surface.",
            "hashtags": ["#FrameStiffness", "#3DPrinting", "#PrinterFrame", "#Ringing"],
            "seo_keywords": [
                "why frame stiffness matters",
                "printer frame stiffness",
                "printer rigidity",
                "frame braces printer",
                "machine flex ringing",
                "toolhead path drift",
                "stiff printer frame",
            ],
        },
        "fact_check": [
            "The frame takes every move's force.",
            "Frame flex drifts the toolhead.",
            "Stiff frames print faster with less ringing.",
            "Shape, not weight, decides stiffness.",
            "Boxes and triangles beat open beams.",
        ],
    },
    {
        "topic": "Aluminum Extrusion",
        "core_question": "How does a solid block become a T-slot rail?",
        "learning_objective": "The viewer understands aluminum extrusion and its profile shapes.",
        "engineering_summary": "Aluminum extrusion squeezes a heated billet through a steel die, so a solid block becomes a long profile with the die's cross section. The process makes T-slot rails, angles, and custom shapes cheaply, because the die shapes the whole length at once. Profiles then bolt together with slot nuts, building frames without welding. The die is the cost, and the profile is the product.",
        "real_world_application": "Printer frames, rigs, and workstations are all built from T-slot profiles.",
        "common_misconceptions": [
            "Extrusion is machining (it is squeezing through a die)",
            "Profiles are cast (they are shaped by pressure, not poured)",
            "Frames need welding (slot nuts bolt profiles together)",
        ],
        "teaching_strategy": "Show the die, the press, and the long profile coming out.",
        "script": "Aluminum extrusion squeezes a heated billet through a steel die, so a solid block becomes a long profile with the die's cross section. The process makes T-slot rails, angles, and custom shapes cheaply, because the die shapes the whole length at once. Profiles then bolt together with slot nuts, building frames without welding. The die is the cost, and the profile is the product.",
        "text_overlay": [
            "SQUEEZE THROUGH THE DIE",
            "DIE SHAPES THE LENGTH",
            "T-SLOTS, ANGLES, CUSTOMS",
            "FRAMES WITHOUT WELDING",
        ],
        "scenes": [
            {
                "goal": "Hook: the T-slot rail",
                "teaching_point": "One die, endless rail",
                "shot": "medium shot of a long T-slot extrusion rail on a bench",
                "motion": "camera slides along the profile",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["T-slot rail", "profile", "slots"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a long T-slot extrusion rail on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "The squeeze",
                "teaching_point": "Billet through the die",
                "shot": "diagram-style shot of a billet being squeezed through a die",
                "motion": "billet shortens, profile emerges",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["billet", "steel die", "emerging profile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of aluminum extrusion through a die, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shapes",
                "teaching_point": "T-slots, angles, customs",
                "shot": "medium shot of different extrusion profiles grouped",
                "motion": "camera pans the shapes",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["T-slot", "angle profile", "custom shape"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of different extrusion profiles grouped on a bench, neutral lab lighting, workbench",
            },
            {
                "goal": "The frame",
                "teaching_point": "Slot nuts, no welding",
                "shot": "medium shot of a frame built from profiles and slot nuts",
                "motion": "nuts slide and lock in the slots",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["profile frame", "slot nuts", "brackets"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a profile frame with slot nuts being assembled, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The die is the cost",
                "shot": "wide hero shot of extrusion dies and profiles on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["extrusion dies", "profiles", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of extrusion dies and profiles on a bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A billet squeezing through a die into a T-slot profile",
            "subject": "aluminum extrusion",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "die center, profile emerging",
            "text": "SQUEEZE, SHAPE, SLIDE",
            "elements": ["billet", "steel die", "T-slot profile"],
            "style": "geometry studio photography",
            "mood": "squeezed, shaped, long",
            "prompt": "photograph of a billet squeezing through a die into a T-slot profile with the die marked, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Aluminum Extrusion: Squeeze, Shape, Slide",
            "title_variations": [
                "How Is Aluminum Extruded",
                "Aluminum Extrusion Explained",
                "T-Slot Profiles",
                "Extrusion Process Basics",
                "Extruded Aluminum Frames",
            ],
            "description": "Aluminum extrusion squeezes a heated billet through a steel die, turning a solid block into a long profile with the die's cross section. That makes T-slot rails, angles, and custom shapes cheaply, because the die shapes the whole length at once. Profiles then bolt together with slot nuts, building frames without welding. This short follows the billet through the die and into the frames that printers are built from.",
            "hashtags": ["#AluminumExtrusion", "#TSlot", "#Profiles", "#Manufacturing"],
            "seo_keywords": [
                "how is aluminum extruded",
                "aluminum extrusion",
                "t-slot profiles",
                "extrusion process",
                "extruded aluminum frames",
                "slot nuts framing",
                "extrusion die shapes",
            ],
        },
        "fact_check": [
            "Extrusion squeezes a billet through a die.",
            "The die sets the cross section.",
            "T-slot rails are made this way.",
            "Profiles build frames without welding.",
            "The die is the main cost.",
        ],
    },
]