"""Batch 4: troubleshooting, materials, gears, and electronics fundamentals."""

CURATED = [
    # ======================================================================
    {
        "topic": "Stringing",
        "core_question": "What causes stringing and how do I remove it?",
        "learning_objective": "The viewer can diagnose stringing as melt-pressure ooze and fix it in order: retraction, temperature, cooling, then travel settings.",
        "engineering_summary": "Stringing is molten filament oozing from the nozzle during travel moves. Melt pressure inside the hotend pushes plastic out even when the extruder is idle. The fix order: retraction distance/speed (pull pressure back), nozzle temperature (lower within the material window reduces fluidity), part cooling (solidifies ooze faster), and travel settings (combing, z-hop, travel speed). PETG and TPU string more because of low viscosity and moisture; wet filament strings worse.",
        "real_world_application": "Cosmetic parts and threaded features are ruined by strings; print farms tune retraction per material and keep dry spools to hold string-free production.",
        "common_misconceptions": [
            "Stringing is the filament's fault (it is melt pressure; every filament strings if settings are wrong)",
            "Lower temperature always fixes stringing (too cold under-extrudes and weakens layers)",
            "Retraction alone fixes everything (temperature, moisture, and travel settings all matter)",
        ],
        "teaching_strategy": "Show the ooze mechanism at the nozzle, then the fix order as a ranked list with the most common culprit first.",
        "script": "Those cobwebs on your print? That's stringing, and it's a pressure problem. Molten plastic keeps pushing out of the nozzle even when it shouldn't. The fix order matters. One: retraction - pull the filament back to kill the pressure. Two: temperature - cooler plastic oozes less. Three: cooling - freeze the drip fast. Four: travel - smarter paths mean fewer chances to leak. And keep the filament dry: moisture turns to steam and pushes plastic out. Four fixes, one cause: pressure.",
        "text_overlay": [
            "COBWEBS = PRESSURE",
            "1. RETRACTION",
            "2. TEMPERATURE",
            "3. COOLING + DRY",
            "4. TRAVEL PATHS",
        ],
        "scenes": [
            {
                "goal": "Hook: the cobwebs",
                "teaching_point": "Stringing is ooze during travel",
                "shot": "macro close-up of a stringy print with cobwebs between towers",
                "motion": "slow push-in on the strands",
                "lighting": "raking side light",
                "background": "dark workshop blur",
                "objects": ["stringy print", "filament strands"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part with fine filament strings between features, raking side light, dark workshop background",
            },
            {
                "goal": "The pressure idea",
                "teaching_point": "Melt pressure pushes plastic out even when idle",
                "shot": "graphic-style shot of a hotend cross-section with ooze arrows",
                "motion": "pressure arrows push a drip",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hotend cutaway", "ooze arrows"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hotend cutaway with ooze pressure arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Fix 1-2: retraction and temperature",
                "teaching_point": "Pull pressure back, then reduce fluidity",
                "shot": "macro shot of filament retracting in the extruder",
                "motion": "pull-back loop",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["extruder", "filament", "retraction motion"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of filament being pulled back through a dual-gear extruder, bright task lighting, print lab",
            },
            {
                "goal": "Fix 3-4: cooling, drying, travel",
                "teaching_point": "Freeze the drip fast and plan smarter paths",
                "shot": "medium shot of a printer with strong part cooling, then a dry box",
                "motion": "cuts between cooling fan and dry box",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer fan", "dry box", "filament spool"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer with part cooling fan running, neutral lab lighting, modern print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fix the pressure, not the symptom",
                "shot": "wide hero shot of a clean, string-free print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a clean string-free 3D print on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Cobwebbed print with a numbered fix ladder overlaid",
            "subject": "stringy 3D print with a clean print beside it",
            "background": "dark workshop blur",
            "angle": "macro eye-level",
            "lighting": "raking side light",
            "composition": "stringy print left, clean print right, ladder in between",
            "text": "4 FIXES",
            "elements": ["stringy print", "clean print", "fix ladder"],
            "style": "diagnostic macro photography",
            "mood": "corrective, ranked, clear",
            "prompt": "macro photograph of a stringy 3D print on the left and a clean print on the right with a numbered fix ladder overlay, raking side light, dark workshop, 9:16 vertical composition, ultra sharp filament detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Stringing: 4 Fixes, One Cause",
            "title_variations": [
                "Why Your Print Has Spider Webs",
                "The Real Cause of Stringing",
                "Fix Stringing in the Right Order",
                "PETG Stringing? Here's the Order",
                "Cobwebs on Prints: Solved",
            ],
            "description": "Stringing is molten filament oozing from the nozzle during travel - a melt pressure problem, not a bad spool. Fix it in order: retraction to pull the pressure back, nozzle temperature within the material window, part cooling to freeze drips fast, and smarter travel paths. Plus why wet filament strings worse: moisture flashes to steam and pushes plastic out. Cobwebs have one cause and four fixes.",
            "hashtags": ["#3Dprinting", "#Stringing", "#Troubleshooting", "#3DPrintingTips"],
            "seo_keywords": [
                "fix stringing",
                "why does my print string",
                "stringing 3d print",
                "petg stringing fix",
                "retraction stringing",
                "filament cobwebs",
                "stringing temperature",
            ],
        },
        "fact_check": [
            "Stringing severity tracks melt viscosity, nozzle temperature, and moisture content; PETG and TPU are low-viscosity offenders.",
            "Retraction pulls molten filament away from the melt zone, lowering nozzle pressure during travel.",
            "Lowering nozzle temperature reduces ooze but risks under-extrusion and poor layer bonding below the material's window.",
            "Moisture flashes to steam in the hotend, violently pushing plastic out - one reason wet spools string badly.",
            "Combing, z-hop, and travel speed reduce the number and duration of nozzle passes over open air.",
        ],
    },
    # ======================================================================
    {
        "topic": "ABS",
        "core_question": "Why is ABS hard to print, and is it worth it?",
        "learning_objective": "The viewer knows ABS's strength and heat properties, its warping and fume requirements, and when it beats PLA and PETG.",
        "engineering_summary": "ABS (acrylonitrile butadiene styrene) is a tough engineering thermoplastic: high impact resistance, glass transition ~105 C, and good chemical resistance. It prints at 220-250 C nozzle and 90-110 C bed, shrinks aggressively during cooling, and warps without a heated chamber. It also emits styrene fumes requiring ventilation. ASA is its UV-stable sibling for outdoor use. ABS excels where parts face heat, impacts, or automotive environments.",
        "real_world_application": "Automotive interior brackets, power tool housings, functional prototypes, and Lego-style parts; ABS is a benchmark material for strength testing and vapor smoothing.",
        "common_misconceptions": [
            "ABS is outdated and useless (it remains a reference engineering material with unique heat and impact performance)",
            "You can print ABS without an enclosure (large parts warp badly without chamber heat and draft control)",
            "ABS fumes are harmless (styrene fumes warrant ventilation)",
        ],
        "teaching_strategy": "Frame the trade in three beats: what it's for (heat and impact), what it costs (enclosure and fumes), and the alternative (ASA for outdoors).",
        "script": "ABS is the engineering veteran: the plastic of car dashboards, power tools, and Legos. It shrugs off heat and takes impacts that would shatter PLA. But it's demanding. It shrinks hard as it cools, so it needs a hot bed, an enclosure, and no drafts - or it warps off the plate. And it fumes: ventilate your space. Print it right, and you get parts that survive the sun, the torque wrench, and the drop test. ABS isn't easy. It's worth it.",
        "text_overlay": [
            "HEAT + IMPACT TOUGH",
            "~105°C GLASS TRANSITION",
            "ENCLOSURE + HOT BED",
            "FUMES = VENTILATE",
            "ASA = UV TWIN",
        ],
        "scenes": [
            {
                "goal": "Hook: what ABS builds",
                "teaching_point": "ABS is the plastic of dashboards and power tools",
                "shot": "medium shot of an ABS car interior bracket and power tool housing",
                "motion": "slow pan across the parts",
                "lighting": "neutral product light",
                "background": "workshop shelf",
                "objects": ["car bracket", "power tool housing", "ABS parts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of ABS plastic parts including a car bracket and power tool housing on a workshop shelf, neutral product lighting",
            },
            {
                "goal": "What it survives",
                "teaching_point": "High glass transition and impact resistance",
                "shot": "graphic-style shot of an ABS part near a hot engine and under impact",
                "motion": "heat and impact callouts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["ABS part", "heat source", "impact icon"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an ABS part with heat and impact callouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The cost: warping",
                "teaching_point": "Aggressive shrinkage demands enclosure and hot bed",
                "shot": "medium shot of a printer inside an enclosure printing ABS",
                "motion": "slow dolly around the enclosure",
                "lighting": "warm chamber light",
                "background": "print lab",
                "objects": ["printer", "enclosure", "ABS print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer inside a heated enclosure printing ABS, warm chamber lighting, print lab",
            },
            {
                "goal": "The cost: fumes",
                "teaching_point": "Ventilation is non-negotiable",
                "shot": "medium shot of a printer near a ventilated window with airflow",
                "motion": "airflow visualization",
                "lighting": "neutral lab light",
                "background": "print room",
                "objects": ["printer", "window vent", "airflow"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer printing near an open ventilated window, neutral lighting, print room",
            },
            {
                "goal": "Takeaway: ASA alternative",
                "teaching_point": "Use ASA when the part lives outdoors",
                "shot": "wide hero shot of an ASA part mounted outdoors",
                "motion": "slow orbit",
                "lighting": "bright daylight",
                "background": "outdoor wall",
                "objects": ["ASA printed part", "outdoor mount"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of an ASA 3D printed part mounted on an outdoor wall, bright daylight, realistic product photography",
            },
        ],
        "thumbnail": {
            "concept": "ABS bracket surviving a hammer blow with a heat gauge in the corner",
            "subject": "black ABS bracket with impact and heat callouts",
            "background": "dark workshop blur",
            "angle": "macro low-angle",
            "lighting": "hard key with rim",
            "composition": "bracket centered, callouts in the corners",
            "text": "ABS",
            "elements": ["ABS bracket", "hammer", "heat gauge"],
            "style": "industrial product photography",
            "mood": "tough, demanding, proven",
            "prompt": "macro photograph of a black ABS 3D printed bracket with a hammer and heat gauge callouts, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp surface detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "ABS: The Engineering Veteran",
            "title_variations": [
                "Why ABS Is Hard to Print (And Worth It)",
                "ABS Settings: Enclosure, Bed, and Fumes",
                "ABS vs PLA vs PETG: Heat and Impact",
                "Print ABS Without Warping",
                "ASA vs ABS: Pick the Outdoor Twin",
            ],
            "description": "ABS is the engineering veteran behind car dashboards, power tools, and Legos: it shrugs off heat and impacts that shatter PLA. But it shrinks aggressively, demanding a hot bed, an enclosure, and draft control - and its fumes call for ventilation. This short covers the print requirements, the warping physics, and why ASA is the UV-stable twin for outdoor parts.",
            "hashtags": ["#3Dprinting", "#ABS", "#Filament", "#Engineering"],
            "seo_keywords": [
                "abs filament",
                "abs print settings",
                "abs warping fix",
                "abs enclosure",
                "abs vs pla",
                "abs fumes ventilation",
                "asa vs abs",
            ],
        },
        "fact_check": [
            "ABS glass transition is about 105 C; prints survive higher service temperatures than PLA or PETG.",
            "Typical ABS settings: 220-250 C nozzle, 90-110 C bed; a heated chamber (ideally 50-90 C) controls shrinkage-induced warping.",
            "ABS has higher shrinkage than PLA, so large flat parts lift without brims, enclosures, and draft control.",
            "ABS emits styrene and other VOCs during printing; ventilation or filtration is recommended.",
            "ASA is ABS with acrylic rubber chemistry for UV stability, printing with nearly identical settings.",
            "Units: temperatures in degrees Celsius.",
        ],
    },
    # ======================================================================
    {
        "topic": "Wall Line Count",
        "core_question": "How many wall lines should I use?",
        "learning_objective": "The viewer can choose wall count by part role: 2-3 for cosmetic, 3-4 for functional, more for threaded or sealing parts.",
        "engineering_summary": "Wall lines (perimeters) are the outer shells of a print and carry the majority of bending and impact loads because outer fibers experience peak stress. Two walls suffice for cosmetic parts; three to four walls serve most functional parts; threaded and pressure-touching parts use more. Wall count interacts with infill: at low infill, walls carry nearly all load, so wall count beats infill density for strength. Each wall adds nozzle passes and time.",
        "real_world_application": "Brackets and mounts default to 3-4 walls; waterproof or vacuum parts need many walls (or 100% infill) because layer boundaries leak; threaded inserts rely on surrounding wall material for pull-out strength.",
        "common_misconceptions": [
            "Infill provides strength and walls are cosmetic (walls carry bending loads; infill mainly supports top surfaces)",
            "More walls are always better (beyond 4-5, strength gains shrink while time rises)",
            "Wall count doesn't affect water tightness (wall boundaries are leak paths; more walls reduce them)",
        ],
        "teaching_strategy": "Bend two identical brackets with different wall counts at 20% infill and let the wall-dominant behavior show.",
        "script": "Your print's skeleton is the walls, not the infill. Wall lines are the outer shells, and they carry most of the load because the outside of a part bends hardest. Two walls? Fine for decorative. Three or four? That's the functional default: brackets, mounts, anything that takes a real load. More walls make threads and seals hold, but each one adds time. So stop cranking infill - set your walls first. Strength lives at the edges.",
        "text_overlay": [
            "WALLS = LOAD CARRIERS",
            "2 = COSMETIC",
            "3-4 = FUNCTIONAL",
            "THREADS + SEALS = MORE",
            "STRENGTH LIVES AT THE EDGES",
        ],
        "scenes": [
            {
                "goal": "Hook: bending test",
                "teaching_point": "Walls carry bending load, not the fill",
                "shot": "two brackets flexing, one 2-wall one 4-wall",
                "motion": "side-by-side flex test",
                "lighting": "bright task light",
                "background": "lab bench",
                "objects": ["printed brackets", "test rig"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two 3D printed brackets being flexed in a bench test, bright task lighting, engineering lab bench",
            },
            {
                "goal": "The shells",
                "teaching_point": "Wall lines are concentric shells around the part",
                "shot": "cutaway macro of a print showing wall rings and infill",
                "motion": "slow pan across the cutaway",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["cutaway print", "wall rings", "infill"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed part cut in half showing concentric wall rings around infill, even diffused lighting, neutral workbench",
            },
            {
                "goal": "The defaults",
                "teaching_point": "2 walls decorative, 3-4 functional",
                "shot": "graphic-style shot of wall-count callouts on a bracket",
                "motion": "wall rings count up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bracket model", "wall count callouts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bracket model with wall count callouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Threads and seals",
                "teaching_point": "Pull-out strength and leak paths depend on wall mass",
                "shot": "macro shot of a threaded boss with heat-set insert",
                "motion": "slow push-in on the boss walls",
                "lighting": "bright task light",
                "background": "workbench blur",
                "objects": ["threaded boss", "heat-set insert", "wall rings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a 3D printed threaded boss with a brass heat-set insert, bright task lighting, workbench background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Set walls first, then infill",
                "shot": "wide hero shot of a strong bracket printing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["bracket", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a functional 3D printed bracket on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Cutaway bracket showing 4 wall rings with a wall-count dial",
            "subject": "printed bracket cut in half, wall rings glowing in the cross-section",
            "background": "dark bench blur",
            "angle": "macro three-quarter",
            "lighting": "hard key with rim",
            "composition": "cutaway centered, wall rings visible",
            "text": "3-4 WALLS",
            "elements": ["wall rings", "infill core", "cutaway face"],
            "style": "technical macro photography",
            "mood": "structural, clear, load-bearing",
            "prompt": "macro photograph of a 3D printed bracket cut in half showing four concentric wall rings around a sparse infill core, hard key light with rim, dark workbench, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Wall Count Beats Infill for Strength",
            "title_variations": [
                "How Many Walls Do You Need?",
                "Stop Cranking Infill: Set Walls First",
                "Walls vs Infill: Where Strength Lives",
                "3-4 Walls: The Functional Default",
                "Wall Lines Explained for Strong Prints",
            ],
            "description": "Your print's skeleton is its wall lines, not the infill: outer shells carry most bending and impact loads. Two walls suit decorative parts, three to four cover functional brackets and mounts, and threaded or sealing features need more. This short explains why wall count beats infill density for strength and how to read a cutaway to choose the right number.",
            "hashtags": ["#3Dprinting", "#WallCount", "#PrintStrength", "#3DPrintingTips"],
            "seo_keywords": [
                "wall line count",
                "perimeters 3d print",
                "how many walls 3d print",
                "wall count vs infill",
                "strong 3d printed parts",
                "shell thickness print",
                "perimeter strength",
            ],
        },
        "fact_check": [
            "Bending stress peaks at the outermost fiber, so the perimeter carries the highest bending moment contribution.",
            "2-3 walls are typical for cosmetic parts; 3-4 for functional; threaded bosses and sealing walls need more.",
            "Layer boundaries are leak paths for fluids; watertight prints require many walls or 100% infill plus flow tuning.",
            "Beyond roughly 4-5 walls, additional walls return diminishing strength per print-time cost.",
            "Units: wall count dimensionless; wall thickness = count x line width (e.g., 3 x 0.4 mm = 1.2 mm).",
        ],
    },
    # ======================================================================
    {
        "topic": "Z-Seam Alignment",
        "core_question": "Where does the z-seam go and how do I hide it?",
        "learning_objective": "The viewer can choose seam position by geometry: corners over flat faces, and use coasting, retraction, and scarf seams to minimize visibility.",
        "engineering_summary": "Each layer starts and ends at one point; the stacked start/stop points form the z-seam, a visible line of blobs or indentations. Seam position can be aligned to corners or hidden edges, scattered randomly, or placed nearest a chosen point. Because the start/stop region has slightly different extrusion pressure, seam quality improves with retraction, coasting, and power-loss-dependent scarf seams. Curved parts hide seams better at inner radii where geometry masks the blob.",
        "real_world_application": "Cosmetic prints (vases, phone stands) use seam-to-corner alignment and random seams; round vessels often accept a seam at the back; slicers now offer scarf seams that cut the weld point into a taper.",
        "common_misconceptions": [
            "The seam is a print defect (it is a geometric consequence of layer start/stop, manageable but not erasable)",
            "Seam placement doesn't affect strength (a seam is a stress concentration on loaded walls)",
            "Ironing fixes the seam (ironing smooths top surfaces, not side seams)",
        ],
        "teaching_strategy": "Show the same cylinder with seam front, seam back-corner, and random seams side by side; the visual contrast teaches alignment instantly.",
        "script": "Every layer starts somewhere, and where it starts, it leaves a mark: the z-seam, that line of tiny blobs marching up your print. You can't delete it, but you can direct it. Put the seam in a corner, and the geometry hides it. Put it on the back of a cylinder, and nobody sees it. Go random, and it scatters like noise. Then clean up the start: add a little retraction and coasting, and the blob shrinks. Seams are like shadows - you can't remove them, but you can aim them.",
        "text_overlay": [
            "EVERY LAYER STARTS SOMEWHERE",
            "CORNER = HIDDEN SEAM",
            "BACK = INVISIBLE",
            "RANDOM = NOISE",
            "AIM THE SHADOW",
        ],
        "scenes": [
            {
                "goal": "Hook: the seam line",
                "teaching_point": "Stacked layer start points form a visible line",
                "shot": "macro close-up of a cylinder with a visible z-seam line",
                "motion": "slow tilt up the seam",
                "lighting": "raking side light",
                "background": "dark bench blur",
                "objects": ["printed cylinder", "z-seam line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D printed cylinder with a visible z-seam line running up its side, raking side light, dark bench",
            },
            {
                "goal": "Why it forms",
                "teaching_point": "Start/stop pressure differences mark the layer point",
                "shot": "graphic-style shot of a layer ring with start point marked",
                "motion": "extrusion starts and stops at the mark",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer ring", "start point mark"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a layer ring with a marked start point on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Alignment options",
                "teaching_point": "Corners, back, and random all change visibility",
                "shot": "three cylinders side by side with seams in different positions",
                "motion": "slow pan across the three",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["corner seam cylinder", "back seam cylinder", "random seam cylinder"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of three 3D printed cylinders with seams in different positions, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Cleaning the start",
                "teaching_point": "Retraction and coasting shrink the seam blob",
                "shot": "slicer screen showing seam and retraction settings",
                "motion": "value callouts appear",
                "lighting": "screen glow in dark room",
                "background": "dark studio",
                "objects": ["slicer screen", "seam setting", "retraction setting"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a slicer interface showing seam position and retraction settings, screen glow in a dark studio, clean UI",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Aim the seam into geometry that hides it",
                "shot": "wide hero shot of a smooth vase print rotating",
                "motion": "slow turntable rotation",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["smooth vase print", "turntable"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a smooth 3D printed vase on a turntable, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Cylinder with an arrow pointing at the seam and a crosshair targeting a corner",
            "subject": "printed cylinder with a visible seam line and an aiming reticle",
            "background": "dark bench blur",
            "angle": "macro eye-level",
            "lighting": "raking side light",
            "composition": "cylinder centered, reticle overlaid",
            "text": "AIM THE SEAM",
            "elements": ["cylinder", "seam line", "aiming reticle"],
            "style": "diagnostic macro photography",
            "mood": "directable, precise, clean",
            "prompt": "macro photograph of a 3D printed cylinder with a visible z-seam and an aiming reticle overlay, raking side light, dark workbench, 9:16 vertical composition, ultra sharp surface detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Z-Seam: Hide It, Don't Fight It",
            "title_variations": [
                "Where to Put the Z-Seam",
                "Why Your Print Has That Line",
                "Seam Alignment: Corners Beat Faces",
                "The Seam Is Not a Defect",
                "Clean Seams With Coasting and Retraction",
            ],
            "description": "Every layer starts somewhere, and that point stacks into the z-seam - a line of tiny blobs marching up your print. You can't delete the seam, but you can direct it: corners hide it, the back of a cylinder buries it, random placement scatters it. This short explains seam mechanics, alignment options, and how retraction and coasting shrink the blob at the start point.",
            "hashtags": ["#3Dprinting", "#ZSeam", "#PrintQuality", "#3DPrintingTips"],
            "seo_keywords": [
                "z seam alignment",
                "hide z seam",
                "seam position slicer",
                "z seam blobs",
                "seam on cylinder",
                "scarf seam",
                "coasting z seam",
            ],
        },
        "fact_check": [
            "The z-seam is the stacked start/stop point of each layer contour, inherent to FDM toolpaths.",
            "Aligned seams can be placed at corners, at a chosen point, or scattered randomly; random hides regularity but leaves multiple small marks.",
            "Retraction at layer start reduces pressure overshoot; coasting stops extrusion slightly early to empty the melt zone.",
            "Scarf seams (available in newer slicers) taper the weld point across layers, dramatically reducing visibility.",
            "The seam region is a minor stress concentration; on heavily loaded walls it can initiate failure.",
        ],
    },
    # ======================================================================
    {
        "topic": "Gears: How Teeth Engage",
        "core_question": "How do gear teeth mesh and transfer motion?",
        "learning_objective": "The viewer can explain involute tooth shape, why teeth roll rather than slide, and the basic meshing rules.",
        "engineering_summary": "Gear teeth are involute curves: a tooth shape where the contact point rolls smoothly along the line of action, keeping the angular velocity ratio constant even with slightly varying center distance. Meshing teeth make rolling contact with minor sliding, transferring force through the line of action between pitch points. The base pitch and module determine size; proper meshing requires equal module/pitch and correct center distance. Backlash prevents jamming and accommodates thermal and tolerance variation.",
        "real_world_application": "3D printed gears use standard modules (e.g., module 1 or 2) with 20-degree pressure angle; backlash of 0.2-0.4 mm is often added for print tolerance; printer extruder gears and filament drives rely on the same tooth geometry.",
        "common_misconceptions": [
            "Gear teeth slide against each other like friction wheels (they roll through involute contact, minimizing wear)",
            "Any two gears can mesh (they need equal module or pitch)",
            "Tight meshing is better (tight mesh jams; controlled backlash is required)",
        ],
        "teaching_strategy": "Animate the involute contact: mark the two contacting teeth and show the rolling line of action; then show the failure of mismatched modules.",
        "script": "Two gears that just touch would slip like polished wheels. What makes them grip is geometry: the involute curve. Each tooth is shaped so that when gears mesh, the teeth roll against each other along a straight line of action - no scraping, constant speed, no matter the size. That's why watch gears spin smoothly and car gearboxes whine only when worn. One rule: teeth must share the same module, or size step, to mesh at all. Geometry does the work - teeth just follow the line.",
        "text_overlay": [
            "SLIP = NO GEOMETRY",
            "INVOLUTE = ROLLING TEETH",
            "LINE OF ACTION",
            "SAME MODULE = MESHES",
            "GEOMETRY DOES THE WORK",
        ],
        "scenes": [
            {
                "goal": "Hook: smooth rolling teeth",
                "teaching_point": "Meshing gears roll, they don't scrape",
                "shot": "macro close-up of two meshing steel gears with one tooth marked",
                "motion": "marked tooth rolls through contact",
                "lighting": "hard key with brass reflections",
                "background": "machine shop blur",
                "objects": ["steel gears", "marked tooth"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of two meshing steel gears with a marked tooth, hard key light with metallic reflections, machine shop background",
            },
            {
                "goal": "The involute shape",
                "teaching_point": "Involute teeth roll along a straight line of action",
                "shot": "graphic-style shot of an involute tooth profile with contact line",
                "motion": "contact point travels the line of action",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["involute profile", "line of action"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an involute gear tooth profile with a line of action on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Why shape matters",
                "teaching_point": "Constant speed ratio comes from the curve, not the teeth count",
                "shot": "two gears of different sizes meshing smoothly in slow motion",
                "motion": "slow-motion meshing",
                "lighting": "soft studio light",
                "background": "dark bench blur",
                "objects": ["large gear", "small gear"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a large and small gear meshing in slow motion, soft studio lighting, dark bench",
            },
            {
                "goal": "The module rule",
                "teaching_point": "Matching module or pitch is required to mesh",
                "shot": "two gears with mismatched teeth trying to mesh",
                "motion": "they jam instead of roll",
                "lighting": "even diffused light",
                "background": "neutral bench",
                "objects": ["mismatched gears", "jammed teeth"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two mismatched gears trying to mesh and jamming, even diffused lighting, neutral workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Backlash is designed in, not a defect",
                "shot": "wide hero shot of an open gearbox turning",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["gearbox", "meshing gears"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of an open gearbox with meshing gears turning, dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two gears with a glowing involute profile and a line of action arrow",
            "subject": "meshing steel gears with a highlighted tooth profile",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "gears filling the frame, contact line drawn",
            "text": "INVOLUTE",
            "elements": ["gear teeth", "involute profile", "contact line"],
            "style": "industrial macro photography",
            "mood": "geometric, precise, mechanical",
            "prompt": "macro photograph of two meshing steel gears with a highlighted involute tooth profile and contact line, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp tooth detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Gear Teeth: The Involute Secret",
            "title_variations": [
                "Why Gear Teeth Are That Shape",
                "How Gears Mesh Without Slipping",
                "The Line of Action Explained",
                "Why Mismatched Gears Jam",
                "Gear Geometry in 30 Seconds",
            ],
            "description": "Gear teeth are shaped as involute curves so meshing gears roll along a straight line of action - no scraping, constant speed, minimal wear. That geometry is why watch gears spin smoothly and why mismatched modules jam instead of mesh. This short explains the tooth shape, the meshing rule, and why backlash is deliberately designed in, not a manufacturing defect.",
            "hashtags": ["#Engineering", "#Gears", "#MechanicalEngineering", "#HowItWorks"],
            "seo_keywords": [
                "how gears work",
                "involute gear teeth",
                "gear mesh explained",
                "gear module",
                "line of action gears",
                "gear backlash",
                "gear tooth profile",
            ],
        },
        "fact_check": [
            "Standard involute gears use a 20-degree pressure angle (older: 14.5 degrees).",
            "Involute geometry keeps the angular velocity ratio constant and tolerates small center-distance variation.",
            "Mating gears must share module (metric) or diametral pitch (imperial) to mesh correctly.",
            "Backlash is the intentional play between meshing teeth, typically 0.05-0.1 mm for machined gears and more for printed gears (0.2-0.4 mm).",
            "Printed gears use modules like 0.5-2 depending on load; tooth strength scales with module.",
        ],
    },
    # ======================================================================
    {
        "topic": "Pressure & Force",
        "core_question": "What's the difference between pressure and force?",
        "learning_objective": "The viewer can compute pressure from force and area, and explain why concentrated forces crush and spread forces don't.",
        "engineering_summary": "Force is a push or pull (N); pressure is force spread over an area (Pa = N/m2). The same force produces very different effects: a 70 kg person on stiletto heels exerts ~500x the pressure of the same person in snowshoes. Pressure is what damages surfaces, seals, and tissues. Fluid pressure acts equally in all directions (Pascal's principle), which is the basis of hydraulics, and pressure is the driver behind fasteners (bolt clamp pressure) and bearings (contact pressure limits).",
        "real_world_application": "Hydraulic presses multiply force via Pascal's law; tire contact patches, skateboard bearings, and print bed adhesion all depend on pressure distribution; snowshoes and heels demonstrate it daily.",
        "common_misconceptions": [
            "Pressure and force are the same thing (pressure is force per area; the units differ)",
            "Smaller contact area doesn't matter (smaller area concentrates the same force into more damage)",
            "Fluid pressure pushes only downward (fluids push equally in every direction)",
        ],
        "teaching_strategy": "The stiletto vs snowshoe comparison is the whole lesson in one image; then Pascal's law connects it to hydraulics.",
        "script": "Same force, two results: a heel sinks, a snowshoe floats. The difference? Pressure - force spread over area. The heel concentrates your weight onto a few square centimeters; the snowshoe spreads it over a hundred times more. Same weight, hundredth of the pressure. That's why cutting tools are sharp, why bearing balls are small, and why hydraulic systems work: fluids push equally in every direction, so a small piston can push a big one. Force starts the fight. Area decides the damage.",
        "text_overlay": [
            "PRESSURE = FORCE / AREA",
            "HEEL SINKS, SHOE FLOATS",
            "SAME FORCE, 100x PRESSURE",
            "FLUIDS PUSH EVERY WAY",
            "AREA DECIDES THE DAMAGE",
        ],
        "scenes": [
            {
                "goal": "Hook: heel vs snowshoe",
                "teaching_point": "Same force, different pressure",
                "shot": "split-screen: stiletto heel in soft ground vs snowshoe on snow",
                "motion": "cross-fade between the two",
                "lighting": "bright daylight",
                "background": "outdoor scenes",
                "objects": ["stiletto heel", "snowshoe", "soft ground", "snow"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a stiletto heel sinking into soft ground, bright daylight, realistic outdoor photography",
            },
            {
                "goal": "The formula",
                "teaching_point": "Pressure = force divided by area",
                "shot": "graphic-style shot of force arrows over a contact patch",
                "motion": "area changes, pressure readout changes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["contact patch", "force arrows", "pressure readout"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a contact patch with force arrows and a pressure readout on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Engineering uses",
                "teaching_point": "Sharper tools and smaller contacts concentrate pressure",
                "shot": "macro shot of cutting tools and bearing balls",
                "motion": "slow push-in on contact points",
                "lighting": "bright bench light",
                "background": "machine shop blur",
                "objects": ["cutting tools", "bearing balls", "sharp edges"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of cutting tools and steel bearing balls on a machine shop bench, bright bench lighting",
            },
            {
                "goal": "Pascal's law",
                "teaching_point": "Fluids push equally in all directions",
                "shot": "hydraulic press demo with small and large pistons",
                "motion": "small piston pushes, large piston lifts",
                "lighting": "neutral workshop light",
                "background": "workshop",
                "objects": ["hydraulic pistons", "press frame", "workpiece"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hydraulic press with visible pistons in a workshop, neutral workshop lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design area to control pressure",
                "shot": "wide hero shot of a wide tire on soft ground",
                "motion": "slow roll over soft ground",
                "lighting": "golden-hour light",
                "background": "off-road track",
                "objects": ["wide tire", "soft ground"],
                "transition": "fade",
                "duration": 6,
                "prompt": "photograph of a wide off-road tire rolling over soft ground at golden hour, realistic automotive photography",
            },
        ],
        "thumbnail": {
            "concept": "Stiletto heel and snowshoe side by side with a pressure formula overlay",
            "subject": "stiletto heel on one side, snowshoe on the other",
            "background": "dark studio blur",
            "angle": "medium low-angle",
            "lighting": "hard key with rim",
            "composition": "two objects mirrored, formula between them",
            "text": "P = F / A",
            "elements": ["stiletto heel", "snowshoe", "formula"],
            "style": "educational product photography",
            "mood": "surprising, physical, clear",
            "prompt": "photograph of a stiletto heel on the left and a snowshoe on the right with a pressure equals force over area formula between them, hard key light with rim, dark studio, 9:16 vertical composition, high contrast",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, logos",
        },
        "seo": {
            "title": "Pressure vs Force: Area Decides",
            "title_variations": [
                "Why a Heel Sinks and a Snowshoe Floats",
                "Pressure = Force / Area Explained",
                "Same Force, Hundred Times the Pressure",
                "Pascal's Law in 30 Seconds",
                "Why Tools Are Sharp: Pressure",
            ],
            "description": "What's the difference between force and pressure? Force is the push; pressure is the push spread over an area. The same weight under a stiletto heel crushes, under a snowshoe floats - a hundred times less pressure. This short explains P = F / A, why cutting tools are sharp, why bearings use small contacts, and how Pascal's law powers hydraulic presses.",
            "hashtags": ["#Physics", "#Engineering", "#Pressure", "#HowItWorks"],
            "seo_keywords": [
                "pressure vs force",
                "pressure formula",
                "pascal's law explained",
                "force over area",
                "why heels sink in grass",
                "hydraulic press physics",
                "contact pressure",
            ],
        },
        "fact_check": [
            "Pressure = force / area (Pa = N/m2); 1 bar = 100 kPa = 14.5 psi.",
            "A 70 kg person on stiletto heels (contact area ~1 cm2 total) exerts roughly 500x the pressure of the same person on snowshoes (~1000+ cm2).",
            "Pascal's principle: pressure applied to an enclosed fluid transmits equally in all directions.",
            "Hydraulic multiplication: output force = input force x (output area / input area), ignoring losses.",
            "Bearing contact pressure limits and Hertzian stress govern bearing life and material choice.",
        ],
    },
    # ======================================================================
    {
        "topic": "Ohm's Law",
        "core_question": "How do voltage, current, and resistance relate?",
        "learning_objective": "The viewer can apply V = I x R to size components, read circuit problems, and compute power with P = V x I.",
        "engineering_summary": "Ohm's law states voltage equals current times resistance (V = I x R). Voltage is the electrical push, current the flow, resistance the opposition. For a fixed voltage, doubling resistance halves current. Power follows P = V x I = I^2 x R. This governs fuse sizing, wire gauge, heater cartridge wattage, and why short circuits melt wires: tiny resistance at fixed voltage creates huge current and power.",
        "real_world_application": "3D printer heater cartridges (e.g., 40 W at 24 V draws ~1.7 A), fan ratings, battery wiring, and fuse selection all come from V = I x R and P = V x I.",
        "common_misconceptions": [
            "Voltage pushes current through anything (current is limited by resistance; a wire to ground is a short circuit)",
            "High voltage means high danger always (current through the body is what matters; V = I x R applies to you too)",
            "Batteries push constant current (batteries hold voltage; current depends on load resistance)",
        ],
        "teaching_strategy": "Use the water analogy once: pressure = voltage, flow = current, pipe kink = resistance; then switch to real numbers on a printer heater.",
        "script": "Voltage, current, resistance: the holy trinity of circuits. Voltage is the push, current is the flow, resistance is the squeeze. One equation ties them: voltage equals current times resistance. Same push, double the squeeze, half the flow. That's it - that's ohm's law. Why care? Your printer's heater draws its power through this math, your fuses protect by this math, and your short circuits melt wires because of it. Small resistance, fixed voltage: enormous current. Three numbers, one equation, whole world of electronics.",
        "text_overlay": [
            "V = I x R",
            "PUSH = FLOW x SQUEEZE",
            "HEATER: 40W @ 24V = 1.7A",
            "SHORT = TINY R, HUGE I",
            "THREE NUMBERS, ONE EQUATION",
        ],
        "scenes": [
            {
                "goal": "Hook: the short circuit",
                "teaching_point": "Tiny resistance at fixed voltage makes enormous current",
                "shot": "macro shot of a glowing overheated wire end",
                "motion": "slow push-in on the glowing point",
                "lighting": "dim workshop light",
                "background": "dark workbench",
                "objects": ["wire", "glowing short point"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of an overheated wire end glowing from a short circuit, dim workshop lighting, dark workbench, realistic",
            },
            {
                "goal": "The equation",
                "teaching_point": "V = I x R ties the three quantities",
                "shot": "graphic-style shot of the equation with variable callouts",
                "motion": "values change and recalculate",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["equation", "variable callouts"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an ohm's law equation with variable callouts on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Real numbers",
                "teaching_point": "A 40 W heater at 24 V draws about 1.7 A",
                "shot": "medium shot of a printer hotend heater cartridge",
                "motion": "power readout overlay",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["heater cartridge", "hotend", "power readout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a 3D printer heater cartridge in a hotend with a power readout overlay, neutral lab lighting, print lab",
            },
            {
                "goal": "Fuses and wires",
                "teaching_point": "Wire gauge and fuses are ohm's law in practice",
                "shot": "macro shot of a fuse and wire gauge chart",
                "motion": "slow pan across the chart",
                "lighting": "bright bench light",
                "background": "electronics bench",
                "objects": ["fuse", "wire gauge chart"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a glass fuse next to a wire gauge chart on an electronics bench, bright bench lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One equation powers all of electronics",
                "shot": "wide hero shot of a neatly wired printer control board",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark bench",
                "objects": ["control board", "wiring", "connectors"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a 3D printer control board with clean wiring, dark bench background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "The V = I x R triangle with a glowing wire circuit behind it",
            "subject": "large V = I x R equation over an electronics bench",
            "background": "dark electronics bench blur",
            "angle": "medium eye-level",
            "lighting": "hard key with rim",
            "composition": "equation centered, circuit elements around",
            "text": "V = I x R",
            "elements": ["equation", "resistor", "wire", "multimeter"],
            "style": "educational electronics photography",
            "mood": "fundamental, clear, essential",
            "prompt": "photograph of a large voltage equals current times resistance equation over an electronics bench with resistors and a multimeter, hard key light with rim, dark bench, 9:16 vertical composition, clean and sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing fake circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands, logos",
        },
        "seo": {
            "title": "Ohm's Law: Three Numbers, One Equation",
            "title_variations": [
                "V = I x R Explained in 30 Seconds",
                "Voltage, Current, Resistance: The Trinity",
                "Why Short Circuits Melt Wires",
                "Ohm's Law for 3D Printer Wiring",
                "How Much Current Does That Draw?",
            ],
            "description": "Voltage is the push, current is the flow, resistance is the squeeze - and V = I x R ties them together. This short explains ohm's law with real numbers: a 40 W heater at 24 V draws 1.7 A, fuses protect by this math, and short circuits melt wires because tiny resistance at fixed voltage means enormous current. The one equation that powers all of electronics.",
            "hashtags": ["#Electronics", "#OhmsLaw", "#Engineering", "#Physics"],
            "seo_keywords": [
                "ohm's law explained",
                "voltage current resistance",
                "v equals ir",
                "calculate current",
                "heater cartridge wattage",
                "short circuit current",
                "wire gauge current",
            ],
        },
        "fact_check": [
            "Ohm's law: V = I x R; power: P = V x I = I^2 x R = V^2 / R.",
            "A 40 W heater at 24 V: I = P / V = 1.67 A; its resistance R = V^2 / P = 14.4 ohms.",
            "Short circuits approach zero resistance, so current and power spike; protection devices and proper wire gauge prevent thermal failure.",
            "Ohm's law is linear only for ohmic materials (metals at constant temperature); heaters and motors deviate as temperature changes.",
            "Units: V in volts, I in amperes, R in ohms, P in watts.",
        ],
    },
    # ======================================================================
    {
        "topic": "Soldering Basics",
        "core_question": "How do I make a reliable solder joint?",
        "learning_objective": "The viewer can produce a good through-hole joint: clean, hot, flux, and a smooth fillet - and identify cold joints.",
        "engineering_summary": "Soldering joins metals with a low-melting filler (tin-lead or lead-free) that wets both surfaces through a metallurgical bond, not just glue. The recipe: clean surfaces, apply flux (integral in most solder cores), heat both the pad and the wire together, then feed solder until it flows into a smooth fillet. A cold joint - dull, cracked, or blobby - comes from insufficient heat, movement while cooling, or dirty surfaces. Lead-free solder needs higher temperatures and longer dwell.",
        "real_world_application": "Every 3D printer motherboard connection, motor lead, and sensor wire; heater cartridge and thermistor connections must be solid because vibration and heat cycles stress them.",
        "common_misconceptions": [
            "Soldering is just melting solder onto the joint (the pad and wire must both reach temperature for a true bond)",
            "More solder means a stronger joint (excess solder hides cold joints and bridges)",
            "Movement while cooling is fine (any wiggle during solidification creates a cracked crystalline joint)",
        ],
        "teaching_strategy": "Show good vs cold joints side by side: shiny fillet vs dull cracked blob, and let the surface finish teach the lesson.",
        "script": "Soldering isn't melting metal onto metal - it's alloying. The solder wets both parts and forms a real bond. The recipe: clean the surfaces, touch the iron to both the pad and the wire, and feed solder until it flows into a smooth cone. Shiny cone, good joint. Dull, cracked, blobby? Cold joint - the heat wasn't there, or you wiggled while it cooled. Lead-free runs hotter, so give it time. Solder doesn't glue. It alloys. Heat, flux, patience.",
        "text_overlay": [
            "SOLDER ALLOYS, NOT GLUES",
            "HEAT PAD + WIRE TOGETHER",
            "SHINY CONE = GOOD",
            "DULL = COLD JOINT",
            "NO WIGGLE WHILE COOLING",
        ],
        "scenes": [
            {
                "goal": "Hook: good vs cold",
                "teaching_point": "Shiny fillet vs dull cracked joint",
                "shot": "macro close-up of two solder joints, one shiny one dull",
                "motion": "slow push-in on the cold joint",
                "lighting": "bright bench light",
                "background": "electronics bench blur",
                "objects": ["good solder joint", "cold solder joint", "pcb"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a printed circuit board with one shiny solder joint and one dull cracked cold joint, bright bench lighting, electronics bench",
            },
            {
                "goal": "The alloy idea",
                "teaching_point": "Wetting creates a metallurgical bond",
                "shot": "graphic-style shot of solder wetting a wire and pad",
                "motion": "solder flows into the joint cross-section",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["solder cross-section", "wire", "pad"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a solder joint cross-section showing wetting on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The recipe",
                "teaching_point": "Clean, heat both, feed solder, hold still",
                "shot": "medium shot of hands soldering a through-hole joint",
                "motion": "iron contact, solder feed, smooth fillet",
                "lighting": "task bench light",
                "background": "electronics bench",
                "objects": ["soldering iron", "solder wire", "pcb", "hands"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of hands soldering a through-hole joint on a pcb, task bench lighting, electronics workbench",
            },
            {
                "goal": "Cold joint anatomy",
                "teaching_point": "Insufficient heat or movement creates cracks",
                "shot": "macro shot of a cracked dull joint under magnification",
                "motion": "slow push-in on the cracks",
                "lighting": "bright bench light",
                "background": "dark blur",
                "objects": ["cracked solder joint", "magnified view"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a cracked dull solder joint under magnification, bright bench lighting, dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Heat, flux, patience",
                "shot": "wide hero shot of a soldered motor connection on a printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark bench",
                "objects": ["motor connector", "soldered joints", "printer"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of soldered motor connections on a 3D printer, dark bench background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "One shiny cone joint vs one cracked cold joint, iron tip hovering",
            "subject": "two solder joints on a pcb, one perfect one cracked",
            "background": "dark electronics bench blur",
            "angle": "macro top-down",
            "lighting": "hard key with rim",
            "composition": "joints centered, iron tip entering the frame",
            "text": "GOOD vs COLD",
            "elements": ["shiny joint", "cracked joint", "iron tip"],
            "style": "electronics macro photography",
            "mood": "skill, precision, contrast",
            "prompt": "macro photograph of a pcb with one shiny smooth solder joint and one dull cracked cold joint, a soldering iron tip entering the frame, hard key light with rim, dark electronics bench, 9:16 vertical composition, ultra sharp",
            "negative_prompt": "fantasy, sci-fi, magic, glowing fake circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Soldering: Shiny Joint or Cold Joint?",
            "title_variations": [
                "How to Solder Like a Pro",
                "The 4-Step Soldering Recipe",
                "Why Cold Joints Crack",
                "Solder Doesn't Glue, It Alloys",
                "Through-Hole Soldering Basics",
            ],
            "description": "Soldering forms a metallurgical bond - the solder wets both parts - not a glue job. The recipe: clean surfaces, heat both the pad and the wire together, feed solder until it forms a smooth shiny cone, and don't wiggle while it cools. Learn to identify cold joints - dull, cracked, blobby - and why lead-free solder needs more heat and patience. Heat, flux, and a steady hand.",
            "hashtags": ["#Electronics", "#Soldering", "#HowToSolder", "#Maker"],
            "seo_keywords": [
                "how to solder",
                "cold solder joint",
                "soldering tips",
                "through hole soldering",
                "solder joint quality",
                "lead free solder temperature",
                "soldering for beginners",
            ],
        },
        "fact_check": [
            "Solder wets surfaces through flux-assisted metallurgical bonding; the filler alloy melts well below the base metals' melting points.",
            "Common alloys: Sn63/Pb37 (eutectic, 183 C) and lead-free SAC305 (about 217-220 C).",
            "A cold joint forms from insufficient temperature, contamination, or movement during solidification; it is mechanically and electrically unreliable.",
            "IPC-610 is the standard visual acceptance criteria for solder joints.",
            "Units: temperatures in degrees Celsius.",
        ],
    },
]