"""Batch 17: slicer preview, tree supports, coasting, tolerance, PLA+, boards, cartridges, and PTFE."""

CURATED = [
    # ======================================================================
    {
        "topic": "Slicer Preview Reading",
        "core_question": "What is the preview showing, and what should you check?",
        "learning_objective": "The viewer can read color-coded layers and spot common print problems before pressing print.",
        "engineering_summary": "The slicer preview shows every move your printer will make before you hit print. Color-coded layers reveal speed, temperature, and travel: red means slow, blue means fast, and the gaps show where the nozzle moves without printing. Check for broken rings on top layers, missing walls in thin sections, and supports you forgot to add. The layer slider walks through the print top to bottom, and each line is a wall or infill. A five-minute preview check catches most failed prints. The preview is a free dry run; use it.",
        "real_world_application": "Reviewing every print in preview before slicing catches missing walls, thin sections, and forgotten supports before wasted hours.",
        "common_misconceptions": [
            "The preview is just a render (it is the actual toolpath)",
            "Color is decoration (colors code speed and temperature)",
            "The bottom layer tells the whole story (problems hide in the top layers)",
        ],
        "teaching_strategy": "Open a real preview, decode the colors, then walk the layers and call out the problem spots.",
        "script": "The slicer preview shows every move your printer will make before you hit print. Color-coded layers reveal speed, temperature, and travel: red means slow, blue means fast, and the gaps show where the nozzle moves without printing. Check for broken rings on top layers, missing walls in thin sections, and supports you forgot to add. The layer slider walks through the print top to bottom, and each line is a wall or infill. A five-minute preview check catches most failed prints. The preview is a free dry run; use it.",
        "text_overlay": [
            "COLORS CODE SPEED",
            "RED = SLOW, BLUE = FAST",
            "WALK THE LAYERS",
            "FIVE MINUTES SAVES A PRINT",
        ],
        "scenes": [
            {
                "goal": "Hook: the dry run",
                "teaching_point": "Preview shows every move",
                "shot": "screen capture of a slicer preview rotating",
                "motion": "model orbits with layers",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slicer preview", "model", "layer view"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a slicer preview with a model in layer view, clean engineering visualization on a dark background",
            },
            {
                "goal": "The colors",
                "teaching_point": "Colors code speed and moves",
                "shot": "close-up screen capture of colored layers",
                "motion": "colors animate by speed",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["colored layers", "speed legend"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of colored slicer layers with a speed legend, clean engineering visualization on a dark background",
            },
            {
                "goal": "Walking the layers",
                "teaching_point": "Slider travels top to bottom",
                "shot": "screen capture of the layer slider moving",
                "motion": "layers peel away",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer slider", "peeling layers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer layer slider with layers peeling away, clean engineering visualization on a dark background",
            },
            {
                "goal": "Problem spots",
                "teaching_point": "Broken rings, thin walls, missing supports",
                "shot": "screen capture highlighting problem areas",
                "motion": "problem zones flash red",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["problem markers", "thin walls", "missing supports"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a slicer preview with problem areas highlighted, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Five minutes beats a failed print",
                "shot": "wide hero shot of a printer running next to the preview screen",
                "motion": "print starts as preview shrinks",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["running printer", "preview screen"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer running beside a slicer preview screen, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A slicer layer view with a speed legend and a problem spot flagged",
            "subject": "slicer layer view with legend",
            "background": "dark workshop blur",
            "angle": "isometric view",
            "lighting": "hard key with rim",
            "composition": "layer view center, legend lower corner",
            "text": "READ THE PREVIEW",
            "elements": ["layer view", "speed legend", "flagged problem"],
            "style": "geometry studio photography",
            "mood": "layered, colorful, diagnostic",
            "prompt": "photograph of a slicer layer view with a speed legend and a flagged problem spot, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Read the Slicer Preview Before You Print",
            "title_variations": [
                "How to Read Slicer Preview",
                "Layer View Colors Explained",
                "Spot Print Problems in Preview",
                "Slicer Preview Check",
                "Read G-Code Preview",
            ],
            "description": "The slicer preview is the cheapest insurance in 3D printing: a full dry run of every move the printer will make, shown before you waste an hour of machine time. Colors encode speed, temperature, and travel moves; red crawls, blue cruises, and gaps reveal the nozzle flying without printing. The layer slider walks the model top to bottom so you can spot broken rings on top surfaces, missing walls in thin sections, and supports you never added. Most failed prints are visible in preview for anyone who looks. This short teaches you to read the colors, walk the layers, and catch problems in five minutes.",
            "hashtags": ["#Slicer", "#3Dprinting", "#Tips", "#Preview"],
            "seo_keywords": [
                "how to read slicer preview",
                "slicer layer view",
                "g-code preview colors",
                "spot print problems",
                "preview check before print",
                "slicer speed colors",
                "layer view walkthrough",
            ],
        },
        "fact_check": [
            "The preview shows the actual toolpath.",
            "Colors code speed, temperature, and travel moves.",
            "Broken rings and thin walls show up on top layers.",
            "The layer slider walks the print top to bottom.",
            "A five-minute preview check catches most failed prints.",
        ],
    },
    {
        "topic": "Tree Supports",
        "core_question": "Why branch supports instead of solid walls?",
        "learning_objective": "The viewer knows when tree supports shine, when they fail, and how to tune them.",
        "engineering_summary": "Tree supports branch up from the build plate and touch the part only at the tips, instead of walls of solid plastic. Less material, less scarring, and easier removal: the branches snap off and leave small nubs you sand away. The trade-off: trees need stable footing, so thin, tall parts still struggle, and tuning the branch angle is the trick. Print trees when overhangs are high off the bed or removal is painful. They fail when the branches are too thin or the part rocks. Supports are scaffolding; trees are the tidy version.",
        "real_world_application": "Organic supports slash material use and post-processing time on tall overhangs, at the cost of longer slicing and fragile branches.",
        "common_misconceptions": [
            "Trees always win (they fail on thin tall parts)",
            "Tree supports are stronger (they are less rigid than walls)",
            "Branches leave no trace (small nubs remain at the tips)",
        ],
        "teaching_strategy": "Compare a wall support to a tree on the same overhang, then show the tip contact and the removal.",
        "script": "Tree supports branch up from the build plate and touch the part only at the tips, instead of walls of solid plastic. Less material, less scarring, and easier removal: the branches snap off and leave small nubs you sand away. The trade-off: trees need stable footing, so thin, tall parts still struggle, and tuning the branch angle is the trick. Print trees when overhangs are high off the bed or removal is painful. They fail when the branches are too thin or the part rocks. Supports are scaffolding; trees are the tidy version.",
        "text_overlay": [
            "BRANCHES TOUCH AT THE TIPS",
            "LESS MATERIAL, LESS SCARRING",
            "NEEDS STABLE FOOTING",
            "SNAP OFF, SAND THE NUBS",
        ],
        "scenes": [
            {
                "goal": "Hook: the branch",
                "teaching_point": "Branches, not walls",
                "shot": "diagram-style shot of tree supports under a part",
                "motion": "branches grow up to the part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["tree supports", "part", "branch tips"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of tree supports branching up under a part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The payoff",
                "teaching_point": "Less material, less scarring",
                "shot": "medium shot of a printed part with tree supports",
                "motion": "supports snap off cleanly",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["printed part", "tree supports", "removal"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of tree supports snapping off a printed part, neutral lab lighting, workbench",
            },
            {
                "goal": "The trade-off",
                "teaching_point": "Thin tall parts still struggle",
                "shot": "close-up shot of a thin part with branch supports",
                "motion": "branches flex under load",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["thin part", "flexing branches"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of thin parts with flexing tree supports in a print lab, bright task lighting",
            },
            {
                "goal": "When to use",
                "teaching_point": "High overhangs, painful removal",
                "shot": "screen capture of tree support settings",
                "motion": "branch angle slider adjusts the model",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["support settings", "branch angle", "model"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of tree support settings with a branch angle slider, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Scaffolding, but tidy",
                "shot": "wide hero shot of a clean part with nub marks",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean part", "nub marks"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean printed part with small support nubs, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part supported by branching trees with a snap-off tip highlighted",
            "subject": "tree supports under a part",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "branches center, tip contact highlighted",
            "text": "TREE SUPPORTS",
            "elements": ["tree branches", "part", "tip contact"],
            "style": "geometry studio photography",
            "mood": "branching, clean, removable",
            "prompt": "photograph of a part supported by branching tree supports with the tip contact highlighted, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Tree Supports: The Tidy Scaffold",
            "title_variations": [
                "Are Tree Supports Better",
                "Organic Supports Explained",
                "Tree vs Wall Supports",
                "When to Use Tree Supports",
                "Easy Support Removal",
            ],
            "description": "Tree supports grow up from the build plate like roots in reverse and touch the part only at their tips, trading solid walls of plastic for branching geometry. The payoff: far less material, smaller scars, and supports that snap off instead of fighting you with pliers. The catch is stability: trees need solid footing, so thin, tall models still need walls or denser branches, and branch angle and tip size are the settings that make or break removal. Use trees for high overhangs and delicate details, and switch back when parts are heavy or the branches are weak. This short shows when trees win and how to tune them.",
            "hashtags": ["#TreeSupports", "#3Dprinting", "#Supports", "#Tips"],
            "seo_keywords": [
                "tree supports",
                "organic supports 3d printing",
                "tree vs wall supports",
                "when to use tree supports",
                "support removal easy",
                "tree support settings",
                "branch angle support",
            ],
        },
        "fact_check": [
            "Tree supports touch the part only at the tips.",
            "They use less material and leave less scarring than walls.",
            "Thin, tall parts still need stable footing.",
            "Branch angle and thickness are the key settings.",
            "Trees fail when branches are too thin or the part rocks.",
        ],
    },
    {
        "topic": "Coasting & Wipe",
        "core_question": "Why do corners blob, and how do two settings fix it?",
        "learning_objective": "The viewer understands pressure control at the end of a line and how to tune coasting and wipe.",
        "engineering_summary": "Coasting stops extrusion a few millimeters before a move ends, letting the leftover pressure finish the line. Wipe drags the nozzle across the printed edge after the move, cleaning the tip. Together they kill blobs at corners and stringing on travel. The cost: coast too far and gaps appear at the end of lines, so the setting is tuned in tiny steps. Coasting mostly matters with a direct drive; Bowden setups need more wipe. Little artifacts, two settings, one clean corner.",
        "real_world_application": "Slicer coasting and wipe settings tame corner blobs and travel stringing with near-zero material cost.",
        "common_misconceptions": [
            "Coasting reduces flow (it only stops pushing early)",
            "More coasting is better (too much leaves gaps)",
            "Wipe only cleans the nozzle (it also scars the part edge)",
        ],
        "teaching_strategy": "Show the nozzle at line end, then the coast and wipe moves, and tune on a zigzag test.",
        "script": "Coasting stops extrusion a few millimeters before a move ends, letting the leftover pressure finish the line. Wipe drags the nozzle across the printed edge after the move, cleaning the tip. Together they kill blobs at corners and stringing on travel. The cost: coast too far and gaps appear at the end of lines, so the setting is tuned in tiny steps. Coasting mostly matters with a direct drive; Bowden setups need more wipe. Little artifacts, two settings, one clean corner.",
        "text_overlay": [
            "STOP PUSHING EARLY",
            "DRAG TO CLEAN THE TIP",
            "TUNE IN TINY STEPS",
            "ONE CLEAN CORNER",
        ],
        "scenes": [
            {
                "goal": "Hook: the blob",
                "teaching_point": "Pressure at line end makes blobs",
                "shot": "close-up shot of a nozzle leaving a blob at a corner",
                "motion": "blob forms at the corner",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["nozzle", "corner blob", "printed wall"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a nozzle leaving a blob at a printed corner, bright task lighting, print lab",
            },
            {
                "goal": "Coasting",
                "teaching_point": "Stop pushing, pressure finishes",
                "shot": "diagram-style shot of a line ending early",
                "motion": "extrusion stops before the corner",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extrusion line", "coast distance", "corner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram showing the coast distance at the end of a line, clean engineering visualization on a dark background",
            },
            {
                "goal": "Wipe",
                "teaching_point": "Drag the tip across the edge",
                "shot": "close-up shot of the nozzle wiping across a wall edge",
                "motion": "nozzle drags and cleans",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["nozzle", "wall edge", "wipe move"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle wiping across a printed wall edge, bright task lighting, print lab",
            },
            {
                "goal": "Tuning",
                "teaching_point": "Tiny steps, check the line ends",
                "shot": "screen capture of coasting and wipe sliders",
                "motion": "sliders adjust the preview",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["coasting slider", "wipe slider", "preview"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of slicer coasting and wipe sliders with a preview, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Two settings, one clean corner",
                "shot": "wide hero shot of a clean printed corner",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean corner", "printed cube"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean printed cube corner, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle at a corner with a coast distance arrow and a clean edge",
            "subject": "nozzle with coast arrow",
            "background": "dark workshop blur",
            "angle": "close-up side view",
            "lighting": "hard key with rim",
            "composition": "nozzle center, arrow marks the coast",
            "text": "NO MORE BLOBS",
            "elements": ["nozzle", "coast arrow", "clean edge"],
            "style": "geometry studio photography",
            "mood": "clean, precise, blobby",
            "prompt": "photograph of a nozzle at a printed corner with a coast distance arrow and a clean edge, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Coasting & Wipe: Fix Corner Blobs",
            "title_variations": [
                "What Are Coasting and Wipe",
                "Stop Corner Blobs",
                "Wipe Settings Explained",
                "Coasting Tuning Guide",
                "Clean Corners 3D Printing",
            ],
            "description": "Blobs at corners and strings on travel are pressure problems: the nozzle holds molten plastic that keeps flowing after the move should stop. Coasting answers by ending extrusion a few millimeters early, letting the remaining pressure finish the line, while wipe drags the nozzle across the printed edge to clean the tip. The trade-off is precision: coast too far and lines end in gaps, so the settings are tuned in small steps on a test cube. Direct drive machines coast best; Bowden setups lean on wipe. This short explains both moves, shows the tuning, and leaves you with clean corners.",
            "hashtags": ["#Coasting", "#Wipe", "#3Dprinting", "#Tips"],
            "seo_keywords": [
                "coasting and wipe",
                "fix corner blobs",
                "wipe setting 3d printer",
                "coasting tuning",
                "blobs on corners",
                "pressure advance alternative",
                "clean print corners",
            ],
        },
        "fact_check": [
            "Coasting stops extrusion before the move ends.",
            "Wipe drags the nozzle across the printed edge.",
            "Too much coasting leaves gaps at line ends.",
            "Direct drive needs less coasting than Bowden setups.",
            "A zigzag test cube reveals the tuning.",
        ],
    },
    {
        "topic": "Filament Tolerance",
        "core_question": "Does the box's 0.05 number actually matter?",
        "learning_objective": "The viewer understands diameter tolerance and why consistent filament prints better.",
        "engineering_summary": "Filament tolerance is how close the strand stays to its rated diameter, typically 1.75 millimeters plus or minus 0.05. Tight tolerance means steady extrusion: consistent walls, even layers, fewer jams. Loose filament wanders wide and thin, and the printer pumps uneven flow that shows as banding and gaps. Cheaper spools drift more, and every printer cares: a strand that swells jams the nozzle. Check the box for the tolerance spec before you buy. Diameter consistency is the quiet spec that decides print quality.",
        "real_world_application": "Tolerance specs separate cheap spools from reliable ones; a quarter of a millimeter of drift shows up in every wall.",
        "common_misconceptions": [
            "Tolerance never matters (it shows in every wall)",
            "Wide filament only jams (it also prints uneven)",
            "All spools are the same (tolerance is a selling point)",
        ],
        "teaching_strategy": "Show a caliper on the strand, then two prints from tight and loose spools.",
        "script": "Filament tolerance is how close the strand stays to its rated diameter, typically 1.75 millimeters plus or minus 0.05. Tight tolerance means steady extrusion: consistent walls, even layers, fewer jams. Loose filament wanders wide and thin, and the printer pumps uneven flow that shows as banding and gaps. Cheaper spools drift more, and every printer cares: a strand that swells jams the nozzle. Check the box for the tolerance spec before you buy. Diameter consistency is the quiet spec that decides print quality.",
        "text_overlay": [
            "1.75 +/- 0.05 MM",
            "TIGHT SPOOL, STEADY FLOW",
            "DRIFT SHOWS IN WALLS",
            "CHECK THE BOX",
        ],
        "scenes": [
            {
                "goal": "Hook: the number",
                "teaching_point": "Rated diameter plus or minus a spec",
                "shot": "close-up shot of calipers on a filament strand",
                "motion": "calipers close on the strand",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["calipers", "filament strand", "measurement"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of calipers measuring filament diameter, bright task lighting, print lab",
            },
            {
                "goal": "The range",
                "teaching_point": "Plus or minus 0.05 is tight",
                "shot": "graphic-style shot of a diameter range chart",
                "motion": "range band narrows",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["diameter chart", "tolerance band"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a filament diameter tolerance chart, clean engineering visualization on a dark background",
            },
            {
                "goal": "The print",
                "teaching_point": "Drift shows as banding and gaps",
                "shot": "medium shot of two printed walls side by side",
                "motion": "walls compare under a light",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["tight spool wall", "loose spool wall", "banding"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of two printed walls comparing filament tolerance, neutral lab lighting, workbench",
            },
            {
                "goal": "The jam",
                "teaching_point": "A swollen strand jams the nozzle",
                "shot": "close-up shot of a jammed hotend and the offending strand",
                "motion": "strand pulls free with a pause",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["jammed hotend", "swollen strand"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a jammed hotend with a swollen filament strand, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Check the box before you buy",
                "shot": "wide hero shot of filament spools with spec labels",
                "motion": "slow pan across the boxes",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["spools", "tolerance labels"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of filament spools with tolerance labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Calipers on a filament strand with a tolerance band graphic",
            "subject": "calipers and filament",
            "background": "dark workshop blur",
            "angle": "macro side view",
            "lighting": "hard key with rim",
            "composition": "calipers center, band graphic behind",
            "text": "+/- 0.05 MATTERS",
            "elements": ["calipers", "filament", "tolerance band"],
            "style": "geometry studio photography",
            "mood": "precise, tight, measurable",
            "prompt": "photograph of calipers measuring a filament strand with a tolerance band graphic and a spool behind, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Filament Tolerance: The Quiet Spec",
            "title_variations": [
                "Does Filament Tolerance Matter",
                "1.75mm Tolerance Explained",
                "Why Filament Diameter Matters",
                "Pick Consistent Filament",
                "Filament Quality Specs",
            ],
            "description": "Filament tolerance is the quiet spec that decides print quality: how closely the strand holds its rated 1.75 millimeter diameter. A plus or minus 0.05 specification is tight; cheaper spools drift far wider, and every swell or shrink shows as banding, gaps, and jams. The printer assumes consistent diameter and meters flow accordingly, so the strand is the one variable it cannot correct. Check the box for a tolerance spec, weigh the spool if you can, and let consistency be your filter. This short explains the numbers, shows the print difference, and helps you pick spools that behave.",
            "hashtags": ["#Filament", "#Tolerance", "#3Dprinting", "#Quality"],
            "seo_keywords": [
                "filament diameter tolerance",
                "1.75mm filament spec",
                "does tolerance matter",
                "filament quality",
                "banding from filament",
                "filament jam causes",
                "choose good filament",
            ],
        },
        "fact_check": [
            "Tolerance is deviation from the rated diameter.",
            "Typical spec is 1.75 millimeters plus or minus 0.05.",
            "Drift shows as banding and gaps in walls.",
            "A swollen strand jams the nozzle.",
            "Cheaper spools drift more, so check the box.",
        ],
    },
    {
        "topic": "PLA+ vs PLA",
        "core_question": "Is the plus actually worth the extra money?",
        "learning_objective": "The viewer knows what PLA+ changes and when to choose it over plain PLA.",
        "engineering_summary": "PLA+ is regular PLA with additives that boost strength, toughness, and impact resistance while keeping easy printing. Drop tests survive better, layer bonds hold longer, and the surface finishes about the same. The cost: slightly higher price, and the plus blend varies between brands, so results are not universal. PLA+ is not a new material; it is a tuned recipe. Choose it when parts take load or knocks; choose plain PLA for prints that just sit there. The plus buys margin, and margin wins.",
        "real_world_application": "Functional brackets, hinges, and tossed-around parts get the plus; display prints do not need it.",
        "common_misconceptions": [
            "PLA+ is a different plastic (it is tuned PLA)",
            "PLA+ prints hotter always (blends vary by brand)",
            "Plus is always better (plain PLA is fine for display parts)",
        ],
        "teaching_strategy": "Drop test both, compare a broken plain part to an intact plus part, then read the brand spec.",
        "script": "PLA+ is regular PLA with additives that boost strength, toughness, and impact resistance while keeping easy printing. Drop tests survive better, layer bonds hold longer, and the surface finishes about the same. The cost: slightly higher price, and the plus blend varies between brands, so results are not universal. PLA+ is not a new material; it is a tuned recipe. Choose it when parts take load or knocks; choose plain PLA for prints that just sit there. The plus buys margin, and margin wins.",
        "text_overlay": [
            "ADDITIVES, NOT A NEW PLASTIC",
            "MORE IMPACT, SAME EASY PRINT",
            "BLENDS VARY BY BRAND",
            "MARGIN WINS",
        ],
        "scenes": [
            {
                "goal": "Hook: the drop test",
                "teaching_point": "Plus survives the drop",
                "shot": "medium shot of two printed parts dropped on a bench",
                "motion": "slow-motion drop",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["PLA part", "PLA+ part", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two printed parts mid-drop over a workbench, neutral lab lighting",
            },
            {
                "goal": "The blend",
                "teaching_point": "Additives tune the base plastic",
                "shot": "diagram-style shot of PLA granules with added modifiers",
                "motion": "additives mix into the granules",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["PLA granules", "additives", "blend"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of PLA granules blending with additives, clean engineering visualization on a dark background",
            },
            {
                "goal": "The test",
                "teaching_point": "Layer bonds hold longer",
                "shot": "close-up shot of a bend test on two printed beams",
                "motion": "beams flex to the break",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["PLA beam", "PLA+ beam", "bend test"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bend test on PLA and PLA+ beams, bright task lighting, print lab",
            },
            {
                "goal": "The variation",
                "teaching_point": "Every brand has its own recipe",
                "shot": "medium shot of different brand spools labeled PLA+",
                "motion": "labels pan across the spools",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["brand spools", "PLA+ labels"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of PLA+ spools from different brands, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Loads and knocks get the plus",
                "shot": "wide hero shot of a functional printed bracket",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["functional bracket", "PLA+ print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a functional PLA+ printed bracket, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bent PLA+ beam next to a snapped PLA beam with a plus badge",
            "subject": "bend test comparison",
            "background": "dark workshop blur",
            "angle": "low side view",
            "lighting": "hard key with rim",
            "composition": "two beams side by side, badge on the survivor",
            "text": "PLA+ WORTH IT?",
            "elements": ["PLA+ beam", "snapped PLA beam", "plus badge"],
            "style": "geometry studio photography",
            "mood": "tested, tough, simple",
            "prompt": "photograph of a bent PLA plus beam beside a snapped PLA beam with a plus badge, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PLA+ vs PLA: Is the Plus Worth It?",
            "title_variations": [
                "PLA Plus Explained",
                "PLA+ vs PLA Strength",
                "Should You Buy PLA+",
                "Tough PLA vs PLA",
                "PLA+ for Functional Parts",
            ],
            "description": "PLA+ is plain PLA with additives mixed in to improve strength, toughness, and impact resistance, while keeping the easy printing that made PLA famous. Drop tests survive, layer bonds hold longer, and the surface looks about the same; the price is slightly higher and the recipe varies from brand to brand. For functional parts, hinges, and anything that takes knocks, the plus is worth it. For prints that sit on a shelf, plain PLA is still the value pick. This short compares both materials, shows the bend and drop tests, and explains what the plus actually buys you.",
            "hashtags": ["#PLA+", "#PLA", "#Filament", "#3Dprinting"],
            "seo_keywords": [
                "pla+ vs pla",
                "is pla+ worth it",
                "pla plus strength",
                "tough pla",
                "pla+ impact resistance",
                "best pla for parts",
                "pla plus brands",
            ],
        },
        "fact_check": [
            "PLA+ is PLA with strength and toughness additives.",
            "It prints about as easily as plain PLA.",
            "Blends vary between brands.",
            "Choose PLA+ for load and impact; plain PLA for display.",
            "The plus buys margin, not a new material.",
        ],
    },
    {
        "topic": "Mainboards & Firmware",
        "core_question": "What does the brain do, and what changes when you upgrade it?",
        "learning_objective": "The viewer understands board roles, driver choices, and firmware basics before upgrading.",
        "engineering_summary": "The mainboard is the printer's brain: it reads sensors, drives motors, and runs firmware. Choosing one means matching voltage, stepper drivers, and connector types, and firmware like Marlin or Klipper makes it all work. Drivers decide noise and smoothness; more memory buys features like input shaping. Upgrading a board is the biggest single upgrade: quieter, faster, more reliable motion. The catch: wiring mistakes fry boards, so match everything before power. The brain is only as good as the firmware and the wiring behind it.",
        "real_world_application": "Board swaps modernize old printers with quiet drivers, faster motion, and input shaping.",
        "common_misconceptions": [
            "Firmware is optional (a board is dead without it)",
            "Any driver works (drivers set noise, current, and smoothness)",
            "Upgrading is plug and play (wiring must match exactly)",
        ],
        "teaching_strategy": "Open a board, name the parts, then show the firmware screen and what an upgrade changes.",
        "script": "The mainboard is the printer's brain: it reads sensors, drives motors, and runs firmware. Choosing one means matching voltage, stepper drivers, and connector types, and firmware like Marlin or Klipper makes it all work. Drivers decide noise and smoothness; more memory buys features like input shaping. Upgrading a board is the biggest single upgrade: quieter, faster, more reliable motion. The catch: wiring mistakes fry boards, so match everything before power. The brain is only as good as the firmware and the wiring behind it.",
        "text_overlay": [
            "THE PRINTER'S BRAIN",
            "DRIVERS SET NOISE + SMOOTHNESS",
            "MARLIN OR KLIPPER RUNS IT",
            "WIRING MISTAKES FRY BOARDS",
        ],
        "scenes": [
            {
                "goal": "Hook: the brain",
                "teaching_point": "Sensors, motors, firmware",
                "shot": "medium shot of an open mainboard with cables",
                "motion": "cables route to the board",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["mainboard", "cables", "stepper drivers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an open printer mainboard with cables and stepper drivers, neutral lab lighting, workbench",
            },
            {
                "goal": "The drivers",
                "teaching_point": "Drivers decide noise and smoothness",
                "shot": "close-up shot of stepper driver chips",
                "motion": "chips highlight one by one",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["stepper drivers", "heatsinks", "board"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of stepper driver chips on a mainboard, bright task lighting, print lab",
            },
            {
                "goal": "The firmware",
                "teaching_point": "Marlin or Klipper makes it work",
                "shot": "screen capture of a firmware menu and console",
                "motion": "menu scrolls with settings",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["firmware menu", "settings", "console"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printer firmware menu on a screen, clean engineering visualization on a dark background",
            },
            {
                "goal": "The upgrade",
                "teaching_point": "Quieter, faster, more reliable",
                "shot": "medium shot of a board swap on a printer",
                "motion": "old board out, new board in",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["old board", "new board", "printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a mainboard upgrade in a printer, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match everything before power",
                "shot": "wide hero shot of a printer running after an upgrade",
                "motion": "slow push in on the motion",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["upgraded printer", "quiet motion"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer running after a mainboard upgrade, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An open mainboard with labeled driver chips and a firmware screen",
            "subject": "mainboard with labels",
            "background": "dark workshop blur",
            "angle": "top down",
            "lighting": "hard key with rim",
            "composition": "board center, firmware screen behind",
            "text": "THE BRAIN",
            "elements": ["mainboard", "driver chips", "firmware screen"],
            "style": "geometry studio photography",
            "mood": "upgraded, quiet, precise",
            "prompt": "photograph of an open mainboard with labeled driver chips and a firmware screen behind, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Mainboards & Firmware: The Printer's Brain",
            "title_variations": [
                "Which Mainboard Should I Choose",
                "Mainboard Upgrade Guide",
                "Marlin vs Klipper Basics",
                "Stepper Drivers Explained",
                "Printer Firmware 101",
            ],
            "description": "The mainboard is the printer's brain: it reads the sensors, drives the steppers, and runs the firmware that turns G-code into motion. Upgrading one is the single biggest upgrade you can make, adding quiet stepper drivers, smoother motion, and features like input shaping that old boards cannot run. The choices are real: board voltage, driver type, connector layout, and firmware flavor like Marlin or Klipper all have to match your machine. Wiring mistakes can fry the board instantly, so matching specs before powering on is everything. This short tours the board, the drivers, and the firmware that make it work.",
            "hashtags": ["#Mainboard", "#Firmware", "#3Dprinting", "#Upgrade"],
            "seo_keywords": [
                "printer mainboard",
                "mainboard upgrade",
                "marlin vs klipper",
                "stepper drivers explained",
                "printer firmware",
                "input shaping board",
                "quiet 3d printer",
            ],
        },
        "fact_check": [
            "The mainboard reads sensors and drives motors.",
            "Stepper drivers set noise, current, and smoothness.",
            "Marlin and Klipper are common firmware choices.",
            "Board swaps are the biggest single upgrade.",
            "Wiring mistakes can fry boards.",
        ],
    },
    {
        "topic": "Heater Cartridges",
        "core_question": "How does a metal tube become the hotend's heat source?",
        "learning_objective": "The viewer understands cartridge types, wattage, and failure modes.",
        "engineering_summary": "A heater cartridge is a resistive coil in a metal tube that turns current into heat. It sits inside the hotend block, and a thermistor or thermocouple reports back so firmware holds the temperature. Cartridges come in 12 and 24 volt versions; the wrong one draws the wrong current and can cook a board or barely heat. The wattage decides how fast the block recovers after the fan kicks on. When a cartridge dies, it fails open or shorts: replace it and re-tune. Heat is watts, and watts are controlled.",
        "real_world_application": "Hotend heat-up time, temperature stability, and safe board current all trace back to the cartridge spec.",
        "common_misconceptions": [
            "All cartridges are the same (voltage and wattage matter)",
            "The heater reads the temperature (a sensor does that)",
            "A dead cartridge just stops (it can short and cook the board)",
        ],
        "teaching_strategy": "Show a cartridge installed, read the wattage stamp, then show the failure modes.",
        "script": "A heater cartridge is a resistive coil in a metal tube that turns current into heat. It sits inside the hotend block, and a thermistor or thermocouple reports back so firmware holds the temperature. Cartridges come in 12 and 24 volt versions; the wrong one draws the wrong current and can cook a board or barely heat. The wattage decides how fast the block recovers after the fan kicks on. When a cartridge dies, it fails open or shorts: replace it and re-tune. Heat is watts, and watts are controlled.",
        "text_overlay": [
            "RESISTIVE COIL IN METAL",
            "12V OR 24V - MATCH IT",
            "WATTS SET RECOVERY",
            "FAILS OPEN OR SHORTS",
        ],
        "scenes": [
            {
                "goal": "Hook: the metal tube",
                "teaching_point": "Resistance turns current into heat",
                "shot": "close-up shot of a heater cartridge glowing in the hotend",
                "motion": "heat glow builds",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["heater cartridge", "hotend block"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a heater cartridge glowing inside a hotend block, bright task lighting, print lab",
            },
            {
                "goal": "The loop",
                "teaching_point": "Heater and sensor close the loop",
                "shot": "diagram-style shot of the heater and thermistor loop",
                "motion": "signal flows around the loop",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heater loop", "thermistor", "firmware"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the heater and thermistor control loop, clean engineering visualization on a dark background",
            },
            {
                "goal": "Voltages",
                "teaching_point": "12 and 24 volt versions",
                "shot": "medium shot of two cartridges side by side",
                "motion": "labels light up on each",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["12 volt cartridge", "24 volt cartridge", "labels"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of 12 and 24 volt heater cartridges side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "Wattage",
                "teaching_point": "Watts decide heat-up and recovery",
                "shot": "graphic-style shot of heat-up curves",
                "motion": "curves climb at different rates",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["heat-up curves", "wattage ratings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of heater cartridge heat-up curves, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Replace dead cartridges, re-tune",
                "shot": "wide hero shot of a fresh cartridge installed",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["new cartridge", "hotend"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fresh heater cartridge in a hotend, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A glowing cartridge with 24V stamped and a heat-up curve",
            "subject": "heater cartridge with stamp",
            "background": "dark workshop blur",
            "angle": "macro side view",
            "lighting": "hard key with rim",
            "composition": "cartridge center, stamp and curve flanking",
            "text": "HEAT IS WATTS",
            "elements": ["heater cartridge", "24V stamp", "heat-up curve"],
            "style": "geometry studio photography",
            "mood": "hot, steady, controlled",
            "prompt": "photograph of a glowing heater cartridge with a voltage stamp and a heat-up curve, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Heater Cartridges: How Hotends Get Hot",
            "title_variations": [
                "How Heater Cartridges Work",
                "12V vs 24V Cartridge",
                "Heater Cartridge Wattage",
                "Fix Hotend Heat Issues",
                "Cartridge Replacement Guide",
            ],
            "description": "A heater cartridge is a resistive coil sealed in a metal tube: apply current and it converts watts into heat inside the hotend block. Voltage must match the machine, wattage sets how fast the block heats and recovers, and a separate thermistor reads the temperature so firmware can hold the target. Get the voltage wrong and you either barely heat or cook the board. When cartridges fail they fail open or short, and the fix is a swap plus a quick re-tune. This short explains the parts, the specs, and the failure modes so you can pick and replace cartridges with confidence.",
            "hashtags": ["#HeaterCartridge", "#Hotend", "#3Dprinting", "#Repair"],
            "seo_keywords": [
                "heater cartridge",
                "how heater cartridges work",
                "12v vs 24v cartridge",
                "heater wattage hotend",
                "hotend not heating",
                "replace heater cartridge",
                "thermistor control loop",
            ],
        },
        "fact_check": [
            "A cartridge is a resistive coil in a metal tube.",
            "Voltage must match the printer; wattage sets recovery speed.",
            "The thermistor, not the heater, reads temperature.",
            "Wrong voltage can cook a board or barely heat.",
            "Failed cartridges fail open or short.",
        ],
    },
    {
        "topic": "PTFE Liner & Temperature",
        "core_question": "Why does the tube limit your temperature ceiling?",
        "learning_objective": "The viewer knows PTFE limits, degradation signs, and when to go all-metal.",
        "engineering_summary": "Many hotends guide filament through a PTFE tube that touches the heated zone. PTFE is slippery and self-lubricating, but it degrades above about 240 degrees Celsius, releasing fumes and gumming up. That is the hard ceiling: keep PETG cool, and forget nylon in a lined hotend. An all-metal heat break removes the tube from the hot zone, so high-temperature filament becomes possible. Check the liner length when you push temperatures. The tube is convenient, and temperature is its only enemy.",
        "real_world_application": "Printing hot materials safely means knowing the liner's ceiling and swapping to all-metal when needed.",
        "common_misconceptions": [
            "PTFE handles any temperature (it degrades near 240 Celsius)",
            "Degradation is silent (fumes and dark tube warn you)",
            "All-metal prints everything better (PTFE liners reduce friction jams)",
        ],
        "teaching_strategy": "Show the tube inside the hotend, the 240 degree line, and the all-metal swap.",
        "script": "Many hotends guide filament through a PTFE tube that touches the heated zone. PTFE is slippery and self-lubricating, but it degrades above about 240 degrees Celsius, releasing fumes and gumming up. That is the hard ceiling: keep PETG cool, and forget nylon in a lined hotend. An all-metal heat break removes the tube from the hot zone, so high-temperature filament becomes possible. Check the liner length when you push temperatures. The tube is convenient, and temperature is its only enemy.",
        "text_overlay": [
            "SLIPPERY, BUT NOT INVINCIBLE",
            "240C IS THE CEILING",
            "FUMES = DEGRADING",
            "ALL-METAL OPENS THE TOP END",
        ],
        "scenes": [
            {
                "goal": "Hook: the liner",
                "teaching_point": "Filament slides through PTFE",
                "shot": "diagram-style cutaway of a hotend with a PTFE liner",
                "motion": "liner highlights inside the hotend",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hotend cutaway", "PTFE liner", "filament path"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hotend cutaway showing the PTFE liner, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ceiling",
                "teaching_point": "Degrades above 240 Celsius",
                "shot": "graphic-style shot of a temperature scale with the 240 mark",
                "motion": "marker locks at 240",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temperature scale", "240 mark"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a temperature scale with the 240 degree mark, clean engineering visualization on a dark background",
            },
            {
                "goal": "The signs",
                "teaching_point": "Fumes, darkening, clogs",
                "shot": "close-up shot of a degraded PTFE tube",
                "motion": "tube darkens and warps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["degraded tube", "darkening", "clog"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a degraded PTFE tube darkening, bright task lighting, print lab",
            },
            {
                "goal": "The fix",
                "teaching_point": "All-metal removes the tube",
                "shot": "medium shot of an all-metal heat break install",
                "motion": "tube swaps for metal",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["all-metal heat break", "PTFE tube", "hotend"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an all-metal heat break replacing a PTFE liner, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Temperature is the tube's enemy",
                "shot": "wide hero shot of a hotend printing nylon hot",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["all-metal hotend", "high temp print"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an all-metal hotend printing a high temperature filament, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hotend cutaway with the PTFE liner and a 240C warning line",
            "subject": "hotend with liner marked",
            "background": "dark workshop blur",
            "angle": "cutaway view",
            "lighting": "hard key with rim",
            "composition": "cutaway center, 240C line across",
            "text": "240C CEILING",
            "elements": ["hotend cutaway", "PTFE liner", "240C line"],
            "style": "geometry studio photography",
            "mood": "hot, warned, mechanical",
            "prompt": "photograph of a hotend cutaway with the PTFE liner and a 240 degree warning line, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PTFE Liners: The 240C Ceiling",
            "title_variations": [
                "PTFE Temperature Limits",
                "All-Metal vs PTFE Hotend",
                "Why PTFE Degrades",
                "Safe Temperatures for Hotends",
                "Upgrade to All-Metal",
            ],
            "description": "PTFE liners make filament slide smoothly through the hotend, but the convenience has a ceiling: above about 240 degrees Celsius the tube degrades, releasing fumes, darkening, and eventually clogging. That hard limit is why high-temperature filament like nylon needs an all-metal hotend, where a metal heat break keeps the tube away from the hot zone. PETG prints fine in a lined hotend if you stay cool, and many printers never need more. This short shows where the liner sits, what the warning signs look like, and when the all-metal swap is worth it.",
            "hashtags": ["#PTFE", "#Hotend", "#3Dprinting", "#Temperatures"],
            "seo_keywords": [
                "ptfe temperature limit",
                "ptfe liner hotend",
                "all metal vs ptfe",
                "ptfe degradation",
                "240c hotend ceiling",
                "nylon hotend upgrade",
                "ptfe fumes",
            ],
        },
        "fact_check": [
            "PTFE liners touch the heated zone in many hotends.",
            "PTFE degrades above about 240 degrees Celsius.",
            "Degradation shows as fumes, darkening, and clogs.",
            "All-metal heat breaks remove the tube from the hot zone.",
            "Keep PETG cool and go all-metal for high-temperature filaments.",
        ],
    },
]
