"""Batch 50: PLA, polycarbonate PC, spool weight and flow, titanium in practice, radiation and infrared, workshop lighting, deburring tools, laser levels."""

CURATED = [
    # ======================================================================
    {
        "topic": "PLA",
        "core_question": "What is PLA filament?",
        "learning_objective": "The viewer understands PLA filament.",
        "engineering_summary": "PLA is the starter plastic and the workhorse: it is made from plant starch, prints at low temperature, and stays stiff and cheap, so it is the default for models, jigs, and prototypes. The trade is thermal: PLA softens near sixty degrees, creeps under steady load, and snaps before it bends, so it is not the choice for hot or stressed parts. The rules are temperature, cooling, and use: print it cool and fast, keep the fan on, and pick a tougher resin when the part will sit in a car. PLA prints easy and lives easy.",
        "real_world_application": "Prototypes, jigs, and display models are PLA territory.",
        "common_misconceptions": [
            "PLA is strong everywhere (it softens near sixty degrees)",
            "PLA is fully compostable in practice (industrial conditions only)",
            "One setting suits all PLA (brands and colors vary)",
        ],
        "teaching_strategy": "Show the easy print, then the heat test.",
        "script": "PLA is the starter plastic and the workhorse: it is made from plant starch, prints at low temperature, and stays stiff and cheap, so it is the default for models, jigs, and prototypes. The trade is thermal: PLA softens near sixty degrees, creeps under steady load, and snaps before it bends, so it is not the choice for hot or stressed parts. The rules are temperature, cooling, and use: print it cool and fast, keep the fan on, and pick a tougher resin when the part will sit in a car. PLA prints easy and lives easy.",
        "text_overlay": [
            "THE STARTER WORKHORSE",
            "PRINTS COOL AND CHEAP",
            "SOFTENS NEAR SIXTY DEGREES",
            "EASY TO PRINT, EASY TO LIVE WITH",
        ],
        "scenes": [
            {
                "goal": "Hook: the spool",
                "teaching_point": "Everyone starts here",
                "shot": "close-up shot of a bright PLA spool",
                "motion": "camera pans the glossy filament",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PLA spool", "glossy filament", "starter kit"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a bright PLA filament spool, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The ease",
                "teaching_point": "Low temp, stiff, cheap",
                "shot": "diagram-style shot of the PLA benefits",
                "motion": "temperature gauge stays low",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["low temp gauge", "stiff part", "cheap price tag"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of PLA print benefits, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Heat is the enemy",
                "shot": "diagram-style shot of the heat test",
                "motion": "part softens near sixty degrees",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["softening part", "thermometer", "bent sample"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of PLA softening with heat, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Cool, fast, fan on",
                "shot": "diagram-style shot of the PLA settings",
                "motion": "fan spins as layers cool",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cooling fan", "fast print", "crisp layers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of PLA print settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick the right resin for the job",
                "shot": "wide hero shot of printed PLA parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PLA models", "jigs", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of finished PLA parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bright PLA spool beside a printed model and a low temperature gauge",
            "subject": "PLA filament",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spool left, model right",
            "text": "SOFTENS NEAR SIXTY DEGREES",
            "elements": ["PLA spool", "printed model", "temperature gauge"],
            "style": "geometry studio photography",
            "mood": "easy, cool, stiff",
            "prompt": "photograph of a bright PLA spool beside a printed model and a digital thermometer showing the low print temperature, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "PLA: The Starter Workhorse",
            "title_variations": [
                "What Is PLA Filament",
                "PLA Print Settings",
                "PLA Temperature Guide",
                "Best PLA for Beginners",
                "PLA vs Other Filaments",
            ],
            "description": "PLA is the starter plastic and the workhorse: it is made from plant starch, prints at low temperature, and stays stiff and cheap, so it is the default for models, jigs, and prototypes. The trade is thermal: PLA softens near sixty degrees, creeps under steady load, and snaps before it bends, so it is not the choice for hot or stressed parts. The rules are temperature, cooling, and use: print it cool and fast, keep the fan on, and pick a tougher resin when the part will sit in a car. This short prints the model, runs the heat test, and picks the resin. PLA prints easy and lives easy.",
            "hashtags": ["#PLA", "#Filament", "#3DPrinting", "#Beginners"],
            "seo_keywords": [
                "what is PLA filament",
                "pla",
                "pla filament",
                "pla settings",
                "pla temperature",
                "pla vs abs",
                "pla heat resistance",
            ],
        },
        "fact_check": [
            "PLA prints cool and cheap.",
            "Plant starch makes it.",
            "It softens near sixty degrees.",
            "It snaps before bending.",
            "Keep the fan on.",
        ],
    },
    {
        "topic": "Polycarbonate: PC",
        "core_question": "How to print polycarbonate?",
        "learning_objective": "The viewer understands polycarbonate printing.",
        "engineering_summary": "Polycarbonate is the tough one: it shrugs off impacts, holds stiffness at high temperature, and prints parts that outlast ABS, but it pays for that toughness with a hard workflow. The rules are heat, dryness, and enclosure: PC prints hot, near three hundred degrees, it drinks moisture like nylon, and it warps hard without a hot chamber, because the shrinkage fights the bed. The wins come with the setup: a hardened nozzle, an enclosed printer, and a dry spool turn PC into real structural parts. Polycarbonate is a machine, not a filament.",
        "real_world_application": "Structural brackets and high-temp parts are printed in PC.",
        "common_misconceptions": [
            "PC prints like PLA (it needs extreme heat and an enclosure)",
            "Any nozzle survives (high temps need hardened steel)",
            "Warping is a settings issue (the chamber decides)",
        ],
        "teaching_strategy": "Show the hot workflow, then the enclosed print.",
        "script": "Polycarbonate is the tough one: it shrugs off impacts, holds stiffness at high temperature, and prints parts that outlast ABS, but it pays for that toughness with a hard workflow. The rules are heat, dryness, and enclosure: PC prints hot, near three hundred degrees, it drinks moisture like nylon, and it warps hard without a hot chamber, because the shrinkage fights the bed. The wins come with the setup: a hardened nozzle, an enclosed printer, and a dry spool turn PC into real structural parts. Polycarbonate is a machine, not a filament.",
        "text_overlay": [
            "THE TOUGH ONE",
            "NEAR THREE HUNDRED DEGREES",
            "DRY, HOT, ENCLOSED",
            "A MACHINE, NOT A FILAMENT",
        ],
        "scenes": [
            {
                "goal": "Hook: the tough part",
                "teaching_point": "It outlasts ABS",
                "shot": "close-up shot of a clear PC bracket",
                "motion": "camera pans the glossy part",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PC bracket", "glossy surface", "impact test"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clear polycarbonate bracket, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The heat",
                "teaching_point": "Hot nozzle, hot chamber",
                "shot": "diagram-style shot of the temperature scale",
                "motion": "gauge climbs past three hundred",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temperature gauge", "hot nozzle", "hot chamber"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of polycarbonate print temperatures, clean engineering visualization on a dark background",
            },
            {
                "goal": "The moisture",
                "teaching_point": "PC drinks water like nylon",
                "shot": "diagram-style shot of the dry box",
                "motion": "moisture leaves the spool",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dry box", "moisture arrow", "dry spool"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of drying polycarbonate filament, clean engineering visualization on a dark background",
            },
            {
                "goal": "The warp",
                "teaching_point": "Shrinkage fights the bed",
                "shot": "diagram-style shot of the warped corner",
                "motion": "corner lifts without a chamber",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["lifted corner", "shrink arrows", "enclosed fix"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of polycarbonate warping, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Setup turns it structural",
                "shot": "wide hero shot of an enclosed printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["enclosed printer", "hardened nozzle", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an enclosed printer printing polycarbonate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A clear PC part from an enclosed printer with a dry box",
            "subject": "polycarbonate printing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part left, printer right",
            "text": "DRY, HOT, ENCLOSED",
            "elements": ["clear PC part", "enclosed printer", "dry box"],
            "style": "geometry studio photography",
            "mood": "tough, hot, dried",
            "prompt": "photograph of a clear polycarbonate part emerging from an enclosed printer with a hardened nozzle and a dry box beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Polycarbonate: PC — A Machine, Not a Filament",
            "title_variations": [
                "How to Print Polycarbonate",
                "PC Filament Guide",
                "High Temp Filament Basics",
                "Polycarbonate vs ABS",
                "PC Print Settings",
            ],
            "description": "Polycarbonate is the tough one: it shrugs off impacts, holds stiffness at high temperature, and prints parts that outlast ABS, but it pays for that toughness with a hard workflow. The rules are heat, dryness, and enclosure: PC prints hot, near three hundred degrees, it drinks moisture like nylon, and it warps hard without a hot chamber, because the shrinkage fights the bed. The wins come with the setup: a hardened nozzle, an enclosed printer, and a dry spool turn PC into real structural parts. This short heats the chamber, dries the spool, and prints the bracket. Polycarbonate is a machine, not a filament.",
            "hashtags": ["#Polycarbonate", "#PC", "#3DPrinting", "#HighTemp"],
            "seo_keywords": [
                "how to print polycarbonate",
                "polycarbonate",
                "pc filament",
                "pc printing",
                "high temp filament",
                "polycarbonate vs abs",
                "pc print settings",
            ],
        },
        "fact_check": [
            "PC shrugs off impacts.",
            "It prints near three hundred.",
            "Moisture ruins the melt.",
            "Warping needs a chamber.",
            "Setup makes it structural.",
        ],
    },
    {
        "topic": "Spool Weight & Flow",
        "core_question": "Is spool weight exact?",
        "learning_objective": "The viewer understands spool weight and flow.",
        "engineering_summary": "The spool's weight is a promise with a tolerance: the label says one kilogram, the real filament mass varies a little, and the core adds weight that is not printable material. Flow is set separately: the slicer asks for a length, the extruder feeds it, and the flow rate decides whether the part matches the label. The rules are tare, measure, and calibrate: weigh the empty core, subtract it, and tune the flow factor until the part comes out right. Weight is the truth the flow settings chase.",
        "real_world_application": "Dimensional prints need a flow calibration, not the label.",
        "common_misconceptions": [
            "The label weight is exact (the mass varies a little)",
            "Flow is a fixed value (it must be calibrated per filament)",
            "Core weight does not matter (it is not printable material)",
        ],
        "teaching_strategy": "Show the tare scale, then the flow calibration.",
        "script": "The spool's weight is a promise with a tolerance: the label says one kilogram, the real filament mass varies a little, and the core adds weight that is not printable material. Flow is set separately: the slicer asks for a length, the extruder feeds it, and the flow rate decides whether the part matches the label. The rules are tare, measure, and calibrate: weigh the empty core, subtract it, and tune the flow factor until the part comes out right. Weight is the truth the flow settings chase.",
        "text_overlay": [
            "WEIGHT IS A PROMISE",
            "TARE THE CORE",
            "FLOW NEEDS CALIBRATION",
            "WEIGH, SUBTRACT, TUNE",
        ],
        "scenes": [
            {
                "goal": "Hook: the scale",
                "teaching_point": "Labels are promises",
                "shot": "close-up shot of a spool on a scale",
                "motion": "camera pans to the readout",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["filament spool", "digital scale", "weight readout"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a filament spool on a digital scale, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The core",
                "teaching_point": "The hub is not plastic",
                "shot": "diagram-style shot of the tare",
                "motion": "empty core weight drops off the total",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["empty core", "tare arrow", "true mass"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of taring a spool core, clean engineering visualization on a dark background",
            },
            {
                "goal": "The flow",
                "teaching_point": "Length fed versus length wanted",
                "shot": "diagram-style shot of the feed rate",
                "motion": "extruder feeds while the gauge reads",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extruder gear", "feed gauge", "flow factor"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of filament flow rate, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tune",
                "teaching_point": "Calibrate until it matches",
                "shot": "diagram-style shot of the calibration part",
                "motion": "part dimensions match the drawing",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["calibration part", "dimension marks", "match line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flow calibration, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Weight tells the truth",
                "shot": "wide hero shot of a calibrated print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["calibrated part", "correct walls", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dimensionally correct printed part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A spool on a scale beside an empty core and a calibration print",
            "subject": "spool weight and flow",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spool left, core right",
            "text": "WEIGH, SUBTRACT, TUNE",
            "elements": ["filament spool", "empty core", "digital scale"],
            "style": "geometry studio photography",
            "mood": "weighed, tared, tuned",
            "prompt": "photograph of a filament spool on a digital scale beside an empty spool core and a flow calibration print, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Spool Weight & Flow: Weight Is the Truth",
            "title_variations": [
                "Is Spool Weight Exact",
                "Filament Flow Calibration",
                "Spool Weight Accuracy",
                "Tare Filament Core",
                "Flow Factor Tuning",
            ],
            "description": "The spool's weight is a promise with a tolerance: the label says one kilogram, the real filament mass varies a little, and the core adds weight that is not printable material. Flow is set separately: the slicer asks for a length, the extruder feeds it, and the flow rate decides whether the part matches the label. The rules are tare, measure, and calibrate: weigh the empty core, subtract it, and tune the flow factor until the part comes out right. This short tares the core, measures the mass, and tunes the flow. Weight is the truth the flow settings chase.",
            "hashtags": ["#Filament", "#Calibration", "#FlowRate", "#3DPrinting"],
            "seo_keywords": [
                "is spool weight exact",
                "spool weight",
                "filament flow",
                "spool accuracy",
                "material weight",
                "flow calibration filament",
                "tare filament core",
            ],
        },
        "fact_check": [
            "Labels are a promise.",
            "The core is not material.",
            "Flow needs calibration.",
            "Tare before you weigh.",
            "Weight tells the truth.",
        ],
    },
    {
        "topic": "Titanium in Practice",
        "core_question": "When should you use titanium?",
        "learning_objective": "The viewer understands titanium in practice.",
        "engineering_summary": "Titanium is the exotic metal: it matches steel strength at half the weight, shrugs off corrosion and heat, and aerospace, medical, and bike builders love it, but every advantage is priced in money and difficulty. The trade is manufacturing: titanium is hard to machine because it work-hardens and burns tools, and printing it needs argon-filled powder machines, so the cost lands far above steel or aluminum. The rules are use, weight, and budget: choose titanium when strength per gram or corrosion wins the job, and let steel handle the rest. Titanium is a specialist, not a default.",
        "real_world_application": "Aerospace brackets and medical implants justify the price.",
        "common_misconceptions": [
            "Titanium is stronger than steel (it matches steel, lighter)",
            "It machines like aluminum (it work-hardens and burns tools)",
            "Printing it is simple (it needs argon-filled machines)",
        ],
        "teaching_strategy": "Show the weight compare, then the hard machining.",
        "script": "Titanium is the exotic metal: it matches steel strength at half the weight, shrugs off corrosion and heat, and aerospace, medical, and bike builders love it, but every advantage is priced in money and difficulty. The trade is manufacturing: titanium is hard to machine because it work-hardens and burns tools, and printing it needs argon-filled powder machines, so the cost lands far above steel or aluminum. The rules are use, weight, and budget: choose titanium when strength per gram or corrosion wins the job, and let steel handle the rest. Titanium is a specialist, not a default.",
        "text_overlay": [
            "STEEL STRENGTH, HALF THE WEIGHT",
            "HARD TO MACHINE, COSTLY TO PRINT",
            "STRENGTH PER GRAM WINS",
            "A SPECIALIST, NOT A DEFAULT",
        ],
        "scenes": [
            {
                "goal": "Hook: the scale",
                "teaching_point": "Same strength, half the weight",
                "shot": "close-up shot of titanium and steel parts on a scale",
                "motion": "camera pans the balanced pair",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["titanium part", "steel part", "weight scale"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of titanium and steel parts on a scale, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The wins",
                "teaching_point": "Corrosion and heat resistance",
                "shot": "diagram-style shot of the titanium wins",
                "motion": "corrosion and heat tiles glow",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["corrosion tile", "heat tile", "strength bar"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of titanium advantages, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Hard to machine, costly to print",
                "shot": "diagram-style shot of the machining struggle",
                "motion": "tool burns while titanium work-hardens",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["burning tool", "work-hardened edge", "argon chamber"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of titanium machining difficulty, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Use, weight, budget",
                "shot": "diagram-style shot of the decision tiles",
                "motion": "strength per gram tips the choice",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["use tile", "weight tile", "budget tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of titanium selection rules, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Specialist metal",
                "shot": "wide hero shot of titanium parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["titanium parts", "medical implant", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of finished titanium parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A titanium bracket beside steel and aluminum on a weight scale",
            "subject": "titanium in practice",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "titanium left, metals right",
            "text": "STEEL STRENGTH, HALF THE WEIGHT",
            "elements": ["titanium bracket", "steel part", "weight scale"],
            "style": "geometry studio photography",
            "mood": "light, strong, priced",
            "prompt": "photograph of a lightweight titanium bracket beside steel and aluminum parts on a scale showing the weight comparison, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Titanium in Practice: A Specialist, Not a Default",
            "title_variations": [
                "When Should You Use Titanium",
                "Titanium vs Steel Weight",
                "Titanium Strength Guide",
                "Lightweight Metal Choice",
                "Titanium Cost vs Benefit",
            ],
            "description": "Titanium is the exotic metal: it matches steel strength at half the weight, shrugs off corrosion and heat, and aerospace, medical, and bike builders love it, but every advantage is priced in money and difficulty. The trade is manufacturing: titanium is hard to machine because it work-hardens and burns tools, and printing it needs argon-filled powder machines, so the cost lands far above steel or aluminum. The rules are use, weight, and budget: choose titanium when strength per gram or corrosion wins the job, and let steel handle the rest. This short weighs the pair, burns the tool, and sets the budget. Titanium is a specialist, not a default.",
            "hashtags": ["#Titanium", "#Materials", "#Aerospace", "#Engineering"],
            "seo_keywords": [
                "when should you use titanium",
                "titanium",
                "ti parts",
                "titanium strength",
                "lightweight metal",
                "titanium vs steel weight",
                "titanium machining difficulty",
            ],
        },
        "fact_check": [
            "Titanium matches steel strength.",
            "It weighs half as much.",
            "It work-hardens when cut.",
            "Printing needs argon machines.",
            "It is a specialist metal.",
        ],
    },
    {
        "topic": "Radiation & Infrared",
        "core_question": "How does heat radiate?",
        "learning_objective": "The viewer understands radiation and infrared.",
        "engineering_summary": "Radiant heat needs no air: every surface emits infrared, and the hotter surface pours energy at the cooler one, which is why a fire warms you across the room and the sun crosses empty space. The twist is emissivity: a dark, rough surface radiates and absorbs well, while a shiny one reflects and stays cool, so a polished heat sink loses less heat than a blackened one. The rules are temperature, emissivity, and area: radiation grows with the fourth power of temperature, dark surfaces trade heat best, and more area radiates more. Heat leaves objects as light.",
        "real_world_application": "Heat sinks and radiators are finished dark to radiate better.",
        "common_misconceptions": [
            "Heat needs air to travel (radiation crosses vacuum)",
            "Shiny surfaces radiate best (they reflect instead)",
            "Radiation is slow (it scales with temperature to the fourth)",
        ],
        "teaching_strategy": "Show the glowing emitter, then the emissivity compare.",
        "script": "Radiant heat needs no air: every surface emits infrared, and the hotter surface pours energy at the cooler one, which is why a fire warms you across the room and the sun crosses empty space. The twist is emissivity: a dark, rough surface radiates and absorbs well, while a shiny one reflects and stays cool, so a polished heat sink loses less heat than a blackened one. The rules are temperature, emissivity, and area: radiation grows with the fourth power of temperature, dark surfaces trade heat best, and more area radiates more. Heat leaves objects as light.",
        "text_overlay": [
            "HEAT NEEDS NO AIR",
            "FIRE WARMS ACROSS THE ROOM",
            "DARK RADIATES, SHINY REFLECTS",
            "FOURTH POWER OF TEMPERATURE",
        ],
        "scenes": [
            {
                "goal": "Hook: the glowing heater",
                "teaching_point": "It warms without touching",
                "shot": "close-up shot of a glowing heat source",
                "motion": "camera pans the radiating glow",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["glowing heater", "infrared glow", "warm hand"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a glowing infrared heater, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The waves",
                "teaching_point": "Energy crosses empty space",
                "shot": "diagram-style shot of the radiant waves",
                "motion": "waves travel from hot to cold",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["radiant waves", "hot surface", "cold surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of radiant heat waves, clean engineering visualization on a dark background",
            },
            {
                "goal": "The emissivity",
                "teaching_point": "Dark trades, shiny reflects",
                "shot": "diagram-style shot of the surface compare",
                "motion": "black surface glows, polished stays dim",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dark surface", "polished surface", "emissivity pair"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of emissivity comparison, clean engineering visualization on a dark background",
            },
            {
                "goal": "The math",
                "teaching_point": "Fourth power of temperature",
                "shot": "diagram-style shot of the radiation curve",
                "motion": "curve climbs steeply with heat",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["radiation curve", "temperature axis", "steep climb"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the radiation temperature curve, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Finish sinks dark",
                "shot": "wide hero shot of a blackened heat sink",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["black heat sink", "finned area", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a blackened heat sink, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A glowing object radiating infrared waves toward a cooler surface",
            "subject": "radiation and infrared",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "glow left, receiver right",
            "text": "DARK RADIATES, SHINY REFLECTS",
            "elements": ["glowing source", "infrared waves", "cool receiver"],
            "style": "geometry studio photography",
            "mood": "radiated, absorbed, reflected",
            "prompt": "photograph of a glowing hot object radiating infrared heat waves toward a cooler surface with emissivity arrows shown, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Radiation & Infrared: Heat Needs No Air",
            "title_variations": [
                "How Does Heat Radiate",
                "Infrared Radiation Explained",
                "Emissivity Basics",
                "Thermal Radiation Guide",
                "Heat Transfer by Radiation",
            ],
            "description": "Radiant heat needs no air: every surface emits infrared, and the hotter surface pours energy at the cooler one, which is why a fire warms you across the room and the sun crosses empty space. The twist is emissivity: a dark, rough surface radiates and absorbs well, while a shiny one reflects and stays cool, so a polished heat sink loses less heat than a blackened one. The rules are temperature, emissivity, and area: radiation grows with the fourth power of temperature, dark surfaces trade heat best, and more area radiates more. This short follows the waves, compares the surfaces, and blackens the sink. Heat leaves objects as light.",
            "hashtags": ["#Radiation", "#Infrared", "#HeatTransfer", "#Thermodynamics"],
            "seo_keywords": [
                "how does heat radiate",
                "radiation",
                "infrared",
                "emissivity",
                "thermal radiation",
                "emissivity heat sink",
                "radiant heat transfer",
            ],
        },
        "fact_check": [
            "Radiant heat needs no air.",
            "Hot pours at cold.",
            "Dark surfaces radiate best.",
            "Shiny surfaces reflect.",
            "Radiation scales to the fourth power.",
        ],
    },
    {
        "topic": "Workshop Lighting",
        "core_question": "What lighting for a workshop?",
        "learning_objective": "The viewer understands workshop lighting.",
        "engineering_summary": "Workshop lighting is a tool: bright task light over the bench stops squinting and mistakes, while the color temperature decides how colors read, because a warm bulb makes a gray part look yellow and a cool bulb makes it look blue. The rules are brightness, color, and placement: aim for bright, even light with few shadows, pick a neutral color temperature for judging parts, and put the light where your hands work. Glare is the enemy: a bare bulb in your eyes hides detail. Light is the cheapest precision tool you own.",
        "real_world_application": "A neutral 4000K bar over the bench reads parts accurately.",
        "common_misconceptions": [
            "Any bright bulb works (color temperature changes how parts read)",
            "More light means more glare (placement beats brightness)",
            "Lighting is decoration (it is a precision tool)",
        ],
        "teaching_strategy": "Show the warm versus cool bulb, then the task bar.",
        "script": "Workshop lighting is a tool: bright task light over the bench stops squinting and mistakes, while the color temperature decides how colors read, because a warm bulb makes a gray part look yellow and a cool bulb makes it look blue. The rules are brightness, color, and placement: aim for bright, even light with few shadows, pick a neutral color temperature for judging parts, and put the light where your hands work. Glare is the enemy: a bare bulb in your eyes hides detail. Light is the cheapest precision tool you own.",
        "text_overlay": [
            "LIGHTING IS A TOOL",
            "COLOR TEMPERATURE LIES OR TELLS",
            "NEUTRAL FOR JUDGING PARTS",
            "THE CHEAPEST PRECISION TOOL",
        ],
        "scenes": [
            {
                "goal": "Hook: the dim bench",
                "teaching_point": "Squinting costs mistakes",
                "shot": "close-up shot of a dim workbench",
                "motion": "camera pans the shadowy bench",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["dim bench", "shadow parts", "task area"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a dim workshop bench, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The color",
                "teaching_point": "Warm and cool change the part",
                "shot": "diagram-style shot of the two bulbs",
                "motion": "gray part shifts yellow then blue",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["warm bulb", "cool bulb", "gray part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of warm versus cool lighting, clean engineering visualization on a dark background",
            },
            {
                "goal": "The placement",
                "teaching_point": "Light where the hands work",
                "shot": "diagram-style shot of the task bar",
                "motion": "light bar sweeps the bench",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["task bar", "hand zone", "even pool"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of task lighting placement, clean engineering visualization on a dark background",
            },
            {
                "goal": "The glare",
                "teaching_point": "Bare bulbs hide detail",
                "shot": "diagram-style shot of the glare",
                "motion": "bare bulb floods the eyes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bare bulb", "glare ray", "hidden detail"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of glare hiding detail, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Bright, even, neutral",
                "shot": "wide hero shot of a lit bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["lit bench", "task bar", "clean parts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a brightly lit workshop bench, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bright bench with warm and cool bulbs showing color temperature",
            "subject": "workshop lighting",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bench left, bulbs right",
            "text": "LIGHTING IS A TOOL",
            "elements": ["task bar", "warm bulb", "cool bulb"],
            "style": "geometry studio photography",
            "mood": "bright, even, neutral",
            "prompt": "photograph of a bright workshop bench with task lighting and two parts under a warm bulb and a cool bulb showing color temperature, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Workshop Lighting: The Cheapest Precision Tool You Own",
            "title_variations": [
                "What Lighting for a Workshop",
                "Workbench Light Guide",
                "Task Lighting Basics",
                "Color Temperature for Workshops",
                "Bright Shop Lighting",
            ],
            "description": "Workshop lighting is a tool: bright task light over the bench stops squinting and mistakes, while the color temperature decides how colors read, because a warm bulb makes a gray part look yellow and a cool bulb makes it look blue. The rules are brightness, color, and placement: aim for bright, even light with few shadows, pick a neutral color temperature for judging parts, and put the light where your hands work. Glare is the enemy: a bare bulb in your eyes hides detail. This short dims the bench, swaps the bulbs, and lights the work. Light is the cheapest precision tool you own.",
            "hashtags": ["#Workshop", "#Lighting", "#TaskLighting", "#Workspace"],
            "seo_keywords": [
                "what lighting for a workshop",
                "workshop lighting",
                "workbench light",
                "task lighting",
                "color temp",
                "best workshop lighting",
                "workbench color temperature",
            ],
        },
        "fact_check": [
            "Lighting prevents mistakes.",
            "Color temperature changes parts.",
            "Neutral reads parts best.",
            "Placement beats brightness.",
            "Glare hides detail.",
        ],
    },
    {
        "topic": "Deburring Tools",
        "core_question": "How do you deburr edges?",
        "learning_objective": "The viewer understands deburring tools.",
        "engineering_summary": "Deburring is the last pass: machining and printing leave burrs, chips, and whisker edges that snag, cut, and look unprofessional, and the fix is a set of simple tools that shave them smooth. The kit is small: a handheld deburring tool with a swivel blade rides along the edge, a countersink cleans holes, and sanding blocks and needle files refine tight spots. The rules are direction, pressure, and finish: drag the blade in one direction, let the tool do the work, and finish with fine grit for a clean edge. Smooth edges are the mark of a finished part.",
        "real_world_application": "A swivel-blade deburrer cleans edges in seconds.",
        "common_misconceptions": [
            "Burrs are cosmetic (they snag, cut, and catch)",
            "Harder pressure cuts better (light passes win)",
            "One tool does it all (each tool has a job)",
        ],
        "teaching_strategy": "Show the swivel blade ride, then the countersink on a hole.",
        "script": "Deburring is the last pass: machining and printing leave burrs, chips, and whisker edges that snag, cut, and look unprofessional, and simple tools fix it. The kit is small: a handheld deburring tool with a swivel blade rides along the edge, a countersink cleans holes, and sanding blocks and needle files refine tight spots. The rules are direction, pressure, and finish: drag the blade in one direction, let the tool do the work, and finish with fine grit for a clean edge. Smooth edges are the mark of a finished part.",
        "text_overlay": [
            "BURRS SNUG, CUT, AND CATCH",
            "THE SWIVEL BLADE RIDES",
            "ONE DIRECTION, LIGHT PRESSURE",
            "SMOOTH IS FINISHED",
        ],
        "scenes": [
            {
                "goal": "Hook: the burr",
                "teaching_point": "Rough edges snag and cut",
                "shot": "close-up shot of a burred edge",
                "motion": "camera pans the jagged edge",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["burred part", "jagged edge", "rough face"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part with a burred edge, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The blade",
                "teaching_point": "Swivel blade rides the edge",
                "shot": "diagram-style shot of the deburrer",
                "motion": "blade glides along the edge",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["deburring tool", "swivel blade", "smooth line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a deburring tool, clean engineering visualization on a dark background",
            },
            {
                "goal": "The holes",
                "teaching_point": "Countersink cleans the bore",
                "shot": "diagram-style shot of the countersink",
                "motion": "chamfer appears at the hole mouth",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["countersink", "hole mouth", "clean chamfer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a countersink cleaning a hole, clean engineering visualization on a dark background",
            },
            {
                "goal": "The finish",
                "teaching_point": "Fine grit refines the spot",
                "shot": "diagram-style shot of the sanding block",
                "motion": "block smooths the tight spot",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sanding block", "needle file", "fine grit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of fine sanding a spot, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Smooth edges mean finished",
                "shot": "wide hero shot of a deburred part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["deburred part", "clean edges", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smoothly deburred part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A swivel-blade deburrer riding along a jagged edge",
            "subject": "deburring tools",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "tool left, part right",
            "text": "SMOOTH IS FINISHED",
            "elements": ["deburring tool", "swivel blade", "burred edge"],
            "style": "geometry studio photography",
            "mood": "smooth, clean, finished",
            "prompt": "photograph of a swivel blade deburring tool riding along a burred metal edge leaving a smooth line, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Deburring Tools: Smooth Is Finished",
            "title_variations": [
                "How Do You Deburr Edges",
                "Best Deburring Tool",
                "Deburr Machined Parts",
                "Edge Finishing Basics",
                "Countersink Holes Clean",
            ],
            "description": "Deburring is the last pass: machining and printing leave burrs, chips, and whisker edges that snag, cut, and look unprofessional, and the fix is a set of simple tools that shave them smooth. The kit is small: a handheld deburring tool with a swivel blade rides along the edge, a countersink cleans holes, and sanding blocks and needle files refine tight spots. The rules are direction, pressure, and finish: drag the blade in one direction, let the tool do the work, and finish with fine grit for a clean edge. This short follows the blade, countersinks the hole, and sands the spot. Smooth edges are the mark of a finished part.",
            "hashtags": ["#Deburring", "#Finishing", "#Machining", "#Workshop"],
            "seo_keywords": [
                "how do you deburr edges",
                "deburring",
                "deburr tool",
                "edge finishing",
                "swivel blade",
                "deburr metal parts",
                "countersink holes",
            ],
        },
        "fact_check": [
            "Burrs snag and cut.",
            "Swivel blades ride edges.",
            "Countersinks clean holes.",
            "Fine grit refines spots.",
            "Smooth edges mean finished.",
        ],
    },
    {
        "topic": "Laser Levels",
        "core_question": "When do you trust a laser level?",
        "learning_objective": "The viewer understands laser levels.",
        "engineering_summary": "A laser level draws a perfect reference line: a self-leveling unit spins a beam into a flat plane, and suddenly every shelf, frame, and bracket lines up, but only if the tool earns your trust. The catch is calibration: the unit assumes it is level, a drop can knock the pendulum out of true, and a wall that is off plumb makes the beam look wrong when the tool is right. The rules are check, position, and read: run a level check on a known wall, keep the laser stable, and remember the beam is only as good as the mount. Trust the line, verify the tool.",
        "real_world_application": "A self-leveling laser lines up shelves and brackets fast.",
        "common_misconceptions": [
            "The laser is always level (drops knock it out of true)",
            "The beam is the truth (a wall off plumb lies to you)",
            "Any surface reads the same (shiny walls scatter the beam)",
        ],
        "teaching_strategy": "Show the check against a known wall, then the true line.",
        "script": "A laser level draws a reference line: a self-leveling unit spins a beam into a flat plane, and every shelf, frame, and bracket lines up, but only if the tool earns your trust. The catch is calibration: the unit assumes it is level, a drop knocks the pendulum off true, and a wall off plumb makes the beam look wrong when the tool is right. The rules are check, position, and read: check against a known wall, keep the laser stable, and know the beam is as good as the mount. Trust the line, verify the tool.",
        "text_overlay": [
            "A LASER DRAWS THE LINE",
            "DROPS KNOCK IT OUT OF TRUE",
            "WALLS OFF PLUMB LIE",
            "TRUST THE LINE, VERIFY THE TOOL",
        ],
        "scenes": [
            {
                "goal": "Hook: the perfect line",
                "teaching_point": "One beam, every shelf level",
                "shot": "close-up shot of a laser line on a wall",
                "motion": "camera pans the clean red line",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["laser level", "red beam", "marked wall"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a laser level drawing a line on a wall, dark engineering lab, cinematic key light",
            },
            {
                "goal": "The trust",
                "teaching_point": "It assumes it is level",
                "shot": "diagram-style shot of the pendulum",
                "motion": "drop knocks the pendulum off true",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pendulum", "drop impact", "tilted beam"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a laser level pendulum, clean engineering visualization on a dark background",
            },
            {
                "goal": "The wall",
                "teaching_point": "Off plumb walls lie",
                "shot": "diagram-style shot of the wall check",
                "motion": "beam sits true while the wall leans",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["true beam", "leaning wall", "plumb arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a laser line against an out of plumb wall, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Check, position, read",
                "shot": "diagram-style shot of the check tiles",
                "motion": "known wall verifies the beam",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["check tile", "position tile", "read tile"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of laser level usage rules, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Verify the tool",
                "shot": "wide hero shot of a leveled shelf line",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["leveled shelf", "straight line", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a leveled shelf with a straight laser line, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A laser level casting a perfect line against a marked wall",
            "subject": "laser levels",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "laser left, line right",
            "text": "TRUST THE LINE, VERIFY THE TOOL",
            "elements": ["laser level", "red beam", "marked wall"],
            "style": "geometry studio photography",
            "mood": "leveled, checked, trusted",
            "prompt": "photograph of a self-leveling laser casting a crisp red reference line on a marked wall with a level check fixture, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Laser Levels: Trust the Line, Verify the Tool",
            "title_variations": [
                "When Do You Trust a Laser Level",
                "Laser Level Calibration",
                "Self-Leveling Laser Basics",
                "Mark Straight Lines Fast",
                "Laser Level Check",
            ],
            "description": "A laser level draws a perfect reference line: a self-leveling unit spins a beam into a flat plane, and suddenly every shelf, frame, and bracket lines up, but only if the tool earns your trust. The catch is calibration: the unit assumes it is level, a drop can knock the pendulum out of true, and a wall that is off plumb makes the beam look wrong when the tool is right. The rules are check, position, and read: run a level check on a known wall, keep the laser stable, and remember the beam is only as good as the mount. This short drops the pendulum, checks the wall, and marks the line. Trust the line, verify the tool.",
            "hashtags": ["#LaserLevel", "#Leveling", "#Tools", "#Workshop"],
            "seo_keywords": [
                "when do you trust a laser level",
                "laser level",
                "self leveling",
                "straight lines",
                "level calibration",
                "laser level check",
                "mark shelves level",
            ],
        },
        "fact_check": [
            "A laser draws a reference line.",
            "It assumes it is level.",
            "Drops knock it out of true.",
            "Off plumb walls lie.",
            "Verify the tool before trusting.",
        ],
    },
]