"""Batch 6: bed systems, hotends, finishing, process comparison, infill, and power transmission."""

CURATED = [
    # ======================================================================
    {
        "topic": "Print Bed Types",
        "core_question": "Which build plate surface should I use for which filament?",
        "learning_objective": "The viewer can compare glass, PEI, and build-surface options and pick the right bed for PLA, PETG, ABS, and TPU.",
        "engineering_summary": "The build surface sets the adhesion chemistry between the first layer and the plate. Glass gives a smooth glossy first layer and tolerates higher heat, but sticks poorly for some materials and can bond too well to PETG (which can tear chunks out of glass). PEI sheets - smooth or textured - are the industry favorite: strong adhesion when hot, parts pop off when cool, and PETG releases cleanly with a thin layer of adhesive or by switching to the textured side. Spring steel magnetic beds make removal and flexing easy. Common rules: PLA loves smooth PEI or glass with glue; PETG needs a release layer on glass and prefers textured PEI; ABS wants a hot bed plus enclosure.",
        "real_world_application": "Production print farms standardize on PEI spring steel so the same bed handling procedure works across every machine; textured PEI is the default for engineering materials.",
        "common_misconceptions": [
            "One surface works for every filament (PETG on glass can bond permanently; TPU needs release)",
            "Glue stick is for adhesion only (it is also a release layer for PETG on glass)",
            "Smooth surfaces always stick better (textured PEI grips better and releases easier)",
        ],
        "teaching_strategy": "Open with a PETG chunk torn out of glass, then compare surface options with a material table and end with a simple pairing rule.",
        "script": "Which bed surface? Glass gives that glossy first layer, but PETG can bond to it like concrete and rip chunks out. PEI is the workhorse: it grips hard when hot, and parts pop off when the plate cools. Smooth PEI loves PLA; the textured side releases PETG and TPU cleanly. Spring steel magnetic beds flex to pop prints loose, and ABS wants a hot bed and an enclosure. So: smooth PEI for PLA, textured PEI for PETG and flexibles, glass with glue when you must. Match the surface to the material, and first layers stop being a fight.",
        "text_overlay": [
            "GLASS: GLOSSY, PETG RISK",
            "PEI: GRIPS HOT, POPS COOL",
            "TEXTURED: PETG + TPU",
            "MATCH SURFACE TO MATERIAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the glass chunk",
                "teaching_point": "PETG can bond permanently to glass",
                "shot": "macro close-up of a glass bed with a torn chunk of PETG stuck to it",
                "motion": "slow push-in on the damage",
                "lighting": "raking side light",
                "background": "dark print bay",
                "objects": ["glass bed", "torn PETG chunk", "scar"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a glass print bed with a torn chunk of PETG bonded to it, raking side light, dark print bay",
            },
            {
                "goal": "The PEI workhorse",
                "teaching_point": "Grips hot, releases cool",
                "shot": "medium shot of a PEI flex plate with a part popping off",
                "motion": "plate flexes and the part releases",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["PEI plate", "print", "flexing motion"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a flexing PEI build plate with a 3D print releasing from it, bright task lighting, print lab",
            },
            {
                "goal": "Smooth vs textured",
                "teaching_point": "Surface texture changes the material pairing",
                "shot": "macro shot of smooth and textured PEI side by side with prints",
                "motion": "slow pan across both surfaces",
                "lighting": "even diffused light",
                "background": "dark bench",
                "objects": ["smooth PEI", "textured PEI", "printed parts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of smooth and textured PEI build surfaces side by side with printed parts, even diffused lighting, dark bench",
            },
            {
                "goal": "Material pairings",
                "teaching_point": "PLA, PETG, ABS, TPU each want a surface",
                "shot": "tablet-style graphic pairing materials with surfaces",
                "motion": "pairings highlight one by one",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["pairing table", "bed surfaces", "spools"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a material to bed surface pairing table on a dark studio screen, even diffused lighting, spools nearby",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match surface to material",
                "shot": "wide hero shot of a perfect first layer on PEI with the material labelled",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["PEI plate", "perfect first layer", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a perfect first layer printing on a PEI build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three bed surfaces with their best materials labelled",
            "subject": "glass, smooth PEI, and textured PEI plates",
            "background": "dark print lab blur",
            "angle": "top-down close-up",
            "lighting": "hard key with rim",
            "composition": "three plates in a row with material labels",
            "text": "PICK THE BED",
            "elements": ["glass plate", "PEI plates", "material labels", "prints"],
            "style": "industrial top-down photography",
            "mood": "ordered, comparative, practical",
            "prompt": "photograph of glass, smooth PEI, and textured PEI build plates in a row with material labels, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Which Print Bed Surface?",
            "title_variations": [
                "Glass vs PEI Build Plates",
                "Best Build Surface for PETG",
                "Bed Surfaces Compared",
                "Why PETG Tears Glass",
                "Picking a Build Plate",
            ],
            "description": "The build surface decides how the first layer bonds to the plate. Glass gives a glossy first layer but can bond PETG so strongly that parts tear chunks out of it. PEI is the workhorse: smooth PEI loves PLA, while the textured side releases PETG and TPU cleanly. Spring steel magnetic beds flex to pop parts off, and ABS needs a hot bed and an enclosure no matter the surface. This short compares glass, PEI, and coated surfaces, explains the PETG-on-glass danger, and gives a simple pairing rule for PLA, PETG, ABS, and TPU so first layers stop being a fight.",
            "hashtags": ["#BuildPlate", "#3Dprinting", "#Adhesion", "#PEI"],
            "seo_keywords": [
                "best build plate for 3d printing",
                "glass vs PEI bed",
                "PETG glass bed tearing",
                "textured PEI",
                "flexible build plate",
                "build surface comparison",
                "first layer adhesion surface",
            ],
        },
        "fact_check": [
            "PETG can bond so strongly to bare glass that it tears glass fragments out on removal.",
            "PEI sheets offer strong hot adhesion and release as the bed cools below the material's bonding temperature.",
            "Textured PEI reduces surface contact area, easing release for PETG and flexible materials.",
            "Glass provides the smoothest first-layer finish but requires a release agent for PETG.",
            "Spring steel magnetic beds combine PEI adhesion with flex-based part removal.",
        ],
    },
    # ======================================================================
    {
        "topic": "Hotend Types",
        "core_question": "What is inside a hotend, and which type should I choose?",
        "learning_objective": "The viewer can name the hotend zones, compare PTFE-lined and all-metal designs, and pick one by the materials they print.",
        "engineering_summary": "A hotend has three zones: the cold side (filament intake), the heat break (a thermal bottleneck that keeps the cold side cool), and the heat block with the nozzle. PTFE-lined hotends use a Teflon tube down to the nozzle, which gives smooth feeding and easy assembly but limits temperature to about 240 C and can degrade, releasing fumes. All-metal hotends remove the liner: the filament rides the metal walls, supporting 280 C+ for PETG, ABS, nylon, and polycarbonate. All-metal designs need better heat-break cooling to avoid heat creep jams. Volumetric flow, not just temperature, is the modern selection axis: high-flow hotends exchange heating length and throat design for speed.",
        "real_world_application": "A maker printing only PLA and PETG stays on a PTFE-lined hotend; printing nylon or PC, or chasing high speed, forces an all-metal high-flow design.",
        "common_misconceptions": [
            "All-metal is always better (PTFE-lined is cheaper, easier, and perfectly fine below 240 C)",
            "Temperature is the only spec (flow rate and cooling design matter for speed printing)",
            "All-metal hotends never jam (they jam from heat creep if cooling is inadequate)",
        ],
        "teaching_strategy": "Cut into a hotend to show the three zones, compare liner types with a temperature scale, then a flow-based selection rule.",
        "script": "Peek inside a hotend: filament goes in the cold side, through the heat break, and melts in the block. The heat break keeps plastic stiff above and molten below. PTFE-lined hotends are simple and smooth, but the tube dies above about two-forty Celsius. All-metal hotends run filament on metal walls, hitting two-eighty-plus: nylon, polycarbonate, real speed. The catch is cooling - all-metal jams from heat creep if the heat break runs hot. If you print PLA and PETG, the lined hotend is perfect. Going exotic or fast? All-metal, and cool it well.",
        "text_overlay": [
            "3 ZONES: COLD | BREAK | BLOCK",
            "PTFE LIMIT: 240C",
            "ALL-METAL: 280C+",
            "COOL THE HEAT BREAK",
        ],
        "scenes": [
            {
                "goal": "Hook: the cutaway",
                "teaching_point": "A hotend is three engineered zones",
                "shot": "cutaway graphic-style shot of a hotend showing cold side, heat break, and block",
                "motion": "zones highlight in sequence",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hotend cutaway", "zone labels", "filament path"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a hotend cutaway diagram with cold side, heat break, and heat block zones on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The heat break",
                "teaching_point": "Thermal bottleneck keeps filament stiff",
                "shot": "macro shot of a bare heat break with the thermal gradient",
                "motion": "heat gradient glows down the break",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["heat break", "thermal gradient"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a bare hotend heat break with a glowing thermal gradient, bright task light, dark bench",
            },
            {
                "goal": "PTFE vs all-metal",
                "teaching_point": "The liner sets the temperature ceiling",
                "shot": "side-by-side shots of a PTFE-lined and an all-metal hotend",
                "motion": "cross-cut between the two with a temp scale",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["PTFE hotend", "all-metal hotend", "temperature scale"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a PTFE-lined hotend and an all-metal hotend side by side with a temperature scale, even diffused lighting, dark studio",
            },
            {
                "goal": "Heat creep",
                "teaching_point": "All-metal jams if cooling fails",
                "shot": "macro shot of filament jamming in a heat break zone",
                "motion": "soft filament collapses and jams",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["hotend", "jammed filament", "cooling fan"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of filament jamming inside a hotend heat break zone with a cooling fan, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match hotend to materials and speed",
                "shot": "wide hero shot of two printers running with their hotends labelled",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["two printers", "hotend labels", "spools"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of two 3D printers with their hotend types labelled, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hotend split open with its three zones labelled",
            "subject": "disassembled hotend with zone labels",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "hotend center, zone labels radiating",
            "text": "INSIDE THE HOTEND",
            "elements": ["hotend parts", "heat break", "zone labels", "filament"],
            "style": "industrial macro photography",
            "mood": "technical, exploded, clear",
            "prompt": "macro photograph of a disassembled hotend with cold side, heat break, and block labels, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Hotends Explained: 3 Zones",
            "title_variations": [
                "PTFE-Lined vs All-Metal Hotends",
                "What's Inside a Hotend",
                "Hotend Upgrade Guide",
                "Why All-Metal Hotends Jam",
                "Choosing a Hotend",
            ],
            "description": "A hotend is three zones: the cold side that keeps filament stiff, the heat break that creates a sharp thermal gradient, and the heat block that melts plastic. PTFE-lined hotends are simple and smooth but limited to about 240 C, because the liner degrades above that. All-metal hotends let filament ride metal walls for 280 C and beyond, unlocking nylon, polycarbonate, and high speed - but they jam from heat creep if the heat break is not cooled properly. This short cuts open the hotend, compares liner types with real temperature ceilings, and gives a simple rule for choosing by the materials you print.",
            "hashtags": ["#Hotend", "#3Dprinting", "#Hardware", "#Upgrade"],
            "seo_keywords": [
                "hotend types explained",
                "all metal hotend",
                "ptfe lined hotend",
                "hotend heat break",
                "heat creep fix",
                "high flow hotend",
                "hotend upgrade",
            ],
        },
        "fact_check": [
            "PTFE (Teflon) liners begin to degrade near 240 C, releasing fumes and narrowing the bore.",
            "All-metal hotends support 280 C and above, required for nylon and polycarbonate.",
            "The heat break creates a steep thermal gradient separating the melt zone from the filament path.",
            "Heat creep happens when heat travels up the heat break, softening filament before the melt zone and jamming it.",
            "High-flow hotends increase heating path and melt volume to support faster volumetric extrusion.",
        ],
    },
    # ======================================================================
    {
        "topic": "Sanding PLA & ABS",
        "core_question": "What is the right way to sand a 3D print smooth?",
        "learning_objective": "The viewer can run a graded sanding routine from rough grit to polish and avoid melting or smearing the plastic.",
        "engineering_summary": "Sanding removes layer steps and surface defects by abrasion. Start coarse and step finer: remove layer lines at 120-180 grit, blend at 240-320, smooth at 400-600, and polish at 800-1500 or wet-sand for a gloss finish. Wet sanding keeps grit loaded, flushes particles, and reduces heat that softens PLA, preventing smearing and clogged paper. ABS sands similarly but softer; PLA can melt-smear under pressure, so lighter passes and water help. Sanding direction alternates (cross-hatching) to reveal remaining defects. For paint prep, 320-400 is typically the finish grit before primer; for bare gloss, go past 1000 and buff.",
        "real_world_application": "Cosplay props, enclosures, and functional parts get sanded to remove print lines before paint; engineering prototypes are sanded to a controlled surface finish for fitting tests.",
        "common_misconceptions": [
            "Start with fine grit (coarse grit is needed first to remove layer steps efficiently)",
            "Dry sanding is always faster (heat melts PLA and loads the paper)",
            "One grit can do the whole job (skipping grits leaves deep scratches that fine paper cannot remove)",
        ],
        "teaching_strategy": "Show the grit ladder as a sequence of passes on one part, then the wet-sanding trick and the paint-prep stopping point.",
        "script": "Layer lines come off in steps, not in one pass. Start coarse at one-twenty grit to flatten the ridges, then climb: two-forty, four-hundred, six-hundred, and beyond. Each grit only removes the scratches from the one before. Go wet: water keeps the paper from loading and stops friction heat from melting the plastic. Pass light, cross the direction, inspect what's left. For paint, stop at four-hundred grit and let primer do the rest. For gloss, chase the scratches to a thousand plus, then buff. Sand in steps, and prints go from ribbed to smooth.",
        "text_overlay": [
            "120 -> 240 -> 400 -> 600+",
            "WET SAND: NO MELT",
            "CROSS THE DIRECTION",
            "PAINT: STOP AT 400",
        ],
        "scenes": [
            {
                "goal": "Hook: the ribbed print",
                "teaching_point": "Layer steps are the enemy",
                "shot": "macro close-up of unsanded layer lines under raking light",
                "motion": "light sweeps across the ridges",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["unsanded print", "layer lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a 3D print with visible layer lines under raking side light, dark bench",
            },
            {
                "goal": "The grit ladder",
                "teaching_point": "Each grit removes the last one's scratches",
                "shot": "tabletop shot of sandpaper sheets from coarse to fine",
                "motion": "camera slides across the grits",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["sandpaper sheets", "grit numbers", "sanding block"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of sandpaper sheets from coarse to fine grit with a sanding block, even diffused lighting, dark studio",
            },
            {
                "goal": "Wet sanding",
                "teaching_point": "Water prevents melt and loading",
                "shot": "close-up of wet sanding a part with water droplets",
                "motion": "gentle back and forth strokes",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["sandpaper", "wet part", "water droplets"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of wet sanding a 3D printed part with water droplets on the paper, bright task lighting, workbench",
            },
            {
                "goal": "Crossing directions",
                "teaching_point": "Alternate direction to see the defects",
                "shot": "medium shot of hands sanding in crossing strokes",
                "motion": "strokes cross at right angles",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["part", "sandpaper", "sanding strokes"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part being sanded with crossing strokes in a workshop, neutral lab lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Stop grit where the finish needs it",
                "shot": "wide hero shot of a smooth, glossy sanded part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["glossy sanded part", "sandpaper sheets"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a smooth glossy sanded 3D print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part half-sanded: ribs on one side, gloss on the other",
            "subject": "half-sanded print with sandpaper sheets",
            "background": "dark workshop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "rough half left, glossy half right",
            "text": "SAND IN STEPS",
            "elements": ["half-sanded part", "sandpaper", "grit ladder"],
            "style": "industrial macro photography",
            "mood": "smooth, procedural, satisfying",
            "prompt": "macro photograph of a 3D print half sanded, rough layer lines on one side and glossy on the other, sandpaper sheets beside, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Sand Prints Smooth: Grit Order",
            "title_variations": [
                "How to Sand 3D Prints",
                "Wet Sanding PLA Explained",
                "Grit Guide for Prints",
                "Smooth Prints Before Paint",
                "Sanding ABS Without Melting",
            ],
            "description": "Layer lines come off in steps, not one pass. Start coarse at 120 grit to flatten the ridges, then climb through 240, 400, 600, and beyond - each grit only removes the scratches from the one before it. Wet sanding keeps the paper from loading and stops friction heat from melting PLA, which smears instead of smoothing. Cross your sanding direction each pass so remaining defects are visible. For paint prep, stop at 400 grit and let primer fill the rest; for a bare gloss finish, chase the scratches past 1000 and buff. This short covers the full grit ladder for PLA and ABS.",
            "hashtags": ["#Sanding", "#3Dprinting", "#Finishing", "#DIY"],
            "seo_keywords": [
                "how to sand 3d prints",
                "sand PLA smooth",
                "wet sanding 3d print",
                "sandpaper grit for 3d printing",
                "sanding ABS",
                "remove layer lines",
                "paint prep 3d print",
            ],
        },
        "fact_check": [
            "Layer-line removal starts around 120-180 grit; skipping grits leaves scratches too deep for finer paper to clear.",
            "Wet sanding cools the surface and flushes abrasive dust, preventing PLA melt-smearing and paper loading.",
            "Cross-hatching strokes reveal remaining defects by alternating scratch direction.",
            "Paint preparation typically finishes at 320-400 grit before primer.",
            "Gloss finishes require grits past 1000 followed by buffing or polishing compound.",
        ],
    },
    # ======================================================================
    {
        "topic": "Painting 3D Prints",
        "core_question": "How do I get a clean paint job on a 3D print?",
        "learning_objective": "The viewer can run the paint pipeline: sand, prime, paint in thin coats, and protect the result.",
        "engineering_summary": "Paint jobs fail on preparation: layer lines and pores show through any topcoat. The pipeline is sand (320-400 for paint prep), primer (filler primer fills micro-porosity), paint in thin even coats, and a clear protective coat. Spray paint in light coats from 15-25 cm, letting each flash off before the next, because thick coats run and hide details. PLA and PETG need no chemical prep beyond degreasing (warm water and dish soap); ABS benefits from acetone-based primer misting for adhesion. Lacquers and polyurethane clear coats protect the paint from handling. Detail painting and masking produce crisp lines; decals or water-slide transfers go under the clear coat.",
        "real_world_application": "Props, cosplay, and product prototypes get production-looking finishes: sanded, primed, painted, and clear-coated, matching injection-molded appearance at a fraction of tooling cost.",
        "common_misconceptions": [
            "Paint hides print lines (it follows the surface and amplifies defects)",
            "One thick coat is efficient (thick coats run and obscure details)",
            "Primer is optional (it bonds the paint and fills micro-porosity)",
        ],
        "teaching_strategy": "Show the before/after of a skipped prep step, then the coat discipline with a spray-can technique, ending with the clear coat.",
        "script": "Paint follows the surface, so print lines must go first. Sand to four-hundred grit, degrease with soapy water, then prime - filler primer hides the micro-pores that make paint look cheap. Now the rule: thin coats. Spray from a hand away, and let each coat flash before the next. Thin coats don't run, don't hide details, and dry fast. Two or three coats of color, then a clear coat to lock it all in. Skip the prep and the paint job shows every line. Do the steps in order, and a twenty-dollar print looks like a production part.",
        "text_overlay": [
            "SAND -> PRIME -> PAINT -> CLEAR",
            "THIN COATS ONLY",
            "15-25CM, SWEEP FAST",
            "PREP IS THE PAINT JOB",
        ],
        "scenes": [
            {
                "goal": "Hook: the cheap look",
                "teaching_point": "Paint follows every layer line",
                "shot": "macro close-up of an un-prepped print showing lines through paint",
                "motion": "slow push-in on the visible lines",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["badly painted print", "visible layer lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a badly painted 3D print with layer lines showing through the paint, raking side light, dark bench",
            },
            {
                "goal": "Prep",
                "teaching_point": "Sand, degrease, prime",
                "shot": "tabletop shot of the prep kit: sandpaper, soapy water, filler primer",
                "motion": "items arranged and used in sequence",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["sandpaper", "soapy water", "filler primer", "part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a paint prep kit with sandpaper, soapy water, and filler primer on a workbench, bright task lighting",
            },
            {
                "goal": "The thin coat rule",
                "teaching_point": "Light passes, flash time between",
                "shot": "medium shot of spray painting a part from a hand away",
                "motion": "sweeping spray passes",
                "lighting": "neutral lab light",
                "background": "spray booth",
                "objects": ["spray can", "part on stand", "booth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of spray painting a 3D print with sweeping light passes in a spray booth, neutral lab lighting",
            },
            {
                "goal": "Protection",
                "teaching_point": "Clear coat locks the finish",
                "shot": "medium shot of clear coating a finished painted part",
                "motion": "glossy clear layer goes on",
                "lighting": "bright task light",
                "background": "spray booth",
                "objects": ["clear coat", "painted part", "glossy finish"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of applying a clear coat to a painted 3D print in a spray booth, bright task lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Steps in order, production look",
                "shot": "wide hero shot of a finished glossy painted part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark studio",
                "objects": ["finished painted part", "glossy surface"],
                "transition": "fade",
                "duration": 6,
                "prompt": "studio photograph of a finished glossy painted 3D print on a dark studio background, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Half the part raw, half painted glossy",
            "subject": "part with raw and painted halves",
            "background": "dark studio blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "raw half left, painted half right",
            "text": "PAINT IT RIGHT",
            "elements": ["raw print half", "painted half", "spray can"],
            "style": "studio product photography",
            "mood": "clean, transformable, polished",
            "prompt": "studio photograph of a 3D print with a raw half and a glossy painted half, spray can beside, hard key light with rim, dark studio, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Paint Prints Like a Pro",
            "title_variations": [
                "How to Paint 3D Prints",
                "The Painting Pipeline Explained",
                "Why Your Paint Shows Lines",
                "Spray Painting PLA",
                "Filler Primer for Prints",
            ],
            "description": "Paint follows the surface, so print lines must be removed before color goes on. The pipeline is simple: sand to 400 grit, degrease with soapy water, prime with filler primer to hide micro-porosity, then paint in thin even coats from 15-25 centimeters, letting each coat flash before the next. Thick coats run and hide details; thin coats dry fast and look clean. Two or three color coats, then a clear coat locks the finish and protects it from handling. This short walks the full painting pipeline for PLA and PETG and explains why preparation is the entire paint job.",
            "hashtags": ["#Painting", "#3Dprinting", "#Finishing", "#Props"],
            "seo_keywords": [
                "how to paint 3d prints",
                "paint PLA parts",
                "filler primer 3d printing",
                "spray painting 3d print",
                "smooth paint job prints",
                "clear coat 3d print",
                "paint prep for 3d prints",
            ],
        },
        "fact_check": [
            "Paint layers are thin and follow the substrate surface, so layer lines remain visible without sanding.",
            "Filler primer fills micro-porosity and improves topcoat adhesion and uniformity.",
            "Thin coats from 15-25 cm avoid runs and preserve fine details; flash time between coats prevents solvent entrapment.",
            "Warm water and dish soap degrease PLA and PETG without damaging them.",
            "A clear coat protects the color layer from handling and weathering.",
        ],
    },
    # ======================================================================
    {
        "topic": "SLA vs FDM",
        "core_question": "SLA or FDM - which printer technology should I pick?",
        "learning_objective": "The viewer can compare FDM and SLA on resolution, strength, materials, workflow, and cost, and choose by part purpose.",
        "engineering_summary": "FDM (fused deposition modeling) extrudes molten filament in layers: strong, tough, and cheap, with wide engineering material options, but visible layer steps and anisotropic strength. SLA (stereolithography) cures liquid resin layer by layer with UV light: smooth, detailed surfaces with high feature resolution, ideal for miniatures, jewelry, and precise fit parts - but resins are brittle, need washing and curing, and the workflow is messier and costlier per part. Build orientation, support strategy, and post-processing differ completely. For functional load-bearing parts choose FDM; for detail, surface finish, or casting patterns choose SLA.",
        "real_world_application": "Product teams print functional brackets on FDM and fit-check masters on SLA; jewelry and dental labs are SLA-only because of resolution, while drone frames are FDM-only for toughness.",
        "common_misconceptions": [
            "SLA is just higher quality (it wins on detail but loses on toughness and material range)",
            "Resin parts are stronger than filament (standard resins are brittle; engineering resins are costly)",
            "FDM can match SLA detail (layer steps and nozzle size set a hard floor on FDM detail)",
        ],
        "teaching_strategy": "Show the same test part on both machines, compare failure modes and surfaces, then a decision matrix by use case.",
        "script": "Two technologies, two personalities. FDM melts filament and lays it down in beads - tough parts, cheap material, tons of options, but visible layer steps and weak across the layers. SLA cures liquid resin with light - surfaces like glass, details that FDM can only dream of, but the resin is brittle, and every print needs washing and curing. So ask what the part does. Load-bearing and rough use? FDM. Miniatures, jewelry, or casting masters? SLA. Detail costs workflow: buckets of goop, gloves, and cleanup. Choose by the part, not the hype.",
        "text_overlay": [
            "FDM: TOUGH + CHEAP",
            "SLA: DETAIL + SMOOTH",
            "SLA: WASH + CURE + BRITTLE",
            "LOAD? FDM. DETAIL? SLA",
        ],
        "scenes": [
            {
                "goal": "Hook: the same part, two ways",
                "teaching_point": "Technology shapes the part",
                "shot": "side-by-side shots of an FDM and an SLA printed test part",
                "motion": "cross-cut between surfaces",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["FDM part", "SLA part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an FDM printed part beside an SLA printed part on a dark studio table, even diffused lighting",
            },
            {
                "goal": "FDM strengths",
                "teaching_point": "Tough, cheap, engineering materials",
                "shot": "medium shot of an FDM part being flexed and abused",
                "motion": "part flexes and springs back",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["FDM part", "flexing test"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a flexed FDM 3D printed part springing back on a test bench, neutral lab lighting",
            },
            {
                "goal": "SLA strengths",
                "teaching_point": "Smooth surfaces, fine details",
                "shot": "macro close-up of a miniature with crisp detail",
                "motion": "slow push-in on the fine features",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["SLA miniature", "fine detail", "smooth surface"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of an SLA printed miniature with crisp fine details, raking side light, dark bench",
            },
            {
                "goal": "The workflow cost",
                "teaching_point": "Wash, cure, mess",
                "shot": "tabletop shot of the SLA workflow: gloves, wash station, cure station",
                "motion": "gloved hands move the part through the stations",
                "lighting": "bright task light",
                "background": "workshop",
                "objects": ["gloves", "wash station", "cure station", "resin bottles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of the SLA workflow with gloves, wash station, and cure station on a workshop bench, bright task lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick by part purpose",
                "shot": "wide hero shot of a functional FDM bracket and a detailed SLA miniature side by side",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["FDM bracket", "SLA miniature", "labels"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a functional FDM bracket and a detailed SLA miniature side by side with labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Layer lines versus glass-smooth, side by side",
            "subject": "FDM part with layer lines and SLA part with smooth surface",
            "background": "dark studio blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "FDM left, SLA right, VS between",
            "text": "SLA vs FDM",
            "elements": ["FDM part", "SLA part", "VS graphic"],
            "style": "studio product photography",
            "mood": "comparative, clean, decisive",
            "prompt": "macro photograph of an FDM part with visible layer lines on the left and a smooth SLA part on the right with a VS graphic, hard key light with rim, dark studio, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "SLA or FDM? Pick Right",
            "title_variations": [
                "SLA vs FDM: Which Printer",
                "Resin vs Filament Printing",
                "FDM or SLA for My Parts",
                "Resolution vs Toughness",
                "Choosing a 3D Printer Technology",
            ],
            "description": "FDM extrudes molten filament in beads: tough parts, cheap materials, and a wide range of engineering plastics, but visible layer steps and weaker bonds between layers. SLA cures liquid resin with UV light: glass-smooth surfaces and fine details for miniatures, jewelry, and precision fits, but standard resins are brittle and every print needs washing and curing. Load-bearing parts want FDM; detail, surface finish, and casting patterns want SLA. This short compares both technologies on strength, resolution, materials, workflow, and cost, and gives a decision rule based on what the part actually does.",
            "hashtags": ["#SLA", "#FDM", "#3Dprinting", "#Resin"],
            "seo_keywords": [
                "SLA vs FDM",
                "resin or filament printer",
                "which 3d printer technology",
                "SLA printing explained",
                "FDM printing explained",
                "resin vs filament strength",
                "best 3d printer for detail",
            ],
        },
        "fact_check": [
            "FDM parts are anisotropic, with interlayer strength typically 30-50% lower than in-layer strength.",
            "SLA achieves higher feature resolution and surface finish than FDM at equivalent cost tiers.",
            "Standard photopolymer resins are more brittle than common FDM thermoplastics like ABS and nylon.",
            "SLA workflow requires washing in solvent and UV curing, plus resin handling precautions.",
            "Engineering resins (tough, high-temp, castable) exist but cost several times standard resin.",
        ],
    },
    # ======================================================================
    {
        "topic": "Infill Density vs Strength",
        "core_question": "Does more infill actually make parts stronger?",
        "learning_objective": "The viewer can judge when infill density matters, when walls matter more, and how infill interacts with print time and weight.",
        "engineering_summary": "Infill density contributes strength mainly in compression and internal support, but for bending and tension, walls (perimeters) dominate: a single outer wall carries more bending load than most light infill patterns. Going from 20% to 100% infill roughly doubles bending strength at best while multiplying material use and time; adding two walls achieves similar gains at a fraction of the cost. Infill pattern also matters: gyroid gives isotropic behavior and good energy absorption, cubic aligns with some loads, and grid is fast but anisotropic. For stiffness, thicker walls and a strong pattern at 20-40% usually beat dense infill. Infill is the skeleton, walls are the armor.",
        "real_world_application": "Structural brackets and drone parts are designed with 3-4 walls and 20-30% gyroid infill; solid parts are only used where internal strength or fluid sealing matters.",
        "common_misconceptions": [
            "100% infill is the strongest always (slightly stronger than walls-plus-light-infill but far costlier)",
            "Infill percentage is the main strength setting (walls carry most bending loads)",
            "All infill patterns are equal (pattern directionality and energy absorption differ strongly)",
        ],
        "teaching_strategy": "Show a bending test comparing dense infill versus more walls, then the wall-carrying diagram and a cost comparison.",
        "script": "More infill equals stronger, right? No. For bending and pulling, the walls do the heavy lifting - a couple of perimeters beat a heavy core. Test it: twenty percent infill with four walls beats eighty percent with two, and prints faster. Infill matters when the load pushes into the part: compression and impact. Pattern changes behavior too - gyroid absorbs energy in every direction; grid is quick but weak along one axis. The rule: armor the outside with walls, skeleton the inside at twenty to forty percent. Dense infill is for sealing or crushing loads, not default strength.",
        "text_overlay": [
            "WALLS = ARMOR",
            "INFILL = SKELETON",
            "20% + 4 WALLS > 80% + 2 WALLS",
            "GYROID FOR EVERY-DIRECTION",
        ],
        "scenes": [
            {
                "goal": "Hook: the strength myth",
                "teaching_point": "Dense infill is not free strength",
                "shot": "medium shot of a bending test on two parts: dense infill and thin walls",
                "motion": "both bend, walls version holds longer",
                "lighting": "even diffused light",
                "background": "test bench",
                "objects": ["two test parts", "vise", "weights"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bending test on two 3D printed parts clamped in a vise, even diffused lighting, test bench",
            },
            {
                "goal": "Walls carry bending",
                "teaching_point": "Perimeters are the outer armor",
                "shot": "graphic-style shot of a cross-section with force arrows on the walls",
                "motion": "load arrows land on the outer rings",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cross-section diagram", "wall rings", "load arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a part cross-section diagram with bending load arrows on the outer wall rings, dark screen, clean engineering visualization",
            },
            {
                "goal": "When infill matters",
                "teaching_point": "Compression and impact load the core",
                "shot": "macro shot of a crush test on an infilled part",
                "motion": "part compresses under a press",
                "lighting": "bright task light",
                "background": "test bench",
                "objects": ["crush press", "infilled part", "dial gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a crush test compressing a 3D printed part under a press with a dial gauge, bright task light, test bench",
            },
            {
                "goal": "Pattern choice",
                "teaching_point": "Gyroid absorbs, grid is directional",
                "shot": "tabletop shot of infill pattern samples side by side",
                "motion": "camera slides across the patterns",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["gyroid sample", "grid sample", "cubic sample"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of gyroid, grid, and cubic infill pattern samples side by side on a dark studio table, even diffused lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Armor the walls, skeleton the core",
                "shot": "wide hero shot of a cut part showing walls and gyroid infill",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["cut part", "walls", "gyroid infill"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a cut 3D print showing thick walls and gyroid infill, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cutaway part showing thin armor walls and a light skeleton core",
            "subject": "cut print cross-section with walls and infill",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "cross-section center, wall labels radiating",
            "text": "WALLS > INFILL",
            "elements": ["cut print", "wall rings", "infill pattern", "labels"],
            "style": "industrial macro photography",
            "mood": "structural, engineered, clear",
            "prompt": "macro photograph of a cut 3D print cross-section showing outer walls and infill with labels, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Infill: The Strength Truth",
            "title_variations": [
                "Does Infill Density Matter?",
                "Walls vs Infill Strength",
                "What Infill Percentage to Use",
                "Gyroid vs Grid Strength",
                "Stronger Prints, Less Plastic",
            ],
            "description": "More infill is not automatically stronger. For bending and tension, the walls do the heavy lifting: twenty percent infill with four walls beats eighty percent with two walls and prints faster. Infill matters for compression and impact, where the load pushes into the core, and the pattern changes behavior too - gyroid absorbs energy in every direction while grid is fast but weak along one axis. The practical rule is armor the outside with walls and skeleton the inside at twenty to forty percent, reserving dense infill for sealing or crushing loads. This short explains the mechanics with tests you can run on your own printer.",
            "hashtags": ["#Infill", "#3Dprinting", "#Strength", "#Design"],
            "seo_keywords": [
                "infill density vs strength",
                "does infill affect strength",
                "best infill percentage",
                "walls vs infill",
                "gyroid infill strength",
                "strong 3d print settings",
                "infill pattern comparison",
            ],
        },
        "fact_check": [
            "Perimeters carry most bending and tension loads; infill contributes compression and internal support.",
            "Dense infill roughly doubles bending strength at best while multiplying print time and material.",
            "Gyroid infill is near-isotropic and absorbs energy well across directions.",
            "Grid infill is fast to print but anisotropic, with weaker lines across its structure.",
            "The practical strong-part recipe is 3-4 walls with 20-40% infill for most structural applications.",
        ],
    },
    # ======================================================================
    {
        "topic": "Bridging Design",
        "core_question": "How far can a print bridge, and how do I design bridges that work?",
        "learning_objective": "The viewer can explain how bridges form, set bridge-friendly slicer settings, and design spans that print cleanly.",
        "engineering_summary": "A bridge is a horizontal span printed between two supports without anything underneath: the nozzle draws the plastic in a straight line and it sags only by its own weight. PLA can bridge 10-20 mm cleanly; longer spans sag. The slicer's bridge settings cut speed and increase cooling during the span, letting the plastic freeze in tension. Design rules: keep spans under 15 mm where possible, add small radiused ends so lines anchor, break long spans into shorter sections, and orient the span so bridges run parallel to the shorter axis. Sagging is the failure mode: each drooping line hangs from the previous one.",
        "real_world_application": "Enclosures with cable windows, phone stands, and gantry parts rely on clean bridges to avoid supports; print farms tune bridge speed and fan per material for cosmetic top surfaces.",
        "common_misconceptions": [
            "Bridges are impossible without supports (short spans print cleanly with fan and speed tuned)",
            "Bridge strength equals solid material (bridges are tension-drawn and weaker than supported floors)",
            "All bridges sag equally (span length, cooling, and speed decide the sag)",
        ],
        "teaching_strategy": "Show a bridge test print with increasing spans, the fan-and-speed mechanism, then the design rules with a before/after model.",
        "script": "A bridge is a layer drawn across thin air: no support, just plastic and tension. The trick is cooling. Slow the speed, hit it with the fan, and the plastic freezes before it sags. PLA handles ten to twenty millimeters cleanly; past that, gravity wins. Design fixes: short spans, split gaps, bridges along the short axis. Radius the ends so each line has an anchor. Sag is not a slicer bug - it's a span that overstayed its welcome. Design short, cool hard, bridge clean.",
        "text_overlay": [
            "SLOW + COOL = TENSION",
            "PLA BRIDGES 10-20MM",
            "SPLIT LONG SPANS",
            "RADIUS THE ANCHORS",
        ],
        "scenes": [
            {
                "goal": "Hook: the bridge test",
                "teaching_point": "Spans sag past their limit",
                "shot": "wide shot of a bridge test print with sagging long spans",
                "motion": "slow pan across the spans",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["bridge test print", "sagging spans"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bridge test 3D print with long sagging spans, raking side light, dark bench",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Cooling freezes the drawn line",
                "shot": "macro shot of a nozzle drawing a bridge line with fan airflow",
                "motion": "line drawn straight while the fan blows",
                "lighting": "bright task light",
                "background": "printer in lab",
                "objects": ["nozzle", "bridge line", "cooling fan"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a nozzle drawing a bridge line with strong cooling fan airflow, bright task lighting, print lab",
            },
            {
                "goal": "The limit",
                "teaching_point": "PLA bridges 10-20 mm cleanly",
                "shot": "tablet-style graphic showing span lengths and sag",
                "motion": "sag curve animates as span grows",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["span diagram", "sag curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bridge span diagram with a sag curve on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Design fixes",
                "teaching_point": "Short spans, split gaps, anchor radii",
                "shot": "CAD-style shot of a model with split spans and radiused anchors",
                "motion": "model edits appear one by one",
                "lighting": "neutral lab light",
                "background": "CAD workstation",
                "objects": ["CAD model", "bridge edits", "radius highlights"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a CAD model showing bridge design edits with split spans and radiused anchors, neutral lab lighting, CAD workstation",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design short, cool hard",
                "shot": "wide hero shot of a clean bridged part on the build plate",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean bridged part", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean bridged 3D print with flat unsupported spans on the build plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A bridge line held in tension between two pillars",
            "subject": "printed bridge span between two pillars",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "pillars left and right, clean span between",
            "text": "BRIDGE IT CLEAN",
            "elements": ["printed bridge", "pillars", "clean span"],
            "style": "industrial macro photography",
            "mood": "tension, geometry, clean",
            "prompt": "macro photograph of a clean 3D printed bridge span between two pillars, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bridges: How Far Can You Go?",
            "title_variations": [
                "How to Design Print Bridges",
                "Bridge Without Supports",
                "Why Bridges Sag",
                "Bridge Settings Explained",
                "Printing Overhangs and Gaps",
            ],
            "description": "A bridge is a layer drawn across empty space, held in tension until it cools. The slicer's bridge settings cut speed and raise fan power so the plastic freezes before gravity wins. PLA bridges 10-20 millimeters cleanly; longer spans sag. Good design works around the limit: keep spans short, split long gaps into sections, run bridges along the part's short axis, and add small radiused ends so each line has an anchor. Sagging is not a printer bug - it is a span that exceeded the material's limit. This short shows bridge tests, the cooling mechanism, and design rules for flat, clean unsupported floors.",
            "hashtags": ["#Bridging", "#3Dprinting", "#Design", "#Overhang"],
            "seo_keywords": [
                "3d printing bridges",
                "bridge settings",
                "how far can a print bridge",
                "bridge sag fix",
                "design bridges 3d print",
                "print without supports",
                "bridge overhang quality",
            ],
        },
        "fact_check": [
            "PLA can bridge roughly 10-20 mm cleanly with tuned speed and cooling.",
            "Bridge lines are drawn in tension between anchors; each line sags from the previous one if it does not cool.",
            "Bridge settings reduce speed and increase fan power specifically during bridge moves.",
            "Radiused ends provide anchor points that reduce line detachment at the span edges.",
            "Long spans can be broken into shorter sections with small intervening supports in the design.",
        ],
    },
    # ======================================================================
    {
        "topic": "Belts & Pulleys",
        "core_question": "How do belts and pulleys transmit power, and how do ratios change speed and torque?",
        "learning_objective": "The viewer can explain belt friction and pitch, compute pulley ratios, and pick a belt drive for a job.",
        "engineering_summary": "A belt transmits power from a driving pulley to a driven pulley through friction (flat and V-belts) or positive tooth engagement (timing belts). Friction belts slip under load and handle misalignment poorly; timing belts - like the GT2 belts on 3D printers - transmit exact position without slip because teeth mesh with pulley grooves. The ratio is driven teeth over driving teeth: halving the driving teeth doubles speed and halves torque. Belt tension creates the preload that keeps teeth engaged and prevents skipping; too little tension skips steps, too much wears bearings and motors. Pulley diameter scales both ratio and resolution: a 20-tooth pulley on a printer moves a set distance per motor step.",
        "real_world_application": "3D printers use GT2 timing belts for precise motion; garage doors and engines use V-belts for high-load friction drive; printers' reduction stages trade speed for torque with toothed pulley ratios.",
        "common_misconceptions": [
            "Belts slip like ropes (timing belts mesh teeth and never slip)",
            "Bigger pulleys are always better (pulley size sets ratio, resolution, and load on the motor)",
            "Tighter belts are better (over-tension wears bearings and motors and can cause skipping from binding)",
        ],
        "teaching_strategy": "Show a slip demonstration with a friction belt versus a timing belt, then the ratio math with a gear-pair visual, ending with tension rules.",
        "script": "Belts move power, but not all belts behave the same. Friction belts grab by squeeze - overload them and they slip. Timing belts have teeth: they mesh with the pulley and never slip, which is exactly why printers use them. Position is now a ratio game. Small driver, big driven pulley: speed down, torque up. Big driver, small driven: speed up, torque down. And tension matters: too loose and teeth skip; too tight and you cook the bearings. GT2 timing belts on your printer are precision instruments, not rubber bands. Tune the tension, respect the ratio.",
        "text_overlay": [
            "FRICTION BELTS SLIP",
            "TIMING BELTS MESH",
            "SMALL->BIG: MORE TORQUE",
            "TENSION = PRECISION",
        ],
        "scenes": [
            {
                "goal": "Hook: the slip test",
                "teaching_point": "Friction belts slip, timing belts don't",
                "shot": "tabletop shot of a friction belt slipping under load",
                "motion": "belt squeals and slips on the pulley",
                "lighting": "bright task light",
                "background": "test bench",
                "objects": ["friction belt", "pulley", "load"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a friction belt slipping under load on a pulley, bright task light, test bench",
            },
            {
                "goal": "The mesh",
                "teaching_point": "Teeth lock the belt to the pulley",
                "shot": "macro close-up of a GT2 timing belt meshing with a pulley",
                "motion": "teeth engage one by one",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["GT2 belt", "timing pulley", "teeth"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a GT2 timing belt meshing with a toothed pulley, raking side light, dark bench",
            },
            {
                "goal": "The ratio",
                "teaching_point": "Tooth count sets speed and torque",
                "shot": "graphic-style shot of two pulley pairs with ratio arrows",
                "motion": "ratio arrows animate between the pairs",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pulley pair diagram", "ratio arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a pulley ratio diagram with speed and torque arrows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Tension",
                "teaching_point": "Too loose skips, too tight cooks",
                "shot": "medium shot of hands checking belt tension with a deflection test",
                "motion": "belt pressed and released",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer gantry", "belt", "hands"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a belt tension check with a deflection test on a printer gantry, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Belts are precision instruments",
                "shot": "wide hero shot of a printer's belt system in close detail",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "belt system", "pulleys"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printer belt drive system in close detail, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A toothed belt wrapping a pulley with a ratio arrow",
            "subject": "GT2 timing belt and pulley close-up",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "pulley center, belt wrapping, arrow accent",
            "text": "BELT DRIVES 101",
            "elements": ["timing belt", "pulley", "ratio arrow"],
            "style": "industrial macro photography",
            "mood": "mechanical, precise, engaging",
            "prompt": "macro photograph of a GT2 timing belt wrapping a toothed pulley with a ratio arrow, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Belts & Pulleys Explained",
            "title_variations": [
                "How Timing Belts Work",
                "Belt Drive Ratios",
                "Friction vs Timing Belts",
                "Belt Tension on Printers",
                "Pulleys and Gear Ratios",
            ],
            "description": "Belts transmit power from a driving to a driven pulley. Friction belts - flat and V-belts - grab by squeeze and slip under overload, while timing belts like the GT2 belts in 3D printers mesh teeth with pulley grooves and never slip, making them exact positioning drives. The ratio is driven teeth over driving teeth: a smaller driver boosts speed and cuts torque, a larger one does the reverse. Tension is the hidden variable: too loose and teeth skip, too tight and bearings and motors overheat. This short explains belt types, ratio math, and the tension rules that keep printer motion precise.",
            "hashtags": ["#Belts", "#Pulleys", "#Mechanical", "#3Dprinting"],
            "seo_keywords": [
                "how belts and pulleys work",
                "timing belt explained",
                "GT2 belt printer",
                "belt drive ratio",
                "pulley ratio torque",
                "belt tension 3d printer",
                "friction belt vs timing belt",
            ],
        },
        "fact_check": [
            "Timing belts use toothed engagement and transmit position without slip.",
            "Friction belts (flat, V) rely on tension and friction and slip under overload.",
            "Ratio equals driven tooth count over driving tooth count; torque and speed scale inversely.",
            "Insufficient timing-belt tension causes skipped teeth; excess tension overloads bearings and motors.",
            "GT2 belts and pulleys are the standard motion elements on Cartesian and CoreXY printers.",
        ],
    },
]
