"""Batch 33: first layer flow, support interface, spiral contours, per-object settings, print order, acceleration and jerk, flow rate, overlap and width."""

CURATED = [
    # ======================================================================
    {
        "topic": "First Layer Flow",
        "core_question": "Why does the bottom of your print look different from the walls?",
        "learning_objective": "The viewer understands first-layer flow and when to change it.",
        "engineering_summary": "The first layer does a different job than the rest: it must squish onto the bed and stick, so the slicer prints it thicker and slower than the walls. First-layer flow is a separate extrusion multiplier for that squish, and its value trades two failures: too little flow and the lines stay round, weak, and unglued; too much and the base bulges and elephants its foot. The rest of the print is tuned by normal flow; the first layer gets its own number, because its job is adhesion, not geometry.",
        "real_world_application": "A higher first-layer flow buys adhesion on tricky beds and filaments.",
        "common_misconceptions": [
            "One flow number tunes everything (the first layer is a separate job)",
            "More first-layer flow is always better (it bulges the base)",
            "It replaces leveling (flow can help, but height is the base)",
        ],
        "teaching_strategy": "Print pads at three first-layer flows and read the squish.",
        "script": "The first layer does a different job than the rest: it must squish onto the bed and stick, so the slicer prints it thicker and slower than the walls. First-layer flow is a separate extrusion multiplier for that squish, and its value trades two failures: too little flow and the lines stay round, weak, and unglued; too much and the base bulges and elephants its foot. The rest of the print is tuned by normal flow; the first layer gets its own number, because its job is adhesion, not geometry.",
        "text_overlay": [
            "SQUISH, STICK, HOLD",
            "THICKER, SLOWER, SEPARATE FLOW",
            "TOO LITTLE: ROUND, UNGLUED",
            "TOO MUCH: BULGED BASE",
        ],
        "scenes": [
            {
                "goal": "Hook: the peeled pad",
                "teaching_point": "Adhesion starts at flow",
                "shot": "close-up shot of a first layer peeling from the bed",
                "motion": "pad edge lifts away",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["peeling pad", "bed", "lift edge"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a first layer peeling from the bed, bright task lighting, print lab",
            },
            {
                "goal": "The job",
                "teaching_point": "Thicker and slower",
                "shot": "diagram-style shot of the first layer profile",
                "motion": "bottom line sits wide and low",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["thick first line", "squish profile", "bed line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of first layer squish profile, clean engineering visualization on a dark background",
            },
            {
                "goal": "Too little",
                "teaching_point": "Round, weak, unglued",
                "shot": "close-up shot of round separated first-layer lines",
                "motion": "lines sit high and loose",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["round lines", "loose pad", "bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of round weak first-layer lines on the bed, bright task lighting, print lab",
            },
            {
                "goal": "Too much",
                "teaching_point": "Bulge and foot",
                "shot": "close-up shot of a bulged first layer",
                "motion": "base flares outward",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["bulged base", "flare", "first layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bulged first layer on the bed, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Its own number",
                "shot": "wide hero shot of a perfectly stuck print base",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["stuck print", "clean base", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a perfectly stuck print base, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A squished first layer with round and bulged extremes side by side",
            "subject": "first layer flow",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "squish profile center, pads beside",
            "text": "ADHESION, NOT GEOMETRY",
            "elements": ["squish profile", "round lines", "bulged base"],
            "style": "geometry studio photography",
            "mood": "squished, stuck, tuned",
            "prompt": "photograph of a squished first layer on the bed with round and bulged extremes beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "First Layer Flow: Adhesion, Not Geometry",
            "title_variations": [
                "How Much First Layer Flow",
                "First Layer Flow Setting",
                "Initial Layer Flow Guide",
                "First Layer Squish Flow",
                "Bottom Layer Flow",
            ],
            "description": "The first layer does a different job than the rest: it must squish onto the bed and stick, so the slicer prints it thicker and slower than the walls. First-layer flow is a separate extrusion multiplier for that squish: too little leaves round, weak, unglued lines, and too much bulges the base and elephants its foot. The rest of the print is tuned by normal flow. This short squishes three pads and shows why the first layer gets its own number.",
            "hashtags": ["#FirstLayer", "#Flow", "#Adhesion", "#3DPrinting"],
            "seo_keywords": [
                "how much first layer flow",
                "first layer flow setting",
                "initial layer flow",
                "first layer squish",
                "bottom layer flow",
                "first layer adhesion flow",
                "first layer extrusion multiplier",
            ],
        },
        "fact_check": [
            "The first layer sticks the part.",
            "It prints thicker and slower.",
            "Too little flow leaves round lines.",
            "Too much flow bulges the base.",
            "It is a separate multiplier.",
        ],
    },
    {
        "topic": "Support Interface Density",
        "core_question": "How do you make supports easy to peel off?",
        "learning_objective": "The viewer understands the support interface.",
        "engineering_summary": "The support interface is the layer sandwich between the support and the part: a dense, low layer that supports the overhang without fusing to it. The interface density is the knob: dense interface gives a clean part bottom but sticks hard, sparse interface peels easy but leaves droopy sagging. The slicer prints the interface as a separate zone, often with its own pattern and a gap, so the part lands on a pillow instead of a bed of spikes. Strength of support is about structure; ease of removal is about the interface.",
        "real_world_application": "Support-heavy prints are judged by the interface, not the towers.",
        "common_misconceptions": [
            "Density is support strength (it is the interface texture)",
            "More density is always cleaner (it fuses harder)",
            "Removal is a post-process problem (the interface decides it)",
        ],
        "teaching_strategy": "Peel supports with sparse and dense interfaces and compare the bottoms.",
        "script": "The support interface is the layer sandwich between the support and the part: a dense, low layer that supports the overhang without fusing to it. The interface density is the knob: dense interface gives a clean part bottom but sticks hard, sparse interface peels easy but leaves droopy sagging. The slicer prints the interface as a separate zone, often with its own pattern and a gap, so the part lands on a pillow instead of a bed of spikes. Strength of support is about structure; ease of removal is about the interface.",
        "text_overlay": [
            "THE SANDWICH LAYER",
            "DENSE: CLEAN, STICKS HARD",
            "SPARSE: EASY, SAGGY",
            "REMOVAL LIVES IN THE INTERFACE",
        ],
        "scenes": [
            {
                "goal": "Hook: the ripped bottom",
                "teaching_point": "Support fused to part",
                "shot": "close-up shot of a part bottom torn by supports",
                "motion": "camera pans the torn face",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["torn bottom", "support scar", "part face"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part bottom torn by supports, bright task lighting, print lab",
            },
            {
                "goal": "The sandwich",
                "teaching_point": "Interface between them",
                "shot": "diagram-style shot of the support interface layers",
                "motion": "part, interface, support stack apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["part layer", "interface layer", "support layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of support interface layers, clean engineering visualization on a dark background",
            },
            {
                "goal": "The dense",
                "teaching_point": "Clean bottom, hard peel",
                "shot": "diagram-style shot of dense interface grid",
                "motion": "tight grid holds the overhang",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["dense grid", "clean bottom", "hard peel"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dense support interface, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sparse",
                "teaching_point": "Easy peel, droopy bottom",
                "shot": "diagram-style shot of sparse interface grid",
                "motion": "loose grid lets the sag show",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sparse grid", "sag marks", "easy peel"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of sparse support interface, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pillow, not spikes",
                "shot": "wide hero shot of a clean part beside its peeled supports",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean bottom", "peeled supports", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean part beside its peeled supports, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A support sandwich with dense and sparse interface grids",
            "subject": "support interface density",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "sandwich center, grids beside",
            "text": "REMOVAL LIVES IN THE INTERFACE",
            "elements": ["interface layer", "dense grid", "sparse grid"],
            "style": "geometry studio photography",
            "mood": "sandwiched, peeled, clean",
            "prompt": "photograph of a support interface sandwich with dense and sparse grids and a peeled part bottom, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Support Interface Density: Removal Lives in the Interface",
            "title_variations": [
                "What Is Support Interface Density",
                "Support Interface Setting",
                "Support Surface Density",
                "Easy Support Removal",
                "Interface Layers Support",
            ],
            "description": "The support interface is the layer sandwich between the support and the part: a dense, low layer that supports the overhang without fusing to it. Dense interface gives a clean part bottom but sticks hard; sparse interface peels easy but leaves sagging. The slicer prints the interface as a separate zone with its own pattern and gap, so the part lands on a pillow instead of a bed of spikes. This short stacks the sandwich and shows where removal is really decided.",
            "hashtags": ["#SupportInterface", "#Supports", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "what is support interface density",
                "support interface setting",
                "support surface density",
                "easy support removal",
                "interface layers support",
                "support bottom clean",
                "support density vs interface",
            ],
        },
        "fact_check": [
            "The interface sits between part and support.",
            "Dense interface gives clean bottoms.",
            "Dense interface sticks harder.",
            "Sparse interface sags more.",
            "Removal depends on the interface.",
        ],
    },
    {
        "topic": "Spiral vs Normal Contours",
        "core_question": "Why is a vase printed in one continuous line?",
        "learning_objective": "The viewer understands spiral contour mode.",
        "engineering_summary": "Normal contours finish each layer and jump up: the head finishes a ring, travels, and starts the next one, leaving a tiny z-seam where the rings meet. Spiral mode removes the jump: the nozzle climbs continuously as it circles, so the whole part is one spiral line with no layer seams at all. The cost is a single wall and no top surface, which is why spiral is for vases, not boxes. Spiral is contour printing that never stops, and seamless shells are its gift and its limit.",
        "real_world_application": "Vases, lampshades, and smooth shells use spiral contour mode.",
        "common_misconceptions": [
            "Spiral is faster for everything (it is one wall and open top)",
            "Spiral removes all lines (it removes seams, lines remain)",
            "Any part can go spiral (flat tops break it)",
        ],
        "teaching_strategy": "Show the seam on normal rings, then the continuous climb of spiral.",
        "script": "Normal contours finish each layer and jump up: the head finishes a ring, travels, and starts the next one, leaving a tiny z-seam where the rings meet. Spiral mode removes the jump: the nozzle climbs continuously as it circles, so the whole part is one spiral line with no layer seams at all. The cost is a single wall and no top surface, which is why spiral is for vases, not boxes. Spiral is contour printing that never stops, and seamless shells are its gift and its limit.",
        "text_overlay": [
            "NORMAL: FINISH, JUMP, SEAM",
            "SPIRAL: CLIMB WHILE CIRCLING",
            "NO SEAMS, SINGLE WALL",
            "VASES, NOT BOXES",
        ],
        "scenes": [
            {
                "goal": "Hook: the seam line",
                "teaching_point": "Rings meet, seam shows",
                "shot": "close-up shot of a z-seam on a printed vase",
                "motion": "camera pans the seam line",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["z-seam", "vase wall", "seam line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a z-seam on a printed vase, bright task lighting, print lab",
            },
            {
                "goal": "The jump",
                "teaching_point": "Finish, travel, start",
                "shot": "diagram-style shot of normal layer jumps",
                "motion": "rings close then jump upward",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["closed rings", "jump path", "seam dots"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of normal contour layer jumps, clean engineering visualization on a dark background",
            },
            {
                "goal": "The climb",
                "teaching_point": "One continuous spiral",
                "shot": "diagram-style shot of the spiral path",
                "motion": "nozzle climbs while circling",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["spiral path", "climbing nozzle", "seamless line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of spiral contour printing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cost",
                "teaching_point": "One wall, no top",
                "shot": "diagram-style shot of a vase cutaway",
                "motion": "single wall and open top show",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["single wall", "open top", "cutaway"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a spiral vase cutaway, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Seamless shells",
                "shot": "wide hero shot of a smooth spiral vase",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth vase", "spiral shell", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth spiral vase, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A vase climbing in one spiral line with a seam-marked ring beside",
            "subject": "spiral contour mode",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spiral vase center, seam ring beside",
            "text": "CLIMB WHILE CIRCLING",
            "elements": ["spiral path", "vase", "seam ring"],
            "style": "geometry studio photography",
            "mood": "climbing, seamless, spiral",
            "prompt": "photograph of a vase climbing in one spiral line with a seam-marked ring beside it, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Spiral vs Normal Contours: Climb While Circling",
            "title_variations": [
                "Spiral Contour Printing Explained",
                "Vase Mode Contours",
                "Spiral vs Normal Slicer",
                "Z Seam Free Vase",
                "Spiral Contour Mode",
            ],
            "description": "Normal contours finish each layer and jump up, leaving a tiny z-seam where the rings meet. Spiral mode removes the jump: the nozzle climbs continuously as it circles, so the whole part is one spiral line with no layer seams. The cost is a single wall and no top surface, which is why spiral is for vases, not boxes. This short marks the seam, climbs the spiral, and shows that seamless shells are its gift and its limit.",
            "hashtags": ["#SpiralMode", "#VaseMode", "#ZSeam", "#Slicer"],
            "seo_keywords": [
                "spiral contour printing",
                "vase mode contours",
                "spiral vs normal slicer",
                "z seam free vase",
                "spiral contour mode",
                "continuous spiral print",
                "seamless shell print",
            ],
        },
        "fact_check": [
            "Normal contours jump between rings.",
            "The jump leaves a seam.",
            "Spiral climbs while circling.",
            "It has no layer seams.",
            "Spiral is single-wall only.",
        ],
    },
    {
        "topic": "Per-Object Settings",
        "core_question": "What if two parts on one plate needed different settings?",
        "learning_objective": "The viewer understands per-object slicer settings.",
        "engineering_summary": "One plate often holds very different parts: a tiny pin and a big bracket, a draft part and a fine part. Per-object settings let each model carry its own slicer values, so the pin prints slow and fine while the bracket prints fast and thick, all in one job. The slicer applies the override at the model level, overriding the global profile per object. One plate, many recipes, one job. Per-object settings are the difference between compromise and control.",
        "real_world_application": "Mixed plates of prototypes and production parts run per-object profiles.",
        "common_misconceptions": [
            "All parts share one profile (each object can override it)",
            "Per-object is per-layer (it is per-model)",
            "It is complex to set (it is a right-click override)",
        ],
        "teaching_strategy": "Show two parts on one plate with different settings applying.",
        "script": "One plate often holds very different parts: a tiny pin and a big bracket, a draft part and a fine part. Per-object settings let each model carry its own slicer values, so the pin prints slow and fine while the bracket prints fast and thick, all in one job. The slicer applies the override at the model level, overriding the global profile per object. One plate, many recipes, one job. Per-object settings are the difference between compromise and control.",
        "text_overlay": [
            "MIXED PARTS, ONE PLATE",
            "EACH MODEL CARRIES ITS RECIPE",
            "PIN FINE, BRACKET FAST",
            "COMPROMISE OR CONTROL",
        ],
        "scenes": [
            {
                "goal": "Hook: the mixed plate",
                "teaching_point": "Different parts, one job",
                "shot": "wide shot of a plate with a tiny pin and a big bracket",
                "motion": "camera pans both parts",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["tiny pin", "big bracket", "plate"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a plate with a tiny pin and a big bracket, neutral lab lighting, print lab",
            },
            {
                "goal": "The compromise",
                "teaching_point": "One global profile",
                "shot": "diagram-style shot of one profile over two parts",
                "motion": "single profile card covers both",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["global profile", "pin icon", "bracket icon"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a global profile covering two parts, clean engineering visualization on a dark background",
            },
            {
                "goal": "The override",
                "teaching_point": "Per-model recipes",
                "shot": "diagram-style shot of per-object profile cards",
                "motion": "two cards split by model",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pin profile", "bracket profile", "split cards"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of per-object profile cards, clean engineering visualization on a dark background",
            },
            {
                "goal": "The plate",
                "teaching_point": "One job, two speeds",
                "shot": "medium shot of a plate printing with mixed speeds",
                "motion": "pin prints slow, bracket prints fast",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["slow pin", "fast bracket", "mixed plate"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a plate printing with mixed part speeds, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Control, not compromise",
                "shot": "wide hero shot of both finished parts on the plate",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished pin", "finished bracket", "plate"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished pin and bracket on the plate, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two parts on one plate with separate profile cards",
            "subject": "per-object settings",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pin and bracket flanking cards",
            "text": "ONE PLATE, MANY RECIPES",
            "elements": ["tiny pin", "big bracket", "profile cards"],
            "style": "geometry studio photography",
            "mood": "split, overridden, controlled",
            "prompt": "photograph of a tiny pin and a big bracket on one plate with separate profile cards, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Per-Object Settings: One Plate, Many Recipes",
            "title_variations": [
                "How to Use Per-Object Settings",
                "Per Object Slicer Settings",
                "Per Model Settings",
                "Multiple Objects Different Settings",
                "Per Object Profiles",
            ],
            "description": "One plate often holds very different parts: a tiny pin and a big bracket, a draft part and a fine part. Per-object settings let each model carry its own slicer values, so the pin prints slow and fine while the bracket prints fast and thick, all in one job. The slicer applies the override at the model level. This short loads a mixed plate, splits the recipes, and shows the difference between compromise and control.",
            "hashtags": ["#PerObject", "#Slicer", "#Profiles", "#3DPrinting"],
            "seo_keywords": [
                "how to use per-object settings",
                "per object slicer settings",
                "per model settings",
                "multiple objects different settings",
                "per object profiles",
                "mixed plate print",
                "per model override",
            ],
        },
        "fact_check": [
            "One plate can hold mixed parts.",
            "Per-object settings override the global.",
            "Each model carries its own recipe.",
            "It applies at the model level.",
            "It turns compromise into control.",
        ],
    },
    {
        "topic": "Print Order & Adhesion",
        "core_question": "Which part should the printer finish first?",
        "learning_objective": "The viewer understands print order on multi-part plates.",
        "engineering_summary": "On a plate of several parts, the slicer picks an order, and that order shapes the print. The classic choices are one-at-a-time and layer-by-layer: one-at-a-time finishes each part fully and can stop early if one fails, but the tall head can knock into other parts; layer-by-layer is safer for tall plates but mixes every part's fate. Adhesion matters too: long skinny parts and big flat parts warm the bed differently. The order is a safety decision, and the slicer's default is not always the safest one.",
        "real_world_application": "Batch plates balance print height against collision risk.",
        "common_misconceptions": [
            "Order is cosmetic (it affects collisions and failures)",
            "One-at-a-time is always better (it risks head collisions)",
            "All parts on a plate fail together (order decides isolation)",
        ],
        "teaching_strategy": "Show the two orders on the same plate and the failure outcomes.",
        "script": "On a plate of several parts, the slicer picks an order, and that order shapes the print. The classic choices are one-at-a-time and layer-by-layer: one-at-a-time finishes each part fully and can stop early if one fails, but the tall head can knock into other parts; layer-by-layer is safer for tall plates but mixes every part's fate. Adhesion matters too: long skinny parts and big flat parts warm the bed differently. The order is a safety decision, and the slicer's default is not always the safest one.",
        "text_overlay": [
            "ONE AT A TIME OR LAYER BY LAYER",
            "FINISH EARLY, OR SHARE FATE",
            "TALL HEAD, COLLISION RISK",
            "ORDER IS A SAFETY DECISION",
        ],
        "scenes": [
            {
                "goal": "Hook: the knocked part",
                "teaching_point": "Order can collide",
                "shot": "wide shot of a tall head passing a shorter part",
                "motion": "head swings close to the neighbor",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["tall head", "shorter part", "collision zone"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a tall print head passing a shorter part, neutral lab lighting, print lab",
            },
            {
                "goal": "One at a time",
                "teaching_point": "Finish each part fully",
                "shot": "diagram-style shot of one-at-a-time sequence",
                "motion": "parts finish one by one",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["finished part", "printing part", "waiting part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of one-at-a-time print order, clean engineering visualization on a dark background",
            },
            {
                "goal": "Layer by layer",
                "teaching_point": "All parts rise together",
                "shot": "diagram-style shot of layer-by-layer sequence",
                "motion": "all parts climb level by level",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["rising parts", "shared layers", "level line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of layer-by-layer print order, clean engineering visualization on a dark background",
            },
            {
                "goal": "The trade",
                "teaching_point": "Isolation versus safety",
                "shot": "graphic-style shot of the order trade-off",
                "motion": "isolation and collision bars balance",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["isolation bar", "collision bar", "balance line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of print order trade-offs, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pick the safe order",
                "shot": "wide hero shot of a clean multi-part plate finishing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["multi-part plate", "finished parts", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean multi-part plate finishing, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two sequence diagrams: parts finishing one by one versus together",
            "subject": "print order adhesion",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two sequences side by side",
            "text": "ORDER IS A SAFETY DECISION",
            "elements": ["one-at-a-time", "layer-by-layer", "collision zone"],
            "style": "geometry studio photography",
            "mood": "ordered, isolated, safe",
            "prompt": "photograph of print order sequences showing one-at-a-time and layer-by-layer with a tall head collision zone, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Print Order & Adhesion: A Safety Decision",
            "title_variations": [
                "Which Part Prints First",
                "Print Order Multi Part",
                "One at a Time vs Layer by Layer",
                "Sequence Printing",
                "Batch Plate Print Order",
            ],
            "description": "On a plate of several parts, the slicer picks an order, and that order shapes the print. One-at-a-time finishes each part fully and can stop early if one fails, but the tall head can knock into other parts; layer-by-layer is safer for tall plates but mixes every part's fate. Adhesion matters too, because big and skinny parts warm the bed differently. This short runs both orders on the same plate and shows why the slicer's default is not always the safest one.",
            "hashtags": ["#PrintOrder", "#BatchPrint", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "which part prints first",
                "print order multi part",
                "one at a time vs layer by layer",
                "sequence printing",
                "batch plate print order",
                "collision risk print",
                "adhesion between parts",
            ],
        },
        "fact_check": [
            "The slicer chooses the order.",
            "One-at-a-time isolates failures.",
            "One-at-a-time risks collisions.",
            "Layer-by-layer shares all fates.",
            "Order is a safety decision.",
        ],
    },
    {
        "topic": "Acceleration & Jerk Settings",
        "core_question": "Why is print speed not the whole story?",
        "learning_objective": "The viewer understands acceleration and jerk.",
        "engineering_summary": "The speed number is a limit, not the pace: the head must ramp up and down, and how fast it ramps decides how much of the print actually runs at speed. Acceleration is the ramp rate, and jerk is the instant speed change at corners. Low acceleration is smooth but slow on small parts; high acceleration is fast but shakes the frame and ghosts the walls. The slicer can cap both, and the caps matter more than the speed for small, twisty prints. Speed is the limit; acceleration is the reality.",
        "real_world_application": "Small detailed prints are acceleration-limited, not speed-limited.",
        "common_misconceptions": [
            "Speed is the main setting (short moves never reach it)",
            "High acceleration is always fast (it rings the frame)",
            "Jerk is a spoiler setting (it is the corner snap)",
        ],
        "teaching_strategy": "Show the speed profile of a small print under different accelerations.",
        "script": "The speed number is a limit, not the pace: the head must ramp up and down, and how fast it ramps decides how much of the print actually runs at speed. Acceleration is the ramp rate, and jerk is the instant speed change at corners. Low acceleration is smooth but slow on small parts; high acceleration is fast but shakes the frame and ghosts the walls. The slicer can cap both, and the caps matter more than the speed for small, twisty prints. Speed is the limit; acceleration is the reality.",
        "text_overlay": [
            "SPEED IS A LIMIT, NOT THE PACE",
            "ACCELERATION IS THE RAMP",
            "JERK IS THE CORNER SNAP",
            "CAPS BEAT SPEED ON SMALL PARTS",
        ],
        "scenes": [
            {
                "goal": "Hook: the never-fast print",
                "teaching_point": "Short moves, no speed",
                "shot": "close-up shot of a small detailed print printing",
                "motion": "head moves in short bursts",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["small print", "short moves", "nozzle"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a small detailed print with short nozzle moves, bright task lighting, print lab",
            },
            {
                "goal": "The ramp",
                "teaching_point": "Acceleration shapes the pace",
                "shot": "diagram-style shot of speed ramps",
                "motion": "speed rises and falls like a ramp",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["speed ramp", "accel slope", "target speed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of acceleration speed ramps, clean engineering visualization on a dark background",
            },
            {
                "goal": "The snap",
                "teaching_point": "Jerk at the corner",
                "shot": "diagram-style shot of the corner snap",
                "motion": "head turns with an instant change",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["corner turn", "jerk step", "path corner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of jerk at a corner, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shake",
                "teaching_point": "Fast ramps ring the frame",
                "shot": "medium shot of a frame shaking at high acceleration",
                "motion": "frame vibrates, wall ghosts",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["shaking frame", "ghost wall", "vibration"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printer frame shaking at high acceleration, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Acceleration is reality",
                "shot": "wide hero shot of a clean twisty print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["twisty print", "clean walls", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean twisty detailed print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A speed ramp with a corner snap and a shaking frame",
            "subject": "acceleration jerk settings",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "ramp center, frame behind",
            "text": "SPEED IS A LIMIT, NOT THE PACE",
            "elements": ["speed ramp", "corner snap", "printer frame"],
            "style": "geometry studio photography",
            "mood": "ramped, snapped, capped",
            "prompt": "photograph of a speed ramp with a corner snap and a printer frame behind, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Acceleration & Jerk Settings: Speed Is a Limit, Not the Pace",
            "title_variations": [
                "How Do Acceleration and Jerk Affect Prints",
                "Acceleration Jerk Settings",
                "Jerk Setting Explained",
                "Print Speed vs Acceleration",
                "Motion Quality Slicer",
            ],
            "description": "The speed number is a limit, not the pace: the head must ramp up and down, and how fast it ramps decides how much of the print actually runs at speed. Acceleration is the ramp rate and jerk is the instant speed change at corners. Low acceleration is smooth but slow; high acceleration shakes the frame and ghosts the walls. This short ramps a small print, snaps a corner, and shows why the caps matter more than speed for twisty parts.",
            "hashtags": ["#Acceleration", "#Jerk", "#Motion", "#3DPrinting"],
            "seo_keywords": [
                "how do acceleration and jerk affect prints",
                "acceleration jerk settings",
                "jerk setting explained",
                "print speed vs acceleration",
                "motion quality slicer",
                "acceleration ramp rate",
                "corner snap jerk",
            ],
        },
        "fact_check": [
            "Speed is only a limit.",
            "Acceleration is the ramp rate.",
            "Jerk is the corner snap.",
            "Low accel is smooth but slow.",
            "High accel shakes the frame.",
        ],
    },
    {
        "topic": "Flow Rate Calibration",
        "core_question": "Why does your first cube never come out exactly right?",
        "learning_objective": "The viewer understands flow rate calibration methods.",
        "engineering_summary": "The printer extrudes what it thinks is the right volume, but real filament, gears, and nozzles shift the truth, and the result is walls that are slightly too thick or too thin. Flow rate calibration measures that error and fixes it: print a test cube or a wall, measure with calipers, then divide expected by actual to get the multiplier. The test is quick, the math is one line, and the fix lives in one number. It is the first calibration after mechanics, because every other quality test sits on top of correct volume.",
        "real_world_application": "E-steps set the machine's truth; flow rate matches the slicer to it.",
        "common_misconceptions": [
            "E-steps and flow are the same (E-steps are mechanical, flow is slicing)",
            "One calibration is forever (filament rolls change it)",
            "The slicer default is right (it is a generic starting point)",
        ],
        "teaching_strategy": "Print a cube, measure the wall, and compute the multiplier.",
        "script": "The printer extrudes what it thinks is the right volume, but real filament, gears, and nozzles shift the truth, and the result is walls that are slightly too thick or too thin. Flow rate calibration measures that error and fixes it: print a test cube or a wall, measure with calipers, then divide expected by actual to get the multiplier. The test is quick, the math is one line, and the fix lives in one number. It is the first calibration after mechanics, because every other quality test sits on top of correct volume.",
        "text_overlay": [
            "REALITY SHIFTS THE VOLUME",
            "CUBE, CALIPER, DIVIDE",
            "EXPECTED OVER ACTUAL",
            "FIRST CALIBRATION AFTER MECHANICS",
        ],
        "scenes": [
            {
                "goal": "Hook: the off cube",
                "teaching_point": "Walls off by a hair",
                "shot": "close-up shot of a printed cube beside a caliper",
                "motion": "caliper shows the mismatch",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["printed cube", "caliper", "wall reading"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printed cube beside a caliper, bright task light, workbench",
            },
            {
                "goal": "The shift",
                "teaching_point": "Filament and gears drift",
                "shot": "diagram-style shot of volume error sources",
                "motion": "diameter and grip errors stack",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["diameter error", "grip error", "volume gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flow volume error sources, clean engineering visualization on a dark background",
            },
            {
                "goal": "The measure",
                "teaching_point": "Caliper on the walls",
                "shot": "close-up shot of measuring wall thickness with calipers",
                "motion": "jaws close on the wall",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper jaws", "wall thickness", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of measuring wall thickness with calipers, bright task light, workbench",
            },
            {
                "goal": "The math",
                "teaching_point": "Expected divided by actual",
                "shot": "diagram-style shot of the multiplier formula",
                "motion": "expected over actual equals flow",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["expected value", "actual value", "flow result"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the flow multiplier formula, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Volume first, then quality",
                "shot": "wide hero shot of a calibrated cube row",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["calibrated cubes", "caliper", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a row of calibrated cubes, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cube with a caliper and the expected-over-actual formula",
            "subject": "flow rate calibration",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cube center, formula above",
            "text": "EXPECTED OVER ACTUAL",
            "elements": ["test cube", "caliper", "multiplier formula"],
            "style": "geometry studio photography",
            "mood": "measured, divided, fixed",
            "prompt": "photograph of a test cube with a caliper and the expected over actual formula, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Flow Rate Calibration: Expected Over Actual",
            "title_variations": [
                "How to Calibrate Flow Rate",
                "Flow Rate Calibration Method",
                "Extrusion Multiplier Test",
                "Over Extrusion Fix",
                "Flow Test Cube Guide",
            ],
            "description": "The printer extrudes what it thinks is the right volume, but real filament, gears, and nozzles shift the truth, so walls come out slightly too thick or too thin. Flow rate calibration measures that error and fixes it: print a test cube or wall, measure with calipers, then divide expected by actual to get the multiplier. It is the first calibration after mechanics, because every other quality test sits on top of correct volume. This short cubes it, measures it, and does the one-line math.",
            "hashtags": ["#FlowRate", "#Calibration", "#Caliper", "#3DPrinting"],
            "seo_keywords": [
                "how to calibrate flow rate",
                "flow rate calibration",
                "extrusion multiplier test",
                "over extrusion fix",
                "flow test cube",
                "flow vs e-steps",
                "expected over actual flow",
            ],
        },
        "fact_check": [
            "Real volume shifts from ideal.",
            "Filament and gears cause it.",
            "Caliper measures the error.",
            "Expected over actual is the fix.",
            "Flow comes before quality tests.",
        ],
    },
    {
        "topic": "Overlap & Extrusion Width",
        "core_question": "How do wall and infill lines bond together?",
        "learning_objective": "The viewer understands extrusion width and overlap.",
        "engineering_summary": "A printed line is wider than the nozzle hole, because the nozzle squishes the plastic sideways, and that extrusion width is the unit the slicer uses for wall thickness, infill, and spacing. Overlap is how much the wall lines and infill lines intrude into each other so they fuse into one solid mass: too little overlap and the layers stay as separate lines with cold seams; too much and the surface bulges with squeezed plastic. Width sets the geometry; overlap sets the bond.",
        "real_world_application": "Wall-to-infill bonding is the quiet strength of every printed part.",
        "common_misconceptions": [
            "Wall width equals nozzle size (it is wider than the hole)",
            "Overlap is a strength hack (it is standard fusion practice)",
            "The slicer width is exact (it changes with flow and layer height)",
        ],
        "teaching_strategy": "Show the line being wider than the nozzle, then the overlap fusing walls.",
        "script": "A printed line is wider than the nozzle hole, because the nozzle squishes the plastic sideways, and that extrusion width is the unit the slicer uses for wall thickness, infill, and spacing. Overlap is how much the wall lines and infill lines intrude into each other so they fuse into one solid mass: too little overlap and the layers stay as separate lines with cold seams; too much and the surface bulges with squeezed plastic. Width sets the geometry; overlap sets the bond.",
        "text_overlay": [
            "LINE WIDER THAN THE HOLE",
            "WIDTH IS THE SLICER'S UNIT",
            "OVERLAP FUSES THE LINES",
            "WIDTH SETS GEOMETRY, OVERLAP SETS BOND",
        ],
        "scenes": [
            {
                "goal": "Hook: the cold seam",
                "teaching_point": "Lines that never fused",
                "shot": "close-up shot of a wall showing line separation",
                "motion": "light catches the seam gaps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["line separation", "seam gaps", "wall"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of wall lines separating on a print, bright task lighting, print lab",
            },
            {
                "goal": "The squeeze",
                "teaching_point": "Line wider than nozzle",
                "shot": "diagram-style shot of the nozzle squeezing a wide line",
                "motion": "plastic flattens beyond the hole",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle hole", "wide line", "squish arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of extrusion width squish, clean engineering visualization on a dark background",
            },
            {
                "goal": "The unit",
                "teaching_point": "Width rules the geometry",
                "shot": "diagram-style shot of width units in walls and infill",
                "motion": "width tiles the wall and grid",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wall width", "infill spacing", "unit tiles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of extrusion width as a unit, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bond",
                "teaching_point": "Overlap fuses the mass",
                "shot": "diagram-style shot of wall and infill overlapping",
                "motion": "lines merge into one solid",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wall line", "infill line", "overlap zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of wall and infill overlap, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Bond, then geometry",
                "shot": "wide hero shot of a solid cross-sectioned part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["cut part", "fused walls", "solid core"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a cross-sectioned solid part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle squeezing a wide line with an overlap zone fusing walls",
            "subject": "extrusion width overlap",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "nozzle center, overlap zone beside",
            "text": "WIDTH SETS GEOMETRY, OVERLAP SETS BOND",
            "elements": ["nozzle", "wide line", "overlap zone"],
            "style": "geometry studio photography",
            "mood": "squeezed, fused, solid",
            "prompt": "photograph of a nozzle squeezing a wide line with an overlap zone fusing the walls, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Overlap & Extrusion Width: Width Sets Geometry, Overlap Sets Bond",
            "title_variations": [
                "What Is Extrusion Width Overlap",
                "Line Width Slicer Setting",
                "Wall Overlap Explained",
                "Extrusion Width Guide",
                "Infill Wall Bonding",
            ],
            "description": "A printed line is wider than the nozzle hole, because the nozzle squishes the plastic sideways, and that extrusion width is the unit the slicer uses for wall thickness, infill, and spacing. Overlap is how much the wall and infill lines intrude into each other so they fuse: too little leaves cold seams, too much bulges the surface. This short squeezes the line, tiles the geometry, and shows how width sets the geometry while overlap sets the bond.",
            "hashtags": ["#ExtrusionWidth", "#Overlap", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "what is extrusion width overlap",
                "line width slicer setting",
                "wall overlap explained",
                "extrusion width guide",
                "infill wall bonding",
                "line wider than nozzle",
                "overlap cold seam",
            ],
        },
        "fact_check": [
            "Lines print wider than the nozzle.",
            "Extrusion width is the slicer unit.",
            "Overlap fuses wall and infill.",
            "Too little overlap leaves seams.",
            "Too much overlap bulges surfaces.",
        ],
    },
]