"""Batch 7: clogs, motion failures, firmware, mechanisms, fluids, chemical finishing, and resin."""

CURATED = [
    # ======================================================================
    {
        "topic": "Clogged Nozzle",
        "core_question": "Why does my nozzle clog, and how do I clear it?",
        "learning_objective": "The viewer can diagnose the three clog types - debris, charred polymer, and heat creep - and clear a nozzle safely.",
        "engineering_summary": "Nozzle clogs come in three flavors. Debris clogs: dust, burnt particles, or material contamination jams the bore; they respond to cold pulls and needle cleaning. Charred clogs: polymer decomposes in the hotend and hardens into carbon deposits, common with high temperatures, long dwell times, and poor retraction hygiene; they respond to cleaning filament, hot flushes, and nozzle replacement. Heat-creep clogs: heat travels up the heat break, softening filament early so it binds against the cold side; they respond to better heat-break cooling and lower hotend temperature. Prevention beats curing: filter or wipe filament, keep temperatures in the material window, and maintain a clean heat break.",
        "real_world_application": "Print farms schedule hotend servicing because a silent partial clog is the most common cause of mysterious under-extrusion and mid-print failures in production.",
        "common_misconceptions": [
            "Clogs are always dirty nozzles (heat creep is equally common and needs cooling, not cleaning)",
            "More temperature clears clogs (extra heat can char polymer and harden the clog)",
            "Needles fix everything (needles can dislodge debris but spread charred residue)",
        ],
        "teaching_strategy": "Show the three clog mechanisms as a diagnostic tree, then the cold-pull and cleaning routines in sequence.",
        "script": "Nozzle clogged? Diagnose first. Debris: dust and burnt bits jam the bore - fix with a cold pull or a needle. Char: polymer cooks into carbon at high temps - clean with cleaning filament or hot flushes. Heat creep: the heat break runs hot, filament softens early and binds - that's a cooling problem, not a dirt problem. Prevention beats cures: wipe the filament, respect the temperature window, service the hotend. A partial clog is the sneakiest cause of under-extrusion, because the print still runs, just weak. Know the three types, fix the right one.",
        "text_overlay": [
            "1. DEBRIS: COLD PULL",
            "2. CHAR: HOT FLUSH",
            "3. HEAT CREEP: COOL IT",
            "PREVENT > CURE",
        ],
        "scenes": [
            {
                "goal": "Hook: the silent failure",
                "teaching_point": "Partial clogs under-extrude quietly",
                "shot": "macro close-up of a weak, gappy print still running",
                "motion": "slow push-in on the gaps",
                "lighting": "raking side light",
                "background": "dark print bay",
                "objects": ["weak print", "gaps", "printer running"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a weak 3D print with gaps forming while printing, raking side light, dark print bay",
            },
            {
                "goal": "Debris clogs",
                "teaching_point": "Dust and particles jam the bore",
                "shot": "macro shot of the nozzle bore with trapped debris",
                "motion": "needle pokes debris loose",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["nozzle", "debris", "cleaning needle"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a nozzle bore with trapped debris and a cleaning needle, bright task light, dark bench",
            },
            {
                "goal": "Char clogs",
                "teaching_point": "Cooked polymer hardens into carbon",
                "shot": "macro shot of black charred residue in a nozzle",
                "motion": "slow push-in on the carbon",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["charred nozzle", "carbon residue", "cleaning filament"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a nozzle with charred black residue and cleaning filament, warm task light, dark bench",
            },
            {
                "goal": "Heat creep",
                "teaching_point": "Softened filament binds in the cold side",
                "shot": "graphic-style shot of filament softening up the heat break",
                "motion": "heat gradient rises and filament swells",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hotend diagram", "heat gradient", "filament bind"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hotend diagram with heat creeping up the heat break and filament binding, dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Diagnose the type, then fix",
                "shot": "wide hero shot of a clean, strong print fresh off the printer",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean print", "serviced hotend"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean strong 3D print with a serviced hotend behind it, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A nozzle with three labelled clog causes around it",
            "subject": "disassembled nozzle with diagnostic labels",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "nozzle center, three cause labels around",
            "text": "CLOGGED?",
            "elements": ["nozzle", "debris", "char", "heat labels"],
            "style": "diagnostic macro photography",
            "mood": "technical, troubleshooting, clear",
            "prompt": "macro photograph of a disassembled nozzle with debris, char, and heat labels around it, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Nozzle Clogs: 3 Causes, 3 Fixes",
            "title_variations": [
                "Why Your Nozzle Clogs",
                "How to Unclog a Hotend",
                "Cold Pull Explained",
                "Heat Creep vs Debris Clogs",
                "Fix Under-Extrusion Clogs",
            ],
            "description": "Nozzle clogs come in three types. Debris clogs from dust and particles respond to cold pulls and needles. Char clogs happen when polymer cooks into carbon at high temperatures and respond to cleaning filament and hot flushes. Heat-creep clogs mean heat travels up the heat break, softening filament early - a cooling problem, not a dirt problem. Prevention beats curing: wipe filament, respect the temperature window, service the hotend regularly. A partial clog is the sneakiest cause of under-extrusion because the print still runs, just weak. This short builds a diagnostic tree for all three clog types.",
            "hashtags": ["#CloggedNozzle", "#3Dprinting", "#Troubleshooting", "#Hotend"],
            "seo_keywords": [
                "clogged nozzle fix",
                "why does my nozzle clog",
                "cold pull 3d printer",
                "heat creep clog",
                "unclog hotend",
                "nozzle cleaning filament",
                "under-extrusion clog",
            ],
        },
        "fact_check": [
            "Debris clogs respond to cold pulls, which form a plug around trapped particles.",
            "Polymer charring occurs during long high-temperature dwells, hardening carbon into the bore.",
            "Heat creep is a thermal problem: heat conducts up the heat break and softens filament before the melt zone.",
            "Prevention measures include filament filtration, correct temperature windows, and regular hotend servicing.",
            "A partial clog produces consistent under-extrusion without stopping the print, mimicking flow-calibration errors.",
        ],
    },
    # ======================================================================
    {
        "topic": "Layer Shifting",
        "core_question": "Why do my layers shift sideways, and how do I fix it?",
        "learning_objective": "The viewer can distinguish skipped steps from loose belts and mechanical binds, and fix each cause.",
        "engineering_summary": "Layer shift is a sudden lateral offset in the print, usually caused by the motion system losing steps or skipping. Causes: (1) acceleration and speed demand more torque than the steppers deliver, so the motor stalls and the position reference is lost; (2) loose or worn belts let the carriage slip on the pulley; (3) mechanical binds - tight bearings, a warped gantry, or a print colliding with the nozzle - stop the axis dead. The fix order: check belt tension and grub screws, reduce acceleration or print speed, verify axis movement by hand for binds, and confirm the print cannot crash into the gantry. Electrical causes like driver current and overheating also drop torque.",
        "real_world_application": "A shifting print is a total loss: production parts and long prints fail hours in; print farms cap acceleration after the first shift incident rather than restarting jobs.",
        "common_misconceptions": [
            "Layer shift is a slicer problem (it is a motion-system failure, not g-code)",
            "Faster motors fix shifts (acceleration demand, not top speed, usually stalls the motor)",
            "Tightening belts always helps (over-tight belts add bind and can cause skipping)",
        ],
        "teaching_strategy": "Show a shifted print, then a diagnostic tree: torque, belts, binds - with the check-and-fix order as a checklist.",
        "script": "A layer that jumps sideways means the motion system lied - the motor skipped, or the belt slipped. Three suspects. One: too much acceleration; the stepper stalls, loses its position, and starts counting from the wrong place. Two: loose belts or pulley screws letting the axis slip. Three: a bind - a tight bearing, a bent gantry, or the print crashing the nozzle. Fix in order: tension belts, torque screws, slow acceleration, slide the axis by hand. And make sure the part clears the gantry. Skip the steps, and the whole print is garbage.",
        "text_overlay": [
            "MOTOR STALL = LOST STEPS",
            "LOOSE BELT = SLIP",
            "BIND = DEAD STOP",
            "CHECK TORQUE, TENSION, BINDS",
        ],
        "scenes": [
            {
                "goal": "Hook: the shifted print",
                "teaching_point": "One sudden jump ruins the print",
                "shot": "wide shot of a print with a clear layer shift offset",
                "motion": "slow push-in on the offset step",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["shifted print", "offset layers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D print with a visible layer shift offset, raking side light, dark bench",
            },
            {
                "goal": "Lost steps",
                "teaching_point": "Acceleration stalls the stepper",
                "shot": "graphic-style shot of a stepper motor stalling and losing count",
                "motion": "step count jumps and position resets",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["stepper diagram", "step counter", "stall marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a stepper motor diagram stalling and losing its step count on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Belt slip",
                "teaching_point": "Loose belts and screws slip",
                "shot": "close-up of hands checking belt tension and pulley grub screws",
                "motion": "belt pressed, screwdriver on grub screw",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["belt", "pulley", "grub screw", "screwdriver"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of checking belt tension and tightening pulley grub screws on a printer, bright task lighting, print lab",
            },
            {
                "goal": "Mechanical binds",
                "teaching_point": "Tight bearings and crashes stop the axis",
                "shot": "medium shot of sliding an axis by hand to feel resistance",
                "motion": "axis slides with a catch",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["gantry", "axis", "hands", "bearings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of sliding a printer axis by hand to check for binds, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Fix in the right order",
                "shot": "wide hero shot of a clean tall print completing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["tall clean print", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a tall clean 3D print completing on the printer, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A print split in two by a sudden offset step",
            "subject": "shifted print with an offset layer line",
            "background": "dark print lab blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "shifted print center, cause labels around",
            "text": "LAYER SHIFT?",
            "elements": ["shifted print", "offset step", "cause labels"],
            "style": "diagnostic studio photography",
            "mood": "failed, diagnostic, corrective",
            "prompt": "photograph of a 3D print with a dramatic layer shift and cause labels around it, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Layer Shift: Find the Cause",
            "title_variations": [
                "Why Is My Print Shifting?",
                "Skipped Steps Explained",
                "Loose Belt Layer Shift",
                "Layer Shift Fix Order",
                "Printer Skips Layers",
            ],
            "description": "Layer shift is a sudden lateral offset that usually means the motion system failed: a stepper stalled under acceleration demand and lost its position, a loose belt or pulley screw let the carriage slip, or a mechanical bind - tight bearings, a bent gantry, or the print colliding with the nozzle - stopped the axis. Fix in order: tension belts and torque pulley grub screws, reduce acceleration or print speed, slide the axis by hand to feel binds, and verify the print clears the gantry. Electrical causes like driver current and overheating also drop torque. This short walks the diagnostic tree from symptom to fix.",
            "hashtags": ["#LayerShift", "#3Dprinting", "#Troubleshooting", "#FixIt"],
            "seo_keywords": [
                "layer shift fix",
                "why is my print shifting",
                "skipped steps 3d printer",
                "loose belt layer shift",
                "stepper motor stall",
                "3d print layer offset",
                "belt tension layer shift",
            ],
        },
        "fact_check": [
            "Skipped steps occur when acceleration demand exceeds stepper torque, losing positional reference.",
            "Loose belts or pulley grub screws allow the carriage to slip relative to the motor.",
            "Mechanical binds and print collisions stop an axis abruptly, producing the same symptom.",
            "Driver current, driver temperature, and supply voltage all affect available stepper torque.",
            "Layer shift is cumulative: once steps are lost, every later layer prints at the new position.",
        ],
    },
    # ======================================================================
    {
        "topic": "Klipper vs Marlin",
        "core_question": "Should I run Klipper or Marlin on my printer?",
        "learning_objective": "The viewer can compare the two firmware families and decide by hardware, features, and willingness to tune.",
        "engineering_summary": "Marlin is the classic firmware: runs on the printer's own board, mature, easy for beginners, supports nearly every machine out of the box, but its motion planning is limited by the board's CPU. Klipper moves the heavy computation to a host (Raspberry Pi or similar) and sends motion to the board in real time, enabling input shaping, pressure advance, and faster, smoother motion even on cheap boards. Klipper's configuration is a single text file, requires a host computer, and demands more setup and tuning. Marlin is set-and-forget; Klipper is tune-and-fly. If you want speed, resonance compensation, and are comfortable editing configs, Klipper wins; for reliability out of the box, Marlin.",
        "real_world_application": "Speed-builders run Klipper with input shaping on stock hardware to nearly double print speed; production and hobby machines that must just work stay on Marlin.",
        "common_misconceptions": [
            "Klipper makes hardware faster (it removes firmware limits; mechanics still set the ceiling)",
            "Klipper needs a fast board (it offloads math to the host precisely because boards are weak)",
            "Marlin is outdated (it is actively developed and the default on most machines)",
        ],
        "teaching_strategy": "Show the architecture difference - board versus host - then side-by-side results with input shaping, and a decision rule by user type.",
        "script": "Your printer's brain comes in two flavors. Marlin runs on the board itself: mature, simple, and it just works out of the box - but the little chip limits how fast it can think. Klipper outsources the math to a host computer and pipes the answers to the board in real time. That unlocks input shaping, pressure advance, and faster, smoother motion - even on cheap boards. The cost: a host, a config file, and tuning patience. Marlin: flash and forget. Klipper: tune and fly. Speed and control? Klipper. Just works? Marlin.",
        "text_overlay": [
            "MARLIN: BOARD BRAINS",
            "KLIPPER: HOST BRAINS",
            "KLIPPER = SHAPING + SPEED",
            "TUNE? KLIPPER. JUST WORKS? MARLIN",
        ],
        "scenes": [
            {
                "goal": "Hook: the brain question",
                "teaching_point": "Firmware decides how the printer thinks",
                "shot": "tabletop shot of a printer mainboard and a host computer side by side",
                "motion": "camera pans between them",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["mainboard", "host computer", "printer"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a 3D printer mainboard and a host computer side by side on a dark studio table, even diffused lighting",
            },
            {
                "goal": "Marlin",
                "teaching_point": "Runs on the board, mature and simple",
                "shot": "medium shot of a Marlin boot screen on a printer display",
                "motion": "menu scrolls",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["printer screen", "Marlin menu", "printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Marlin firmware menu on a 3D printer display, neutral lab lighting, print lab",
            },
            {
                "goal": "Klipper",
                "teaching_point": "Host does the math, board follows",
                "shot": "graphic-style shot of a host computer feeding motion commands to a board",
                "motion": "command packets stream to the board",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["host diagram", "board diagram", "command stream"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a Klipper architecture diagram with a host computer streaming motion commands to a board, dark screen, clean engineering visualization",
            },
            {
                "goal": "Input shaping",
                "teaching_point": "Resonance compensation unlocks speed",
                "shot": "side-by-side prints: ringing and clean",
                "motion": "cross-cut between the two surfaces",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["ringing print", "clean print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a ringing print beside a clean print with input shaping, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Choose by your style",
                "shot": "wide hero shot of a fast clean print on a Klipper screen with stats",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fast print", "Klipper dashboard", "printer"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a fast clean 3D print with a Klipper dashboard screen behind, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A brain split: mainboard left, host computer right",
            "subject": "mainboard and host computer with a VS between",
            "background": "dark machine shop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "mainboard left, host right, VS center",
            "text": "KLIPPER vs MARLIN",
            "elements": ["mainboard", "host computer", "VS graphic"],
            "style": "industrial comparison photography",
            "mood": "technical, comparative, decisive",
            "prompt": "photograph of a printer mainboard on the left and a host computer on the right with a VS graphic, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Klipper or Marlin?",
            "title_variations": [
                "Klipper vs Marlin Firmware",
                "Which Firmware Should I Run",
                "Input Shaping with Klipper",
                "Marlin vs Klipper Speed",
                "Firmware Comparison 3D Printers",
            ],
            "description": "Marlin runs on the printer's own board: mature, simple, and compatible with nearly every machine out of the box, but its motion planning is limited by the board's CPU. Klipper offloads the math to a host computer and streams commands to the board in real time, enabling input shaping, pressure advance, and faster smoother motion even on budget boards. The trade-off is setup: Klipper needs a host, a config file, and tuning patience. Marlin is flash and forget; Klipper is tune and fly. This short compares the architectures, shows input-shaping results, and gives a decision rule for your printer and your style.",
            "hashtags": ["#Klipper", "#Marlin", "#Firmware", "#3Dprinting"],
            "seo_keywords": [
                "Klipper vs Marlin",
                "Klipper firmware explained",
                "Marlin firmware",
                "input shaping 3d printer",
                "Klipper on Raspberry Pi",
                "best printer firmware",
                "faster 3d printing firmware",
            ],
        },
        "fact_check": [
            "Marlin executes motion planning on the printer mainboard itself.",
            "Klipper runs motion planning on a host computer and streams step commands to the board.",
            "Klipper enables input shaping and pressure advance that Marlin boards often lack or implement more coarsely.",
            "Klipper requires a host computer (typically a Raspberry Pi) running continuously.",
            "Both firmwares are actively maintained; Marlin remains the default on most commercial printers.",
        ],
    },
    # ======================================================================
    {
        "topic": "Print-in-Place Mechanisms",
        "core_question": "How do print-in-place mechanisms work, and how do I design them?",
        "learning_objective": "The viewer can design a print-in-place joint with correct clearances, breakaway layers, and orientation, and fix fused parts.",
        "engineering_summary": "Print-in-place parts assemble themselves during printing: joints, hinges, and gears are printed as separate parts in one pass, separated by clearance gaps in the model. Success depends on the x-y clearance between moving surfaces, typically 0.3-0.5 mm for a free hinge and 0.2-0.3 mm for a gear pair, plus z clearance so layers do not fuse into bridges. The first separation happens because the slicer treats the gap as a travel move; layer fusion at the top of a gap makes breakaway layers. Design rules: orient the gap so its top surface is flat, keep the moving interface perpendicular to the build plate where possible, and avoid elephant foot by raising clearance at the first layer. Calibrated extrusion width is essential: over-extrusion fuses print-in-place joints.",
        "real_world_application": "Foldable drones, articulated toys, and tool-less enclosures ship as single prints; print farms set dedicated calibrated profiles because one over-extruded layer fuses an entire mechanism.",
        "common_misconceptions": [
            "Print-in-place parts are always printed fused (they rely on exact clearances, not on breaking apart)",
            "Bigger gaps make better joints (excess clearance makes sloppy, rattling parts)",
            "Any printer can print them (over-extrusion and elephant foot fuse the joints)",
        ],
        "teaching_strategy": "Cut into a print-in-place hinge to show the gap anatomy, show an over-extrusion failure, then the clearance table and design rules.",
        "script": "A hinge, printed in one piece, works on day one - if the gaps are right. Print-in-place parts hide a tiny separation between moving surfaces, and that gap is everything. Too small, and layers fuse across it; the joint welds shut. Too big, and the mechanism rattles like a cheap toy. The sweet spot: about a third of a millimeter for hinges, a little less for gears. Keep the gap opening upward so each layer draws cleanly, and watch your flow: over-extrusion is the number one joint killer. Calibrate the machine first, then design the motion.",
        "text_overlay": [
            "GAP = THE MECHANISM",
            "0.3MM: HINGE | 0.25MM: GEAR",
            "GAP FACES UP",
            "OVER-EXTRUSION WELDS IT SHUT",
        ],
        "scenes": [
            {
                "goal": "Hook: the one-piece hinge",
                "teaching_point": "One print, moving parts",
                "shot": "macro shot of a print-in-place hinge flexing fresh off the plate",
                "motion": "hinge opens and closes",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["print-in-place hinge", "flexing motion"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a print-in-place hinge flexing open and closed, bright task light, dark bench",
            },
            {
                "goal": "Gap anatomy",
                "teaching_point": "Clearance separates the moving surfaces",
                "shot": "graphic-style shot of a hinge cross-section with the gap highlighted",
                "motion": "gap highlights and parts separate",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hinge cross-section", "clearance gap", "parts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a hinge cross-section diagram with the clearance gap highlighted on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The failure",
                "teaching_point": "Over-extrusion fuses the joint",
                "shot": "macro shot of a fused print-in-place joint",
                "motion": "slow push-in on the welded seam",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["fused joint", "welded seam", "hinge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a fused print-in-place hinge joint with a welded seam, raking side light, dark bench",
            },
            {
                "goal": "The clearances",
                "teaching_point": "0.3mm hinges, 0.25mm gears",
                "shot": "tablet-style graphic showing the clearance table",
                "motion": "values highlight per mechanism",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["clearance table", "hinge", "gear samples"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a clearance table for print-in-place mechanisms on a dark studio screen, even diffused lighting, hinge and gear samples",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Calibrate first, then design motion",
                "shot": "wide hero shot of a fully articulated print-in-place robot",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["articulated robot", "moving joints"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an articulated print-in-place 3D printed robot with moving joints, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hinge cross-section with the critical gap glowing",
            "subject": "print-in-place hinge with a highlighted gap",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "hinge center, gap highlighted, clearance label",
            "text": "PRINT-IN-PLACE",
            "elements": ["hinge", "clearance gap", "glowing seam"],
            "style": "industrial macro photography",
            "mood": "mechanical, precise, clever",
            "prompt": "macro photograph of a print-in-place hinge with a glowing clearance gap highlighted, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Print-in-Place, Zero Assembly",
            "title_variations": [
                "How Print-in-Place Works",
                "Designing Working Hinges",
                "Print-in-Place Clearances",
                "Why Print-in-Place Fuses",
                "One-Print Mechanisms",
            ],
            "description": "Print-in-place parts assemble themselves during printing: joints and hinges are separated by clearance gaps in the model. The x-y gap is everything - too small and layers fuse across it, welding the joint shut; too big and the mechanism rattles. The sweet spot is about 0.3 millimeters for hinges and 0.25 for gear pairs, with the gap opening upward so each layer draws cleanly. Over-extrusion is the number one joint killer, so the machine must be flow-calibrated before the mechanism is designed. This short cuts into a print-in-place hinge, shows the failure modes, and gives the clearance table and design rules.",
            "hashtags": ["#PrintInPlace", "#3Dprinting", "#Design", "#Mechanisms"],
            "seo_keywords": [
                "print in place mechanisms",
                "print in place hinge",
                "print in place clearance",
                "why print in place fuses",
                "articulated 3d print design",
                "working hinges 3d print",
                "no assembly 3d printing",
            ],
        },
        "fact_check": [
            "Print-in-place joints rely on modeled x-y clearances, typically 0.3-0.5 mm for hinges.",
            "Over-extrusion or incorrect extrusion width can bridge the gap and fuse the joint.",
            "Gap orientation matters: upward-facing gaps print cleaner than horizontal pockets.",
            "Elephant foot at the first layer can fuse joints; increasing the first-layer gap or z offset helps.",
            "Gear pairs in print-in-place parts typically use smaller clearances of 0.2-0.3 mm for smooth meshing.",
        ],
    },
    # ======================================================================
    {
        "topic": "Vacuum & Suction",
        "core_question": "How does suction actually work, and what makes a good vacuum grip?",
        "learning_objective": "The viewer can explain pressure-differential suction, estimate holding force, and apply it to grippers and seals.",
        "engineering_summary": "Suction is not pulling; it is pressure pushing. Atmospheric pressure (about 101 kPa) presses on everything; a vacuum cup removes air inside a sealed pocket, so the outside atmosphere pushes the cup against the surface with a force equal to the pressure difference times the cup area. A 50 mm diameter cup holds roughly 200 N at full vacuum. Real cups leak, so force falls with the pressure ratio; soft cup lips conform to rough surfaces while stiff lips need flat surfaces. Venturi ejectors generate vacuum from compressed air with no moving parts; pumps move more volume for big systems. Grip fails when leakage exceeds flow or when lateral shear beats seal friction.",
        "real_world_application": "Robot pick-and-place arms lift glass, sheet metal, and packaged goods with suction cups; CNC fixtures use vacuum to hold sheets flat, and shop dust collection is suction at scale.",
        "common_misconceptions": [
            "Suction pulls objects (the atmosphere pushes; the vacuum only removes the opposing pressure)",
            "Bigger vacuum always means more grip (seal quality and leakage decide the real force)",
            "Suction works on rough surfaces (any leak path kills the pressure difference)",
        ],
        "teaching_strategy": "Show a cup lifting a sheet, cut it open to reveal the pressure difference, then the force equation and the leak failure modes.",
        "script": "Suction doesn't pull - the air pushes. Inside the cup, the vacuum removes the air; outside, the whole atmosphere keeps pressing. That pressure times the cup area is your grip: a fifty millimeter cup holds about two hundred newtons. But only if the seal holds. Rough surfaces leak, leaks drop the pressure, and the grip dies. That's why robot grippers use soft squishy lips, and why the math is area times pressure difference, not the pump's rating. Lift a sheet, hold a part, seal a joint: suction is just atmospheric pressure doing the work.",
        "text_overlay": [
            "SUCTION = ATMOSPHERE PUSHING",
            "FORCE = PRESSURE x AREA",
            "50MM CUP ≈ 200N",
            "LEAKS KILL THE GRIP",
        ],
        "scenes": [
            {
                "goal": "Hook: the lift",
                "teaching_point": "One cup holds a sheet of glass",
                "shot": "medium shot of a robotic arm lifting a glass sheet with suction cups",
                "motion": "sheet lifts smoothly and holds",
                "lighting": "neutral lab light",
                "background": "automation cell",
                "objects": ["robot arm", "suction cups", "glass sheet"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a robotic arm lifting a glass sheet with suction cups in an automation cell, neutral lab lighting",
            },
            {
                "goal": "The pressure story",
                "teaching_point": "Atmosphere pushes into the void",
                "shot": "graphic-style shot of a suction cup with atmosphere arrows pushing inward",
                "motion": "arrows press the cup down",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["suction cup diagram", "pressure arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a suction cup diagram with atmosphere pressure arrows pushing inward on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The force equation",
                "teaching_point": "Area times pressure difference",
                "shot": "tablet-style graphic showing the holding-force formula with numbers",
                "motion": "values pop into the formula",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["formula tablet", "suction cup", "force gauge"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a holding force formula on a tablet beside a suction cup and force gauge, even diffused lighting, dark studio",
            },
            {
                "goal": "Leak failure",
                "teaching_point": "Rough surfaces leak and release",
                "shot": "macro shot of a leaking cup edge on a rough surface",
                "motion": "air bubbles escape the lip",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["suction cup", "rough surface", "leak bubbles"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a leaking suction cup edge on a rough surface with air bubbles escaping, raking side light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Pressure difference is the whole game",
                "shot": "wide hero shot of a vacuum system holding a workpiece on a CNC table",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["vacuum table", "workpiece", "vacuum line"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a vacuum fixture holding a workpiece on a CNC table, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A suction cup with atmosphere arrows showing the push",
            "subject": "suction cup gripping a glass sheet",
            "background": "dark automation cell blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "cup center, pressure arrows radiating",
            "text": "SUCTION 101",
            "elements": ["suction cup", "glass sheet", "pressure arrows"],
            "style": "industrial macro photography",
            "mood": "physics, precise, strong",
            "prompt": "macro photograph of a suction cup gripping a glass sheet with pressure arrows, hard key light with rim, dark automation cell, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Suction: It's the Air Pushing",
            "title_variations": [
                "How Suction Actually Works",
                "Vacuum Cup Force Explained",
                "Why Vacuum Grips Hold",
                "Suction Cups and Pressure",
                "The Physics of Vacuum Grip",
            ],
            "description": "Suction does not pull; the atmosphere pushes. A vacuum cup removes the air inside a sealed pocket, and atmospheric pressure then presses the cup against the surface with a force equal to pressure difference times area. A 50 millimeter cup holds roughly 200 newtons at full vacuum, but only if the seal holds - rough surfaces leak, leaks drop the pressure, and grip dies. Soft cup lips conform to imperfect surfaces, and venturi ejectors make vacuum from compressed air with no moving parts. This short explains the pressure story, the holding-force equation, and why seal quality matters more than pump rating.",
            "hashtags": ["#Vacuum", "#Physics", "#Engineering", "#Robotics"],
            "seo_keywords": [
                "how suction works",
                "vacuum cup force",
                "suction cup physics",
                "vacuum gripper explained",
                "atmospheric pressure suction",
                "venturi vacuum ejector",
                "vacuum holding force",
            ],
        },
        "fact_check": [
            "Atmospheric pressure is about 101 kPa, and suction force equals pressure difference times cup area.",
            "A 50 mm diameter cup at full vacuum holds roughly 200 N (minus seal losses).",
            "Seal leakage reduces the achievable pressure difference, lowering grip force.",
            "Venturi ejectors generate vacuum from compressed air with no moving parts.",
            "Lateral grip capacity depends on the friction coefficient at the cup-to-part seal.",
        ],
    },
    # ======================================================================
    {
        "topic": "Acetone Smoothing ABS",
        "core_question": "How does acetone vapor smoothing work on ABS prints?",
        "learning_objective": "The viewer can set up a safe acetone vapor bath, explain why only ABS smooths, and control the result.",
        "engineering_summary": "Acetone dissolves ABS at the surface: vapor or liquid melts the outer layer, and surface tension pulls the softened plastic into a smooth skin, leaving layer lines gone. Vapor smoothing is gentler and more even than dipping: suspended parts in a sealed chamber with a small acetone pool smooth in minutes. Control knobs are exposure time, vapor temperature, and air circulation - too little leaves lines, too much melts details and collapses thin walls. Safety is the real spec: acetone is flammable, evaporates fast, and the vapor is heavier than air; work in a ventilated area away from ignition sources. Only ABS smooths this way; PLA and PETG resist acetone.",
        "real_world_application": "ABS enclosures, jigs, and prototypes get injection-molded-looking finishes with vapor smoothing; print farms run fume-extracted chambers for batch finishing.",
        "common_misconceptions": [
            "Acetone smooths any plastic (it dissolves ABS; PLA and PETG barely react)",
            "Dipping is the best method (vapor gives even coverage; dipping runs and pools)",
            "More time equals smoother (over-exposure melts details and collapses thin walls)",
        ],
        "teaching_strategy": "Show the before/after on one part, the chamber setup, then the over-smoothing failure to teach exposure control.",
        "script": "Acetone melts ABS - and that's the trick. The vapor dissolves the outer layer, and surface tension pulls the softened plastic smooth, erasing layer lines in minutes. Setup: suspend the part in a sealed jar over a small acetone pool, wait. But control it: too little time leaves lines, too much melts your details away and collapses thin walls. And respect the chemistry: acetone is flammable, its vapor sinks, so ventilate and keep ignition far away. PLA and PETG? They shrug acetone off. ABS is the one material that vapor-smooths like this.",
        "text_overlay": [
            "ACETONE DISSOLVES ABS",
            "SURFACE TENSION SMOOTHS",
            "MINUTES, NOT DIPS",
            "VENTILATE + NO SPARKS",
        ],
        "scenes": [
            {
                "goal": "Hook: the smooth swap",
                "teaching_point": "Layer lines erased in minutes",
                "shot": "before/after macro of an ABS part, ribbed then glossy",
                "motion": "cross-fade between the two surfaces",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["rough ABS part", "smoothed ABS part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a rough ABS print beside a vapor-smoothed glossy ABS print, raking side light, dark bench",
            },
            {
                "goal": "The chemistry",
                "teaching_point": "Acetone dissolves the outer layer",
                "shot": "graphic-style shot of solvent molecules softening the surface",
                "motion": "surface layer melts into a skin",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["surface diagram", "solvent molecules", "melting skin"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a polymer surface diagram with acetone molecules melting the outer layer on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The chamber",
                "teaching_point": "Suspend, pool, seal, wait",
                "shot": "tabletop shot of a sealed vapor chamber with a suspended part",
                "motion": "part lowers in, lid seals",
                "lighting": "bright task light",
                "background": "workshop bench",
                "objects": ["vapor chamber", "suspended part", "acetone pool"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a sealed acetone vapor smoothing chamber with a part suspended inside, bright task lighting, workshop bench",
            },
            {
                "goal": "Over-smoothing",
                "teaching_point": "Too long melts the details",
                "shot": "macro shot of an over-smoothed part with collapsed details",
                "motion": "slow push-in on the melted features",
                "lighting": "warm task light",
                "background": "dark bench",
                "objects": ["over-smoothed part", "melted details", "collapsed wall"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of an over-smoothed ABS print with melted and collapsed details, warm task light, dark bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Control time, respect the chemistry",
                "shot": "wide hero shot of a glossy smoothed enclosure part on a bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["glossy smoothed part", "chamber"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a glossy acetone-smoothed ABS enclosure part, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part emerging from vapor, half ribbed half gloss",
            "subject": "ABS part emerging from a vapor chamber",
            "background": "dark workshop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "part center, chamber left, gloss gradient",
            "text": "VAPOR SMOOTHING",
            "elements": ["ABS part", "vapor chamber", "glossy surface"],
            "style": "industrial macro photography",
            "mood": "chemical, glossy, controlled",
            "prompt": "photograph of an ABS part emerging from an acetone vapor chamber with a glossy smoothed surface, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Acetone Smoothing: ABS Only",
            "title_variations": [
                "Vapor Smoothing ABS Explained",
                "How to Smooth ABS Prints",
                "Acetone Bath for 3D Prints",
                "Glossy ABS Finish",
                "Smooth Prints Without Sanding",
            ],
            "description": "Acetone dissolves ABS, and vapor smoothing puts that chemistry to work: the vapor melts the outer layer and surface tension pulls the softened plastic into a smooth skin, erasing layer lines in minutes. The setup is simple - suspend the part in a sealed chamber with a small acetone pool - but control matters: too little time leaves lines, too much melts details and collapses thin walls. Safety is non-negotiable: acetone is flammable and its vapor sinks, so ventilate and keep ignition sources away. PLA and PETG resist acetone, so ABS is the material that vapor-smooths. This short covers the mechanism, setup, and exposure control.",
            "hashtags": ["#ABS", "#Acetone", "#Finishing", "#3Dprinting"],
            "seo_keywords": [
                "acetone smoothing ABS",
                "vapor smoothing 3d prints",
                "acetone bath ABS",
                "smooth ABS finish",
                "acetone vapor chamber",
                "ABS post processing",
                "glossy 3d print finish",
            ],
        },
        "fact_check": [
            "Acetone dissolves ABS at the surface; surface tension then levels the softened layer.",
            "PLA and PETG are largely acetone-resistant, so vapor smoothing is ABS-specific.",
            "Vapor smoothing is more even than dipping, which can run and pool.",
            "Over-exposure melts fine details and can collapse thin walls.",
            "Acetone is highly flammable with vapor heavier than air; ventilation and spark isolation are required.",
        ],
    },
    # ======================================================================
    {
        "topic": "Resin Types",
        "core_question": "Which SLA resin should I use for which job?",
        "learning_objective": "The viewer can sort standard, tough, durable, castable, and engineering resins by use case.",
        "engineering_summary": "Standard resin is the cheap default: crisp details and smooth surfaces, but brittle with low impact resistance, suitable for display pieces. Tough resins add impact modifiers for parts that take knocks. Durable resins flex and absorb energy, acting like ABS prints. Castable resins burn out cleanly for jewelry and investment casting. Engineering resins cover high temperature (HT), high stiffness, and biocompatible (dental, medical) grades at premium prices. All resin parts share weaknesses: UV degradation, creep under sustained load, and sensitivity to supports and orientation. Price tracks performance: a tough or engineering resin costs several times standard.",
        "real_world_application": "Jewelers cast from castable resin; dental labs use biocompatible grades; product teams use tough resin for snap-fit prototypes and standard resin for fit checks.",
        "common_misconceptions": [
            "All resin is brittle (tough and durable grades rival ABS-like thermoplastics)",
            "Resin is stronger than FDM plastic (standard resin is glassy-brittle; toughness costs extra)",
            "One resin does everything (each grade trades off strength, flexibility, temperature, and cost)",
        ],
        "teaching_strategy": "Show a drop test across resin grades, then the castable burn-out demo and a price-versus-performance decision table.",
        "script": "Resin isn't one material - it's a family. Standard resin: gorgeous detail, glass-brittle, perfect for display. Tough resin: takes knocks and drops without shattering - the workhorse for prototypes. Durable resin flexes and springs back, like a printed rubber band. Castable resin burns out clean, which is why jewelers print in it and cast the final metal. And engineering grades handle heat and even your mouth - at several times the price. Rule of thumb: standard for lookers, tough for users, castable for metal, engineering for extremes. Match the resin to the job, not the machine.",
        "text_overlay": [
            "STANDARD: DISPLAY",
            "TOUGH: PROTOTYPES",
            "DURABLE: FLEX",
            "CASTABLE: TO METAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the drop test",
                "teaching_point": "Resin grades fail differently",
                "shot": "tabletop shot of three resin parts being dropped",
                "motion": "standard shatters, tough bounces",
                "lighting": "bright task light",
                "background": "test bench",
                "objects": ["resin parts", "drop test", "shattered standard part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a drop test with three SLA resin parts where the standard one shatters, bright task light, test bench",
            },
            {
                "goal": "Standard vs tough",
                "teaching_point": "Tough resin survives impacts",
                "shot": "macro close-up of a tough resin part after impact, intact",
                "motion": "slow push-in on the undamaged edge",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["tough resin part", "impact point"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of an intact tough resin part after impact testing, raking side light, dark bench",
            },
            {
                "goal": "Castable",
                "teaching_point": "Burns out clean for metal casting",
                "shot": "tabletop shot of a castable resin ring pattern being burned out of a mold",
                "motion": "pattern disappears, metal pours",
                "lighting": "warm task light",
                "background": "foundry bench",
                "objects": ["castable ring", "investment mold", "molten metal"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a castable resin ring pattern being burned out and cast in metal, warm task light, foundry bench",
            },
            {
                "goal": "Engineering grades",
                "teaching_point": "Heat and biocompatibility cost more",
                "shot": "tabletop shot of high-temperature and biocompatible resin bottles",
                "motion": "camera pans across the labels",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["HT resin bottle", "dental resin bottle", "printed parts"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of high-temperature and biocompatible resin bottles with printed parts, even diffused lighting, dark studio",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match resin to the job",
                "shot": "wide hero shot of four resin prints lined up by grade",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["four resin prints", "grade labels"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of four SLA resin prints lined up with grade labels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Four resin bottles feeding one print, each labelled",
            "subject": "resin bottles with a printed part",
            "background": "dark studio blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "bottles left, print right, labels",
            "text": "PICK YOUR RESIN",
            "elements": ["resin bottles", "printed part", "grade labels"],
            "style": "studio product photography",
            "mood": "categorized, practical, clear",
            "prompt": "photograph of four resin bottles beside a printed part with grade labels, hard key light with rim, dark studio, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Resin Types: Pick Right",
            "title_variations": [
                "Which SLA Resin Should I Use",
                "Tough vs Standard Resin",
                "Castable Resin Explained",
                "Resin Grades Compared",
                "Engineering Resin Guide",
            ],
            "description": "SLA resin is a family, not one material. Standard resin gives crisp details but is glass-brittle, perfect for display pieces. Tough resin survives drops and impacts for functional prototypes. Durable resin flexes and springs back like rubber. Castable resin burns out cleanly so jewelers print a pattern and cast the final metal. Engineering grades handle heat and biocompatibility at several times the price. All resin shares UV sensitivity and creep under sustained load. This short compares the grades with a drop test, a casting demo, and a price-versus-performance rule for choosing the right resin for the job.",
            "hashtags": ["#Resin", "#SLA", "#3Dprinting", "#Materials"],
            "seo_keywords": [
                "SLA resin types",
                "tough resin vs standard resin",
                "castable resin",
                "durable resin 3d printing",
                "engineering resin",
                "which resin should I use",
                "resin material comparison",
            ],
        },
        "fact_check": [
            "Standard resins are brittle with low impact strength compared to ABS-like thermoplastics.",
            "Tough and durable resins use impact modifiers and flexible networks to improve toughness.",
            "Castable resins are formulated to burn out cleanly with minimal ash for investment casting.",
            "Engineering resins include high-temperature, high-stiffness, and biocompatible grades at premium prices.",
            "All photopolymer parts degrade under prolonged UV exposure and creep under sustained load.",
        ],
    },
    # ======================================================================
    {
        "topic": "Snap Fits",
        "core_question": "How do I design a snap fit that clicks together and doesn't break?",
        "learning_objective": "The viewer can design cantilever and annular snap fits with deflection limits and understand why PLA snaps.",
        "engineering_summary": "A snap fit locks by elastic deflection: a cantilever or ring deflects as parts engage, then springs back into a retention groove. The design variables are beam length, thickness, and the ramp angle that sets insertion force; the retention angle (90 degrees for permanent, 30-45 for detachable) sets removal force. The failure mode is over-strain: plastics like PLA break when deflection strain exceeds about 2-3% of the beam thickness. The fix is length: a longer, thinner cantilever deflects farther at lower strain. Print orientation matters - cantilevers should print flat with layers along the beam so the hinge plane is strong, and living-hinge-style roots need fillets.",
        "real_world_application": "Battery doors, camera mounts, and consumer enclosures use cantilever snaps; automotive and medical parts use annular snaps where orientation allows.",
        "common_misconceptions": [
            "Snap fits work in any plastic (PLA snaps at low strain; nylon and PETG tolerate far more deflection)",
            "Thicker beams are stronger (thickness raises strain; length, not mass, cures snapping)",
            "Snap fits are permanent (retention angle sets whether they release or not)",
        ],
        "teaching_strategy": "Show a broken snap and a working one, the strain math as a diagram, then the design recipe: length, fillet, orientation.",
        "script": "A snap fit is elastic deflection, then release. The catch pushes a cantilever aside, and it springs back into the groove. Design in three numbers: beam length, thickness, and the angle of the ramp. Too stiff, and the plastic strains past its limit - PLA snaps at a few percent strain. The classic fix is length: longer beams deflect farther with less stress. Fillet the root, where cracks start. Print it flat, layers along the beam. Angle decides the feel: ninety degrees locks forever, forty-five releases by hand. Deflect, spring, lock.",
        "text_overlay": [
            "DEFLECT, SPRING, LOCK",
            "LENGTH CURES SNAPPING",
            "FILLET THE ROOT",
            "90 DEG = LOCK | 45 = RELEASE",
        ],
        "scenes": [
            {
                "goal": "Hook: the broken snap",
                "teaching_point": "PLA snaps at low strain",
                "shot": "macro close-up of a snapped cantilever snap fit",
                "motion": "slow push-in on the fracture plane",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["broken snap fit", "fracture plane", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a broken snap fit cantilever with a clean fracture plane, raking side light, dark bench",
            },
            {
                "goal": "The mechanism",
                "teaching_point": "Elastic deflection and spring-back",
                "shot": "graphic-style shot of a cantilever deflecting and springing into a groove",
                "motion": "beam bends, catches, locks",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["cantilever diagram", "groove", "deflection arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a cantilever snap fit diagram deflecting and locking into a groove on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The strain limit",
                "teaching_point": "Length lowers strain",
                "shot": "tablet-style graphic comparing short and long beams",
                "motion": "stress numbers drop as the beam lengthens",
                "lighting": "even diffused light",
                "background": "dark studio",
                "objects": ["beam comparison diagram", "strain numbers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a beam strain comparison diagram on a dark studio screen, even diffused lighting",
            },
            {
                "goal": "Orientation and fillets",
                "teaching_point": "Print flat, fillet the root",
                "shot": "CAD-style shot of a snap fit with the beam orientation and root fillet highlighted",
                "motion": "fillet highlights and layer lines appear",
                "lighting": "neutral lab light",
                "background": "CAD workstation",
                "objects": ["CAD model", "root fillet", "layer direction"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a CAD model of a snap fit with root fillet and layer direction highlighted, neutral lab lighting, CAD workstation",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the feel with angles",
                "shot": "wide hero shot of a snapped-together enclosure clicking shut",
                "motion": "parts click together and hold",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["enclosure halves", "working snap fit"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a 3D printed enclosure snapping together and holding, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cantilever beam flexing with a highlighted root fillet",
            "subject": "snap fit beam deflecting into a groove",
            "background": "dark machine shop blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "beam center, deflection arrow, fillet highlight",
            "text": "SNAP FITS 101",
            "elements": ["snap fit beam", "groove", "deflection arrow"],
            "style": "industrial macro photography",
            "mood": "mechanical, precise, springy",
            "prompt": "macro photograph of a snap fit cantilever deflecting into a groove with a deflection arrow, hard key light with rim, dark machine shop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Snap Fits That Don't Break",
            "title_variations": [
                "How to Design Snap Fits",
                "Why PLA Snap Fits Break",
                "Cantilever Snap Design",
                "Snap Fit Angles Explained",
                "Working Snap Joints",
            ],
            "description": "A snap fit is elastic deflection: the catch pushes a cantilever aside and it springs back into the groove. Three numbers rule the design: beam length, thickness, and ramp angle. PLA breaks at only a few percent strain, so stiff thick beams snap - the classic fix is length, because longer beams deflect farther at lower stress. A fillet at the root stops cracks, and printing flat keeps layer lines along the beam for strength. The retention angle sets the feel: ninety degrees locks permanently, forty-five releases by hand. This short covers the mechanism, the strain math, and the design recipe for snap fits that click and hold.",
            "hashtags": ["#SnapFit", "#3Dprinting", "#Design", "#Mechanisms"],
            "seo_keywords": [
                "snap fit design",
                "why snap fits break",
                "cantilever snap fit",
                "snap fit 3d printing",
                "snap joint design",
                "PLA snap fit strain",
                "snap fit angles",
            ],
        },
        "fact_check": [
            "Snap fits rely on elastic deflection within the material's strain limit, roughly 2-3% for PLA.",
            "Cantilever strain scales with thickness and inversely with beam length.",
            "Root fillets reduce stress concentration, the common crack initiation site.",
            "Retention angles of 30-45 degrees allow release; 90 degrees is permanent.",
            "Print orientation with layers along the cantilever significantly improves snap strength.",
        ],
    },
]