"""Batch 40: GD&T for prints, datum features, design for FDM vs resin, design for post-processing, dovetail joins, friction-fit vs epoxy, multi-part assemblies, internal channels."""

CURATED = [
    # ======================================================================
    {
        "topic": "GD&T for 3D Prints",
        "core_question": "Which tolerancing rules actually matter on a printed part?",
        "learning_objective": "The viewer understands GD&T applied to printing.",
        "engineering_summary": "GD&T, geometric dimensioning and tolerancing, is the language of how parts fit: it defines the true position of a feature and its allowed zone, so a hole is not just a diameter but a location with a tolerance. On a print, the rules that matter are the ones about form: flatness, parallelism, and true position of holes, because layer ridges and shrinkage make printed features wander more than machined ones. The practical limit is the printer: a 0.2 millimeter layer and thermal shrinkage set the floor for every tolerance you can hold. GD&T tells you what to measure, and the printer tells you what you can promise.",
        "real_world_application": "Mating printed assemblies use true position callouts for hole patterns.",
        "common_misconceptions": [
            "GD&T is only for machining (fit callouts matter on prints too)",
            "Tighter is always better (the printer sets the floor)",
            "A dimension is a guarantee (a zone with a tolerance is)",
        ],
        "teaching_strategy": "Show a hole pattern with true position, then the measured zone.",
        "script": "GD&T, geometric dimensioning and tolerancing, is the language of how parts fit: a hole is not just a diameter but a true position with an allowed zone. On a print, the rules that matter are form: flatness, parallelism, and true position of holes, because layer ridges and shrinkage make features wander more than machined ones. The practical limit is the printer: a 0.2 millimeter layer and thermal shrinkage set the floor for every tolerance you can hold. GD&T tells you what to measure, and the printer tells you what you can promise.",
        "text_overlay": [
            "A HOLE IS A POSITION AND A ZONE",
            "FORM RULES: FLAT, PARALLEL, TRUE",
            "THE PRINTER SETS THE FLOOR",
            "MEASURE WHAT FITS",
        ],
        "scenes": [
            {
                "goal": "Hook: the misaligned plate",
                "teaching_point": "Holes must line up",
                "shot": "close-up shot of misaligned bolt holes on a plate",
                "motion": "camera pans the offset holes",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["plate pair", "offset holes", "bolt gap"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of misaligned bolt holes on a printed plate, bright task lighting, print lab",
            },
            {
                "goal": "The zone",
                "teaching_point": "True position zone",
                "shot": "diagram-style shot of a hole with its tolerance zone",
                "motion": "position circle wraps the hole center",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hole center", "position zone", "diameter callout"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a hole with a true position zone, clean engineering visualization on a dark background",
            },
            {
                "goal": "The form rules",
                "teaching_point": "Flat, parallel, true",
                "shot": "diagram-style shot of flatness and parallelism callouts",
                "motion": "symbols lock onto the faces",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flatness symbol", "parallelism symbol", "form faces"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of form tolerance symbols on a part, clean engineering visualization on a dark background",
            },
            {
                "goal": "The floor",
                "teaching_point": "Printer limits the tolerance",
                "shot": "diagram-style shot of the layer and shrinkage floor",
                "motion": "layer step and shrink arrow set the limit",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["layer step", "shrink arrow", "tolerance floor"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the printer tolerance floor, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Promise what the printer holds",
                "shot": "wide hero shot of mating printed plates bolted true",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["mating plates", "aligned holes", "bolts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of mating printed plates bolted together, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A hole with a true position zone and form symbols on a printed plate",
            "subject": "GD&T for prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "plate center, zone around hole",
            "text": "MEASURE WHAT FITS",
            "elements": ["position zone", "form symbols", "hole pattern"],
            "style": "geometry studio photography",
            "mood": "zoned, measured, aligned",
            "prompt": "photograph of a hole with a true position zone and form symbols on a printed plate, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "GD&T for 3D Prints: Measure What Fits",
            "title_variations": [
                "GD&T on Printed Parts",
                "True Position Printing",
                "Tolerancing a 3D Print",
                "Print Tolerance Callouts",
                "GD&T Basics for Makers",
            ],
            "description": "GD&T, geometric dimensioning and tolerancing, is the language of how parts fit: it defines the true position of a feature and its allowed zone, so a hole is not just a diameter but a location with a tolerance. On a print, the rules that matter are form: flatness, parallelism, and true position, because layer ridges and shrinkage make features wander. The practical limit is the printer. This short zones a hole, locks the form symbols, and shows what you can promise.",
            "hashtags": ["#GDnT", "#Tolerancing", "#Fit", "#3DPrinting"],
            "seo_keywords": [
                "GD&T on printed parts",
                "true position printing",
                "tolerancing a 3D print",
                "print tolerance callouts",
                "GD&T basics for makers",
                "flatness parallelism print",
                "printed hole pattern fit",
            ],
        },
        "fact_check": [
            "GD&T defines fit zones.",
            "Holes have position callouts.",
            "Form rules matter on prints.",
            "The printer sets the floor.",
            "Measure what actually fits.",
        ],
    },
    {
        "topic": "Datum Features",
        "core_question": "Where does measurement start on a printed part?",
        "learning_objective": "The viewer understands datum features.",
        "engineering_summary": "A datum is the reference that every measurement starts from: it is the face or edge you set the part against, and every other dimension is read from it. On a print, the datum should be the largest functional surface, the face that matters in the assembly, so all the other features measure true to the part's real job. The trap is datum drift: a warped bed or a curled corner makes the datum surface wander, and every measurement from it wanders too. Pick the datum that the part lives by, and print it flat. The datum is the anchor of the part's whole truth.",
        "real_world_application": "Assembly faces and mating surfaces are the datums for printed parts.",
        "common_misconceptions": [
            "Any face can be the datum (it must be the functional one)",
            "The datum is just a label (it defines every measurement)",
            "A warped corner does not matter (it moves the whole datum)",
        ],
        "teaching_strategy": "Show measurements radiating from a datum face, then the warp warning.",
        "script": "A datum is the reference that every measurement starts from: the face or edge you set the part against, and every other dimension is read from it. On a print, the datum should be the largest functional surface, the face that matters in the assembly, so all other features measure true to the part's real job. The trap is datum drift: a warped bed or curled corner makes the datum wander, and every measurement from it wanders too. Pick the datum the part lives by, and print it flat.",
        "text_overlay": [
            "EVERY MEASUREMENT STARTS HERE",
            "THE DATUM IS THE FUNCTIONAL FACE",
            "WARPED DATUM, WANDERING TRUTH",
            "PRINT THE DATUM FLAT",
        ],
        "scenes": [
            {
                "goal": "Hook: the confusing part",
                "teaching_point": "Where do you measure from?",
                "shot": "close-up shot of a hand measuring a part against a face",
                "motion": "caliper reads from one face",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper", "datum face", "measured part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of measuring a printed part against a face, bright task lighting, workbench",
            },
            {
                "goal": "The anchor",
                "teaching_point": "All dimensions radiate",
                "shot": "diagram-style shot of dimensions radiating from a datum",
                "motion": "arrows fan from the datum face",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["datum face", "dimension arrows", "feature map"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of dimensions radiating from a datum face, clean engineering visualization on a dark background",
            },
            {
                "goal": "The pick",
                "teaching_point": "The functional face wins",
                "shot": "diagram-style shot of choosing the assembly face as datum",
                "motion": "the mating face gets the label",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["mating face", "datum label", "assembly arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of choosing the assembly face as datum, clean engineering visualization on a dark background",
            },
            {
                "goal": "The drift",
                "teaching_point": "Warped datum, wrong part",
                "shot": "close-up shot of a curled corner lifting a datum face",
                "motion": "the corner rises off the flat",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["curled corner", "datum face", "warp gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a curled corner lifting a datum face, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The part lives by its datum",
                "shot": "wide hero shot of a part seated on its datum in an assembly",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["datum seat", "assembled part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part seated on its datum in an assembly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Dimensions radiating from a labeled datum face with a warp warning",
            "subject": "datum features",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, datum face front",
            "text": "EVERY MEASUREMENT STARTS HERE",
            "elements": ["datum face", "dimension arrows", "warp warning"],
            "style": "geometry studio photography",
            "mood": "anchored, radiating, true",
            "prompt": "wide photograph of dimensions radiating from a labeled datum face with a warp warning at the corner, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Datum Features: Every Measurement Starts Here",
            "title_variations": [
                "What Is a Datum Feature",
                "Print Datum Reference",
                "Measure Prints Correctly",
                "Datum Face Design",
                "Reference Surface Printing",
            ],
            "description": "A datum is the reference that every measurement starts from: the face or edge you set the part against, and every other dimension is read from it. On a print, the datum should be the largest functional surface, so all other features measure true to the part's real job. The trap is datum drift: a warped bed or curled corner makes the datum wander, and everything measured from it wanders too. This short anchors the arrows, picks the functional face, and warns against the drift.",
            "hashtags": ["#DatumFeatures", "#Measurement", "#Reference", "#3DPrinting"],
            "seo_keywords": [
                "what is a datum feature",
                "print datum reference",
                "measure prints correctly",
                "datum face design",
                "reference surface printing",
                "datum drift warp",
                "functional datum face",
            ],
        },
        "fact_check": [
            "The datum starts all measurements.",
            "It should be the functional face.",
            "Dimensions radiate from it.",
            "Warp moves the datum.",
            "Print the datum flat.",
        ],
    },
    {
        "topic": "Design for FDM vs Resin",
        "core_question": "Why does the same part need different designs on different printers?",
        "learning_objective": "The viewer understands design differences between FDM and resin.",
        "engineering_summary": "FDM and resin print in different physics, so the same shape needs different rules: FDM builds fused layers that are strong in one direction and weak across seams, while resin cures thin slices that are nearly uniform but brittle and slow to print. FDM loves horizontal strength and hates steep overhangs, so the part gets laid on its side; resin loves fine detail and overhangs, so the part gets angled to reduce suction and drain holes. The design question is always the same: which process is the part for? The same bracket may need a different wall, a different angle, and a different hole for each machine. Process picks the rules.",
        "real_world_application": "Functional brackets print in FDM while jewelry-like detail goes to resin.",
        "common_misconceptions": [
            "One design fits both (the physics demand different rules)",
            "Resin is just finer FDM (it cures, it does not weld)",
            "Orientation only matters on FDM (resin angles for suction too)",
        ],
        "teaching_strategy": "Show the same part redesigned for each process side by side.",
        "script": "FDM and resin print in different physics, so the same shape needs different rules: FDM fuses layers that are strong in one direction, while resin cures slices that are nearly uniform but brittle and slow. FDM loves horizontal strength and hates steep overhangs, so parts lay on their side; resin loves fine detail, so parts angle to reduce suction and get drain holes. The design question is always the same: which process is the part for? A bracket may need a different wall, angle, and hole for each machine. Process picks the rules.",
        "text_overlay": [
            "FDM WELDS, RESIN CURES",
            "FDM LAYS FLAT, RESIN ANGLES",
            "DRAIN HOLES FOR RESIN",
            "PROCESS PICKS THE RULES",
        ],
        "scenes": [
            {
                "goal": "Hook: the same bracket, two ways",
                "teaching_point": "Different physics",
                "shot": "wide shot of two brackets from different printers",
                "motion": "camera compares the surfaces",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["FDM bracket", "resin bracket", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two printed brackets from FDM and resin printers, neutral lab lighting, workbench",
            },
            {
                "goal": "The physics",
                "teaching_point": "Weld versus cure",
                "shot": "diagram-style shot of layer welding versus slice curing",
                "motion": "both processes build the shape",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["fused layers", "cured slices", "build physics"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of FDM welding versus resin curing, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Lay FDM flat, angle resin",
                "shot": "diagram-style shot of the two orientation rules",
                "motion": "FDM part lies down, resin part tilts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["flat FDM part", "angled resin part", "orientation arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of FDM and resin orientation rules, clean engineering visualization on a dark background",
            },
            {
                "goal": "The holes",
                "teaching_point": "Resin needs drain holes",
                "shot": "diagram-style shot of drain holes on a resin part",
                "motion": "suction arrows escape through the holes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["drain holes", "suction arrows", "hollow part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of drain holes on a resin part, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design for the machine",
                "shot": "wide hero shot of each bracket in its machine",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["FDM machine", "resin machine", "matching parts"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of two printers with their matching parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "The same bracket split into FDM and resin design rules",
            "subject": "design for FDM vs resin",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "two brackets, rules between",
            "text": "PROCESS PICKS THE RULES",
            "elements": ["FDM bracket", "resin bracket", "rule arrows"],
            "style": "geometry studio photography",
            "mood": "split, angled, process-matched",
            "prompt": "overhead photograph of the same bracket shown with FDM and resin design rules beside each machine, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Design for FDM vs Resin: Process Picks the Rules",
            "title_variations": [
                "FDM vs Resin Design Rules",
                "Design a Part for Resin",
                "FDM Orientation Design",
                "Resin Drain Holes",
                "Same Part Two Printers",
            ],
            "description": "FDM and resin print in different physics, so the same shape needs different rules: FDM builds fused layers that are strong in one direction, while resin cures thin slices that are nearly uniform but brittle. FDM loves horizontal strength, so parts lay on their side; resin loves detail, so parts angle to reduce suction and get drain holes. This short welds and cures the same bracket, lays it flat and tilts it, and shows why the process picks the rules.",
            "hashtags": ["#FDMvsResin", "#DesignRules", "#ProcessDesign", "#3DPrinting"],
            "seo_keywords": [
                "FDM vs resin design rules",
                "design a part for resin",
                "FDM orientation design",
                "resin drain holes",
                "same part two printers",
                "resin suction design",
                "FDM layer strength design",
            ],
        },
        "fact_check": [
            "FDM welds layers.",
            "Resin cures slices.",
            "FDM lays flat for strength.",
            "Resin angles for suction.",
            "Each process has its rules.",
        ],
    },
    {
        "topic": "Design for Post-Processing",
        "core_question": "How does finishing change the way you design a part?",
        "learning_objective": "The viewer understands designing for post-processing.",
        "engineering_summary": "Designing for finishing means the part arrives ready to be finished: flat faces that a sander can reach, corners rounded for sanding, and no hidden details the tools cannot touch. The finishing allowance is the rule: if a face gets sanded, the design should add a little material so the final part lands on size, and if it gets coated, the surfaces need to be smooth and sealed first. Supports leave scars where they attach, so the design hides them or makes them reachable. A part designed for finishing finishes in minutes; a part designed without it fights every step.",
        "real_world_application": "Paint-ready enclosures and display parts are designed for the sander and spray.",
        "common_misconceptions": [
            "Finishing fixes any design (hidden details stay unreachable)",
            "Sanding only removes material (designs add allowance for it)",
            "Supports leave no trace (they scar the surface)",
        ],
        "teaching_strategy": "Show a reachable finish job, then the unreachable detail.",
        "script": "Designing for finishing means the part arrives ready to finish: flat faces a sander can reach, corners rounded for sanding, and no hidden details the tools cannot touch. The allowance is the rule: if a face gets sanded, the design adds a little material so the final part lands on size, and coated surfaces need to be smooth and sealed first. Supports leave scars where they attach, so the design hides them or makes them reachable. A part designed for finishing finishes in minutes; a part designed without it fights every step.",
        "text_overlay": [
            "EVERY FACE A TOOL CAN REACH",
            "ADD ALLOWANCE FOR SANDING",
            "SEAL BEFORE YOU COAT",
            "HIDE OR REACH THE SUPPORT SCARS",
        ],
        "scenes": [
            {
                "goal": "Hook: the unreachable pocket",
                "teaching_point": "Finishing cannot reach it",
                "shot": "close-up shot of sanding into a tight pocket",
                "motion": "the sander cannot touch the walls",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["tight pocket", "sanding tool", "unreachable wall"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of sanding into a tight pocket of a print, bright task lighting, workbench",
            },
            {
                "goal": "The allowance",
                "teaching_point": "Add material to remove",
                "shot": "diagram-style shot of the finishing allowance",
                "motion": "sanding arrows shave the extra layer",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["extra layer", "sanding arrows", "final size"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the finishing allowance, clean engineering visualization on a dark background",
            },
            {
                "goal": "The coat",
                "teaching_point": "Smooth and sealed first",
                "shot": "diagram-style shot of a coated surface build-up",
                "motion": "primer, paint, and clear stack up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["primer layer", "paint layer", "clear layer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a coated surface build-up, clean engineering visualization on a dark background",
            },
            {
                "goal": "The scars",
                "teaching_point": "Hide or reach the supports",
                "shot": "comparison shot of hidden and exposed support scars",
                "motion": "hidden scar under a lip, exposed one out",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["hidden scar", "exposed scar", "support lip"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of hidden and exposed support scars on printed parts, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Ready to finish",
                "shot": "wide hero shot of a finished part on the bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished part", "sanding tools", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished printed part beside sanding tools, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A part with reachable flat faces beside a sanding allowance diagram",
            "subject": "design for post-processing",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, allowance diagram beside",
            "text": "EVERY FACE A TOOL CAN REACH",
            "elements": ["flat faces", "allowance layer", "support scars"],
            "style": "geometry studio photography",
            "mood": "reachable, allowed, finished",
            "prompt": "wide photograph of a part with reachable flat faces beside a sanding allowance diagram and hidden support scars, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Design for Post-Processing: Every Face a Tool Can Reach",
            "title_variations": [
                "Design Parts for Sanding",
                "Finishing Allowance Print",
                "Paint-Ready Print Design",
                "Hide Support Scars",
                "Design for Finishing",
            ],
            "description": "Designing for finishing means the part arrives ready to be finished: flat faces that a sander can reach, corners rounded for sanding, and no hidden details the tools cannot touch. If a face gets sanded, the design should add a little material so the final part lands on size, and coated surfaces need to be smooth and sealed first. Supports leave scars where they attach. This short reaches into the pockets, adds the allowance, and finishes a part that was designed to finish.",
            "hashtags": ["#PostProcessing", "#DesignForFinish", "#Sanding", "#3DPrinting"],
            "seo_keywords": [
                "design parts for sanding",
                "finishing allowance print",
                "paint-ready print design",
                "hide support scars",
                "design for finishing",
                "reachable faces design",
                "finishing allowance design",
            ],
        },
        "fact_check": [
            "Faces must be reachable.",
            "Sanding needs allowance.",
            "Coats need smooth bases.",
            "Supports leave scars.",
            "Design decides finish time.",
        ],
    },
    {
        "topic": "Dovetail Joins",
        "core_question": "How do you join two printed parts with no glue and no screws?",
        "learning_objective": "The viewer understands dovetail joints.",
        "engineering_summary": "A dovetail is a wedge-shaped tongue and groove that locks two parts together: the angled walls pull the joint tight in one direction and stop it sliding apart in the other, so the assembly holds with no glue and no fasteners. The joint is a favorite for prints because it slides together in one axis and locks solidly in the others, and the wedge shape keeps the seam from opening under load. The design rules are the angle, about ten degrees, and the fit, tight enough to hold but loose enough to slide. A dovetail is joinery that prints beautifully and holds forever.",
        "real_world_application": "Split enclosures and large panels join with printed dovetails.",
        "common_misconceptions": [
            "Dovetails need glue (the wedge holds on its own)",
            "Any angle works (too steep binds, too shallow slips)",
            "Only woodworkers use them (they print perfectly)",
        ],
        "teaching_strategy": "Show the tongue sliding in, then the lock against load.",
        "script": "A dovetail is a wedge-shaped tongue and groove that locks two parts together: the angled walls pull the joint tight in one direction and stop it sliding apart in the other, so the assembly holds with no glue and no fasteners. It slides together in one axis and locks in the others, and the wedge keeps the seam from opening under load. The rules are the angle, about ten degrees, and the fit: tight enough to hold, loose enough to slide. A dovetail is joinery that prints beautifully and holds forever.",
        "text_overlay": [
            "A WEDGE THAT LOCKS",
            "SLIDES IN ONE AXIS, LOCKS ALL",
            "TEN DEGREES, TIGHT FIT",
            "JOINERY WITH NO FASTENERS",
        ],
        "scenes": [
            {
                "goal": "Hook: the two halves",
                "teaching_point": "No glue, no screws",
                "shot": "wide shot of two halves of a printed panel",
                "motion": "camera shows the empty seam",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["panel halves", "dovetail edge", "empty seam"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two halves of a printed panel, neutral lab lighting, workbench",
            },
            {
                "goal": "The wedge",
                "teaching_point": "Angled walls lock",
                "shot": "diagram-style shot of the dovetail wedge",
                "motion": "angled walls pull the joint tight",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wedge walls", "tongue", "groove"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a dovetail wedge joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "The slide",
                "teaching_point": "One axis to assemble",
                "shot": "diagram-style shot of the joint sliding together",
                "motion": "tongue slides into the groove",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["slide arrow", "tongue path", "groove rail"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a dovetail sliding together, clean engineering visualization on a dark background",
            },
            {
                "goal": "The rules",
                "teaching_point": "Ten degrees, tight fit",
                "shot": "diagram-style shot of the dovetail angle",
                "motion": "angle gauge reads about ten degrees",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["angle gauge", "wedge slope", "fit gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the dovetail angle rule, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Holds forever",
                "shot": "wide hero shot of the joined panel under load",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["joined panel", "dovetail seam", "load"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a joined printed panel under load, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A dovetail tongue sliding into a groove with a ten degree angle label",
            "subject": "dovetail joins",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "joint center, angle label beside",
            "text": "JOINERY WITH NO FASTENERS",
            "elements": ["dovetail tongue", "groove", "angle label"],
            "style": "geometry studio photography",
            "mood": "wedged, slid, locked",
            "prompt": "photograph of a dovetail tongue sliding into a groove with a ten degree angle label, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Dovetail Joins: Joinery With No Fasteners",
            "title_variations": [
                "How to Design a Dovetail",
                "Print a Dovetail Joint",
                "Join Parts Without Glue",
                "Dovetail Angle Guide",
                "Interlocking Print Parts",
            ],
            "description": "A dovetail is a wedge-shaped tongue and groove that locks two parts together: the angled walls pull the joint tight in one direction and stop it sliding apart in the other, so the assembly holds with no glue and no fasteners. It slides together in one axis and locks solidly in the others, keeping the seam from opening under load. The rules are the angle, about ten degrees, and a fit that holds but slides. This short wedges the walls, slides the joint, and locks the panel.",
            "hashtags": ["#Dovetail", "#Joinery", "#Assembly", "#3DPrinting"],
            "seo_keywords": [
                "how to design a dovetail",
                "print a dovetail joint",
                "join parts without glue",
                "dovetail angle guide",
                "interlocking print parts",
                "dovetail joint 3D print",
                "wedge joint assembly",
            ],
        },
        "fact_check": [
            "The wedge locks the joint.",
            "It slides in one axis.",
            "Ten degrees is the angle.",
            "Fit must hold and slide.",
            "No glue or fasteners.",
        ],
    },
    {
        "topic": "Friction-Fit vs Epoxy",
        "core_question": "Should you glue printed parts or press them together?",
        "learning_objective": "The viewer understands friction-fit versus epoxy joints.",
        "engineering_summary": "Two printed parts can join by grip or by glue: a friction fit presses the parts together with a tiny interference so the material's spring holds the joint, while epoxy bonds the surfaces with a chemical weld that fills every gap. The friction fit wins when the joint needs to come apart again, because it is clean and reversible; epoxy wins when the joint carries real load, because the bond is stronger than the plastic itself. The rule is load: light and temporary means friction, heavy and permanent means epoxy. Each joint has a job, and mixing them means designing the fit and the glue joint from the start.",
        "real_world_application": "Snap-together enclosures friction fit, while loaded arms get epoxy.",
        "common_misconceptions": [
            "Glue is always stronger (friction fits beat it when load is light)",
            "Friction fits are weak (they hold real grip with the right interference)",
            "Epoxy needs no preparation (the surfaces need sanding and fit)",
        ],
        "teaching_strategy": "Show the same joint pressed and glued, then the load test.",
        "script": "Two printed parts can join by grip or by glue: a friction fit presses the parts together with a tiny interference so the material's spring holds the joint, while epoxy bonds the surfaces with a chemical weld that fills every gap. Friction wins when the joint must come apart again, because it is clean and reversible; epoxy wins when the joint carries real load, because the bond is stronger than the plastic itself. The rule is load: light and temporary means friction, heavy and permanent means epoxy. Each joint has a job.",
        "text_overlay": [
            "GRIP OR GLUE",
            "FRICTION: CLEAN AND REVERSIBLE",
            "EPOXY: STRONGER THAN THE PLASTIC",
            "LOAD PICKS THE JOINT",
        ],
        "scenes": [
            {
                "goal": "Hook: the two halves",
                "teaching_point": "Join without a fastener",
                "shot": "wide shot of two parts waiting to join",
                "motion": "camera pans the seam",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["part halves", "mating faces", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two printed parts waiting to join, neutral lab lighting, workbench",
            },
            {
                "goal": "The grip",
                "teaching_point": "Interference spring holds",
                "shot": "diagram-style shot of a friction fit cross-section",
                "motion": "interference arrows press the joint",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["interference", "spring grip", "joint section"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a friction fit joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bond",
                "teaching_point": "Epoxy welds the gap",
                "shot": "diagram-style shot of epoxy filling a joint",
                "motion": "glue layer bonds the faces",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["epoxy layer", "bonded faces", "filled gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of epoxy bonding a joint, clean engineering visualization on a dark background",
            },
            {
                "goal": "The load test",
                "teaching_point": "Load picks the winner",
                "shot": "comparison shot of both joints under load",
                "motion": "friction pops, epoxy holds",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["friction joint", "epoxy joint", "load rig"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of friction and epoxy joints under load, bright task lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Each joint has a job",
                "shot": "wide hero shot of both joined parts on the bench",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["fitted part", "glued part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of friction-fitted and epoxy-glued parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A pressed joint beside a glued joint with load arrows deciding",
            "subject": "friction-fit vs epoxy",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "friction left, epoxy right",
            "text": "LOAD PICKS THE JOINT",
            "elements": ["pressed joint", "glued joint", "load arrows"],
            "style": "geometry studio photography",
            "mood": "gripped, bonded, decided",
            "prompt": "comparison photograph of a pressed joint beside a glued joint with load arrows deciding the winner between them, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Friction-Fit vs Epoxy: Load Picks the Joint",
            "title_variations": [
                "Glue or Press Fit Parts",
                "Epoxy Printed Parts",
                "Friction Fit Joint Design",
                "Join Prints Without Screws",
                "Epoxy vs Snap Fit",
            ],
            "description": "Two printed parts can join by grip or by glue: a friction fit presses the parts together with a tiny interference so the material's spring holds the joint, while epoxy bonds the surfaces with a chemical weld that fills every gap. Friction wins when the joint must come apart again, and epoxy wins when the joint carries real load. The rule is load: light and temporary means friction, heavy and permanent means epoxy. This short grips the press, welds the glue, and tests both.",
            "hashtags": ["#FrictionFit", "#Epoxy", "#Joining", "#3DPrinting"],
            "seo_keywords": [
                "glue or press fit parts",
                "epoxy printed parts",
                "friction fit joint design",
                "join prints without screws",
                "epoxy vs snap fit",
                "interference fit print",
                "epoxy bond strength print",
            ],
        },
        "fact_check": [
            "Friction fits use spring grip.",
            "Epoxy welds the gap.",
            "Friction is reversible.",
            "Epoxy carries heavy load.",
            "Load picks the joint.",
        ],
    },
    {
        "topic": "Multi-Part Assemblies",
        "core_question": "How do you design a project that prints as many parts?",
        "learning_objective": "The viewer understands multi-part assembly design.",
        "engineering_summary": "Multi-part design is modular thinking: a big project splits into pieces that each print well, then mate by pins, slots, or dovetails, and every piece must be designed for its own orientation and its own fit. The rules are compatibility: mating features use the same tolerance language, parts share the same reference faces, and each joint is designed for how the user will put it together. The payoff is printability: smaller pieces mean no supports, no failed towers, and no huge build plate, and one bad piece can be reprinted alone. A multi-part build is a system of fits, not a pile of parts.",
        "real_world_application": "Large enclosures and display models split into printable, reprintable pieces.",
        "common_misconceptions": [
            "One big print is simpler (it fails as one big job)",
            "Any split works (each cut must be a designed joint)",
            "Parts just need to be close (they need real fits)",
        ],
        "teaching_strategy": "Show a big part failing, then the modular pieces mating.",
        "script": "Multi-part design is modular thinking: a big project splits into pieces that each print well, then mates by pins, slots, or dovetails. The rules are compatibility: mating features share the same tolerance language, parts share reference faces, and each joint suits how the user will assemble it. The payoff is printability: smaller pieces mean no supports, no failed towers, no huge build plate, and one bad piece can be reprinted alone. A multi-part build is a system of fits, not a pile of parts.",
        "text_overlay": [
            "SPLIT INTO PIECES THAT PRINT WELL",
            "PINS, SLOTS, AND DOVETAILS MATE",
            "ONE BAD PIECE, ONE REPRINT",
            "A SYSTEM OF FITS",
        ],
        "scenes": [
            {
                "goal": "Hook: the failed tower",
                "teaching_point": "One big print fails big",
                "shot": "wide shot of a failed tall print with a snapped layer",
                "motion": "camera pans the failure",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["failed tower", "snapped layer", "build plate"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a failed tall print with a snapped layer, neutral lab lighting, print lab",
            },
            {
                "goal": "The split",
                "teaching_point": "Pieces each print well",
                "shot": "diagram-style shot of a model split into pieces",
                "motion": "the part separates into sections",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["model sections", "split lines", "piece stack"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a model split into printable pieces, clean engineering visualization on a dark background",
            },
            {
                "goal": "The mates",
                "teaching_point": "Pins, slots, dovetails",
                "shot": "diagram-style shot of mating features joining",
                "motion": "pin, slot, and dovetail snap in",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pin joint", "slot joint", "dovetail joint"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of mating features joining parts, clean engineering visualization on a dark background",
            },
            {
                "goal": "The reprint",
                "teaching_point": "One piece reprints alone",
                "shot": "medium shot of a single piece being reprinted",
                "motion": "one part builds while the rest sit assembled",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["reprinting piece", "assembled set", "printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a single piece reprinting beside an assembled set, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A system of fits",
                "shot": "wide hero shot of the full assembly together",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["full assembly", "mating seams", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a full multi-part assembly, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A model split into pieces mating by pins slots and dovetails",
            "subject": "multi-part assemblies",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "split model center, mates around",
            "text": "A SYSTEM OF FITS",
            "elements": ["model pieces", "pin joints", "dovetail mates"],
            "style": "geometry studio photography",
            "mood": "split, mated, modular",
            "prompt": "open photograph of a model split into pieces mating by pins slots and dovetails with a reprinting piece beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Multi-Part Assemblies: A System of Fits",
            "title_variations": [
                "Design Multi-Part Prints",
                "Split a Print Into Pieces",
                "Modular Print Design",
                "Print Large Parts in Parts",
                "Multi-Piece Assembly Guide",
            ],
            "description": "Multi-part design is modular thinking: a big project splits into pieces that each print well, then mate by pins, slots, or dovetails. The rules are compatibility: mating features share tolerance language, parts share reference faces, and each joint suits the user's assembly. The payoff is printability, since smaller pieces mean no supports and one bad piece can be reprinted alone. This short fails a tower, splits the model, and mates the pieces into a system of fits.",
            "hashtags": ["#MultiPart", "#Assembly", "#ModularDesign", "#3DPrinting"],
            "seo_keywords": [
                "design multi-part prints",
                "split a print into pieces",
                "modular print design",
                "print large parts in parts",
                "multi-piece assembly guide",
                "print mating pins slots",
                "modular print system",
            ],
        },
        "fact_check": [
            "Big prints fail big.",
            "Pieces print smaller and safer.",
            "Mates need designed fits.",
            "One piece reprints alone.",
            "A build is a system of fits.",
        ],
    },
    {
        "topic": "Internal Channels",
        "core_question": "How do you print a hollow channel inside a part?",
        "learning_objective": "The viewer understands printing internal channels.",
        "engineering_summary": "An internal channel is a hidden passage for flow, cables, or cooling, and printing one is a geometry problem: the roof of a channel prints over air, so it sags unless it is rounded or angled, and the channel walls must drain and vent or the cavity traps heat and resin. The rules are shape and size: an arched or teardrop roof bridges without supports, a minimum size keeps the channel open, and the ends get drafted so flow passes clean. The failure is collapse: a flat roof sags, a narrow channel clogs, and a sealed pocket traps steam. A channel is a tunnel with print rules.",
        "real_world_application": "Cooling ducts and cable runs thread through printed parts every day.",
        "common_misconceptions": [
            "A flat roof prints fine (it sags over air)",
            "Smaller channels are better (they clog with ridges)",
            "Channels are just holes (roofs and vents need design)",
        ],
        "teaching_strategy": "Show a sagging flat roof, then the arched channel.",
        "script": "An internal channel is a hidden passage for flow, cables, or cooling, and printing one is a geometry problem: the roof prints over air, so it sags unless rounded or angled, and the walls must drain and vent or the cavity traps heat. The rules are shape and size: an arched or teardrop roof bridges without supports, a minimum size keeps the channel open, and drafted ends let flow pass clean. The failure is collapse: a flat roof sags, a narrow channel clogs, and a sealed pocket traps steam. A channel is a tunnel with print rules.",
        "text_overlay": [
            "THE ROOF PRINTS OVER AIR",
            "ARCH IT OR IT SAGS",
            "MINIMUM SIZE, DRAFTED ENDS",
            "A TUNNEL WITH PRINT RULES",
        ],
        "scenes": [
            {
                "goal": "Hook: the sagged roof",
                "teaching_point": "Flat roofs sag",
                "shot": "close-up shot of a sagging channel roof in a cut part",
                "motion": "camera pans the drooped ceiling",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["sagged roof", "channel cut", "drooped ceiling"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a sagging channel roof in a cut printed part, bright task lighting, print lab",
            },
            {
                "goal": "The arch",
                "teaching_point": "Arch bridges without support",
                "shot": "diagram-style shot of an arched channel roof",
                "motion": "the arch bridges the open air",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["arched roof", "open span", "channel body"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of an arched channel roof, clean engineering visualization on a dark background",
            },
            {
                "goal": "The size",
                "teaching_point": "Minimum size stays open",
                "shot": "diagram-style shot of a narrow channel clogging",
                "motion": "ridge walls meet and block",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["narrow walls", "ridge block", "clog point"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a narrow channel clogging, clean engineering visualization on a dark background",
            },
            {
                "goal": "The vent",
                "teaching_point": "Drain and vent the pocket",
                "shot": "diagram-style shot of vent holes on a channel",
                "motion": "steam and resin escape the ends",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["vent holes", "escape arrows", "channel ends"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of vent holes on a channel, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Tunnel with rules",
                "shot": "wide hero shot of a cooling duct part with its channel glowing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["duct part", "channel glow", "flow arrows"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a cooling duct with its internal channel glowing, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cut part showing an arched channel roof beside a sagged flat roof",
            "subject": "internal channels",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "cut part center, roofs compared",
            "text": "A TUNNEL WITH PRINT RULES",
            "elements": ["arched roof", "sagged roof", "channel cut"],
            "style": "geometry studio photography",
            "mood": "arched, vented, flowing",
            "prompt": "photograph of a cut part showing an arched channel roof beside a sagged flat roof, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Internal Channels: A Tunnel With Print Rules",
            "title_variations": [
                "How to Print Channels",
                "Internal Channel Design",
                "Print a Cooling Duct",
                "Channel Roof Sag Fix",
                "Hidden Passages in Prints",
            ],
            "description": "An internal channel is a hidden passage for flow, cables, or cooling, and printing one is a geometry problem: the roof prints over air, so it sags unless rounded or angled, and the walls must drain and vent or the cavity traps heat. The rules are shape and size: an arched roof bridges without supports, a minimum size keeps the channel open, and the ends get drafted. This short sags a flat roof, arches the tunnel, and vents the flow.",
            "hashtags": ["#InternalChannels", "#CoolingDucts", "#Geometry", "#3DPrinting"],
            "seo_keywords": [
                "how to print channels",
                "internal channel design",
                "print a cooling duct",
                "channel roof sag fix",
                "hidden passages in prints",
                "teardrop channel print",
                "channel vent holes print",
            ],
        },
        "fact_check": [
            "Roofs print over air.",
            "Arches bridge without support.",
            "Narrow channels clog.",
            "Pockets need vents.",
            "Channel shape follows rules.",
        ],
    },
]