"""Batch 41: CNC finishing prints, welding plastics, silicone molding, SLS nylon, powder coating, electroplating prints, casting and mold making, DMLS and LPBF."""

CURATED = [
    # ======================================================================
    {
        "topic": "CNC Finishing of Prints",
        "core_question": "Can you machine a printed part for a perfect finish?",
        "learning_objective": "The viewer understands CNC finishing of prints.",
        "engineering_summary": "A print can leave the printer rough and arrive finished by the mill: CNC finishing clamps the printed part and machines the critical faces, holding tolerances and smoothness that layers cannot reach. The rules are plastic rules: light cuts, sharp tools, and a rigid setup, because plastic deflects and melts where metal would chatter. The win is selective: only the mating faces get machined, while the printed geometry keeps its complex shape. The best workflow prints the hard geometry and mills the critical truth.",
        "real_world_application": "Mating faces and bolt pads get milled flat while the print keeps its shape.",
        "common_misconceptions": [
            "Machining a print ruins it (light cuts finish it cleanly)",
            "Metal feeds work on plastic (plastic deflects and melts)",
            "Everything must be machined (only critical faces need it)",
        ],
        "teaching_strategy": "Show a rough face, then the milled face meeting spec.",
        "script": "A print can leave the printer rough and arrive finished by the mill: CNC finishing clamps the printed part and machines the critical faces, holding tolerances and smoothness that layers cannot reach. The rules are plastic rules: light cuts, sharp tools, and a rigid setup, because plastic deflects and melts where metal would chatter. The win is selective: only the mating faces get machined, while the printed geometry keeps its complex shape. Print the hard geometry, mill the critical truth.",
        "text_overlay": [
            "THE MILL FINISHES WHAT LAYERS CANNOT",
            "PLASTIC RULES: LIGHT CUTS",
            "ONLY THE CRITICAL FACES",
            "PRINT GEOMETRY, MILL TRUTH",
        ],
        "scenes": [
            {
                "goal": "Hook: the rough face",
                "teaching_point": "Layers limit the finish",
                "shot": "close-up shot of a rough printed face",
                "motion": "light rakes across the ridges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["rough face", "layer ridges", "printed part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a rough printed face with layer ridges, bright task lighting, print lab",
            },
            {
                "goal": "The clamp",
                "teaching_point": "Rigid setup first",
                "shot": "medium shot of a printed part clamped in a mill",
                "motion": "vise closes on the part",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["vise", "clamped part", "mill table"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printed part clamped in a mill vise, bright task lighting, machine shop",
            },
            {
                "goal": "The pass",
                "teaching_point": "Light cut, sharp tool",
                "shot": "close-up shot of a light mill pass on plastic",
                "motion": "cutter skims the face clean",
                "lighting": "bright task light",
                "background": "machine shop",
                "objects": ["end mill", "light pass", "clean face"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a light mill pass on a printed part, bright task lighting, machine shop",
            },
            {
                "goal": "The selective win",
                "teaching_point": "Only critical faces milled",
                "shot": "comparison shot of milled and printed faces on one part",
                "motion": "milled face shines, printed face stays",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["milled face", "printed face", "one part"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of milled and printed faces on the same part, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Geometry plus machined truth",
                "shot": "wide hero shot of the finished part beside the mill",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished part", "mill", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a CNC-finished part beside a mill, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed part in a mill vise with one face being machined smooth",
            "subject": "CNC finishing prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "part center, cutter above",
            "text": "PRINT GEOMETRY, MILL TRUTH",
            "elements": ["end mill", "clamped part", "clean face"],
            "style": "geometry studio photography",
            "mood": "clamped, machined, precise",
            "prompt": "photograph of a printed part in a mill vise with one face being machined smooth, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "CNC Finishing of Prints: Print Geometry, Mill Truth",
            "title_variations": [
                "Machine a Printed Part",
                "CNC Finish Plastic Print",
                "Milled Print Faces",
                "Mill a 3D Print Flat",
                "CNC Post-Processing Prints",
            ],
            "description": "A print can leave the printer rough and arrive finished by the mill: CNC finishing clamps the printed part and machines the critical faces, holding tolerances and smoothness that layers cannot reach. The rules are plastic rules: light cuts, sharp tools, and a rigid setup, because plastic deflects and melts. The win is selective, since only the mating faces get machined. This short clamps the part, skims the face, and shows print geometry meeting machined truth.",
            "hashtags": ["#CNCFinishing", "#Machining", "#PostProcessing", "#3DPrinting"],
            "seo_keywords": [
                "machine a printed part",
                "CNC finish plastic print",
                "milled print faces",
                "mill a 3D print flat",
                "CNC post-processing prints",
                "CNC plastic cutting rules",
                "mill printed mating faces",
            ],
        },
        "fact_check": [
            "The mill finishes critical faces.",
            "Plastic needs light cuts.",
            "Sharp tools prevent melting.",
            "Only mating faces get milled.",
            "The print keeps its shape.",
        ],
    },
    {
        "topic": "Welding Plastics",
        "core_question": "Can you weld two printed parts into one?",
        "learning_objective": "The viewer understands plastic welding.",
        "engineering_summary": "Plastic parts can be welded with heat and pressure: a hot tool, a friction weld, or a solvent chemically softens the join faces, and the melted plastic fuses into one continuous part. The strongest weld matches the parent material: same filament, clean faces, and even heat, because a weld is only as strong as the bond it makes. The catch is control: too hot and the plastic degrades, too cool and the faces never fuse. A weld is a joint made of the part's own material.",
        "real_world_application": "Repairing cracked parts and extending beams uses heat welding and solvent glue.",
        "common_misconceptions": [
            "Any glue is a weld (a weld fuses the material itself)",
            "Different filaments weld fine (mismatched plastics do not bond)",
            "More heat is faster (heat degrades the plastic)",
        ],
        "teaching_strategy": "Show the fused joint, then the temperature warning.",
        "script": "Plastic parts can be welded with heat and pressure: a hot tool, a friction weld, or a solvent chemically softens the join faces, and the melted plastic fuses into one continuous part. The strongest weld matches the parent material: same filament, clean faces, and even heat, because a weld is only as strong as the bond it makes. The catch is control: too hot and the plastic degrades, too cool and the faces never fuse. A weld is a joint made of the part's own material.",
        "text_overlay": [
            "HEAT AND PRESSURE FUSE THE FACES",
            "MATCH THE PARENT MATERIAL",
            "TOO HOT DEGRADES, TOO COOL NEVER FUSES",
            "A JOINT OF THE PART'S OWN MATERIAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the two broken halves",
                "teaching_point": "They can become one",
                "shot": "wide shot of two halves of a broken part",
                "motion": "camera pans the fracture faces",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["broken halves", "fracture faces", "part"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of two halves of a broken printed part, neutral lab lighting, workbench",
            },
            {
                "goal": "The fuse",
                "teaching_point": "Heat softens and joins",
                "shot": "diagram-style shot of faces fusing under heat",
                "motion": "softened faces merge into one",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["hot tool", "softened faces", "fusion line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of plastic faces fusing under heat, clean engineering visualization on a dark background",
            },
            {
                "goal": "The match",
                "teaching_point": "Same filament bonds best",
                "shot": "diagram-style shot of matching and mismatched plastic",
                "motion": "matching bars fuse, mismatched separate",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["matching bars", "mismatched bars", "bond test"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of matching versus mismatched plastic welding, clean engineering visualization on a dark background",
            },
            {
                "goal": "The catch",
                "teaching_point": "Heat must stay controlled",
                "shot": "diagram-style shot of the weld temperature window",
                "motion": "needle stays between degrade and fuse",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temp needle", "safe window", "degrade zone"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the plastic weld temperature window, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "One part again",
                "shot": "wide hero shot of the welded part whole again",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["welded part", "fusion seam", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a welded printed part whole again, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two plastic faces fusing under a hot tool with a temperature warning",
            "subject": "welding plastics",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "joint center, tool above",
            "text": "A JOINT OF THE PART'S OWN MATERIAL",
            "elements": ["hot tool", "fusion line", "temperature gauge"],
            "style": "geometry studio photography",
            "mood": "fused, matched, controlled",
            "prompt": "photograph of two plastic faces fusing under a hot tool with a temperature gauge, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Welding Plastics: A Joint of the Part's Own Material",
            "title_variations": [
                "How to Weld Plastic Parts",
                "Plastic Welding 3D Print",
                "Friction Weld PLA",
                "Solvent Weld Prints",
                "Repair Print With Welding",
            ],
            "description": "Plastic parts can be welded with heat and pressure: a hot tool, a friction weld, or a solvent chemically softens the join faces, and the melted plastic fuses into one continuous part. The strongest weld matches the parent material, since a weld is only as strong as the bond it makes. The catch is control: too hot and the plastic degrades, too cool and the faces never fuse. This short fuses the halves, matches the filament, and welds the part whole.",
            "hashtags": ["#PlasticWelding", "#Joining", "#Repair", "#3DPrinting"],
            "seo_keywords": [
                "how to weld plastic parts",
                "plastic welding 3D print",
                "friction weld PLA",
                "solvent weld prints",
                "repair print with welding",
                "plastic weld temperature",
                "weld same filament",
            ],
        },
        "fact_check": [
            "Heat and pressure fuse faces.",
            "Solvent softens the join.",
            "Same filament bonds best.",
            "Heat control decides quality.",
            "The weld is parent material.",
        ],
    },
    {
        "topic": "Silicone Molding from Prints",
        "core_question": "How do you turn one print into many identical parts?",
        "learning_objective": "The viewer understands silicone molding from prints.",
        "engineering_summary": "Silicone molding copies a print: the part is suspended in a container, silicone is poured around it, and once it cures you have a flexible mold that casts the same shape over and over. The two-part pour is the classic: a first half, a release layer, and a second half, with a sprue for the resin to enter and vents for the air to leave. The master matters: it must be smooth and sealed, because every master flaw repeats in every cast. One print, one mold, and a hundred parts: that is the payoff.",
        "real_world_application": "Makers cast custom knobs, gaskets, and miniatures from printed masters.",
        "common_misconceptions": [
            "The mold copies perfectly (every master flaw repeats)",
            "One pour is enough (two halves need a release layer)",
            "Any resin works (casting resin needs the right sprue and vents)",
        ],
        "teaching_strategy": "Show the two-part pour, then the repeated casts.",
        "script": "Silicone molding copies a print: the part is suspended in a container, silicone is poured around it, and once it cures you have a flexible mold that casts the same shape over and over. The two-part pour is the classic: a first half, a release layer, and a second half, with a sprue for the resin to enter and vents for the air to leave. The master matters: it must be smooth and sealed, because every master flaw repeats in every cast. One print, one mold, and a hundred parts: that is the payoff.",
        "text_overlay": [
            "THE PRINT BECOMES THE MASTER",
            "POUR HALF ONE, RELEASE, POUR HALF TWO",
            "A SPRUE TO ENTER, VENTS TO LEAVE",
            "ONE MASTER, A HUNDRED PARTS",
        ],
        "scenes": [
            {
                "goal": "Hook: the master part",
                "teaching_point": "One print, many copies",
                "shot": "close-up shot of a printed master part",
                "motion": "camera orbits the part",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["master part", "smooth surface", "print"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printed master part for molding, bright task lighting, print lab",
            },
            {
                "goal": "The box",
                "teaching_point": "Suspended and sealed",
                "shot": "medium shot of a master in a mold box",
                "motion": "part hangs in the container",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["mold box", "suspended master", "container"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printed master suspended in a mold box, neutral lab lighting, workbench",
            },
            {
                "goal": "The pour",
                "teaching_point": "Two halves with release",
                "shot": "diagram-style shot of the two-part pour",
                "motion": "first pour, release layer, second pour",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["first half", "release layer", "second half"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the two-part silicone mold pour, clean engineering visualization on a dark background",
            },
            {
                "goal": "The cast",
                "teaching_point": "Sprue in, vents out",
                "shot": "diagram-style shot of resin casting in the mold",
                "motion": "resin enters the sprue, air leaves the vents",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sprue", "vent holes", "resin flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of casting resin in a silicone mold, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Repeated copies",
                "shot": "wide hero shot of a row of cast parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["cast parts", "row of copies", "master beside"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a row of cast parts beside the master, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed master inside a mold box with a two-part pour diagram",
            "subject": "silicone molding from prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "mold box center, diagram beside",
            "text": "ONE MASTER, A HUNDRED PARTS",
            "elements": ["mold box", "master part", "pour diagram"],
            "style": "geometry studio photography",
            "mood": "poured, cured, copied",
            "prompt": "photograph of a printed master inside a mold box with a two-part pour diagram, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Silicone Molding from Prints: One Master, a Hundred Parts",
            "title_variations": [
                "Make a Silicone Mold",
                "Mold From a 3D Print",
                "Two-Part Mold Tutorial",
                "Cast Parts at Home",
                "Silicone Mold Master Print",
            ],
            "description": "Silicone molding copies a print: the part is suspended in a container, silicone is poured around it, and once it cures you have a flexible mold that casts the same shape over and over. The two-part pour is the classic, with a sprue for the resin to enter and vents for the air to leave. The master matters because every flaw repeats in every cast. This short boxes the master, pours the halves, and casts the row of copies.",
            "hashtags": ["#SiliconeMolding", "#Casting", "#MoldMaking", "#3DPrinting"],
            "seo_keywords": [
                "make a silicone mold",
                "mold from a 3D print",
                "two-part mold tutorial",
                "cast parts at home",
                "silicone mold master print",
                "sprue and vents mold",
                "casting resin mold",
            ],
        },
        "fact_check": [
            "The print becomes the master.",
            "Two halves pour with release.",
            "Sprue and vents direct the cast.",
            "Master flaws repeat in casts.",
            "One mold casts many parts.",
        ],
    },
    {
        "topic": "SLS & Nylon Powder",
        "core_question": "How does a laser sinter nylon powder into a part?",
        "learning_objective": "The viewer understands SLS printing with nylon powder.",
        "engineering_summary": "SLS builds parts from powder: a laser sweeps the bed and sinters each cross-section into solid nylon, then a roller lays fresh powder for the next layer, so the un-sintered powder supports everything, and parts need no supports at all. The win is the freedom: no support structures, strong nylon, and fine detail, which is why SLS parts feel like production parts. The trade-offs are the machine: a heated chamber, expensive powder, and post-processing to blast the loose powder away. SLS trades a big machine for the most design freedom in plastics.",
        "real_world_application": "Production-grade nylon parts with moving joints print nested in powder.",
        "common_misconceptions": [
            "SLS needs supports (the powder bed holds everything)",
            "It is just a laser cutter (each layer sinters into the next)",
            "Powder is cheap (the system and material carry a price)",
        ],
        "teaching_strategy": "Show the powder bed and laser, then the support-free parts.",
        "script": "SLS builds parts from powder: a laser sweeps the bed and sinters each cross-section into solid nylon, then a roller lays fresh powder for the next layer, so the un-sintered powder supports everything, and parts need no supports at all. The win is the freedom: no support structures, strong nylon, and fine detail, which is why SLS parts feel like production parts. The trade-offs are the machine: a heated chamber, expensive powder, and post-processing to blast the loose powder away. SLS trades a big machine for the most design freedom in plastics.",
        "text_overlay": [
            "THE LASER SINTERS EACH CROSS-SECTION",
            "THE POWDER SUPPORTS EVERYTHING",
            "NO SUPPORTS AT ALL",
            "MOST DESIGN FREEDOM IN PLASTICS",
        ],
        "scenes": [
            {
                "goal": "Hook: the powder bed",
                "teaching_point": "Parts grow in powder",
                "shot": "wide shot of an SLS machine with a glowing bed",
                "motion": "camera pans the powder chamber",
                "lighting": "neutral lab light",
                "background": "production floor",
                "objects": ["powder bed", "SLS machine", "chamber"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of an SLS machine with a glowing powder bed, neutral lab lighting, production floor",
            },
            {
                "goal": "The sweep",
                "teaching_point": "Laser sinters, roller lays",
                "shot": "diagram-style shot of the laser and roller cycle",
                "motion": "laser draws, roller spreads fresh powder",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["laser beam", "sinter line", "roller sweep"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the SLS laser and roller cycle, clean engineering visualization on a dark background",
            },
            {
                "goal": "The freedom",
                "teaching_point": "Powder supports the part",
                "shot": "diagram-style shot of parts nested in powder",
                "motion": "unsupported shapes sit in the bed",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nested parts", "powder fill", "free shapes"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of parts nested in SLS powder, clean engineering visualization on a dark background",
            },
            {
                "goal": "The finish",
                "teaching_point": "Blast the loose powder",
                "shot": "medium shot of a part being powder-blasted",
                "motion": "air jets clear the loose powder",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["air jets", "nylon part", "powder cloud"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of an SLS part being powder blasted, neutral lab lighting, workshop",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Production-grade freedom",
                "shot": "wide hero shot of finished SLS nylon parts",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["nylon parts", "moving joints", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of finished SLS nylon parts, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A laser sintering a cross-section in a powder bed with parts nested around",
            "subject": "SLS nylon powder",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bed center, laser above",
            "text": "MOST DESIGN FREEDOM IN PLASTICS",
            "elements": ["laser beam", "powder bed", "nested parts"],
            "style": "geometry studio photography",
            "mood": "sintered, nested, support-free",
            "prompt": "photograph of a laser sintering a cross-section in a powder bed with parts nested around, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "SLS & Nylon Powder: Most Design Freedom in Plastics",
            "title_variations": [
                "How Does SLS Work",
                "SLS Nylon Printing",
                "Selective Laser Sintering",
                "Support-Free SLS Parts",
                "Nylon Powder Print",
            ],
            "description": "SLS builds parts from powder: a laser sweeps the bed and sinters each cross-section into solid nylon, then a roller lays fresh powder for the next layer, so the un-sintered powder supports everything and parts need no supports at all. The win is freedom: no support structures, strong nylon, and fine detail. The trade-offs are the machine, the powder cost, and the blast finishing. This short sweeps the laser, nests the parts, and blasts the finished nylon.",
            "hashtags": ["#SLS", "#NylonPowder", "#IndustrialAM", "#3DPrinting"],
            "seo_keywords": [
                "how does SLS work",
                "SLS nylon printing",
                "selective laser sintering",
                "support-free SLS parts",
                "nylon powder print",
                "SLS powder bed",
                "SLS vs FDM parts",
            ],
        },
        "fact_check": [
            "The laser sinters cross-sections.",
            "Powder supports every part.",
            "No supports are needed.",
            "Heated chambers cost power.",
            "Blasting finishes the parts.",
        ],
    },
    {
        "topic": "Powder Coating",
        "core_question": "Can you powder coat a printed part?",
        "learning_objective": "The viewer understands powder coating prints.",
        "engineering_summary": "Powder coating is a dry paint: charged powder is sprayed at a grounded part, sticks by static, and melts into a tough skin in a curing oven, and the result is a finish tougher than any spray paint. On a print the catch is heat: the curing oven runs hot enough to soften most plastics, so powder coating only works on heat-stable parts like nylon or with low-temperature powder. The payoff is the finish: thick, chip-resistant color that hides layer lines completely. Powder coating is paint with an oven, and the oven is the deciding rule.",
        "real_world_application": "Heat-stable nylon brackets get chip-proof color from powder coating.",
        "common_misconceptions": [
            "Any print can be coated (the oven heat rules it out)",
            "Powder is paint dust (it melts into a skin in the oven)",
            "Layer lines stay visible (the thick skin hides them)",
        ],
        "teaching_strategy": "Show the charged spray, then the oven cure and the skin.",
        "script": "Powder coating is a dry paint: charged powder is sprayed at a grounded part, sticks by static, and melts into a tough skin in a curing oven, and the result is a finish tougher than any spray paint. On a print the catch is heat: the curing oven runs hot enough to soften most plastics, so powder coating only works on heat-stable parts like nylon or with low-temperature powder. The payoff is the finish: thick, chip-resistant color that hides layer lines completely. Powder coating is paint with an oven, and the oven is the deciding rule.",
        "text_overlay": [
            "CHARGED POWDER STICKS BY STATIC",
            "THE OVEN MELTS THE SKIN",
            "HEAT RULES OUT MOST PLASTICS",
            "PAINT WITH AN OVEN",
        ],
        "scenes": [
            {
                "goal": "Hook: the matte bracket",
                "teaching_point": "Spray paint chips",
                "shot": "wide shot of a chipped painted bracket",
                "motion": "camera pans the chip damage",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["chipped bracket", "paint damage", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a chipped painted bracket, neutral lab lighting, workbench",
            },
            {
                "goal": "The charge",
                "teaching_point": "Static sticks the powder",
                "shot": "diagram-style shot of charged powder spraying a part",
                "motion": "powder flies to the grounded part",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["charged powder", "grounded part", "static field"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of powder coating static spray, clean engineering visualization on a dark background",
            },
            {
                "goal": "The oven",
                "teaching_point": "Heat melts the skin",
                "shot": "diagram-style shot of a part curing in an oven",
                "motion": "powder melts into a smooth skin",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["curing oven", "melting powder", "smooth skin"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of powder curing in an oven, clean engineering visualization on a dark background",
            },
            {
                "goal": "The catch",
                "teaching_point": "Heat rules out plastics",
                "shot": "diagram-style shot of the temperature limit bar",
                "motion": "oven heat crosses the plastic limit",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temp bar", "plastic limit", "oven line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of powder coating temperature limits, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A chip-proof skin",
                "shot": "wide hero shot of a coated bracket in color",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["coated bracket", "color skin", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a powder coated bracket, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Charged powder spraying a grounded part beside a curing oven",
            "subject": "powder coating prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "spray center, oven beside",
            "text": "PAINT WITH AN OVEN",
            "elements": ["powder spray", "grounded part", "curing oven"],
            "style": "geometry studio photography",
            "mood": "charged, melted, chip-proof",
            "prompt": "photograph of charged powder spraying a grounded part beside a curing oven with a chip-proof skin, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Powder Coating: Paint With an Oven",
            "title_variations": [
                "Can You Powder Coat Prints",
                "Powder Coat Nylon Parts",
                "Powder Coating Plastic",
                "Chip-Proof Print Finish",
                "Powder Coat 3D Prints",
            ],
            "description": "Powder coating is a dry paint: charged powder is sprayed at a grounded part, sticks by static, and melts into a tough skin in a curing oven. On a print the catch is heat, since the oven runs hot enough to soften most plastics, so only heat-stable parts like nylon qualify. The payoff is a thick, chip-resistant color that hides layer lines. This short charges the spray, melts the skin, and coats the bracket in chip-proof color.",
            "hashtags": ["#PowderCoating", "#Finishing", "#Coating", "#3DPrinting"],
            "seo_keywords": [
                "can you powder coat prints",
                "powder coat nylon parts",
                "powder coating plastic",
                "chip-proof print finish",
                "powder coat 3D prints",
                "powder coating oven heat",
                "static powder spray",
            ],
        },
        "fact_check": [
            "Static sticks the powder.",
            "The oven melts the skin.",
            "Oven heat rules out plastics.",
            "Nylon tolerates the cure.",
            "The skin hides layer lines.",
        ],
    },
    {
        "topic": "Electroplating Prints",
        "core_question": "Can a plastic print wear a real metal coat?",
        "learning_objective": "The viewer understands electroplating prints.",
        "engineering_summary": "Electroplating gives a print a real metal skin: the plastic is first coated with a conductive layer, usually copper or nickel by chemical deposition, then hung in a plating bath where electric current draws metal ions onto the surface. The metal layer is thin but real: it carries current, resists wear, and gives the part a true metal look. The limits are the chemistry: the part must be clean, the conductive base must be uniform, and the bath must be controlled or the plate blisters. Electroplating is a metal skin over a plastic heart.",
        "real_world_application": "Display parts and fixtures get chrome and copper skins from plating baths.",
        "common_misconceptions": [
            "Plating is just painting (it deposits real metal)",
            "Any print plates directly (it needs a conductive base)",
            "The coat is thick and strong (it is a thin skin)",
        ],
        "teaching_strategy": "Show the conductive base, then the bath depositing the skin.",
        "script": "Electroplating gives a print a real metal skin: the plastic is first coated with a conductive layer, usually copper or nickel by chemical deposition, then hung in a plating bath where electric current draws metal ions onto the surface. The metal layer is thin but real: it carries current, resists wear, and gives the part a true metal look. The limits are the chemistry: the part must be clean, the conductive base must be uniform, and the bath must be controlled or the plate blisters. Electroplating is a metal skin over a plastic heart.",
        "text_overlay": [
            "METAL IONS LAND BY CURRENT",
            "FIRST A CONDUCTIVE BASE",
            "THIN, REAL, WEAR-RESISTANT",
            "A METAL SKIN OVER A PLASTIC HEART",
        ],
        "scenes": [
            {
                "goal": "Hook: the plastic part",
                "teaching_point": "It can wear real metal",
                "shot": "close-up shot of a plain plastic part",
                "motion": "camera orbits the part",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["plastic part", "plain surface", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a plain plastic part for plating, bright task lighting, print lab",
            },
            {
                "goal": "The base",
                "teaching_point": "Conductive layer first",
                "shot": "diagram-style shot of the conductive base forming",
                "motion": "copper layer coats the plastic",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["copper layer", "plastic core", "conductive base"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a conductive base on a print, clean engineering visualization on a dark background",
            },
            {
                "goal": "The bath",
                "teaching_point": "Current draws the metal",
                "shot": "medium shot of a part in a plating bath",
                "motion": "bubbles rise as metal deposits",
                "lighting": "neutral lab light",
                "background": "workshop",
                "objects": ["plating bath", "hanging part", "bubble flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a print hanging in an electroplating bath, neutral lab lighting, workshop",
            },
            {
                "goal": "The skin",
                "teaching_point": "Thin, real, and bright",
                "shot": "diagram-style shot of the metal skin cross-section",
                "motion": "thin metal layer wraps the plastic",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["metal skin", "plastic core", "cross-section"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a metal skin on a plastic part, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Metal skin, plastic heart",
                "shot": "wide hero shot of the plated part gleaming",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["plated part", "metal gleam", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an electroplated print gleaming, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A print hanging in a plating bath with a metal skin cross-section beside",
            "subject": "electroplating prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "bath center, section beside",
            "text": "A METAL SKIN OVER A PLASTIC HEART",
            "elements": ["plating bath", "hanging part", "metal section"],
            "style": "geometry studio photography",
            "mood": "coated, deposited, gleaming",
            "prompt": "photograph of a print hanging in a plating bath with a metal skin cross-section beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Electroplating Prints: A Metal Skin Over a Plastic Heart",
            "title_variations": [
                "Can You Electroplate Prints",
                "Copper Plate 3D Print",
                "Metal Plate Plastic",
                "Chrome Print Finish",
                "Electroplating at Home",
            ],
            "description": "Electroplating gives a print a real metal skin: the plastic is first coated with a conductive layer, then hung in a plating bath where electric current draws metal ions onto the surface. The metal layer is thin but real: it carries current, resists wear, and gives a true metal look. The limits are the chemistry, since the base must be uniform and the bath controlled. This short bases the part, hangs it in the bath, and gleams the metal skin.",
            "hashtags": ["#Electroplating", "#MetalPlating", "#Copper", "#3DPrinting"],
            "seo_keywords": [
                "can you electroplate prints",
                "copper plate 3D print",
                "metal plate plastic",
                "chrome print finish",
                "electroplating at home",
                "conductive base plating",
                "plating bath print",
            ],
        },
        "fact_check": [
            "A conductive base comes first.",
            "Current draws the metal.",
            "The skin is thin and real.",
            "Clean parts plate evenly.",
            "The bath needs control.",
        ],
    },
    {
        "topic": "Casting & Mold Making",
        "core_question": "How do you turn a print into cast metal or resin parts?",
        "learning_objective": "The viewer understands casting from printed masters.",
        "engineering_summary": "Casting copies a master into another material: a printed part becomes a pattern, the pattern forms a mold, and the mold fills with resin, plaster, or molten metal to make the real part. The rules are the release and the flow: the pattern must pull free of the mold, and the material must reach every corner, so sprues, vents, and draft angles do the work. The payoff is material choice: one master can cast in materials a printer cannot use. Casting turns a single print into parts made of anything.",
        "real_world_application": "Printed masters cast metal jewelry, resin miniatures, and plaster molds.",
        "common_misconceptions": [
            "The mold copies the print exactly (release and draft still matter)",
            "Any material casts the same (each needs its own sprue system)",
            "The pattern is disposable (it shapes every cast)",
        ],
        "teaching_strategy": "Show the pattern, the mold, and the cast part.",
        "script": "Casting copies a master into another material: a printed part becomes a pattern, the pattern forms a mold, and the mold fills with resin, plaster, or molten metal to make the real part. The rules are the release and the flow: the pattern must pull free of the mold, and the material must reach every corner, so sprues, vents, and draft angles do the work. The payoff is material choice: one master can cast in materials a printer cannot use. Casting turns a single print into parts made of anything.",
        "text_overlay": [
            "THE PRINT BECOMES THE PATTERN",
            "RELEASE AND FLOW DECIDE",
            "SPRUES, VENTS, AND DRAFT",
            "ONE MASTER, ANY MATERIAL",
        ],
        "scenes": [
            {
                "goal": "Hook: the pattern",
                "teaching_point": "The print shapes the mold",
                "shot": "wide shot of a printed pattern part",
                "motion": "camera orbits the pattern",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["pattern part", "draft faces", "bench"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a printed pattern for casting, bright task lighting, print lab",
            },
            {
                "goal": "The mold",
                "teaching_point": "Pattern forms the cavity",
                "shot": "medium shot of a mold forming around a pattern",
                "motion": "mold material sets around the part",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["mold shell", "pattern inside", "cavity"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a mold forming around a printed pattern, neutral lab lighting, workbench",
            },
            {
                "goal": "The flow",
                "teaching_point": "Sprues and vents move material",
                "shot": "diagram-style shot of the sprue and vent system",
                "motion": "material enters, air escapes",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sprue channel", "vent holes", "flow arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a casting sprue and vent system, clean engineering visualization on a dark background",
            },
            {
                "goal": "The release",
                "teaching_point": "Draft pulls the pattern free",
                "shot": "diagram-style shot of the draft angle releasing",
                "motion": "angled walls slide out of the mold",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["draft angle", "mold wall", "release arrow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a draft angle releasing from a mold, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cast in anything",
                "shot": "wide hero shot of cast parts in several materials",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["resin cast", "metal cast", "plaster cast"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of cast parts in resin metal and plaster, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A printed pattern beside its mold and cast copies in different materials",
            "subject": "casting from prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "pattern center, casts around",
            "text": "ONE MASTER, ANY MATERIAL",
            "elements": ["pattern part", "mold shell", "cast copies"],
            "style": "geometry studio photography",
            "mood": "patterned, molded, cast",
            "prompt": "photograph of a printed pattern beside its mold and cast copies in different materials, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Casting & Mold Making: One Master, Any Material",
            "title_variations": [
                "Cast From a Printed Master",
                "Mold Making From Prints",
                "Resin Casting Master",
                "Cast Metal From Print",
                "Pattern to Cast Guide",
            ],
            "description": "Casting copies a master into another material: a printed part becomes a pattern, the pattern forms a mold, and the mold fills with resin, plaster, or molten metal. The rules are release and flow: the pattern must pull free, and the material must reach every corner, so sprues, vents, and draft angles do the work. The payoff is material choice, since one master casts in materials a printer cannot use. This short patterns the part, molds the cavity, and casts in anything.",
            "hashtags": ["#Casting", "#MoldMaking", "#CastingResin", "#3DPrinting"],
            "seo_keywords": [
                "cast from a printed master",
                "mold making from prints",
                "resin casting master",
                "cast metal from print",
                "pattern to cast guide",
                "casting sprue vent",
                "draft angle casting mold",
            ],
        },
        "fact_check": [
            "The print becomes the pattern.",
            "The pattern shapes the mold.",
            "Sprues and vents guide flow.",
            "Draft angles release the part.",
            "One master casts many materials.",
        ],
    },
    {
        "topic": "DMLS & LPBF",
        "core_question": "How do metal 3D printers build parts from powder?",
        "learning_objective": "The viewer understands DMLS and LPBF.",
        "engineering_summary": "DMLS and LPBF are the same family of metal printing: a laser sweeps a bed of metal powder and melts each cross-section, layer by layer, into a solid metal part, and the names differ mostly by vendor and marketing. The process needs real shielding: the build chamber floods with inert gas while the laser melts, because hot metal powder ignites in air. The part is born rough: support structures and a heat-treat and removal from the plate follow the build. Metal AM trades cost for geometry no mill can reach, like internal cooling channels in a turbine blade.",
        "real_world_application": "Aerospace and medical parts use LPBF for internal channels and lattices.",
        "common_misconceptions": [
            "DMLS and LPBF differ deeply (they are the same process)",
            "The part prints ready (it needs supports, heat treat, and removal)",
            "Air is fine in the chamber (inert gas protects the melt)",
        ],
        "teaching_strategy": "Show the powder bed and laser, then the post-build steps.",
        "script": "DMLS and LPBF are the same family of metal printing: a laser sweeps a bed of metal powder and melts each cross-section, layer by layer, into a solid metal part, and the names differ mostly by vendor and marketing. The process needs real shielding: the build chamber floods with inert gas while the laser melts, because hot metal powder ignites in air. The part is born rough: support structures and a heat-treat and removal from the plate follow the build. Metal AM trades cost for geometry no mill can reach, like internal cooling channels in a turbine blade.",
        "text_overlay": [
            "A LASER MELTS METAL POWDER",
            "THE SAME FAMILY, TWO NAMES",
            "INERT GAS PROTECTS THE MELT",
            "GEOMETRY NO MILL CAN REACH",
        ],
        "scenes": [
            {
                "goal": "Hook: the metal part",
                "teaching_point": "Powder became solid metal",
                "shot": "close-up shot of a rough LPBF metal part on its plate",
                "motion": "camera pans the layered surface",
                "lighting": "bright task light",
                "background": "production floor",
                "objects": ["metal part", "build plate", "rough surface"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a rough LPBF metal part on its build plate, bright task lighting, production floor",
            },
            {
                "goal": "The melt",
                "teaching_point": "Laser melts each layer",
                "shot": "diagram-style shot of the laser melting powder",
                "motion": "melt pool follows the beam",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["laser beam", "melt pool", "powder bed"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of the LPBF laser melting powder, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shield",
                "teaching_point": "Inert gas protects",
                "shot": "diagram-style shot of gas flooding the chamber",
                "motion": "inert flow wraps the melt zone",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gas flow", "melt zone", "chamber seal"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of inert gas shielding an LPBF chamber, clean engineering visualization on a dark background",
            },
            {
                "goal": "The born-rough",
                "teaching_point": "Supports, treat, remove",
                "shot": "diagram-style shot of the post-build steps",
                "motion": "supports detach, plate releases",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["support web", "heat treat", "plate removal"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of LPBF post-build steps, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Geometry no mill can reach",
                "shot": "wide hero shot of a finished LPBF part with internal channels",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["finished part", "internal channels", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a finished LPBF part with visible internal channels, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A laser melting metal powder in a shielded chamber with a rough part rising",
            "subject": "DMLS and LPBF",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "laser center, part below",
            "text": "GEOMETRY NO MILL CAN REACH",
            "elements": ["laser beam", "melt pool", "metal part"],
            "style": "geometry studio photography",
            "mood": "melted, shielded, printed",
            "prompt": "photograph of a laser melting metal powder in a shielded chamber with a rough part rising, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "DMLS & LPBF: Geometry No Mill Can Reach",
            "title_variations": [
                "How Metal 3D Printing Works",
                "DMLS vs LPBF",
                "Laser Powder Bed Fusion",
                "Metal AM Explained",
                "Metal Powder Printing",
            ],
            "description": "DMLS and LPBF are the same family of metal printing: a laser sweeps a bed of metal powder and melts each cross-section, layer by layer, into a solid metal part. The process needs inert gas shielding, because hot metal powder ignites in air. The part is born rough, with supports, heat treat, and plate removal following the build. This short melts the powder, shields the chamber, and shows geometry no mill can reach.",
            "hashtags": ["#DMLS", "#LPBF", "#MetalAM", "#3DPrinting"],
            "seo_keywords": [
                "how metal 3D printing works",
                "DMLS vs LPBF",
                "laser powder bed fusion",
                "metal AM explained",
                "metal powder printing",
                "metal 3D printing inert gas",
                "LPBF support removal",
            ],
        },
        "fact_check": [
            "DMLS and LPBF are the same family.",
            "The laser melts each layer.",
            "Inert gas shields the melt.",
            "Parts need post-build steps.",
            "Metal AM prints unmillable geometry.",
        ],
    },
]