"""Batch 16: g-code, data sheets, thermistors, overhangs, tapers, planetary gears, viscosity, and dividers."""

CURATED = [
    # ======================================================================
    {
        "topic": "G-Code Explained",
        "core_question": "What is G-code, and what are the printer commands doing?",
        "learning_objective": "The viewer can recognize common G-code commands and understand what the slicer produces.",
        "engineering_summary": "G-code is the language of your printer: a list of numbered commands the firmware executes line by line. G1 moves the nozzle, E values push filament, M commands control temperatures and fans. The slicer writes this program from your model, so every print is a file of thousands of tiny instructions. Reading the basics helps you diagnose: G28 homes the machine, and the end sequence parks the toolhead. You don't need to write G-code, but recognizing the commands tells you what the printer is doing and why. It's the translator between your model and the machine.",
        "real_world_application": "Start and end G-code scripts are edited by every user; diagnosis of homing, temperature, and retraction problems starts by reading the file.",
        "common_misconceptions": [
            "G-code is a proprietary format (it is a decades-old open standard)",
            "You must write G-code to use a printer (the slicer writes it for you)",
            "The print starts at the first move (start scripts home, heat, and purge first)",
        ],
        "teaching_strategy": "Show a G-code file, decode the common commands, then follow the script through a real print.",
        "script": "G-code is the language of your printer: a list of numbered commands the firmware executes line by line. G1 moves the nozzle, E values push filament, M commands control temperatures and fans. The slicer writes this program from your model, so every print is a file of thousands of tiny instructions. Reading the basics helps you diagnose: G28 homes the machine, and the end sequence parks the toolhead. You don't need to write G-code, but recognizing the commands tells you what the printer is doing and why. It's the translator between your model and the machine.",
        "text_overlay": [
            "G1 = MOVE, M = TEMP",
            "E VALUES = FILAMENT",
            "G28 = HOME",
            "SLICER WRITES THE SCRIPT",
        ],
        "scenes": [
            {
                "goal": "Hook: the code file",
                "teaching_point": "A print is a list of commands",
                "shot": "text editor shot of a G-code file scrolling",
                "motion": "lines scroll down the screen",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["g-code file", "text editor", "scrolling lines"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a G-code file scrolling in a text editor on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The commands",
                "teaching_point": "G1 moves, E pushes filament",
                "shot": "graphic-style shot of G-code lines annotated with meanings",
                "motion": "annotations light up per line",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["annotated code", "command meanings"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of annotated G-code lines with command meanings on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The start script",
                "teaching_point": "Home, heat, purge, print",
                "shot": "medium shot of a printer homing and purging at print start",
                "motion": "toolhead homes then purges filament",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["printer", "homing moves", "purge line"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printer homing and purging at the start of a print, bright task lighting, print lab",
            },
            {
                "goal": "The end script",
                "teaching_point": "Park the toolhead, off the part",
                "shot": "medium shot of a finished print with the toolhead parked",
                "motion": "toolhead lifts and parks",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["finished print", "parked toolhead"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a finished print with the toolhead parked high, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Recognize, don't write",
                "shot": "wide hero shot of a print running from its G-code file",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["running print", "screen with code"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a print running from its G-code file with the code on screen, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "G-code lines morphing into printer motion",
            "subject": "code lines above a printer",
            "background": "dark print lab blur",
            "angle": "graphic overlay",
            "lighting": "hard key with rim",
            "composition": "code top, printer below",
            "text": "G-CODE 101",
            "elements": ["g-code lines", "printer", "motion arrows"],
            "style": "software studio photography",
            "mood": "coded, literal, decoded",
            "prompt": "photograph of G-code lines overlaying a 3D printer with motion arrows, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "G-Code: The Printer's Language",
            "title_variations": [
                "What is G-Code",
                "G-Code Commands Explained",
                "Reading G-Code for Beginners",
                "How Slicers Write G-Code",
                "G1 and M Commands",
            ],
            "description": "G-code is the language of your printer: a list of numbered commands the firmware executes line by line. G1 moves the nozzle, E values push filament, M commands control temperatures and fans. The slicer writes this program from your model, so every print is a file of thousands of tiny instructions. Reading the basics helps you diagnose: G28 homes the machine, and the end sequence parks the toolhead. You don't need to write G-code, but recognizing the commands tells you what the printer is doing and why. It's the translator between your model and the machine.",
            "hashtags": ["#GCode", "#3Dprinting", "#Firmware", "#Basics"],
            "seo_keywords": [
                "what is g-code",
                "g-code commands explained",
                "reading g-code",
                "g1 g28 m commands",
                "how slicer writes g-code",
                "g-code for beginners",
                "3d printer code language",
            ],
        },
        "fact_check": [
            "G-code is an open standard command language for machine control.",
            "G1 moves axes; E values control extrusion; M commands control machine functions.",
            "Slicers generate G-code from the model and settings.",
            "Start scripts home, heat, and purge before printing.",
            "Recognizing common commands aids print diagnosis.",
        ],
    },
    # ======================================================================
    {
        "topic": "Material Data Sheets",
        "core_question": "How do I read a filament data sheet to compare materials?",
        "learning_objective": "The viewer can interpret key mechanical properties and derate them for printed parts.",
        "engineering_summary": "A material data sheet is the filament's report card: the numbers engineers use to compare materials. The big ones: tensile strength, how hard it pulls; modulus, how stiff; elongation at break, how far it stretches; and heat deflection temperature, how hot before sagging. Printed parts are always weaker than the sheet says - layers and voids cut the numbers, often by half. The sheet also lists drying and print temperature, the practical column that matters first. Read the sheet to pick the material, then derate the numbers for printing. The spec is a promise; printed reality is the verdict.",
        "real_world_application": "Engineering filament selection - nylon vs PC vs PETG - is decided on the data sheet before the first test print.",
        "common_misconceptions": [
            "Data sheet numbers are what printed parts achieve (layers and voids cut them roughly in half)",
            "Tensile strength alone ranks materials (stiffness and heat resistance matter for most jobs)",
            "All sheets measure the same way (test standards and conditions differ between brands)",
        ],
        "teaching_strategy": "Show a real data sheet, walk through each key row, then the derating rule for printed parts.",
        "script": "A material data sheet is the filament's report card: the numbers engineers use to compare materials. The big ones: tensile strength, modulus for stiffness, elongation at break for stretch, and heat deflection temperature for sagging. Printed parts are always weaker than the sheet says - layers and voids cut the numbers, often by half. The sheet also lists drying and print temperature, the practical column that matters first. Read the sheet to pick the material, then derate the numbers for printing. The spec is a promise; printed reality is the verdict.",
        "text_overlay": [
            "TENSILE + MODULUS + ELONGATION",
            "HDT = HEAT LIMIT",
            "PRINTS RUN ~HALF THE SPEC",
            "DERATE BEFORE YOU DESIGN",
        ],
        "scenes": [
            {
                "goal": "Hook: the spec table",
                "teaching_point": "The report card of the material",
                "shot": "close-up of a filament data sheet table on screen",
                "motion": "rows highlight across the table",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["data sheet", "property rows", "values"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a filament data sheet table with highlighted rows on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The properties",
                "teaching_point": "Strength, stiffness, stretch, heat",
                "shot": "graphic-style shot of property bars for tensile modulus and HDT",
                "motion": "bars fill per property",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["property bars", "material values"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of material property bars for tensile strength modulus and HDT on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The derating",
                "teaching_point": "Layers and voids cut the numbers",
                "shot": "macro shot of layer lines and voids in a printed test piece",
                "motion": "slow push-in on the layer structure",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["printed test piece", "layer lines", "voids"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of layer lines and voids in a printed test piece, raking side light, dark bench",
            },
            {
                "goal": "The practical column",
                "teaching_point": "Drying and print temperatures first",
                "shot": "data sheet shot with the print temperature row highlighted",
                "motion": "temperature row highlights",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["data sheet", "print temperature row"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a data sheet with the print temperature row highlighted on a dark screen, clean engineering visualization",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Spec is a promise, print is the verdict",
                "shot": "wide hero shot of an engineered part beside its material spool",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["engineered part", "material spool"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of an engineered part beside its filament spool, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A data sheet table beside a printed test coupon",
            "subject": "data sheet with test coupon",
            "background": "dark workshop blur",
            "angle": "three-quarter close-up",
            "lighting": "hard key with rim",
            "composition": "sheet left, coupon right",
            "text": "READ THE DATA SHEET",
            "elements": ["data sheet", "test coupon", "values"],
            "style": "materials studio photography",
            "mood": "tabulated, comparative, honest",
            "prompt": "photograph of a material data sheet beside a printed test coupon, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Data Sheets: Pick the Right Filament",
            "title_variations": [
                "How to Read Filament Data Sheets",
                "Tensile Strength vs Modulus",
                "HDT Explained for Prints",
                "Comparing Engineering Filaments",
                "Filament Specs Decoded",
            ],
            "description": "A material data sheet is the filament's report card: the numbers engineers use to compare materials. The big ones: tensile strength, how hard it pulls; modulus, how stiff; elongation at break, how far it stretches; and heat deflection temperature, how hot before sagging. Printed parts are always weaker than the sheet says - layers and voids cut the numbers, often by half. The sheet also lists drying and print temperature, the practical column that matters first. Read the sheet to pick the material, then derate the numbers for printing. The spec is a promise; printed reality is the verdict.",
            "hashtags": ["#DataSheets", "#Filament", "#Materials", "#Engineering"],
            "seo_keywords": [
                "how to read filament data sheets",
                "tensile strength vs modulus",
                "heat deflection temperature HDT",
                "engineering filament comparison",
                "filament specs explained",
                "derating printed parts",
                "material data sheet 3d printing",
            ],
        },
        "fact_check": [
            "Data sheets list tensile strength, modulus, elongation, and HDT.",
            "Printed parts typically achieve roughly half the sheet's mechanical values.",
            "Layer lines and voids weaken printed parts versus molded samples.",
            "Drying and print temperatures are the practical starting columns.",
            "Test standards and conditions vary between manufacturers.",
        ],
    },
    # ======================================================================
    {
        "topic": "Thermistor Readings",
        "core_question": "How does my printer measure nozzle temperature, and why does it lie?",
        "learning_objective": "The viewer can explain thermistor behavior, common failure modes, and verification checks.",
        "engineering_summary": "Thermistors are your hotend's temperature sensors: a resistor whose resistance drops steeply as it warms. The firmware reads that resistance and converts it to temperature using a calibration curve - the 100K NTC thermistor is the standard. The catch: thermistors are not linear, so the curve matters, and a loose wire reads as wild swings. A thermistor that reads cold overheats the nozzle, burning filament and jamming; one that reads hot prints too cold and weak. The checks: verify it reads room temperature when cold, and confirm the right thermistor type in firmware. Trust the sensor, but verify it.",
        "real_world_application": "Thermal runaway protection relies on the thermistor; a bad sensor is the first suspect when temperatures swing or prints under- or overheat.",
        "common_misconceptions": [
            "Temperature readings are exact (thermistor error of several degrees is normal)",
            "Any thermistor works with any board (the firmware curve must match the sensor type)",
            "A swinging reading means the heater is bad (loose wires read as swings)",
        ],
        "teaching_strategy": "Show the resistance curve, the cold-read and hot-read failure modes, then the verification routine.",
        "script": "Thermistors are your hotend's temperature sensors: a resistor whose resistance drops as it warms. Firmware reads that resistance and converts it to temperature with a calibration curve; the 100K NTC thermistor is standard. The catch: thermistors are not linear, so the curve matters, and a loose wire reads as wild swings. A thermistor that reads cold overheats the nozzle, burning filament and jamming; one that reads hot prints too cold and weak. Check it reads room temperature when cold, and confirm the right thermistor type in firmware. Trust the sensor, but verify it.",
        "text_overlay": [
            "RESISTANCE DROPS AS IT WARMS",
            "CURVE = TEMPERATURE",
            "LOOSE WIRE = WILD SWINGS",
            "COLD READ = OVERHEAT",
        ],
        "scenes": [
            {
                "goal": "Hook: the swinging temp",
                "teaching_point": "Wild swings mean a bad connection",
                "shot": "screen shot of a temperature graph swinging wildly",
                "motion": "temp line swings across the graph",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["temperature graph", "swinging line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a wildly swinging temperature graph on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The sensor",
                "teaching_point": "Resistance falls with heat",
                "shot": "macro shot of a thermistor bead in a heater block",
                "motion": "slow push-in on the bead",
                "lighting": "bright task light",
                "background": "dark bench",
                "objects": ["thermistor", "heater block", "wires"],
                "transition": "cut",
                "duration": 6,
                "prompt": "macro photograph of a thermistor bead in a hotend heater block, bright task light, dark bench",
            },
            {
                "goal": "The curve",
                "teaching_point": "Not linear, curve matters",
                "shot": "graphic-style shot of the thermistor resistance-temperature curve",
                "motion": "curve sweeps steeply downward",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["resistance curve", "temperature axis"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a thermistor resistance temperature curve on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The failure modes",
                "teaching_point": "Cold read overheats, hot read weakens",
                "shot": "tabletop shot of a burned filament jam and a weak cold print",
                "motion": "pan between the two failures",
                "lighting": "neutral lab light",
                "background": "test bench",
                "objects": ["burned jam", "weak print"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a burned filament jam and a weak print from thermistor errors, neutral lab lighting, test bench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Verify the sensor",
                "shot": "wide hero shot of a hotend with a verified steady temperature reading",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["hotend", "steady temperature screen"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a hotend with a steady temperature reading on screen, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A thermistor bead with a resistance curve behind it",
            "subject": "thermistor with curve overlay",
            "background": "dark print lab blur",
            "angle": "macro close-up",
            "lighting": "hard key with rim",
            "composition": "bead center, curve behind",
            "text": "THERMISTORS",
            "elements": ["thermistor bead", "resistance curve"],
            "style": "sensor macro photography",
            "mood": "thermal, curved, verified",
            "prompt": "macro photograph of a thermistor bead with a resistance curve overlay, hard key light with rim, dark print lab, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Thermistors: Why Temps Lie",
            "title_variations": [
                "How Hotend Thermistors Work",
                "Temperature Reading Problems",
                "Thermistor Curve Explained",
                "Loose Thermistor Wire Fix",
                "Verify Nozzle Temperature",
            ],
            "description": "Thermistors are your hotend's temperature sensors: a resistor whose resistance drops steeply as it warms. The firmware reads that resistance and converts it to temperature using a calibration curve - the 100K NTC thermistor is the standard. The catch: thermistors are not linear, so the curve matters, and a loose wire reads as wild temperature swings. A thermistor that reads cold overheats the nozzle, burning filament and jamming; one that reads hot prints too cold and weak. The checks: verify the sensor reads room temperature when cold, and confirm the correct thermistor type in firmware. Trust the sensor, but verify it.",
            "hashtags": ["#Thermistor", "#Hotend", "#Electronics", "#Troubleshooting"],
            "seo_keywords": [
                "how thermistors work",
                "hotend temperature sensor",
                "thermistor curve",
                "temperature swings printer",
                "100k ntc thermistor",
                "verify nozzle temperature",
                "thermal runaway thermistor",
            ],
        },
        "fact_check": [
            "Thermistors are resistors whose resistance drops steeply with temperature.",
            "Firmware converts resistance to temperature with a calibration curve.",
            "The 100K NTC thermistor is the common 3D printer standard.",
            "Loose thermistor wires cause wild temperature readings.",
            "A cold-reading thermistor causes overheating; a hot-reading one causes weak prints.",
        ],
    },
    # ======================================================================
    {
        "topic": "Overhangs & Sagging",
        "core_question": "Why do overhangs sag, and how far can a printer overhang?",
        "learning_objective": "The viewer can explain the overhang limit and fix sagging with speed, cooling, and orientation.",
        "engineering_summary": "An overhang is any surface that slopes outward: plastic that must bridge air until it meets the layer below. Up to about 45 degrees, printers handle overhangs cleanly; steeper, and layers droop and sag without support underneath. The classic fixes: slower speeds give the layer time to cool, higher part cooling hardens it faster, and lower layer heights cut how far each layer sticks out. Orientation matters too - rotate the part so the worst overhang becomes a vertical wall. Beyond the limit, add supports or redesign with a chamfer. Sagging means the geometry outran the physics.",
        "real_world_application": "Model faces, lettering, and angled brackets all contain overhangs; the 45-degree rule guides design for printing without supports.",
        "common_misconceptions": [
            "Overhang quality is purely cooling (speed, layer height, and orientation also decide it)",
            "Any angle prints fine slowly (past a material-dependent limit, layers sag regardless)",
            "Supports are the only fix (orientation and design solve most overhangs)",
        ],
        "teaching_strategy": "Show the sagging layers, the angle limit, then the speed and cooling fixes and the orientation trick.",
        "script": "An overhang is any surface that slopes outward: plastic that must bridge air until it meets the layer below. Up to about 45 degrees, printers handle overhangs cleanly; steeper, and layers droop and sag without support underneath. The classic fixes: slower speeds give the layer time to cool, higher part cooling hardens it faster, and lower layer heights cut how far each layer sticks out. Orientation matters too - rotate the part so the worst overhang becomes a vertical wall. Beyond the limit, add supports or redesign with a chamfer. Sagging means the geometry outran the physics.",
        "text_overlay": [
            "~45° = THE LIMIT",
            "SLOWER + COOLER + THINNER",
            "ROTATE THE WORST ANGLE",
            "PAST THE LIMIT: SUPPORTS",
        ],
        "scenes": [
            {
                "goal": "Hook: the sagging face",
                "teaching_point": "Drooping layers under an angle",
                "shot": "macro shot of a sagging overhang surface",
                "motion": "slow push-in on the drooping layers",
                "lighting": "raking side light",
                "background": "dark bench",
                "objects": ["sagging overhang", "drooping layers"],
                "transition": "cut",
                "duration": 5,
                "prompt": "macro photograph of a sagging overhang surface on a print, raking side light, dark bench",
            },
            {
                "goal": "The angle rule",
                "teaching_point": "Forty-five degrees clean, steeper sags",
                "shot": "graphic-style shot of angle markers on an overhang profile",
                "motion": "angles mark the limit on the profile",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["overhang profile", "angle markers"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of overhang angle markers on a profile diagram on a dark screen, clean engineering visualization",
            },
            {
                "goal": "The fixes",
                "teaching_point": "Speed, cooling, layer height",
                "shot": "medium shot of a printer printing an overhang with tuned cooling",
                "motion": "layers cool and hold the angle",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["tuned print", "cooling fan", "overhang"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a printer printing an overhang with tuned cooling, bright task lighting, print lab",
            },
            {
                "goal": "The orientation",
                "teaching_point": "Rotate the worst angle vertical",
                "shot": "tabletop shot of a part rotated on the build plate",
                "motion": "part rotates until the angle faces up",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["part", "build plate", "rotation"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a part being rotated on a build plate to avoid an overhang, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Design the angle away",
                "shot": "wide hero shot of a clean angled part printing without supports",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean angled part", "no supports"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean angled part printing without supports, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "An overhang profile with a 45-degree marker and droop zone",
            "subject": "overhang profile with angle marker",
            "background": "dark workshop blur",
            "angle": "profile view",
            "lighting": "hard key with rim",
            "composition": "profile center, angle marked",
            "text": "OVERPANGES 101",
            "elements": ["overhang profile", "45 degree mark", "droop zone"],
            "style": "geometry studio photography",
            "mood": "angled, drooping, fixable",
            "prompt": "photograph of an overhang profile with a 45 degree marker and droop zone, hard key light with rim, dark workshop, 9:16 vertical composition, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Overhangs: The 45-Degree Rule",
            "title_variations": [
                "Why Overhangs Sag",
                "Overhang Angle Limits",
                "Fix Sagging Layers",
                "Printing Overhangs Without Supports",
                "45 Degree Rule 3D Printing",
            ],
            "description": "An overhang is any surface that slopes outward: plastic that must bridge air until it meets the layer below. Up to about 45 degrees, printers handle overhangs cleanly; steeper, and layers droop and sag without support underneath. The classic fixes: slower speeds give the layer time to cool, higher part cooling hardens it faster, and lower layer heights cut how far each layer sticks out. Orientation matters too - rotate the part so the worst overhang becomes a vertical wall. Beyond the limit, add supports or redesign with a chamfer. Sagging means the geometry outran the physics.",
            "hashtags": ["#Overhangs", "#3Dprinting", "#Design", "#Tips"],
            "seo_keywords": [
                "why overhangs sag",
                "overhang angle limit",
                "45 degree rule printing",
                "fix sagging print layers",
                "print overhangs without supports",
                "overhang cooling speed",
                "part orientation overhang",
            ],
        },
        "fact_check": [
            "Overhangs beyond about 45 degrees sag without support.",
            "Slower speeds, stronger cooling, and thinner layers improve overhang quality.",
            "Rotating the part can convert an overhang into a vertical wall.",
            "Supports or chamfer redesigns handle extreme overhangs.",
            "The usable overhang angle varies with material and settings.",
        ],
    },
    {
        "topic": "Draft Angles & Tapers",
        "core_question": "Why do walls lean, and when does a taper matter?",
        "learning_objective": "The viewer understands what draft angle is, why molds need it, and when printing benefits from a taper.",
        "engineering_summary": "Draft angle is the slight taper on a part wall that lets it release cleanly from a mold. Injection molded parts lean every wall back one to two degrees, or plastic locks around the tool and tears. Tapers appear everywhere: bottle caps, gear hubs, and battery compartments. In printing, draft matters when parts must slide or snap together, and tapers ease press fits and assembly. Draft is not sloppiness: even half a degree changes ejection force dramatically. When you design parts that must release from a tool or mate with another, check every vertical wall. Geometry that cannot release is geometry that binds.",
        "real_world_application": "Molded products, snap-fit cases, and press-fit parts all rely on draft; printed parts use tapers to ease sliding fits.",
        "common_misconceptions": [
            "Draft is a flaw (it is a deliberate release feature)",
            "Only molds need draft (sliding fits in printed parts benefit too)",
            "Steeper draft is always better (too much draft changes the fit)",
        ],
        "teaching_strategy": "Show a mold diagram with tapered walls, then a printed part with a taper that slides freely.",
        "script": "Draft angle is the slight taper on a part wall that lets it release from a mold. Injection molded parts lean every wall back one to two degrees, or plastic locks around the tool and tears. Tapers are everywhere: bottle caps, gear hubs, battery compartments. In printing, draft matters when parts slide or snap together; tapers ease press fits. Draft is not sloppiness: even half a degree changes ejection force. When you design parts that must release from a tool, check every vertical wall. Geometry that cannot release is geometry that binds.",
        "text_overlay": [
            "WALLS LEAN 1-2 DEGREES",
            "RELEASE ANGLE",
            "TAPER = SLIDES FREE",
            "CHECK EVERY VERTICAL WALL",
        ],
        "scenes": [
            {
                "goal": "Hook: the tapered wall",
                "teaching_point": "Molds lean walls to release",
                "shot": "diagram-style shot of a mold cross section with tapered walls",
                "motion": "walls highlight and pull apart",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["mold cross section", "tapered walls"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a mold cross section with tapered walls pulling apart, clean engineering visualization on a dark background",
            },
            {
                "goal": "The numbers",
                "teaching_point": "One to two degrees frees the part",
                "shot": "graphic-style shot of a wall with a degree marker",
                "motion": "angle marker sweeps in",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["wall section", "angle marker"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a part wall with a draft angle marker, clean engineering visualization on a dark background",
            },
            {
                "goal": "Real products",
                "teaching_point": "Bottles, hubs, battery cases",
                "shot": "medium shot of everyday molded parts on a workbench",
                "motion": "parts turn to show tapered walls",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["bottle cap", "gear hub", "battery compartment"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of molded parts with draft angles on a workbench, neutral lab lighting",
            },
            {
                "goal": "Printed fits",
                "teaching_point": "Tapers ease sliding parts",
                "shot": "close-up shot of printed parts sliding together",
                "motion": "parts slide smoothly",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["printed parts", "sliding fit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of printed parts sliding together with a taper fit, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Geometry that cannot release binds",
                "shot": "wide hero shot of a release check on a part",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["release angle check", "part"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part with a marked release angle, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A mold wall leaning back with a draft angle marker and a part releasing",
            "subject": "tapered mold wall with angle marker",
            "background": "dark workshop blur",
            "angle": "profile view",
            "lighting": "hard key with rim",
            "composition": "wall profile center, marker at the lean",
            "text": "DRAFT ANGLES 101",
            "elements": ["tapered wall", "angle marker", "releasing part"],
            "style": "geometry studio photography",
            "mood": "smooth, releasing, deliberate",
            "prompt": "photograph of a mold wall leaning back with a draft angle marker and a part releasing, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Draft Angles: Why Molded Walls Lean",
            "title_variations": [
                "What Is Draft Angle",
                "Tapers in Mold Design",
                "Why Parts Need Draft",
                "Draft Angle for 3D Printing",
                "Release Angles Explained",
            ],
            "description": "Draft angle is the deliberate taper on a part wall that lets it release cleanly from a mold: typically one to two degrees per side, enough to break the vacuum grip and avoid tearing plastic. Every bottle cap, gear hub, and battery compartment leans slightly for this reason. The same idea applies to printed parts: tapers ease sliding fits, press fits, and parts that snap together, and they reduce friction between mating surfaces. Too little draft binds the part; too much draft changes the fit. This short explains where draft comes from, how much you need, and how to check your own designs for walls that will lock.",
            "hashtags": ["#DraftAngle", "#MoldDesign", "#3Dprinting", "#CAD"],
            "seo_keywords": [
                "what is draft angle",
                "draft angle mold design",
                "taper part design",
                "release angle 3d printing",
                "why parts need draft",
                "snap fit taper",
                "press fit draft angle",
            ],
        },
        "fact_check": [
            "Typical draft is one to two degrees per side.",
            "Draft lets molded parts release without tearing.",
            "Tapers ease sliding and press fits in printed parts.",
            "Too little draft binds the part; too much changes the fit.",
            "Every vertical wall that mates with a tool or part deserves a draft check.",
        ],
    },
    {
        "topic": "Planetary Gears",
        "core_question": "Why do drill gearboxes pack so much reduction into so little space?",
        "learning_objective": "The viewer understands the sun, ring, and carrier, and why planetary gears carry more load.",
        "engineering_summary": "A planetary gearset puts a sun gear, a ring gear, and planets spinning between them. Power can enter the sun, the ring, or the carrier, and each input gives a different ratio, including reverse and direct drive. That compactness is why planetary gears live in drills, automatic transmissions, and robot joints. The load splits across several planet teeth, so the set carries more torque than a pair of gears the same size. Staging several sets multiplies the ratios. When a mechanism needs a big reduction in a small space, planetary gears are usually the answer.",
        "real_world_application": "Drill chucks, automatic gearboxes, robot joints, and winches use planetary stages for compact high-torque reduction.",
        "common_misconceptions": [
            "Planetary gears need more space (they pack the most reduction per volume)",
            "There is one fixed ratio (every input and output choice gives a new ratio)",
            "Planet gears carry the load alone (the load spreads across all planet teeth)",
        ],
        "teaching_strategy": "Show a cutaway gearset, trace the power paths, then count the ratio options.",
        "script": "A planetary gearset puts a sun gear, a ring gear, and planets spinning between them. Power can enter the sun, the ring, or the carrier, and each input gives a different ratio, including reverse and direct drive. That compactness is why planetary gears live in drills, automatic transmissions, and robot joints. The load splits across several planet teeth, so the set carries more torque than a pair of gears the same size. Staging several sets multiplies the ratios. When a mechanism needs a big reduction in a small space, planetary gears are the answer.",
        "text_overlay": [
            "SUN + RING + PLANETS",
            "POWER PATH = RATIO",
            "LOAD SPLITS ACROSS TEETH",
            "STAGE SETS TO MULTIPLY",
        ],
        "scenes": [
            {
                "goal": "Hook: the gearset",
                "teaching_point": "Three parts: sun, ring, planets",
                "shot": "diagram-style cutaway of a planetary gearset rotating",
                "motion": "planets orbit slowly",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["sun gear", "ring gear", "planet gears"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a cutaway planetary gearset with orbiting planet gears, clean engineering visualization on a dark background",
            },
            {
                "goal": "Power paths",
                "teaching_point": "Input choice sets the ratio",
                "shot": "graphic-style shot of the gearset with input arrows",
                "motion": "arrows trace sun, ring, and carrier paths",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["gearset", "input arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a planetary gearset with input arrows tracing power paths, clean engineering visualization on a dark background",
            },
            {
                "goal": "Real machines",
                "teaching_point": "Drills, transmissions, robot joints",
                "shot": "medium shot of a cordless drill cutaway and gearbox",
                "motion": "gearbox stages rotate",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["drill", "gearbox", "planetary stages"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a cordless drill gearbox with planetary stages on a workbench, neutral lab lighting",
            },
            {
                "goal": "Load sharing",
                "teaching_point": "Teeth split the torque",
                "shot": "close-up shot of planet gears engaging the ring",
                "motion": "slow rotation of the mesh",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["planet gears", "ring gear", "contact points"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of planet gears engaging a ring gear, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Big reduction, small space",
                "shot": "wide hero shot of the gearset in a cut housing",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["planetary gearset", "cut housing"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a planetary gearset in a cut housing, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A cutaway planetary gearset with sun, ring, and planets marked",
            "subject": "planetary gearset cutaway",
            "background": "dark workshop blur",
            "angle": "front view",
            "lighting": "hard key with rim",
            "composition": "gearset center, labels on each part",
            "text": "PLANETARY GEARS",
            "elements": ["sun gear", "ring gear", "planet gears", "labels"],
            "style": "geometry studio photography",
            "mood": "compact, mechanical, powerful",
            "prompt": "photograph of a cutaway planetary gearset with sun ring and planet gears labeled in a cut housing, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Planetary Gears: Big Reduction, Small Space",
            "title_variations": [
                "How Planetary Gears Work",
                "Sun Ring Planet Explained",
                "Why Drills Use Planetary Gears",
                "Planetary Gearbox Ratios",
                "Epicyclic Gears 101",
            ],
            "description": "Planetary gears are the most compact way to get a large speed reduction: a sun gear, a ring gear, and planets spinning between them all share one housing. Power can enter the sun, the ring, or the carrier, and each choice produces a different ratio, including reverse and direct drive. Because the load spreads across several planet teeth at once, a planetary stage carries more torque than a simple pair of gears the same size. This is why drills, automatic transmissions, and robot joints all use them. This short breaks down the parts, the power paths, and how to pick a ratio, with cutaways and real gearboxes.",
            "hashtags": ["#PlanetaryGears", "#Gears", "#Engineering", "#MechanicalDesign"],
            "seo_keywords": [
                "how planetary gears work",
                "sun ring planet gears",
                "planetary gearbox ratio",
                "why drills use planetary gears",
                "epicyclic gearset explained",
                "planetary gear torque",
                "compact gear reduction",
            ],
        },
        "fact_check": [
            "A planetary set has a sun gear, a ring gear, and planets on a carrier.",
            "Each input-output choice yields a different ratio, including reverse.",
            "Load splits across the planet teeth, increasing torque capacity.",
            "Staging multiple sets multiplies the reduction.",
            "Planetary gears give the most reduction per volume of any common gearbox.",
        ],
    },
    {
        "topic": "Viscosity",
        "core_question": "What makes oil thick, and why does temperature matter?",
        "learning_objective": "The viewer can explain viscosity, its units, and why temperature and pressure matter for real fluids.",
        "engineering_summary": "Viscosity is a fluid's resistance to flow: its internal thickness. Honey pours slowly; water pours fast. Engineers measure it in centipoise, and it changes sharply with temperature: warm oil flows far more freely than cold oil. Viscosity decides how grease spreads, how paint levels, and how a pump behaves. High-viscosity fluids need more pressure to push through a line, and thicker films carry more load in bearings. In printing, molten plastic viscosity controls extrusion and bridging. Pick the fluid for the job, and watch the temperature, because viscosity never stays still.",
        "real_world_application": "Oil grades, grease selection, pump sizing, paint application, and filament extrusion all depend on viscosity and its temperature behavior.",
        "common_misconceptions": [
            "Viscosity is a fixed property (it changes sharply with temperature)",
            "Thicker always means better (too thick starves bearings and pumps)",
            "Pressure does not matter (high pressure can freeze some fluids)",
        ],
        "teaching_strategy": "Compare honey and water, show the centipoise scale, then trace viscosity through a bearing and a pump.",
        "script": "Viscosity is a fluid's resistance to flow: its internal thickness. Honey pours slowly; water pours fast. Engineers measure it in centipoise, and it changes sharply with temperature: warm oil flows far more freely than cold oil. Viscosity decides how grease spreads, how paint levels, and how a pump behaves. High-viscosity fluids need more pressure to push through a line, and thicker films carry more load in bearings. Molten plastic viscosity controls extrusion and bridging in printing. Pick the fluid for the job, and watch the temperature: viscosity never stays still.",
        "text_overlay": [
            "RESISTANCE TO FLOW",
            "MEASURED IN CENTIPOISE",
            "HEAT THINS EVERYTHING",
            "PICK THE FLUID FOR THE JOB",
        ],
        "scenes": [
            {
                "goal": "Hook: thick versus thin",
                "teaching_point": "Honey pours slowly, water pours fast",
                "shot": "medium shot of honey and water being poured",
                "motion": "slow pour side by side",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["honey", "water", "pouring"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of honey and water pouring side by side, neutral lab lighting, workbench",
            },
            {
                "goal": "The scale",
                "teaching_point": "Centipoise numbers rank thickness",
                "shot": "graphic-style shot of a viscosity scale with fluids",
                "motion": "fluids slide onto the scale",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["viscosity scale", "fluid samples"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a viscosity scale chart with fluid samples, clean engineering visualization on a dark background",
            },
            {
                "goal": "Temperature",
                "teaching_point": "Heat thins oil dramatically",
                "shot": "close-up shot of cold and warm oil flowing from bottles",
                "motion": "side-by-side flows",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["cold oil", "warm oil", "flow"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of cold and warm oil flowing from bottles side by side, bright task lighting, print lab",
            },
            {
                "goal": "Machines",
                "teaching_point": "Thickness decides bearings, pumps, paint",
                "shot": "medium shot of a bearing and a gear pump in a lab",
                "motion": "bearing rotates through the film",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["bearing", "gear pump", "oil film"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a bearing and gear pump with an oil film in a lab, neutral lab lighting, workbench",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Match the fluid, watch the temperature",
                "shot": "wide hero shot of oiling a machine with a temperature gauge",
                "motion": "slow push in",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["oil", "machine", "temperature gauge"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of oiling a machine with a temperature gauge, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Honey and water pouring with a centipoise scale behind them",
            "subject": "two pours with viscosity scale",
            "background": "dark workshop blur",
            "angle": "side angle",
            "lighting": "hard key with rim",
            "composition": "two streams center, scale behind",
            "text": "VISCOSITY 101",
            "elements": ["honey pour", "water pour", "centipoise scale"],
            "style": "fluid studio photography",
            "mood": "thick, flowing, measurable",
            "prompt": "photograph of honey water and oil pouring slowly with a centipoise scale behind them on a lab bench, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Viscosity: Why Oil Thickness Matters",
            "title_variations": [
                "What Is Viscosity",
                "Why Oil Gets Thinner When Hot",
                "Centipoise Explained",
                "Thick Fluids and Pumps",
                "Viscosity for Engineering",
            ],
            "description": "Viscosity is a fluid's internal resistance to flow: honey resists, water barely does. Engineers rank fluids in centipoise, and the numbers matter because viscosity is not fixed: warm oil flows freely, cold oil thickens into syrup, and pressure changes the behavior too. That temperature swing decides which oil grade you need, how a pump behaves, how paint levels on a wall, and how grease stays in a bearing. Pick a fluid that is too thick and it starves pumps and bearings; too thin and it drains away and fails to protect. This short shows the pour test, the scale, and the machines that depend on it.",
            "hashtags": ["#Viscosity", "#Fluids", "#Engineering", "#Oil"],
            "seo_keywords": [
                "what is viscosity",
                "viscosity in centipoise",
                "why oil thins when hot",
                "viscosity temperature effect",
                "thick fluid pumps",
                "bearing oil film",
                "fluid resistance explained",
            ],
        },
        "fact_check": [
            "Viscosity is a fluid's resistance to flow.",
            "It is measured in centipoise and changes sharply with temperature.",
            "Warm fluids flow far more freely than cold ones.",
            "High-viscosity fluids need more pressure to push through a line.",
            "Thicker films carry more load in bearings, but too much thickness starves machines.",
        ],
    },
    {
        "topic": "Voltage Dividers",
        "core_question": "How do two resistors shrink a voltage?",
        "learning_objective": "The viewer can compute a divider ratio and knows why loading destroys the output.",
        "engineering_summary": "A voltage divider splits a supply into a smaller voltage using two resistors in series. The output sits between them, and its value follows the ratio of the resistors, not their size. Need five volts from twelve? Pick the right pair. The catch: any load attached to the output changes the division, so dividers only feed tiny currents like sensor signals and reference voltages. They are everywhere: thermistor circuits, potentiometers, and volume knobs are dividers in disguise. Knowing the ratio shows how sensors talk to microcontrollers, and why a wrong resistor ruins a calibration.",
        "real_world_application": "Thermistor readouts, potentiometer controls, sensor scaling, and ADC reference circuits all depend on divider ratios.",
        "common_misconceptions": [
            "Bigger resistors drop more voltage (it is the ratio, not the size)",
            "You can power things from a divider (any real load shifts the ratio)",
            "Dividers are complex (a potentiometer is just a variable divider)",
        ],
        "teaching_strategy": "Draw two resistors, solve the ratio with real numbers, then add a load and watch the output collapse.",
        "script": "A voltage divider splits a supply into a smaller voltage using two resistors in series. The output sits between them, and its value follows the ratio of the resistors, not their size. Need five volts from twelve? Pick the right pair. The catch: any load attached to the output changes the division, so dividers only feed currents like sensor signals and reference voltages. They are everywhere: thermistor circuits, potentiometers, and volume knobs are dividers in disguise. Knowing the ratio shows how sensors talk to microcontrollers, and why a wrong resistor ruins a calibration.",
        "text_overlay": [
            "RATIO, NOT SIZE",
            "V OUT BETWEEN THE PAIR",
            "LOAD? THE OUTPUT MOVES",
            "SENSORS TALK THROUGH DIVIDERS",
        ],
        "scenes": [
            {
                "goal": "Hook: two resistors",
                "teaching_point": "A divider is two resistors in series",
                "shot": "diagram-style shot of a divider circuit lighting up",
                "motion": "voltage traces through the pair",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["two resistors", "circuit diagram", "voltage trace"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a two resistor voltage divider circuit diagram with a voltage trace, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ratio",
                "teaching_point": "Output follows the ratio, not size",
                "shot": "graphic-style shot of the divider with numbers",
                "motion": "ratio values appear at the output",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["divider", "resistor values", "output number"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a voltage divider with resistor values and the computed output, clean engineering visualization on a dark background",
            },
            {
                "goal": "The catch",
                "teaching_point": "Loading the output changes the split",
                "shot": "medium shot of a divider on a breadboard with a meter",
                "motion": "meter reading drops as a load connects",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["breadboard", "divider", "multimeter", "load"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a voltage divider on a breadboard with a multimeter reading, bright task lighting, print lab",
            },
            {
                "goal": "Hidden dividers",
                "teaching_point": "Thermistors, knobs, and sensors",
                "shot": "close-up shot of a thermistor circuit and a potentiometer",
                "motion": "knob turns and the reading changes",
                "lighting": "neutral lab light",
                "background": "workbench",
                "objects": ["thermistor", "potentiometer", "sensor circuit"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a thermistor circuit and potentiometer on a workbench, neutral lab lighting",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Ratio in, scaled voltage out",
                "shot": "wide hero shot of a divider feeding a microcontroller pin",
                "motion": "signal trace climbs and holds",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["divider", "microcontroller", "signal trace"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a voltage divider feeding a microcontroller, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Two resistors in series with the output node glowing between them",
            "subject": "divider circuit with glowing output",
            "background": "dark workshop blur",
            "angle": "top down",
            "lighting": "hard key with rim",
            "composition": "circuit center, output node highlighted",
            "text": "VOLTAGE DIVIDERS",
            "elements": ["two resistors", "output node", "circuit board"],
            "style": "geometry studio photography",
            "mood": "small, precise, split",
            "prompt": "photograph of two resistors in series with a glowing output node between them on a circuit board, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Voltage Dividers: Two Resistors, One Ratio",
            "title_variations": [
                "How Voltage Dividers Work",
                "Resistor Divider Formula",
                "Why Dividers Can't Power Things",
                "Voltage Divider for Sensors",
                "Ratio Circuits Explained",
            ],
            "description": "A voltage divider is the simplest way to make a smaller voltage: two resistors in series, with the output taken from the middle. The output follows the ratio of the two resistors, so the pair's absolute size barely matters. Five volts from twelve takes the same ratio as five millivolts from twelve millivolts. The catch is that any current drawn from the output changes the division, which is why dividers only feed high-impedance loads like sensor pins and reference inputs. Thermistor circuits, potentiometers, and volume knobs are all dividers in disguise. This short walks through the formula, the loading trap, and where dividers hide in your electronics.",
            "hashtags": ["#VoltageDivider", "#Electronics", "#Circuits", "#Sensors"],
            "seo_keywords": [
                "how voltage dividers work",
                "voltage divider formula",
                "resistor ratio circuit",
                "why dividers can't power loads",
                "divider for sensor signals",
                "potentiometer as divider",
                "thermistor divider circuit",
            ],
        },
        "fact_check": [
            "A divider is two resistors in series with the output between them.",
            "The output depends on the ratio of the resistors, not their size.",
            "Any load attached to the output changes the division.",
            "Dividers suit sensor signals and reference voltages, not power.",
            "Thermistors and potentiometers are dividers in disguise.",
        ],
    },
]