"""Batch 31: baseline profiles, first-layer tests, flow, mesh leveling, elephant foot, bridges, supports, linear advance."""

CURATED = [
    # ======================================================================
    {
        "topic": "Baseline Profile Setup",
        "core_question": "Where do you start when nothing prints right?",
        "learning_objective": "The viewer understands why a saved baseline profile is essential.",
        "engineering_summary": "A baseline profile is a saved snapshot of settings that you know print well, captured while the machine is healthy: flow, temperature, speeds, retraction, and the g-code start sequence. When a print suddenly goes wrong, the first move is not to retune everything, it is to compare against the baseline and find the one changed variable. Save the good profile before you need it, because troubleshooting needs a reference point.",
        "real_world_application": "Every serious profile collection starts from one known-good baseline.",
        "common_misconceptions": [
            "Tuning is always forward (you need a reference to compare)",
            "Profiles are for sharing only (your machine needs its own)",
            "Defaults are the baseline (the baseline is your tuned state)",
        ],
        "teaching_strategy": "Show a printer failing, then restoring a saved profile.",
        "script": "A baseline profile is a saved snapshot of settings that you know print well, captured while the machine is healthy: flow, temperature, speeds, retraction, and the g-code start sequence. When a print suddenly goes wrong, the first move is not to retune everything, it is to compare against the baseline and find the one changed variable. Save the good profile before you need it, because troubleshooting needs a reference point.",
        "text_overlay": [
            "SAVE THE GOOD STATE",
            "TROUBLESHOOTING NEEDS A REFERENCE",
            "FIND THE ONE CHANGED VARIABLE",
            "BACKUP BEFORE YOU NEED IT",
        ],
        "scenes": [
            {
                "goal": "Hook: the mystery failure",
                "teaching_point": "Something changed",
                "shot": "medium shot of a failing print on a printer",
                "motion": "camera zooms to the fault",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["failing print", "printer", "fault line"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a failing print on a printer, neutral lab lighting, print lab",
            },
            {
                "goal": "The snapshot",
                "teaching_point": "Known-good settings saved",
                "shot": "diagram-style shot of a profile card with settings",
                "motion": "flow, temp, speed list and lock",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["profile card", "settings list", "save state"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a saved baseline profile, clean engineering visualization on a dark background",
            },
            {
                "goal": "The compare",
                "teaching_point": "Diff against the baseline",
                "shot": "diagram-style shot of two settings side by side",
                "motion": "one changed value highlights",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["baseline list", "current list", "changed value"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of comparing settings to a baseline, clean engineering visualization on a dark background",
            },
            {
                "goal": "The restore",
                "teaching_point": "One changed variable fixed",
                "shot": "medium shot of a clean print finishing",
                "motion": "profile restores, print comes clean",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["restored profile", "clean print", "printer"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a clean print finishing after a profile restore, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Save before you need it",
                "shot": "wide hero shot of a printer with a backup drive beside",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["printer", "backup drive", "profile files"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a printer with a backup drive beside, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A profile card being saved before a print goes wrong",
            "subject": "baseline profile setup",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "card center, printer behind",
            "text": "SAVE THE GOOD STATE",
            "elements": ["profile card", "settings list", "backup drive"],
            "style": "geometry studio photography",
            "mood": "saved, referenced, stable",
            "prompt": "photograph of a profile settings card being saved beside a printer with a settings list, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Baseline Profile Setup: Save the Good State",
            "title_variations": [
                "How to Make a Baseline Profile",
                "Baseline Profile Printer",
                "Known Good Settings",
                "Profile Backup Guide",
                "Default Profile Setup",
            ],
            "description": "A baseline profile is a saved snapshot of settings that you know print well, captured while the machine is healthy: flow, temperature, speeds, retraction, and the g-code start sequence. When a print goes wrong, the first move is not to retune everything but to compare against the baseline and find the one changed variable. This short fails a print, saves the good state, and shows why troubleshooting needs a reference point.",
            "hashtags": ["#Baseline", "#Profiles", "#3DPrinting", "#Troubleshooting"],
            "seo_keywords": [
                "how to make a baseline profile",
                "baseline profile printer",
                "known good settings",
                "profile backup",
                "default profile setup",
                "compare settings diff",
                "save profile before tuning",
            ],
        },
        "fact_check": [
            "A baseline is a saved snapshot.",
            "It captures the healthy state.",
            "Compare failures to it first.",
            "Find the one changed variable.",
            "Backup before you need it.",
        ],
    },
    {
        "topic": "First-Layer Test Prints",
        "core_question": "Why is the first layer the whole game?",
        "learning_objective": "The viewer understands first-layer tests and what they check.",
        "engineering_summary": "The first layer carries every layer above it: if it squishes unevenly or lets go, the whole print fails hours later. A first-layer test is a quick pad that shows exactly what is off: too high and the lines are round and separated, too low and they are flat and ragged, and just right means smooth and fused. The test takes minutes, not hours, so it is the cheapest insurance in printing. The bed, the nozzle, and the height all meet in that one layer.",
        "real_world_application": "Rapid first-layer pads precede every serious print session.",
        "common_misconceptions": [
            "Leveling is the only factor (height and flow matter too)",
            "One perfect print means done (heat and wear change daily)",
            "The test wastes time (it saves hour-long reprints)",
        ],
        "teaching_strategy": "Print the same pad at three heights and read the differences.",
        "script": "The first layer carries every layer above it: if it squishes unevenly or lets go, the whole print fails hours later. A first-layer test is a quick pad that shows exactly what is off: too high and the lines are round and separated, too low and they are flat and ragged, and just right means smooth and fused. The test takes minutes, not hours, so it is the cheapest insurance in printing. The bed, the nozzle, and the height all meet in that one layer.",
        "text_overlay": [
            "FIRST LAYER CARRIES THE REST",
            "TOO HIGH: ROUND, SEPARATED",
            "TOO LOW: FLAT, RAGGED",
            "MINUTES, NOT HOURS",
        ],
        "scenes": [
            {
                "goal": "Hook: the tall print",
                "teaching_point": "It fails at layer one",
                "shot": "wide shot of a tall print with a peeled base",
                "motion": "camera tilts down to the failed base",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["tall print", "peeled base", "bed"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a tall print with a peeled base, neutral lab lighting, print lab",
            },
            {
                "goal": "Too high",
                "teaching_point": "Round, separated lines",
                "shot": "close-up shot of a test pad with round lines",
                "motion": "light shows gaps between lines",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["round lines", "gaps", "pad"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a test pad with round separated lines, bright task lighting, print lab",
            },
            {
                "goal": "Too low",
                "teaching_point": "Flat, ragged lines",
                "shot": "close-up shot of a test pad with crushed lines",
                "motion": "light rakes the ragged edges",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["flat lines", "ragged edges", "pad"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a test pad with crushed ragged lines, bright task lighting, print lab",
            },
            {
                "goal": "Just right",
                "teaching_point": "Smooth and fused",
                "shot": "close-up shot of a perfect test pad",
                "motion": "lines fuse into one surface",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["smooth lines", "fused pad", "glass-like top"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a perfect fused first-layer test pad, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Cheapest insurance",
                "shot": "wide hero shot of three pads compared on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["three pads", "bed", "comparison row"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of three first-layer pads compared on the bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "Three first-layer pads: round, ragged, and fused",
            "subject": "first-layer test prints",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "three pads in a row",
            "text": "FIRST LAYER CARRIES THE REST",
            "elements": ["test pad", "round lines", "fused pad"],
            "style": "geometry studio photography",
            "mood": "squished, read, insured",
            "prompt": "photograph of three first-layer test pads showing round, ragged, and fused lines on a printer bed, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "First-Layer Test Prints: The Cheapest Insurance",
            "title_variations": [
                "What Is a First Layer Test",
                "First Layer Test Print",
                "Level Test Print",
                "First Layer Height Guide",
                "Calibration Print First Layer",
            ],
            "description": "The first layer carries every layer above it: if it squishes unevenly or lets go, the whole print fails hours later. A first-layer test is a quick pad that shows what is off: too high gives round separated lines, too low gives flat ragged lines, and just right means smooth and fused. It takes minutes, not hours, so it is the cheapest insurance in printing. This short prints the same pad three ways and reads each one.",
            "hashtags": ["#FirstLayer", "#TestPrint", "#Calibration", "#3DPrinting"],
            "seo_keywords": [
                "what is a first layer test",
                "first layer test print",
                "level test print",
                "first layer height",
                "first layer squish",
                "calibration pad",
                "first layer adhesion test",
            ],
        },
        "fact_check": [
            "The first layer carries the rest.",
            "Too high gives separated lines.",
            "Too low gives ragged lines.",
            "Correct height fuses lines.",
            "The test takes minutes, not hours.",
        ],
    },
    {
        "topic": "Flow Calibration",
        "core_question": "Why are your walls thicker or thinner than they should be?",
        "learning_objective": "The viewer understands flow calibration and the extrusion multiplier.",
        "engineering_summary": "Flow is how much filament the extruder pushes, and the machine's default guess can be off: the slicer assumes a filament diameter and gear grip that may not match reality. When flow is too high the walls bulge and the surface gets rough; too low and the walls thin out and gaps appear. Calibration measures the wall with a caliper and adjusts the multiplier until the wall matches the design. The number lands around one hundred percent, and then the surface follows.",
        "real_world_application": "Every roll and every nozzle change can shift the flow multiplier.",
        "common_misconceptions": [
            "Flow is set once (filament and nozzles change it)",
            "Temperature fixes flow (flow is volume, temp is viscosity)",
            "The slicer default is exact (it is a guess per machine)",
        ],
        "teaching_strategy": "Print a hollow cube, measure the wall, and correct the multiplier.",
        "script": "Flow is how much filament the extruder pushes, and the machine's default guess can be off: the slicer assumes a filament diameter and gear grip that may not match reality. When flow is too high the walls bulge and the surface gets rough; too low and the walls thin out and gaps appear. Calibration measures the wall with a caliper and adjusts the multiplier until the wall matches the design. The number lands around one hundred percent, and then the surface follows.",
        "text_overlay": [
            "FLOW IS VOLUME PER MOVE",
            "TOO HIGH: BULGING WALLS",
            "TOO LOW: GAPS",
            "MEASURE, ADJUST, MATCH",
        ],
        "scenes": [
            {
                "goal": "Hook: the bulging wall",
                "teaching_point": "Too much plastic",
                "shot": "close-up shot of a bulging rough wall",
                "motion": "light rakes the lumps",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["bulging wall", "rough surface", "print"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bulging rough wall on a print, bright task lighting, print lab",
            },
            {
                "goal": "The guess",
                "teaching_point": "Defaults are assumptions",
                "shot": "diagram-style shot of filament diameter and gear grip",
                "motion": "two assumptions feed the flow math",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["filament diameter", "gear grip", "flow math"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of flow assumptions, clean engineering visualization on a dark background",
            },
            {
                "goal": "The measure",
                "teaching_point": "Caliper on the wall",
                "shot": "close-up shot of a caliper measuring a printed wall",
                "motion": "jaw closes on the wall",
                "lighting": "bright task light",
                "background": "workbench",
                "objects": ["caliper", "printed wall", "reading"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a caliper measuring a printed wall, bright task lighting, workbench",
            },
            {
                "goal": "The adjust",
                "teaching_point": "Multiplier toward one hundred",
                "shot": "diagram-style shot of the flow multiplier dial",
                "motion": "dial settles near one hundred",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["multiplier dial", "percent mark", "target"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a flow multiplier dial, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "The surface follows",
                "shot": "wide hero shot of a smooth cube beside a caliper",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["smooth cube", "caliper", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a smooth cube beside a caliper, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A caliper measuring a bulging wall with a multiplier dial",
            "subject": "flow calibration",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "caliper center, dial beside",
            "text": "MEASURE, ADJUST, MATCH",
            "elements": ["caliper", "printed wall", "multiplier dial"],
            "style": "geometry studio photography",
            "mood": "measured, corrected, matched",
            "prompt": "photograph of a caliper measuring a printed wall with a flow multiplier dial beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Flow Calibration: Measure, Adjust, Match",
            "title_variations": [
                "How to Calibrate Extrusion Flow",
                "Flow Calibration 3D Printer",
                "Extrusion Multiplier Guide",
                "Calibrate Flow Walls",
                "Flow Test Cube",
            ],
            "description": "Flow is how much filament the extruder pushes, and the machine's default guess can be off because the slicer assumes a filament diameter and gear grip that may not match reality. Too much flow bulges the walls and roughens the surface; too little thins them and opens gaps. Calibration measures the wall with a caliper and adjusts the multiplier until the wall matches the design. This short measures a hollow cube, moves the dial, and follows the surface back to clean.",
            "hashtags": ["#FlowCalibration", "#Extrusion", "#Caliper", "#3DPrinting"],
            "seo_keywords": [
                "how to calibrate extrusion flow",
                "flow calibration printer",
                "extrusion multiplier",
                "calibrate flow walls",
                "flow test cube",
                "wall thickness caliper",
                "under extrusion gap",
            ],
        },
        "fact_check": [
            "Flow is filament volume per move.",
            "Defaults are machine guesses.",
            "Too much flow bulges walls.",
            "Too little flow opens gaps.",
            "Caliper measure drives the multiplier.",
        ],
    },
    {
        "topic": "Manual Mesh Bed Leveling",
        "core_question": "Why level one point when you can level the whole map?",
        "learning_objective": "The viewer understands manual mesh bed leveling.",
        "engineering_summary": "A bed is never perfectly flat, so manual mesh leveling samples the surface at many points and stores a height map, then the printer compensates as the nozzle travels. The three-point level sets the average tilt, but the mesh catches the dips and humps between the corners. You probe the grid by hand or with a sensor, the firmware keeps the map, and the nozzle rides the real surface. Tilt first, mesh second, and every point prints the same.",
        "real_world_application": "Mesh leveling makes the whole bed usable, not just the middle.",
        "common_misconceptions": [
            "One point is enough (the bed bows between corners)",
            "The mesh replaces leveling (the tilt must be set first)",
            "Sensors make it automatic forever (mechanics still drift)",
        ],
        "teaching_strategy": "Probe a bowed bed and show the nozzle following the map.",
        "script": "A bed is never perfectly flat, so manual mesh leveling samples the surface at many points and stores a height map, then the printer compensates as the nozzle travels. The three-point level sets the average tilt, but the mesh catches the dips and humps between the corners. You probe the grid by hand or with a sensor, the firmware keeps the map, and the nozzle rides the real surface. Tilt first, mesh second, and every point prints the same.",
        "text_overlay": [
            "NO BED IS FLAT",
            "SAMPLE THE GRID",
            "NOZZLE RIDES THE MAP",
            "TILT FIRST, MESH SECOND",
        ],
        "scenes": [
            {
                "goal": "Hook: the bowed bed",
                "teaching_point": "Corners differ from center",
                "shot": "wide shot of a bed with a visible bow",
                "motion": "light sweeps the curve",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["bowed bed", "corner dip", "center hump"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bowed printer bed, neutral lab lighting, print lab",
            },
            {
                "goal": "The map",
                "teaching_point": "Probe a grid of points",
                "shot": "diagram-style shot of a grid of probe points",
                "motion": "points light up across the bed",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["grid points", "probe path", "bed outline"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a mesh leveling grid, clean engineering visualization on a dark background",
            },
            {
                "goal": "The map",
                "teaching_point": "Height map stored",
                "shot": "diagram-style shot of a color height map",
                "motion": "colors show dips and humps",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["height map", "dip colors", "hump colors"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of a bed height map, clean engineering visualization on a dark background",
            },
            {
                "goal": "The ride",
                "teaching_point": "Nozzle follows the surface",
                "shot": "medium shot of a nozzle tracing a map over the bed",
                "motion": "head rises and dips with the map",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["nozzle", "bed", "map path"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a nozzle following a mesh map over the bed, neutral lab lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Every point prints the same",
                "shot": "wide hero shot of a flat print across the whole bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["flat print", "whole bed", "grid"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a flat print covering the whole bed, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A probe grid over a bowed bed with a color height map",
            "subject": "manual mesh bed leveling",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "grid center, map beside",
            "text": "NOZZLE RIDES THE MAP",
            "elements": ["probe grid", "bowed bed", "height map"],
            "style": "geometry studio photography",
            "mood": "sampled, mapped, ridden",
            "prompt": "photograph of a probe grid over a bowed bed with a color height map beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Manual Mesh Bed Leveling: The Nozzle Rides the Map",
            "title_variations": [
                "What Is Manual Mesh Leveling",
                "Manual Mesh Bed Leveling",
                "Bed Mesh Guide",
                "Leveling Grid Printer",
                "Probe Bed Surface",
            ],
            "description": "A bed is never perfectly flat, so manual mesh leveling samples the surface at many points and stores a height map, then the printer compensates as the nozzle travels. The three-point level sets the average tilt, but the mesh catches the dips and humps between the corners. This short probes the grid, stores the map, and shows the nozzle riding the real surface, so every point prints the same: tilt first, mesh second.",
            "hashtags": ["#MeshLeveling", "#BedLevel", "#3DPrinting", "#Calibration"],
            "seo_keywords": [
                "what is manual mesh leveling",
                "manual mesh bed leveling",
                "bed mesh guide",
                "leveling grid",
                "probe bed surface",
                "height map printer",
                "mesh vs three point level",
            ],
        },
        "fact_check": [
            "No bed is perfectly flat.",
            "The mesh samples many points.",
            "The firmware stores a map.",
            "The nozzle follows the map.",
            "Tilt must be set before the mesh.",
        ],
    },
    {
        "topic": "Elephant Foot Compensation",
        "core_question": "Why do your prints look like they are wearing clown shoes?",
        "learning_objective": "The viewer understands elephant foot and how to compensate for it.",
        "engineering_summary": "Elephant foot is the flared bulge at the bottom of a print, where the first layers get squished by the nozzle height and bed heat. The nozzle drags through soft plastic, the corners push outward, and the base widens. The slicer fights back with compensation: it offsets the first-layer contour inward so the bulge lands on the design line, and it can lift the nozzle slightly or drop the bed temperature. The goal is a base that matches the walls, not a flare that hides the design.",
        "real_world_application": "Precision-fit parts measure from the base, so the flare must go.",
        "common_misconceptions": [
            "It is only from too-close leveling (bed heat matters too)",
            "Compensation is cheating (it corrects a real physics squeeze)",
            "It only affects looks (it ruins bottom fit and dimension)",
        ],
        "teaching_strategy": "Show the bulge, then the compensated contour matching the wall.",
        "script": "Elephant foot is the flared bulge at the bottom of a print, where the first layers get squished by the nozzle height and bed heat. The nozzle drags through soft plastic, the corners push outward, and the base widens. The slicer fights back with compensation: it offsets the first-layer contour inward so the bulge lands on the design line, and it can lift the nozzle slightly or drop the bed temperature. The goal is a base that matches the walls, not a flare that hides the design.",
        "text_overlay": [
            "HEAT SQUISHES THE BASE",
            "CORNERS PUSH OUT",
            "OFFSET THE CONTOUR INWARD",
            "BASE MATCHES THE WALLS",
        ],
        "scenes": [
            {
                "goal": "Hook: the clown shoe",
                "teaching_point": "Flared base",
                "shot": "close-up shot of a part with a flared bottom",
                "motion": "camera tilts from wall to flare",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["flared base", "part wall", "bulge"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part with a flared elephant foot base, bright task lighting, print lab",
            },
            {
                "goal": "The squish",
                "teaching_point": "Nozzle drag and bed heat",
                "shot": "diagram-style shot of the first layer being squished",
                "motion": "nozzle flattens soft plastic",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["nozzle", "soft base", "squish arrows"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of first-layer squish, clean engineering visualization on a dark background",
            },
            {
                "goal": "The offset",
                "teaching_point": "Contour shifted inward",
                "shot": "diagram-style shot of the compensated contour",
                "motion": "first-layer line moves inside the design line",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["design line", "compensated line", "offset"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of elephant foot compensation offset, clean engineering visualization on a dark background",
            },
            {
                "goal": "The extra levers",
                "teaching_point": "Z lift and cooler bed",
                "shot": "graphic-style shot of compensation options",
                "motion": "offset, z lift, bed temp light up",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["offset option", "z lift option", "bed temp option"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of elephant foot compensation options, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Base matches the walls",
                "shot": "wide hero shot of a straight-sided print on the bed",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["straight print", "clean base", "bed"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a straight-sided print with a clean base, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A flared base with the compensated contour line cutting inward",
            "subject": "elephant foot compensation",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "base center, contour line through",
            "text": "BASE MATCHES THE WALLS",
            "elements": ["flared base", "contour line", "part wall"],
            "style": "geometry studio photography",
            "mood": "flared, offset, matched",
            "prompt": "photograph of a flared print base with a compensated contour line cutting inward and a clean wall, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Elephant Foot Compensation: Base Matches the Walls",
            "title_variations": [
                "How to Fix Elephant Foot",
                "Elephant Foot Compensation",
                "First Layer Bulge Fix",
                "Bottom Flare Print",
                "First Layer Dimension Fix",
            ],
            "description": "Elephant foot is the flared bulge at the bottom of a print, where the first layers get squished by nozzle height and bed heat: the nozzle drags through soft plastic and the corners push outward. The slicer fights back with compensation, offsetting the first-layer contour inward so the bulge lands on the design line, plus a nozzle lift or a cooler bed. This short flares a base, offsets the contour, and matches the walls.",
            "hashtags": ["#ElephantFoot", "#FirstLayer", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "how to fix elephant foot",
                "elephant foot compensation",
                "first layer bulge",
                "bottom flare fix",
                "first layer dimension",
                "compensation offset",
                "bed heat base squish",
            ],
        },
        "fact_check": [
            "Elephant foot is a bottom flare.",
            "Nozzle height and bed heat cause it.",
            "The first layer drags soft plastic.",
            "Compensation offsets the contour.",
            "Z lift and bed temp also help.",
        ],
    },
    {
        "topic": "Bridge Settings",
        "core_question": "How does a printer span a gap with nothing below?",
        "learning_objective": "The viewer understands bridging and how to tune it.",
        "engineering_summary": "A bridge is filament stretched across empty air, and it works by letting the plastic cool and stiffen fast enough to hold its line. The slicer runs bridges at higher speed, cooler temperature, and stronger fan, because a thin fast strand solidifies before it sags. The tuning knobs are bridge speed, bridge fan, and bridge flow: too slow and it sags, too much flow and it droops, just right and the strand snaps straight across. The gap is not a hole in the design; it is a test of cooling.",
        "real_world_application": "Windows, cable channels, and vents all depend on clean bridges.",
        "common_misconceptions": [
            "Bridges need supports (a tuned bridge spans on its own)",
            "Slower is better (slow strands sag from heat)",
            "Bridge settings are global (bridges are separate moves)",
        ],
        "teaching_strategy": "Print a gap at three bridge speeds and watch the sag.",
        "script": "A bridge is filament stretched across empty air, and it works by letting the plastic cool and stiffen fast enough to hold its line. The slicer runs bridges at higher speed, cooler temperature, and stronger fan, because a thin fast strand solidifies before it sags. The tuning knobs are bridge speed, bridge fan, and bridge flow: too slow and it sags, too much flow and it droops, just right and the strand snaps straight across. The gap is not a hole in the design; it is a test of cooling.",
        "text_overlay": [
            "STRAND ACROSS EMPTY AIR",
            "FAST, COOL, STRONG FAN",
            "TOO SLOW SAGS",
            "THE GAP TESTS COOLING",
        ],
        "scenes": [
            {
                "goal": "Hook: the hanging strand",
                "teaching_point": "Filament across nothing",
                "shot": "close-up shot of a bridge printing across a gap",
                "motion": "strand stretches across open air",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["bridge strand", "gap", "nozzle"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a bridge strand printing across a gap, bright task lighting, print lab",
            },
            {
                "goal": "The recipe",
                "teaching_point": "Fast, cool, strong fan",
                "shot": "diagram-style shot of bridge settings",
                "motion": "speed, temp, fan values set",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["bridge speed", "bridge temp", "bridge fan"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of bridge settings, clean engineering visualization on a dark background",
            },
            {
                "goal": "The sag",
                "teaching_point": "Slow strands droop",
                "shot": "close-up shot of a sagging bridge",
                "motion": "strand dips under its own weight",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["sagging strand", "droop curve", "gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a sagging bridge strand, bright task lighting, print lab",
            },
            {
                "goal": "The snap",
                "teaching_point": "Thin strand stiffens",
                "shot": "close-up shot of a straight tight bridge",
                "motion": "strand snaps straight across",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["straight bridge", "tight strand", "clean span"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a straight tight bridge strand, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "A test of cooling",
                "shot": "wide hero shot of a part with clean window bridges",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean bridges", "window part", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a part with clean window bridges, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A strand snapping straight across a gap with bridge setting knobs",
            "subject": "bridge settings",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "strand center, knobs below",
            "text": "THE GAP TESTS COOLING",
            "elements": ["bridge strand", "gap", "setting knobs"],
            "style": "geometry studio photography",
            "mood": "stretched, stiffened, snapped",
            "prompt": "photograph of a bridge strand snapping across a gap with bridge setting knobs and a sagging strand beside, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Bridge Settings: The Gap Tests Cooling",
            "title_variations": [
                "How to Tune Bridging",
                "Bridge Speed Fan Flow",
                "Bridge Stringing Fix",
                "Bridging Settings Guide",
                "Clean Bridges 3D Print",
            ],
            "description": "A bridge is filament stretched across empty air, and it works by letting the plastic cool and stiffen fast enough to hold its line. The slicer runs bridges at higher speed, cooler temperature, and stronger fan, because a thin fast strand solidifies before it sags. The knobs are bridge speed, bridge fan, and bridge flow: too slow sags, too much flow droops. This short spans a gap, cools the strand, and snaps the bridge straight across.",
            "hashtags": ["#Bridging", "#BridgeSettings", "#Cooling", "#3DPrinting"],
            "seo_keywords": [
                "how to tune bridging",
                "bridge speed fan flow",
                "bridge stringing fix",
                "bridging settings",
                "clean bridges print",
                "bridge sag fix",
                "overhang bridge cooling",
            ],
        },
        "fact_check": [
            "A bridge spans empty air.",
            "Fast strands stiffen first.",
            "Strong fan is critical.",
            "Too slow causes sag.",
            "Bridges are a cooling test.",
        ],
    },
    {
        "topic": "Custom Supports",
        "core_question": "Why let the slicer grow a forest when you can plant one tree?",
        "learning_objective": "The viewer understands custom supports and when to use them.",
        "engineering_summary": "Default supports grow everywhere the slicer thinks a surface needs help, which means wasted material, hard-to-remove trees, and scars on the part. Custom supports flip the idea: you paint support only where you want it, or block the auto supports entirely, so the slicer grows a small precise tree exactly under the overhang. Supports go where the surface would fail, and stay off the surfaces you want clean. Auto is a guess; custom is a decision.",
        "real_world_application": "Text faces, mating surfaces, and threaded holes stay clean with custom supports.",
        "common_misconceptions": [
            "More supports are safer (each one leaves a scar)",
            "Supports are automatic perfection (they fail where they touch)",
            "Removal is the problem (placement is the problem)",
        ],
        "teaching_strategy": "Show auto supports everywhere, then paint one tree under the overhang.",
        "script": "Default supports grow everywhere the slicer thinks a surface needs help, which means wasted material, hard-to-remove trees, and scars on the part. Custom supports flip the idea: you paint support only where you want it, or block the auto supports entirely, so the slicer grows a small precise tree exactly under the overhang. Supports go where the surface would fail, and stay off the surfaces you want clean. Auto is a guess; custom is a decision.",
        "text_overlay": [
            "AUTO GROWS EVERYWHERE",
            "PAINT ONLY WHERE NEEDED",
            "SCARS HURT FIT SURFACES",
            "AUTO IS A GUESS",
        ],
        "scenes": [
            {
                "goal": "Hook: the forest",
                "teaching_point": "Support everywhere",
                "shot": "wide shot of a part buried in default supports",
                "motion": "camera pans the support forest",
                "lighting": "neutral lab light",
                "background": "print lab",
                "objects": ["support forest", "buried part", "trees"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of a part buried in default supports, neutral lab lighting, print lab",
            },
            {
                "goal": "The scars",
                "teaching_point": "Touch points leave marks",
                "shot": "close-up shot of support scars on a print face",
                "motion": "light rakes the contact marks",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["support scars", "print face", "contact marks"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of support scars on a print face, bright task lighting, print lab",
            },
            {
                "goal": "The paint",
                "teaching_point": "Paint one tree",
                "shot": "diagram-style shot of painted support regions in the slicer",
                "motion": "brush strokes mark the overhang",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["painted region", "overhang", "brush"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of painting custom supports, clean engineering visualization on a dark background",
            },
            {
                "goal": "The tree",
                "teaching_point": "Small precise support",
                "shot": "close-up shot of a single tree support under an overhang",
                "motion": "one tree grows exactly below",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["single tree", "overhang", "clean face"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a single custom tree support under an overhang, bright task lighting, print lab",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Custom is a decision",
                "shot": "wide hero shot of a clean part beside its removed support",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["clean part", "removed support", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a clean part beside its removed support, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A paint brush placing one tree support under an overhang",
            "subject": "custom supports",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "brush center, tree below",
            "text": "AUTO IS A GUESS",
            "elements": ["paint brush", "tree support", "overhang"],
            "style": "geometry studio photography",
            "mood": "painted, precise, decided",
            "prompt": "photograph of a paint brush placing one tree support under an overhang in a slicer view, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Custom Supports: Auto Is a Guess",
            "title_variations": [
                "How to Add Custom Supports",
                "Custom Supports Slicer",
                "Support Painting Guide",
                "Support Blockers Explained",
                "Manual Supports Placement",
            ],
            "description": "Default supports grow everywhere the slicer thinks a surface needs help, which means wasted material, hard-to-remove trees, and scars on the part. Custom supports flip the idea: paint support only where you want it, or block the auto supports, so the slicer grows a small precise tree exactly under the overhang. This short buries a part in auto supports, paints one tree, and shows how supports go where the surface would fail and stay off the faces you want clean.",
            "hashtags": ["#CustomSupports", "#Supports", "#Slicer", "#3DPrinting"],
            "seo_keywords": [
                "how to add custom supports",
                "custom supports slicer",
                "support painting",
                "support blockers",
                "manual support placement",
                "support scar removal",
                "tree supports overhang",
            ],
        },
        "fact_check": [
            "Auto supports grow everywhere.",
            "Every support touch leaves a scar.",
            "Custom support paints regions.",
            "Blockers stop unwanted supports.",
            "Placement beats removal.",
        ],
    },
    {
        "topic": "Linear Advance",
        "core_question": "Why do corners blob when the printer stops and goes?",
        "learning_objective": "The viewer understands linear advance and the k-factor.",
        "engineering_summary": "When the extruder stops and restarts, pressure in the nozzle lags the motion: it oozes at corners and starves at the restart, so corners blob and ends look hollow. Linear advance fixes the lag by shaping the extrusion pressure: the firmware starts to pressurize before the move begins and releases it before the stop, tuned by a single number called the k-factor. Too low and blobs return, too high and the walls under-extrude. The k-factor is the calibration handshake between motion and flow.",
        "real_world_application": "Marlin and Klipper both implement pressure control as a k-factor.",
        "common_misconceptions": [
            "It is only for fast printers (corners blob at any speed)",
            "It replaces flow calibration (it shapes pressure, not volume)",
            "K-factor is a fixed number (nozzle and filament change it)",
        ],
        "teaching_strategy": "Show corner blobs, then the k-factor ramp fixing the lag.",
        "script": "When the extruder stops and restarts, pressure in the nozzle lags the motion: it oozes at corners and starves at the restart, so corners blob and ends look hollow. Linear advance fixes the lag by shaping the extrusion pressure: the firmware starts to pressurize before the move begins and releases it before the stop, tuned by a single number called the k-factor. Too low and blobs return, too high and the walls under-extrude. The k-factor is the calibration handshake between motion and flow.",
        "text_overlay": [
            "PRESSURE LAGS MOTION",
            "OOZE AT CORNERS",
            "PRESSURIZE BEFORE THE MOVE",
            "K-FACTOR IS THE HANDSHAKE",
        ],
        "scenes": [
            {
                "goal": "Hook: the blobby corner",
                "teaching_point": "Ooze at the stop",
                "shot": "close-up shot of blobbed corners on a print",
                "motion": "camera pans the corner blobs",
                "lighting": "bright task light",
                "background": "print lab",
                "objects": ["corner blobs", "print wall", "ooze"],
                "transition": "cut",
                "duration": 5,
                "prompt": "photograph of corner blobs on a print, bright task lighting, print lab",
            },
            {
                "goal": "The lag",
                "teaching_point": "Pressure lags the move",
                "shot": "diagram-style shot of pressure lagging motion",
                "motion": "motion stops, pressure still flows",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["motion line", "pressure line", "lag gap"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of nozzle pressure lag, clean engineering visualization on a dark background",
            },
            {
                "goal": "The shape",
                "teaching_point": "Pressure shaped like motion",
                "shot": "diagram-style shot of the shaped pressure ramp",
                "motion": "pressure rises before the move starts",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["pressure ramp", "motion line", "shaped curve"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of linear advance pressure shaping, clean engineering visualization on a dark background",
            },
            {
                "goal": "The k-factor",
                "teaching_point": "One number, tuned",
                "shot": "diagram-style shot of k-factor tuning values",
                "motion": "k-values scan and one wins",
                "lighting": "clean viewport light",
                "background": "dark viewport",
                "objects": ["k-factor list", "test values", "winner"],
                "transition": "cut",
                "duration": 6,
                "prompt": "photograph of a diagram of k-factor tuning values, clean engineering visualization on a dark background",
            },
            {
                "goal": "Takeaway",
                "teaching_point": "Motion and flow shake hands",
                "shot": "wide hero shot of a sharp-cornered clean print",
                "motion": "slow orbit",
                "lighting": "studio key with rim",
                "background": "dark lab",
                "objects": ["sharp corners", "clean print", "bench"],
                "transition": "fade",
                "duration": 5,
                "prompt": "studio photograph of a sharp-cornered clean print, dark engineering lab, cinematic key light",
            },
        ],
        "thumbnail": {
            "concept": "A blobbed corner with a shaped pressure ramp and k-factor dial",
            "subject": "linear advance",
            "background": "dark workshop blur",
            "angle": "three quarter view",
            "lighting": "hard key with rim",
            "composition": "corner center, ramp behind",
            "text": "K-FACTOR IS THE HANDSHAKE",
            "elements": ["corner blob", "pressure ramp", "k-factor dial"],
            "style": "geometry studio photography",
            "mood": "lagged, shaped, sharp",
            "prompt": "photograph of a blobbed corner on a printed wall with a shaped pressure ramp and k-factor dial, hard key light with rim, dark workshop, ultra sharp detail",
            "negative_prompt": "fantasy, sci-fi, magic, glowing circuitry, cartoon, illustration, text artifacts, watermark, blurry, low quality, people, hands",
        },
        "seo": {
            "title": "Linear Advance: The K-Factor Handshake",
            "title_variations": [
                "What Is Linear Advance",
                "Linear Advance Explained",
                "K-Factor Tuning",
                "Pressure Advance Guide",
                "Corner Blobs Fix",
            ],
            "description": "When the extruder stops and restarts, pressure in the nozzle lags the motion: it oozes at corners and starves at the restart, so corners blob and ends look hollow. Linear advance fixes the lag by shaping extrusion pressure, pressurizing before the move and releasing before the stop, tuned by a single number called the k-factor. This short blobs a corner, shapes the ramp, and shows the calibration handshake between motion and flow.",
            "hashtags": ["#LinearAdvance", "#KFactor", "#PressureAdvance", "#3DPrinting"],
            "seo_keywords": [
                "what is linear advance",
                "linear advance explained",
                "k-factor tuning",
                "pressure control nozzle",
                "corner blobs fix",
                "extrusion pressure lag",
                "marlin klipper pressure",
            ],
        },
        "fact_check": [
            "Pressure lags motion.",
            "Corners blob at the stop.",
            "Linear advance shapes pressure.",
            "The k-factor tunes it.",
            "Too high under-extrudes walls.",
        ],
    },
]